### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by 9p4** [PrismLauncher/PrismLauncher#10]
### Role

I (want to use) PlaceholderMC

### Suggestion

I want an AUR package (or at least maintain it)

### Benefit

To install PlaceholderMC on Arch (and derivative) computers with a package.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Scrumplex** [comment]
I already claimed all packages on the AUR
They aren't working right now. We need to rename the organization first

**Comment by 9p4** [comment]
I had made the "placeholdermc" aur packages before the rebrand happened, and I got them to compile and run. I can help out with the aur package.

**Comment by molaeiali** [comment]
Is FlatHub package in your control or it's a third-party?
