### ISSUE TITLE
FTB Skies 1.0.6 does not load in Prism Launcher

### ISSUE THREAD

**Issue by admiral0** [PrismLauncher/PrismLauncher#1000]
### Operating System

Fedora 37

### Version of Prism Launcher

Prism Launcher 6.3 from Flathub on Fedora

### Version of Qt

This program uses Qt version 5.15.9.

### Description of bug

FTB Skies modpack 1.0.6 does not start after a fresh install. 

### Steps to reproduce

* Install FTB  Skies 1.0.6
* Download manually [BeeFix](https://mediafilez.forgecdn.net/files/4203/419/BeeFix-1.19-1.0.7.jar) as asked (download autodetected)
* Launch modpack

### Suspected cause

Succeds to load in FTB app. Some files are missing and kubejs mod fails at startup. There's a [related issue](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2906) in the FTB tracker but from reports it seems the modpack is loading fine in MultiMC as well, so it most likely is specific just to PrismLauncher.

Diff (files generated with `find . | sort` in mc dir) with modpack constructed by FTB App:
```shell
◆ ~ ❯❯❯ diff good_modpack.txt bad_modpack.txt
```
```diff
181,182d180
< ./config/ftbpc-client.snbt
< ./config/ftbpc-common.snbt
230,231d227
< ./config/ftbsba-common.toml
< ./config/ftbteamdimensions-client.toml
241,242d236
< ./config/Hexerei-client.toml
< ./config/Hexerei-common.toml
284d277
< ./config/jade/jade.json
412d404
< ./config/moreoverlays.toml
426d417
< ./config/petrock-common.toml
437a429
> ./config/rftoolsstorage-client-1.toml.bak
509a502,505
> ./coremods
> ./crash-reports
> ./crash-reports/crash-2023-04-16_18.17.54-fml.txt
> ./crash-reports/crash-2023-04-16_20.24.20-fml.txt
589d584
< ./fancymenu_data/default_scale_set.fm
598,599c593
< ./folder.jpg
< ./instance.json
---
> ./icon.png
1180d1173
< ./log4jfixer.jar
1182c1175,1176
< ./logs/console.log
---
> ./logs/2023-04-16-1.log.gz
> ./logs/debug-1.log.gz
1189a1184,1185
> ./logs/minetogether/2023-04-16-1.log.gz
> ./logs/minetogether/debug-1.log.gz
1193d1188
< ./mods/accelerated-decay-forge-1.0.0+mc1.19.2.jar
1204d1198
< ./mods/antiblocksrechiseled-0.1.7.jar
1320d1313
< ./mods/ftb-pack-companion-2.0.3-build.8+mc1.19.2.jar
1323,1324d1315
< ./mods/ftb-skyblock-addons-1.0.0+mc1.19.2.jar
< ./mods/ftb-team-dimensions-1.0.1-build.3.jar
1335d1325
< ./mods/hexerei-0.3.0.jar
1361d1350
< ./mods/kube-utils-forge-1.0.2+mc1.19.2.jar
1386d1374
< ./mods/moreoverlays-1.21.5-mc1.19.2.jar
1404d1391
< ./mods/petrock-0.11.14.jar
1504a1492,1493
> ./screenshots
> ./server-resource-packs
1507c1496
< ./version.json
---
> ./texturepacks
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
Can you attach a Prism launcher client log that contains prism attempting to install the pack?

**Comment by Hawk-v3** [comment]
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/11522651/PrismLauncher-0.log)

This one's a download list. The second is a launch log.
[debug.log](https://github.com/PrismLauncher/PrismLauncher/files/11522662/debug.log)
[latest.log](https://github.com/PrismLauncher/PrismLauncher/files/11522663/latest.log)

It did appear to launch correctly this time- Not sure what's going on with that because I had problems before, hence finding this bug report?

**Comment by Ryex** [comment]
It looks like you didn't download *all* the blocked mods last time but did this time.

Also, as FTB support has now been removed at the request of FTB we won't be able to look into this further.

**Comment by TheKodeToad** [comment]
While FTB App import should be available at some point, i don't believe this issue will still happen
