### ISSUE TITLE
Launcher crashes when scrolling download mods on the curseforge tab too fast.

### ISSUE THREAD

**Issue by StarlessKnights** [PrismLauncher/PrismLauncher#1002]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.3.0

### Description of bug

Scrolling on the curseforge tab on the download mods window causes the launcher to crash.

### Steps to reproduce

Go to the download mods screen (I did this on fabric)
Go to curseforge tab
Scroll really fast
Crash!

### Suspected cause

I feel like the api for getting the curseforge available mods is not able to keep up with the fast scrolling causing the api to return corrupted values causing the launcher to crash.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Revvilo** [comment]
I just wanted to add that this also affects the modrinth modlist.
I've found the easiest way to reproduce the error is rapidly scrolling up and down over and over, with the down stroke being bigger to reach the bottom each time.

I've triggered the crash multiple times and the recurring theme in the logs is that the Search NetJob is invoked twice simultaneously. From what I can see that consistently correlates with a crash.

```
    10.337 D | Task "NetJob(Modrinth::Search)" starting for the first time
    10.337 D | Task "NetJob(Modrinth::Search)" starting for the first time
```

**Comment by NicoTheCinderace** [comment]
I have the same issue.

**Comment by Gabryelcz** [comment]
I would like to comfirm that this issue is happening to me too.
On OS: Windows 
Both CurseForge and Modrinth

**Comment by TayouVR** [comment]
this got fixed somewhere along the way to 7.0
I couldn't pinpoint a specific PR, but its probably the one related to tasks.

**Comment by FreeFull** [comment]
I've just experienced this crash, although it seems it's a lot harder to make it happen in 7.0 compared to 6.3. I've got a full backtrace here:
https://gist.github.com/FreeFull/4b01c0c7a99391c4d8926fc32d157edd

I'm on Arch Linux, with Prism Launcher 7.0, and Qt 6.5.1

**Comment by Revvilo** [comment]
This also occurs when searching for mods and clicking the other provider's tab. Might be a different issue tho.
