### ISSUE TITLE
Instance crashes on launch

### ISSUE THREAD

**Issue by Stellini101** [PrismLauncher/PrismLauncher#1003]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.4.2

### Description of bug

Launched instance crashed instantly
Log:
Couldn't extract native jar 'C:/Users/-/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar' to destination 'C:/Users/-/AppData/Roaming/PrismLauncher/instances/Enigmatica 2 Expert Unofficial - E2Eu/natives'
Couldn't extract native jar 'C:/Users/-/AppData/Roaming/PrismLauncher/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar' to destination 'C:/Users/-/AppData/Roaming/PrismLauncher/instances/Enigmatica 2 Expert Unofficial - E2Eu/natives'

### Steps to reproduce

idk sorry

### Suspected cause

The game freezed and I force quit it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Rags56** [comment]
Hi! could you provide some more information as to what steps you went through to try and fix this? one common reason this specific issue occurs is because of a java process that doesn't shutdown properly, could you try restarting your system then launching the instance?

**Comment by Scrumplex** [comment]
Probably https://github.com/MultiMC/Launcher/issues/2098

**Comment by Rags56** [comment]
we can probably close this issue then

**Comment by Trial97** [comment]
As no more information is provided I will presume that this is solved.
Feel free to reopen it
