### ISSUE TITLE
Scrolling Through Modrinth Recently Updated Mod List Crashes Prism Launcher

### ISSUE THREAD

**Issue by eithli** [PrismLauncher/PrismLauncher#1006]
### Operating System

Windows

### Version of Prism Launcher

6.3

### Version of Qt

6.4.2

### Description of bug

Pretty self-explanatory; the Prism Launcher completely crashes when trying to download a mod onto an instance while scrolling through the Modrinth recently updated mod list.

### Steps to reproduce

* Launch Prism Launcher.
* Go to Mod List for Recently Updated Mods.
* Observe the Crash.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by eithli** [comment]
**UPDATE:** This seems to happen at random, as I cannot replicate the issue consistently.

**Comment by CassieRoseZA** [comment]
Can confirm i get this also

**Comment by TayouVR** [comment]
this got fixed somewhere along the way to 7.0
I couldn't pinpoint a specific PR, but its probably the one related to tasks.
