### ISSUE TITLE
mod platform column

### ISSUE THREAD

**Issue by ColonelGerdauf** [PrismLauncher/PrismLauncher#1020]
### Role

I have instances with large lists of mods.

### Suggestion

Add a column in the mods table to show what platform each mod is linked to.

### Benefit

This can make it easier for people to look up the mods, and switch the mods between platforms.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

There are three/four categories I can think of:

- Modrinth
- Curseforge
- GitHub
- manual (or "other")

GitHub is a possible option though I am not too sure how this is to be implemented on the mod maker perspective. Curseforge is not only slow with its API, but is currently facing PR issues. People would appreciate an easy way to identify CF mods to switch them to Modrith in their own discretion.

**Comment by Ryex** [comment]
Mods are not fundimentaly linked to a mod provider. so far as prism is concerend it's just a file on your system. we build an index of the pack by querying the mod platforms for has of the files.
all a user has to do is select the prefered platform when updating for the first time.

**Comment by ColonelGerdauf** [comment]
It is included in Prism 7.0, so this request is now redundant
