### ISSUE TITLE
Pre-package JRE's

### ISSUE THREAD

**Issue by ColonelGerdauf** [PrismLauncher/PrismLauncher#1021]
### Role

I run both modern (1.18 and beyond) and legacy (1.12 and 1.16) version instances.

### Suggestion

have the Prism packages come packaged with the needed Java runtimes as sandboxes.

### Benefit

Simple QOL; reduce need to manually configure Java version across versions.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Looking at the supported platforms and version recommendations, there should be little issue with doing this. Just have a `prismlauncher/java` directory set up, where the appropriate versions can be loaded up for before and after 1.16.5. The only caveat that I can see is with M1-class Macs, which lack a Java 8 JRE. The next best in that situation is Java 11.

Then Prism can be coded to do the loading and 1.16 switching when a manual Java version is not defined. The setting for java path can have the manual URL,  `javaw`, or `auto` which would do what is suggested here.

As a side note, this can also improve compatibility with enclosed environments like [Window Store](https://github.com/PrismLauncher/PrismLauncher/issues/995).

**Comment by TheKodeToad** [comment]
I think this is already a thing on Flatpak?

**Comment by ColonelGerdauf** [comment]
Okay, and why is this not the norm? Why does it require the restrictions of flatpaks to justify sandboxing JRE's?

There are many reasons why people prefer not to have an installed JRE/JDK

**Comment by Ryex** [comment]
it's not a think on flatpak.

Also, duplicate multiple times over #335 #442 #734 #789 #762
initial work was being done in  #285

**Comment by ColonelGerdauf** [comment]
Those were about internal downloading and automatic switching. Fair enough with the latter, but I am seeking for JREs to be included from the get-go. Java allows for the running of portable or sandboxed runtimes.

The specificity of this suggestion is to widen the use case for Prism. Not everybody has the time to go download additional things on to an install. In fact, such might raise security and integrity questions. Expanding Prism to general audiences is never an issue, so long as the scope is understood in good faith.

Doing it this way, a player can easily switch between 1.12 and 1.18, without worrying about what is compatible with which runtimes. The option exist for experienced users who want to get something specialized in non-conventional versions, or wish to test specific differences in implementations, such as OpenJ9 or Graal. That is not something people should touch otherwise.

**Comment by Scrumplex** [comment]
What platform are you on? For Linux both Flatpak and AppImage already come with bundled JREs. For native Linux packages users should rely on distro packages.

**Comment by ColonelGerdauf** [comment]
Windows (x64)

**Comment by Scrumplex** [comment]
I wouldn't say that always shipping our own runtime is a good idea, as some people might prefer managing this by themselves (i.e. through a package manager like Scoop, WinGet or Chocolatey)

**Comment by ColonelGerdauf** [comment]
With both Windows and OSX, when you ask a program to run from "default" runtimes, it looks for which ones are installed; ProgFiles/Applications, Registry and all.

In the casual environment as well as a number of circles, the installation of Java is very strongly discouraged, which in this case would leave users to manually download portable JRE's and configure the runtime per instance on Prism. That is quite burdensome for people.

"Some people might prefer managing..." Well, that is what the manual config for runtime is for, isn't it? I never asked to hard-lock the runtimes. All I am asking is to provide an `auto` option where things can be handled internally. Again, for normal users, the preference is strong for things to be managed internally. This is not a shuttle rocket where fine precision and awareness of overflows is required. This is a game launcher, intended to be used by just about anyone.

**Comment by ColonelGerdauf** [comment]
I should add that the multiple suggested JRE's makes the installation of Java less than ideal, and we would be right back at square one. Distinguishing between two installed JRE's is something that has to be done manually, which can be a bit painful for those not familiar to the Windows install paths, or in particular what the needed executable is and where it is in relation to the installation folder(s).

There is simply no way for Windows to host two installations of Java. Once you install a newer/older version, both the Path and Registry defaults get overriden from the previous install.

**Comment by Ryex** [comment]
> There is simply no way for Windows to host two installations of Java. Once you install a newer/older version, both the Path and Registry defaults get overriden from the previous install.

Which is why Prism manually searches in the common install paths to find all installed versions even if they arn't "registered" in the windows path.

but again. the ideal solution is not to package java with prism but to have prism acquire the correct java for the Minecraft instance.

**Comment by ColonelGerdauf** [comment]
No. I have tested this by installing Java 8 alongside Java 17. The overriding of path still happens, as when I launch Prism again, I get notified that I no longer have a valid 17 JRE. That is despite the fact that all of my instances are manually configured already with sandboxed JRE's.

What that tells me is that the launcher is checking the `javaw` parameter, which exclusively relies on the path variable, as that is what it is. Such path is now version 8. This automatic lookup of compatible JRE does not exist, and nothing I do would ever allow such mechanism to function "as intended".

There is no "smart select" option in the list. It is either "Javaw" which is strictly defined to one version at any one time, or a fully manual configuration.

**Comment by ColonelGerdauf** [comment]
And I must repeat that installation of Java is a no-no regardless. I am not too sure how it is in Linux, but for Windows and especially OSX, Java is considered a "Boomer computer thing" much in the same line as Adobe Flash, and if you tell anyone that Java has any use at all outside of Minecraft, it will invite confused feedback from them.

And that is just for the joes and people partially informed about computers. Those who are more in depth with programming and computing, tend to be quite cynical about the fact that Java has any use at all. They despise both the JRE/JDK and how they work, and also the inherit limitations and potential of problems of the Java language.

**Comment by lirtistan** [comment]
Hi,

i just stumbled over this issue, because i have trouble running older mods like "Skyfactory 4" which obviously need a old JRE to run (but not available/bundled inside flatpak). 

Does that mean we become a Java installer integrated into PrismLauncher?

**Comment by Trial97** [comment]
Yes there will be a java installer integrated in PrismLauncher.
But it will not install it globally (only for Prismlauncher)

**Comment by lirtistan** [comment]
Sure, i didn't expect a global install.

Nice move ❤️ , can't await to play other mods on SD.
