### ISSUE TITLE
Mangohud not detected in flatpak

### ISSUE THREAD

**Issue by MithicSpirit** [PrismLauncher/PrismLauncher#1024]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 5.15.9

### Description of bug

Prismlauncher does not recognize MangoHud under flatpak, even if the MangoHud flatpak (ref `runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/22.08`) is installed.

### Steps to reproduce

- Install Prismlauncher through flatpak
- Install MangoHud through flatpak
- Open Prismlauncher
- Open settings
- MangoHud option is greyed out

### Suspected cause

Looking through the flatpak environment at runtime (with `flatpak enter org.prismlauncher.PrismLauncher bash`) it seems like MangoHud is installed to `/usr/lib/extensions/vulkan/share/vulkan/implicit_layer.d/`. However, cross-referencing this with https://github.com/PrismLauncher/PrismLauncher/blob/8dc3267925537d58a1e9418863b78e4cc55bd1c1/launcher/MangoHud.cpp, it seems like that path is not checked. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Bitwolfies** [comment]
Can confirm, its greyed out. You can still use mangohud --dlsym as a wrapper command and it will work, but the button is grey.

**Comment by Scrumplex** [comment]
This is probably #963

Fixed in the upcoming 7.0 release
