### ISSUE TITLE
Build failes with JDK 20

### ISSUE THREAD

**Issue by edgars-cirulis** [PrismLauncher/PrismLauncher#1026]
### Operating System

Linux

### Version of Prism Launcher

git/develop

### Version of Qt

5.15.9

### Description of bug

Failes to build with JDK 20

➜  PrismLauncher git:(develop)  cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DENABLE_LTO=ON -DLauncher_BUILD_PLATFORM=Linux -DLauncher_QT_VERSION_MAJOR=5 -G Ninja
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IPO / LTO enabled
-- Git commit: 8dc3267925537d58a1e9418863b78e4cc55bd1c1
-- Git tag: -128-NOTFOUND
-- Git refspec: refs/heads/develop
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Checking for one of the modules 'scdoc'
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found Java: /usr/bin/java (found suitable version "20.0.1", minimum required is "1.7") found components: Development 
-- Using system zlib
-- Using system QuaZip
-- Using system tomlplusplus
-- Using system cmark
-- Using system ghc_filesystem
-- Configuring done (2.4s)
-- Generating done (0.1s)
-- Build files have been written to: /home/edgars/PrismLauncher/build
➜  PrismLauncher git:(develop) cmake --build build
[13/555] Building Java objects for NewLaunch.jar
FAILED: libraries/launcher/CMakeFiles/NewLaunch.dir/java_compiled_NewLaunch /home/edgars/PrismLauncher/build/libraries/launcher/CMakeFiles/NewLaunch.dir/java_compiled_NewLaunch 
cd /home/edgars/PrismLauncher/libraries/launcher && /usr/bin/cmake -DCMAKE_JAVA_CLASS_OUTPUT_PATH=/home/edgars/PrismLauncher/build/libraries/launcher/CMakeFiles/NewLaunch.dir -DCMAKE_JAR_CLASSES_PREFIX= -P /usr/share/cmake/Modules/UseJava/ClearClassFiles.cmake && /usr/bin/javac -target 7 -source 7 -classpath :/home/edgars/PrismLauncher/libraries/launcher:/home/edgars/PrismLauncher/build/jars -d /home/edgars/PrismLauncher/build/libraries/launcher/CMakeFiles/NewLaunch.dir @/home/edgars/PrismLauncher/build/libraries/launcher/CMakeFiles/NewLaunch.dir/java_sources && /usr/bin/cmake -E touch /home/edgars/PrismLauncher/build/libraries/launcher/CMakeFiles/NewLaunch.dir/java_compiled_NewLaunch
[0.021s][warning][cds] A jar file is not the one used while building the shared archive file: /usr/lib/jvm/java-20-openjdk/lib/modules
[0.021s][warning][cds] /usr/lib/jvm/java-20-openjdk/lib/modules timestamp has changed.
warning: [options] bootstrap class path not set in conjunction with -source 7
error: Source option 7 is no longer supported. Use 8 or later.
error: Target option 7 is no longer supported. Use 8 or later.
[14/555] Building Java objects for JavaCheck.jar
FAILED: libraries/javacheck/CMakeFiles/JavaCheck.dir/java_compiled_JavaCheck /home/edgars/PrismLauncher/build/libraries/javacheck/CMakeFiles/JavaCheck.dir/java_compiled_JavaCheck 
cd /home/edgars/PrismLauncher/libraries/javacheck && /usr/bin/cmake -DCMAKE_JAVA_CLASS_OUTPUT_PATH=/home/edgars/PrismLauncher/build/libraries/javacheck/CMakeFiles/JavaCheck.dir -DCMAKE_JAR_CLASSES_PREFIX= -P /usr/share/cmake/Modules/UseJava/ClearClassFiles.cmake && /usr/bin/javac -target 7 -source 7 -Xlint:deprecation -Xlint:unchecked -classpath :/home/edgars/PrismLauncher/libraries/javacheck:/home/edgars/PrismLauncher/build/jars -d /home/edgars/PrismLauncher/build/libraries/javacheck/CMakeFiles/JavaCheck.dir @/home/edgars/PrismLauncher/build/libraries/javacheck/CMakeFiles/JavaCheck.dir/java_sources && /usr/bin/cmake -E touch /home/edgars/PrismLauncher/build/libraries/javacheck/CMakeFiles/JavaCheck.dir/java_compiled_JavaCheck
[0.010s][warning][cds] A jar file is not the one used while building the shared archive file: /usr/lib/jvm/java-20-openjdk/lib/modules
[0.010s][warning][cds] /usr/lib/jvm/java-20-openjdk/lib/modules timestamp has changed.
warning: [options] bootstrap class path not set in conjunction with -source 7
error: Source option 7 is no longer supported. Use 8 or later.
error: Target option 7 is no longer supported. Use 8 or later.
[22/555] Building CXX object libraries/systeminfo/CMakeFiles/systeminfo.dir/src/distroutils.cpp.o
ninja: build stopped: subcommand failed.

### Steps to reproduce

Build with JDK 20

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
See #1013
Java 20 deprecated java 7 binary compat, but we have to keep it for getting old MC to work
