### ISSUE TITLE
Customize Font

### ISSUE THREAD

**Issue by JawboTau** [PrismLauncher/PrismLauncher#1033]
### Role

The text on my screen is very small in prism launcher, especially in logs. This is made worse by my visual impairments.

### Suggestion

I want prism launcher to allow the user to change the font size

### Benefit

This will improve prism launcher's accessibility

### This suggestion is unique

- [ ] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This will benefit those with small or far away monitors, and those with visual impairments; especially those that are older.

**Comment by JawboTau** [comment]
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/268 and https://github.com/PrismLauncher/PrismLauncher/issues/475

**Comment by Ryex** [comment]
Do the font setting under
Settings > Launcher > Console > Console Font  at least help with logs for you? or do you need something more?

**Comment by ColonelGerdauf** [comment]
I think they are referring to the font of the UI pages, including menu items, instance names, lists inside of an instance, etc

**Comment by adventuretc** [comment]
I would find this option useful (and necessary). For the whole GUI.

**Comment by PioneersProd** [comment]
Developers who insist on tiny font interfaces have been to Epstein island
