### ISSUE TITLE
Minecraft Fullscreen OFFSET

### ISSUE THREAD

**Issue by Iwo24pl** [PrismLauncher/PrismLauncher#1039]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.4.2

### Description of bug

When I started Minecraft via official launcher, fullscreen worked as expected, but via Prism Launcher when I turn on fullscreen it's offset: 
![image](https://user-images.githubusercontent.com/70712002/234867621-f943a7a1-3a9a-46cf-80b1-ad5f4e8d7281.png)

### Steps to reproduce

* Install some mods.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Iwo24pl** [comment]
It's mods error.

**Comment by PeliZxD** [comment]
https://www.reddit.com/r/PrismLauncher/comments/yq0fdg/fullscreen_zoomed_in_and_off_center/ 
Here, that worked for me. Hope it helps too!
@Iwo24pl
