### ISSUE TITLE
Copying an instance doesn't hide .index folder

### ISSUE THREAD

**Issue by RuiNtD** [PrismLauncher/PrismLauncher#104]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.0-develop 2ebaf460957edfdd286da426b4a754219149c159

### Version of Qt

Qt 6.4.0

### Description of bug

Copying an instance doesn't hide the `.index` folder in the OS, causing it to appear in the Mods menu.

### Steps to reproduce

- Create an instance with a mod loader
- Download a mod using PolyMC's mod downloader
- Ensure there's a hidden .index folder in the instance's mod folder
- Click Copy Instance in PolyMC and copy the instance
- Check the mods menu on the new instance
- Notice how the .index folder is visible
- Check the instance's mod folder
- Notice how the .index folder is visible

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by villainous-j** [comment]
worth mentioning for anyone looking here that the workaround is to set the .index folder as 'hidden' using the properties of Windows Explorer.

**Comment by ColonelGerdauf** [comment]
I think a Windows-specific solution could include doing a full copy of files
The CMD equivalent would be `robocopy /e /j /copyall /sl /sj`

Or, otherwise it could more simply double-check and reapply the hidden folder property for .index.
