### ISSUE TITLE
Redirect curseforge link to modrinth

### ISSUE THREAD

**Issue by barraIhsan** [PrismLauncher/PrismLauncher#1045]
### Role

I play modded Minecraft

### Suggestion

I want mods downloaded using modrinth

### Benefit

fixes dead link

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

So as you know, some mods like Sodium, Iris, and also ModMenu has recently moved from curseforge to modrinth. But, there is still some curseforge mod pack that link to their curseforge link. And sometimes the link is dead.

So when a modpack requires, for example `sodium-fabric-mc1.19.2-0.4.4+build.18.jar` from curseforge, just redirect it to modrinth download that has the exact file name on it.

**Comment by Scrumplex** [comment]
I don't think this in scope for Prism Launcher. Modpacks should just fix this themselves.

**Comment by Trial97** [comment]
Not a prism issue
