### ISSUE TITLE
Icons aren't being rendered in a portable build

### ISSUE THREAD

**Issue by lovelymono** [PrismLauncher/PrismLauncher#1048]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.0-develop, commit ae75585b52078ca6d89b4014668c08d9aea4a17b

### Version of Qt

Qt 6.5.0

### Description of bug

Most of menu and instance icons aren't being rendered. Other icon sets don't work at all.

![20230430_14h06m15s_grim](https://user-images.githubusercontent.com/99364286/235352124-9623372f-61a0-4564-a093-e4b0ad18a5e0.png)
![20230430_14h06m49s_grim](https://user-images.githubusercontent.com/99364286/235352125-defe32bb-b9db-4137-8c4f-8f1af1a32906.png)
![20230430_14h12m04s_grim](https://user-images.githubusercontent.com/99364286/235352279-effe8d10-4e7f-44f8-91ed-377f7e39a74a.png)
![20230430_14h14m26s_grim](https://user-images.githubusercontent.com/99364286/235352387-e909ef81-3d32-43b7-882f-89ec2c80ff4d.png)

### Steps to reproduce

* Compile and install a portable build following the instructions
* Start Prism Launcher
* Icons aren't being rendered

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
You probably need Qt SVG.

Name of the exact package depends on your distro ofc.

**Comment by lovelymono** [comment]
Right, installing `qt6-svg` fixed that. Thanks!

I'm surprised that Qt SVG is not a hard dependency, or at least it doesn't print a warning when building without it available.

The [Build Instructions](https://prismlauncher.org/wiki/development/build-instructions/) page also doesn't mention a dependency on it. It mentions `libqt5gui5` for Qt 5 which pulls it in, and while there's a similar package for Qt 6, `libqt6gui6`, it doesn't depend on `libqt6svg6` like the Qt 5 equivalent. None of the other listed packages for Qt 6 build depend on `libqt6svg6` either, at least from what I can see on the Debian Packages.
