### ISSUE TITLE
Launch Instances Offline From Command Line `-o <name>`

### ISSUE THREAD

**Issue by Jazztache** [PrismLauncher/PrismLauncher#1059]
### Role

I play modded Minecraft, with a custom setup that allows me to play local co-op without an internet connection.

### Suggestion

Add in a launch flag for launching instances offline. Using `-l <instance> -o <name> `as a way of launching offline instances with a specific name.

### Benefit

This is so you can do offline LAN games, or quickly spin up offline instances for pure singleplayer.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This is specifically good for quickly spinning up offline instances. There is a really important use case for this as well.

Using a tiling window manager (or Bismuth on KDE), turning off 'pause on unfocus' in the minecraft config, creating a controller-modded instance for each player, and launching the seperate instances in offline mode, you can have offline splitscreen LAN minecraft.

For everything above, it's scriptable using Bash. Find and replace on text files for configs in both Minecraft and WMs, copying instances and duplicating them, and launching instances... *but not in offline mode*. You have to use the GUI for this, which makes scripting this setup impossible.

I believe that adding the -o flag would be very helpful, especially because if you want to test on a server offline, you can do this:

```
prismlauncher -l Offline1 -o OfflinePlayerOne -s localhost
prismlauncher -l Offline2 -o OfflinePlayerTwo -s localhost
```

**Comment by eff3ry** [comment]
you can create offline profiles/accounts in the launcher first and then launch with `--profile "<profile>"` to open an offline game

**Comment by Jazztache** [comment]
Does --profile always launch in offline mode?

**Comment by Jazztache** [comment]
I am not sure this would work.
This would require 8 offline profiles if we wanted to play with 8 players locally offline, so this would not be scaling up, especially if I have to manually create each account.

On top of that, creating all of the offline users using a script (if even possible) would pollute the account list, and users/accounts aren't easily group-able like the instances.

Is there a way to launch offline without previously creating an offline account? This would be much better for the use case described above.
