### ISSUE TITLE
More PolyMC brandings in PrismLauncher and Issue Templates

### ISSUE THREAD

**Issue by nesper8** [PrismLauncher/PrismLauncher#106]
### Operating System

Linux

### Version of PolyMC

PrismLauncher 5.0-develop (commit: 325e58d98c26fb802956de75e8ddfcfe0d9e3782)

### Version of Qt

Qt 6.3.1

### Description of bug

There is still a lot of PolyMC branding in the app
Such as in the settings
![image](https://user-images.githubusercontent.com/57890520/196617391-3650ce08-f560-4ab3-a975-ad91880ee9be.png)

In the news section
![image](https://user-images.githubusercontent.com/57890520/196617792-aa3f597c-44fa-4651-a374-990d39a7b353.png)

In the About section
![image](https://user-images.githubusercontent.com/57890520/196617918-a0e11bd1-d7b7-4e28-9c88-8eece3e704ef.png)

There are also some PolyMC brandings in this issue template too
Such as here
![image](https://user-images.githubusercontent.com/57890520/196618157-b6395857-042e-4eed-8dcd-9d08873569e2.png)

here
![image](https://user-images.githubusercontent.com/57890520/196618298-9b914af7-fc2e-4796-a51d-55840898e8f4.png)

and also here
![image](https://user-images.githubusercontent.com/57890520/196618373-a18189d1-049a-4588-b0c4-68e12eaa28f3.png)

### Steps to reproduce

Filled in Bug Description

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Evrey** [comment]
Also the favicon of the website.

**Comment by tobimori** [comment]
This is adressed in #92

**Comment by nesper8** [comment]
The logos are changed in commit: 0691a77a402db47dffd831bb77cda9d221bab066
But launcher still shows news from PolyMC

**Comment by MenacingPerson** [comment]
I think it's all fixed, except news

**Comment by RuiNtD** [comment]
Everything seems to be fixed in 5.0

> But launcher still shows news from PolyMC

> I think it's all fixed, except news

News lists all the PolyMC news, as well as news on the latest Prism Launcher release. If they wanted to remove all the PolyMC news, they would've done so by now. I believe it's intentional.

> Also the favicon of the website.

The website still needs some work.

**Comment by flowln** [comment]
I think everything here has been taken care of, the news we'll probably keep around, maybe with something to distinguish the old ones from the new ones. closing this then :)

**Comment by nesper8** [comment]
Thank you
