### ISSUE TITLE
Account Selection setting for instances

### ISSUE THREAD

**Issue by SmilerRyan** [PrismLauncher/PrismLauncher#1060]
### Role

I play minecraft with multiple accounts.

### Suggestion

I want Prism Launcher to allow me to automatically select an account to use in an instance's settings.

### Benefit

So that I can more easily open an instance with the correct account.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

In my case, I have multiple offline accounts and one instance for each account that I need to start up.
Currently I would have to select an account, and then launch the instance for that specific account, in the right order.

I'd like it if in an instance's settings I could select an account to use for each instance.
Not only does this save time when launching multiple instances, it makes sure you don't use the wrong account.

Presumably if the account is not ready or has been removed after launching an instance, it will tell you beforehand.

![image](https://user-images.githubusercontent.com/14893385/236602899-83e9f4c4-ac14-4a62-835a-33f2d08fccda.png)

**Comment by leia-uwu** [comment]
that was already done in #685

**Comment by SmilerRyan** [comment]
Thanks for the update, not sure why I can't seem to see this option on the latest release (6.3).
![image](https://user-images.githubusercontent.com/14893385/236606266-9f04609e-2150-4304-a68b-20feaa4dc2e3.png)

**Comment by leia-uwu** [comment]
its coming in 7.0

**Comment by leia-uwu** [comment]
(next release)
