### ISSUE TITLE
cannot launch mc with mods

### ISSUE THREAD

**Issue by JustLok** [PrismLauncher/PrismLauncher#1062]
### Operating System

Windows

### Version of Prism Launcher

prism launcher 7.0-develop

### Version of Qt

This program uses Qt version 6.4.0.

### Description of bug

i cannot launch mc version 16.5 with java 17 because  of different java requirement
![minecraftpng](https://user-images.githubusercontent.com/128099086/236783864-0f0a2c7b-3d43-415c-9f2c-0c8b95a5ac4c.png)
but when i get to java 8 it gives me this error which i assume means that it's not compatible with some of the mods i have even tho my friend played the same mod pack with no problems
![kfdskljfksd](https://user-images.githubusercontent.com/128099086/236784272-ab00244c-de1f-4a69-adfb-be43b7635b2d.png)

### Steps to reproduce

.

### Suspected cause

i have no clue honestly 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
update the forge version. old verison of forge are incompatable with new versions of java 8

**Comment by ghost** [comment]
Update Forge

**Comment by Trial97** [comment]
Closing this as complete.
