### ISSUE TITLE
Unable to launch my modpack

### ISSUE THREAD

**Issue by VoiDzzx** [PrismLauncher/PrismLauncher#1068]
### Operating System

Windows 10

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.4.2

### Description of bug

I got Prism set up this morning and wanted to make a small modpack to play, but whenever I try to launch, it crashes and I have NO idea how to read the crash log. I've attached all the red text in the report here:
![Screenshot 2023-05-10 124323](https://github.com/PrismLauncher/PrismLauncher/assets/133137855/ebc2b718-b991-4b39-9db9-64dbaad41758)
![Screenshot 2023-05-10 124351](https://github.com/PrismLauncher/PrismLauncher/assets/133137855/0416a4cc-d78f-42dd-b930-4d396feebd0a)
![Screenshot 2023-05-10 124421](https://github.com/PrismLauncher/PrismLauncher/assets/133137855/41b32c85-8d51-4718-8482-82c35785c527)
![Screenshot 2023-05-10 124434](https://github.com/PrismLauncher/PrismLauncher/assets/133137855/ca31f80e-3739-4307-9823-9b6616a79427)
![Screenshot 2023-05-10 124449](https://github.com/PrismLauncher/PrismLauncher/assets/133137855/cca4ca57-1a0e-42fe-8ca3-2f2c0d582d2b)
![Screenshot 2023-05-10 124504](https://github.com/PrismLauncher/PrismLauncher/assets/133137855/11fa28e6-05f2-4669-8f23-b0f0793481f9)

### Steps to reproduce

Launching the modpack

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by row454** [comment]
You are mixing fabric and forge mods

**Comment by Trial97** [comment]
Closing this as it doesn't look like a bug for PrismLauncer but rather a bug in your modpack:


> You are mixing fabric and forge mods
