### ISSUE TITLE
[Feature Request] Per-Instance Mod Grouping

### ISSUE THREAD

**Issue by spigelli** [PrismLauncher/PrismLauncher#1076]
I frequently extend modpacks with 150+ mods with mod integrations that I install. It would be nice if I could edit the instance after creating one from a mod pack and organize the mods list with categories or tags.

For instance recently I was adding JEI extension mods to a modpack with some pre-existing JEI mods. When something crashed I wanted to try switching to a set of REI mods buts some mod names weren't prefixed with "just enough" or "jei" so I had to manually search through the list.

Additionally it would be helpful to quickly toggle on or off all mods of a particular tag.

**Comment by Trial97** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/154
