### ISSUE TITLE
Brownish color

### ISSUE THREAD

**Issue by edgars-cirulis** [PrismLauncher/PrismLauncher#1085]
### Operating System

Windows

### Version of Prism Launcher

Develop ~ 42ceaa0015217d67245b40adf71120fcd8a739f2

### Version of Qt

QT 6.5

### Description of bug

After switching from the dark to the system theme, Prismlauncher displays a brownish color accent. Ehh, upon closing the application, it reverts back to the white theme instead of matching the expected behavior described in the Qt 6.5 article on qt.io/blog/dark-mode-on-windows-11-with-qt-6.5.

### Steps to reproduce

1. Launch Prismlauncher that is based on QT 6.5 on Windows.
2. Observe that it opens with a white theme despite Windows being set to dark mode.
3. Switch to the Dark theme within Prismlauncher.
4. Switch back to the System theme.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TayouVR** [comment]
after updating my dev version I can confirm this 
![image](https://github.com/PrismLauncher/PrismLauncher/assets/31988415/dd7f3a4e-87fb-4d83-aee9-95e83a8c0b88)

**Comment by DioEgizio** [comment]
Must be some regression related to https://github.com/PrismLauncher/PrismLauncher/pull/982

**Comment by TayouVR** [comment]
build from #982 doesn't cause this behaviour (as its still Qt 6.4), the CI build from #983 however already produces this behaviour
![image](https://github.com/PrismLauncher/PrismLauncher/assets/31988415/d87ac860-a635-4533-8946-e882ce8077a8)

EDIT: reverting #982 does not fix it either, see https://github.com/TayouVR/PrismLauncher/tree/fix-qt6_5-brown-system-theme

**Comment by TayouVR** [comment]
it looks like Qt is reporting the wrong color values to us in the QColorPalette provided by `QApplication::style()->standardPalette()`
I logged some of the color values to console on the latest build and compared it with the colors it has on startup.
For some reason it does pick up the correct colors when the app starts, but as soon as we try to get the colors and set them ourselves we get the wrong colors delivered

maybe we need to find a different way to fetch the system theme colors?

(bottom 3 colors are the correct colors for my win32 system theme)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/31988415/deabde1f-44c6-43c3-8d09-64753ffbdc52)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/31988415/12499878-bc2f-4d9f-9491-2dc324e5c6ea)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/31988415/9c522918-6680-467f-a7a3-5860e9019d49)
