### ISSUE TITLE
Cannot add or use custom themes on the portable version of Prism Launcher

### ISSUE THREAD

**Issue by jbeckham149** [PrismLauncher/PrismLauncher#1098]
### **Operating System**

Windows 11

### **Version of Prism Launcher**

Prism Launcher 6.3
Windows x64 (Portable)

### **Description of bug**

I am using the portable version of the launcher and it is not on my C:\ drive. There is no themes folder in %appdata% and there is none in the directory where the application is. When I try to manually create a themes folder, and then place a theme into the folder, it is not detected in Prism Launcher, so I am assuming that this functionality might be broken or not supported in portable mode.

### **Screenshot**

https://i.imgur.com/NvY3ERs.png

### **Other notes**

I am not sure if this "bug" is intentional or not, as there is no mention on the wiki article for downloading and adding themes on the portable version of the launcher.

https://prismlauncher.org/wiki/getting-started/change-themes/

**Comment by TayouVR** [comment]
I am fairly certain themes work in portable mode. The folder is indeed not created for you (ever, in regular installs not either), make sure when you paste the theme it has its own top level folder inside "themes".

The file structure should look like this:
```
<Prism Launcher install folder>
	<themes>
		<themename>
			theme.json
			<someFileName>.qss or .css <- optional, but most themes have this file
			resources/ <- optional, but most themes have this folder
```
my non portable install themes folder has this inside: 
![image](https://github.com/PrismLauncher/PrismLauncher/assets/31988415/cebe9239-5c18-44e6-aa5d-4f1310c20241)

EDIT: just confirmed it works on my portable build:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/31988415/31918048-9d11-4ae4-91df-f3eb6b7c3f54)

**Comment by jbeckham149** [comment]
The issue was a simple oversight. I was placing the .zip file itself into the themes folder I created in the directory. I did not extract it. Issue resolved.

Thanks!
