### ISSUE TITLE
[develop] its possible for a @Variant(something) to be saved as custom meta server url

### ISSUE THREAD

**Issue by TayouVR** [PrismLauncher/PrismLauncher#1113]
### Operating System

Windows, macOS, Linux

### Version of Prism Launcher

7.0-develop (several versions, I am not sure when it started)
the last fabric version on my meta cache was from February 25th (0.14.17)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/31988415/9479554f-6d05-4afc-a091-4178e604f5ed)

### Version of Qt

6.5.1

### Description of bug

the meta URL is populated by some weird Variant thing.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/31988415/4f72ea1b-3a4a-4321-9a05-afcc4b93177d)

![image](https://github.com/PrismLauncher/PrismLauncher/assets/31988415/8ee06bc0-3864-409b-a6b8-3852ec2a69e9)
for the record, data from the save file: `@Variant(\0\0\0\x11\0\0\0\x1d@Variant(000x11xffxffxffxff)/)`

related discord conversation: 
from this message: https://discord.com/channels/1031648380885147709/1031648381514289175/1115643075402940456
to this message: https://discord.com/channels/1031648380885147709/1031648381514289175/1115650002895782010

### Steps to reproduce

I wish I knew... 

### Suspected cause

somehow some piece of code seems to shove a QVariant into that field for saving, I guess?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
oh that's interesting. I bet at some point in the code a `QUrl` is shoved into the settings  and it's pulled back out as a string.
we just need to convert the QUrl to a string before putting it in.

**Comment by TayouVR** [comment]
ah, if its simple enough of a change, should probably include this in 7.0

**Comment by TheKodeToad** [comment]
I experienced this too :thinking:
