### ISSUE TITLE
Launcher timestamps not matching system time

### ISSUE THREAD

**Issue by Lucky-Red** [PrismLauncher/PrismLauncher#1121]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 5.15.2

### Description of bug

Timestamps in the console log and screenshot filenames are not matching up with the timezone of my system. Instead, they are seven hours ahead of my local time. 

### Steps to reproduce

![image](https://github.com/PrismLauncher/PrismLauncher/assets/68577998/a947550d-8604-4583-b850-00c12703f36e)
These entries occurred at 6:05 PM local time.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
timestamps in the console are *since the process started* and are measured in cpu time not real time.

**Comment by Lucky-Red** [comment]
Oddly enough, the issue seems to have corrected itself, though I have no idea what the cause may have been.
