### ISSUE TITLE
Fork winget-pkgs from Microsoft, not PolyMC

### ISSUE THREAD

**Issue by russellbanks** [PrismLauncher/PrismLauncher#113]
[PrismLauncher/winget-pkgs](https://github.com/PrismLauncher/winget-pkgs) needs to be forked from [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) rather than [PolyMC/winget-pkgs](https://github.com/PolyMC/winget-pkgs) as it currently is as upstream package changes in Microsoft/winget-pkgs won't be able to be merged/included otherwise.

**Comment by Scrumplex** [comment]
Done! Thanks for the headsup
