### ISSUE TITLE
Memory leak while adding mods to instance

### ISSUE THREAD

**Issue by BluSpring** [PrismLauncher/PrismLauncher#1130]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.4.2

### Description of bug

While downloading mods (from Modrinth specifically) in Prism, my Prism suddenly froze, and upon checking Task Manager, the memory usage suddenly bumped to be very high before crashing.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/20620191/16aa53e0-24d5-43cc-a6bf-25abeb928628)

### Steps to reproduce

* Create a 1.20 instance with Fabric
* Add mods from Modrinth
* When I deselected a mod (Mod Loading Screen), the launcher froze on the Download Mods screen

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ColonelGerdauf** [comment]
See if this issue still occurs in Prism 7.0

**Comment by Ryex** [comment]
Yes, I fixed this leak in particular among others in 7.0. reopen if you still experience the issue in 7.0.
