### ISSUE TITLE
Unescaped PreLaunchCommand in older instance.cfg files loses quotes and spaces when launching

### ISSUE THREAD

**Issue by Lemmmy** [PrismLauncher/PrismLauncher#1134]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.0-release-7.x, I've tested these versions:

Does not work:
- PrismLauncher-Windows-MSVC-Portable-7fb4c83-Debug
- PrismLauncher-Windows-MSVC-Portable-9b9d439-Debug
- **PrismLauncher-Windows-MSVC-Portable-c6834e3-Debug** (build after suspected cause)

Works:
- Prism Launcher 6.2
- Prism Launcher 6.3
- **PrismLauncher-Windows-MSVC-Portable-004d1dc-Debug** (build before suspected cause)

I have not tested other operating systems.

### Version of Qt

Qt 6.5.1

### Description of bug

A user of our modpack today running 9b9d439 ran into an issue where the pack did not launch, because the PreLaunchCommand was parsed incorrectly. Upon further inspection I can reproduce this between c6834e3 and 7fb4c83 too. Our modpack launch looks roughly like this:

```ini
PreLaunchCommand="$INST_JAVA" -jar packwiz-installer-bootstrap.jar --bootstrap-update-url "https://api.github.com/repos/SwitchCraftCC/packwiz-installer/releases/latest" -s client --title "Updating SwitchCraft 3 (packwiz-installer)" https://pack.sc3.io/client-pack/pack.toml
```

When attempting to launch the pack on one of the 7.x versions, the PreLaunchCommand gets re-saved and becomes this:

```ini
PreLaunchCommand=$INST_JAVA -jar packwiz-installer-bootstrap.jar --bootstrap-update-url https://api.github.com/repos/SwitchCraftCC/packwiz-installer/releases/latest -s client --title Updating SwitchCraft 3 (packwiz-installer)https://pack.sc3.io/client-pack/pack.toml
```

Notice the quotes have been removed, especially around the 'title' argument, and the URL argument now touches the title argument. This results in the following error and output in the Prism log:

```
Running Pre-Launch command: C:/Program Files/Eclipse Adoptium/jdk-17.0.3.7-hotspot/bin/javaw.exe-jar packwiz-installer-bootstrap.jar --bootstrap-update-url https://api.github.com/repos/SwitchCraftCC/packwiz-installer/releases/latest-s client --title Updating SwitchCraft 3 (packwiz-installer)https://pack.sc3.io/client-pack/pack.toml
The process failed to start.
Pre-Launch command failed with code 0.
```

Of course, for our modpack we can change the quotes in instance.cfg and distribute an updated pack to our players, but I'm creating this issue in case this is an unexpected regression in config parsing. For the time being I have told the user to revert to a stable build of Prism Launcher.

### Steps to reproduce

1. Create a new instance and click 'OK' with all default settings
2. Close Prism Launcher
3. Modify the instance.cfg file for the instance and set `PreLaunchCommand=-example "argument with spaces" -example2`
4. Open Prism Launcher and launch the instance
5. Observe that the PreLaunchCommand has been overwritten to `PreLaunchCommand=-example argument with spaces-example2`

### Suspected cause

While setting up a reproduction case I noticed that the UI now saves settings with escaped quotes, e.g. `-example \"argument with spaces\" -example2`. When using escaped quotes like this in the new versions of the launcher, the command is parsed and saved correctly.

I bisected the issue to blame 788fa40c2ae0e9786c070f4593a4e7ff6efc77d3 (the refactor to use QSettings); the 004d1dc build works with old packs but c6834e3 does not.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ricket** [comment]
I also hit this in a sort of reverse way; my pre-launch and postexit commands have spaces in them and were not quoted, and it worked fine in Prism 5.1 but broke when I updated to 7.0. Luckily I figured out that adding quotes around the command fixes my issue.
