### ISSUE TITLE
Can't see 1.20 in the version list

### ISSUE THREAD

**Issue by stantios** [PrismLauncher/PrismLauncher#1136]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 5.15.2

### Description of bug

It is basically the title. I tried to create a new instance for 1.20 and found that it was not available in the version list. Here is a screenshot to represent my issue:

![image](https://github.com/PrismLauncher/PrismLauncher/assets/98621617/a1493ad5-cbf8-4cae-b5e1-e554f5d698f5)

### Steps to reproduce

1. Open Prism Launcher
2. Click 'Add instance'
3. See if 1.20 is availble in the version list
4. If not, you have found the bug

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
- Go to Settings 	-> APIs and remove the text in Metadata Server
- Refresh the version list

If this fixes it, then it's a bug which has already been resolved (#1113)!

**Comment by stantios** [comment]
Yep, removing the text in 'Metadata Server' and restarting the launcher fixed the issue. Thank You for the help!
