### ISSUE TITLE
7.0 Crash when choosing mod

### ISSUE THREAD

**Issue by AxionQc** [PrismLauncher/PrismLauncher#1138]
### Version of Prism Launcher

Prism Launcher 7.0

### Version of Qt

Qt 6.5.1

### Description of bug

When choosing a mod and going to Curseforge and back to Modrinth tab it crashes

### Steps to reproduce

1. Click DOwnload mods
2. click curseforge
3. go back to modrinth

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sollace** [comment]
Similar issue on 6.3. Going to download mods and scrolling to the bottom results in a crash.

**Comment by RowanSkie** [comment]
Adding a comment because I'm getting this too.

**Comment by Apocalypsing** [comment]
I'n even getting crashes when Prism cannot load the default list of available mods from Modrinth (due to Modrinth being hit with heavy traffic and sometimes being down)

**Comment by AqueleHaru** [comment]
when importing modpack it crashes too.

**Comment by Trial97** [comment]
Can you try the nightly build(https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/5394098599) and see if this is still reproducing?

**Comment by Trial97** [comment]
Closing this as no further information was provided. Feel free to repoen it once you can reproduce it on the latest version(8.0)
