### ISSUE TITLE
Instance Storage Tab

### ISSUE THREAD

**Issue by SmilerRyan** [PrismLauncher/PrismLauncher#1142]
### Role

I manage multiple instances

### Suggestion

I want Prism Launcher to have the storage tab option from PolyMC.

### Benefit

So that I can calculate the size of the instances without using other tools.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Here's an image of how it would look like it it was added from PolyMC into Prism launcher.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/14893385/81fd50b0-b721-4215-9682-124f2fb2d05f)

**Comment by Regular-Baf** [comment]
Something like this would actually be awesome

**Comment by TheKodeToad** [comment]
#532 I think this is a duplicate?

**Comment by TheKodeToad** [comment]
Yeah, I think discussion should defintely happen on the other issue.
