### ISSUE TITLE
Up-to-date dialog closes immediately

### ISSUE THREAD

**Issue by MbtMarco** [PrismLauncher/PrismLauncher#1143]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 7.0

### Version of Qt

Qt 6.5.0

### Description of bug

Trying to update the mods, if they are all updated the confirmation window closes by itself.

https://github.com/PrismLauncher/PrismLauncher/assets/124934175/506827e6-e7e9-4242-8bd1-25788d565517

### Steps to reproduce

Run an update check on the mods making sure they are all up to date. And if they are it will buggy the window.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
fixed, right?

**Comment by MbtMarco** [comment]
I saw that it was fixed in some develop version, but I can't tell you where exactly I read it.
I'll check right away to make sure.

**Comment by MbtMarco** [comment]
I was wrong, I guess it's not fixed yet.

**Comment by MbtMarco** [comment]
In any case, I wouldn't know what to call this bug so the title is a little confusing.

**Comment by MbtMarco** [comment]
Still happen in 7.2

**Comment by MbtMarco** [comment]
I was uploading a log and i noticed this bug happen there too.
