### ISSUE TITLE
Disabled Microsoft account not owning Minecraft not letting you play even with one owning Minecraft

### ISSUE THREAD

**Issue by Vivaan-d** [PrismLauncher/PrismLauncher#1148]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.0

### Version of Qt

6.5.1

### Description of bug

I had a Microsoft account without Minecraft in the launcher, not defaulted (because I was going to buy one on it soon) and a account with Minecraft which was defaulted.

Expected: Opens Minecraft normally with the default account

What happend: Tells me I don't have Minecraft purchased

### Steps to reproduce

1. Add a Microsoft account with Minecraft
2. Add a Microsoft account without Minecraft
3. Default the one with Minecraft
4. Try to launch

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by emmie314** [comment]
I experienced the same issue. You can resolve it simply by removing the account on the launcher that doesn't have Minecraft. Click your username in the top right of the launcher, click "Manage Accounts", click the account that doesn't have Minecraft, and then "Remove" on the right hand sidebar.

If I had to guess, the launcher is having trouble actually setting new accounts to default.

**Comment by JillSwift** [comment]
Had the same issue today. Except it was a fresh install with no accounts - the account would register, but claim "no profile", and would not launch claiming the account does not own a copy of minecraft.
I tried to re-do several times to no avail.

**Comment by Vivaan-d** [comment]
> I experienced the same issue. You can resolve it simply by removing the account on the launcher that doesn't have Minecraft. Click your username in the top right of the launcher, click "Manage Accounts", click the account that doesn't have Minecraft, and then "Remove" on the right hand sidebar.

Yes, I found that same solution, which helped me find the cause and report it.

**Comment by Trial97** [comment]
Fixed in #1692
