### ISSUE TITLE
Mod List Export Options

### ISSUE THREAD

**Issue by SteamWo1f** [PrismLauncher/PrismLauncher#1152]
### Role

I make modpack's and play modded Minecraft frequently 

### Suggestion

Export mod list as .HTML or .TXT

### Benefit

Makes it easier to share your mod list

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### Description
I would like to suggest the addition of a quality-of-life feature that allows users to export the mod list for an instance in either a text file or an HTML file format. This feature would greatly enhance the user experience by providing an easy way to save and share the mod list.

#### Text File Example: "PACKNAME-Mods.txt"
```
Example Mod 1 [By Example Dev 1]
Example Mod 2 [By Example Dev 2]
Example Mod 3 [By Example Dev 3]
```

#### HTML File Example: "PACKNAME-Mods.html"
```html
<ul>
   <li><a href="https://modrinth.com/mod/example-mod-1">Example Mod 1 [By Example Dev 1]</a></li>
   <li><a href="https://modrinth.com/mod/example-mod-2">Example Mod 2 [By Example Dev 2]</a></li>
   <li><a href="https://www.curseforge.com/minecraft/mc-mods/example-mod-3">Example Mod 3 [By Example Dev 3]</a></li>
</ul>
```

### Benefits

- Easy Sharing: Users can share the exported mod lists with others, making it simpler to discuss and compare mods.
- Documentation: Exported mod lists can serve as documentation for reference or troubleshooting purposes.
---

## Image Concepts

Please find the image concepts below:

[![Screen1.png](https://i.postimg.cc/wjRcQK4m/Screen1.png)](https://postimg.cc/nXZDnWJF)
[![Screen2.png](https://i.postimg.cc/SK0LZZHt/Screen2.png)](https://postimg.cc/87Hrcbph)
[![Screen3.png](https://i.postimg.cc/jdF4fqcT/Screen3.png)](https://postimg.cc/bs1nch4V)

These image concepts provide visual representations of the ideas and suggestions discussed. They can help the development team better understand and implement the requested features.

### Thank you for reading, I hope to see this implemented in the future.

**Comment by warior456** [comment]
while adding this could you also add curseforge export support with converting as many links to curseforge as possible?
