### ISSUE TITLE
Auto Dependency Download

### ISSUE THREAD

**Issue by GamingInfinite** [PrismLauncher/PrismLauncher#116]
### Role

I make modpacks to play with friends on a regular basis, with varying mods

### Suggestion

Download mod dependencies when detected and not manually selected

### Benefit

While you can go through the log and just download all the mods that your modloader reported as missing, it's just frustrating that I have to do that every time to get it to work.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Downloading dependencies is a pain in the ass for how many mods I play with.

**Comment by Rafii2198** [comment]
An idea to build up on it or an alternative: When there is a mod detected to have dependencies, there will be this icon which when clicked would show these mods in the search, allowing you to download them easily. Maybe pressing with shift would automatically select newest version.
![obraz](https://user-images.githubusercontent.com/26695327/196741531-17d60866-8c1a-4aa3-af39-b90904f7aa7d.png)
In this case, it would show AdvancedChatCore and Malilib.

**Comment by SolDev69** [comment]
how do I follow this?

**Comment by yavko** [comment]
Wouldn't this require modrinth/curseforge providing deps? Which afaik only curseforge does.

**Comment by Sea-Kerman** [comment]
Modrinth also has dependencies

**Comment by yavko** [comment]
I checked the api, but didn't see anything on it, my bad

**Comment by Rafii2198** [comment]
Now that I think about it, Modrinth has dependencies per file meaning, what dependencies should the button show from my idea then? I mean mostly dependencies doesn't change, but it sometimes happens. That means a safer approach would be to show dependencies when marking for download. It should also check what mods you have installed because if this wouldn't be a thing, anytime you would mark a fabric/quilt mod it would show you that you need to download (Quilted) Fabric API.

**Comment by Bourbon8464** [comment]
Hello, I was just wondering what is the progress on this issue or an ETA for this patch release. I have noticed that a lot of people have been requesting this and I can't seem to find any information regarding how to do it on the website if this has been given the go ahead.

**Comment by Rafii2198** [comment]
I have an idea for UI if that is the problem, as I said, my previous idea was slightly incompatible with Modrinth's per file dependencies. My new idea is:
- Move `Filter Options` button to the left, placing it before the search bar – I think it is more natural as it is closer to the text you are typing
- In its original place put new button called `Depenedcies`, clicking that button would fill search results with only mods that are marked as dependency for mods you have selected to download
- The `Depenedcies` button would be grayed out until there is a dependency to be downloaded
- And if possible, add `Select all Depenedecies for download` button or something shorter to quickly mark every dependency to download, as they are all needed, there is no reason to review every one by one.

**Comment by rotkudnoK** [comment]
Guys, this is arguably one of the most important features, how is it still not implemented?

**Comment by yavko** [comment]
It is, why else would it be marked as completed lol. #986

**Comment by rotkudnoK** [comment]
How do I enable it then?

**Comment by Rafii2198** [comment]
It will be added in 8.0

**Comment by rotkudnoK** [comment]
Ah, I see, thanks

**Comment by BerrnBerrn** [comment]
is it implemented yet?

**Comment by Rafii2198** [comment]
Yes it is added, you can see it is marked as completed
