### ISSUE TITLE
Not respecting "Override default account" toggle state, always enabled?

### ISSUE THREAD

**Issue by CyberLykan** [PrismLauncher/PrismLauncher#1163]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.0

### Version of Qt

Qt 6.5.1

### Description of bug

The "Override default account" setting for an instance does not seem to respect its toggle state. If an account was set for the instance, and the setting is disabled, even if you changed your account in the launcher, it still wants to use the instance's account.

### Steps to reproduce

Make a new instance.
Enable "Override default account" and set it to a different account than what is currently being used for the launcher.
(For example, launcher is A and override is B.)
Disable "Override default account".
Launch the instance.
It should incorrectly use account B instead of account A.

### Suspected cause

Not respecting the toggle state for the setting.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by leia-uwu** [comment]
can't reproduce here, after turning off the instance toggle it uses the launcher default account

**Comment by DUCKONAROLL** [comment]
this is unrelated but how do I override the default account in the first place?

**Comment by CyberLykan** [comment]
May have been fixed by a full reinstall of Prism Launcher.
