### ISSUE TITLE
Exporting to mrpack puts all mods into Overrides

### ISSUE THREAD

**Issue by Rafii2198** [PrismLauncher/PrismLauncher#1165]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.0
Commit: bfe7e3afed286de02dfc1ec4cc2b39f31972d295

### Version of Qt

Qt 6.5.1

### Description of bug

Export instances to mrpacks just puts all mods into Overrides instead of indexing them in modrinth.index.json leading to huge file sizes and probably incompatibility with Modrinth itself 

### Steps to reproduce

* Create new moded instance
* Download mods from Modrinth
* Export the pack as .mrpack

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Shahelion** [comment]
This issue is still happening with Prism Launcher 8.0. Almost every mod in the override folder, way too big for Modrinth.

**Comment by TheKodeToad** [comment]
That should only happen for mods which can't be found on Modrinth! Are you sure that's not the case?

**Comment by Shahelion** [comment]
I checked a few, and they do seem to exist on Modrinth. I'll have to investigate specific version numbers later, but I have over 200 mods in the pack and only 8 ended up in the manifest which seems unlikely that none of those would be available on Modrinth.

**Comment by Rafii2198** [comment]
Are you sure have metadata generated for all mods? If there is no metadata, then Prism will just see these mods as random files and put them in override

**Comment by Shahelion** [comment]
What do you mean by metadata?

It worked for the curseforge export, for the most part, if that makes a difference.

**Comment by TheKodeToad** [comment]
> Are you sure have metadata generated for all mods? If there is no metadata, then Prism will just see these mods as random files and put them in override

It looks them up on Modrinth anyway even if metadata is missing

**Comment by Shahelion** [comment]
I just tried again, and the same thing happened. Unlike the CurseForge manifest, I can't exactly manually edit the modrinth mod list. Is there any way to get this to work?

**Comment by Rafii2198** [comment]
It works for me perfectly on version 8.4. I would imagine sending logs would help determine what is happening in the background and thus why it is not working
