### ISSUE TITLE
Can't write to files, causing inability to change icons or install/remove modded versions.

### ISSUE THREAD

**Issue by LeWolfYT** [PrismLauncher/PrismLauncher#1167]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 7.0

### Version of Qt

Qt 6.5.0

### Description of bug

Every time I try to install Fabric/Forge, change the version,  or change the Minecraft version, it doesn't work.

### Steps to reproduce

1. Open Prism Launcher
2. Edit an instance
3. Change the version of Minecraft
4. Click "reload", or launch the game. It will show the version of Minecraft that was installed before you changed the value.

### Suspected cause

Insufficient permissions

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
can you send prismluancher_0.log from an a run where you attempt a number of these things.

**Comment by LeWolfYT** [comment]
I found a fix. Go into the instances folder and run the command
sudo chmod -R 777 ./
This shouldn't be a problem, so a permanent fix may be helpful. (maybe try using chmod whenever an instance-related file is detected as being read-only)

**Comment by Trial97** [comment]
Well if the system is telling us that the files are read-only we can not elevate the permissions for them(that would be a security risk).
I will close this issue as a solution was found(just ensure that the files are writable) and because it was not caused by the launcher
