### ISSUE TITLE
Older Technic packs on 1.4.7 and 1.5.2 fail to install

### ISSUE THREAD

**Issue by oolivero45** [PrismLauncher/PrismLauncher#1168]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.0

### Version of Qt

Qt 6.5.1

### Description of bug

Some older Technic platform modpacks fail to install, throwing an error stating `Invalid "forgeversion.properties"!`. This appears to be isolated to packs running on Forge for MC 1.4.7 and 1.5.2.

### Steps to reproduce

* Create a new instance using the Technic platform.
* Select a modpack which runs on Forge for MC 1.4.7 or 1.5.2. One known pack which can be used for testing is Tekkit Lite.
* Attempt to install the pack. Prism will successfully download all the pack's mods, but then fail to complete the installation.

### Suspected cause

I've spent a while trying to debug the issue, and I believe that I've managed to isolate the cause of the bug.
As far as I can tell, the issue was introduced by changes made to [launcher/settings/INIFile.cpp](https://github.com/PrismLauncher/PrismLauncher/blob/b174f8226132a5484aa3b1421352a929372ed2b0/launcher/settings/INIFile.cpp) in https://github.com/PrismLauncher/PrismLauncher/commit/788fa40c2ae0e9786c070f4593a4e7ff6efc77d3 - this commit removed the code from the INI file handler which allowed it to be passed a file as a QByteArray rather than being passed a filename.

I suspect that this change broke the code at at [launcher/modplatform/technic/TechnicPackProcessor.cpp, lines 108-124](https://github.com/PrismLauncher/PrismLauncher/blob/b174f8226132a5484aa3b1421352a929372ed2b0/launcher/modplatform/technic/TechnicPackProcessor.cpp#L108-L124), which handles Technic modpacks on these Forge versions, as this code attempts to pass a QByteArray to `INIFile.loadFile`.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Mariocraft95** [comment]
I will also vote this one up! I love how you actually went in the commit history and found the issue. I wish I was as smart as you
