### ISSUE TITLE
ViveCraft option

### ISSUE THREAD

**Issue by luximus-hunter** [PrismLauncher/PrismLauncher#117]
### Role

I play Minecraft (a lot) and I have a VR headset

### Suggestion

Add an option in the "create instance" menu (below technic or something similar) to create a ViveCraft instance

### Benefit

It saves a lot of people time to set up ViveCraft

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TayouVR** [comment]
vivecraft exists on modrinth nowadays, so you can install it just via the mod downloader. 
See https://modrinth.com/mod/vivecraft

**Comment by NarwhalAndMe** [comment]
> vivecraft exists on modrinth nowadays, so you can install it just via the mod downloader. See https://modrinth.com/mod/vivecraft

Additionally, you can also make modpacks with the mods you like, and just download them whenever you want to add something new! (kind of like a template/base pack)

**Comment by luximus-hunter** [comment]
Oh, I didn't know they put it up on Modrinth! That's awesome, thanks so much guys!
