### ISSUE TITLE
Modify mod metadata files (for example, fabric.mod.json) to force mods to try and run on different Minecraft versions

### ISSUE THREAD

**Issue by floral-qua-floral** [PrismLauncher/PrismLauncher#1170]
### Role

I use Prism Launcher to create, manage, and play personal modpacks.

### Suggestion

It would be nice to have some way to select a mod or group of mods, press a button, and have all of those mods' metadata modified such that they will try to load on whatever version the containing Instance is set to.

### Benefit

Recently 1.20.1 was released, which is similar enough to 1.20 that most mods should work fine on it - however, some mods have their metadata set up to explicitly require 1.20 and will refuse to load on 1.20.1, even though they would likely work. I could open up each of these mods' jars using a program like 7zip and modify their metadata manually to get them to accept the newer version, but doing so is slow and tedious.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
~~maybe Fabric, Quilt or Forge could implement a system property to have the same effect without modifying jars... :woman_shrugging:~~

read the message below v

**Comment by DioEgizio** [comment]
Already exists 

https://fabricmc.net/wiki/tutorial:dependency_overrides / https://github.com/QuiltMC/quilt-loader/wiki/Dependency-Overrides
