### ISSUE TITLE
Change "Import from zip" to "Import from modpack" to avoid confusion of whether .mrpack is supported

### ISSUE THREAD

**Issue by drkhn1234** [PrismLauncher/PrismLauncher#1171]
### Role

I am an ordinary person who just happened to got confused by the wording till I read wiki to learn that I could indeed import .mrpack aswell and not just .zip modpacks 

### Suggestion

I want the string "Import from zip" within the pop-up dialog of the action "Add Instance" to be changed as "Import from modpack"

### Benefit

This should make it clearer for new users (such as me) who wants to import from modpack but don't know from where or which formats are supported

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by getchoo** [comment]
i think a better solution here might be changing the name to something like "import from mrpack/zip" in order to avoid confusion for everyone - since only including the former might also make it confusing for those importing zips

**Comment by RuiNtD** [comment]
It probably makes more sense to change it to "Import from File". The page already details what types of files are supported.

**Comment by TheKodeToad** [comment]
Or just import? File sounds like it might be local

**Comment by RuiNtD** [comment]
ZIP also sounds like it would be local. The page already makes it clear it also accepts URLs, although the option to import from URL seems like more of an advanced option anyways, especially since it requires a **direct** download.

**Comment by getchoo** [comment]
i agree with kodetoad here. i think "import" would make the most sense as it is kind a hub for all of our misc imported stuff
