### ISSUE TITLE
Add a list of mods in a text file that can be put in your friends' Prism Launchers to automatically download the specified mods

### ISSUE THREAD

**Issue by ruguysgoingtrickortreating** [PrismLauncher/PrismLauncher#1178]
### Role

I want to share my mods with my friends who are just getting into Prism.

### Suggestion

You could press a button in the mods section of an instance to create a file (probably a list of mods in plain text) that could be put into another download of Prism (or the same but a different instance) to automatically download the mods specified.

### Benefit

It would be a great way to share pseudo-modpacks with your friends or give your mod setup to a buddy.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
#214 (using csv) is better imo - assuming it's not a duplicate; not sure if we want that either though
