### ISSUE TITLE
Auto-download dependencies for mods

### ISSUE THREAD

**Issue by SolDev69** [PrismLauncher/PrismLauncher#118]
### Role

Downloading mods with dependencies

### Suggestion

Auto-downloading of dependencies similarly to the CurseForge launcher.

### Benefit

Easier to download mods with dependencies (instead of having to check the mod page for dependencies manually)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by MoustacheOff** [comment]
Already exists: #116

**Comment by DioEgizio** [comment]
duplicate of #116
