### ISSUE TITLE
Application Add Option (or some other name)

### ISSUE THREAD

**Issue by Zac99LOL** [PrismLauncher/PrismLauncher#1180]
### Role

I play modded Minecraft and make Minecraft mods.

### Suggestion

I want to be able to add applications to the instance menu so I can launch them from there.

### Benefit

So that I can make mods easier.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I use MacOS and would like the feature to work for both.

**Comment by Trial97** [comment]
Try: https://www.raycast.com/lockieluke3389/prism-launcher
