### ISSUE TITLE
PrismLauncher crashes when I reize to a thin window

### ISSUE THREAD

**Issue by emmaLikesLinux** [PrismLauncher/PrismLauncher#1188]
### Version of Prism Launcher

prismlauncher 7.0-1 from aur

### Version of Qt

6.5.1

### Description of bug

Whenever I try to resize the PrismLauncher main window to a very thin size, it crashes. I'm using fully up to date arch linux with zen kernel, hyprland

### Steps to reproduce

* Open PrismLauncher
* Resize window so the left sidebar cannot display fully
* PrismLauncher Crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by leia-uwu** [comment]
hyrpland and other window managers ignore the minimum requested size for the window, its not supposed to get that small

**Comment by emmaLikesLinux** [comment]
Ahh tsym my bad
