### ISSUE TITLE
Auto-change java version for newly created instances of olver versions of MC

### ISSUE THREAD

**Issue by ThaBluNate** [PrismLauncher/PrismLauncher#1193]
### Role

I play multiple different versions of minecraft, mostly because of mods

### Suggestion

I want the prism launcher to automatically switch the version of java used on some instances.

### Benefit

It is a pain to manually switch the java version of older versions.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Every time I make an instance with an older version and try to boot it up, it usually just crashes. 
Cue searching through crash logs and... oh... I forgot to switch java versions.
This is something that should be configurable in settings  ("Java" tab, under "Java Runtime"?)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/51035517/f426ded0-934c-4699-98e4-2ae6588d1c5b)

**Comment by RuiNtD** [comment]
Duplicate of #335

**Comment by Scrumplex** [comment]
indeed
