### ISSUE TITLE
Add the ability to hide columns

### ISSUE THREAD

**Issue by stantios** [PrismLauncher/PrismLauncher#1197]
### Role

I play with CurseForge and Modrinth modpacks

### Suggestion

I want there to be an option where you can hide colums in the mods or any section (I am not sure what they orginally called, so I just called them that).

Here is a screenshot of what I am talking about: https://imgur.com/a/1PLfpLH

### Benefit

The benefit of why this should be added is because the user might want to hide the 'Provider' column if the provider is unknown so they can see the full name for the mods, or the user might want to hide the 'Last changed' column since it might not be relevant to them.

Here is a screenshot of what I am talking about: https://imgur.com/a/B08CylE

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Ryex** [comment]
#1058 would solve this. it's part of the PR
