### ISSUE TITLE
large screenshots cause Prism to malfunction and then hang

### ISSUE THREAD

**Issue by nmiell** [PrismLauncher/PrismLauncher#1201]
### Operating System

Linux

### Version of Prism Launcher

prismlauncher-7.0-1.fc37.x86_64

### Version of Qt

6.5.1

### Description of bug

When a large screenshot is present in the Minecraft instance's screenshot folder, Prism Launcher malfunctions when you select the **Screenshots** category in the **Edit Instance** window.

Specifically,
* the large screenshot never replaces its placeholder image with the real thumbnail
* attempting to open any screenshot at all does nothing
* the various context menu options (**View Folder**, **Copy File(s)**, etc.) do nothing
* lots the following error appears in the user's systemd journal:
    > org.prismlauncher.PrismLauncher.desktop[943522]:    122.961 W | [qt.gui.imageio]: QImageIOHandler: Rejecting image as it exceeds the current allocation limit of 128 megabytes
* the application stops responding and needs to be forcibly terminated after you close the **Edit Instance** window

### Steps to reproduce

* save an image of your Minecraft world map using the JourneyMap mod (the image in question is a 11776 x 13824 PNG that is 25 MB compressed)
* select your instance, click the **Edit** button
* click the **Screenshots** category
* try manipulating the screenshots, nothing works
* close the window, the application stops responding (if you do not try to open any screenshots, the application appears to continue without problem)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by telans** [comment]
I've created a PR that should fix the hangs, if you're able to give it a try.

This won't help with missing thumbnails for large images as they exceed the QImage allocation limit of 128MiB
