### ISSUE TITLE
Macos Crash when Switching Between Modrinth and Curseforge while Searching

### ISSUE THREAD

**Issue by MassiveZappy** [PrismLauncher/PrismLauncher#1205]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 7.0

### Version of Qt

Qt 6.5.0

### Description of bug

I didn't expect that to exit the program. It's challenging to make mod packs with this issue.

### Steps to reproduce

[Video](https://github.com/PrismLauncher/PrismLauncher/assets/51025321/bcb12e3d-5a36-4ee5-92d2-0a907068d21a
)
* Open Prism launcher.
* Open profile setting for a profile. (I used forge 1.20.1)
* Select a mod for download. (I used [FerriteCore](https://modrinth.com/mod/ferrite-core))
* Search for another mod that is on both Curseforge and Modrinth. (I used [Curios API](https://modrinth.com/mod/curios))
* Select that mod.
* Switch between Curseforge and Modrinth vendors.
### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Update to 7.1

**Comment by Trial97** [comment]
Hi, can you please try to reproduce this using the latest nightly builds: https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop

**Comment by Trial97** [comment]
@MassiveZappy does this happen in 8.2?

**Comment by Trial97** [comment]
Closing this as there were no updates.
If you still experience this in that latest version please feel free to reopen this.
