### ISSUE TITLE
Flatpak and AppImage crash when downloading new Modpacks (specifically ATM8)

### ISSUE THREAD

**Issue by j00w33** [PrismLauncher/PrismLauncher#1208]
### Operating System

Fedora Linux 38

### Version of Prism Launcher

Flatpak 7.0, and AppImage 7.1

### Version of Qt

Flatpak: 5.15.9
AppImage: 6.2.4

### Description of bug

When downloading a new modpack from Curseforge, the client will get to the "Resolving ModIDs". then the program will immediately close. This can be for any modpack from Curse. The issue doesn't seem to be an issue with Modrinth packs

### Steps to reproduce

- Press "Add Instance" at the top
- Select "Curseforge" on the side
- Select ATM8 from the list
- Click OK

### Suspected cause

Might have something to do with the 404 returns on a lot of the mods that are on Curseforge?
Unsure since it's not ALL curseforge mod packs and it only happens on the AppImage and FlatPak releases. The tar.gz portable works fine

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by alexanderjkslfj** [comment]
I have the same issue with PrismLauncher 7.1 on Windows 11 (non-ARM). Tested with ATM8 v1.0.19b and Minecolonies Official v1.19.

**Comment by TheWind32** [comment]
Same Issue here on 7.0 and 7.1

**Comment by vasubawa** [comment]
Same issue with 7.0 and 7.1

**Comment by j00w33** [comment]
I have an update. I found that if you change the Curseforge API key to the one that the official client uses then it works without issues.  
`$2a$10$bL4bIL5pUWqfcO7KQtnMReakwtfHbNKh6v1uTpKlzhwoueEJQnPnm`  

I'm pretty sure this isn't a permanent fix so I'm gonna leave this issue open

**Comment by thaddeuskkr** [comment]
Same issue, **7.1** on **Windows 11 (x64)** downloaded via `winget` and tested using RLCraft. And the API key fix works, thanks.

**Comment by slonkazoid** [comment]
workaround
```diff
diff --git a/launcher/net/ByteArraySink.h b/launcher/net/ByteArraySink.h
index 728193b3..b747d687 100644
--- a/launcher/net/ByteArraySink.h
+++ b/launcher/net/ByteArraySink.h
@@ -53,10 +53,10 @@ class ByteArraySink : public Sink {
    public:
     auto init(QNetworkRequest& request) -> Task::State override
     {
-        if (m_output)
-            m_output->clear();
-        else
-            qWarning() << "ByteArraySink did not initialize the buffer because it's not addressable";
+        // if (m_output)
+        //     m_output->clear();
+        // else
+        //     qWarning() << "ByteArraySink did not initialize the buffer because it's not addressable";
         if (initAllValidators(request))
             return Task::State::Running;
         return Task::State::Failed;
@@ -75,10 +75,10 @@ class ByteArraySink : public Sink {
 
     auto abort() -> Task::State override
     {
-        if (m_output)
-            m_output->clear();
-        else
-            qWarning() << "ByteArraySink did not clear the buffer because it's not addressable";
+        // if (m_output)
+        //     m_output->clear();
+        // else
+        //     qWarning() << "ByteArraySink did not clear the buffer because it's not addressable";
         failAllValidators();
         return Task::State::Failed;
     }
```
note that this probably causes several memory leaks and might crash for other reasons. compile 7.1 with this patch and use it to download broken modpacks only

**Comment by slonkazoid** [comment]
also happens on latest commit, here on arch linux running the `prismlauncher-git` aur package (qt6)

**Comment by slonkazoid** [comment]
fixed with #1200

**Comment by Ryex** [comment]
> fixed with #1200

you tested after that merge?

**Comment by j00w33** [comment]
Has this merge been released through flatpak/AppImage. I don't know about the AUR functionality, but I was only having issues with those package variants.  
The copr repo and the tar.gz archive worked previously without any changes

Edit: I see the merge was only 6hr ago. My apologies

**Comment by slonkazoid** [comment]
> > fixed with #1200
> 
> you tested after that merge?

compiled and tested it locally before and after :+1:

**Comment by slonkazoid** [comment]
> Has this merge been released through flatpak/AppImage. I don't know about the AUR functionality, but I was only having issues with those package variants. The copr repo and the tar.gz archive worked previously without any changes
> 
> Edit: I see the merge was only 6hr ago. My apologies

you need to compile it yourself or download a dev build from actions if u want that commit right now

**Comment by j00w33** [comment]
I mainly wanted the commit to test the fix and help your testing. I'll
await the next release before removing the API key. Just glad to help out 😊

**Comment by Trial97** [comment]
Closing this as it was reported that it was solved on the latest develop build.
