### ISSUE TITLE
Update Screen still showing PolyMC Updates

### ISSUE THREAD

**Issue by Windgott1910** [PrismLauncher/PrismLauncher#121]
### Operating System

Linux

### Version of PolyMC

Prism Launcher 5.0

### Version of Qt

5.15.3

### Description of bug

news page shows PolyMC updates

### Steps to reproduce

Launcher --> other News

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Windgott1910** [comment]
done by #106

**Comment by RuiNtD** [comment]
...you mean duplicate of #106???
