### ISSUE TITLE
Crash when installing StaTech industry modpack

### ISSUE THREAD

**Issue by Janitor53** [PrismLauncher/PrismLauncher#1211]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.1
Commit: 34d80a8c754ffa2e79cbde2be54b8de7d3f1a67c

### Version of Qt

Qt 6.5.1

### Description of bug

I got a crash when trying to install StaTech Industry modpack version 1.0.3. from a curseforge.
Logfile: https://mclo.gs/9GfWJ1a
This crash also happens on 7.0 version of the launcher, but not on the 6.3. 6.3 works fine.
Error log from windows event viewer:
```
Faulting application name: prismlauncher.exe, version: 7.1.0.0, time stamp: 0x648c4d34
Faulting module name: Qt6Core.dll, version: 6.5.1.0, time stamp: 0x6469b02c
Exception code: 0xc0000005
Fault offset: 0x000000000011d5ba
Faulting process id: 0x0x1878
Faulting application start time: 0x0x1D9A08239EFEB2F
Faulting application path: C:\Games\PrismLauncher.new\prismlauncher.exe
Faulting module path: C:\Games\PrismLauncher.new\Qt6Core.dll
Report Id: 21f6a942-708c-45fb-accc-645ddb6fc02d

```
### Steps to reproduce

Add instance - Curseforge - Statech Industry - OK

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by alexanderjkslfj** [comment]
Is this the same as #1208 ?

**Comment by Janitor53** [comment]
#1208 is about Linux version of launcher so it's not the same I guess.

**Comment by Matakor** [comment]
I believe I'm getting this same crash, and the last thing seen is 'resolving mod ids'. It's completely reproducible on 7.1, as far as I can tell. I've not been able to update Statech, or install a new instance of it either.  -- scratch that, for some bizarre reason, when I tried to capture a pic of the exact screen using a third party screen capture tool (sharex), it suddenly passed the faulting point and went to the 'download blocked mods' bit.

Not really sure what caused the fault then, maybe a window creation issue, or graphics issue? bizarre fix for that though~

**Comment by Trial97** [comment]
Can you try the nightly build(https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/5394098599) and see if this is still reproducing?

**Comment by Janitor53** [comment]
Nightly build works fine. No crash here.

**Comment by Trial97** [comment]
Closing this as it was reported that it was solved on the latest develop build.
