### ISSUE TITLE
Instances don't seem to launch properly if the instance's settings page was opened.

### ISSUE THREAD

**Issue by CyberLykan** [PrismLauncher/PrismLauncher#1215]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

Instances don't seem to launch properly if the instance's settings page was opened.

Normally, it should show a popup with the startup processes (like connecting to Mojang servers) and then start the instance.

Because of this bug, no such popup appears.

I have tried opening and closing other menus (such as Add Instance and About Prism Launcher) before launching the instance to see if there might be an issue with windows interfering somehow. There is not.

I also tried seeing if the instance settings type of window specifically was causing an issue by opening and closing the settings of a separate instance then launching the desired instance. There was no issue.

### Steps to reproduce

- Open Prism Launcher
- Open the settings page for an instance
- Close the settings page
- Try to launch the instance

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RedsonBr140** [comment]
I wasn't able to replicate the issue on my machine.

**Comment by CyberLykan** [comment]
Fixed by a full reinstall of Prism Launcher.
