### ISSUE TITLE
The .DS_Store file during export should be unselected by default

### ISSUE THREAD

**Issue by MbtMarco** [PrismLauncher/PrismLauncher#1225]
### Role

I create modpacks.

### Suggestion

The .DS_Store file during export should be unselected by default

### Benefit

Operating systems other than Macos do not use this file, and it could be confusing if a user uses another operating system. (On Macos this file is always hidden and can be found in every folder.)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Example image:
<img width="1004" alt="Image" src="https://github.com/PrismLauncher/PrismLauncher/assets/124934175/192eb13d-d31b-497f-b778-b2c1173ae2fa">

**Comment by TheKodeToad** [comment]
Tbh I think the .DS_Store file should be entirely hidden as well as unchecked.

**Comment by MbtMarco** [comment]
I already don't know why PrismLauncher displays it and selects it for export.
