### ISSUE TITLE
mrpack invalid link

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [PrismLauncher/PrismLauncher#1226]
### Operating System

Linux

### Version of Prism Launcher

7.1 flatpak

### Version of Qt

5.15.10

### Description of bug

Expected
https://cdn.modrinth.com/data/QdG47OkI/versions/7ainrOrH/modelfix-1.8-fabric%20%281%29.jar
Received
https://cdn.modrinth.com/data/QdG47OkI/versions/7ainrOrH/modelfix-1.8-fabric %281%29.jar

copied from the modrinth discord server support. linux flatpak v7.1

### Steps to reproduce

make a mrpack file

### Suspected cause

space is encoded as %20 in URLs

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by telans** [comment]
Is this really an issue? The mrpack importer can still download the mods with "%20" encoded to " "
