### ISSUE TITLE
Desktop shortcuts cause Segmentation Fault

### ISSUE THREAD

**Issue by lewisfm** [PrismLauncher/PrismLauncher#1229]
### Operating System

macOS, Linux

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.0

### Description of bug

Desktop shortcuts of Minecraft Instances do not successfully start the game. Instead, they open a terminal window showing a segmentation fault error message.
![34987](https://github.com/PrismLauncher/PrismLauncher/assets/75394401/52e20b79-d1ce-4ab6-9822-90bed2fc79c7)

### Steps to reproduce

1. Click "Add Instance", select "Vanilla", and click "OK"
2. Click "Create Shortcut"
3. Close Prism Launcher
4. Double-click the file created on the desktop

### Suspected cause

It seems related to downloading assets. This also seems specific to the `--launch` command line flag and doesn't happen when using the app manually.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by sadespresso** [comment]
I also have the same issue on KDE Desktop (KDE Neon 5.27)

The problem occurs both on CLI, and `.desktop` links, but launching the instance through Prism Launcher (no links, no arguments) works as expected

Steps and suspected cause is same as this issue.

OS: KDE Neon 5.27
Prism Launcher Version: 7.1
Command: `./prismlauncher --launch 1.20.1`
Logs:
```
...
...
...
    2.727 D | [launcher.task]: Task "NetJob(Libraries for instance Intro City ID: b1fd7ae6-99a1-4d53-a055-121141ddc4f7)" starting for the first time
     2.728 D | [launcher.task]: Task "NetJob(Libraries for instance Intro City ID: b1fd7ae6-99a1-4d53-a055-121141ddc4f7)" succeeded
     2.728 D | [launcher.task]: Task "LibrariesTask(0x5607c0d496a0 ID: 4e97f97f-72d3-47c3-8530-f2f484fecd74)" succeeded
     2.728 D | [launcher.task]: Task "FMLLibrariesTask(0x5607c0d351a0 ID: b00f629e-75d2-47b7-95b5-84e882c7c974)" starting for the first time
     2.728 D | [launcher.task]: Task "FMLLibrariesTask(0x5607c0d351a0 ID: b00f629e-75d2-47b7-95b5-84e882c7c974)" succeeded
     2.728 D | [launcher.task]: Task "AssetUpdateTask(0x5607c0d48a40 ID: 9ae2b50e-e924-4524-a802-0298c9d13ab8)" starting for the first time
     2.728 D | Asset index SHA1: "9d58fdd2538c6877fb5c5c558ebc60ee0b6d0e84"
     2.728 D | "Intro City" : Starting asset index download
     2.729 D | [launcher.task]: Task "NetJob(Asset index for Intro City ID: 7dcea6cc-d846-4492-9e44-2fd8c4c37441)" starting for the first time
     2.732 D | [launcher.task]: Task "Net::Download(CACHE:https://piston-meta.mojang.com/v1/packages/9d58fdd2538c6877fb5c5c558ebc60ee0b6d0e84/5.json ID: b12ab7d9-96dd-4597-aa44-ffbe2f22d19d)" starting for the first time
Segmentation fault
```

**Comment by DioEgizio** [comment]
i can reproduce

**Comment by 42willow** [comment]
I can reproduce on Windows.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/70784752/80876e53-b2d6-4dba-a00f-9fa9cf1da8ac)
I don't know how to view the launcher console though.

**Comment by sadespresso** [comment]
I also just found out if you have a currently open Prism Launcher window, and use the shortcut (or thru cli), it [correctly] launches the desired Minecraft instance.

**Comment by Ryex** [comment]
@doinkythederp 
can I get you to test a nightly build?
https://github.com/PrismLauncher/PrismLauncher/actions/runs/5440563742
or
https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/5440563742

Another user on dicord provided macos logs of the segfualt and I was able to determine a possible cause
