### ISSUE TITLE
Consistent UX between modpack providers

### ISSUE THREAD

**Issue by DioEgizio** [PrismLauncher/PrismLauncher#1239]
### Role

i use prism

### Suggestion

Right now, every modpack provider UI has pretty much a different UX. The only ones that are somewhat consistent are Modrinth and CurseForge. Hell, FTB Legacy doesn't even have a search bar. So my suggestion is, making them consistent and similar to the resource downloader: a search bar with the same text and with a search button (for some reason atlauncher doesn't have it) (perhaps we could also add the instant searching to every modpack page like the resource downloader), and the modpacks have the name and below it their short description if available, while the whole body when clicked, like modrinth and cf right now. Also preserving the search term between the providers would be a nice UX thing

### Benefit

better UX

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
related to: https://github.com/PrismLauncher/PrismLauncher/issues/401 ,https://github.com/PrismLauncher/PrismLauncher/issues/843
