### ISSUE TITLE
Failed to get authorization for Xbox services: Host xsts.auth.xboxlive.com not found

### ISSUE THREAD

**Issue by whytf** [PrismLauncher/PrismLauncher#1244]
### Operating System

- Windows 11 Enterprise 22H2

### Version of Prism Launcher

- 7.1

### Version of Qt

- 6.5.1

### Description of bug

Cannot login with microsoft account with this error:
"Failed to get authorization for Xbox services: Host xsts.auth.xboxlive.com not found"

Context: Before this issue i tried to "refresh" account in accounts section because i couldn't launch online, only offline, so i tried to add the account again but couldn't

![Screenshot 2023-06-22 013640](https://github.com/PrismLauncher/PrismLauncher/assets/35870617/88360496-f7f6-4efe-a7fd-e81c46592eb6)

### Steps to reproduce

- Add a microsoft account
- After confirming login on website the error shows

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by cupidjack** [comment]
@whytf Did you ever end up finding a fix to this?

**Comment by Trial97** [comment]
Did you have some firewall rules that block Microsoft services?
It is still reproducible on 7.2?

**Comment by Trial97** [comment]
Closing this as no response was received.
Please feel free to reopen this if this still happens on 8.0 or later versions of the Launcher

**Comment by all-yall** [comment]
I had this issue as well because I had just changed my username on my Xbox and Microsoft accounts. After about 20 minutes it allowed me to log in.
