### ISSUE TITLE
Modrinth API and Prism Launcher news API not working

### ISSUE THREAD

**Issue by biomseed** [PrismLauncher/PrismLauncher#1247]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

I opened Prism Launcher a few days ago, and the news on the bottom stopped showing up.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/73907153/a752597a-123f-4cb5-9892-503d9b26ef94)
Like this.
I could still use the launcher normally, so that was fine. It clearly wasn't a problem with my network because everything else worked fine, so I assumed you were updating your API or something. A day later, suddenly everything related to Modrinth stopped working entirely.
When I try to install Modrinth modpacks:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/73907153/2859a0ab-b3f7-41b0-afff-7c82f83bbe51)

When I try to install Modrinth mods, shader packs, resource packs, or anything else:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/73907153/1488139a-585e-4566-bf54-050e98a46f95)

When I try to update existing Modrinth mods:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/73907153/3f994a52-e7b9-40dd-9172-274fd9973a95)

After a while of using the launcher, Modrinth stuff starts working again, without mod icons:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/73907153/b3995297-b07b-405c-bee0-a38d666ddf55)

### Steps to reproduce

- Open Prism Launcher
- Press "Add Instance"
- Click on "Modrinth"

### Suspected cause

Something might have gotten messed up in whatever files Prism Launcher is using. It has nothing to do with any of my instances.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by biomseed** [comment]
I deleted the Prism Launcher appdata folder (I have my instances on a seperate drive don't worry), and relaunched it and set my settings to how they were, and it was the same. It must have nothing to do with what's on my end (or maybe it's my PolyMC appdata, since Prism Launcher brings it over). Now there's a new problem. I had to add my account again, as usual, but adding accounts TAKES FOREVER. This has to be related to this issue, since the news isn't loading either. Everything that has to do with PolyMC, Mojang, or Modrinth's API seems to be delayed a lot. Whenever there's a loading screen for something related to them, it always stays at a certain point for a long long time, and then completes like normal.
Now I try to install the versions and libraries as usual, and this happens:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/73907153/8d93fc92-0938-42f9-90c6-0ecd76f6e561)
Clicking abort does nothing.

**Comment by biomseed** [comment]
Also Technic and ATLauncher stuff doesn't work either. Only Curseforge does.

**Comment by biomseed** [comment]
It seems the problem has fixed itself now. Will close until anything happens again. Also, thanks for the help.

**Comment by biomseed** [comment]
It's happening again.

**Comment by TheKodeToad** [comment]
> It seems the problem has fixed itself now. Will close until anything happens again. Also, thanks for the help.

I don't think anyone helped you. lmao. I can have a look now though! 🫠

**Comment by biomseed** [comment]
> > It seems the problem has fixed itself now. Will close until anything happens again. Also, thanks for the help.
> 
> I don't think anyone helped you. lmao. I can have a look now though! 🫠

That was the point of me saying thanks for the help, because I got no help.

**Comment by TheKodeToad** [comment]
:/ the github issue tracker isn't for support in the first place

**Comment by biomseed** [comment]
> :/ the github issue tracker isn't for support in the first place

This is a bug. It has happened for multiple people. Figuring out what's going on is part of fixing a bug.

**Comment by Ryex** [comment]
> > :/ the github issue tracker isn't for support in the first place
> 
> This is a bug. It has happened for multiple people. Figuring out what's going on is part of fixing a bug.

I can can almost guarantee that this is related to service interruptions, not a software bug.

**Comment by biomseed** [comment]
This can be fixed by disconnecting and reconnecting to the internet.
