### ISSUE TITLE
LWJGL 2.9.4-nightly-20150209 appears to be non-functional on macOS arm64

### ISSUE THREAD

**Issue by Jazzzny** [PrismLauncher/PrismLauncher#125]
### Operating System

macOS

### Version of PolyMC

PrismLauncher 5.0

### Version of Qt

Qt 6.3.0

### Description of bug

Versions of Minecraft that use LWJGL 2 crash when LWJGL 2.9.4-nightly-20150209 is selected (default behaviour). 

Things I've tried:
Selecting LWJGL 2.9.3, works
Using ManyMC's Metadata server, does not work
Using PolyMC 1.4.2 with ManyMC's Metadata server, works

Minecraft 1.0's crash log: https://mclo.gs/LnrGuzQ
Minecraft 1.12.2's crash log: https://mclo.gs/eHvK82M

### Steps to reproduce

- Create a new instance with any version that uses LWJGL 2 (E.g. Minecraft 1.12.2) on an arm64 macOS platform
- Launch the instance
- Instance will crash, appears as if LWJGL is missing

### Suspected cause

N/A

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Jazzzny** [comment]
Seems to be fixed after nuking /Application Support/PolyMC. Apologies

**Comment by MachineRat8** [comment]
I encountered the same issue with LWJGL 3, and I fixed it the same way.
