### ISSUE TITLE
Java sometimes fails the compatibility check

### ISSUE THREAD

**Issue by crispyLettuce3** [PrismLauncher/PrismLauncher#1250]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 5.15.10

### Description of bug

the java 1.8.0_372 distribution included with the flatpak package registers as such in the games F3 menu and the auto-detect picker. in the game logs, it registers as version 17.0.7, and the compatibility checker forbids launching. this does not happen with a separately downloaded openjdk version installed to the flatpak jdk folder.

https://mclo.gs/E4yiTKK

### Steps to reproduce

-install prism launcher on linux from flatpak 
-install a 1.12.2 instance
-set active java binary in the instance or global settings to either binary marked with 1.8.0_372
-fail to launch the game

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LackingCats** [comment]
That's happening with me as well. Trying to use packaged java 17 flatpak bundle, however it is detecting it as java 8?
flatpak 8.0-develop

**Comment by therealmate** [comment]
Reverting to the 7.0 flatpak fixes the issue for me. After launching the game with 7.0 and updating back to 7.1 it now stuck on java 8.

**Comment by getchoo** [comment]
i've found a way to produce in not just flatpak, but nix as well (thus the issue name change). trying to figure out the bad commit now :)

**Comment by TheKodeToad** [comment]
I've got some bad news for ya
you've been scrumped

jokes aside, i think i have a fix ;p
