### ISSUE TITLE
Prism Launcher only says "working" when logging into a microsoft account

### ISSUE THREAD

**Issue by K9vis** [PrismLauncher/PrismLauncher#1257]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

I can't log into my Microsoft account, it just says "working"
![image](https://github.com/PrismLauncher/PrismLauncher/assets/67525127/b7f0a557-e177-42e9-9b7b-9979bf525246)

### Steps to reproduce

II install the prism laucher whether the portable or the installer, and always gives the same error and I can not log in, I tried to re-install delete all files and re-install and did not work. I found it on the issue tracker, and have tried to reinstall and install it, but it doesn't work

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by biomseed** [comment]
disconnect and reconnect to internet

**Comment by K9vis** [comment]
I already did that and it didn't work

**Comment by K9vis** [comment]
I already did that and it didn't work

**Comment by K9vis** [comment]
I already did that and it didn't work

**Comment by K9vis** [comment]
I already did that and it didn't work

**Comment by Ryex** [comment]
try using alternate dns server

**Comment by K9vis** [comment]
I have also done this, I used google dns and it still doesn't work

**Comment by K9vis** [comment]
well I just solved it, if someone else is having the same problem go to settings, APIs, others, and change your user agent

**Comment by Ryex** [comment]
> well I just solved it, if someone else is having the same problem go to settings, APIs, others, and change your user agent

what did you change your user agent to?

**Comment by K9vis** [comment]
I switched to Mozilla/5.0, but if I try to add another account it still gives me the same, but I had done this and was already able to add my account. But I don't know if the error was fixed when I changed my user agent.

**Comment by Ryex** [comment]
well that at least is sane. The code for setting a user agent does not touch the auth flow. the user agent is never used in the auth requests.

For clarification. does this happen before or after you enter the user code on Microsoft's webpage?

**Comment by K9vis** [comment]
before, I click on add account, it just said "working" and I was even able to log in, now, when I try to start a game, it can't authenticate and offers to start offline

**Comment by K9vis** [comment]
well i will wait for an update or for the modrinth launcher to be released
