### ISSUE TITLE
Add a filter to "Download mods" screen for already installed mods

### ISSUE THREAD

**Issue by Superniquito** [PrismLauncher/PrismLauncher#1260]
### Role

I play minecraft on custom modpacks

### Suggestion

In the "Download mods" screen add a filter checkbox to hide installed mods

### Benefit

It would make it easier to search for new mods, specially in search by popular

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Should be off by default, easily toggled in the "Filter Options" section alongside the version match options.
Should be easy to implement since installed mods are already highlighted on the list.

**Comment by susan3333333** [comment]
Seconded, would love to be able to filter out already installed mods

**Comment by Mr-Lesbian** [comment]
Thirded, was going to suggest this myself if no-one else had, would be really helpful! Awesome to see it seems to be getting added? Based devs <3

**Comment by Trial97** [comment]
This is implemented already waiting to be accepted into the codebase
