### ISSUE TITLE
Crashes when trying

### ISSUE THREAD

**Issue by Mirandatz** [PrismLauncher/PrismLauncher#1265]
### Version of Prism Launcher

7.1

### Version of Qt

6.5.1

### Description of bug

Launcher crashes silently when trying to ad ATM 8 from curse forge.

### Steps to reproduce

Try to add ATM 8 from curse forge.

### Suspected cause

???

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
I know that I ask a lot but: this sounds a lot like a crash that was already fixed in develop(but not yet released as a version increment ) so can you try building the application from the source, and see if you can reproduce it?
If not you need to wait for the next release.

**Comment by Mirandatz** [comment]
Chief, I am gonna be honest. It looks like it's a pain to build. As in, it looks like it would be easier to create a container with all the requirements just to build the thing. I am think I am going to wait for the next release.

**Comment by Ryex** [comment]
or you could try one of the nightly builds. and see if they work
https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/5394098599

**Comment by Mirandatz** [comment]
@Ryex Thank you for the link! :D
Indeed, it no longer crashes on the nightly build (tried on Windows and on Linux). But I am also no longer able to join servers:

![image](https://github.com/PrismLauncher/PrismLauncher/assets/7132905/da0a4575-db24-4370-a409-44b696c597da)

**Comment by Trial97** [comment]
From my knowledge, Hexerei is a mod that blocked third-party apps so maybe you just need to update it manually.
