### ISSUE TITLE
Issues when translations was transfered ?

### ISSUE THREAD

**Issue by Pkrakmo** [PrismLauncher/PrismLauncher#127]
### Version of PolyMC

5.0

### Version of Qt

6.4.0

### Description of bug

I can see that the language is not 1:1 with that Poly had on some languages, but most notably is Norwegian nb_NO

https://hosted.weblate.org/projects/prismlauncher/launcher/nb_NO/

https://hosted.weblate.org/projects/polymc/polymc/nb_NO/

Any reasoning behind that ?

### Steps to reproduce

I love 🐢

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
Same with Russian. Some strings are just strange

**Comment by Scrumplex** [comment]
Not sure. Technically it should all be the same as before

**Comment by Scrumplex** [comment]
Looks like someone has been hard at work translating stuff for PolyMC there since we forked

**Comment by Pkrakmo** [comment]
Would it be ethical to copy their translations over to this project ?

**Comment by Scrumplex** [comment]
> Would it be ethical to copy their translations over to this project ?

From what I have heard there has been "a little trolling" on the polymc translations so it wouldn't make much sense

**Comment by Pkrakmo** [comment]
> > Would it be ethical to copy their translations over to this project ?
> 
> From what I have heard there has been "a little trolling" on the polymc translations so it wouldn't make much sense

I was thinking more if I should copy/proof-read what the author for the Norwegian translation has added from poly over to prism

**Comment by Scrumplex** [comment]
Sure, you can do that. The translations in both projects are available under a free and open source license
