### ISSUE TITLE
Use "legacy.curseforge.com" instead of "www.curseforge.com" for downloading mods

### ISSUE THREAD

**Issue by unilock** [PrismLauncher/PrismLauncher#1271]
### Role

I play modpacks that occasionally require manual downloads of mods from CurseForge, due to them being inaccessible from the API (having third-party downloads blocked).

### Suggestion

It would be nice if Prism Launcher would automatically open the download links to these mods using CurseForge's legacy domain ("legacy.curseforge.com") instead of their normal domain ("www.curseforge.com"), as the former downloads mods instantly, rather than having the user wait 5 seconds beforehand.

### Benefit

Downloading several mods with third-party downloads blocked would be much faster and more convenient.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I do have the feeling that this violates CurseForge's TOS somehow, but I'm not sure - hence the issue.

Notably, "www.curseforge.com" requires the user to have the tab *focused* for 5 seconds before starting a download, which is painful with modpacks that have many API-inaccessible mods. "legacy.curseforge.com" always starts the download immediately, as far as I'm aware.

**Comment by TheKodeToad** [comment]
Downloads instantly on both sites for me. I think it's related to being logged in or logged out (that was how I remember the behaviour).

**Comment by DioEgizio** [comment]
tbh it's 5 seconds for both. Pretty sure there are some userscripts for bypassing it but definitely not 5 seconds only on the new page

**Comment by TheKodeToad** [comment]
![Screencast from 2023-06-25 14-32-50.webm](https://github.com/PrismLauncher/PrismLauncher/assets/57493648/934610f5-0b62-44e7-81df-e1fabe01d9ac)
this is with no userscripts!

**Comment by TayouVR** [comment]
some of my browser addons (probably FastForward) remove the 5s on both sites.

But either way, I don't think it makes sense for us to support the legacy site. At some point I'm sure curseforge is going to remove it anyways.
Sure, if someone is willing to PR a toggle to switch to the legacy site, I wouldn't be opposed to approving and merging it. I just don't think its worth the development effort.

**Comment by TheKodeToad** [comment]
Ohh, okay. it was one of my extensions for me! So the legacy site does remove the delay (only if you're logged in though :P)

**Comment by unilock** [comment]
It seems it *is* related to whether you're logged in. On www, I have the 5 second wait regardless; but on legacy, I only get the 5 second wait if I'm *not* logged in; otherwise the download starts immediately.

I agree that it wouldn't be a good idea to make a complete switch, since the legacy site will likely be removed at some point anyway.

Honestly, it would probably be best for the user to just use a userscript that automatically redirects from `https://www.curseforge.com/minecraft/mc-mods/<slug>/download/<file_id>` to the `legacy` equivalent - or an extension that removes download wait times, as previously mentioned.

That being said, I'll close this as "not planned", since even a toggle to use the legacy website would be rendered obsolete soon enough.
