### ISSUE TITLE
Launching instance from command line causes segmentation fault

### ISSUE THREAD

**Issue by YellowLemon571** [PrismLauncher/PrismLauncher#1273]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

I attempted to launch a specific instance from command line. Since I am using the Flatpak version, the command I used was `flatpak run org.prismlauncher.PrismLauncher --launch "SkyFactory 4"`. The launcher loads my account and some assets before promptly terminating itself with a SIGSEGV signal. The relevant logs [are here](https://mclo.gs/BXlN40W) and the generated coredump [is attached here.](https://github.com/PrismLauncher/PrismLauncher/files/11861154/coredump.zip)
On another note, I've temporarily gotten around the issue by using the prismlauncher-git AUR package and directly invoking the launcher's binary instead of running via Flatpak. I want to continue using Flatpak, however, so I would like to figure out this current issue.

### Steps to reproduce

* Install Prism Launcher via Flatpak: `flatpak install flathub org.prismlauncher.PrismLauncher`
* Configure initial settings, add account and import (known working) instance named "SkyFactory 4"
* Exit Prism Launcher and attempt to run instance using `flatpak run org.prismlauncher.PrismLauncher --launch "SkyFactory 4"`
* Watch as Prism Launcher loads account/assets then promptly crash

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by whitebear60** [comment]
The same goes for launching an instance from the desktop shortcut on macOS. The error log from the system crash window is available here: https://mclo.gs/Y9ZUGeF

**Comment by Ryex** [comment]
fixed with #1302
