### ISSUE TITLE
1.20.x missing

### ISSUE THREAD

**Issue by 0xIO32** [PrismLauncher/PrismLauncher#1287]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

I should be able to select 1.20 or 1.20.1 as version

### Steps to reproduce

* create a new Instance
* 1.20.x is missing -.-

### Suspected cause

It's maybe just not updated. (MultiMC has 1.20.x as version listed)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
See #1136
