### ISSUE TITLE
Attack of the B-Team fails to install due to version.json

### ISSUE THREAD

**Issue by Teelair** [PrismLauncher/PrismLauncher#1289]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

When attempting to install Attack of the B-Team, the launcher appears to successfully download all the mods, then fails close to the end saying:

`Could not understand "version.json": inheritsFrom is missing`

![image](https://github.com/PrismLauncher/PrismLauncher/assets/22324401/9eed7871-7fda-493f-a5ab-b87e2fb7f13f)

### Steps to reproduce

- Click Add Instance
- Go to Technic
- Search for "Attack of the B-Team"
- Click Ok
- Wait for it to fail

### Suspected cause

Not exactly sure what's up here, but Attack of the B-Team is based on 1.6.4. Technic is able to download it as expected though, so I think Prism should support this.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by 0TheWildcat0** [comment]
I have the same problem on Linux mint 21.1.

**Comment by polocatfan** [comment]
Same problem on Windows 11 x86_64

EDIT: I can't download them on Technic either, so I think their site is having issues. So not really a prism issue.
EDIT 2: Started working again on Technic so nvm.

**Comment by Mariocraft95** [comment]
Having same issue on version 7.2 still. Same error message

**Comment by Firlaev-Hans** [comment]
Same issue with Tekkit, which is also 1.6.4 based

**Comment by Trial97** [comment]
This is solved in the latest develop.
I will close this as done if you are still experiencing this after the 8.0 release please let us know
