### ISSUE TITLE
Integrate QTWin11 theme into PrismLauncher

### ISSUE THREAD

**Issue by e-splat** [PrismLauncher/PrismLauncher#129]
### Role

Launcher interface

### Suggestion

i like this template theme app here https://github.com/witalihirsch/QTWin11, it is more like the Win11

### Benefit

benefit for my eyes, default dark theme is so ugly

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by sowelipililimute** [comment]
Note that Qt stylesheets have a *lot* of issues; see https://www.kdab.com/say-no-to-qt-style-sheets/

**Comment by DioEgizio** [comment]
this can be done as a custom theme, and we already have [a dark one](https://github.com/PrismLauncher/Themes/tree/main/themes/Fluent-Dark)

**Comment by Trial97** [comment]
Closing in favor of https://github.com/PrismLauncher/PrismLauncher/issues/208 and https://github.com/PrismLauncher/PrismLauncher/issues/362
