### ISSUE TITLE
Export into Curseforge format

### ISSUE THREAD

**Issue by TheAirBlow** [PrismLauncher/PrismLauncher#1291]
### Role

Modpack development

### Suggestion

Have ability to export into Curseforge format, manifest.json is already maintained in flame folder

### Benefit

So modpack developers could use Prism instead of the Curseforge app

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheAirBlow** [comment]
Duplicate of #269

**Comment by TheKodeToad** [comment]
Hmm, i think having a separate issue would've been ideal in the first place

**Comment by TheAirBlow** [comment]
> Hmm, i think having a separate issue would've been ideal in the first place

oh wow

**Comment by ColonelGerdauf** [comment]
I think a bit of caution is needed for this. For modpacks loaded by or registered from CF, yeah, this is useful. The recent inclusion of trusted third-parties can throw a wrench into things.

But the like should also happen with Modrinth modpacks; loading the mod provider as Modrinth default.
