### ISSUE TITLE
Change the way of displaying shortcuts

### ISSUE THREAD

**Issue by tjw123hh** [PrismLauncher/PrismLauncher#1295]
### Role

I use Prism Launcher.

### Suggestion

I want another way of displaying shortcuts instead of underlining the letter of it in the name of the actions.

### Benefit

Or Some language translations need to be followed by parentheses such as "启动（L）" in Simplified Chinese which makes the interface look ugly even if you haven't press Alt.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It looks like this:
![图片](https://github.com/PrismLauncher/PrismLauncher/assets/56749271/6771e143-03a3-4bac-94bc-e654da216377)

**Comment by Ryex** [comment]
This is a limitation of Qt. These shortcuts are denoted by an underlined character created by marking that character with a `&` in the name. It is up to the translators to translate the string and mark the new shortcut with a reasonable mnemonic.
The only alternative is to hard code the shortcuts and leave no way to translate them.

**Comment by TayouVR** [comment]
ignoring Qt limitations, in terms of UX the shortcut could be denoted in the tooltip, making the actual text cleaner.
But thats not how Qt works normally, so we would have to build our own solution for those shortcuts then
