### ISSUE TITLE
Settings are sometimes reset after crash

### ISSUE THREAD

**Issue by Anthonity** [PrismLauncher/PrismLauncher#1296]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

From time to time, Prism starts crashing with “Instruction at 0x000… Referenced Memory at 0x000000000000. Memory Cannot Be Read” errors for me. Often after the crash, the settings are reset and I have to set them back again. It happens at random intervals

### Steps to reproduce

1. Open Prism
2. Try to install a mod
3. Prism crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TayouVR** [comment]
this seems very odd.. could you send the entire (or a larger section of the end of) PrismLauncher0.log after it happens? (stored in the logs folder in Prism Launchers data directory) 
Might give us a stacktrace or smth.. anything that would indicate where in the code it happens.

**Comment by Trial97** [comment]
Any updates on this issue?

**Comment by Trial97** [comment]
Closing this as no further information was provided. Feel free to repoen it once you can provide more info regarding this.
