### ISSUE TITLE
Change the UA

### ISSUE THREAD

**Issue by tjw123hh** [PrismLauncher/PrismLauncher#1300]
### Role

I use Modrinth to download resource.

### Suggestion

Change the UA to "PrismLauncher/PrismLauncher/7.1 (prismlauncher.org)" like Modrinth suggests.

### Benefit

see https://docs.modrinth.com/api-spec/#section/User-Agents

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Ryex** [comment]
the default user agent string is `PrismLauncher/{Version}`  All Modrinth asks is that it is unique and identifying. and this certainly is.
