### ISSUE TITLE
Some strings do not support localization

### ISSUE THREAD

**Issue by tjw123hh** [PrismLauncher/PrismLauncher#1307]
### Operating System

Windows, macOS, Linux, Other

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 5.15.8

### Description of bug

Some strings in many interfaces cannot be found on [the translation website](https://hosted.weblate.org/projects/prismlauncher/launcher).

### Steps to reproduce

Open the following interface:

- ![图片](https://github.com/PrismLauncher/PrismLauncher/assets/56749271/8aef0223-811b-4b9e-9949-11c1a9a9df52)

- ![图片](https://github.com/PrismLauncher/PrismLauncher/assets/56749271/f86be278-46e1-48be-92a8-9ca8bb7146e0)

- ![图片](https://github.com/PrismLauncher/PrismLauncher/assets/56749271/7f43cac3-06d2-4501-9065-0b8f2cf89e69)

- ![图片](https://github.com/PrismLauncher/PrismLauncher/assets/56749271/91284072-3926-43a6-851c-e8d6262cba29)

- ![图片](https://github.com/PrismLauncher/PrismLauncher/assets/56749271/c1567341-a82c-4068-89f6-8bd5789abe5a)

### Suspected cause

These strings are not enabled for localization(?)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Some of these strings were recently updated in our develop branch, so they will not be available on Weblate. This should fix itself once 7.2 or 8.0 releases

**Comment by Scrumplex** [comment]
We currently don't have a better way to deal with translation strings in multiple versions. So this is gonna happen every now and then. This will definitely be fixed in an upcoming release though.
