### ISSUE TITLE
How tf do I use prism launcher with Shadow Play.

### ISSUE THREAD

**Issue by master7720** [PrismLauncher/PrismLauncher#1308]
### Goal

Gefore ShadowPlay cant seem to detect prism launcher anyone know a fix to this??

### Motivation

i hate my life

### Specification

i hate my life

### Drawbacks

i hate my life

### Unresolved Questions

how to fix.

### Alternatives Considered

i hate my life

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by getchoo** [comment]
https://www.makeuseof.com/windows-geforce-experience-add-game/

please don't add unnecessary comments to issues in the future

edit: also see the [CoC](https://github.com/PrismLauncher/PrismLauncher/blob/develop/CODE_OF_CONDUCT.md)
