### ISSUE TITLE
Minecraft fails to launch with non-latin characters in windows name

### ISSUE THREAD

**Issue by a-name-real** [PrismLauncher/PrismLauncher#131]
### Operating System

Windows

### Version of PolyMC

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

Launching instance in prism launcher does not work when the windows user folder includes non-latin characters.
After clean installation of the launcher trying to launch any minecraft version/snapshot/modpack will cause the following error:

Oct 19, 2022 10:26:01 PM org.prismlauncher.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
    at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
Oct 19, 2022 10:26:01 PM org.prismlauncher.EntryPoint main
INFO: Exiting with 1
Process exited with code 1.

### Steps to reproduce

-Create a new windows user with non-latin characters (Cyrillic in this case)
-Install prism launcher as normally
-Make new instance and try to launch the game

### Suspected cause

Windows user folder with non-latin/cyrillic name is most likely causing this issue as it works on the same system with latin-only user folder.
Seems to be caused only if "Use Unicode UTF-8 for worldwide language support" is enabled in Control Panel > Region > Administrative > Change System Locale

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Can you confirm if this is still the case?

**Comment by a-name-real** [comment]
On Prism Launcher 5.2 with enabled windows feature "Beta: Use Unicode UTF-8 for worldwide language support" still gives the same error when launching.
If the said feature is disabled game starts without problem.
