### ISSUE TITLE
"PrismLauncher" on Mac menu bar

### ISSUE THREAD

**Issue by RuiNtD** [PrismLauncher/PrismLauncher#132]
Should be named "Prism Launcher" instead of "PrismLauncher" on the MacOS menu bar.

<img width="290" alt="CleanShot 2022-10-19 at 21 29 51@2x" src="https://user-images.githubusercontent.com/29142128/196786004-2f102826-47f4-410f-84d5-5a513cd99ff1.png">

_Originally posted by @tobimori in https://github.com/PrismLauncher/PrismLauncher/issues/126#issuecomment-1284476930_

**Comment by ryanccn** [comment]
this, `Prism Launcher` would be more suitable than `PrismLauncher`

**Comment by Scrumplex** [comment]
Is this controlled by the name of the .app?

**Comment by tobimori** [comment]
<img width="613" alt="CleanShot 2022-10-22 at 12 54 29@2x" src="https://user-images.githubusercontent.com/29142128/197335314-1f6494fb-59b5-4ba6-a782-85722124f40c.png">
nope, manually renaming doesn't work.

It reads its info from the Info.plist file that's included with every Mac app. Responsible string here is CFBundleName.
<img width="385" alt="CleanShot 2022-10-22 at 12 55 01@2x" src="https://user-images.githubusercontent.com/29142128/197335357-b82f4728-7f71-4920-9b7a-9f2030151d1c.png">

Setting that fixes the issue.
Besides that, \n isn't supported in NSHumanReadableCopyright and CFBundleGetInfoString includes the wrong app name tho (although it doesn't seem to be displayed anywhere).

**Comment by Scrumplex** [comment]
Should be a matter of updating these values here then: https://github.com/PrismLauncher/PrismLauncher/blob/54c26b05faa73dd6c8eb21f6fa898d438a3e867a/CMakeLists.txt#L225-L232
