### ISSUE TITLE
Unable to write or copy/paste on the Curseforge Core API box

### ISSUE THREAD

**Issue by An12854** [PrismLauncher/PrismLauncher#1323]
### Operating System

Windows, Linux

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

Can't modify the api key for Curseforge, won't let me write or copy/paste

### Steps to reproduce

* Open Settings > API > API keys
* Try to write or paste something in the Curseforge API box

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
You have to write https:// at the start
However I think this should be changed in future

**Comment by An12854** [comment]
Problem is i can't write or paste anything, can't even write or paste https://

**Comment by Scrumplex** [comment]
Make sure that there are no spaces in the copied api key. That's usually the reason why it might not work

**Comment by TheKodeToad** [comment]
Sorry I wasn't paying attention. It's not meant to contain https://
oops :sweat: 

I can't type either...

**Comment by An12854** [comment]
Not your fault the place i got it from had a letter wrong, thank you anyways

**Comment by joendter** [comment]
I have the same problem (unable to write anything into the text box)
I'm on Win11, Prism 8.0, Qt 6.6.0

**Comment by Trial97** [comment]
Write the token in some kind of text editor first, then copy-paste it fully inside that box.
If it did not paste(the input is still empty) that means it is not a valid token.

**Comment by Tomhero200** [comment]
I found a fix for now.

1. First, go to the Prism Launcher directory ( [Check this documentation page for where it is located on your operation system](https://prismlauncher.org/wiki/getting-started/data-location/))
2. If you haven't already, close Prism Launcher.
3. Then, in the the Prism Launcher directory, open the file called 'prismlauncher.cfg'
4. In this file, locate the entry 'FlameKeyOverride' and paste your key directly after the '=' (NO SPACES between the = and the key)
5. Save and close the file
6. Open Prism Launcher
7. Check the settings, if your key has appeared.

Hope this helps.

Edit: fixed typo

**Comment by Tomhero200** [comment]
Note: This now allows to write into the Token box in the settings directly.

**Comment by midvightmirage** [comment]
whenever i open prismlauncher it clears the api key
