### ISSUE TITLE
Microphone usage on MacOS fails

### ISSUE THREAD

**Issue by Ryex** [PrismLauncher/PrismLauncher#1327]
### Role

Developer who has seen complaints

### Issue

Users complain about being unable to access microphone on MacOS

mods like simple voice chat  should be able to use the microphone

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

https://developer.apple.com/documentation/bundleresources/information_property_list/nsmicrophoneusagedescription?language=objc

**Comment by Ryex** [comment]
Wait a moment.... 
https://github.com/PrismLauncher/PrismLauncher/blob/develop/cmake/MacOSXBundleInfo.plist.in#L7
we *already* have this permisison...
_And_ the audio device input entitlement
https://github.com/PrismLauncher/PrismLauncher/blob/develop/program_info/App.entitlements#L9

Why can't people use the microphone then?

**Comment by DioEgizio** [comment]
Yep we have had it for an year now, since https://github.com/PrismLauncher/PrismLauncher/commit/9462dd3ddc55e3e48e47ca794c05e11cabb6226e

**Comment by RustyKnight** [comment]
On my 3.1 GhZ Quad-Core Intel Core i7 15" 2017 MacBook Pro, I am prompted for Microphone access
On my Apple M2 15" 2023 MacBook Air I am not

Both are running Ventura 13.4.1

Possibly might have to do with having Java 20 JDK installed on the MacBook Air

Download 7.1 via brew

Tried removing JDK 20 and Prism 7.1, installing JDK 17 and reinstalling Prism 7.1 and still not getting prompted for Microphone access

Any way to force it?

**Comment by RustyKnight** [comment]
So, apparently, once I launched an instance and connected to a valid server with Simple Voice Chat installed - I was prompted for micro phone access - this was a little unexpected, but not unwelcome, as prompting before might have had me asking questions
