### ISSUE TITLE
Instance update failed because: Failed to read the assets index!

### ISSUE THREAD

**Issue by An12854** [PrismLauncher/PrismLauncher#133]
### Operating System

Windows 10 Home 21H1

### Version of PolyMC

PrismLauncher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

Launching a modpack copied from the `instances` folder from PolyMC takes a long time and it ends with `Instance update failed because: Failed to read the assets index! `

```
Prism Launcher version: 5.0


Launched instance in online mode

authserver.mojang.com resolves to:
    [13.225.11.45, 13.225.11.35, 13.225.11.57, 13.225.11.51]

session.minecraft.net resolves to:
    [34.199.236.154, 100.24.172.95, 35.153.153.200]

textures.minecraft.net resolves to:
    [13.225.244.120, 13.225.244.43, 13.225.244.31, 13.225.244.58]

api.mojang.com resolves to:
    [13.225.244.69, 13.225.244.13, 13.225.244.78, 13.225.244.75]


Minecraft folder is:
C:/Users/an12854/AppData/Roaming/PrismLauncher/instances/Bliss - a peaceful-like experience/minecraft


Java path is:
C:/Program Files/Eclipse Adoptium/jdk-17.0.4.101-hotspot/bin/javaw.exe


Checking Java version...
Java is version 17.0.4.1, using 64 (amd64) architecture, from Eclipse Adoptium.


Instance update failed because: Failed to read the assets index!

```

### Steps to reproduce

Copy an instance from the `instances` folder in PolyMC to PrismLauncher, launch the modpack and after some minutes the error should occur

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by An12854** [comment]
The launcher works correctly on Fedora Linux on kernel version 5.19.15-202.fsync.fc36.x86_64 with Qt 6.2.4

**Comment by DioEgizio** [comment]
try going to help- clear metadata cache and try again

**Comment by Scrumplex** [comment]
Clear Metadata seemingly doesn't work all the time :(

**Comment by An12854** [comment]
It doesn't work, I've tried reinstalling PrismLauncher even and moved those instances to another folder and created a new one

**Comment by An12854** [comment]
Got it fixed
apparently i just bruteforced it by launching many times.

**Comment by MrDefined** [comment]
> Got it fixed apparently i just bruteforced it by launching many times.

this also worked for me lol

**Comment by thisiskret** [comment]
> Got it fixed apparently i just bruteforced it by launching many times.

me when i'm unhelpful

**Comment by Niterux** [comment]
Can it be made possible to launch the game without updating the assets indexed? I don't need my assets updated *every single time* I play the game!!!!

**Comment by deustch1** [comment]
doesnt work for me. i tried bruteforcing and nothing. how to fix pls help! ive tried re installing and everything else. im on pollymc 7.0

**Comment by Ryex** [comment]
> im on pollymc 7.0

your problem
