### ISSUE TITLE
Permanently delete old mods after updating them

### ISSUE THREAD

**Issue by MbtMarco** [PrismLauncher/PrismLauncher#1330]
### Role

I play modded Minecraft.

### Suggestion

On macOS when you update mods, the older ones do not disappear completely but are moved to the trash. In my opinion it would be better to delete them permanently without moving them to the trash.

### Benefit

I don't find it convenient to empty the trash every time I update mods.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
This I probably a bug I caused! :blush: 

Anyway, I shouldn't be proud; I should try to fix this :P
