### ISSUE TITLE
Viewing the Managed Pack tab for certain packs from CF crashes PrismLauncher

### ISSUE THREAD

**Issue by YoYoK3nny** [PrismLauncher/PrismLauncher#1349]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0 (Debug Build: `c897a62`)

P.S: This issue has existed in previous versions.

### Version of Qt

Qt 6.5.1

### Description of bug

Attempting to view this tab on certain packs crashes the app.

What I expect to happen is that any info that is not obtainable is left blank (or what happens with a self-made pack that doesn't exist ie: invalid pack)

### Steps to reproduce

1. Import the attached instance.
2. (Optional Step) In the CF App, install v1.0.6 of "Create a Colony - MineColonies / Create / MCA" (Project ID: 833835, File ID: 4477406)
3. (Optional Step) Copy the files from the Instance in the CF App into the ".minecraft" folder in the attached instance.
4. Edit the attached instance and switch to the Managed Pack tab.
5. PrismLauncher will proceed to crash after a small delay.

### Attachments
[Create a Colony v1.0.6-nofiles.zip](https://github.com/PrismLauncher/PrismLauncher/files/12027790/Create.a.Colony.v1.0.6-nofiles.zip) - _Note: modpack contents not included_
[PrismLauncher.log](https://github.com/PrismLauncher/PrismLauncher/files/12027987/PrismLauncher.log) - (cleared of personal and irrelevant details)

### Suspected cause

I suspect the modpack author has disallowed installing the pack in third-party launchers as trying to install the pack normally in PrismLauncher shows "no valid versions"

Also: The managedpack settings in the instance.cfg were manually added after importing the downloaded modpack zip, though it should have the correct entries/values.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by YoYoK3nny** [comment]
P.S: I am using a debug build due to certain download tasks during instance creation/update crashing the app.

**Comment by Trial97** [comment]
So this is happening because Curseforge restricting the third-party apps: that modpack is only downloadable from curseforge app now, or imported as a zip file in the launcher.
The proposed fix in the PR only loads a message that it failed to retrieve the data.

**Comment by YoYoK3nny** [comment]
As long as the crash no longer happens I'll be happy.

Cheers for the quick fix on this (I'll try it out once the build action finishes)

EDIT: Works perfectly, thank you. 😄
