### ISSUE TITLE
Crash on MacOS when choosing "Custom" color scheme

### ISSUE THREAD

**Issue by GhostIsBeHere** [PrismLauncher/PrismLauncher#135]
### Operating System

macOS

### Version of PolyMC

PrismLauncher 5.0

### Version of Qt

Qt 5.15.2

### Description of bug

When choosing "custom" color scheme, the app crashed.

### Steps to reproduce

- Be on MacOS Legacy
- Go to Settings
- Go to User Interface
- Change "Colors" from "System" to "Custom"
- Crash

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Still happening?

**Comment by GhostIsBeHere** [comment]
Crash no longer occurs!

**Comment by DioEgizio** [comment]
Probably related to #510 btw
