### ISSUE TITLE
Headless browser for curseforge download

### ISSUE THREAD

**Issue by spookytea** [PrismLauncher/PrismLauncher#1353]
### Role

I play modded minecraft

### Suggestion

Download curseforge mods that require a browser headlessly

### Benefit

No user interaction needed to download mods

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Prism should check for an installed browser (chrome, chromium, firefox, etc.) or allow the user to add the browser's name (if it is in $PATH) or location in the preferences and launch a headless instance (using --headless which is supported on most if not all browsers) and kill the launched browser when the file is found in the downloads folder.

**Comment by TayouVR** [comment]
we had some discussion about this before somewhere, but it might've been off github (on discord), so lost to time.
The idea we had was to create or embed a browser profile with the launcher to redirect downloads right to the launcher (or right in the mods folder). With that attempt we could ofc launch the browser headless too.
However I think nobody ended up implementing that as it seemed a bit excessive.

Maybe someone in the future will show more interest in this idea. I think it would improve user experience overall.

**Comment by Ryex** [comment]
Implementing this would break the CurseForge TOS.
the browser must open and give the user the opportunity to see CurseForge's placed ads.
we could use an internal browser but we would need to render the ads and at that point why not use the user's installed browser.
