### ISSUE TITLE
Ability to Downgrade/Change Version of Installed Mods

### ISSUE THREAD

**Issue by vertexcubed** [PrismLauncher/PrismLauncher#1354]
### Role

I am a modpack developer.

### Suggestion

The ability to change an installed mod's version to any version(including older versions) without deleting and reinstalling the mod.

### Benefit

This would save time whenever a mod update crashes the game, as you'd only need to click one or two buttons instead of deleting the mod then installing it again.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

ATLauncher has a similar feature to this, where you can select a mod and "reinstall" it, which lets you select whatever mod version you want.

**Comment by YoYoK3nny** [comment]
You can already do this, just use the Mod Downloader and pick an older version of the mods that need downgrading.
No need to delete the mod to change versions.
The only exception is if the installed version of the mod has been archived or removed from the CDN, then you would need to delete the mod first in that case.

**Comment by P3rf3ctXZer0** [comment]
It does not do so successfully and instead keeps both mods ... @Trial97 @YoYoK3nny I am using stable 8.0

**Comment by Trial97** [comment]
@P3rf3ctXZer0 most probably you are experiencing https://github.com/PolyMC/PolyMC/issues/550 and I also have a PR for that: https://github.com/PrismLauncher/PrismLauncher/pull/1752

**Comment by P3rf3ctXZer0** [comment]
> @P3rf3ctXZer0 most probably you are experiencing [PolyMC/PolyMC#550](https://github.com/PolyMC/PolyMC/issues/550) and I also have a PR for that: #1752

This is exactly what is happening.

**Comment by bentterp** [comment]
Downgrading is not only for modpack developers, also useful for the rest of us:
When I do an update of all my mods, I get one in there which causes a crash. Now it would be very nice if I could rollback to a previous version and prevent the broken version from getting installed again. When the mods gets fixed and a newer version is released, I would want that to be picked up.
So I have beta1 installed and it works, beta2 comes out and has a bug, I mark beta2 as bad so we roll back to beta1 and wait for beta3
