### ISSUE TITLE
Make all launcher logs go into a 'logs' directory

### ISSUE THREAD

**Issue by he3als** [PrismLauncher/PrismLauncher#136]
### Role

I am a Prism Launcher user.

### Suggestion

I want there to be a dedicated logs folder, instead of launcher logs being placed into the root of the settings directory. For example, the Prism Launcher AppData folder on Windows.

### Benefit

So that it is more organised and clean.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://user-images.githubusercontent.com/65787561/196805814-e79fec84-4374-4c50-aa05-5146f3bad781.png)

**Comment by Scrumplex** [comment]
Sounds like a good idea and should be fairly simple to do
