### ISSUE TITLE
When uploading a log let the user know it's been added to the clipboard along with having a clickable link

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#1361]
### Role

I play modded Minecraft

### Suggestion

When uploading a log let the user know it's been added to the clipboard along with having a clickable link

### Benefit

So people will know it's been added along with getting to the site easier

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It used to be there but after the Prism launcher 7.0 update it's been removed

**Comment by Trial97** [comment]
Can you add the steps on how to reproduce this?
When trying to upload an instance log I get this:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/72f8915d-a348-4ca0-9035-72eb9e6914bf)
where it clearly states that the link was copied to the clipboard and the link is clearly visible on the dialog(the red text)

**Comment by Aces-and-Jacks** [comment]
https://github.com/PrismLauncher/PrismLauncher/assets/106651342/c45c0638-aef1-4bee-9c4e-0b1305caba7e

**Comment by Aces-and-Jacks** [comment]
maybe it's just a mac issue

**Comment by Trial97** [comment]
maybe, I was able to reproduce it with the version from the website(on mac) but with the latest develop I got the dialog. 
So most probably it was already fixed.
You can try to test it on the nightly build or wait for the next release and test it then.

**Comment by pog5** [comment]
Already fixed in latest develop release

**Comment by Aces-and-Jacks** [comment]
If this was fixed in the develop release I'm not sure which version the fix will be made. In the recent 7.2 update it still occurs

**Comment by Trial97** [comment]
Is this still an issue on 8.0?

**Comment by Aces-and-Jacks** [comment]
It's fixed

**Comment by Aces-and-Jacks** [comment]
A clickable link would still be nice but the issue overall is fixed

**Comment by Trial97** [comment]
There is a clickable link (the red text is the link):
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/f973fe88-2257-4dec-8b76-8b05c50103ec)

**Comment by Aces-and-Jacks** [comment]
I don't get that on Mac. It just says the link has been copied to the clipboard

**Comment by Aces-and-Jacks** [comment]
Wait...I confused this with a different issue. This should still be open

**Comment by Aces-and-Jacks** [comment]
So before in the clip I showed the box just disappeared but now the dialog box shows, just without the clickable link

**Comment by Trial97** [comment]
can you click that text(maybe is a theme issue)

**Comment by Aces-and-Jacks** [comment]
<img width="372" alt="Screen Shot 2023-11-16 at 9 13 18 PM" src="https://github.com/PrismLauncher/PrismLauncher/assets/106651342/bcab52e3-608e-4822-b26a-15ed015af242">

Didn't think about including a screenshot but basically this is what shows

**Comment by Aces-and-Jacks** [comment]
Not sure if it's mac specific

**Comment by Trial97** [comment]
Yep, that is a mac limitation.
I will close this ticket now that the message at least appears.
