### ISSUE TITLE
Modded Minecraft Not Starting

### ISSUE THREAD

**Issue by IrisWasTaken1** [PrismLauncher/PrismLauncher#1366]
### Operating System

Windows 11 22H2

### Version of Prism Launcher

Prism Launcher 7.3

### Version of Qt

Qt 6.5.1

### Description of bug

Minecraft crashes upon attempting to start.
Log file:
https://paste.gg/p/anonymous/ee223c98df7c456ca7584a9c13d19146

### Steps to reproduce

idk

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by IrisWasTaken1** [comment]
Mods Installed:
https://drive.google.com/drive/folders/1CRBNVPV0DIe8O_hdDoy9Mguyc59GKKLu?usp=sharing

**Comment by Ryex** [comment]
This is not a launcher bug but an issue with your instance configuration
