### ISSUE TITLE
Minecraft 1.16.5 don't working multiplayer if you use custom modpack

### ISSUE THREAD

**Issue by pandamonkeez** [PrismLauncher/PrismLauncher#1367]
### Version of Prism Launcher

7.1

### Version of Qt

Qt 6.5.1

### Description of bug

Minecraft 1.16.5 don't working multiplayer if you use custom modpack. But if you use any other assembly or version, then everything is ok.

### Steps to reproduce

-

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
We'd need more information to investigate this (such as logs), but it doesn't sound like an issue with the launcher!

This isn't the place for support.
