### ISSUE TITLE
Mac app should be called "Prism Launcher.app"

### ISSUE THREAD

**Issue by RuiNtD** [PrismLauncher/PrismLauncher#137]
Apparently, the name of the .app file for Mac is `PrismLauncher.app` instead of `Prism Launcher.app`

_Originally posted by @tobimori in https://github.com/PrismLauncher/PrismLauncher/issues/126#issuecomment-1284476930_

**Comment by Goobaroo** [comment]
Duplicates #132

**Comment by RuiNtD** [comment]
> Duplicates #132 

I literally posted that other issue. I don't know how Mac works, but unless the filename directly correlates to the name shown in the menu bar, it's not a duplicate.

**Comment by DioEgizio** [comment]
Fixed in develop
