### ISSUE TITLE
Interface bug when "System" is selected in "Colors".

### ISSUE THREAD

**Issue by MbtMarco** [PrismLauncher/PrismLauncher#1389]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

I cannot find this information.

### Description of bug

When in the interface settings choose between "Light," "Dark," or "System"; if you select system the interface has obvious differences that do not fit into the simple "Colors."

https://github.com/PrismLauncher/PrismLauncher/assets/124934175/14823cfe-e630-4c7c-b2e1-ae020252e5d8

### Steps to reproduce

Settings > User Interface > Change the "Colors" between "Dark"/"Light" and "System."

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TayouVR** [comment]
"Colors" in fact changes the QStyle, Qts widget style, which is way more than just colors as well as the QColorPalette, which is actually just colors.
Maybe we can rename that setting in the future to something like "Widget Theme" or just "Theme"

**Comment by TheKodeToad** [comment]
will be fixed in my pull request :3

**Comment by MbtMarco** [comment]
> will be fixed in my pull request :3

🥳 Ty.
