### ISSUE TITLE
Make it possible to update resource packs and shaders

### ISSUE THREAD

**Issue by MbtMarco** [PrismLauncher/PrismLauncher#1390]
### Role

I create modpacks.

### Suggestion

It would be nice if you could check and update the shaders and resource packs from the launcher.

### Benefit

Easy updates for resource packs and shaders as can be done with mods.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
similar to :https://github.com/PrismLauncher/PrismLauncher/issues/1207
