### ISSUE TITLE
ability to add custom source locations to mods

### ISSUE THREAD

**Issue by Dialgatrainer02** [PrismLauncher/PrismLauncher#1393]
### Role

i use mods that are only available to download off github

### Suggestion

allow for custom mod download urls 

### Benefit

get more up to date version not on mopdrinth or that arent on modrinth/curseforge

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

 please add the ability to use custom mod download urls for example from github and potentially specify file name to save time when updating

**Comment by Trial97** [comment]
sounds similar to: https://github.com/PrismLauncher/PrismLauncher/issues/1155

and here for modpack:https://github.com/PrismLauncher/PrismLauncher/issues/694

**Comment by Dialgatrainer02** [comment]
oops clearly didnt look hard enough at the other issues
