### ISSUE TITLE
Allow updating instances through mrpack

### ISSUE THREAD

**Issue by MenacingPerson** [PrismLauncher/PrismLauncher#1394]
### Role

I make a modpack I want to update locally

### Suggestion

I want an updater for local mrpacks, instead of requiring modrinth publishing

### Benefit

So it's not required to publish the mrpack to modrinth

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Okay, imagine this:

You import an instance through an mrpack

You want to update it, so you use another, separate mrpack, which is a more up-to-date/newer version of the first one

Prism Launcher allows you to update the existing instance through the new mrpack, copying over the options.txt, config, any custom-added mods, resourcepacks, preferences, whatever is done with the current modrinth modpack updater.

You don't need to publish it to modrinth, so you can use it to test beta versions/run long-running mutations of your modpack.

**Comment by gBasil** [comment]
@Trial97 I'm running the most recent build artifact and that change doesn't seem to work for modpacks installed through .mrpack files (the management page doesn't show up at all), only modpacks installed directly from Modrinth or CurseForge.

**Comment by Trial97** [comment]
Thanks, I created a new PR regarding this. 
If merged this should allow you to update from file all instances.

**Comment by Trial97** [comment]
I reopened to track the progress.
Also opened another PR that does the same but is limited to only packs created using curseforge or modrinth pack files.
