### ISSUE TITLE
Empty accounts list message doesn't correctly reflect the UI

### ISSUE THREAD

**Issue by MMK21Hub** [PrismLauncher/PrismLauncher#1410]
### Operating System

Linux

### Version of Prism Launcher

PrismLauncher 7.1
34d80a8c754ffa2e79cbde2be54b8de7d3f1a67c

### Version of Qt

5.12.8

### Description of bug

When viewing the **Accounts** tab of **Settings**, and there aren't any registered accounts, a message is shown to instruct the user on how to add an account:
> Welcome!
> If you're new here, you can click the \"Add\" button to add your Mojang or Minecraft account.

However, this message references "The "Add" button", which isn't a button that exists in the Accounts UI. In addition, it doesn't mention Microsoft (MS) accounts, which are now used by the majority (?) of players. For context, there are three different buttons for adding accounts: **Add Microsoft**, **Add Mojang** and **Add Offline**.

Since legacy Minecraft accounts are increasingly rare (if they even still function), and Offline accounts require an Online account to be added first, it seems sensible to mention Mojang and MS accounts in this message. For example:

> Welcome!
> If you're new here, click the "Add Microsoft" button to sign in, or "Add Mojang" to use an old Mojang account.

The phrasing above points the user towards MS accounts as a primary option, which are used by ["millions" of players](https://www.minecraft.net/en-us/article/account-migration-last-call). As an alternative, the option below is more similar to the current message (but a bit more verbose):

> Welcome!
> If you're new here, you can click the "Add Microsoft" button to add your Microsoft account, or "Add Mojang" to add your Mojang account.

### Steps to reproduce

1. Hide your registered accounts by renaming `PrismLauncher/accounts.json` to `PrismLauncher/accounts.json.bak`
2. Open Prism Launcher
3. Navigate to **File** > **Settings** > **Accounts**

### Suspected cause

I assume that at some point in the past, the launcher simply had an "Add" button to add a Mojang/Minecraft account, but this was re-done when support for Microsoft accounts was added, without updating the new-user message.

The message is defined in [`AccountListPage.cpp`](https://github.com/PrismLauncher/PrismLauncher/blob/593f45298614843c14acb11994320f90a474c750/launcher/ui/pages/global/AccountListPage.cpp#L66).

### Screenshot

![A screenshot of Prism Launcher's Accounts page](https://github.com/PrismLauncher/PrismLauncher/assets/50421330/214611af-2ed9-493d-b85d-f8cdffc903be)

**Comment by MMK21Hub** [comment]
I've just realised that Mojang accounts do, in fact, still function. I've updated the issue description accordingly.

**Comment by TheKodeToad** [comment]
This is a very easy task! if you have any git/github knowledge it'd be appreciated if you could change the string :P

**Comment by MMK21Hub** [comment]
Sounds good - I'll take a look at making a PR! I'll use the first suggested message unless y'all have another preference.

**Comment by TheKodeToad** [comment]
Maybe
> Welcome! If you're new here, you can click the "Add Microsoft" or "Add Mojang" button to log in.

**Comment by MMK21Hub** [comment]
That sounds good!

**Comment by dannydorazio** [comment]
PR created— used grep to search through files and find two other instances of "minecraft account".
#1551
