### ISSUE TITLE
Crashes caused by the introduction of certain mods

### ISSUE THREAD

**Issue by rei-shirataki** [PrismLauncher/PrismLauncher#1421]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

I installed a mod called SpawnChecker and tried to start it, but minecraft crashed and wouldn't start.

The error does not occur when using the official minecraft launcher, so I assume the problem only occurs when using the Prism Launcher.

We have confirmed that the bug occurs in versions 1.7.10 and 1.12.2.
It may occur in other versions.

### Steps to reproduce

Install and launch SpawnChecker[[dropbox link](https://www.dropbox.com/sh/mlfsx6b3z5ek8wv/AACY9hwBeG6QnisIy3tgul0Ca/SpawnChecker?dl=0)]

### Suspected cause

I found a description in part of the error log that may be the cause of the problem, so I will describe it.

[12:44:58] [Client thread/ERROR] [FML]: The mod spawnchecker is expecting signature 26e70d58815b73cd7c6c865fe091672f79070a35 for source SpawnChecker-2.7.7.137.jar, however there is no signature matching that description
[12:44:58] [Client thread/ERROR] [spawnchecker]: 
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

 This mod may have been hacked. (modid: spawnchecker)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Please specify JVM option ’-Dspawnchecker.ignoreFingerprintViolation=true’ if you badly want to ignore this error.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Just do what the message says: add  `-Dspawnchecker.ignoreFingerprintViolation=true` to JVM arguments
Also closing this as prism doesn't have anything to do with the mentioned check
