### ISSUE TITLE
Launcher crashes while trying to update a modpack

### ISSUE THREAD

**Issue by peachey2k2** [PrismLauncher/PrismLauncher#1422]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 5.15.10

### Description of bug

Trying to update any modpack from CurseForge crashes the application. 
![image](https://github.com/PrismLauncher/PrismLauncher/assets/100072467/24f65425-ba6f-418f-a9ef-b9c6904a1ff2)
Right after showing this "Extracting modpack" prompt, it crashes with a segmentation fault.
[Here](https://github.com/PrismLauncher/PrismLauncher/files/12138608/PrismLauncher-1.log)'s a log file from an instance of the crash, happened while trying to update Supersymmetry from 0.1.4 to 0.1.5.

### Steps to reproduce

1. Open Prism Launcher.
2. Select an instance of a modpack installed from CurseForge.
3. Click "Edit".
4. Select "CurseForge" from the left panel.
5. Click on "Update pack"
6. It downloads the zip and crashes at "Extracting modpack" step.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by metalim** [comment]
Repeatable with many packs on MacOS as well

**Comment by nmcnew** [comment]
Happens on Windows 11 on version 7.1 stable. Was able to update by going through the install modpack wizard. Prompts to update pack and pack was updated without crashing.
