### ISSUE TITLE
Blocked mods found shown unnecessarily

### ISSUE THREAD

**Issue by syntheer** [PrismLauncher/PrismLauncher#1425]
### Role

Modpack manager

### Suggestion

Add an option to auto-approve the modpack update for blocked mods

### Benefit

There would be no need to click on "OK" button where no action required from user

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

In this example I tried to update a modpack to a new version (published on CurseForge), and got following window:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/9214228/70b14f5c-deb3-4692-859f-53d4c6bd7480)

The neoncraft mod was already in the Downloads folder when I clicked the "Update pack" button, so I don't know what's the benefit of asking me to just click OK, instead of directly going to update the modpack - since no manual action required from me.

**Comment by Ryex** [comment]
This is behavior as intended.

Hash collisions are a thing so it's possible that the file found is *not* the correct file so the user needs to verify that the correct file has been found.

**Comment by TheKodeToad** [comment]
that doesn't sound too plausible to me

**Comment by Ryex** [comment]
> that doesn't sound too plausible to me

while not probable it's still possible. 
A user verification isn't that much of an inconvenience.

**Comment by TheKodeToad** [comment]
yeah i don't think there's much benefit to removing this, and there may actually be drawbacks
