### ISSUE TITLE
Prismlauncher segfaults when updating instance

### ISSUE THREAD

**Issue by dhasial** [PrismLauncher/PrismLauncher#1430]
### Operating System

Arch Linux 64-bits

### Version of Prism Launcher

Prism Launcher 7.1
Commit: c264d0ad5942df9523fe1d52357f392e2a904350

### Version of Qt

Qt 5.15.10

### Description of bug

It's only after getting a bit into the update, it doesn't happen instantaneously. It also appears to happen at an arbitrary step in the process. Worst of all, it doesn't segfault every single time, just about 9/10 times and I end up just having to restart the launcher and try to update over and over again until it decides not to segfault.

I've experienced this issue since the prismlauncher fork.

[GDB backtrace](https://gist.github.com/dhasial/e790ab259e422c6a5245c0c14a48eb8d)

### Steps to reproduce

 Click on the "Curseforge" tab in the instance, then click the "update pack" button.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by KSPAtlas** [comment]
I am also experiencing this issue, attempting to update the curseforge modpack Supersymmetry from 0.1.4 to 0.1.5 (Running Flatpak). However, on my end, it seems to always occur, and at the same place (right at the end of extracting modpack)

**Comment by dhasial** [comment]
Yes, it seems to happen regardless of modpack or settings, I think it's maybe a race condition within the update function.

**Comment by Ryex** [comment]
can you replicate this in 7.2 or on develop?
