### ISSUE TITLE
Error/message when clicking check for updates with only disabled mods selected

### ISSUE THREAD

**Issue by mattp12** [PrismLauncher/PrismLauncher#1469]
### Version of Prism Launcher

Prism Launcher 7.2 (originally had 7.1, didn't realize 7.2 was out)

### Version of Qt

Qt 6.5.1

### Description of bug

When you select 1 or more mods that are disabled and click check for updates, the errors "[One of the tasks failed!](https://i.imgur.com/EmTuSz0.png)" and "[The mod updater was aborted!](https://i.imgur.com/FkwjEvm.png)" show up. 

Although Prism is made to not update mods that are disabled to [prevent duplicates](https://i.imgur.com/d0eTqtG.png), a similar message is not present when attempting to update _only_ mods that are disabled.

Updating disabled mods isn't something a user would be able to do anyway (and instead be greeted with the "no duplicates" screen), but making it clearer to a user who did not know disabled mods are excluded when attempting to update only disabled mods (and removing the error messages) would probably be beneficial.

I believe this error was mentioned here https://github.com/PrismLauncher/PrismLauncher/issues/1019#issuecomment-1591107888. 
I have not seen any issues made regarding this.

### Steps to reproduce

* Select an instance and click edit 
* Click the mods tab (make sure to have at least one mod)
* Disable a mod
* Select the disabled mod and click check for updates

The error appears.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by willrun4fun** [comment]
I am also getting this error now.  For me it is trying to do any kind of check for update.  This pack had no disabled mods.  I was trying to check enabled mods.

**Comment by Trial97** [comment]
> I am also getting this error now. For me it is trying to do any kind of check for update. This pack had no disabled mods. I was trying to check enabled mods.

That is because a shortage of modrinth API discussed here: https://github.com/PrismLauncher/PrismLauncher/issues/2095
