### ISSUE TITLE
Total playtime displayed as 0s

### ISSUE THREAD

**Issue by Ikethepro18** [PrismLauncher/PrismLauncher#1471]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt 6.5.1

### Description of bug

The total playtime in the lower right corner reads 0s despite having multiple days on several instances

### Steps to reproduce

* Launch Prism
* Total playtime: 0s

### Suspected cause

I believe this occurred after Prism crashed opening a game log while the running instance was hung but I honestly have no idea what could be causing it. I've played multiple instances for several minutes to see if it updates but it won't change

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Found here: https://discord.com/channels/1031648380885147709/1162832618564366488 that there wee a instance with negative total time played so we need to make sure that doesn't happen
