### ISSUE TITLE
Detection of JREs installed through SDKMAN! 

### ISSUE THREAD

**Issue by tomasz-brak** [PrismLauncher/PrismLauncher#1477]
### Operating System

Garuda Linux

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

 6.5.2

### Description of bug

#790 Enhancement was not implemented successfully 

Only cheked on linux, i _**don't**_ know how it behaves on windows

# System:
`Kernel: 6.4.6-zen1-1-zen arch: x86_64 bits: 64 compiler: gcc v: 13.1.1
    parameters: BOOT_IMAGE=/@/boot/vmlinuz-linux-zen
    root=UUID=0d041406-fe13-41c0-b9f2-4c294e2a1d84 rw rootflags=subvol=@
    quiet quiet rd.udev.log_priority=3 vt.global_cursor_default=0
    resume=UUID=dff8cd6b-a08c-479d-bb33-80f49a2c20cb loglevel=3 ibt=off
  Desktop: KDE Plasma v: 5.27.6 tk: Qt v: 5.15.10 wm: kwin_x11 vt: 2
    dm: SDDM Distro: Garuda Linux base: Arch Linux`

The launcher does not detect java versions installed by sdkman.

Only the java versions from pacman are visible:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/62989490/d34c0ab6-85b9-4004-a6f0-529463a15640)

### Steps to reproduce

* Download and install the launcher
* Download sdkman via curl [sdkman download docs](https://sdkman.io/install)
* Install at least one version of java
* The java exec will be located in `$HOME/.sdkman/candidates/java/... `
![image](https://github.com/PrismLauncher/PrismLauncher/assets/62989490/51f62f7c-d1ea-4358-877f-b0c01ff0c6b0)
* Autodetect java versions

### Suspected cause

Perhaps the launcher does not scan the folder here?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
We don't scan sdkman specifically, which is why it won't show up there. This could very well be implemented though

**Comment by tomasz-brak** [comment]
using sdkman is really convenient when you need to run a server on the same pc as your mc client. Because how easy it is to switch between java versions. Maybe later add an option to download java version directly from the launcher.

**Comment by tomasz-brak** [comment]
> We don't scan sdkman specifically, which is why it won't show up there. This could very well be implemented though

I will open a new enhancement issue for that then

**Comment by TheKodeToad** [comment]
Labels can be edited

**Comment by tomasz-brak** [comment]
> Labels can be edited

maybe add junior job too

**Comment by TheKodeToad** [comment]
hmmm.. I don't think that's necessarily applicable!

**Comment by ylluminate** [comment]
This would be nice - I fear I may not have time to make such a modification given my workload, but what needs to be done generally to facilitate this (using it on macOS here)?

**Comment by Scrumplex** [comment]
Implemented in #1682
