### ISSUE TITLE
provider unknown when I download mods or update them

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#1479]
### Operating System

macOS

### Version of Prism Launcher

7.2

### Version of Qt

6.5.0

### Description of bug

I expected the provider to show where it's from. Either curseforge or modrinth 

### Steps to reproduce

Download mod > provider unknown

Update provider unknown mod > provider unknown

### Suspected cause

Maybe it's a corrupted folder but I don't know what to delete. Happened after the 7.0 update I think

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment]
It's not with all of them but most of them

**Comment by futag** [comment]
also my windows app can read mod version

**Comment by Trial97** [comment]
Can you provide some logs?
Also had the same issue. In my case, a mod metadata file was corrupted, deleting that fixed it.

**Comment by Aces-and-Jacks** [comment]
@Trial97 [PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/12403519/PrismLauncher-0.log)

**Comment by Trial97** [comment]
> @Trial97 [PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/12403519/PrismLauncher-0.log)

For starter delete the following file: `PrismLauncher/instances/1.19.2 (Personal vanilla quilt)/.minecraft/mods/.index/betteraddserver.pw.toml`

As this just gives the first error and doesn't do anything, look into your logs for `"Could not open file <filename>!" and delete the specified name from the mods `.index` folder.
Obviously by deleting the file you lose the metadata regarding the mods , but a simple update should fix that.

Also if you have more trouble with this or you can not find the exact file to delete, please let me know( and add a new log file).

**Comment by Aces-and-Jacks** [comment]
ok I'll try this. Thanks so much for helping with this, otherwise would've been buried and left in dust probably

**Comment by Aces-and-Jacks** [comment]
Wait if I delete the pw.toml does that just refresh the source for that mod? Source as in provider

**Comment by Trial97** [comment]
No, it doesn't refresh the source automatically it just gets rid of the metadata for that one, and then after you see no more errors in the logs you can try to update the mods resulting in populating the metadata for the deleted files.

**Comment by Aces-and-Jacks** [comment]
Ok now it's weird. Whenever I delete the mod and the index file everything is normal but when I install it provider error returns

**Comment by Aces-and-Jacks** [comment]
Is that being caused by something with the mod?

**Comment by Trial97** [comment]
Is it just that mod?
~~Can you attach the logs with the installation also?
It helps if you specify the provider, Minecraft version, loader, and mod version.~~
No need for more info: for Quilt for 1.192 and the mod is betteraddserver from modrinth(I was able to reproduce it)

**Comment by Aces-and-Jacks** [comment]
ok, was typing out a long thought out chronological process of how it happened with 3 logs of each stage. But since you can reproduce all good now. If you have a hypothesis about why that mod is causing issues I'd be curious to hear, and thanks again for helping

**Comment by Trial97** [comment]
Ok found the bug: we did not correctly escape the `"` for a string.
I already have a fix for this here: https://github.com/PrismLauncher/PrismLauncher/pull/1543

**Comment by Aces-and-Jacks** [comment]
That's great. Again, thanks a lot for helping. And sorry if I'm repeating this too much

**Comment by Trial97** [comment]
No problem, I'm glad that I could help!

**Comment by Aces-and-Jacks** [comment]
Wait, should I close this since you have a fix or just wait for the release/merge. No idea how these things go

**Comment by Trial97** [comment]
No, I linked this issue with my PR: once the PR is accepted this will close automatically
