### ISSUE TITLE
Instance Folder

### ISSUE THREAD

**Issue by bjsho** [PrismLauncher/PrismLauncher#1480]
### Role

I use both Linux and Windows and i want to play my Instances on both OS'

### Suggestion

A setting where you can choose where your instace folder is

### Benefit

I dont need to copy files all the time

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It would be nice to face a setting in PrismLauncher where you can say where your Instance Folder is, for me, for example its on my Windows Drive, but when I use Linux, I cant access them, so it would be great if i can set where my instances are, so that PrismLauncher accesses them and can start them.

**Comment by TheKodeToad** [comment]
This option exists!
![image](https://github.com/PrismLauncher/PrismLauncher/assets/57493648/0af34bcc-9290-49bd-8f8e-5c969e35fd7d)

**Comment by bjsho** [comment]
Ive searched for this for like hours and didnt find it, sometimes i am just really stupid, sorry
