### ISSUE TITLE
Teawee is not a cat

### ISSUE THREAD

**Issue by ruguysgoingtrickortreating** [PrismLauncher/PrismLauncher#1482]
### Operating System

Windows, macOS, Linux

### Version of Prism Launcher

Prism Launcher 5.2

### Version of Qt

6.5.1

### Description of bug

Teawee is not a cat, it is a mouse/human character. Maybe teawee could be removed or the cat button renamed.

### Steps to reproduce

* Press the cat button
* If Teawee is selected, it will not be a cat.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
too bad!

**Comment by raincandy13** [comment]
_also it's spelled Teawie and not Teawee_

**Comment by ruguysgoingtrickortreating** [comment]
why was this issue closed it continues to plague my modding experience

**Comment by raincandy13** [comment]
there is no teawie in 5.2 
your issue cannot be reproduced

**Comment by Fnige** [comment]
# Teawie is a rat!

**Comment by Ryex** [comment]
Teawie is a rat and while at first glance rats may seem different than cats they are actually very similar. Both are cute mammals that clean themselves fastidiously. Both are kept a pets. both are known to survive falls grim height and excape death on luck that borders on eldritch powers.

clearly cats and rats are the same and there is no issue here.

**Comment by ruguysgoingtrickortreating** [comment]
what about tom and jerry i think you haven’t watched tom and jerry

**Comment by TheKodeToad** [comment]
This conversation is extremely heated
