### ISSUE TITLE
"Updating assets index" stuck on 100%

### ISSUE THREAD

**Issue by Ardub92** [PrismLauncher/PrismLauncher#1484]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.2 

### Version of Qt

Qt 6.5.1

### Description of bug

![prismlauncher_XGkXdXscvJ](https://github.com/PrismLauncher/PrismLauncher/assets/35745292/2a17942e-a36b-4bd8-99c4-e384c451a982)

Launcher just can't start the game, even when all assets are loaded. Loading gets stuck at 100% and won't launch. Only works if current progress is 100% and press "Abort" and then press launch.

### Steps to reproduce

1. Press launch on any instance, not "Offline" or "Demo"

### Suspected cause

But it can be platform specific.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
I do think that this should be solved by: https://github.com/PrismLauncher/PrismLauncher/pull/1102 but please keep it open until it is merged and you test it with that

**Comment by Trial97** [comment]
I do think that this should be solved by: https://github.com/PrismLauncher/PrismLauncher/pull/1102 needs to be tested after is merged

**Comment by Trial97** [comment]
Hi, can you please try to reproduce this using the latest nightly builds: https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop

**Comment by Trial97** [comment]
Closing this as no more updates.
