### ISSUE TITLE
Modrinth crash causes Check Updates to want to update all my mods with one particular mod

### ISSUE THREAD

**Issue by MeeniMc** [PrismLauncher/PrismLauncher#1488]
### Version of Prism Launcher

Prism Launcher 7.2 (win11-x64)

### Version of Qt

This program uses Qt version 6.5.1.

### Description of bug

1. When clicking the 'Check for Updates' button, the usual modal windows open, the window that summarize what Prism is about to do reports that Prism will update EVERY Modrinth mod with a new version.
2. That new version is the same (it is Iris 1.6.5, in my instance), with the same changelog item. 

![image](https://github.com/PrismLauncher/PrismLauncher/assets/68366846/c1a41f6e-c9e6-4f6b-929f-af44ddd190fb)

* I didn't click update, since that looked wrong, so not sure if it would actually proceed to do this nonsense. 
* Modrinth had a malfunction around the time this issue appeared, I'll report back if issue disappears when Modrinth is back fully operational. In any case, invalid metadata should not cause this?

### Steps to reproduce

1. Have multiple mods installed from Modrinth
2. Have Iris installed
3. Click Update All
4. 1 or more window may inform that mod provider is not found, and/or disabled mods will not be updated, they are correct
5. The summary window for what is about to happen reports that all Modrinth mods will be updated (with Iris 1.6.5)
6. Expanding the Changelog bullet confirms that this is the same Changelog for all mods (again, from Iris 1.6.5)

Note: issue can be reproduced when Iris is already updated to the latest version. 

### Suspected cause

Caused by Modrinth issue, most probably. 
https://discord.com/channels/734077874708938864/734077874708938867/1137256213025919057

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by intergrav** [comment]
FYI for those looking at this issue

![image](https://github.com/PrismLauncher/PrismLauncher/assets/42325132/c888c519-a92c-4bfa-a9f7-4375e4051e9d)

**Comment by itkzj** [comment]
+1，After canceling the update, my mod list is gone!

**Comment by MeeniMc** [comment]
upstream issue is now resolved. Not sure if Prism can do something to correct when provider supplies incorrect metadata.
