### ISSUE TITLE
Combine the install mod loader buttons

### ISSUE THREAD

**Issue by RuiNtD** [PrismLauncher/PrismLauncher#1495]
### Role

I like to put together my own modded instances.

### Suggestion

The "Install Forge," "Install Fabric," "Install Quilt," and "Install LiteLoader" buttons in Edit Instance should all be combined into one "Install Mod Loader" button.

### Benefit

This would make the cluttered sidebar in Edit Instance a lot cleaner.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The button could open a popup with the same UI as the bottom of the New Instance window.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/1149870/249af517-c09f-4a72-a811-5d9d8a7c6ad9)

This suggestion would also affect #1356, which adds yet another mod loader!

**Comment by DioEgizio** [comment]
https://github.com/PrismLauncher/PrismLauncher/pull/1230
