### ISSUE TITLE
Incorrect file names for overrides in Modrinth pack export

### ISSUE THREAD

**Issue by helpimnotdrowning** [PrismLauncher/PrismLauncher#1497]
### Operating System

Windows

### Version of Prism Launcher

7.2

### Version of Qt

6.5.1

### Description of bug

When looking over files for #1496 , I noticed that the file path for an override was not the same as the actual path. This path had non-latin characters.

Result: `1.20.mrpack\overrides\config\inventoryprofilesnext\Uruha Rushia ????? BGM\`
Expected: `1.20.mrpack\overrides\config\inventoryprofilesnext\Uruha Rushia 潤羽るしあ BGM\`

### Steps to reproduce

* Create an instance
* Create two new world with the following names: `TEST قلب 你好 Привет नमस्ते ελληνι` and `TEST 潤羽るしあ 세계 עולם โลก (^‿^)✌️` 
* Export the mrpack
* Examine the mrpack/overrides/saves directory
* All non-latin characters are transformed into `?` (side note: this also happens in the game log but I think it's unrelated since it stays like that in the game-generated log files)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/35247379/9fd28630-a681-4653-bbca-75802740a583)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
given that this in on windows and paths. is possible that eh issue with with improper wide character to utf8 conversion. windows is a pain with paths and utf8
