### ISSUE TITLE
Undo Last Instance Deletion Doesn't Work

### ISSUE THREAD

**Issue by RuiNtD** [PrismLauncher/PrismLauncher#150]
### Operating System

Windows

### Version of PolyMC

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

The "Undo Last Instance Deletion" command doesn't seem to work

### Steps to reproduce

- Create an instance and delete it
- If you don't have a menu bar, press Alt to show it
- Go to the Edit menu
- The "Undo Last Instance Deletion" option is grayed out

### Suspected cause

Likely a conflict with the new feature that moves trashes instances instead of deleting them

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
works on my machine

**Comment by ludgie** [comment]
Doesn't work with the Flatpak version from Flathub on Fedora Silverblue 36.
