### ISSUE TITLE
Netty 4.1.82's arm64 packages are being called on x86_64 linux.

### ISSUE THREAD

**Issue by Kichura** [PrismLauncher/PrismLauncher#1500]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0.

### Version of Qt

Qt 6.5.2.

### Description of bug

When starting up any instance that is Minecraft 1.14 or greater - The ARM64 packages of netty *(In this transport-native-epoll)* is being called into the x86_64 linux system when it's not compatible at all.

### Steps to reproduce

1. Make any instance that is based on 1.14 or newer,
2. Start up the client without making any changes,
3. Check the logs that contain the libraries list,
4. Find out it called both the x86_64 and aarch_64 versions of `netty-transport-native-epoll-4.1.82.Final-linux`,
5. Now edit the minecraft library itself to filter the library to the correct architectures,
6. Start up client again with change applied and get same result.

### Suspected cause

I'm likely guessing that the launcher does not detect the two libraries correctly and assumes they are universally compatible when their architecture variants are actually split, This problem doesn't exist on the Java-ObjC-Bridge library however for example - and while this is a split issue on this specific part; There is also no way to call "macos" instead of "osx" as such code doesn't exist on prism.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Can you provide more information about your environment? Most maintainers of Prism are using Linux as their primary operating system (including me) and this is the first time I read about this.

> There is also no way to call "macos" instead of "osx" as such code doesn't exist on prism.

I don't understand how this is a problem? `osx` is any macOS / Mac OS X

**Comment by Kichura** [comment]
> Can you provide more information about your environment? Most maintainers of Prism are using Linux as their primary operating system (including me) and this is the first time I read about this.
> 
> > There is also no way to call "macos" instead of "osx" as such code doesn't exist on prism.
> 
> I don't understand how this is a problem? `osx` is any macOS / Mac OS X

1. In the vanilla launcher - You are able to use the term `macos` for macOS libraries as an alternate instead of having to re-use the older OS name for it however there is also no `arch` context available meaning you have to essentially consult to using `osx-arm64` as result,
2. The prism launcher library logs can be [found here](https://pastebin.com/raw/Dxgk1E3T) - I can also attach my customized netty file if required,
3. This is the distribution system i have although unsure if this is enough to tell anything:
![a](https://github.com/PrismLauncher/PrismLauncher/assets/68134602/9ae30044-0e4f-4a98-82f2-4d2033386535)

**Comment by Kichura** [comment]
Something i wanna include in this entire issue: If you looked up any other issue that mentions the use of Netty 4.1.82 + Linux, you would quickly find out that the two packages are present there too in each startup log.

**Comment by Scrumplex** [comment]
I have the same list of libraries as you, and it works fine for me. This might be a different problem

**Comment by Kichura** [comment]
> I have the same list of libraries as you, and it works fine for me. This might be a different problem

Ok, will make it a bit more obvious to tell - In [this patch script i made](https://pastebin.com/raw/72eRtfWT), i made a third-party patch for netty to tell the launcher which dependency it's supposed to download for *(In case; aarch_64 copies of netty -> ARM64 linux, x86_64 copies of netty -> Non-ARM64 linux)*.

However instead of it doing exactly what i requested it to do, it instead assumes i wanted **both** dependencies whilst the older aarch_64 netty file *(which i denied via line 86 and line 115 respectively in my script)* for some reason is still being activated despite me saying no to it - and if i repeated the process on mojang's vanilla launcher using their client.json documentation, it does exactly what i wanted to do.

**Comment by Ryex** [comment]
and if you disable your patch and let prism do what it wants?

**Comment by Kichura** [comment]
> and if you disable your patch and let prism do what it wants?

then it will go back to the bundled 4.1.82 netty dependencies as expected although both aarch_64 and x86_64 packages are still shown in logs.

**Comment by Ryex** [comment]
hmm. well Mojang is finally using `osx` and `osx-arm64` to sperate the names in their metadata starting with 1.20. we could in theory modify our metadata patches for arm to use `osx-arm64` and change the generation script and prism to use the correct name on the correct arches.

but if it works correctly without your patch I'm not sure what the issue is?

**Comment by Kichura** [comment]
> hmm. well Mojang is finally using `osx` and `osx-arm64` to sperate the names in their metadata starting with 1.20. we could in theory modify our metadata patches for arm to use `osx-arm64` and change the generation script and prism to use the correct name on the correct arches.
> 
> but if it works correctly without your patch I'm not sure what the issue is?

1. Would definitely approve that prism could have it's metadata modified to ensure the dependencies are in the correct systems because at the moment, i'm currently using my own patches to try and not have it obtain both aarch_64 and x86_64 packages at the same time as the default setup basically has no architecture filter to anything. *(closest is lwjgl itself but it's still managing to get them mixed in some weird way)*

2. While it can run just fine regardless of my test-patch installed, this essentially does tend to confuse me on why a launcher would suddenly obtain arm64 packages to a non-arm64 system when it's not compatible with them in first place.

**Comment by Ryex** [comment]
There are a couple of reasons, 1) because Mojang didn't even sperate the two until 1.20 and it's own rules load both, we would need to explicitly change mojang's rules to change this behavior. 2) x86 emulation modes like Rosetta exist and so sometimes both are needed, 3) All previous behavior would indicate that the JVM is smart and doesn't need us to filter them. so long as it's the right OS it loads the correct native based on the architecture of the host JVM.

of course, If that is not the behavior you observing then we have a bug to solve.

**Comment by Scrumplex** [comment]
The behavior described by the issue is intended. Both libraries are included on Linux regardless of architecture.

If it fails to load the right one there is probably a different issue. You haven't provided a full log of a failing instance.

This could be an issue with your JVM.

**Comment by Kichura** [comment]
Ended up finding the solutions *(last one being a workaround)*:

1. I needed to replace "deny" as "disallow" instead to avoid jar stacking,
2. For the "macos" OS part, i just re-used the "osx" statement instead.

In short, closing this as solved.
