### ISSUE TITLE
Removing Intermediary Mappings does not work

### ISSUE THREAD

**Issue by StarletMD** [PrismLauncher/PrismLauncher#151]
### Operating System

Windows

### Version of PolyMC

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

Attempting to remove the Intermediary Mappings does nothing

### Steps to reproduce

- Select an Instance with Fabric or Quilt installed
- Click Edit
- Click Version
- Click Intermediary Mappings
- Click Remove

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
They are required for Quilt and Fabric. If you remove those it should automatically be gone as well

**Comment by DioEgizio** [comment]
expected behaviour
