### ISSUE TITLE
Launcher crashes after few seconds. 

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [PrismLauncher/PrismLauncher#1514]
### Operating System

Linux

### Version of Prism Launcher

7.2 flatpak

### Version of Qt

missing, probably 5.15 according to flatpak

### Description of bug

Launcher crashes few seconds after launching. This issue does not appear when launching from command line

### Steps to reproduce

1. Open Prism launcher via GUI
2. Wait for crash

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Hi @TheEpicNoobZilla 
Can you try the workaround mentioned here: https://github.com/flatpak/flatpak-builder/issues/389#issuecomment-903472821 ?

**Comment by TheEpicNoobZilla** [comment]
It seems to fix issue (launcher hasn't crashed after few minutes)

**Comment by Trial97** [comment]
I will close the issue as completed. 
~~Feel free to reopen it if happens again.~~
Edit by TheKodeToad: ask to reopen
