### ISSUE TITLE
Installing some MR packs fails with "File already exists"

### ISSUE THREAD

**Issue by sisby-folk** [PrismLauncher/PrismLauncher#152]
### Operating System

Windows

### Version of PolyMC

5.0

### Version of Qt

6.4.0

### Description of bug

Attempting to install Tinkerer's Quilt 3.4.2 (1.18 or 1.19) from modrinth, either through the downloader or directly with the .mrpack file, causes a "Failed to Install Instance" error.

Prism logs 
```
   80.831 C "Failed to apply override from C:/Users/Sisby/AppData/Roaming/PrismLauncher/instances/.LAUNCHER_TEMP/{fbdf9081-e97a-4797-b386-5a65b1355333}/client-overrides to C:/Users/Sisby/AppData/Roaming/PrismLauncher/instances/.LAUNCHER_TEMP/{fbdf9081-e97a-4797-b386-5a65b1355333}/.minecraft"
   80.831 C Reason: "File exists"
   80.831 W Instance creation failed!
   80.831 W Reason:  "Could not rename the client overrides folder:\nclient overrides"
```

### Steps to reproduce

1. Launch Prism 5.0
2. Click create instance -> modrinth -> search "tink" -> install Tinkerer's Quilt 3.4.2
3. Installation will fail

### Suspected cause

No strong idea, file already existing with that uuid/hash could imply some kind of collision? it's unclear.
The packs worked with polymc 1.2, strangely enough.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Madis0** [comment]
Related: #262 
Not a duplicate though, one is for initial install and the other is for updating

**Comment by Scrumplex** [comment]
Probably the same cause as the other bug. Can someone try builds from #301

**Comment by DioEgizio** [comment]
probably fixed with #301, can you try a build from develop?

**Comment by Madis0** [comment]
I can confirm that #262 is fixed in develop for Win 11. Installing by OP's instructions worked as well.

**Comment by DioEgizio** [comment]
fixed in develop
