### ISSUE TITLE
Sinytra support

### ISSUE THREAD

**Issue by Lolothepro** [PrismLauncher/PrismLauncher#1521]
### Role

*

### Suggestion

Be able to download Fabric mods when Sinytra is included in a Forge installation.

### Benefit

*

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
What is that?

**Comment by Lolothepro** [comment]
> What is that?

https://github.com/Sinytra/Connector/blob/master/README.md

**Comment by TheKodeToad** [comment]
Interesting but i expect this project will cause problems for mod devs xD

**Comment by Lolothepro** [comment]
> Interesting but i expect this project will cause problems for mod devs xD

Okay, but isn't it possible to add a way to install Fabric mods on a Forge installation?

**Comment by TheKodeToad** [comment]
It is. Not sure if we should hardcode it for this mod. However you can currently create an empty component and fill in the fields with `Fabric Loader (dummy)`, `net.fabricmc.fabric-loader` or something like that

I don't believe CurseForge allows you to filter multiple loaders though so that may cause some issues

**Comment by Ryex** [comment]
actually, it does. it's a relatively recent change to their api. you can also filter multiple categories.

mod loaders are searched with OR and categories are searched with AND

**Comment by TheKodeToad** [comment]
Ah, I don't think we support that. kind of niche though.

**Comment by TheKodeToad** [comment]
Hmm, since this issue was opened this mod does appear to have received quite a lot of attention. Since we already hardcode Quilt and Fabric API's project IDs (at least IIRC) maybe we could consider automatic detection...

**Comment by Trial97** [comment]
Do we need it once we allow the user to change the loader when searching for mods?

**Comment by TheKodeToad** [comment]
Maybe it could simply automatically select the loaders

**Comment by getchoo** [comment]
imo #1728 is enough for situations like this

although it is sorta comparable to (q)fapi, we aren't dealing with a fork here that's known to have wide compatibility. sinytra still has [many](https://github.com/Sinytra/Connector/discussions/12) [incompatibilities](https://github.com/Sinytra/Connector/issues) (even with some of the most popular fabric mods), and will probably still be in beta for the foreseeable future

regardless (and more importantly), i don't think we should continue hard coding things like this. we can't enumerate every new mod combination that allows for compatibility between loaders and push an update for it; it's also a weird experience to have compatibility checks ignored only *sometimes* when the instance meets conditions completely invisible to you, the user

for development sake and user experience, a clear option that allows you to ignore mod compatibility with your current loader makes much more sense

**Comment by TheKodeToad** [comment]
Hmm, I think I'll leave it open because I wouldn't say it's absolutely not happening

**Comment by vipkingo1** [comment]
i was looking for this and was goanna suggest to add a separate section in the download mods area like this 
![image](https://github.com/PrismLauncher/PrismLauncher/assets/83919595/84723d6a-9cba-4b0c-b2dc-c95c9192d819)
(typo ment to write fabric curseforge)

**Comment by Marks12520** [comment]
Yeah I tried the mod a few days ago and I did think about this it'd be so useful

**Comment by Trial97** [comment]
With https://github.com/PrismLauncher/PrismLauncher/pull/1728 you can select and search any loader.
The autodetection part is redundant
