### ISSUE TITLE
Add option to change prism launcher folder

### ISSUE THREAD

**Issue by BoBkiNN** [PrismLauncher/PrismLauncher#1527]
### Role

Launching and playing minecraft

### Suggestion

Add new option to change PrimLauncher folder from %AppData%/PrismLauncher to any other

### Benefit

More customization

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I think that this is useful because "libraries" folder taking a lot of space on my system volume

**Comment by Trial97** [comment]
There is already an option for that : 
```
 $prismlauncher -h  
Usage: prismlauncher [options]
Prism Launcher

Options:
  -d, --dir <directory>    Use a custom path as application root (use '.' for
                           current directory)
...
```
Like described in the help you can start the prism using --dir argument to specify a root directory or if you use the portable version just create a file named `portable.txt` where the executable is and that will be used as the root directory.

Also, you can directly change in the application the instance's directories to a separate path(Settings>Launcer>Features>Folders).

Another option for your case would be to move the %AppData%/PrismLauncher folder to another drive and create a shortcut in %AppData% to it.

**Comment by BoBkiNN** [comment]
Thanks for guide

**Comment by 4g0tt3nSou1** [comment]
Hi, Thanks for the info. I'd suggest the portable.txt trick be something you can tell it to do at install, simple "Make this installation portable", and I think that an in-UI (installer too would be nice) option for the -d/--dir CLI args (obviously requiring reboot app), should also be in settings. Remember, not everyone is going to want to google this stuff when they want this, they might just want to specify a directory and go. Seems it'd be a cool and neat feature.

**Comment by DeveloperBlue** [comment]
I would also suggest asking for an installation path when running PrismLauncher for the first time - or at the very least use the current directory the launcher is in.

I like to keep my games on a separate drive, so having the installer dump all the files into %appdata% does not work well for me. I can create a symlink, but I would rather avoid that.

**Comment by Anastasis1175** [comment]
Can you change the root folder of the non-portable version of the Prism Launcher.
I would like to know because my C:\ Drive is almost full (because of many instances in prism, many games/apps and many minecraft flashback videos) and I my computer does not like that at all.
It is lagging everywere and I am getting like 30-2 FPS with 4 chunks render distance and 6 simulation distance with V-Sync on.
(•_•)  /|-{ㄒoㄒ}-|\

**Comment by TheAnhSE** [comment]
The man on top said 
"Another option for your case would be to move the %AppData%/PrismLauncher folder to another drive and create a shortcut in %AppData% to it."
it's called **SymLinks** feature

**Comment by Anastasis1175** [comment]
> The man on top said 
> "Another option for your case would be to move the %AppData%/PrismLauncher folder to another drive and create a shortcut in %AppData% to it."
> it's called **SymLinks** feature 

Thanks
