### ISSUE TITLE
Resource / texture pack downloader

### ISSUE THREAD

**Issue by yavko** [PrismLauncher/PrismLauncher#153]
### Role

I like resource packs

### Suggestion

Be able to download resource packs from modrinth and curseforge

### Benefit

I don't have to open a web browser, or have to check for updates

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by soup587** [comment]
seeing as modrinth is getting shader packs now it would be pretty good to have them too
