### ISSUE TITLE
Toggle to disable asking for offline username

### ISSUE THREAD

**Issue by Arenovas** [PrismLauncher/PrismLauncher#1533]
### Role

I sometimes play the game offline on my Steam Deck.

### Suggestion

I want there to be an option of some sort to stop the launcher from asking the player to set an offline username every time they play offline.

### Benefit

Such a toggle would remove an extra step for offline players who only use one username and don't have any other players on their machines.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by pog5** [comment]
You should be able to do this by just setting the Offline account as a Default account in the accounts page
