### ISSUE TITLE
Skin Changer

### ISSUE THREAD

**Issue by Azrian0** [PrismLauncher/PrismLauncher#1534]
### Role

I change skins a lot

### Suggestion

Like the Minecraft launcher lets you hotswap skins, is Prism Launcher able to do this as well?

### Benefit

This would be another reason why you wouldn't use the default launcher, or go to the website to change your skin. Adding this feature will let people not have to go through an extra step.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This would also work per account you have. Being able to hotswitch skins like the regular launcher does, would be a good feature to bypass extra steps for people who **only** want to main Prism.

**Comment by Scrumplex** [comment]
You can already do this, by heading to the Accounts page, selecting your account and clicking Upload Skin

![Upload Skin menu in Prism Launcher](https://scrumplex.rocks/img/1692341483_ip2eiW.png)

**Comment by Scrumplex** [comment]
Reopening, as this is a feature request for switching between recent skins

**Comment by TheKodeToad** [comment]
I feel that this would make sense with #330; therefore I have "merged" the issues
