### ISSUE TITLE
A required function is missing: glfwInitAllocator

### ISSUE THREAD

**Issue by UltraBlackLinux** [PrismLauncher/PrismLauncher#1538]
### Operating System

Linux

### Version of Prism Launcher

7.0.r781.geb4efa5a9 (AUR)

### Version of Qt

6.5.2

### Description of bug

After upgrading my prismlauncher version today, I'm getting the following error:
`Caused by: java.lang.NullPointerException: A required function is missing: glfwInitAllocator`
I tried disabling the native glfw installation, but to no luck.

### Steps to reproduce

launch the game

### Suspected cause

https://github.com/PrismLauncher/PrismLauncher/commit/83aa0062c7d831ca42ed4d82e5f6162ac8793be8

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Can you send a log of an instance?

**Comment by UltraBlackLinux** [comment]
here it is: https://mclo.gs/I42TdkQ
Sorry taht I could not send it earlier, I wanted to play, so I was stuck with the downgraded version

**Comment by Scrumplex** [comment]
Line 49 says that it's still using the system GLFW. Make sure that there is no instance-level override for the setting

**Comment by UltraBlackLinux** [comment]
1. I have no issues with system GLFW on the older version
2. I tried on and off

**Comment by Scrumplex** [comment]
> 1. I have no issues with system GLFW on the older version

Because pre 83aa0062c7d831ca42ed4d82e5f6162ac8793be8 the toggle didn't work on LWJGL 3.3.1 (Minecraft 1.19+)

> 2. I tried on and off

Again, check if there is an **instance-level** override. The option *is* turned on in that log you sent.

**Comment by UltraBlackLinux** [comment]
1: Well native GLFW works fine on older minecraft versions.
2: It actually works with all the toggles disabled. Weirdly, the instance-level toggle did not override the global toggle. I have no idea what could be wrong with the glfw package.

**Comment by Scrumplex** [comment]
> 1: Well native GLFW works fine on older minecraft versions.

That's because LWJGL 3.3.1 and by extension, newer Minecraft versions require a newer GLFW, which hasn't even been released yet.

You don't really need this feature if your Minecraft works fine. The toggle is intended for users who have issues with glfw (like the "stack smashing" problem in #916) or if you want to run the game natively on Wayland using something like https://github.com/Admicos/minecraft-wayland

**Comment by UltraBlackLinux** [comment]
well I don't really see an issue here. The repos provide me with glfw 3.3.8, which is quite a lot more recent.

I want to use the new version because it has a scuffed input bug fixed that caused input delay for me, at least on older versions.

**Comment by Scrumplex** [comment]
the versioning of LWJGL and glfw are not related.

GLFW 3.3.8 was released a year ago: https://github.com/glfw/glfw/releases/tag/3.3.8

**Comment by Scrumplex** [comment]
the function you are talking about `glfwInitAllocator` will be introduced in LWJGL 3.4.0, which is yet to be released: https://github.com/glfw/glfw/commit/22b586b3d87c91581074cc2a47fe5eba6f10bf0d

You could use an unstable package of glfw. I am sure the AUR can help you out here.

**Comment by UltraBlackLinux** [comment]
oh ok that's weird. Well I guess I'll wait then. Thanks for clearing this up!

**Comment by UnlimitedCookies** [comment]
So installing `glfw-git` is currently the best option to play the newest minecraft version?
How are not more people complaining about this issue and why are they using unreleased features from GLFW?! (Are they all using the bundled GLFW?)
