### ISSUE TITLE
Fps locked at 60hz when use vsync with prismlauncher and using minecraft 1.7.10 on linux

### ISSUE THREAD

**Issue by quentin452** [PrismLauncher/PrismLauncher#1542]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt version 6.2.4

### Description of bug

The bug is that the fps is locked at 60hz when using vsync , but i have a pc at 165hz .
When using prismlauncher , archlinux(endeavouros) and using minecraft 1.7.10 forge i got the issue.

### Steps to reproduce

1 : launch minecraft 1.7.10 on linux
2 : watch vsync lock fps at 60hz ,instead of the hz of the screen

### Suspected cause

Suspected cause : Prismlauncher 

I tried using Gdlauncher and its work without the issue
Minecraft 1.12.2 its work without the issue

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
As it looks like you are using an older version of Prism does this happen using the latest release(7.2)?
Do you have an Nvidia GPU?

**Comment by quentin452** [comment]
yes i have an nvidia gpu , i have some problem to download package because i have alot of package to update but if i can reproduce the issue with updated Qt and Prism ,i will edit the report

**Comment by quentin452** [comment]
i have an rtx 3060

**Comment by quentin452** [comment]
for more information : when i disable the vsync the game can run at 165hz but without vsync i have more stutters

**Comment by Trial97** [comment]
Regarding Nvidia it is known that it does some optimizations behind for Minecraft that can break the game(Prism is blocking the nvidia detection and so the optimization are not applied ).
Check this issue: https://github.com/PrismLauncher/PrismLauncher/issues/1137 for more details.
You can either:
- try the DirectLaunch as mentioned here: https://github.com/PrismLauncher/PrismLauncher/issues/1137#issuecomment-1606719798
- add some jvm arguments: https://github.com/PrismLauncher/PrismLauncher/issues/1137#issuecomment-1629131334
- or try using an optimization mod like Sodium/Rubidium

Let me know if something from this list worked for you.

**Comment by quentin452** [comment]
sodium/rubidium doesn't exist in 1.7.10 and the issue only appear with prismlauncher and 1.7.10

**Comment by quentin452** [comment]
l'ill try 

the DirectLaunch as mentioned here:
https://github.com/PrismLauncher/PrismLauncher/issues/1137#issuecomment-1606719798
add some jvm arguments:
https://github.com/PrismLauncher/PrismLauncher/issues/1137#issuecomment-1629131334

**Comment by quentin452** [comment]
where is the instance.cfg

**Comment by quentin452** [comment]
ah ok under the .minecraft

**Comment by quentin452** [comment]
ok none of these fix fixed my issue

**Comment by Trial97** [comment]
Ok, one last thing in the F3 in-game menu does it say that it uses the correct GPU?

**Comment by quentin452** [comment]
yes because when i disable vsync i got 2300 fps , in 1.7.10 the f3 doesn't say so much about gpu

**Comment by Trial97** [comment]
Then just make sure that the `Use discrete GPU` option is used in prism:
- global setting >Minecraft>Tweaks>Use discrete GPU
- instance setting>Performance>Use discrete GPU

**Comment by quentin452** [comment]
already enabled

**Comment by Trial97** [comment]
Ok strange, I'm not sure then why this is happening.

**Comment by quentin452** [comment]
Not fixed by updating prism and Qt

**Comment by quentin452** [comment]
workaround use polymc

**Comment by quentin452** [comment]
Lol i found the real solution disable "Use discrete GPU" in settings of prismlauncher

**Comment by quentin452** [comment]
so it seem thats the combination of linux,minecraft 1.7.10 , prism, Use discrete gpu make the issue
