### ISSUE TITLE
Remove Mojang authentication

### ISSUE THREAD

**Issue by jschenke488** [PrismLauncher/PrismLauncher#155]
### Role

It is no longer possible to play Minecraft with a Mojang account

### Suggestion

Remove Mojang authentication

### Benefit

You can't use Mojang accounts

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

https://www.minecraft.net/en-us/article/last-call-voluntarily-migrate-java-accounts

**Comment by timoreo22** [comment]
Currently you can still log in mojang accounts and play offline

**Comment by Scrumplex** [comment]
Yep. We are keeping it around until you actually can't log in anymore
