### ISSUE TITLE
Latest build failing to filter loaders

### ISSUE THREAD

**Issue by Hedwig7s** [PrismLauncher/PrismLauncher#1565]
### Operating System

Windows

### Version of Prism Launcher

[Action 5962687070](https://github.com/PrismLauncher/PrismLauncher/actions/runs/5962687070)

### Version of Qt

Qt 6.5.2

### Description of bug

Example: If a mod has a fabric build for 1.20 and not a forge build and you're running forge 1.20, the mod will still show in the list but with the "No valid version found!" error
If a mod has not got any loader marked (curseforge exclusive), it will show in the list with the "No valid version found!"
I have not found an instance where there's no version of the mod for a specific version and it showing up (e.g. 1.20 mods won't show up when looking for 1.12 mods)

### Steps to reproduce

Find a loader-exclusive mod (such as [pehkui](https://modrinth.com/mod/pehkui/) which does not have a 1.15 build for forge) or a mod with no loader marked (such as [JEI](https://www.curseforge.com/minecraft/mc-mods/jei/files?version=1.12.2) 1.12.2)
Look it up in the download mods menu
Profit?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Thank you for your issue but that is a PR build(not yet merged in develop).
The latest build can be always found here: https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop
I will try to fix this one in the mentioned PR.

**Comment by Trial97** [comment]
I fixed the curseforge issue that you mentioned if you want to test it out here is the link to the PR build: https://github.com/PrismLauncher/PrismLauncher/actions/runs/5972494077  
But the other issue mentioned is regarding modrinth: it is a known issue for their API even if we request only the forge mods that match the mentioned game version, they return instead a list of mods that fit the game version and have at least one file for the mentioned loader(it doesn't need to be for the same game version). This one is not limited to the mentioned PR and it happens on all the builds.

**Comment by Hedwig7s** [comment]
> I fixed the curseforge issue that you mentioned if you want to test it out here is the link to the PR build: https://github.com/PrismLauncher/PrismLauncher/actions/runs/5972494077 

Now it just crashes

**Comment by Trial97** [comment]
> Now it just crashes

Can you describe how?
What version of Minecraft? What loader?
What mod are you trying to download?
Also logs would help.

**Comment by Hedwig7s** [comment]
1.15.2 Forge recommended version and just a couple of random mods in the featured list

**Comment by Trial97** [comment]
Tried to reproduce with the first 100 mods from that list and I did not manage to crash the launcher.
Can you please provide more details?

**Comment by Hedwig7s** [comment]
Well after reinstalling it it stopped doing that so must've been a fluke

**Comment by Hedwig7s** [comment]
And now after I installed the latest develop build it did it again I'm going insane
Edit: Must've been the same issue as the other issue since you found the issue

**Comment by Trial97** [comment]
The issue found in: https://github.com/PrismLauncher/PrismLauncher/issues/1569 happens on develop and should be fixed in the  build pointed out by me here:https://github.com/PrismLauncher/PrismLauncher/issues/1565#issuecomment-1692837498

But here https://github.com/PrismLauncher/PrismLauncher/issues/1565#issuecomment-1694386256 you said it crashes pointing to the link of the mentioned [PR](https://github.com/PrismLauncher/PrismLauncher/pull/1560) so do you still get crashes using the link provided  here:https://github.com/PrismLauncher/PrismLauncher/issues/1565#issuecomment-1692837498 ?

**Comment by Hedwig7s** [comment]
I really don't feel like going through the trial and error again especially since the bug is extremely unpredictable
It probably was the same issue as develop
I only got the crashing once and after reinstalling the same build it didn't do it again so I'm pretty sure it was #1569

**Comment by Hedwig7s** [comment]
Correction: I think the instance already had bad metadata from the #1569 bug and the launcher can't read it properly

**Comment by Trial97** [comment]
For the metadata, I have another PR:https://github.com/PrismLauncher/PrismLauncher/pull/1543 (it doesn't fix the metadata but instead doesn't write invalid metadata, and in case one is wrong will continue to read the other mods' metadata without failing to read half of the mods list)
