### ISSUE TITLE
filter client side

### ISSUE THREAD

**Issue by pizzav-xyz** [PrismLauncher/PrismLauncher#1568]
### Role

when downloading from modrinth i would like to filter 

### Suggestion

edit > mods > download mods

### Benefit

this would be nice 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TayouVR** [comment]
pretty sure we can filter on the API (at least for modrinth), which would be a lot cleaner. 
Doing it client side is only possible with some metadata, and is not ideal in general.
Someone just needs to implement filtering there in general... Currently the UI only really supports changing the minecraft version range. mod loaders are handled based on what is installed in the instance, but categories are missing entirely. I probably won't have time to do it in the near future, but I'm sure another contributor will step up to that task!

**Comment by Scrumplex** [comment]
I think this request might actually be about filtering for client-side mods? Not sure though :O

**Comment by pizzav-xyz** [comment]
> I think this request might actually be about filtering for client-side mods? Not sure though :O

it is
@TayouVR

**Comment by TayouVR** [comment]
ah, my bad...
Though can't server side mods still be used in single player? (e.g. server optimizations for example)
So I think, still.. actually having proper filters in the UI would be more optimal
