### ISSUE TITLE
Show error on failed version refresh

### ISSUE THREAD

**Issue by melvyn2** [PrismLauncher/PrismLauncher#157]
### Role

I use minecraft

### Suggestion

Prism Launcher should show a GUI error when fetching version info (and other remote resources) fails.

### Benefit

Much easier troubleshooting of version problems.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Prism Launcher was only showing versions of Minecraft up to 1.19, despite 1.19.2 being out at time of writing. Refreshing seemed to go through but did not fix the issue. Checking the console, I saw the following output:
```
    4.470 D Task "NetJob(Download of meta file net.minecraft/index.json)" starting for the first time
    4.479 D Task "Net::Download(0x55e0200ada40)" starting for the first time
    4.479 D Downloading  "https://meta.scrumplex.rocks/net.minecraft/index.json"
    5.340 C Failed  "https://meta.scrumplex.rocks/net.minecraft/index.json"  with reason  QNetworkReply::ContentNotFoundError
    5.340 D Download failed in previous step: "https://meta.scrumplex.rocks/net.minecraft/index.json"
    5.341 D Task "Net::Download(0x55e0200ada40)" restarting for after failing at first
    5.341 D Downloading  "https://meta.scrumplex.rocks/net.minecraft/index.json"
    5.698 C Failed  "https://meta.scrumplex.rocks/net.minecraft/index.json"  with reason  QNetworkReply::ContentNotFoundError
    5.698 D Download failed in previous step: "https://meta.scrumplex.rocks/net.minecraft/index.json"
    5.698 D Task "Net::Download(0x55e0200ada40)" restarting for after failing at first
    5.698 D Downloading  "https://meta.scrumplex.rocks/net.minecraft/index.json"
    5.874 C Failed  "https://meta.scrumplex.rocks/net.minecraft/index.json"  with reason  QNetworkReply::ContentNotFoundError
    5.875 D Download failed in previous step: "https://meta.scrumplex.rocks/net.minecraft/index.json"
```
This is because the old recommended meta server was shut down, which is also something that should be fixed (CNAME or redirect it to the new one).
However, this error was completely invisible to the user in the GUI, and just made it seem like no new version had been released. On top of fixing the old meta server, these errors should definitely be shown to the user in the GUI so that they know something has gone wrong, and can understand why.

**Comment by Scrumplex** [comment]
The old one wasn't shut down. Your URL was broken. It was supposed to be `https://meta.scrumplex.rocks/v1`
Anyway, just use the default meta server for Prism

**Comment by melvyn2** [comment]
That one was my mistake, but the other part of the issue still stands. There’s no indication if the url is functioning in the gui.

**Comment by Scrumplex** [comment]
A lot of them were added in PrismLauncher/meta#5 already
