### ISSUE TITLE
Crash after reviewing mods after internet outage and recovery

### ISSUE THREAD

**Issue by MissPotato** [PrismLauncher/PrismLauncher#1571]
### Operating System

Windows

### Version of Prism Launcher

7,1

### Version of Qt

6.5.1

### Description of bug

I was setting up to download a somewhat sizable list of mods from Modrinth, and a couple from CourseForge. Nearing the end of the process my internet cut out. Once my internet recovered, I was unable to select new mods so I clicked the review button hoping to not lose the current progress. A handful of mods downloaded, then the program crashed without a warning. 

https://pastebin.com/jjwBgGYT

### Steps to reproduce

1) Use the built-in mod downloader
2) Select some mods.
3) Lose internet
4) Have internet recover
5) Have the select button for mods say something along the lines of "fetching versions"
6) Click review selection
7) Crash

### Suspected cause

I suspect that I had selected a mod version right as my internet died, and once it got to that version to download crashed.

(I don't know where else to put this but I tried looking up 'lost internet', 'crash downloading mods', 'download crash' and found nothing.) 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
I prepared a portable debug build: https://media.githubusercontent.com/media/Trial97/prism_gdb/refs/heads/master/PrismLauncher-Windows-MinGW-w64-Portable-b1113f4-Debug.zip?download=true (portable build + debuger)

Download and extract that file.
Start prism using the `gdbprismlauncher.bat` file(the extension may be missing), not the normal executable; do not touch the opened command prompt(black thing with text)
Try to reproduce the crash;if the application is stuck leave it a few minutes(it takes a while to generate all the backtrace)

Once it completely closes there will be a `gdbcrash.log` file. Please share that file( is a stacktrace of the crash)

The source code for how I created that zip can be found here https://github.com/Trial97/prism_gdb/tree/master

**Comment by MissPotato** [comment]
It's been over a year since I reported this, and I am actually no longer on windows I moved to Linux.  I just tested with the flathub build of Prism by unplugging my ethernet and there was no crash. This may no longer be a bug, is platform specific, or requires a more unstable connection and not flatout dropping connection. Sorry I can not be of more help.

**Comment by Trial97** [comment]
Ok then, I will close this as compiled.
If you reencounter it feel free to reopen it.
