### ISSUE TITLE
"This account does not own Minecraft" if another configured microsoft account doesn't own minecraft

### ISSUE THREAD

**Issue by codl** [PrismLauncher/PrismLauncher#1576]
### Operating System

Linux

### Version of Prism Launcher

7.2 (from flathub)

### Version of Qt

5.15.10

### Description of bug

I mistakenly logged into a microsoft account (A) that doesn't own the game, then realizing my mistake I logged into the right microsoft account (B), that does own the game, and set it as the default account, but I did not remove account A from Prism Launcher.

I expected that I would be able to launch the game as account B, since it owns the game and was set as default, but instead Prism Launcher said that it did not own the game and asked if I wanted to launch the demo instead.

Interestingly, if I set no default account and tried to launch the game, I did not get a prompt asking me which account to use, instead I immediately got the "This account does not own Minecraft" prompt.

Removing account A allowed me to launch the game.

Removing every account and then logging into the two accounts in the reverse order still exhibits the problem behaviour, so it's not a "first account configured" thing.

### Steps to reproduce

1. Log into a Microsoft account that does not own Minecraft
2. Log into another Microsoft account that does own Minecraft
3. Set the account that does own Minecraft as the default account
4. Create a fresh new instance and try to launch it

### Suspected cause

I suspect that the check for ownership is not honoring the default account setting, perhaps instead checking every account, or the first one by some mysterious ordering.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by codl** [comment]
Further testing: If I have both accounts configured and I override the default account in the instance settings to use account B (the one that owns the game) then the game launches fine.

**Comment by sybenx** [comment]
Encountered this issue when helping someone set up Prism Launcher today. Removing invalid account fixes the issue but it's not an obvious fix.

**Comment by Camuise** [comment]
> Further testing: If I have both accounts configured and I override the default account in the instance settings to use account B (the one that owns the game) then the game launches fine.

This didn't seem to work for me. i had to remove the account to get it to work
