### ISSUE TITLE
Unselecting mods

### ISSUE THREAD

**Issue by Traehgniw** [PrismLauncher/PrismLauncher#1579]
### Role

i play the game

### Suggestion

i'd like a way to unselect mods in the mod list

### Benefit

it is annoying to close the console window for a modpack and reopen it when trying to check for updates on all mods after having previously selected a mod

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

it is possible i have just missed a deselect mods option but i would like to have somewhere on the UI to click to clear mod selections, so the modpack's mod list tab goes back to having no mods selected so i can run an update check on all of them at once without having to close and reopen the modpack's console window

**Comment by TheKodeToad** [comment]
You can already click on one and ctrl+click that...

**Comment by Traehgniw** [comment]
I did not know that, thank you!
