### ISSUE TITLE
Dark Titlebar only works for main window

### ISSUE THREAD

**Issue by IdrisQe** [PrismLauncher/PrismLauncher#158]
### Operating System

Windows

### Version of PolyMC

PrismLauncher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

When various windows are not in focus on Windows 10, only the main PrismLauncher window will use the dark titlebar implemented in 5.0.

Other windows such as the console, settings, etc. will all default to Windows 10's white unfocused titlebar, making things inconsistent.
![Capture](https://user-images.githubusercontent.com/40530630/196847123-2f3a22cf-6a8b-44ad-8150-ac4120d923f5.PNG)

### Steps to reproduce

1. Launch PrismLauncher 5.0
2. (Might be necessary?) Put PrismLauncher in Dark Mode
3. Open any other window, and click a different, unrelated window to unfocus them all. Only the main window will have the dark titlebar.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RuiNtD** [comment]
It looks just fine for me.
![](https://i.imgur.com/VJBc4BS.png)

**Comment by CompaqDisc** [comment]
Looks good for me as well
![explorer_yQecpCVfri](https://user-images.githubusercontent.com/12076803/196864791-c48a7a87-976a-404e-ad3c-2d85b56c9456.png)

**Comment by DioEgizio** [comment]
switch to dark mode on windows and it'll work fine. This is a built-in feature in Qt.

**Comment by IdrisQe** [comment]
Hm... This actually still seems to be functioning not as it should though.
I checked, Windows is in Dark Mode, but Apps are in Light Mode.

If I turn Apps from Light to Dark then back to Light, the titlebar will turn white when unfocused like every other app.
And given my default was Apps in Light Mode, shouldn't the titlebar have been white when unfocused in the first place?
