### ISSUE TITLE
incorrect arguments in pre 1.6 with `noapplet` trait leading to username and session not being set

### ISSUE THREAD

**Issue by tildejustin** [PrismLauncher/PrismLauncher#1580]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt 6.5.1

### Description of bug

The username is failed to be set on pre 1.6 (I tested down to 1.3) instances with `noapplet`. Without `legacyLaunch` it fails, I didn't expect that to work in any case, but even with `legacyLaunch`, Minecraft just sets it to the generic "Player<numbers>." This behavior differs from the Vanilla Launcher, which launches into a nonapplet window and still sets the player username and session token.

Image of `noapplet` behavior (you can see in the logs "Setting user: Player31, -"):
![image](https://github.com/PrismLauncher/PrismLauncher/assets/66330094/35d5d9fe-2a7e-48a1-9b6e-acb286c294b4)

Image of `applet` behavior:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/66330094/0c43ce58-fba6-4cc5-a995-f065c2b46cb8)

### Steps to reproduce

- Create a default 1.3.2 instance
- Set the "noapplet" trait
- Launch
- Observe the `Setting user` line, ex: `Setting user: Player906, -`
Test Instance: [1.3.2_noapplet_demonstration.zip](https://github.com/PrismLauncher/PrismLauncher/files/12472897/1.3.2_noapplet_demonstration.zip)

### Suspected cause

1.6 has different launch arguments than pre-1.6 but `legacyLaunch` uses the 1.6 ones? I have no idea, I'm hoping someone else does.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by tildejustin** [comment]
https://github.com/FabricMC/fabric-loader/pull/632 I think this could be related, shows there's a difference between 1.6 and pre 1.6 arguments

> Versions before [1.6](https://launchermeta.mojang.com/v1/packages/20116297638f7c70cd046e25a6ac90fee4cae61a/1.6.json) like [1.5](https://launchermeta.mojang.com/v1/packages/924a2dcd8bdc31f8e9d36229811c298b3537bbc7/1.5.2.json) and [b1.7.3](https://launchermeta.mojang.com/v1/packages/44f6969326bd45aa00dcd3c4ca3a7c05ebb24c04/b1.7.3.json) lack --username and --session, instead they pass them directly
>
> 1.6
> 
> ```json
> "minecraftArguments": "--username ${auth_player_name} --session ${auth_session} --version ${version_name} --gameDir ${game_directory} --assetsDir ${game_assets}"
> ```
> 
> pre 1.6
> 
> ```json
> "minecraftArguments": "${auth_player_name} ${auth_session} --gameDir ${game_directory} --assetsDir ${game_assets}"
> ```

**Comment by AdelinaM17n** [comment]
This indeed seems to be the case, as adding ` "minecraftArguments": "${auth_player_name} ${auth_session} --gameDir ${game_directory} --assetsDir ${game_assets}",` (copied from [skyrising manifest](https://skyrising.github.io/mc-versions/manifest/3/4/af212ac1badac3f3037017be9e3a87f0625f41/1.5.2.json)) to the `net.minecraft.json` patch seems to set the username fine (without legacyLaunch, haven't tested with legacyLaunch)
