### ISSUE TITLE
Java configuration dialog repeats repeatedly at launcher startup after an unknown amount of time

### ISSUE THREAD

**Issue by MbtMarco** [PrismLauncher/PrismLauncher#1585]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt 6.5.0

### Description of bug

After a while if I start the launcher the dialog about configuring Java appears, even though it is already configured. (No changes to Java versions have occurred in the interval between launches.) 

### Steps to reproduce

- Launch the launcher
- Configure Java
- Close the launcher and wait a long enough period of time
- Reopen the launcher

(It may not happen the first time)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Are you sure you completed it at first and not just skipped it?
How much time is `a long enough period of time`?

**Comment by MbtMarco** [comment]
No, I didn't skipped the Java setup the first time (And yes I already tried uninstalling the launcher completely, also deleting any remaining folders)

I can't tell you after a period of time it happens, also because it happens when I don't open the launcher for a while, I have no way to measure the exact time frame.

**Comment by Trial97** [comment]
Sorry, I'm unable to reproduce this.
The time when I did not open it on the Mac was over a month.
Also by uninstalling the launcher and deleting the folders you are asking to be prompted with that dialog box as in that way you ensure that you deleted all the choices you made previously.
