### ISSUE TITLE
Copying an instance synchronizes custom commands after copying

### ISSUE THREAD

**Issue by Lyra-Vhess** [PrismLauncher/PrismLauncher#1586]
### Operating System

Linux, Arch

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt 5.15.10

### Description of bug

After copying a Minecraft instance with a custom wrapper command for starting a gamescope window, 
'gamescope --nested-height 1440 --nested-width 2560 --output-height 1080 --output-width 1920  --fullscreen --`,
And removing the custom command on the copied instance, the original instance had the command removed as well. 

Likewise, adding the command to either instance synchronizes it to the other one. Is this intended behaviour? Can it be fixed?

### Steps to reproduce

* Created minecraft 1.20.1 instance
* Added custom wrapper command to instance
* Copied Instance
* Removed command from copy
* Original also had command removed

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Did you perhaps copy the instance using symbolic/hard links?
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/326dd32a-3217-4407-b429-1168525f059e)

**Comment by Lyra-Vhess** [comment]
I did not, no, that was left unchecked. These were the selected options.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/91616359/26e42cb3-c45f-44d2-ad26-7d18e1b63376)
Can you replicate my problem?

**Comment by Trial97** [comment]
Sadly I can not reproduce it.
In order to not confuse the instances did you give them different names? or used different groups?

**Comment by Lyra-Vhess** [comment]
I did give them different names, but not different groups. If you're thinking I misclicked, I made very sure to double check. I could take a short video perhaps

Edit: Video for context 
[Screencast 2023-08-31 10:15:46.webm](https://github.com/PrismLauncher/PrismLauncher/assets/91616359/df89e9d5-b7fe-4503-ba28-30ed42effe9f)

**Comment by Trial97** [comment]
That are the global settings for all instances.
If you want to edit for one specific instance: 
- Select instance 
- Right Click on it and select edit or just click edit on the instance banner 
- in the opened window go to settings page
- custom commands tab
- check the custom comands checkbox
- then modify the wrapper command

**Comment by Lyra-Vhess** [comment]
Thanks! Will do.
