### ISSUE TITLE
Prism Launcher doesn't go to the main menu after Language and Java Setup

### ISSUE THREAD

**Issue by loustact** [PrismLauncher/PrismLauncher#160]
### Operating System

Windows

### Version of PolyMC

Prism Launcher 5.0 (Legacy)

### Version of Qt

Qt 5

### Description of bug

When you get the zip file, extract it, and execute Prism Launcher and its Language and Java setup, it decides to crash itself in the background.

### Steps to reproduce

1. Download, and extract Prism Launcher Windows Legacy (I downloaded portable ver.)
2. Execute prismlauncher.exe
3. Complete Language and Java setup

After that, Prism Launcher will suddenly stop working in the background, and make a new log.
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/9827246/PrismLauncher-0.log)

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Maybe related to #134

**Comment by loustact** [comment]
> Maybe related to #134

Yeah, I didn't caught that.
