### ISSUE TITLE
The pack description is only displayed if it is a string

### ISSUE THREAD

**Issue by lumiscosity** [PrismLauncher/PrismLauncher#1602]
### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt 6.5.1

### Description of bug

Prism Launcher clears any data from the pack description field that isn't a string. However, [any raw JSON text is valid within Minecraft](https://minecraft.fandom.com/wiki/Raw_JSON_text_format).

### Steps to reproduce

- Create a new resource pack, texture pack or data pack.
- In the pack.mcmeta file, set the decription to a valid JSON data type (see link above).
- In-game the description will be displayed; in Prism Launcher, it'll be empty.

Example with a number:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/26834471/6a125d2c-5ecf-46c6-8641-459a15b75686)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/26834471/d43d6029-0092-4daf-922b-47e2a61f086f)

### Suspected cause

The resource pack description reading code (and the equivalent code for data packs and texture packs) seems to ensure that the type is always a string. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by cullvox** [comment]
I did some research into this, and found this line probably causing the issue. Line 144 is the issue because it requires the string type. If that could be changed to allow for an integer too, then your data pack will show a proper description again.

https://github.com/PrismLauncher/PrismLauncher/blob/ba3a1b628087c9e40b6c217f68f747bb0e12dbe1/launcher/minecraft/mod/tasks/LocalDataPackParseTask.cpp#L137-L150

I'll start working on a fix.

**Comment by cullvox** [comment]
Also, if you check your logs, you are probably getting that  'JsonException' warning.

**Comment by cullvox** [comment]
My original response was way off, I needed to reread the issue. I will still be looking into see what might cause this

**Comment by cullvox** [comment]
Now that I have had some time to think about this issue, I don't really see this behavior as a bug. The valid examples on the wiki and from other sources all have 'description' to be a string type. Perhaps you don't have the correct type for 'description' in the 'pack.mcmeta' file and should turn it into a string. 

When it comes to clearing the description, I don't see anything about the description being cleared, at least not in 8.0-develop right now. My invalid description is never changed by Prism.

Regarding data packs, it doesn't look like prism currently displays them and only allows opening the worlds' folder.

In order for me to fix this issue, I would need to see the JSON in your pack.mcmeta file.

**Comment by TheKodeToad** [comment]
I believe newer versions of Minecraft allow components (allowing for rgb colours) instead of legacy strings.

**Comment by cullvox** [comment]
That sounds really cool, I'm a little confused about that and its format. Is this not a traditional string just with characters designating color still?

**Comment by lumiscosity** [comment]
apologies, i wasn't clear enough about this in my initial issue. 
> I believe newer versions of Minecraft allow components (allowing for rgb colours) instead of legacy strings.

>  Is this not a traditional string just with characters designating color still?

it's actually an array of dictionaries:
```json 
{
	"pack": {
		"pack_format": 15,
		"description": [{"text":"Format ","color":"gold"},{"text":"Example","color":"gold"}]
	}
}
```

**Comment by cullvox** [comment]
So currently will read in that description, and converts it to a normal strings without any color codes. Might require more work, but for now this is a simple solution that shows proper text.
