### ISSUE TITLE
have the prism launcher logo as the default

### ISSUE THREAD

**Issue by terraria99** [PrismLauncher/PrismLauncher#161]
### Role

i having the logos look good

### Suggestion

have the prism launcher logo as the default instance logo

### Benefit

you dont need to change the instance logo

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

multimc used to have its logo as the default instance logo 
ive tried to figure out how to get it to work by having the logo svg named "default" in the icons folder but the launcher wouldnt auto select it and wouldnt even let me manuly select it

**Comment by terraria99** [comment]
looking closer at the code that selects the default it seems i misread it so i should be able to make a PR if this is agreed to

**Comment by DioEgizio** [comment]
> multimc used to have its logo as the default instance logo

over an year ago but yeah i agree it'd be cool

**Comment by DioEgizio** [comment]
i don't think this is worth it anymore, the new grass icon (the one in develop) looks very good

![grass](https://user-images.githubusercontent.com/83089242/206429161-47cd27f9-9da8-4d01-8317-b0473c79b315.png)

**Comment by terraria99** [comment]
i have a very bad habit of forgetting to actually do things but i do like the new grass icon so ill close this
