### ISSUE TITLE
Unable to launch PrismLauncher-Linux-7.2-x86_64.AppImage on wayland

### ISSUE THREAD

**Issue by groggone** [PrismLauncher/PrismLauncher#1610]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

qt6-wayland 6.5.2-2

### Description of bug

When i try to launch PrismLauncher-Linux-7.2-x86_64.AppImage with the environment variable `export QT_QPA_PLATFORM=wayland` and qt6-wayland installed, it still says this:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

zsh: IOT instruction (core dumped)  ./PrismLauncher-Linux-7.2-x86_64.AppImage
```

### Steps to reproduce

* Install Prism Launcher release 7.2 appimage through https://github.com/PrismLauncher/PrismLauncher/releases/tag/7.2
* Turn the newly installed Prism Launcher appimage through `chmod +x PrismLauncher-Linux-7.2-x86_64.AppImage`
* Execute the Prism Launcher appimage through `./PrismLauncher-Linux-7.2-x86_64.AppImage`

**Comment by Trial97** [comment]
Can you try setting the `QT_QPA_PLATFORM=xcb` ?
Or does it work without the mentioned env variable? 

Also please note that Minecraft may not work on wayland.

**Comment by groggone** [comment]
Nevermind this, Prism Launcher works in pure wayland in the binary
versions, i have with me both the latest binary versions of Prism Launcher,
on pure wayland, and i can run them perfectly fine

**Comment by Trial97** [comment]
Then can I close this issue if everything works?

**Comment by groggone** [comment]
Sure thing, but running the Appimage on pure wayland still doesn't work, i've tried to run it just now and it just doesn't work. And mind you, it's the latest version, Prism Launcher 7.2, just downloaded it and it does what i said it does, it doesn't work.

**Comment by Trial97** [comment]
From my knowledge, we build the appimage for x11 so you may need XWayland to run it.

Here are some references for running Appimages under wayland:
https://github.com/AppImage/AppImageKit/wiki/Wayland

**Comment by Scrumplex** [comment]
AppImage maintainers are very hostile towards Wayland. See https://github.com/probonopd/linuxdeployqt/pull/540
https://github.com/probonopd/linuxdeployqt/issues/189

Among other issues this has made us consider dropping AppImage support. It is just an objectively bad packaging format, compared to Flatpak. Though Nix is my personal favorite
