### ISSUE TITLE
Ability to upload image to imgur account instead as an anonymous person

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#1614]
### Role

I play modded Minecraft

### Suggestion

I want to be able to upload to my account on imgur instead as an anonymous user

### Benefit

So if you upload something you change your mind on that you want to take off since it's on your account you'd be able to delete it

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

As far as I know users on imgur who upload images with their account instead as an unregistered user are able to take down those images. Maybe Prism Launcher can have somewhere in settings where you put your sign in credentials so it signs in and uploads to your account. Or maybe it uses a token to upload. 

I'm not sure if this is possible or not but since I couldn't find anyone else asking/suggesting this in issues I figured it'd be fine to suggest

**Comment by Trial97** [comment]
The imgur doesn't really offer a nice way to do that.
