### ISSUE TITLE
'Close Launcher After Game Window Opens' Option Fails to Close Launcher Properly

### ISSUE THREAD

**Issue by quackerex** [PrismLauncher/PrismLauncher#1615]
### Operating System

macOS

### Version of Prism Launcher

7.2

### Version of Qt

6.5.0

### Description of bug

The 'Close the launcher after game window opens' option fails to close the launcher entirely; it currently only closes the launcher window while leaving the launcher process running in the background.

### Steps to reproduce

1. Enable "Close the launcher after game window opens" in settings
2. Open a Minecraft instance

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Yep, that is the intended behavior (in case the game crashes we can display the logs).
If you want to close the launcher  with the game window  we have the option: `Quit the launcher after game window closes`

**Comment by quackerex** [comment]
> Yep, that is the intended behavior (in case the game crashes we can display the logs).

Fair enough.

I think it is best to add an option to get the window back.
Something similar to menu option in Notes App that allows to get the window back after closing (but the app isn't completely closed).
AFAIK quitting the game is the only way to get the window back.
<img width="787" alt="Screenshot" src="https://github.com/PrismLauncher/PrismLauncher/assets/41659980/1ab818d5-6962-4305-8be6-9d1db3cafd4f">

**Comment by Trial97** [comment]
>I think it is best to add an option to get the window back.

Did you try to reopen the application?
Also because we do not have support for systray yet(https://github.com/PrismLauncher/PrismLauncher/issues/778) adding a similar option would be impossible.

**Comment by quackerex** [comment]
> Did you try to reopen the application?

Not really. To reopen the window.
Due to how macOS handle windows, apps can still be open without any windows.

> Also because we do not have support for systray yet(https://github.com/PrismLauncher/PrismLauncher/issues/778) adding a similar option would be impossible.

macOS doesn't have a 'systray'. Menu option will suffice. 
This could be simply implemented under the 'Window' menu: https://github.com/PrismLauncher/PrismLauncher/issues/1625
