### ISSUE TITLE
Add support for downloading mods for a different loader

### ISSUE THREAD

**Issue by Haskellered** [PrismLauncher/PrismLauncher#1616]
### Role

If I want to use a mod such as Fabricated Forge, I cannot download forge mods in the built-in downloader.

### Suggestion

Add an option to ignore loader in the mod downloader/detect when such mods (i.e. Fabricated Forge) are present.

### Benefit

I can use the built in downloader to download mods for other loaders.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Afaik there aren't any issues that are the same as this/similar, but I have not looked much.

**Comment by TheKodeToad** [comment]
https://github.com/PrismLauncher/PrismLauncher/issues/1521
still possible though - I just don't think we should look for specific mods.

**Comment by Haskellered** [comment]
> I just don't think we should look for specific mods.

I agree, just mentioning it.
