### ISSUE TITLE
Apple Silicon users need manual migration

### ISSUE THREAD

**Issue by Scrumplex** [PrismLauncher/PrismLauncher#162]
Currently, Apple Silicon macOS users need to manually clear all cache to make the launcher work, if they migrated from ManyMC or PolyMC.

# Instructions

1. Make sure that Prism Launcher is using the default metadata service in Settings → APIs → Metadata Server (it should be empty and say `https://meta.prismlauncher.org/v1/`)
2. Quit Prism Launcher
3. Navigate to your data directory.
  - This is `~/Library/Application Support/PolyMC` or `~/Library/Application Support/PrismLauncher`
  - The launcher will prefer using the `PolyMC` folder over `PrismLauncher` currently.
4. Delete the following four files and folders: `meta metacache cache libraries`
5. Reopen Prism Launcher and start using it again!

Note: `~` is your home directory.

**Comment by Goobaroo** [comment]
Thanks this fixed my launching issues.

**Comment by ghost** [comment]
I think you should rename "M1" to "Apple Silicon" to avoid confusion cuz M2 also exist (: 
Also this issue could apply to any macOS users whether they use the silicon or intel processor
> The launcher will prefer using the PolyMC folder over PrismLauncher currently.

I don't think this is a good practice.

**Comment by Scrumplex** [comment]
@mistic316
> I don't think this is a good practice.

We will offer a migration dialog in a future update.

**Comment by meadowsys** [comment]
oh! for **GOODNESS** sake, thank you so much >w<

I've found that x64 versions of java work fine without doing this, and have just been using that and taking the performance hit

**Comment by Scrumplex** [comment]
Should not be needed anymore thanks to the migration dialog

**Comment by DioEgizio** [comment]
What about people that precious used manymc? I don't think the migration dialog can migrate from it

**Comment by Scrumplex** [comment]
> What about people that precious used manymc? I don't think the migration dialog can migrate from it

We also don't have instructions specific to ManyMC here.
They also have instructions here: https://github.com/MinecraftMachina/ManyMC
