### ISSUE TITLE
Crashes when adding mods from Modrinth and Curseforge

### ISSUE THREAD

**Issue by DrDoctor13** [PrismLauncher/PrismLauncher#1622]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.0

### Version of Qt

Qt 6.5.1

### Description of bug

Selecting mods to download in an instance from Modrinth then going to Curseforge and selecting some mods causes a crash when trying to go back to Modrinth.

### Steps to reproduce

- Open the mods menu of an instance
- Search for and select at least one mod from Modrinth
- Switch to CurseForge
- Select at least one mod
- Switch back to Modrinth

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Hi, can you try to reproduce it on the latest version(7.2):https://prismlauncher.org/download/?

**Comment by DrDoctor13** [comment]
7.2 appears to fix this issue. Sorry, I did not know there was a new version.
