### ISSUE TITLE
Flatpak users need manual migration

### ISSUE THREAD

**Issue by Scrumplex** [PrismLauncher/PrismLauncher#163]
Flatpak users need to manually move their data directory in order to use Prism Launcher, if they used PolyMC before.

# Instructions

1. Install Prism Launcher from Flathub
2. Open Prism Launcher and quit it again
3. Navigate to your old data directory `~/.var/app/org.polymc.PolyMC/data`
4. Move or copy the `PolyMC` folder in your data directory to the new data directory `~/.var/app/org.prismlauncher.PrismLauncher/data`
5. Delete the `PrismLauncher` folder in the new data directory and rename `PolyMC` to `PrismLauncher`
6. Reopen Prism Launcher and start using it again!

Note: `~` is your home directory.

**Comment by DioEgizio** [comment]
> Install Prism Launcher from Flathub

Do you come from the future?

**Comment by Scrumplex** [comment]
yes :pofat:

**Comment by jeronimosg** [comment]
Is there a way for Flatpak users to change the default path where the launcher searches for instances/config files/other data, without individually changing some of them form the launcher.

I'm looking for somthing similar to ATLauncher `CUSTOM_DIR` env variable.

**Comment by orowith2os** [comment]
@UpsettingBoy I believe setting the appropriate `XDG_` variables would do the trick. but could be wrong; I've seen many things hardcode `~/.config`, so it might not work, but it's worth a shot.

**Comment by jd-santos** [comment]
For step 4 I think it would help to clarify the full data path for PrismLauncher:
`~/.var/app/org.prismlauncher.PrismLauncher/data`

I know it seems redundant, but people uncomfortable with Linux or CLIs might be thrown off.

**Comment by Scrumplex** [comment]
> For step 4 I think it would help to clarify the full data path for PrismLauncher: `~/.var/app/org.prismlauncher.PrismLauncher/data`
> 
> I know it seems redundant, but people uncomfortable with Linux or CLIs might be thrown off.

fixed it in my post above. Thanks!

**Comment by catvin82** [comment]
I am a flatpak user and idk what is happening with these projects. It seems like this is something with members or that, but it looks like prism launcher is an upgrade of polymc. I have installed the polymc flatpak and see it in my "software" aplication. I am using fedora 36. I noticed the change and can't find polymc on the flatpak website, but i can see it in my "software" app. Can somebody tell me what is happening?

**Comment by Scrumplex** [comment]
@catvin82 Just download Prism Launcher from "Software" and move the files as described above.

If you want to read about why this happened check this: https://www.pcgamer.com/minecraft-launcher-project-spins-out-of-control-after-dev-hijacks-it-to-fight-leftist-queer-ideology/

Or this video: https://www.youtube.com/watch?v=kY3xfU08Drw

**Comment by catvin82** [comment]
Thanks! I just moved to prism and uninstalled polymc! thanks for letting me know that this was happenning. I didn't hear the news so assumed somthing was off because of the devs on the repo.

**Comment by USMP-lancer** [comment]
good to know

**Comment by Scrumplex** [comment]
Closing this, as it's probably not very relevant anymore.
