### ISSUE TITLE
A super-search option on right click

### ISSUE THREAD

**Issue by ColonelGerdauf** [PrismLauncher/PrismLauncher#1635]
### Role

I look for specific keywords in mods

### Suggestion

When you right click in a menu inside an instance screen, it should provide an option to search in the given directory.

### Benefit

Random times where one wants to search for mods that are linked to a mod or concept

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This is obviously going to depend on the operating system and what searching software is installed.

For example, in Windows you can set it where if it finds Everything Search, Prism can hook to that app and provide the right-click option `Search Everything...`. If such software is not present as an installed program or an active service, nothing happens and that extra option does not show up.

Likewise can happen in Linux with rlocate. OSX already comes with Spotlight, so it is simply a matter of starting the prompt and pre-loading the directory parameter to search in.

**Comment by Trial97** [comment]
This sounds like something very complicated that would require adding additional dependencies to the launcher for a task that can be achieved by searching in the instance folder using the file manager.
We also have a filter for each resource so if you have too many mods you can use that.
