### ISSUE TITLE
Functional keys not working

### ISSUE THREAD

**Issue by Faboslav** [PrismLauncher/PrismLauncher#1636]
### Version of Prism Launcher

7.2

### Version of Qt

6.5.0

### Description of bug

With official mc launcher functional keys works as expected, with prism launcher no functional key works(for example f3 and f5 does nothing), also i am on OSX (Sonoma public beta).

### Steps to reproduce

Run it on osx try functional keys.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Do you mean in-game functional keys or do you mean in launcher?

**Comment by Faboslav** [comment]
Sorry about that, i mean in game

**Comment by Trial97** [comment]
Is this happening on a vanilla instance?
Just for a note the launcher doesn't change Minecraft logic so most probably is something wrong with that instance.

**Comment by Faboslav** [comment]
Yeah, on all instances (even without any mod loader)

**Comment by Faboslav** [comment]
With new sonoma update it somehow works now :).
