### ISSUE TITLE
Add LWJGL 3.3.3 to version selection

### ISSUE THREAD

**Issue by lospejos** [PrismLauncher/PrismLauncher#1645]
### Role

I play modded Minecraft using Prism Launcher

### Suggestion

It would be nice to have a 3.3.3 in LWJGL version selection, since this it out already

### Benefit

Most recent graphics library

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I'm not sure if there are some compatibility issues with this new version

New LWJGL 3.3.3 version is here: https://github.com/LWJGL/lwjgl3/releases/tag/3.3.3

**Comment by Scrumplex** [comment]
We only include LWJGL versions that are used by Mojang.

It also shouldn't matter as new features will not really affect older versions of the game.
