### ISSUE TITLE
[BUG] PrisimLauncher Quick Setup detects two of the same install (P4)

### ISSUE THREAD

**Issue by O-J1** [PrismLauncher/PrismLauncher#166]
### Operating System

Windows

### Version of Prism Launcher

V5.0

### Version of Qt

N/A yet to install

### Description of bug

Running PrismLauncher-Windows-Setup-5.0.exe and getting to the quick setup window shows two of the same Adoptium installs. This is a poor human experience as it may confuse users as to which one is the right one (albeit both will work). Low priority bug IMO 

Occurs on both Windows 10 and 11, confirmed by two users in the discord

### Steps to reproduce

1. Download PrismLauncher-Windows-Setup-5.0.exe
2. Run the .exe
3. Select American English (Likely unimportant) as your language then click next
4. Observer Quick setup displaying two of the same Adoptium installs (same path, version etc)

![image](https://user-images.githubusercontent.com/18110006/196924479-34e0cddb-be10-4cc8-932a-504312350e03.png)

### Suspected cause

Unknown 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
This might have been introduced by PolyMC/PolyMC#1068

CC @TayouVR

**Comment by Scrumplex** [comment]
We might just need to remove duplicates in the final list

**Comment by O-J1** [comment]
> We might just need to remove duplicates in the final list

That would honestly be fine 👍

**Comment by TayouVR** [comment]
my PR just added java installs from path, I didn't add anything to see if they already got found another way. I can look into adding deduplication some time for sure ^^
Now that I am starting to get a bit more familiar with C++ and Qt I get a lot more comfortable actually committing to doing things!

**Comment by AliceDTRH** [comment]
@TayouVR This issue sounds simple, can I try doing this one?

**Comment by TayouVR** [comment]
@AliceDTRH sure, go ahead!

**Comment by AliceDTRH** [comment]
@TayouVR 
I changed my mind, going to buy CLion first. Sorry for the trouble.
