### ISSUE TITLE
1.20.2 Not Launching/Crashing Immediately (Likely Corrupted icu4j-73.2.jar) 

### ISSUE THREAD

**Issue by IrisWasTaken1** [PrismLauncher/PrismLauncher#1662]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt 6.5.1

### Description of bug

The Game crashes when launching.
Log:
Vanilla: https://mclo.gs/sCDV2xm
Modded: https://mclo.gs/NdVE0hd

### Steps to reproduce

Unknown

### Suspected cause

Corrupted icu4j-73.2.jar (https://forum.quiltmc.org/t/game-failed-to-launch-again-again/2075/11)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
If you think that a library is corrupted you can easily just delete it and try again.
My suggestion would be as follows:
- ensure that the metadata server input is empty on the settings page(Seetings>APIs)
- clear the metadata (Help>Clear Metadata Cache)
- delete the libraries folder(C:/Users/********/AppData/Roaming/PrismLauncher/libraries) they will regenerate when you start the game again
- and then try again

**Comment by Trial97** [comment]
Did any of the mentioned suggestions work for you?

**Comment by Trial97** [comment]
Closing this as there were no responses. 
If somebody else experiences this and none of the mentioned methods work please post it here and we will reopen this issue.
