### ISSUE TITLE
32 bit java detection

### ISSUE THREAD

**Issue by maskersss** [PrismLauncher/PrismLauncher#1664]
### Role

I play Minecraft.

### Suggestion

I want the launcher to somehow warn me against using 32 bit Java,

### Benefit

so that I'm not left confused as to why it doesn't work.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

not sure how exactly this would work, imo the simplest/best way to do it is to just remove 32 bit java from autodetect
you can't just add it to java compat check since it will already be an issue when selecting java while setting up prism

**Comment by Trial97** [comment]
We already report to the user the architecture of the java executable:
![image](https://cdn.discordapp.com/attachments/1118165588200657006/1157134903566159912/image.png?ex=6517815b&is=65162fdb&hm=9ac984f8290fd8ddea916e2877292cd6f62a014d84cb8a567c19db1b8aff82ad&)

We can not stop you from using java x32 as that may be the only java on that machine.
We also have a Test button on the java setting page that lets you test if the selected java works.
Here you can find more information about java settings page: https://prismlauncher.org/wiki/help-pages/java-settings/#java-runtime

**Comment by maskersss** [comment]
"We already report to the user the architecture of the java executable"
i know, however i wouldn't expect most users to know that you can't allocate more than 2 gb with java with x86 architecture

"We can not stop you from using java x32 as that may be the only java on that machine."
i'm not suggesting to completely prevent people from using 32 bit java, just remove it from autodetect
you would be able still select it manually
and i don't think there are that many people who can't install 64 bit java?

"We also have a Test button on the java setting page that lets you test if the selected java works." this button says something along the lines of "The specified Java binary didn't work with the arguments you provided", which still leaves the user confused, i'm sure you can find many examples in the discord in #quick-support
it should be more clear about what's wrong if anything

"Here you can find more information about java settings page: https://prismlauncher.org/wiki/help-pages/java-settings/#java-runtime" this page doesn't mention 32 bit java, and regardless i don't think it's a good idea to make people have to check the wiki

**Comment by Trial97** [comment]
> i know, however i wouldn't expect most users to know that you can't allocate more than 2 gb with java with x86 architecture

Your wording did not hint at that: you suggested only a warning against javax32



> i'm not suggesting to completely prevent people from using 32 bit java, just remove it from autodetect
> you would be able still select it manually

Java x32 is still supported to play Minecraft so removing it from autodetect would not make sense.



> and i don't think there aren't that many people who can't install 64 bit java?

Yeah but maybe they are running on a 32 bit system, or they want to use 32 bit java.



> this button says something along the lines of "The specified Java binary didn't work with the arguments you provided", which still leaves the user confused, i'm sure you can find many examples in the discord in #quick-support
> it should be more clear about what's wrong if anything

I completely agree, the message may need improvements. Feel free to open an issue with that, mentioning all the cases in which the message needs to change.

 



> this page doesn't mention 32 bit java, and regardless i don't think it's a good idea to make people have to check the wiki

If you feel that the information is lacking on the wiki feel free to open an issue there regarding that.
And why is it not a good idea to have the users check the wiki? We can not document each case in the launcher.

Unrelated but will help with java installation: there are plans to rework the java system and allow the user to download the java from the launcher here: https://github.com/PrismLauncher/PrismLauncher/pull/285

**Comment by maskersss** [comment]
> Your wording did not hint at that: you suggested only a warning against javax32

i thought x86 = x32 = 32 bit, my bad if not

> Java x32 is still supported to play Minecraft so removing it from autodetect would not make sense.

imo it makes sense since it'll likely not work

> Yeah but maybe they are running on a 32 bit system, or they want to use 32 bit java.

maybe i'm wrong, but again i think there are barely such people and they would still be able to select the java executable manually

> And why is it not a good idea to have the users check the wiki?

if someone just downloaded the launcher, imo they probably wouldn't go check the wiki but would just try to set it up. and i feel like selecting 32 bit java is quite a common issue that will leave make quite a lot of users not be able to set it up and leave frustrated; while if the java wasn't there to select in the first place, they would either select a working Java or get a hint that they need to install another version

**Comment by Trial97** [comment]
> i thought x86 = x32 = 32 bit, my bad if not

Yes, you are correct x86=x32 but what I meant is that in the original message of this issue, you did not mention that you wanted a warning for exceeding 2gb but a warning for x86 java.



> imo it makes sense since it'll likely not work

look into this PR: https://github.com/PrismLauncher/PrismLauncher/pull/1347 and the related issue: https://github.com/PrismLauncher/PrismLauncher/issues/1318 if they can play with 8MB of memory then java x32 can work.



> maybe i'm wrong, but again i think there are barely such people and they would still be able to select the java executable manually

look into the mentioned PR and issue.

 

> if someone just downloaded the launcher, imo they probably wouldn't go check the wiki but would just try to set it up. and i feel like selecting 32 bit java is quite a common issue that will leave make quite a lot of users not be able to set it up and leave frustrated; while if the java wasn't there to select in the first place, they would either select a working Java or get a hint that they need to install another version

that's why we have green(with a checkmark) or red(with X) icons on the first setup java page(when you start the launcher for the first time) : https://github.com/PrismLauncher/PrismLauncher/issues/1664#issuecomment-1740605358 denoting that something is wrong or not.
Also if the x32 bit java was not there and no other java on the system they would still need to check the documentation.
I myself saw a bunch of people on discord who did not even have java installed at all.
