### ISSUE TITLE
Autodetect Java bundled with official launcher

### ISSUE THREAD

**Issue by maskersss** [PrismLauncher/PrismLauncher#1665]
### Role

I'm switching from the official launcher to Prism.

### Suggestion

I want Prism to autodetect Java bundled with the official launcher,

### Benefit

so that I don't have to install Java if I don't have it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

as far as i know official launcher only bundles java 8u51 as java 8 which is really old and might be not worth adding to autodetect? but i don't see any downsides to adding java 17 bundled with the official launcher

**Comment by markfswe** [comment]
Prob related to https://github.com/PrismLauncher/PrismLauncher/issues/734 as it's generally just managing non system wide java installations
