### ISSUE TITLE
New folder in Instances folder.

### ISSUE THREAD

**Issue by xBlake-2012x** [PrismLauncher/PrismLauncher#1667]
### Role

I deleted a Instance an I want it back.

### Suggestion

New folder in Instances folder named "Deleted Instances" filled with the Instances the user deleted

### Benefit

So if i delete a Instance and I need it back.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
Wouldn't it be better if there is a soft delete(move the instance to trash) if the system supports that?
That way if you need an old instance you can restore it from the system bin.

**Comment by TheKodeToad** [comment]
#289
