### ISSUE TITLE
The -s parameter not working

### ISSUE THREAD

**Issue by StaelensJarne** [PrismLauncher/PrismLauncher#1669]
### Operating System

Windows

### Version of Prism Launcher

7.2

### Version of Qt

6.5.1

### Description of bug

According to the [documentation](https://prismlauncher.org/wiki/getting-started/command-line-interface/) it should be possible to join a server when the launcher starts.

I have a Minecraft Java server installed on a rasberry pi. The server has ip-adress 192.168.0.156 and port 25565.
Can the server be located anywhere in the LAN network? Or does the server needs  to be installed on the same device the launcher is installed?

The server is online because it has a green icon on the right.
![MyServer](https://github.com/PrismLauncher/PrismLauncher/assets/26405591/c3b2cc31-4708-4b8e-bffe-677ce49f1158)

But when I try to use the command it only opens the instance and does not join the server.
This is the command that I use:
`.\prismlauncher -l "MyInstance" -s "My Java Server"`

I also tries the -s parameter with the ip-adress and the port but nothing works.

### Steps to reproduce

Use the -s parameter in combination with -l .

### Suspected cause

The second parameter is not read properly. If I go through the output of the command, it always says this:
![parameter not read](https://github.com/PrismLauncher/PrismLauncher/assets/26405591/7a16d848-db27-4f26-b9bf-526c7fbdc7b1)
I also included the log file from the launcher.
[PrismLauncher-1.log](https://github.com/PrismLauncher/PrismLauncher/files/12777496/PrismLauncher-1.log)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
On what minecraft version is this happening?

**Comment by StaelensJarne** [comment]
This is version 1.19.2.

I don't have tested this with a older version. Is it possible that this will work with 1.19 or 1.18?

**Comment by Trial97** [comment]
This looked similar to the issue solved here: https://github.com/PrismLauncher/PrismLauncher/pull/1164
But as the version is different it may be a separate issue
