### ISSUE TITLE
improve windows support

### ISSUE THREAD

**Issue by DioEgizio** [PrismLauncher/PrismLauncher#167]
tracking issue for improving windows support in general

- [x] making things work fine on windows 7 again (#134)
- [x] adding updater (#94)
- [x] making windows 64 bit builds work
- [x] msvc builds

**Comment by DioEgizio** [comment]
This thing is hacky and will never be officially supported

**Comment by Scrumplex** [comment]
Can you provide any sources for those DLLs? At this point, I can't recommend anyone to include these random DLL files in their Prism Launcher installation.

Apart from security issues arising from use of unknown DLLs, Windows 7 itself isn't an ideal OS to run in 2023. Please update to a supported Windows release or switch to a Linux distribution.

**Comment by DioEgizio** [comment]
I mean you can just use Windows-MSVC-Legacy until it gets discontinued, at the end all qt6-exclusive features depends on windows API changes
