### ISSUE TITLE
Set NO_COLOR for custom commands

### ISSUE THREAD

**Issue by RuiNtD** [PrismLauncher/PrismLauncher#1677]
### Role

I use custom commands to automatically backup my instances

### Suggestion

The NO_COLOR env variable should be set for custom commands

### Benefit

This would prevent custom commands from outputting ANSI color codes that don't work in Prism Launcher's log UI

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
You should already be able to do that yourself, but I guess it'd make sense (I doubt it would cause issues).

**Comment by RuiNtD** [comment]
I mean, NO_COLOR is a standard for CLI applications to not output color ANSI. See here: https://no-color.org/
