### ISSUE TITLE
Modpack versioning

### ISSUE THREAD

**Issue by codefreak558** [PrismLauncher/PrismLauncher#170]
### Role

I play modded minecraft

### Suggestion

I would like if somewhere maybe in the taskbar then you click an instance you have the version number and the place it was downloaded from e.g. GT New Horizons 2.2.0 Curseforge

### Benefit

You won't have to try and remember what version your instance modpack is on to find out if there is new updates

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

When the modpack updater becomes more polished what you could do is with the modpack versioning make it run a check on the modpacks you have installed to see if there is an update then you can put a upgrade icon by the instance. You can also make a setting that makes it so that you can turn on or off the modpack update checker

**Comment by MenacingPerson** [comment]
Like modpacks could be added to this screen:

![image](https://user-images.githubusercontent.com/59611020/196952889-6e8fcc03-ab96-4fb1-972e-f01e655c5bc3.png)

**Comment by codefreak558** [comment]
Yeah or even here:
![Screenshot](https://user-images.githubusercontent.com/46318596/196958296-82040d25-37e1-47b4-9b64-16ab41294565.png)
I think maybe having it be at the bottom of this would work

**Comment by flowln** [comment]
Currently modpacks have their managing data (like original name, version, id, etc) storef in the `instance.cfg` file on the instance, as managed pack data. So, they are not components, and really don't fit all that well with the overall structure of components internally i think. So instead, what is currently WIP is having a separate page for managing those information in a graphical way. We could maybe do something in the sidebar too, depending on how it will change in the upcoming UI reworks.

Anyways, the preliminary work for this is being done in #32 (i should add some images later :p), and things like automatically checking for updates and such can come later :)

**Comment by codefreak558** [comment]
Yeah I think that having it's own tab in the "edit instance" could be better. Having the version in the sidebar could be changed to show it in the bottom bar where it shows the minecraft version with playtime?
