### ISSUE TITLE
Login issue since 7.2

### ISSUE THREAD

**Issue by Syon11** [PrismLauncher/PrismLauncher#1700]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

6.5.3

### Description of bug

Unable to authenticate a microsoft account. Microsoft's webside succeeds, however Prism is uanble to auth. Upon checking the logs, it seems like Microsoft throws an error code 7000 for malformed or incorrect request and is flagged as a developper  problem

### Steps to reproduce

* Go in account management
* Add Microsoft account
* Follow the steps
* Surprised pikachu face

### Suspected cause

Microsoft's error page seems to point like it is a developper error, an update of their login API seems unlikely. I have no clue, tbh.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Syon11** [comment]
Nvm, I reverted to Qt5 and it's working... it's the Qt6 update on arch bug, my bad, sorry about this.

**Comment by BVengo** [comment]
This should probably remain open as a bug. KDE Plasma is updating to Qt6 as their primary version, so this requires holding the whole system back just to use prismlauncher.
