### ISSUE TITLE
Minecraft 1.20.2 crashes with exit code 65, "Invalid argument"

### ISSUE THREAD

**Issue by revantTNK** [PrismLauncher/PrismLauncher#1705]
### Operating System

_Fedora 38 KDE on BTRFS_

### Version of Prism Launcher

Prism Launcher 7.2 installed from the Copr repo for Fedora 38.

### Version of Qt

Qt 5.15.10; default Qt bundled with KDE 5.27

### Description of bug

I have a fresh install of Prism Launcher 7.2. If I try to launch Minecraft 1.20.2, it crashes with exit code no. 65.

### Steps to reproduce

I have no idea how to reproduce this error, but I am running a fresh install of Fedora 38 on BTRFS. I tried it with both Java 17 and 21.

### Suspected cause

This error might have occurred due to my system's filesystem. It uses BTRFS instead of EXT4 like any other Linux distribution.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Can you share your Minecraft logs?

**Comment by lawriwe** [comment]
same issue, link to log : https://mclo.gs/xfJUQyT

minecraft 1.20.1 works fine, but 1.20.2 refuses to launch

**Comment by l3miage-lawriwe** [comment]
> Can you share your Minecraft logs?

i have the same issue with this log : https://mclo.gs/xfJUQyT

1.20.2 refuses to launch
1.20.1 works fine tho
