### ISSUE TITLE
mod updater

### ISSUE THREAD

**Issue by pizzav-xyz** [PrismLauncher/PrismLauncher#1710]
### Role

when mc updates

### Suggestion

update mods from old version to new

### Benefit

easy mod upodate

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

[quoted from discord messages in the fabric project](https://discord.com/channels/507304429255393322/1162784538947231815)

a mod which automaticly updates mods from old version to new for example 1.20.1 to 1.20.2 and removes/ adds .disabled to the names if no updated version can be found

that updates mods but doesnt try to find version for other game version and doesnt add .disabled to the names if no updated version 
or jsut deletes

**Comment by pizzav-xyz** [comment]
ai generated this for me


Feature Request: Mod Updater

Problem: Manually updating Minecraft mods can be time-consuming and tedious, especially when there are many mods to update. It can also be difficult to track which mods have updates available, and to ensure that all mods are compatible with the latest version of Minecraft.

Solution: A mod updater would automatically check for updates to installed mods and download and install them seamlessly. This would save users time and effort, and help to ensure that their mods are always up to date.

Implementation: The mod updater could be implemented as a standalone mod or as a feature integrated into the PrismLauncher launcher. If implemented as a standalone mod, it would need to be installed separately from PrismLauncher. If implemented as a feature of PrismLauncher, it would be automatically available to all PrismLauncher users.

Benefits: A mod updater would provide several benefits to PrismLauncher users, including:

Reduced time and effort required to update mods
Improved compatibility between mods and Minecraft versions
Reduced risk of crashes and other problems caused by outdated mods
Example Use Case: A PrismLauncher user with a modpack containing 100 mods could use the mod updater to check for updates to all mods with a single click. The mod updater would then automatically download and install any available updates. Once the updates are installed, the user could launch their modpack and start playing without having to worry about whether their mods are up to date.

Button: The mod updater could be implemented as a button in the PrismLauncher launcher. The button could be labeled "Update Mods" or "Check for Updates". When the user clicks on the button, the mod updater would check for updates to all installed mods. If any updates are found, the mod updater would prompt the user to download and install them.

I hope this feature request is helpful. Please let me know if you have any other questions or suggestions.

**Comment by TheKodeToad** [comment]
I don't see how that could help - you can use AI but the people who will read this are even better - AI without the 'A'!

**Comment by Trial97** [comment]
I'm not sure what is this about, can you elaborate more?
Right now we already have a button to update the mods.
What do you want more?

**Comment by pizzav-xyz** [comment]
> I'm not sure what is this about, can you elaborate more? Right now we already have a button to update the mods. What do you want more?

update mods from 1.20.1 to 1.20.2 and disable the ones which dont have 1.20.2 version yet

**Comment by Trial97** [comment]
Well this is already partially implemented as you can already update them.
But disabling automatically the mods sounds like a bad idea as some mods have compatibility over minor Minecraft versions

**Comment by Trial97** [comment]
In this case, I would better go with an additional column that will display the Minecraft version that the mod is compatible with, allowing the user to order and disable them if needed.

**Comment by pizzav-xyz** [comment]
> In this case, I would better go with an additional column that will display the Minecraft version that the mod is compatible with, allowing the user to order and disable them if needed.

When will this be implemented?

**Comment by Trial97** [comment]
Unsure: nobody picked this up

**Comment by Trial97** [comment]
the MC version column was added by: https://github.com/PrismLauncher/PrismLauncher/pull/1728
Is this enough to consider this as completed?

**Comment by Trial97** [comment]
Closing this as the column was added in https://github.com/PrismLauncher/PrismLauncher/pull/1728
