### ISSUE TITLE
Can not apply read-only themes that don't have `resources`

### ISSUE THREAD

**Issue by Anomalocaridid** [PrismLauncher/PrismLauncher#1719]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.2

### Version of Qt

Qt 6.5.3

### Description of bug

I used NixOS's home manager to get the Catppuccin Mocha theme and place it in ~/.local/share/PrismLauncher/themes. I expected it to work properly, appearing in the Colors drop-down menu in the User Interface settings and appearing properly when selected. However, instead, a blank entry appears in the drop-down menu that makes the theme look like the default Bright theme.

This does not occur when I manually download and install the theme. In this case, it appears in the drop-down menu properly and appears how I expect it to once set.

### Steps to reproduce

* On NixOS, install the `prismlauncher` package
* Put the following snipped in your home manager config:
```nix
  xdg.dataFile."PrismLauncher/themes/catppuccin-mocha".source = pkgs.fetchzip {
    url = "https://github.com/PrismLauncher/Themes/releases/latest/download/Catppuccin-Mocha.zip";
    hash = "sha256-8uRqCoe9iSIwNnK13d6S4XSX945g88mVyoY+LZSPBtQ=";
  };
```
* run `nixos-rebuild test`
* Open Prism Launcher and go to Settings>Launcher>User Interface>Colors.
* Opening the drop-down menu will show it now has a blank entry. Selecting it sets the theme to what appears to be the default Bright theme.

### Suspected cause

I think this might have something to do with the fact that the theme's directory is a symlink to the read-only nix store.

Although I think it is only the read-only part that is causing issues because manually placing a symlink to a non-read-only directory with the theme in it does not appear to cause this issue, with the theme working properly.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Also present in develop

**Comment by Scrumplex** [comment]
https://github.com/PrismLauncher/PrismLauncher/blob/8f2f99801e327e1276c571a72457322d0471771a/launcher/ui/themes/CustomTheme.cpp#L168-L171

This is the source of the issue. Most of our themes from https://github.com/PrismLauncher/Themes don't have a `resources` folder, so Prism is trying to create it but ultimately fails. I could push an empty `resources` folder to all our themes to work around this, until we can fix this in our upcoming release.

**Comment by Trial97** [comment]
We also try to write the theme a few lines after:
https://github.com/PrismLauncher/PrismLauncher/blob/8f2f99801e327e1276c571a72457322d0471771a/launcher/ui/themes/CustomTheme.cpp#L188-L190

**Comment by Scrumplex** [comment]
Yes. But that doesn't stop the theme from loading, so it should be fine and at most just a warning in the logs

**Comment by Anomalocaridid** [comment]
I can confirm that adding an empty `resources` folder makes it work.

Edit: Never mind. I misunderstood and I did not notice you all already did it to the affected themes
