### ISSUE TITLE
Crash when downloading a resource pack through launcher

### ISSUE THREAD

**Issue by TayouVR** [PrismLauncher/PrismLauncher#1740]
### Operating System

Windows

### Version of Prism Launcher

8.0 dev (c638a63a03f60bd43975ad8d069950fbb43de895) from 18/10/2023

### Version of Qt

6.6

### Description of bug

upon scrolling to the downloaded resource, right after downloading it, it crashes the launcher.
```
    19.062 D | Setting up api download
    19.519 D | Setting up api download
    19.525 D | Setting up api download
    19.532 D | Setting up api download
    19.535 D | Setting up api download
    19.537 D | Setting up api download
    19.540 D | Setting up api download
    19.543 D | Setting up api download
    19.548 D | Setting up api download
    19.553 D | Setting up api download
    19.556 D | Setting up api download
    19.559 D | Setting up api download
    19.566 D | Setting up api download
    19.569 D | Setting up api download
    21.814 D | Setting up api download
    21.978 D | Setting up api download
    21.979 D | Setting up api download
    21.980 D | Setting up api download
    22.751 D | Setting up api download
    22.752 D | Setting up api download
    26.616 W | QWindowsWindow::setGeometry: Unable to set geometry 480x139+487+469 (frame: 496x178+479+438) on QWidgetWindow/"ProgressDialogWindow" on "S24F350 (1)". Resulting geometry: 480x204+487+469 (frame: 496x243+479+438) margins: 8, 31, 8, 8 minimum size: 480x139 MINMAXINFO(maxSize=POINT(x=0, y=0), maxpos=POINT(x=0, y=0), maxtrack=POINT(x=0, y=0), mintrack=POINT(x=496, y=178)))
    26.647 D | Setting up api download
    53.016 D | [launcher.task.net.metacache.http]: Saving metacache with 20 entries
   132.590 D | Resource Pack "KoP 1.8 V9 256 modern - Kopie" Had it's image evicted from the cache. reloading...
   132.602 W | Invalid type for resource pack parse task!
   132.602 D | Resource Pack "KoP 1.8 V9 256 modern font" Had it's image evicted from the cache. reloading...
   132.603 F | ASSERT: "pack.type() == ResourceType::ZIPFILE" in file D:\a\PrismLauncher\PrismLauncher\launcher\minecraft\mod\tasks\LocalResourcePackParseTask.cpp, line 237
```

### Steps to reproduce

- go to resource packs on any instance (in my case the resource pack folder is symlinked elsewhere, probably doesn't matter)
- download pack (in my case LB Photo Realism 6.0 from modrinth)
- observe launcher crash

### Suspected cause

bug in LocalResourcePackParseTask.cpp around L237 probably?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by lumiscosity** [comment]
i've had an an identical bug happen occasionally when opening the resource pack tab in an instance after having ran the launcher for a while. also on a build of 8.0

**Comment by TayouVR** [comment]
I tried to follow the exact steps from yesterday on a manual build with debugger, and on the same build version, but i can't get it to crash anymore...
I am still experimenting, but if anyone can provide more precise steps to reproduce this I would be very grateful!

Edit: managed to reproduce it, fixed PR below
