### ISSUE TITLE
[8.0-develop]: Dependency check doesn't work between CurseForge and Modrinth

### ISSUE THREAD

**Issue by SiverDX** [PrismLauncher/PrismLauncher#1745]
### Operating System

Windows

### Version of Prism Launcher

8.0-develop

### Version of Qt

Qt 6.6.0

### Description of bug

Build used: https://github.com/PrismLauncher/PrismLauncher/actions/runs/6605886969

If you have a mod installed from Modrinth which has a required dependency
And you have said required dependency installed but from CurseForge (or the other way around)
Then it won't be able to find it and therefor try to download / recommend it on every update check

This is also relevant for modified versions of a mod (see Just Enough Resources in this screenshot)
It doesn't recognize it as the dependency it needs

![image](https://github.com/PrismLauncher/PrismLauncher/assets/22003703/83569c0b-8d51-4567-92a2-630e290447cc)

![image](https://github.com/PrismLauncher/PrismLauncher/assets/22003703/b4f6c988-5e9f-4b4e-9f9f-7211f38a7608)

![image](https://github.com/PrismLauncher/PrismLauncher/assets/22003703/483b7691-3657-4804-828f-68b7630fd888)

### Steps to reproduce

See description

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Hi @SiverDX,
Right now the dependency check is based on the project ids, and because they are two different providers these do not match between them.
Would you happen to have any suggestions on determining whether you have met the dependencies?
My suggestion is to try to download most of your mods from one provider.
Would it solve your problem if we add a way to disable dependency checking on updates?

**Comment by SiverDX** [comment]
I already tried to stay on one provider but some mods are not present on both
I'm not sure which data you have available for the check (if you had the mod id you'd probably already use that I guess)

An option to disable the check for specific mods would help
Or on update as a general option I suppose (as you suggested)

**Comment by pointydev** [comment]
I just ran into this issue after updating to the 8.0 release, and (for example) even when specifically disabling the CurseForge Fabric API dependency in the updater that is given by some mods while the version from Modrinth is updating, I end up getting the CurseForge copy anyway. See below for the before, during and after of the aforementioned.

![before update](https://github.com/PrismLauncher/PrismLauncher/assets/22241432/4830e57c-15ed-4c27-a67d-e2ad5496f02f)
![during update](https://github.com/PrismLauncher/PrismLauncher/assets/22241432/69df3982-a10c-477b-8357-7d318cdd38cf)
![after update](https://github.com/PrismLauncher/PrismLauncher/assets/22241432/156ef507-1ff2-4747-9cd1-eb8198d75a34)

Personally I would like to see a user-configurable way to blacklist specific mods from certain providers as dependencies, giving the user the autonomy to use their better judgement if they know they already have it by other means.

Thanks,
pointy

**Comment by Trial97** [comment]
The dependency stuff can't distinguish between mods from curse and modrinth so that is expected.
You have a setting to disable the dependency in settings>launcher>mods
Also regarding the blacklist stuff that sounds like a separate issue

**Comment by LastExceed** [comment]
would it be possible to implement something like
> mod X requires dependency Y from curseforge, but a mod called Y from modrinth is already installed. do you want to skip this dependency?

i am aware that a mere name match doesn't guarantee compatibility (or even being the same mod at all), which is why the user should be prompted to decide case by case

**Comment by Trial97** [comment]
I already added a file name check here: https://github.com/PrismLauncher/PrismLauncher/pull/1786
