### ISSUE TITLE
Arch PKGBUILD requires OpenJDK

### ISSUE THREAD

**Issue by DeJayDev** [PrismLauncher/PrismLauncher#1749]
Hi,

Immediate apology for not using a template.

In updating `prismlauncher` from the AUR I noticed that I was being asked to download `jdk17-openjdk` as a make depends. Looking at the revision history, this seemed intentional but I could not find any specific reasoning in the Prism Launcher Discord or the issues here. Honestly maybe it's weird that I care so much about a dependency only used for building, but pulling in `openjdk` onto systems that may already have `corretto`, `zulu`, or any other JDK is a redundant step. 

I'm curious why this is the way it is instead of using `java-environment-common>=17`?

**Comment by txtsd** [comment]
We already do `java-runtime=17` in `depends`. I don't see why we can't do `java-environment=17` in `makedepends`.

I'm testing it here:
https://github.com/txtsd/ankylosaurus/pull/5

---

`java-environment-common` and `java-runtime-common` are something else though.
> Official list of binaries that Java headless runtime packages MUST provide
> This list is based on Arch Linux' default Java implementation: "OpenJDK 7 Icedtea"

**Comment by iTitus** [comment]
It still does not work
`aur/prismlauncher  7.2-2 -> 7.2-3`

```
[  5%] Built target systeminfo
make: *** [Makefile:146: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: prismlauncher-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
prismlauncher - exit status 4
```

**Comment by txtsd** [comment]
@iTitus Make sure your default java is 17.
Check with `archlinux-java status`.

We can either pin it to and force ONE particular flavor and version of jdk, or we can let users use whichever flavor they want but this requires the default java to be set to the correct one.

It builds correctly on a clean system.
See the build logs here: https://github.com/txtsd/ankylosAURus/actions/runs/6663230010

**Comment by iTitus** [comment]
My standard JDK is 21 currently, the latest LTS. It works when setting the java to 17.
It would be nice if that requirement would be documented and a better error message were added.

**Comment by DeJayDev** [comment]
While I agree that better error messages should be added for cryptic errors, the entire point of the issue was to allow the user to choose their distribution and version.

I tried to install `prismlauncher 7.2-3` on my system and faced a slightly more descriptive error:
```
warning: [options] bootstrap class path not set in conjunction with -source 7
error: Source option 7 is no longer supported. Use 8 or later.
error: Target option 7 is no longer supported. Use 8 or later.
make[2]: *** [libraries/launcher/CMakeFiles/NewLaunch.dir/build.make:96: libraries/launcher/CMakeFiles/NewLaunch.dir/java_compiled_NewLaunch] Error 2
make[1]: *** [CMakeFiles/Makefile2:1342: libraries/launcher/CMakeFiles/NewLaunch.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build: 
```

A quick search shows that `-source`, `-target`, and `-release` no longer support JDK 7. So while rolling back to 17, (and technically up to 19) is a valid solution it may be best to bump it from Java 7 entirely here:

https://github.com/PrismLauncher/PrismLauncher/blob/3719ea21b090dd58d897b7bd5c8db4e4c54f488c/libraries/launcher/CMakeLists.txt#L3

and here

https://github.com/PrismLauncher/PrismLauncher/blob/3719ea21b090dd58d897b7bd5c8db4e4c54f488c/libraries/launcher/CMakeLists.txt#L7

[I see that this was previously set to 8](https://github.com/PrismLauncher/PrismLauncher/commit/4fdb21b41400e789ca44a5cc1079469eb2508370), but can't tell why it was downgraded.

Locally, with a patch applied to `find_package` for Java 17 and with a `-target` and `-source` of 17 my launcher builds and installs. But `8` would work great too :)

**Comment by txtsd** [comment]
jdk21 is not currently supported due to some deprecations.

> It would be nice if that requirement would be documented

The PKGBUILDs require `java-environment=17` which means any jdk17, but they also need the jdk17 to be set as default using `archlinux-java set` which is more difficult to enforce. Check which ones are installed with `archlinux-java status`.

**Comment by txtsd** [comment]
@DeJayDev jdk7 is still required to get old minecraft to work.

**Comment by txtsd** [comment]
This has been implemented in all prismlauncher packages on the AUR. Don't forget to set `JAVA_HOME` when compiling/installing if your system's default java is not 17. See the pinned comment on the packages.

**Comment by getchoo** [comment]
this change has been reverted and the [pinned comments](https://aur.archlinux.org/packages/prismlauncher#comment-942325) have also been updated on the aur page with the reasoning. i also think in the future this issues would be better dealt with on the aur page rather than this upstream tracker
