### ISSUE TITLE
Game Crashes On World Load

### ISSUE THREAD

**Issue by Xtremeone23** [PrismLauncher/PrismLauncher#1754]
My log: https://mclo.gs/NhzpieE

I can't figure out why because the log doesn't explicitly state any mods causing problems. It blames Minecraft

**Comment by Trial97** [comment]
Thanks for respecting the template.
Also, this looks like a fabric mapping issue.
As this is not related to the launcher I will close this issue.
You can find more support on our discord in the support channels https://discord.com/channels/1031648380885147709/1118165588200657006
If you do not have the invite: https://discord.gg/ArX2nafFz2
