### ISSUE TITLE
Make the release for macOS a zip

### ISSUE THREAD

**Issue by alucardontop** [PrismLauncher/PrismLauncher#176]
### Role

Tar files are not often used to release mac apps

### Suggestion

PrismLauncher should use .zip files instead of tar, lzma2 is plenty compression. tar files are not commonly used to release mac apps and it may throw unsuspecting users off.

### Benefit

It's the right thing to do

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
zip removes permission stuff, so people would not be able to run the .app without manually chmodding the executable

**Comment by txtsd** [comment]
Yea, we had to resort to tar.gz because of the executable bit not being preserved on the executable file earlier last year.
