### ISSUE TITLE
Add Auto Java Installer to PrismMC

### ISSUE THREAD

**Issue by therabug** [PrismLauncher/PrismLauncher#1765]
### Role

I play modded Minecraft.

### Suggestion

I want to when I setup PrismMC it will need to install java automatically

### Benefit

My life will be easier

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TayouVR** [comment]
duplicate of #734
