### ISSUE TITLE
Missing Forge version

### ISSUE THREAD

**Issue by HalJordan** [PrismLauncher/PrismLauncher#1777]
### Version of Prism Launcher

7.2

### Version of Qt

6.6.0

### Description of bug

Trying to copy in the DW20 pack because their launcher is utter gobshite. The current latest release of the D20 1.20.1 pack uses 1.20.1-forge-47.1.76

Currently, Prism skips from 47.1.47 to 47.2.0

### Steps to reproduce

Create new instance, choose 1.20.1 for the MC version, forge for the loader, and look at the options.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
That is the neofroge version I belive, and we have that

**Comment by Trial97** [comment]
Yep checked that is the neoforge version. If you want to import it to prism I suggest you use the latest build: https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop

We have an FTB app import function too. 
I will close its issue as neoforge only works on 8.0.
