### ISSUE TITLE
Allow for resizing of columns in instance settings

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#1778]
### Role

I like to use PrismLauncher's instance settings to manage my mods, texture packs, shaders, etc.

### Suggestion

Make the organizing tabs at the top of the "Mods", "Resource Packs", "Shader Packs", and "Worlds" easier by allowing for columns to be resized

### Benefit

It would make the UI look a lot nicer on people who run Prism on strange window sizes.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This is what my "Mods" window looks like

![image](https://github.com/PrismLauncher/PrismLauncher/assets/96212687/bbfd1c84-a45e-4e15-92fa-9fbfda25bffe)

It would be nice if we had the ability to make the "Enabled" area smaller and just make the names field as long as my longest mod's name. This isn't the most pressing feature to be added but it would be cool to see implemented! 

Odd side note, you can resize the image field specifically for some reason, despite all images rendering the same regardless.

**Comment by ghost** [comment]
I just realized I never actually finished writing my suggestion. Edited the OP

**Comment by HyPeRXKo** [comment]
Hi, please consider this "enhancement" as a major bug, i am currently unable to properly see approximately 50% of my installed mod names due to theses change on the 8.0 release.

**Comment by cross** [comment]
Me too.  This was very confusing to me as I habitually move and resize columns.  The inability to do so clashes with the UI of most other applications.

**Comment by ghost** [comment]
> Hi, please consider this "enhancement" as a major bug, i am currently unable to properly see approximately 50% of my installed mod names due to theses change on the 8.0 release.

If you want a more temporary bandaid fix, cramming the image all the way back and disabling both "Last Modified" and "Provider" should work for most mods.

**Comment by Trial97** [comment]
fixed in: https://github.com/PrismLauncher/PrismLauncher/pull/1849
