### ISSUE TITLE
Garbage Files Generated After Successful Update and Subsequent Crash 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PrismLauncher/PrismLauncher#1779]
### Operating System

Windows 11

### Version of Prism Launcher

8.0 Development Build Commmit 69c2720872e4797278c46d5748ae1e10a876e572

### Version of Qt

Qt 6.6.0

### Description of bug

After crashing as seen here https://github.com/PrismLauncher/PrismLauncher/issues/659 the program also generates garbage files of the previous versions. In a perfect world it would simply disable the older versions or if set in options would delete the file entirely. Keeping garbled backups creates a lot of unnecessarily bloat.

example 
![prismlauncher_LMpex7YBy8 1](https://github.com/PrismLauncher/PrismLauncher/assets/10351221/fb091f51-3139-48ab-b0ed-3a02171710cb)

**Last Minute thoughts**
Its possible even if it does not crash that it might be generating automatic bloat ... I would need a version not crashing to test.

### Steps to reproduce

https://github.com/PrismLauncher/PrismLauncher/issues/659

### Suspected cause

https://github.com/PrismLauncher/PrismLauncher/issues/659

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Sorry for making you open an issue regarding this(it was late and looked serious).
Here is the explanation of why this is happening: when downloading files prism uses `QSaveFile` which creates a temporary file that is deleted on completion; now because of the crash that happens the temporary is no longer deleted.
