### ISSUE TITLE
minecraft just crashes. it doesnt launch. 

### ISSUE THREAD

**Issue by I-Happen-To-Exist** [PrismLauncher/PrismLauncher#1784]
### Operating System

mac

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.3.0

### Description of bug

i tried to launch and it just didnt. i dont know what caused it. here is the logs. 
(https://mclo.gs/UUCkR4M)

### Steps to reproduce

[mmc-pack.json](https://github.com/PrismLauncher/PrismLauncher/files/13250601/mmc-pack.json)
mods: 
appleskin
autoreglib
balm
bookshelf
clumps
controlling
cookingforblockheads
create
create crafts & additions
create Diesel Generators
Create ender transmission
create goggles
create jetpack
create liquid fuel
create utilities
create: bells & whistles
create garnished
create ruins
create steam 'n' rails
create structures
createarmoury
enchantment descriptions
farming for blockheads
geckolib
journeymap
just enough items
kotlinforforge
mouse tweaks
not enough crashes
not enough animations
projectE
quark
simple weapons
sophisticated backpacks
sophisticated core
tramplenomore
waystones

### Suspected cause

i have no idea

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
This isn't an issue with the launcher.

**Comment by Trial97** [comment]
> Prism Launcher 5.0

Also please upgrade your launcher before reporting any issue
