### ISSUE TITLE
README "Development builds" show forks and other branches

### ISSUE THREAD

**Issue by JL2210** [PrismLauncher/PrismLauncher#1787]
### Role

I want to install the latest development build.

### Suggestion

Have the README link only show builds from the develop branch when it is pushed to

### Benefit

so that people will only install builds from the main repository's development branch

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Link to do this: https://github.com/PrismLauncher/PrismLauncher/actions?query=branch%3Adevelop+event%3Apush

Edited for clarity

**Comment by Trial97** [comment]
Hi @JL2210,
You can already do that using the nightly build: https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop

**Comment by JL2210** [comment]
The README links to a page that has every build from every branch and fork of this repo on it. Maybe that should be the link instead?

**Comment by Trial97** [comment]
That page is all the PRs that were built(so yeah it will be from other users).
The readme points towards that page but there is no way to filter the builds by a specific branch so sorry as we need the other builds in order to see if the PR is working.
Also in the original issue description, you did not complain about the readme.

**Comment by JL2210** [comment]
Sorry about that, yeah. I realized it wasn't obvious what I was talking about.

The link I put in the issue *seems* to filter the commits to only those pushed to the local development branch.

As for checking if PRs build, the CI run is visible from the PR's github page, at least on the desktop site.

I think your README change is good for pointing anyone wanting a dev build to the right place.

Thanks!
