### ISSUE TITLE
1.7.10 minecraft grays out when holding an item in hand

### ISSUE THREAD

**Issue by Orbitalsky210** [PrismLauncher/PrismLauncher#1790]
### Operating System

Windows

### Version of Prism Launcher

7.2

### Version of Qt

6.5.1

### Description of bug

any 1.7.10 packs are grayed out when i hold an item. this is gt new horizons
![help](https://github.com/PrismLauncher/PrismLauncher/assets/149903622/cc6be439-f57c-45d1-836b-530098ff842b)

### Steps to reproduce

lanch 1.7.10 pack start world get item hold in hand

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Closing this as is not a launcher issue but a Minecraft one(or perhaps the java).
