### ISSUE TITLE
Wrong Shader Pack count, possibly other types too

### ISSUE THREAD

**Issue by Rafii2198** [PrismLauncher/PrismLauncher#1803]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

![image](https://github.com/PrismLauncher/PrismLauncher/assets/26695327/0b4448d3-42fe-4219-b4eb-8ae25213477f)
There are 2 elements listed, yet it says that 3 are installed.

### Steps to reproduce

* Install a shader pack
* Go to the game and change settings
* Now Shader packs should say that you have 2 installed 

### Suspected cause

I assume it is due to the fact that shader settings are saved in the same folder, and it just counts the number of files instead of amount of stuff that are displayed on the list.
If that's the case, then other stuff like mods and rps will also show that more are installed based on file count instead of what it detects. I know some mods, especially older ones, saved some stuff in mods folder like cache things etc. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Endrock6** [comment]
I've had the same issue and I'm pretty sure your assumption is correct.

**Comment by Trial97** [comment]
Related to #1807
Also, I belive that only shaders were affected by this
