### ISSUE TITLE
Add toggle for viewing Mod Images when editing instances.

### ISSUE THREAD

**Issue by PlayfulPiano** [PrismLauncher/PrismLauncher#1804]
### Role

Performance

### Suggestion

Add a toggle in settings to disable mod images from being shown in an instance's modlist.

### Benefit

To help improve performance when checking the modlist.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Would also recommend including this for 8.1 (or 8.0.1) since currently the image loading is very taxing on performance with the launcher itself.

**Comment by TheKodeToad** [comment]
You can right click on the text and disable it

**Comment by Trial97** [comment]
You can disable the columns by right click on the header and uncheck it

**Comment by PlayfulPiano** [comment]
Oh, I didn't realize that. I tried right clicking before and nothing came up.
Might then be worth having it either disabled by default or having those column toggles in settings separately as well.

**Comment by TayouVR** [comment]
there are some plans to cache them properly too, which should alleviate the performance issues (maybe)

**Comment by Linguardium** [comment]
turning off the image is a per-instance setting. having to uncheck this on every instance created is not good user experience. I would recommend a setting to configure the columns globally if that is the recommended way to manage it.

**Comment by Poopooracoocoo** [comment]
Yes please make the columns a global setting! It's annoying having to keep making the same changes when I create an instance.
