### ISSUE TITLE
release 8.0 is fucking cancer and there's no "previous versions" download link on your awful site

### ISSUE THREAD

**Issue by wmwdld** [PrismLauncher/PrismLauncher#1806]
### Role

shoo

### Suggestion

no

### Benefit

get bent

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

sk,dfjghnkljdfhjgk,jdfhgn.,jdfmng

**Comment by Aces-and-Jacks** [comment]
Well you seem a bit mad. Pretty sure the site is mainly focused on the main version. On the GitHub you can download any version you want

**Comment by Trial97** [comment]
This tracker is for launcher issues, not the website ones.
We support only the latest version of PrismLauncher, so there is no reason to get all the old versions on the website.
And as previously mentioned you can go to GitHub releases to download any older version.
