### ISSUE TITLE
shaders not being found by launcher

### ISSUE THREAD

**Issue by Endrock6** [PrismLauncher/PrismLauncher#1807]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

I just updated to Prism 8 and started editing my main instance. I wanted to install BSL and complementary but after I selected them and they were successfully installed they didn't show up in the shader list. I went to check the folder and the shader files are definitely present but are just not being registered by the launcher.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/101973300/b6bf9432-6e23-44a7-88c7-7af344a2def2)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/101973300/49374b6d-3c46-455f-997c-44477ae1bf4b)

### Steps to reproduce

- Open the edit menu of any instance that supports shaders
- Install any shader you like (preferably from modrinth because I got mine from them)
- see the shader being installed in your shaderpacks folder but not registered by the launcher

### Suspected cause

I'm not sure what could be causing it except that Prism isn't properly checking the shaderpacks folder for shaders

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by JJMK925** [comment]
I have the same issue, only in 1.20.2
But it just seems to be visual, when i launch the game, the shaders still show up in Iris

**Comment by Trial97** [comment]
> But it just seems to be visual, when i launch the game, the shaders still show up in Iris

Yeah it is only a visual bug

**Comment by Endrock6** [comment]
When will this get fixed? because it persists in version 8.2.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/101973300/e686fec2-a736-4151-92b5-c0b1deac1ca0)

**Comment by willydee** [comment]
Problem still persists in release 8.3. All shader packs are detected and work in-game. but are not listed in the Prism Launcher Console window. The number of shader packs displayed in the panel header is correct though.

**Comment by pumkinhead456** [comment]
Problem still persists even on 8.3

![image_2024-06-15_223739403](https://github.com/PrismLauncher/PrismLauncher/assets/110414198/a5e78d7b-efd8-47c1-9650-cb424ac2ea46)

**Comment by Trial97** [comment]
And will be fixed in 9.0
