### ISSUE TITLE
Start maximised option not working

### ISSUE THREAD

**Issue by j-terp** [PrismLauncher/PrismLauncher#181]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

Ticking the option "Start Minecraft maximised?" will not result in it starting large, both global and instance specific.

### Steps to reproduce

1. Tick the "Start Minecraft maximised?" option on.
2. Launch an instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Rafii2198** [comment]
I initially reported it for Linux system at PolyMC repository. Scrumplex commented that it is working for him on his end, and it is pretty much all of that issue, it never went further. For me, behavior is a bit worse with Prism on either Windows and Linux as on that issue only Maximized didn't work, now even custom window size is not working too.

**Comment by j-terp** [comment]
> now even custom window size is not working too.

Custom launch resultion works for me, however, when the maximised option is ticked it will go to default resolution.

Am using a dual monitor setup on WIn11 if that helps.

**Comment by Rafii2198** [comment]
> when the maximised option is ticked it will go to default resolution.

That's really good information, I didn't expect it to work like that, so I didn't check for that behavior, and now I can confirm this is exactly how it works for me too on Windows 10 and Linux (same pc) and also on Win 11 on my laptop

**Comment by jschenke488** [comment]
Can confirm on Arch Linux with KDE Plasma and Windows 11

**Comment by jschenke488** [comment]
What I did as a temporary "fix" is install the borderless mining mod and enable fullscreen

**Comment by IdrisQe** [comment]
I've had this issue as far back as the original MultiMC. The "start maximized" button has *never* worked for some reason. During the wait for PrismLauncher from PolyMC I temporarily used ATLauncher and even that's "start maximized" button didn't work so I suspect it's not actually an issue with the launchers but with Windows 10, somehow.

**Comment by Rafii2198** [comment]
Not only Windows 10 but all operating systems it seems. Altho Scrumplex said it works for him, but maybe he only checked the resolution part, I dunno. We need input from people to find if it is working for somebody else.

**Comment by r58Playz** [comment]
Start Minecraft maximized just removes the width and height flags so it's up to the WM/Minecraft what the window size is.

**Comment by TheKodeToad** [comment]
> Start Minecraft maximized just removes the width and height flags so it's up to the WM/Minecraft what the window size is.

It shouldn't do, because I *think* that just causes Minecraft to use the default.

Edit: Ah, yep, that is what it does. That's what causing this, then. The funny thing is, the feature only works on very old versions where an applet is used.

https://github.com/PrismLauncher/PrismLauncher/blob/develop/libraries/launcher/org/prismlauncher/impl/OneSixLauncher.java#L162

I'm not even sure if there's any way to do it easily for newer versions. I don't know how you could get GLFW to use the MAXIMIZED hint. LWJGL 2 has quite a few system properties, so it may be possible for 1.12 and below.

Peterix has also commented on this 
https://github.com/MultiMC/Launcher/issues/2770#issuecomment-515713767

**Comment by ghost** [comment]
This issue only happens for Minecraft versions newer than 1.5.2 and there is nothing Prism Launcher could do to fix it according to https://github.com/MultiMC/Launcher/issues/2770#issuecomment-515713767.

For Minecraft 1.5.2 and below it should work as intended.

## Workaround For Minecraft versions newer than 1.5.2

1. Launch Minecraft
2. Join a server/world
3. Maximize the window
4. Open the debug menu (press f3)
6. Copy the display resolution (top right corner)
![image](https://user-images.githubusercontent.com/110736028/198633167-a13b17c5-f9a6-48e9-92c2-308515adcbcd.png)
8. Close Minecraft
9. Go back to the launcher and set the window height and width to what you got in step 5
![image](https://user-images.githubusercontent.com/110736028/198634027-73f09702-b6e8-4050-8798-529e13fcc6f9.png)
11. Launch Minecraft

### Video tutorial:

https://user-images.githubusercontent.com/110736028/198634692-0ab2cfb6-07a7-4917-b3b6-55b565d769bb.mp4

**Comment by IdrisQe** [comment]
It feels so bizzare that this isn't doable. Especially that it _was_ doable but now isn't.
Out of idle curiosity, what changed between 1.5.2 and 1.6.1 exactly which caused it to no longer work?

**Comment by TheKodeToad** [comment]
> It feels so bizzare that this isn't doable. Especially that it _was_ doable but now isn't. Out of idle curiosity, what changed between 1.5.2 and 1.6.1 exactly which caused it to no longer work?

The reason is that 1.5.x and below had support for Java applets, which allowed customisation of this.

However, this could theoretically be fixed using windowing system APIs maybe?

Edit: [678435021](https://github.com/678435021)'s solution does actually get the window manager to recognise its maximised state. Maybe just some hack to work out these values then.

**Comment by luni3359** [comment]
On my end when trying to run minecraft with gamescope (i.e. putting `gamescope -H 1080 -h 720 -f` under Wrapper command on settings), even if start maximized is ticked , the window always shows up in full screen but in 854x480 resolution.

**Comment by ghost** [comment]
> On my end when trying to run minecraft with gamescope (i.e. putting gamescope -H 1080 -h 720 -f under Wrapper command on settings), even if start maximized is ticked , the window always shows up in full screen but in 854x480 resolution.

Go to Minecraft Options > Video Settings > Other and set full screen mode as `Default` or the highest possible setting.
![image](https://user-images.githubusercontent.com/110736028/211149325-c6a925d7-d9c2-4635-8d3a-a4beef7bde94.png)
![image](https://user-images.githubusercontent.com/110736028/211149387-094142b4-1fe2-41e5-a121-4a94118d3cbe.png)

**Comment by TheKodeToad** [comment]
This will be highly painful! :sparkles:
https://stackoverflow.com/a/4088322

I'm guessing x11's floppy-ness would allow using this and then automatically maximising.

Also, i'm unsure whether it's possible on Wayland (probably not)

**Comment by ghost** [comment]
> ## Workaround For Minecraft versions newer than 1.5.2
> 1. Launch Minecraft
> 2. Join a server/world
> 3. Maximize the window
> 4. Open the debug menu (press f3)
> 5. Copy the display resolution (top right corner)
>    ![image](https://user-images.githubusercontent.com/110736028/198633167-a13b17c5-f9a6-48e9-92c2-308515adcbcd.png)
> 6. Close Minecraft
> 7. Go back to the launcher and set the window height and width to what you got in step 5
>    ![image](https://user-images.githubusercontent.com/110736028/198634027-73f09702-b6e8-4050-8798-529e13fcc6f9.png)
> 8. Launch Minecraft

Worth noting that you might have to adjust the value on HiDPI screens. For example on macOS retina displays with the default resolution setting of 1440x900, you should divide by 2 to get the correct window size values.

**Comment by IdrisQe** [comment]
I mean, I know you can do that, but that doesn't actually maximize the window, and there is a distinction.

**Comment by ghost** [comment]
Yeah, it would be nice to have this properly fixed, I was just adding a note to the previously posted workaround.
