### ISSUE TITLE
Play Demo mode crashes with an account that doesn't own Minecraft

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#1810]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

When launching Demo mode with an account that doesn't have Minecraft, Prism Launcher crashes. However if you do the same with a normal account it does not.

### Steps to reproduce

1. Use a Microsoft account that doesn't have Minecraft
2. Try loading Minecraft
3. Crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment]
Since no one made this issue yet I figured I'd put one out there. Even though it's been mentioned on discord

**Comment by Aces-and-Jacks** [comment]
if prism launcher crashed the first time I logged into demo with a fresh microsoft account but worked the second time should I make an issue about that with the launcher logs or leave it be, since it worked? It was in 9.0 

asked in discord, figured I'd ask here

**Comment by petwarrior405-arch** [comment]
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/f3c0a14f-9575-4bb2-ad54-f4d4a7e73145" />
