### ISSUE TITLE
Add description for `Online fixes`

### ISSUE THREAD

**Issue by Desoroxxx** [PrismLauncher/PrismLauncher#1817]
### Role

Playing Minecraft

### Suggestion

Tell me what are the `Online fixes`

### Benefit

Know what the `Online fixes` do so I can judge if I need them

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Setting is found under: `Settings > Minecraft > Tweaks`

![image](https://github.com/PrismLauncher/PrismLauncher/assets/82710983/79ce57da-a79f-48f5-b8b7-91ba8e7cd895)

**Comment by TheKodeToad** [comment]
It's already present in the tooltip. Maybe options should have subtitles?

**Comment by Desoroxxx** [comment]
> It's already present in the tooltip. Maybe options should have subtitles?

Mhh, I don't know if this is a Windows thing but the tooltips seems janky in menus they slide down weirdly and kinda in a jagged way, I don't know how to explain, they also take a long time to appear, thanks though.

**Comment by Desoroxxx** [comment]
> It's already present in the tooltip. Maybe options should have subtitles?

Mhh, I don't know if this is a Windows thing but the tooltips seems janky in menus they slide down weirdly and kinda in a jagged way, I don't know how to explain, they also take a long time to appear
