### ISSUE TITLE
Dependency checking for updates is completely broken

### ISSUE THREAD

**Issue by Desoroxxx** [PrismLauncher/PrismLauncher#1818]
### Operating System

Windows

### Version of Prism Launcher

8.0

### Version of Qt

6.6.0

### Description of bug

Dependency checking for updates is completely broken and makes up that some dependencies are missing.

### Steps to reproduce

Press the check update buttons with mods with dependencies, I am not sure what causes this to happen.

Enabling the `Do no install mod dependencies` option fixes this completely

### Suspected cause

It might be related with the fact that some dependencies are on multiple platforms at once (Modrinth <> CurseForge) and sometime a mod is on one platform and the dependencies are on the other, could investigate more later if needed.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by inikishev** [comment]
I think the underlying issue is that prism launcher very often sees the same mod uploaded on curseforge and modrinth as two different mods, maybe because they have slightly different titles, e.g. one has "[fabric]" in the title.

**Comment by inikishev** [comment]
also how do you enable Do no install mod dependencies

**Comment by Desoroxxx** [comment]
> also how do you enable Do no install mod dependencies

![image](https://github.com/PrismLauncher/PrismLauncher/assets/82710983/2c5e0ae4-0fb3-41e7-80d0-0dc4c2dddfe7)
It will have a slightly different name for you don't worry I am on a dev build

**Comment by Traehgniw** [comment]
I've noticed that this is happening to me while I have the dependency downloaded from Modrinth, but the thing that relies on it is only on Curseforge - so it seems it then only checks the Curseforge version? Also sometimes the Required By field is blank but that might just be a "some of these mods have weird included metadata" kind of deal

**Comment by tehbeard** [comment]
I'm encountering the same issue as described by @Traehgniw 

As a concrete example for testing purposes, I have:

**Curseforge:**
- Map Atlases [Forge] (requires Moonlight Lib)

**Modrinth:**
- Moonlight Lib
- Supplementaries (requires Moonlight Lib)

![image](https://github.com/PrismLauncher/PrismLauncher/assets/734177/c1fa3c24-6e95-4191-bddd-747ea2d5e02e)

Given both providers return the same file with the same name, updating just flips which provider says the "mod isn't installed."
