### ISSUE TITLE
Add better options/functions for CatPack customization

### ISSUE THREAD

**Issue by SympathyTea** [PrismLauncher/PrismLauncher#1820]
### Role

I (intend) to make catpacks in the future

### Suggestion

I want to have 2 new functions added to catpacks that will make producing catpacks easier and more optimized

### Benefit

Less bulky catpacks, saves time for the catpack creator

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

With the current system for catpacks, you have to specify a day and month for each image. Currently this system works for a small scale catpack with 1 image and a few holiday variants, but might become problematic once you try to make a catpack with multiple images that you want to change every day.

The only method at the moment is to specify every day you want that particular image to show, and if you have 4 images in a catpack that you want to have as a sort of slideshow, then you have to do this for every single image, in order.

I have a small suggestion on how this can be improved with 2 new options/functions

1.  "Random", Catpack has a folder in it called either random or just "default_image" and the json file has the ability to select a random image from that file, either every relaunch of prism or every day (gonna leave that up to you)

2. "Slideshow" Catpack has a folder called slideshow, where the images are numbered (like 1.png, 2.png etc) and the file goes through the set of images in order. When it reaches the end, it starts over.

Unsure how possible this is, but it would save me and others alot of time when we are creating catpacks, and should also reduce the json file's size since we don't have to have the same lines repeated over and over again.

I'm not asking you to completely remove the current system, since its good for holiday specific images but I think it should be kept just for specifying holiday images and small scale catpacks with one default image.

**Comment by Scrumplex** [comment]
We would need to store the previous number for the slideshow option. There would be some further questions for that one, like what should happen to that number once the user switches to a different cat pack. Alternatively, we could just fix it to the current day of the year. That would mean that there can be at most 365/366 cats per pack (unless random is used) and if there are less, we can just let it loop.

Selecting the cat in sequence would be:

```cpp
int numberOfCats = 30; // let's say we have a cat pack with 30 sequenced cats

int sequenceNum = QDate::currentDate().dayOfYear() % numberOfCats
```

Today is day 313 of the year, so it would pick the 13th cat (assuming we start counting from 0)

**Comment by SympathyTea** [comment]
i don't have much to comment on this one since i don't understand a lick of how json works and therefore cant give input
lgtm

**Comment by sakecode** [comment]
I do hope if this is added it dates override random/slideshows for doing holidays
