### ISSUE TITLE
Game does not respect custom resolution settings

### ISSUE THREAD

**Issue by FooterManDev** [PrismLauncher/PrismLauncher#1833]
### Operating System

Linux

### Version of Prism Launcher

8.0

### Version of Qt

5.15.10

### Description of bug

When making an Instance window start maximized, or change the resolution, the game will never change, it will always stay at the default resolution.

### Steps to reproduce

Make an Instance
Set to Maximize on start or set a custom resolution (1920x1080 in my case)
Load game

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FooterManDev** [comment]
Video of bug:

https://github.com/PrismLauncher/PrismLauncher/assets/71946346/616fcf48-f9e8-476e-b185-6a2bad3b5d40

**Comment by Trial97** [comment]
The Minecraft maximized option doesn't work( see #181 and #292)
The resolution should still work. Can you try to uncheck the maximized option and try only with a custom width and height?

**Comment by FooterManDev** [comment]
I have tried. Same outcome.

**Comment by Trial97** [comment]
make sure you did not override the settings in the instance

**Comment by FooterManDev** [comment]
Tried it with override and in the Prism settings. Same thing.

**Comment by Trial97** [comment]
Ok then I will change the name of the issue to make it more easier to track

**Comment by Trial97** [comment]
Can you upload a similar video as the one with maximized, but this time with that setting unchecked?
Also on what version of Minecraft does that happen?

**Comment by FooterManDev** [comment]
Aha, I **didn't** change the resolution in Prism settings like I thought I did, changing it to 1920x1080 works fine. I only messed with the Maximize checkbox before.
However, it still doesn't make sense for the override and the maximize checkbox to not do anything.

**Comment by Trial97** [comment]
For maximize look into the other two issues I linked.
And I will close this  as duplicate then if the resolution thing works,



> The Minecraft maximized option doesn't work( see #181 and #292)
