### ISSUE TITLE
Game crashing upon launch

### ISSUE THREAD

**Issue by 4A8** [PrismLauncher/PrismLauncher#1836]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

My game crashes when launching, does not show the game at all but instead just the crash log.

### Steps to reproduce

- open prism launcher
- select any version
- launch
- cry because it doesn't actually launch and shows this crash log instead: https://mclo.gs/YdIEoVI

### Suspected cause

extremely bad pc

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Most probably because of missing/outdated graphics drivers.
 As this is not a launcher issue I will close this, but please feel free to join the discord: https://discord.gg/ArX2nafFz2 as there should be more people that can help with your issue.
