### ISSUE TITLE
Make mod downloading/updating consider already installed mods, to avoid duplicates

### ISSUE THREAD

**Issue by Desempregago** [PrismLauncher/PrismLauncher#1839]
### Role

Modded Minecraft

### Suggestion

Make the download function to search installed mods first before suggesting possible "dependencies" that it deems not installed, even though they're present in the mod list

### Benefit

Because updating/installing mods right now can easily lead to duplicate mod ids if there are forks present.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
I do believe that you did not search this tracker enough before creating this issue.
So closing this as a duplicate of #1745
