### ISSUE TITLE
updating assest index OVER AND OVER

### ISSUE THREAD

**Issue by AsheX1** [PrismLauncher/PrismLauncher#1855]
### Version of Prism Launcher

prism 8.0 just switch all my stuff over from multimc and every time i want to luanch a client updating assest index

play offline and this crap does not happen
play online updating assest index.... and i dont care that it does it the problem is it takes 2 freaking min

why does it needs to keep updating the the assest index there is no reason for this the client is not gone update to any other version of minecraft so its just plain pointless

### Version of Qt

/

### Description of bug

/

### Steps to reproduce

/

### Suspected cause

all i have done is move all my instance from multimc to prismmc 
yes only the instance folders nothing els

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Does the update asset happen more than once per instance? Like it happen each time you launch that instance?

**Comment by AsheX1** [comment]
> Does the update asset happen more than once per instance? Like it happen each time you launch that instance?

keeps doing for all all instance
its not downloasding anything as far as i see its just keep checking/updating the assest index nothing els is getting downloaded

**Comment by AsheX1** [comment]
> Does the update asset happen more than once per instance? Like it happen each time you launch that instance?

keeps doing for all all instance
its not downloasding anything as far as i see its just keep checking/updating the assest index nothing els is getting download

**Comment by Trial97** [comment]
Can you please provide some logs?
Also please note that is normal that first time(only the first time) when you start an instance with a Minecraft version that you never played to popup that in order to download the game. 
If you start an instance that you already played the prism only checks if the cached assets are there(this usually is much more faster almost instant).

**Comment by AsheX1** [comment]
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/13368441/PrismLauncher-0.log)

idk what is going on but even the minecraft login server seems to be pooping them self...

**Comment by AsheX1** [comment]
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/13368486/PrismLauncher-0.log)
and here is an other one where it does it again....

**Comment by AsheX1** [comment]
and here it does it again
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/13368754/PrismLauncher-0.log)
feel like just swithing everything back to multimc.....

**Comment by AsheX1** [comment]
also really fucking love the the freaking microsoft account bs first time try using the zip install get the above crap + ms account loging failing over and over also until it works so now i just installed prismmc and its even worse how is that even able to happen now cant log my account at all on it.......

**Comment by Trial97** [comment]
I'm still not able to figure this out this is happening for you.
Can you try to see if you reproduce it with a portable version, but without migrating anything from multimc?

**Comment by SkyLLerGithub** [comment]
Sorry for necro, but I'm getting this issue too.
Microsoft Login server also takes years, and it keeps updating index and it also takes a very long time.
My internet speed is around 80mbps, and requesting downloads takes longer time than it's supposed to be.
It takes like 3 minutes to fetch news.
Did not migrate from MultiMC, been using Prism since and one day it just had this issue.
Using Arch Linux, with official repo package.

**Comment by SkyLLerGithub** [comment]
Issue doesn't seem to be happening on Portable Qt5

**Comment by AsheX1** [comment]
i was able to fix it at some point but cant remember how or what it was

**Comment by AsheX1** [comment]
i do know it has something to do on the OS side and not prism or multimc

**Comment by SkyLLerGithub** [comment]
> i do know it has something to do on the OS side and not prism or multimc

do u also happen to use some sort of DNS service like cloudflare? I've tried the AUR version of prism it also happens on there. Not to mention portable 9.0 doesnt seem to be packaged properly, ill open another issue for that however.

**Comment by AsheX1** [comment]
> > i do know it has something to do on the OS side and not prism or multimc
> 
> do u also happen to use some sort of DNS service like cloudflare? I've tried the AUR version of prism it also happens on there. Not to mention portable 9.0 doesnt seem to be packaged properly, ill open another issue for that however.

i wish i can help but i cant remember what i have done to fix or what it even was

**Comment by mahmudaliev** [comment]
I am having the same problem guys

<img width="580" height="365" alt="Image" src="https://github.com/user-attachments/assets/b93b22cb-a64d-4448-9da8-2d04b7d2169b" />

can someone help me plz

**Comment by eleanordoesntcode** [comment]
@mahmudaliev Mojang's servers are down, so the index cannot be updated rn

**Comment by Greyneon** [comment]
I'm having issues with every 2-7 days it download a bunch with "updating assets index" 

Which also EVERY SINGLE TIME reset every single keybind and unloads any resourcepacks.

Well, not all keybinds, there is ONE keybind that always survive. That I changed inventory to be on TAB. any other keybind is reset, and it ALWAYS happens with "updating assets" 

For a 1.20.1 modpack that's not even updated. And this happens every 2-7 days.

**Comment by LimeShep** [comment]
I suggest adding an option so it doesn't try to update the index if not possible (i.e. if mojang servers are down) and instead, launches the game as normal.
