### ISSUE TITLE
Add modpack import filter for all supported file types

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#1865]
### Role

I play on a private modrinth pack.

### Suggestion

I want to not have to manually specify I'm importing a modrinth pack to be able to import them.

### Benefit

So that I can have a better user experience.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

By default it is a little confusing as despite there is a valid modpack in the folder selected it won't show up by default: 
![image](https://github.com/PrismLauncher/PrismLauncher/assets/5214513/d8d53da1-8a85-4729-a264-8b12fdea08f5)
Until the Modrinth pack option is selected:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/5214513/497b267b-82da-42f9-ac75-d0264de9f8fb)
I suggest that both pack types should show up by default and the user have the ability to further discriminate between modpack types if needed.

**Comment by ghost** [comment]
I'm not at all knowledgeable with Qt or C family of languages in any form but I think you might be able to start off the filters with `tr("Supported files") + " (*.zip *.mrpack)"` before the zip and the mrpack filters.

Not quite sure if y'all should go with `Supported files` or rather just `Modpack files` but I hope this helps a little.

Oh and I believe this is the method that needs editing, I'm not sure about translations however:
https://github.com/PrismLauncher/PrismLauncher/blob/40cfa145ee1231aa82e1bbc71604f4ee005d5fd3/launcher/ui/pages/modplatform/ImportPage.cpp#L201-L214

**Comment by TheKodeToad** [comment]
I think that would actually work! Feel free to try it and open a PR - even if you're not familiar with C++ you have the right idea.

https://doc.qt.io/qt-6/qfiledialog.html#getOpenFileName

You would want the string to look like `"Supported files (*.zip *.mrpack);;Zip archive (*.zip);;Modrinth pack (*.mrpack)"`.

The `QMimeDatabase().mimeTypeForName("application/zip").filterString()` bit just provides `Zip archive (*.zip)` for your language I believe.
`tr("string")` basically does all of the translation work for you :P

**Comment by quinn-semele** [comment]
I have to say, I am saddened that even after 5 months and a release this still has not been implemented and instead deferred for 9.0
