### ISSUE TITLE
Prism Launcher doesn't launch minecraft anymore

### ISSUE THREAD

**Issue by SprainedSpark89** [PrismLauncher/PrismLauncher#1874]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

This program uses Qt version 5.15.2.

### Description of bug

When i launch any version of minecraft it fails to launch (it used to be only modded minecraft where i had this issue)

### Steps to reproduce

- launch a version (on pi os legacy)

### Suspected cause
[1.6.log](https://github.com/PrismLauncher/PrismLauncher/files/13405045/1.6.log)
[1.20.1.log](https://github.com/PrismLauncher/PrismLauncher/files/13405046/1.20.1.log)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
It would be better to upload logs as attachments

**Comment by SprainedSpark89** [comment]
> It would be better to upload logs as attachments

ok

**Comment by Trial97** [comment]
From the 1.20.1 log, this looks exactly like: #1693, so can you try one of the mentioned solution from here: https://github.com/PrismLauncher/PrismLauncher/issues/1693#issuecomment-1806781768

**Comment by SprainedSpark89** [comment]
> delete the following folders from prism root directory: assets, cache, libraries, meta ; then restart prism and try again(all the mentioned folders should regenerate when you start a instance, but if you want to be sure just make a backup for your prism root folder)


that worked for me thx
