### ISSUE TITLE
XBox user authentication failed: Connection closed

### ISSUE THREAD

**Issue by Rosentti** [PrismLauncher/PrismLauncher#1875]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0-develop (e499aa4783ea1e24d11be83597733a314f5c49a5)

### Version of Qt

Qt 6.6.0

### Description of bug

Can't login with XBox.
Logs:
```
  36.292 D | DeviceFlow::onVerificationReceived: Emitting closeBrowser()
  36.292 D | DeviceFlow::onVerificationReceived: Access token returned for implicit or device flow
  36.292 D | DeviceFlow::onVerificationReceived: Token expires in 3600 seconds
  36.292 D | [katabasis.credentials]: new refresh token: "CENSORED"
  36.292 D | DeviceFlow::setLinked: true
  36.292 D | AuthFlow: "Logging in as an Xbox user."
  36.292 D | First layer of XBox auth ... commencing.
  36.739 W | AuthRequest::onRequestError: Error 2
  36.739 W | AuthRequest::onRequestError: Error string:  "Connection closed"
  36.739 W | AuthRequest::onRequestError: HTTP status 0 ""
  36.739 W | Reply error: QNetworkReply::RemoteHostClosedError
```

### Steps to reproduce

1. Go to account manager
2. Login via Microsoft
3. Error appears once Prism Launcher has been authorized.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Make sure you do not have any firewall rules that would block PrismLauncher.
Try using the portable version if that works go do a reinstall of prism but make sure you delete all the files from the previous version(https://github.com/PrismLauncher/PrismLauncher/issues/1031#issuecomment-1580782178). And I mean the ones found in the installation directory, not the data directory ones.

**Comment by Rosentti** [comment]
It actually turned out to be my school's network blocking it. I just didn't realize, as the message I usually get is something along the lines of "Connection reset".
