### ISSUE TITLE
GLFW Wayland: The platform does not provide the window position

### ISSUE THREAD

**Issue by Aurnytoraink** [PrismLauncher/PrismLauncher#1876]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0 (Flatpak)

### Version of Qt

Qt 5.15.10

### Description of bug

The game instantly crashes. I tested with different versions of Minecraft, with or without fabric or forge. It seems to work only the vanilla version 1.20.2

[Prism Launcher version.txt](https://github.com/PrismLauncher/PrismLauncher/files/13415455/Prism.Launcher.version.txt)

I'm getting another issue on 1.18.1, which I think both bug are related

[Prism LauncherEGL.txt](https://github.com/PrismLauncher/PrismLauncher/files/13415497/Prism.LauncherEGL.txt)

### Steps to reproduce

1) Launch the game
2) It crashes

### Suspected cause

I suspect the game is due to the new version of GNOME 45 and Wayland. I also suspect my Nvidia card, because I know that Linux and Nvidia doesn't match that well.

Maybe it's related to something in the Flatpak Manifest

Or it can be caused by Fabric and Forge

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Looks like you enabled the native glfw override. It should work if you disable it for the time being.

**Comment by Aurnytoraink** [comment]
That's right, after disabling it, it works !

I don't know if I should keep the issue opened because the issue with GLFW is still there

**Comment by Scrumplex** [comment]
You might need a patched version of GLFW to run it on Wayland. See projects like https://github.com/Admicos/minecraft-wayland

**Comment by Hund** [comment]
> You might need a patched version of GLFW to run it on Wayland. See projects like https://github.com/Admicos/minecraft-wayland

Is this still the way to go in 2026 or what?

**Comment by nophoria** [comment]
For reference, that [repo](https://github.com/Admicos/minecraft-wayland) mentioned above was archived in april
