### ISSUE TITLE
Display target Minecraft version of Fabric version

### ISSUE THREAD

**Issue by Braekpo1nt** [PrismLauncher/PrismLauncher#1877]
### Role

I write mods and plugins, and often need to test different versions of Minecraft (and thus different versions of Fabric/Forge)

### Suggestion

When creating a new instance and selecting a mod loader, I'd like a column in the mod loader version selector to display the target Minecraft version(s), so I know which one is best to select

### Benefit

I will know which version to select without having to go to the mod loader's website and checking which version targets which Minecraft version

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Desired workflow:
- Create Instance
- Select Minecraft version (not latest)
- Select Fabric as mod loader
- I'd like to see the target Minecraft version in a column next to the version of Fabric I'm presented with. I am not sure if the starred version is the latest Fabric version, or the last Fabric version for the version of Minecraft I've selected. This feature will not only make it explicit, it will also help with selecting previous Fabric versions to help replicate issues in my mods and plugins when testing and fixing.

**Comment by TheKodeToad** [comment]
Each Fabric version is not tied to any game version.

**Comment by TheKodeToad** [comment]
As for Forge, the target version is the version you're using - it's filtered.
I don't think this is necessary but lmk if you want it reopened.

**Comment by Braekpo1nt** [comment]
@TheKodeToad Understood, that's my mistake for misunderstanding how fabric versions worked. Feel free to close this as complete. You're correct that forge is filtered based on your selected version.
