### ISSUE TITLE
Modrinth  Texture pack downloader

### ISSUE THREAD

**Issue by elchupe123** [PrismLauncher/PrismLauncher#188]
### Role

I play minecraft in general

### Suggestion

I want a texture pack downloader inside the luncher like the mod downloader, we can use modritnh texturepack library 

### Benefit

This would make easier to download texturepack 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flowln** [comment]
Duplicate of  #153
