### ISSUE TITLE
Renaming instances with Borest or Fluent theme has broken visuals

### ISSUE THREAD

**Issue by FantabulousPhoton** [PrismLauncher/PrismLauncher#1881]
### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

When renaming an instance with the Borest or Fluent theme, the old name displays as well as the new name you are currently typing.
In the files below, the old name was "Old Name" and I was typing in "New Name."
![bug-borest](https://github.com/PrismLauncher/PrismLauncher/assets/117485734/98755265-6b48-4eab-8baa-6936f3c1d97a)
![bug-fluent](https://github.com/PrismLauncher/PrismLauncher/assets/117485734/735a33b2-a067-415d-9057-a518a72dabae)

### Steps to reproduce

- Right-click an instance and click Rename.
- Type in something.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
https://github.com/PrismLauncher/Themes/issues/25
