### ISSUE TITLE
- suggestions for the launcher -

### ISSUE THREAD

**Issue by sxtw** [PrismLauncher/PrismLauncher#1883]
**1.** Add the Discord RPC (if possible and there will be no bugs), as well as the ability to enable/disable the Discord RPC in the launcher settings.

**2.** New sorting: the ability to move the instances in a group among themselves.

> _For example:_ I have a group "Alpha", the group has instances "1.19.4", "1.20.1", "1.16.5", and I want to be able to drag them between each other, like to put version 1.16.5 first, 1.20.1 second and 1.19.4 last, and so that after launching any of the instances, their order does not change. I hope you understand what I mean :)

_(and I also want to be able to move groups up and down in the same way)_

**I hope that you will notice this and add these two functions (or at least the second one). Thanks**

**Comment by TheKodeToad** [comment]
you <3 your own suggestion >:(

**Comment by Trial97** [comment]
for discord :https://github.com/PrismLauncher/PrismLauncher/issues/232 
for the instance sort: https://github.com/PrismLauncher/PrismLauncher/issues/688
Closing as duplicate

**Comment by swiftyhikka** [comment]
💀

**Comment by sxtw** [comment]
if they wrote about sorting a year ago, then why is it still not in the launcher?

**Comment by Trial97** [comment]
> if they wrote about sorting a year ago, then why is it still not in the launcher?

If you want it to be implemented and do not want to wait for somebody else to pick it up feel free to implement it yourself, we are welcoming new contributions.

**Comment by sxtw** [comment]
> > if they wrote about sorting a year ago, then why is it still not in the launcher?
> 
> If you want it to be implemented and do not want to wait for somebody else to pick it up feel free to implement it yourself, we are welcoming new contributions.

I would have done it myself, but I don't know how to code 🥱
