### ISSUE TITLE
Minecraft news and updates

### ISSUE THREAD

**Issue by FantabulousPhoton** [PrismLauncher/PrismLauncher#1885]
### Role

I play Minecraft.

### Suggestion

I want to see the latest Minecraft news.

### Benefit

so I don't need to look in the normal launcher or online.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Next to the Prism Launcher news, there could be Minecraft news.

**Comment by TheKodeToad** [comment]
#194
