### ISSUE TITLE
Can Migrate?, Type, and Status columns in the settings > accounts page don't resize properly

### ISSUE THREAD

**Issue by KyngK** [PrismLauncher/PrismLauncher#189]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.3.0

### Description of bug

In the Account Page (Settings > Accounts) the Username and Account columns resize depending on the window, but the text for the other three columns are cut off and don't resize (Can Migrate?, Type, and Status). Attached video explains it better.

Also worth noting that this could be happening in other pages that use a similar view however I wasn't able to find any others.

https://user-images.githubusercontent.com/88447671/197084010-46866359-0b35-4656-a269-67617173c5f6.mp4

### Steps to reproduce

Go to the settings page, click the accounts tab, and try resizing the window

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Can you still reproduce it with the latest ~build~release?

**Comment by KyngK** [comment]
From what I can tell it seems to be better now!
