### ISSUE TITLE
Popup icons are wonky for the fluent icon pack

### ISSUE THREAD

**Issue by RealmKebab** [PrismLauncher/PrismLauncher#1891]
### Operating System

Windows 11 Home

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

the popup icons are displaced
![image](https://github.com/PrismLauncher/PrismLauncher/assets/73048123/124fa72f-0465-4de5-afca-74ed8d670f6c)

### Steps to reproduce

1. install the fluent icon pack
2. bring up a popup (e.g. the upload logs button)
3. take a look at the icons

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
https://github.com/PrismLauncher/Themes/issues/64

**Comment by RealmKebab** [comment]
but that's about the text

**Comment by RealmKebab** [comment]
ok i guess

**Comment by Trial97** [comment]
Look at the icons in that issue, same cut-off you mentioned. Just extend that one.
