### ISSUE TITLE
Crash when searching by author in Curseforge tab by Copy Paste Then Manually Searching for Another Author (Finicky bug)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PrismLauncher/PrismLauncher#1899]
### Version of Prism Launcher

8.0 Stable

### Version of Qt

6.6.0

### Description of bug

When searching for an author by copy pasting a username and then afterword manually typing a user name and click on a mod it crashes. 

### Steps to reproduce

Originally it was copy and paste a author username and then manually write in a different author.

### Suspected cause

Not sure. https://gist.github.com/P3rf3ctXZer0/0603f5e3aecc655ea6d4def26a9e2569

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by P3rf3ctXZer0** [comment]
@Trial97 posted at request.

**Comment by Trial97** [comment]
After investigating this it looks like one of the issues solved by this PR: https://github.com/PrismLauncher/PrismLauncher/pull/1694:
- Search for mod
- abort the previous search by reentering a new text
- this causes the abort and ~destruction of the previous fetch task~ on_abort was null
Can you test this with one of the prebuild binaries from that PR?

**Comment by P3rf3ctXZer0** [comment]
I can reopn if you need felt like everything was said.

**Comment by Trial97** [comment]
Please leave it open until that PR is merged
