### ISSUE TITLE
Launcher fails to open after update to Qt 6.6.1

### ISSUE THREAD

**Issue by nokia8801** [PrismLauncher/PrismLauncher#1903]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.1 Wayland

### Description of bug

Can't open the launcher.

`prismlauncher: symbol lookup error: prismlauncher: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API`

### Steps to reproduce

Trying to start the launcher.

### Suspected cause

Update to Qt 6.6.1 might have caused this cause it was fine just hours before it. Could be considered an extension to #991 as I'm also running Arch Linux on GNOME Wayland with qt6-wayland.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Just reinstall it. If you use the git version make sure you cleaned the builder package before rebuilding.

**Comment by nokia8801** [comment]
Yep, building it again fixed it. I guess some links in Qt changed with the update and it needed to link stuff again.
