### ISSUE TITLE
MacOS root folder

### ISSUE THREAD

**Issue by Maganoos** [PrismLauncher/PrismLauncher#1917]
### Role

Playing modded minecraft, each one taking a lot of space.

### Suggestion

I want the root folder to be either configurable or there be a portable version for macOS

### Benefit

Being able to have the whole root folder on a flash drive and being able to move easily between compiters

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Aces-and-Jacks** [comment]
You can change the instance location on prism if you wanted to. But I don't think that's what your talking about

**Comment by Aces-and-Jacks** [comment]
Isn't this already kinda already thing? all the important folders can be changed to different locations

**Comment by Ryex** [comment]
You have multiple options.

1) use the folder setting the change your instance storage location (really this should be sufficient, except for global settings no other data in the data directory needs to be moved or backed up)
2) set `PRISMLAUNCHER_DATA_DIR` in your environment to change the data directory
3) edit the bundle launch script to use the `-d` or `--dir` flags to change the data directory

if none of these are sufficient we can reopen
