### ISSUE TITLE
Bring the group line back

### ISSUE THREAD

**Issue by jimgo514** [PrismLauncher/PrismLauncher#1918]
### Role

I use group feature for good layout

### Suggestion

The 8.0 update removed the group line(see image below), I want it be back.

### Benefit

The line is so important for me to identify my groups.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![未命名](https://github.com/PrismLauncher/PrismLauncher/assets/64835962/73da2ee9-b2a6-4017-bd4e-e0beb271c4b4)

**Comment by TayouVR** [comment]
related PR: https://github.com/PrismLauncher/PrismLauncher/pull/1286

we had some discussion about it on discord and in the comments there.
I can definitely see the issue here. I'll ask the other maintainers on opinions.
