### ISSUE TITLE
no confirmation when deleting instances on qt 5.12 builds

### ISSUE THREAD

**Issue by Windgott1910** [PrismLauncher/PrismLauncher#192]
### Role

I just migrated from MultiMC and deleted some old instances

### Suggestion

add a confirmation when deleting instances

### Benefit

no accidental deletions

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by timoreo22** [comment]
Instances are moved to trash

**Comment by Windgott1910** [comment]
nope

**Comment by Windgott1910** [comment]
see

https://user-images.githubusercontent.com/52463319/197204272-191dd642-1521-4263-aa69-925192ee8a7c.mp4

**Comment by DioEgizio** [comment]
i think this is because you're using a build built for qt 5.12. still a bug, but for a small subset of users

**Comment by TheKodeToad** [comment]
This also seems to affect flatpak builds which will have a lot more users.

**Comment by ghost** [comment]
> i think this is because you're using a build built for qt 5.12. still a bug, but for a small subset of users

It's actually a bug on the flatpak version as it moves it to the wrong trash location

![image](https://user-images.githubusercontent.com/110736028/197348082-8b0ffcd6-b4c2-48eb-9150-32a93a4ce584.png)

**Comment by DioEgizio** [comment]
i think this is an issue with Qt, we just tell Qt to move it to trash

**Comment by julikaiba** [comment]
please add a confirmation box regardless where its moved, clicking it on accident is really scary and confusing; Especially since the del key seems to work as well, which might be pressed on accident even more often (I for example thought another window was in focus)

**Comment by ludg1e** [comment]
Can confirm it doesn't work on the Flatpak version from Flathub in Fedora Silverblue 36.
