### ISSUE TITLE
Network Error while Scrolling though Mods List

### ISSUE THREAD

**Issue by Universal-Flare** [PrismLauncher/PrismLauncher#1927]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

While Scrolling in the Mods list while Installing Mods for My Modpack , it shows a Network error which prevents the loading of Extra Mods .

### Steps to reproduce

1. Go to a Modpack .
2. Hold the Down Arrow .
3. Hold until Message Shows Up .

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
That is a limitation of the Modrinth/Curseforge API: too many requests per minute will block your APIs.
For example modrinth:
> The ratelimit is currently 300 requests per minute. 

source: https://docs.modrinth.com/api-spec#section/Ratelimits
Curseforge should have a similar mechanism in place

**Comment by Universal-Flare** [comment]
but how do i fix it

**Comment by Trial97** [comment]
> but how do i fix it

You simply do not do so many requests per minute(in your case use the mouse wheel to navigate instead of going with the keyboard arrow through all the mods).
There is nothing to fix on either PrismLauncher or Modrinth/Curseforge as the API limits are in place to prevent DDOS Attacks.
