### ISSUE TITLE
Unable to resolve mod IDs: Invalid data returned from the API

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#1930]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

I wanted to update one of my modpacks (Better Minecraft Forge BMC4), but some time into the installation it failed with "Error while creating new instance: Unable to resolve mod IDs: Invalid data returned from the API." So I removed the pack and tried to reinstall it again, but it hit me with the same error. I can imagine that it's a problem with the modpack provider, but I'm not sure.

### Steps to reproduce

1. Try to install the modpack

### Suspected cause

-

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment]
Tried installing the modpack BMC4 and I was able to. I know that's not helpful but I don't think it's the provider

**Comment by Trial97** [comment]
I also tried to install it and it worked for me.
@ChelloVibes can you try again with the latest modpack version?
If it still doesn't work can you please attach the link to the modpack?
And maybe the prism logs from when it happens.
Additional questions:
- are you using a custom API key?
- are you having a proxy set up?

Small disclaimer it may be impossible for us to fix this if is related to the third-party launcher support on curseforge.

**Comment by ghost** [comment]
I tried installing the latest version again, and still the same error.
Here's the link to the modpack on CurseForge: [https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4](https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4)
Side note: I tried downloading the pack from Prism Launcher itself and tried importing the ZIP from CurseForge. None worked.

Additional answers:

- I'm not using an API key (idk what that even is)
- I'm not using a proxy

**Comment by Trial97** [comment]
That's the one I tried, and it worked.
Can you upload the prism logs?

- restart prism
- try to install the pack
- once it fails upload the `%APPDATA%/PrismLauncher/logs/PrismLauncher-0.log`

Before you upload it make sure that there is no information that you consider private inside that file; if it is just replace it with a bunch of `*` or with something like `<secret>`.

To upload it you can use: https://mclo.gs/ or any other pastebin provider. But if you want to upload it just to Github do it in a code block inside a spoiler.

**Comment by BoberMod** [comment]
I faced with same issue. In log I found these errors:
```
48.546 D \| [launcher.task.net.upload]: "{df58ba6f-d1ea-48e5-adb3-70c9eb79dced}" Runninng  "https://api.curseforge.com/v1/mods/files"
7515 | 48.564 W \| [qt.network.http2]: stream 7 finished with error: "HTTP/2 protocol error"
7516 | 48.564 C \| [launcher.task.net.upload]: "{df58ba6f-d1ea-48e5-adb3-70c9eb79dced}" Failed  "https://api.curseforge.com/v1/mods/files"  with reason  QNetworkReply::ProtocolFailure
7517 | 48.564 D \| [launcher.task.net.upload]: "{df58ba6f-d1ea-48e5-adb3-70c9eb79dced}" Request failed in previous step: "https://api.curseforge.com/v1/mods/files"
7518 | 48.564 D \| Setting up api upload
7519 | 48.564 D \| [launcher.task.net.upload]: "{df58ba6f-d1ea-48e5-adb3-70c9eb79dced}" Runninng  "https://api.curseforge.com/v1/mods/files"
7520 | 48.645 W \| [qt.network.http2]: stream 9 finished with error: "HTTP/2 protocol error"
7521 | 48.645 C \| [launcher.task.net.upload]: "{df58ba6f-d1ea-48e5-adb3-70c9eb79dced}" Failed  "https://api.curseforge.com/v1/mods/files"  with reason  QNetworkReply::ProtocolFailure
7522 | 48.645 D \| [launcher.task.net.upload]: "{df58ba6f-d1ea-48e5-adb3-70c9eb79dced}" Request failed in previous step: "https://api.curseforge.com/v1/mods/files"
7523 | 48.645 D \| Setting up api upload
7524 | 48.645 D \| [launcher.task.net.upload]: "{df58ba6f-d1ea-48e5-adb3-70c9eb79dced}" Runninng  "https://api.curseforge.com/v1/mods/files"
7525 | 48.664 W \| [qt.network.http2]: stream 11 finished with error: "HTTP/2 protocol error"
7526 | 48.664 C \| [launcher.task.net.upload]: "{df58ba6f-d1ea-48e5-adb3-70c9eb79dced}" Failed  "https://api.curseforge.com/v1/mods/files"  with reason  QNetworkReply::ProtocolFailure
7527 | 48.664 D \| [launcher.task.net.upload]: "{df58ba6f-d1ea-48e5-adb3-70c9eb79dced}" Request failed in previous step: "https://api.curseforge.com/v1/mods/files"
7528 | 48.664 W \| Error while parsing JSON response from Flame files task at  0  reason:  "illegal value"
```

I tested a fresh installation of PrismLauncher and it was working as expected. After some file comparison, I found `UserAgentOverride` line in my config. After removing the value from this param, the main installation started working correctly.

**So, if someone faced with this issue, try this:**
1. Open PrismLauncher installation directory
2. Open `prismlauncher.cfg`
3. Remove value from `UserAgentOverride` param, so it should be just `UserAgentOverride=`

----
You also can set default proxy settings, by changing all related params to these:
```
ProxyAddr=127.0.0.1
ProxyPass=
ProxyPort=8080
ProxyType=None
ProxyUser=
```
