### ISSUE TITLE
Archive does not contain a recognized modpack type

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#1932]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

QT 6.6.0

### Description of bug

I tried to download `Nightmare Craft: Survival` modpack but it showed `Archive does not contain a recognized modpack type`

### Steps to reproduce

download modpack
get error

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Just to be clear are you trying to install this: https://www.curseforge.com/minecraft/mc-mods/nightmare-craft-survival as a modpack?

**Comment by Aces-and-Jacks** [comment]
yes

**Comment by Trial97** [comment]
That is a mod. Obviously this doesn't work, it isn't a modpack so I'm gonna close this.
But how did you get that to show in modpack selection?

**Comment by Aces-and-Jacks** [comment]
Oh...I honestly missed that. When I saw it I assumed it was a modpack. I probably should've looked further. I got it to show by typing in the #ID

**Comment by Trial97** [comment]
> I got it to show by typing in the #ID

If you do that please make sure that the project is the correct type: if you do #ID Prism always returns the project mentioned even though it doesn't match the current view(doesn't do an additional check to see if is a modpack or a mod).
So please be careful when using #ID as it may not return the resource type that you want. Only use it when you know what are you doing.
