### ISSUE TITLE
sharing to another 

### ISSUE THREAD

**Issue by ifbw** [PrismLauncher/PrismLauncher#1937]
### Role

i play modded mc with my friend

### Suggestion

add a way to share the modpack to another prism user via their mc username or some other way

### Benefit

so i dont have to export it as mcpack or zip, then upload it to google drive, then to discord. then repeat the next day cause i added a few mods and they are too big for discord

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
For what you describe there is Packwiz: https://packwiz.infra.link/. 
Sorry but right now there is nothing in the plan to develop a different export format(use mcpack, curseforge or prism).
Also, there is no way we can share modpacks only using mc usernames.

**Comment by TayouVR** [comment]
there is also moddermore, specifically to share modpacks/instances.

**Comment by ifbw** [comment]
idk what i described or what i said, and i dont mean that it should be specifically with mc usernames, it can be some sort of connection type thing with friend requests or sum (like dsicord probably) but for sharing mods n modpacks

**Comment by ifbw** [comment]
ok
