### ISSUE TITLE
Modrinth API documentation link in the settings cannot be clicked on

### ISSUE THREAD

**Issue by lumiscosity** [PrismLauncher/PrismLauncher#1939]
### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

In the APIs -> API Keys tab of the launcher settings, the Modrinth documentation link cannot be clicked on. It can, however, be right clicked to obtain the link.

### Steps to reproduce

* Open the APIs -> API Keys tab of the launcher settings
* Try to click on the documentation link

### Suspected cause

Maybe some weird Qt-side bug with links in the highlighted boxes?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
fixed by #1880
