### ISSUE TITLE
Unable to log into microsoft account

### ISSUE THREAD

**Issue by aklausing** [PrismLauncher/PrismLauncher#1940]
### Operating System

Windows 11 22H2 / MacOS 13.6.2

### Version of Prism Launcher

Prism Launcher 8.0 (on PC and MacOS)

### Version of Qt

6.6.0

### Description of bug

In account view my account shows as "failed" and when starting any minecraft instance (mod or non mod) ist fails to login after three tries.
When trying to add a new account it fails with "Fehler beim Abrufen des Minecraft-Zugangs-Token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: "

Sorry for the german error message.

Seems that minecraft vanilla laucher is working.

### Steps to reproduce

Tried to add different accounts on different computers

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
The auth servers are most probably down.
Please be patient.
This is not a Prism issue.
