### ISSUE TITLE
Console window stuck on full screen after accidentally importing window in borderless gaming

### ISSUE THREAD

**Issue by Rice4lyfe** [PrismLauncher/PrismLauncher#1942]
### Operating System

Windows

### Version of Prism Launcher

Version 8.0

### Version of Qt

6.6.0

### Description of bug

I was trying to import a minecraft window to full screen by favorites using an application called Borderless gaming (allowing the user to make any window fullscreen without any mods) but accidentally clicked on a console window instead. Trying to bring back the window from favorites has made the console window stuck on full screen at all times and I can not seem to change it back. In addition, I have tried to reinstall borderless gaming and prism launcher but it still remains that way.

### Steps to reproduce

-Have borderless gaming opened
-Click edit on a Minecraft instance that needs to be edited (to show the console window)
-on the borderless gaming app click on the console window (of that instance) in which case it should make the console windowed fullscreen

### Suspected cause

I think one of the settings for which applications are windowed full  might be hard coded in a folder setting but I don't really know where that might be.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ZeekDaGeek** [comment]
Same issue, except I did it with the main Prism Launcher window as well, and there's no setting to stop Prism Launcher from remembering your previous window dimensions.

**Comment by ZeekDaGeek** [comment]
I was able to fix this issue manually by going into `%APPDATA%\Roaming\PrismLauncher` editing `prismlauncher.cfg` and deleting the following lines:

```ini
MainWindowGeometry= ...
MainWindowState= ...
ConsoleWindowGeometry= ...
ConsoleWindowState= ...
```

It's crazy that the window state saves settings for hiding the title bar with the minimize/maximize buttons, and the outside chrome for resizing the window.
