### ISSUE TITLE
Empty, not installed mod listed when updating mods

### ISSUE THREAD

**Issue by Rafii2198** [PrismLauncher/PrismLauncher#1943]
### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

When updating mods, the first "mod" on the list has no name, says that precious version is "Not installed" and has no new version nor changelog. This is the second time I ever see that, but the first time was some time after 8.0 update.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/26695327/22ace8eb-409e-4128-9b04-83a29f6becd0)

[Link to Gdrive for instance download if needed](https://drive.google.com/file/d/1J9VJ9tj_OOYM2eF82ApYbRZMpOtA7qSr/view?usp=sharing)

### Steps to reproduce

I have no idea how it is triggered, it just happened when I tried updating the mods. But perhaps logs will have more info to identify it
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/13633500/PrismLauncher-0.log)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
fixed by #1843
