### ISSUE TITLE
Enhancement for Cat Overlay

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#195]
### Role

Ideas for Cat Overlay

### Suggestion

Make the cat have the Prism Launcher in it's hand instead of a yarn ball.

### Benefit

Gonna be real.. I don't really know. But it's a cool idea so 💀

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The cat in the launcher is cool n all but I had an idea pop in my head that I think will make the little guy even better!

- When launching Prism, Make the cat move upwards slowly and fade in at the same time.
- Add Prism Logo in replacement of yarn ball.
- When hovering over the yarn ball, make it so colors are constantly in a loop of all the colors of the rainbow.

lmk of any ur ideas below. :)

**Comment by ghost** [comment]
also make the cat meow

**Comment by Scrumplex** [comment]
Not sure if we are going to do that. But we did add multiple cats now! #372

**Comment by ghost** [comment]
oh cool! Well if its something that adds an addition to the cat im all for it!
