### ISSUE TITLE
Cannot launch Forge 1.16.5 on Arch Linux

### ISSUE THREAD

**Issue by soup6020** [PrismLauncher/PrismLauncher#1969]
### Operating System

Arch Linux, kernel `6.6.7-hardened1-1-hardened`, `OpenJDK 64-Bit Server VM Temurin-11.0.21+9`

### Version of Prism Launcher

Prism Launcher commit e39a03421a6e8cdf58f8b5d98388b9eef55d44b7

### Version of Qt

6.6.1

### Description of bug

When I attempt to launch a 1.16.5  instance with Forge installed, the game starts up and I can see Forge take over the loading screen, but it always crashes before the title screen. This does not happen with a vanilla 1.16.5 instance. This is also not solved by reverting to Java 8. 

### Steps to reproduce

Create a 1.16.5 instance in the launcher, install either the suggested or latest version of forge available, using the launcher's interface.

### Suspected cause

I am not sure, but I have logs here: https://mclo.gs/st6sYnJ

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
This is really odd. It looks like it can't set up logging properly. Does your environment havw any special configuration regarding log4j?

**Comment by soup6020** [comment]
Not that I'm aware of. I'm not loading a custom log4j configuration or anything like that, just whatever is provided.

**Comment by soup6020** [comment]
I will also add that this does not happen on another launcher I tested, with an identical JVM.

**Comment by boomshroom** [comment]
Completely different distro, completely different java version, different Minecraft forge version; same Minecraft version, same log4j version, same Prism Launcher version.

Exact same error somehow.

**Comment by boomshroom** [comment]
I was able to resolve the issue by "Customizing" the Minecraft version to replace the present log4j files with a set copied from a manually install minecraft forge version. Notable is that not only were the versions different, but the official installation also had a `log4j-slf4j18-impl` component that wasn't present in the manifest of the PrismLauncher instance.

**Comment by soup6020** [comment]
Marking as closed, issue was solved by deleting ~/.local/share/PrismLauncher and starting fresh
