### ISSUE TITLE
Download button does not appear on resources pack tab

### ISSUE THREAD

**Issue by MeeniMc** [PrismLauncher/PrismLauncher#1974]
### Operating System

Windows

### Version of Prism Launcher

8.0

### Version of Qt

6.6.0

### Description of bug

The 'download' button does not appear on the 'resource pack tab'. 

This is not a feature request, as the feature for downloading resource pack already exist:  the download option is in the right click action, it just looks like the button got forgotten in that tab when the feature was added.

### Steps to reproduce

![image](https://github.com/PrismLauncher/PrismLauncher/assets/68366846/0215017f-a3e2-47e9-9aa8-42d311eb720d)

### Suspected cause

Button is missing because the tab was forgotten during prior update.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
You can choose what buttons are visible on that wide bar by right-clicking it and selecting the button.
Closing this as this is not an issue.

**Comment by MeeniMc** [comment]
Thanks I must have clicked that by mistake at some point
