### ISSUE TITLE
[1.7.10]Online fixes doesn't work 

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#1981]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

If online fixes(experimental) enabled, skins are still look like steve, instead of alex
i know it's experimental, but anyway
1.Discord conversation
![Screenshot_20231224_161354](https://github.com/PrismLauncher/PrismLauncher/assets/139335984/9a8c7a45-dfa1-4cae-8e5f-12294968c640)
2.Minecraft 3rd person
![2023-12-24_16 15 01](https://github.com/PrismLauncher/PrismLauncher/assets/139335984/534d0fbb-e4e3-4559-8a0b-66323031ed92)

### Steps to reproduce

* Enable online fixes(experimental)
* log into minecraft 1.7.10
* skin has 2 black bars on hands

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
i might got it wrong

**Comment by TheKodeToad** [comment]
Online fixes doesn't apply to 1.7.10 as that already supports modern skins. It doesn't support the models but you'll need a mod for that!

Well, Online fixes on older versions does remove the black bars by using some image manipulation but it doesn't change the model.

**Comment by ghost** [comment]
alright
