### ISSUE TITLE
installing a modpack tries *every* path on my drive as a watch path

### ISSUE THREAD

**Issue by thisaray** [PrismLauncher/PrismLauncher#1982]
### Operating System

Windows

### Version of Prism Launcher

Prism 9.0

### Version of Qt

Qt 6.6.0

### Description of bug

I expected prism to search through my defined paths (
![grafik](https://github.com/PrismLauncher/PrismLauncher/assets/41525308/b33c7f83-4740-40b5-99f1-ea6a521abd98)
) and not through random ones (
![grafik](https://github.com/PrismLauncher/PrismLauncher/assets/41525308/5ce43533-232f-453f-8cdb-c5403e6e06cb)
)

### Steps to reproduce

choose a random modpack from curse
install it while watching logs

### Suspected cause

No ideas

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
I know that this is not a solution, but make sure that you do not have any symbolic links in that folder.
Preferably try to reproduce it with an empty folder.
If it still happens upload the full log(maybe trim some  `Add watch path` logs, but mark that somehow e.g. `<AddWatchPath>`.(this is to keep your file names a secret) Please try to keep some of them preferably the first few lines until it starts to scan a different drive.

**Comment by thisaray** [comment]
does not happen with an empty folder, probably some hiccup somewhere
