### ISSUE TITLE
Suggestions on mod list management and mod synchronization

### ISSUE THREAD

**Issue by PeakXing** [PrismLauncher/PrismLauncher#1986]
### Role

I play modded Minecraft with friends

### Suggestion

1. The mods in the mod list are classified according to the type of management. Can it be considered that the operation adds labels? Or get a tag from a mod website? 2.mod synchronization function, provide a string of keys to friends, the initiator uses the key to automatically identify the main mod download, disable or delete the mod? This feature is associated with the person who provided the key, and friends can choose whether to stay with me or not.

### Benefit

1. I play mods with my friends, I have over 200 mods to manage, it's confusing, I often need to check which mods are what features, such as whether they need server-side installation, whether they are terrain generation and so on. 2. I hate syncing every time I tell my friends what I deleted and what I added. I wish I could give them an easier key or other string to keep up with the primary initiator. Of course, this function needs to click the sync button, otherwise it will not take effect.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
Most of what you describe has an issue open:
- categories: https://github.com/PrismLauncher/PrismLauncher/issues/1431,  https://github.com/PrismLauncher/PrismLauncher/issues/1076, https://github.com/PrismLauncher/PrismLauncher/issues/154
- mod side: https://github.com/PrismLauncher/PrismLauncher/issues/1568
- prism already displays the mod provider
- regarding synchronization use mrpack export format(or curseforge one) for updating a exinsting modrinth/curseforge pack from file :https://github.com/PrismLauncher/PrismLauncher/issues/1394 (it's already implemented and will be shiped in 8.1)
