### ISSUE TITLE
Show Warning if using Rivatuner Statistics Server(RTSS) and Sodium/Magnesium

### ISSUE THREAD

**Issue by LakesideMiners** [PrismLauncher/PrismLauncher#1987]
### Role

Play Modded Minecraft

### Suggestion

Show Warning if using Rivatuner Statistics Server(RTSS) and Sodium/Magnesium

### Benefit

assist users in chasing down a really niche issue when using one of the mentioned mods

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

As the title says, when a user has RTSS running, and one of the mods they have installed is Sodium/Magnesium(from now on referred as Sodium for the sake of readability), a popup or something should be shown to the user to let them know that it is why the game crashes. 
This is the intended behavior of sodium as shown in the known issues section of the wiki for Sodium.
https://github.com/CaffeineMC/sodium-fabric/wiki/Known-Issues#rtss-incompatible

Sodium does print a message to the console, but, its a bit burred and having a popup show up might be of use to the end user to allow for it to be less painful to look for it.

The official Minecraft launcher does show said console log more prominently. 
![image](https://github.com/PrismLauncher/PrismLauncher/assets/23389169/07dfbfad-fe50-4fcf-b0c7-b0e0939c2d6b)

As I feel this could be a common issue, adding in a popup box or some other way to better show the error message printed by Sodium would be of use

**Comment by Trial97** [comment]
This is not planned.

**Comment by Scrumplex** [comment]
Perhaps we can adapt this feature request to generally parse Minecraft crash logs and somehow highlight the important parts of a crash log (usually the first line of a stack trace)

**Comment by Trial97** [comment]
> Perhaps we can adapt this feature request to generally parse Minecraft crash logs and somehow highlight the important parts of a crash log (usually the first line of a stack trace)

That is fine, but instead of reusing this issue, I think a new one with clear requirements should be made.
