### ISSUE TITLE
Migration from PolyMC

### ISSUE THREAD

**Issue by jakiisheep** [PrismLauncher/PrismLauncher#2]
PolyMC founder went rouge, please uninstall PolyMC OR change the metaserver as seen here:	

![image](https://user-images.githubusercontent.com/68562536/196278073-b248bbff-b7b6-4829-b62d-6f9d5cea7407.png)

FAQ:

Are minecraft accounts safe?

Yes, from what we know
Don't update PolyMC from now on 

Are Microsoft accounts fine?
Yes, that's controlled by Scrumplex specifically 

New discord: https://discord.gg/hX4g537UNE

**Comment by AetherXSN** [comment]
got it

**Comment by LinusKerman** [comment]
Name it PrideMC or something gay related lol

**Comment by Scrumplex** [comment]
New meta server: `https://meta.scrumplex.rocks/v1/`

**Comment by Midou36O** [comment]
Can someone make a new matrix bridge for the new server? Seems like the polymc bridge got muted now too
![image](https://user-images.githubusercontent.com/45198486/196393946-b0006aff-6ed1-4c34-96c0-2454d2351f42.png)

**Comment by Park-Hajin** [comment]
you have to rename it LGBTlauncher XDD

**Comment by Scrumplex** [comment]
New new meta server: `https://meta.prismlauncher.org/v1/`

I will try to keep the old link up as well

**Comment by Scrumplex** [comment]
> Can someone make a new matrix bridge for the new server? Seems like the polymc bridge got muted now too ![image](https://user-images.githubusercontent.com/45198486/196393946-b0006aff-6ed1-4c34-96c0-2454d2351f42.png)

Matrix bridge is planned. But we are focusing on getting a release out first

**Comment by Sebbl0508** [comment]
Could you pin this issue?

**Comment by Inderix** [comment]
I think it's worth changing the name of this issue as well to better summarize what happened

**Comment by LZeugirdor** [comment]
Discord invite link is frozen for some reason and I can't join but I support what you guys are doing.

**Comment by KaspianDev** [comment]
Are you guys sure it was a hack?

**Comment by DioEgizio** [comment]
oh it wasn't

**Comment by glowiak2** [comment]
May I ask who is the rouge leader?

**Comment by Scrumplex** [comment]
> May I ask who is the rouge leader?

LennnyMcLennington

**Comment by glowiak2** [comment]
ah

**Comment by glowiak2** [comment]
@Scrumplex Is the v1.2.1 I use safe?

**Comment by glowiak2** [comment]
> > May I ask who is the rouge leader?
> 
> LennnyMcLennington

I am safe using v1.2.1?

**Comment by KaspianDev** [comment]
There's no malware too, you just need to replace meta thingy with either prism or new poly (you can find that one on discord)

never trust software no matter if dev is trustworthy or not btw

**Comment by glowiak2** [comment]
> There's no malware too, you just need to replace meta thingy with either prism or new poly (you can find that one on discord)

The M$ metaserver?

**Comment by glowiak2** [comment]
@KaspianDev

**Comment by KaspianDev** [comment]
> > There's no malware too, you just need to replace meta thingy with either prism or new poly (you can find that one on discord)
> 
> The M$ metaserver?

Oh sorry i meant auth ID thing, the new one from poly is posted on discord in news, theres also explaination of security concerns.

**Comment by glowiak2** [comment]
> > > There's no malware too, you just need to replace meta thingy with either prism or new poly (you can find that one on discord)
> > 
> > 
> > The M$ metaserver?
> 
> Oh sorry i meant auth ID thing, the new one from poly is posted on discord in news, theres also explaination of security concerns.

I have my own msaid from times I was maintaining a patched build of mmc, already have this replaced

**Comment by glowiak2** [comment]
@KaspianDev is it enough to change msaid? I saw a new commit on pmc from mrlenny changing it

**Comment by DioEgizio** [comment]
lmao

**Comment by glowiak2** [comment]
nevermind i don't care you guys banned me entirely from github once i don't want to lose this account too

**Comment by KaspianDev** [comment]
> @KaspianDev is it enough to change msaid? I saw a new commit on pmc from mrlenny changing it

I don't know really, ask someone from poly or the new fork.

**Comment by Evrey** [comment]
@glowiak2 

![image](https://user-images.githubusercontent.com/6483505/196466167-40a323c8-b936-468d-9fa3-d2a9e92a6d34.png)

For copy-pasta:

- `https://meta.prismlauncher.org/v1/`
- `c36a9fb6-4f2a-41ff-90bd-ae7cc92031eb`

The Flatpak release is »safe«, for its maintainer is not lenny.

**Comment by glowiak2** [comment]
Uh pmc v1.2.1 does not have the option to change metaserver

**Comment by Evrey** [comment]
Well, that’s a lil’ awkward, then.

![image](https://user-images.githubusercontent.com/6483505/196468046-89fa77e0-6bdb-4d1e-aefb-9218d987b953.png)

The FAQ only speaks of v1.4.2, the last version before all *this*.

(**E:** This is me blindly assuming sharing info from the Discord here is fine.)

**Comment by glowiak2** [comment]
I use still 1.2.1 because for some reason newest versions can't run my 1.2.5 instances

**Comment by DioEgizio** [comment]
i think that got fixed in 1.3.2

**Comment by TheEvilSkeleton** [comment]
> New discord: https://discord.gg/hX4g537UNE

The link appears to be dead for me.

**Comment by Jeder321** [comment]
they removed the working link for some reason
https://discord.gg/prismlauncher

**Comment by glowiak2** [comment]
> i think that got fixed in 1.3.2

right

**Comment by Evrey** [comment]
> they removed the working link for some reason […]

Troll raids.

**Comment by Scrumplex** [comment]
New users can't join right now because of a raid

**Comment by ghost** [comment]
Stop saying he killed the project, he clearly fully intends on continuing development

**Comment by DioEgizio** [comment]
> Stop saying he killed the project, he clearly fully intends on continuing development

just so you know, his contributions to polymc are marginable, and the reputation of polymc broke

**Comment by thatpix3l** [comment]
Seems like you'll also need a full rebrand of the entire project, not just name changes. What about stuff like logos, website design and stuff like that?

**Comment by Scrumplex** [comment]
Currently being worked on

**Comment by TheOPtimal** [comment]
Honestly I think this really exemplifies just how responsible the FOSS community is and how it does not tolerate any sort of transphobia, racism, sexism, or any other form of bigotry. Within a matter of hours of the rogue-ing, announcements went out, some repositories dropped the package and some have stopped updating it, and a new fork was quickly created, with all the devs (except 1, obviously) jumping ship.

You guys rock.

**Comment by AliceDTRH** [comment]
Will this project have any kind of system to prevent a single person from taking over the project?

**Comment by jakiisheep** [comment]
I am gonna close this issue because Prism released 5.0 which means its usable now. If you still wanna comment about migration from PolyMC or anything related you are free to do so!

**Comment by jakiisheep** [comment]
> Will this project have any kind of system to prevent a single person from taking over the project?

Yes, definitely.

**Comment by Midou36O** [comment]
This will also help avoiding the bus effect hopefully

**Comment by rafalohaki** [comment]
rip polymc

**Comment by KaspianDev** [comment]
> rip polymc

PolyMC project is not getting abandoned, just letting you know.

**Comment by DioEgizio** [comment]
> > rip polymc
> 
> PolyMC project is not getting abandoned, just letting you know.

It's getting abandoned, just not officially lol

**Comment by Midou36O** [comment]
> > > rip polymc
> > 
> > 
> > PolyMC project is not getting abandoned, just letting you know.
> 
> It's getting abandoned, just not officially lol

You shouldn't be talking about PolyMC anymore, you have to move on. it's a sad fate for PolyMC but we shouldn't be thinking about it anymore.

**Comment by jakiisheep** [comment]
@Scrumplex @DioEgizio please lock this issue, its starting to get spammy and unnecessary.
