### ISSUE TITLE
Mod Downloader Font Sizes

### ISSUE THREAD

**Issue by LackingCats** [PrismLauncher/PrismLauncher#20]
The font sizes in the mod downloader are disproportionate. https://imgur.com/a/zQOeuvM
(Running Fedora 36 KDE Edition [X11], Kernel Version 5.19.15)

Also, is CurseForge support going to be added in the near future? (needing to apply for new api key)

**Comment by LackingCats** [comment]
(the form to apply for curseforge api key) 
https://forms.monday.com/forms/dce5ccb7afda9a1c21dab1a1aa1d84eb?r=use1

**Comment by LackingCats** [comment]
It seems like curseforge support was added, changing title

**Comment by aprilthepink** [comment]
maybe do 2 seperate issues next time ;)

**Comment by forkiesassds** [comment]
Is it possible to reproduce this bug with the Modrinth modpack tab? I can't really test since I don't have any HIDPI displays

**Comment by LackingCats** [comment]
Yes, I just tested it
