### ISSUE TITLE
Crashing if trying to block gamemode D-Bus with firejail

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#2011]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.4.2

### Description of bug

Prism Launcher is crashing if trying to block D-Bus using firejail with gamemode installed
```
GameMode ERROR: Could not connect to bus: Failed to connect to socket /run/firejail/mnt/dbus/user: Permission denied
dbus[5]: arguments to dbus_connection_unref() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 2832.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
```
it is not firejail bug or something
Prism Launcher **should not** crash if it's not able to access D-Bus, but instead show some warning and continue working!

### Steps to reproduce

```
sudo apt install gamemode
firejail --dbus-user=none ./prismlauncher
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is a gamemode library issue(see https://github.com/FeralInteractive/gamemode/pull/458).
I will leave this open to better track that.
The summary is the gamemode library tries to clean a null pointer breaking the application.

**Comment by Trial97** [comment]
Looks like my PR was merged so I'm gonna close this as completed.
You may need to wait until gamemode releases a new version for this to be fully fixed, but if you want it try building gamemode from the source.
