### ISSUE TITLE
update checker running when it shouldn't

### ISSUE THREAD

**Issue by NotADinosaur** [PrismLauncher/PrismLauncher#2013]
### Operating System

Windows

### Version of Prism Launcher

8.0

### Version of Qt

6.6.0

### Description of bug

I recently switched from multimc after I accidentally uninstalled it (yep, I'm dumb lol) because I'd heard prism was better, and rather than running the update check on launch it seems to run at random times. Sometimes it does it when it's supposed to, but other times it does it hours later when I'm doing something else, forcing the "no updates found" window to be the focus, interrupting whatever other program I'm running (e.g playing a different game). Twice now it has even done this after I closed prismlauncher (using the X button in the titlebar) because it continues running as a background task only visible in task manager for some reason.

### Steps to reproduce

It doesn't happen consistently so I'm not sure what to put here. Just use the launcher I guess? Never happened with multimc.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
What updater do you mean: mod updater or prism updater? 
When closing prism make sure you do not have any instances running(if not prism will run in the background).
Can you provide some logs?

**Comment by NotADinosaur** [comment]
I'm talking about the prism updater. I might've had minecraft running, that would make sense I suppose, however it still should not randomly be running the updater after it has been in the background for a while. I don't see how minecraft logs would be relevant to this issue.

**Comment by Trial97** [comment]
I meant prism logs. They are located inside the prism data root directory inside the logs folder. There should be multiple files that are numbered from 0 to 4(0 means is the most recent).
So once it reproduces please upload all the files that have a 0(there should be multiple files), but make sure you check for personal data(upload it to a pastebin service please).
Also please check, using task manager, if prism is still running after you close it.

**Comment by Trial97** [comment]
Also there is a setting for that that you can toggle off: Settings>Launcher>Check for updates automatically

**Comment by phit** [comment]
turning this on in multimc only does an update check when the launcher is started, not on a timer https://github.com/PrismLauncher/PrismLauncher/blob/f931890e953f2f80c794d68a1fed94863424e126/launcher/updater/PrismExternalUpdater.cpp#L70
supposedly this should be once a day but I also have noticed this coming up after having the launcher open for a couple of hours forcing focus on the update window
