### ISSUE TITLE
Labymod doesn't work for me on prism launcher when for others it does

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#2014]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

When I launcher labymod on prism launcher it crashes

### Steps to reproduce

Install Labymod on prism launcher
crashes

### Suspected cause

Normally this would be something I'd ask in the labymod discord since it's a mod issue, and I did. For a while I just thought they didn't support it. But later on I saw someone say that they downloaded the latest version of prism launcher and labymod and it worked on their system. So now I'm thinking it's an issue for just me but I don't know what. 

I know this is probably more an issue for their mod, but I was thinking that maybe on the off chance it's something with prism launcher that can be fixed? If not then it's fine, at least I asked rather than assuming. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
I'm pretty sure that it is not a prism issue as you mentioned that for other people this is working.
As I'm not familiar exactly with what exactly labymod is, my suggestion is try to ask questions on prism discord (maybe some people may know better)

**Comment by Aces-and-Jacks** [comment]
ok. Also I know this probably isn't helpful but it works on multimc. I know it's what they officially support and that multimc is different from prism launcher but wanted to mention since it being a OS issue would probably be unlikely. Or OS may be a likely issue, but I doubt it. 

Should I close this then since its not solvable on prism's side?

**Comment by TheKodeToad** [comment]
can you post a crash log?

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/moAWP1f

**Comment by Aces-and-Jacks** [comment]
I figured maybe if someone on another system also installed labymod and it worked for them maybe they would be able to see what happened differently

**Comment by Trial97** [comment]
Try with java8

**Comment by Aces-and-Jacks** [comment]
Wouldn't that not make since since `LabyMod-4-1.20.4` 1.20.4 is the version

**Comment by Trial97** [comment]
Not sure myself, I only say because of a warning from the crash log:```[15:52:24] [main/WARN]: The requested compatibility level JAVA_17 is higher than the level supported by the active subsystem 'LabyMod' which supports JAVA_8. This is not a supported configuration and instability may occur.```

**Comment by Aces-and-Jacks** [comment]
Well tried it and it didn't work. Even tried deleting the instance and reinstalling 1.8.9...and while typing this strangely that version worked with java 17 and not with java 8

**Comment by Aces-and-Jacks** [comment]
I remember seeing that before. Which I did try before asking here. But as stated before that didn't work

**Comment by Aces-and-Jacks** [comment]
Imma try different minecraft versions and see what versions don't work

**Comment by Aces-and-Jacks** [comment]
ok it's only 1.8.9 that works...

**Comment by Aces-and-Jacks** [comment]
Scratch that. Gave up too soon. 1.8.9, 1.16.5, 1.17.1, and 1.18.2 all work. Strangely on java 17 but that's probably something they did

**Comment by Aces-and-Jacks** [comment]
Yeah I'm probably just going to close this. They might've done it differently per version and maybe one of those might've caused it

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/nbinDie

```
java.lang.NoClassDefFoundError: ca/weblite/objc/Client
	at ehg.a(SourceFile:42)
	at ehn.a(SourceFile:154)
	at enn.<init>(SourceFile:492)
	at net.minecraft.client.main.Main.main(SourceFile:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:217)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:70)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ClassNotFoundException: ca.weblite.objc.Client
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:351)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:238)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.launchwrapper.LaunchClassLoader.loadClass(LaunchClassLoader.java:228)
	... 13 more
```

I know I closed this but just wanted to put this here since I saw for another issue `java.lang.NoClassDefFoundError: ca/weblite/objc/Client` was a problem

**Comment by Trial97** [comment]
I was able to run it on Linux so it is not a laucher problem, continue asking on discord maybe there is somebody how knows.
