### ISSUE TITLE
Eclipse Adoptium jdk-21.0.1: The specified Java binary didn't work.

### ISSUE THREAD

**Issue by Kirisoup** [PrismLauncher/PrismLauncher#2020]
### Operating System

Windows 10

### Version of Prism Launcher

8.0

### Version of Qt

6.6.0

### Description of bug

Cannot use Eclipse Adoptium jdk-21.0.1+12 (`C:/Program Files/Eclipse Adoptium/jdk-21.0.1.12-hotspot/bin/javaw.exe`). 

In `Settings > Java > Java Runtime`, clicking `Test` will result in
```
Java test failure
The specified Java binary didn't work.
You should use the auto-detect feature, or set the path to the Java executable.
```

Running the game will result in: 
```
Checking Java version...
Could not start java:


Check your Java settings.
```

Edit: Using the same exact jdk to launch minecraft from other launchers works fine, so I don't think it is a problem with the jdk

### Steps to reproduce

+ Install Eclipse Adoptium jdk-21.0.1+12 (Windows x64, .msi) from https://adoptium.net/temurin/releases/?version=21&os=windows&arch=x64.
+ Go to `Settings > Java > Java Runtime` in Prism launcher, set `Java path` based on where you install the jdk.
+ click `Test` (or launch an instance)

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Why does Prism Launcher ask me to change Java version?
Minecraft versions before 1.17 required Java 8 and have issues with newer Java, while newer versions require Java 17, so you need to change Java version. Some people think Java 8 is very outdated, however, it's actually an LTS, meaning it's still getting updates.

If one of your mods is weird and requires newer Java, you can bypass this, by going to instance settings-Java and ticking 'Skip java compatibility checks', but be aware of potential issues, such as [random CMEs](https://bugs.mojang.com/browse/MC-149777).
