### ISSUE TITLE
Add a loading screen before the GLFW window initializes.

### ISSUE THREAD

**Issue by Igrium** [PrismLauncher/PrismLauncher#2021]
### Role

I use a lot of client mods (fabulously optimized), so the game takes a while to load.

### Suggestion

There should be a loading window that appears before the primary GLFW window opens.

### Benefit

This way, people don't get confused when the game is "launching", but they don't see anything.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

In contrast to Vanilla, Fabric Loader performs a myriad of operations before the primary Minecraft window opens. This includes mixin application, mod initializers, etc., which can take quite some time depending on the number of mods installed.

As it is, the only way to monitor this process, or get visual feedback of any kind, is to open the "edit instance" screen and look at the console, which feels a bit janky.

I propose that the loading window displayed by the launcher before the game opens remain open until a GLFW window is detected from the MC process. This way, it's clear to the common person that the game is working.

**Comment by Trial97** [comment]
This looks more like a fabric issue, not a prism one, so I will gonna close this.

**Comment by Igrium** [comment]
I think I may have mis-described the issue.

While Modded Minecraft's extended pre-launch period exacerbates the issue, this is still a problem in Vanilla. Minecraft opens its primary window rather late in its initialization, and due to various limitations with LWJGL and OS integrations, it's impossible for Fabric or any other mod loader to display a pre-loading screen from within the JVM.

This is why external launchers such as Prism must provide a fix. If I'm not mistaken the stock launcher already does this.
