### ISSUE TITLE
Rustic Waters II (Curseforge) "No version is available!"

### ISSUE THREAD

**Issue by kman3107** [PrismLauncher/PrismLauncher#2031]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

I expected a version of the modpack to be shown, and that I would be able to install it.

I can install on both Curseforge and GDLauncher apps.

### Steps to reproduce

1. Add instance
2. Curseforge
3. Filter "Rustic"
4. Choose top hit "Rustic Waters II"
5. Version selected: No version is available!
6. OK button is greyed out (duh)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by KTrain5169** [comment]
<img width="549" alt="image" src="https://github.com/PrismLauncher/PrismLauncher/assets/69028025/6a20c210-d7fe-4d65-ba97-6951809b9a92">

Works completely normally for me

**Comment by Trial97** [comment]
>CurseForge added a new option to block third party clients like Prism Launcher from accessing mod files, and they started to enforce this option lately. We can't allow you to download those mods/modpacks directly from CurseForge because of this.  We highly encourage asking authors who opted out of client downloads to stop doing so.

And from what I know GDLauncher has a deal with curseforge that allows them to access blocked content.

**Comment by kman3107** [comment]
I tried uninstalling and deleting appdata. Unfortunately I am still not getting that pack like you are KTrain5169
![Untitled](https://github.com/PrismLauncher/PrismLauncher/assets/10728652/77b87fb9-8f9f-45f5-ba0a-e0a226e56d57)

**Comment by Trial97** [comment]
It is not a issue with prism but with curseforge API that doesn't allow third party modpack/mods. There is a way to bypass curse verifications by changing the default API token. But that is not recommend as it break's curseforge tos, so I will not detaliate more.
