### ISSUE TITLE
Launching an instance with patched GLFW-Wayland still calls XWayland, only during launch

### ISSUE THREAD

**Issue by nokia8801** [PrismLauncher/PrismLauncher#2032]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.1

### Description of bug

I'm running a [patched version of GLFW](https://github.com/BoyOrigin/glfw-wayland) so I can play the game natively on Wayland, without the use of XWayland. I can confirm with both xeyes and xwininfo that the launched Minecraft instance is running natively on Wayland. Everything works great in that regard, no issues there.

The GUI of Prism Launcher is also running natively on Wayland since I installed qt6-wayland and also have `QT_QPA_PLATFORM=wayland` as an environment variable.

The issue is that when I click on "Launch", the XWayland process is triggered which I can see in GNOME System Monitor and the process immediately starts sleeping. Something is triggering XWayland.

**System Info:**
Arch Linux
Kernel 6.7.0
[Prism Launcher 8.0](https://aur.archlinux.org/packages/prismlauncher)
Qt 6.6.1 with qt6-wayland
GNOME 45.3 on Wayland

### Steps to reproduce

- Use the patched GLFW library.
- Launch an instance.
- See the XWayland process pop up on your system monitor. Observe that it immediately starts sleeping.
- Confirm the that launched instance is using Wayland anyways, with xeyes and/or xwininfo.

### Suspected cause

I don't really know. However since both the GUI and the Minecraft instance itself runs natively on Wayland, I believe the launcher is calling on XWayland for an unrelated reason, only during launch.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Prism Launcher queries information about your GPU using glxinfo. Perhaps that is the culprit here

**Comment by nokia8801** [comment]
I doubt it. My system is pretty much Wayland only, from the variables to the apps.

I forgot to add the logs but here they are.

[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/13942804/PrismLauncher-0.log)
[Minecraft.log](https://github.com/PrismLauncher/PrismLauncher/files/13942860/Minecraft.log)

**Comment by Scrumplex** [comment]
Your `Minecraft.log` shows the GPU info queried by Prism Launcher using `glxinfo`.

`glxinfo` will communicate with your X server's socket (in this case XWayland)

You could uninstall that tool to prevent Prism Launcher from using it

**Comment by nokia8801** [comment]
You were right. Removing `mesa-utils` which included `glxinfo` fixed it. No XWayland process popped up. Just running `glxinfo` in a terminal triggers it too. Bit weird that a Mesa utility of all things relies on X these days.

Maybe Prism Launcher can use another tool to query GPU info? Since Lutris requires `mesa-utils` for me.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PrismLauncher/PrismLauncher/issues/2032#event-11495108544

@nokia8801, considering that this seems like an issue in `glxinfo`, and the fact that https://forums.opensuse.org/t/where-to-report-xwayland-crash-the-cause-matters-right/172543/2 appears to demonstrate that this might well continue to be a problem, are you certain that this issue has been remediated?

**Comment by nokia8801** [comment]
> @nokia8801, considering that this seems like an issue in `glxinfo`, and the fact that https://forums.opensuse.org/t/where-to-report-xwayland-crash-the-cause-matters-right/172543/2 appears to demonstrate that this might well continue to be a problem, are you certain that this issue has been remediated?

I never had crashes or anything like that. I try to keep my system use native Wayland wherever possible and seeing the XWayland process pop up while launching an instance made me investigate what the problem could be. As both the GUI and the launched Minecraft instance run natively over Wayland, I was curious why XWayland was called at all.

As demonstrated above, `glxinfo` was being used to get info about my GPU, which itself relies on X, which runs over XWayland since I'm on a Wayland session. Removing the `mesa-utils` packages which included `glxinfo` fixed the problem. Now when launching an instance no XWayland process pops up.

Although I might reopen this issue cause enabling MangoHud also results in the XWayland process popping up. Without MangoHud and glxinfo, no XWayland process visible.
