### ISSUE TITLE
MangoHud doesn't work with VulkanMod mod in my Fabric Instance

### ISSUE THREAD

**Issue by Kagukara** [PrismLauncher/PrismLauncher#2033]
### Operating System

Linux

### Version of Prism Launcher

prismlauncher-qt5-bin 8.0-2

### Version of Qt

Qt version 5.15.12

### Description of bug

MangoHud isn't working in my instance that is running Minecraft 1.20.4 and Fabric 0.15.5 with VulkanMod 0.3.9. I have seen MangoHud working in issues on the mods GitHub but it's not working with PrismLauncher. 

MangoHud is enabled in "Settings > Minecraft > Tweaks > Performance > Enable MangoHud".

Launching any other instance works with MangoHud, tested with unmodded Minecraft 1.20.4 and "Simply Optimised 1.20.4-3.1.1".

I have tried adding `mangohud` in any of the Custom Commands and disabling MangoHud in the settings, but that didn't work.

### Steps to reproduce

- Open PrismLauncher (Preferably the same version as in this issue)
- Enable MangoHud by navigating to: Settings > Minecraft > Tweaks > Enable MangoHud
- Close Settings
- Add Instance
  - Create Instance:
    - Filter - Releases - Version: Select 1.20.4
    - Mod Loader - Fabric - Version: Select 0.15.5
- Edit Instance
  - Mods - Download mods
    - VulkanMod
- Launch instance
- Once loaded press your MangoHud keybind or if `no_display` is commented in your config you should see the MangoHud overlay, but you don't.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is not a prism issue as Minecraft is an OpenGL game and the automatic detection used for Mangohub presumes that it will use the OpenGL variant.
If you are using Vulkan mod you can disable that tweak there and use the wrapper command to start the mangohub(https://github.com/flightlessmango/MangoHud#normal-usage)

**Comment by Kagukara** [comment]
> If you are using Vulkan mod you can disable that tweak there and use the wrapper command to start the mangohub(https://github.com/flightlessmango/MangoHud#normal-usage)
https://github.com/PrismLauncher/PrismLauncher/issues/2033#issuecomment-1896153685

As said in this issue, I have tried using `mangohud` in all the Custom Commands, which includes Wrapper command. It still doesn't work.
> I have tried adding `mangohud` in any of the Custom Commands and disabling MangoHud in the settings, but that didn't work.

**Comment by Kagukara** [comment]
@Trial97 Unless you have been able to successfully  use "the wrapper command to start the mangohub(https://github.com/flightlessmango/MangoHud#normal-usage)", I'd love to know what you did to get it working. As `mangohud` works when not using PrismLauncher.

As the "Wrapper command" isn't working as intended, to me this looks like a PrismLauncher issue.
