### ISSUE TITLE
When changing a key, "NONE" appears instead of a letter

### ISSUE THREAD

**Issue by b1owulf** [PrismLauncher/PrismLauncher#2036]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 5.15.12

### Description of bug

When changing the key, "NONE" appears instead of a letter. This happens in absolutely all versions of Minecraft.
Because of this, I can't control, or perform any actions that work when I press a letter key.

### Steps to reproduce

1. Go to any version of Minecraft.
2. Go to control settings.
3. Select any action and press the key with any letter.
4. "NONE" appears instead of the specified letter.

### Suspected cause

I don’t even have an opponent as to why this is happening. This happens in both the X session and the Wayland session.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
I doubt it's related to Prism. Could you test on Mojang's official launcher for example?

**Comment by b1owulf** [comment]
> I doubt it's related to Prism. Could you test on Mojang's official launcher for example?

Yes you are right. Just what should I do? If in a game I press one key in a text field, then two characters are displayed at once. This is most likely why the "NONE" key is assigned.

**Comment by TheKodeToad** [comment]
These issues are for tracking issues/features of Prism Launcher, it's not really the place to get support. We have a #support channel on Discord!

**Comment by megahomyak** [comment]
Hello there! Have you found any resolution for this issue? I'm having the same issue myself on any launcher too
