### ISSUE TITLE
Metadata isn't checked for staleness after migration

### ISSUE THREAD

**Issue by rdrpenguin04** [PrismLauncher/PrismLauncher#204]
### Operating System

EndavourOS Linux, based on Arch

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

When Java 19 is installed, no instances seem to function; they all expect Java 17 or 18, but refuse to work on 19. This is a problem because Arch just updated Java to 19, so... I can't play the game right now :upside_down_face:

### Steps to reproduce

* Install Java 19 (update all packages on Arch)
* Attempt to run an instance
* Cry on the inside

### Suspected cause

Probably out-of-date metadata; that's my only guess

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by rawlingsr** [comment]
I believe that all major distros allow you to install LTS versions of Java, though it may require selecting a different, or additional, package in your package manager.

**Comment by jn64** [comment]
Install `jre17-openjdk`

[Java - ArchWiki](https://wiki.archlinux.org/title/Java)

**Comment by rdrpenguin04** [comment]
Yes, I can definitely install an older version of Java; the main problem is that Prism doesn't support the new version. I could definitely fix this on my end if it was a problem for me, but is 1.19.x really incompatible with Java 19?

**Comment by setibeings** [comment]
Are you able to use Jave 19 with the official launcher?

**Comment by Scrumplex** [comment]
If you migrated from PolyMC, you might need to manually clear your metadata. Go to Prism Launcher's data folder and delete the `meta` folder and `metacache` file.

**Comment by txtsd** [comment]
It crashed when I tried. It worked after deleting the `meta` directory and the `metacache` file.

**Comment by rdrpenguin04** [comment]
Clearing metadata fixed it

**Comment by Scrumplex** [comment]
This should be handled by the migration dialog in #243
