### ISSUE TITLE
Prism keeps crashing - JRE Error

### ISSUE THREAD

**Issue by ClaudiusMinimus** [PrismLauncher/PrismLauncher#2044]
### Operating System

Linux

### Version of Prism Launcher

 Prism Launcher 8.0
Build date: 2023-11-07

### Version of Qt

Qt 5/6

### Description of bug

The Minecraft client crashes without notice
[hs_err_pid16500.log](https://pastebin.com/kb1tm47D)

### Steps to reproduce

Anytime during game playgameplay

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
The log is not accessible, and it doesn't look like a prism issue, better luck on our discord server.
