### ISSUE TITLE
enhanced End-User Security: Sandboxed Launcher/Minecraft

### ISSUE THREAD

**Issue by jkroepke** [PrismLauncher/PrismLauncher#2045]
### Role

Player

### Suggestion

I would like to increase the security on my system

### Benefit

Protection against stealing token from other software

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Windows, Linux and Mac (I guess) are supporting filesystem restriction in different ways.

While Linux uses [mount namespaces](https://man7.org/linux/man-pages/man7/mount_namespaces.7.html) to protect the filesystem, [MacOS](https://developer.apple.com/documentation/security/app_sandbox/) and [Windows](https://blogs.windows.com/windowsdeveloper/2023/06/14/public-preview-improve-win32-app-security-via-app-isolation/) having both an concept of an Sandbox/App Isolation.

Running PrismLauncher inside a sandboxed environment had the benefit that mods are not longer able to scrape the filesystem for credentials, e.g. Discord tokens or browser password manager.

Alternatives:
- Using the Java Security Manage with an policy, but its deprecated in Java 17.

**Comment by Trial97** [comment]
> ### This suggestion is unique
> 
>     * [x]  I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

I do not think users are reading this part at all.
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1146
