### ISSUE TITLE
make prismlauncher have its own config on AUR package

### ISSUE THREAD

**Issue by EysseW** [PrismLauncher/PrismLauncher#205]
### Goal

Don't make Prismlauncher conflict with PolyMC

### Motivation

So I saw my instance wouldn't launch. I thought this was weird because it worked perfectly flawless back on polymc. So I tried to install polymc, but I found the ` polymc and prismlauncher-git are in conflict. Remove prismlauncher-git? [y/N]` .

### Specification

I think it's really weird you guys restrict prismlauncher users from also using polymc. This should not be necessary as prismlauncher lives perfectly alongside multimc and so does polymc.

### Drawbacks

You guys might think it's a good way of expressing your political view, to which I would tell you a game launcher shouldn't have any political statements with it.

### Unresolved Questions

Is it even possible? Maybe there is some technical reason it's not possible, but I highly doubt it.

### Alternatives Considered

You could also make it technically impossible to make them not conflict, but it would be a dick move and not really that much of a solution. Idk, this field is required so I might as well write some bs here.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I haven't actually searched the issue tracker because I am lazy and I don't feel like writing all answers again, sorry

**Comment by EysseW** [comment]
I should also point out I am on archlinux, and I am talking about the conflicts in the AUR, which I assume comes from you guys.

**Comment by EysseW** [comment]
Okay, I should do my research better. I just found out the prismlauncher config is the same as polymc's? Why? Changing topic.

**Comment by theo-donacik** [comment]
Prismlauncher is similarly blocked by PolyMC on Gentoo. While I completely disagree that projects "shouldn't have any political statements", I do wish that I could have both installed side by side temporarily just to ensure that my world files and configurations properly transfer before I uninstall polymc for good.

**Comment by Scrumplex** [comment]
Oops

**Comment by Scrumplex** [comment]
This is not a politically motivated decision. There is an actual technical reason why polymc and prsimlauncher are conflicting with each other: Both are using `/usr/share/jars/NewLaunch.jar` `/usr/share/jars/JavaCheck.jar` so you can't install them side-by-side without conflicts.

**Comment by Scrumplex** [comment]
Of course, it is possible to fix this. But not as part of the AUR package but rather in the source code of Prism Launcher or PolyMC, as they expect the jars to be at a specific location.

**Comment by Scrumplex** [comment]
> Okay, I should do my research better. I just found out the prismlauncher config is the same as polymc's? Why? Changing topic.

This is to allow easy migration for existing PolyMC users. Currently the launcher prefers the PolyMC data directory if it exists. We will add a migration prompt in the future, so that it only uses the new path, but gives users an option to automatically migrate all files.

**Comment by EysseW** [comment]
I see. I guess that's nice. Thanks for answering my question, I understand now!

**Comment by Scrumplex** [comment]
The package conflict has been fixed in #218.

The data directory has also moved with #243
