### ISSUE TITLE
Prism Launcher is unable to contact the Internet (getting news, adding a Microsoft account, adding an instance, etc)

### ISSUE THREAD

**Issue by deko0** [PrismLauncher/PrismLauncher#2074]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0/7.2 (probably still happens with older versions)

### Version of Qt

Qt 6.6.0

### Description of bug

Installing the launcher, the only available language is American English. The news section at the bottom of the launcher do not show any news, it just says they're getting news indefinitely. Trying to add a Microsoft account, the pop-up that's supposed to provide a link and a code just hangs on "Working...". Adding any instance does not work, as the launcher is unable to download any files, and trying to add any modpacks does not work, as there are no modpacks listed anywhere.

### Steps to reproduce

- Be on a network that supports IPv6 (in this case, Starlink);
- Have IPv6 enabled and running in your network adapter's settings;
- Install Prism Launcher and try doing any of the above things (changing your language, adding an instance, adding an account): they won't work. Or at least they didn't in my case.

### Suspected cause

I suspect it could be IPv6 connectivity being turned on, since as soon as it was turned off, everything was fixed.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### More info

This issue did not happen on my own computer, nor I could test it on mine because I do not have IPv6 connectivity with my ISP. I was helping a friend figure this out. We tried restarting his router, and his computer. We tried changing Prism versions, and I tried changing the User Agent (just in case that was the issue). My last idea was turning off IPv6, which fixed the issue immediately. My friend is not very tech savvy, so I decided to report this here myself. 
I could not find any mention of this issue as a separate instance anywhere in this github, but I may just be blind, pardon me for that.

**Comment by Trial97** [comment]
Does the portable version have the same issue?

**Comment by MCLP2005** [comment]
Just checked - It's not the case with the portable version. The installed version will just show the loading bar with no progress after about a quarter of the bar.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/47244747/e28f7a0f-c118-4e79-8f7d-a96e8ec6d4af)

Windows version: 22H2 Build 19045.3996
Qt: 6.6.0
Prism Launcher build date: 2023-11-07

**Comment by MCLP2005** [comment]
I also tested in the latest development build: same problem.

Windows version: 22H2 Build 19045.3996
Qt: 6.6.1
Commit: 5d223f6f9359c7b9017583c13c5f538032380b73

**Comment by deko0** [comment]
> Does the portable version have the same issue?

i'm very sorry, I didn't get any notifications from github on my mail about you replying to this... I'll test it as soon as I can, though I imagine MCLP's could be enough

**Comment by Trial97** [comment]
If the portable version works try reinstalling prism:
- completely uninstall it 
- make sure that all program files associated are removed (not the instances but the files that are found at the install location)
- after you make sure prism is uninstalled install it again

**Comment by deko0** [comment]
> If the portable version works try reinstalling prism:
> 
> * completely uninstall it
> * make sure that all program files associated are removed (not the instances but the files that are found at the install location)
> * after you make sure prism is uninstalled install it again

I had already tried this previously, i forgot to add that to the things I had tried.

**Comment by MCLP2005** [comment]
Tried this, still same issue. Also tested again with the portable version: It seems like the portable version is now doing similar to the installed one. Sometimes it'll work for a few seconds and then it looses the connection again. Seems to be the case for both: portable and installed.

**Comment by MCLP2005** [comment]
Just thought: might be caused by changes in the windows insider preview. Can someone maybe test that theory?

**Comment by agaring** [comment]
Hi there, I had a very similar issue myself and my own suspicion is that this is more of a LAN/network issue.
To be precise, I suspect your Router/Box(/whatever you are using to get internet) is at cause and being borked.

I tried various methods without success : 
-  complete reinstall of prism
- disconnecting my Ethernet cable
- restarting my computer

Restarting my Box fixed this issue right away.
Could be a possible solution.

**Comment by MCLP2005** [comment]
Hi again,
I also tried restarting my router, but for me, it didn't work. Still the same.
It might be a possible solution for some cases, but didn't work for me.

**Comment by MCLP2005** [comment]
Edit: did work on second attempt. But may be the case, it was the update. Just updated Prism Launcher.
So, it seems to work in version 8.2. At least works for me. Maybe someone can confirm?

**Comment by MCLP2005** [comment]
Edit: Login works, but the MSA account is being added in offline mode and can't connect. So playing on servers is still difficult.

**Comment by lutravurr** [comment]
im having this exact same issue

**Comment by MCLP2005** [comment]
Just wanted to add: I have the issue with IPv4, so I think it's not an IPv6 problem.

**Comment by MCLP2005** [comment]
Still happens in 8.2.

**Comment by MCLP2005** [comment]
Quickly made a video of what happens and attached the current log file. Hope, this can help

[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/15066331/PrismLauncher-0.log)

https://github.com/PrismLauncher/PrismLauncher/assets/47244747/767f86ba-55d3-40e5-97a1-7d55f4d97c36

**Comment by MCLP2005** [comment]
Checked my network connection and disabled IPv6: It is related to IPv6. 
So: maybe reconfiguring the router may help with that.

Also: I had IPv6 and IPv4 active. So one of my theories is as follows:
1) The Launcher tries to connect via IPv6
2) my router cannot bridge IPv6 Packets to IPv4, but the other way around it's possible (We have a IPv4 connection at home)
3) The network packets get dropped
4) PrismLauncher doesn't notice that and therefore doesn't switch to IPv4.
And that's one of two theories. 
The other theory is that PrismLauncher can't make the decision if it should use IPv4 or IPv6

Maybe someone can check, if it works with only IPv6 active in windows network device settings. @deko0 are you still on this?

**Comment by khankul** [comment]
I have commented on #1248, reporting the same issue. Writing here to let you know that toggling IPv6 did nothing to remedy the issue in my case.

**Comment by deko0** [comment]
> Checked my network connection and disabled IPv6: It is related to IPv6. So: maybe reconfiguring the router may help with that.
> 
> Also: I had IPv6 and IPv4 active. So one of my theories is as follows:
> 
>     1. The Launcher tries to connect via IPv6
> 
>     2. my router cannot bridge IPv6 Packets to IPv4, but the other way around it's possible (We have a IPv4 connection at home)
> 
>     3. The network packets get dropped
> 
>     4. PrismLauncher doesn't notice that and therefore doesn't switch to IPv4.
>        And that's one of two theories.
>        The other theory is that PrismLauncher can't make the decision if it should use IPv4 or IPv6
> 
> 
> Maybe someone can check, if it works with only IPv6 active in windows network device settings. @deko0 are you still on this?

hey i have been off this website for a while, my friend (who had the problem) switched ISPs and the problem is gone, so.. i think it was starlink itself causing issues?

**Comment by Trial97** [comment]
Yep Starlink was reported blocking the APIs
