### ISSUE TITLE
per-instance java versions

### ISSUE THREAD

**Issue by benjamin051000** [PrismLauncher/PrismLauncher#2078]
### Goal

Be able to specify java version and args per-instance rather than globally.

### Motivation

You can't run instances that require a java version different than the one you selected. This causes issues when running older modpacks alongside newer ones.

### Specification

Move the java tab to a tab/entry in the instance settings where it can be applied on a per-instance basis.

### Drawbacks

Not that I know of. Perhaps compat issues?

### Unresolved Questions

Are there compatibility issues with "hotswapping" java versions? 

### Alternatives Considered

nope

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
You can already do that: Select Instance> Edit>Settings>Java

**Comment by benjamin051000** [comment]
Oh! It's under settings. I totally missed that. Thanks!
