### ISSUE TITLE
ftb

### ISSUE THREAD

**Issue by rrdarkenzede** [PrismLauncher/PrismLauncher#2082]
### Version of Prism Launcher

La fonction importation de l'app FTB ne fonctionne pas.
Et aussi votre launcheur est incroyable continué comme ça. 

### Version of Qt

8.0.0

### Description of bug

BUG FTB

### Steps to reproduce

BUG

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
We only accept issues written in English.

If you can't write English well:
https://www.deepl.com / https://translate.google.com/

**Comment by Trial97** [comment]
Also, more detail would help: what doesn't work exactly?

**Comment by Aces-and-Jacks** [comment]
Something about FTB import feature?

**Comment by Trial97** [comment]
Closing this as there were no follow-ups.
Please feel free to add more information and I will reopen it.
