### ISSUE TITLE
[FEATURE] Sort by Client/Server side in Mods menu

### ISSUE THREAD

**Issue by Beethoven-n** [PrismLauncher/PrismLauncher#2083]
### Role

I'm creating a modpack for a server my friends play on.

### Suggestion

Similarly to how you can sort by name, date, and enabled status, I'd like to be able to sort mods by whether they are client or server-side.

### Benefit

I could easily disable all client-side mods before exporting a release of my modpack. This would prevent server crashes and having to manually figure out which mods are client-side to remove them.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

#1568 is similar, but asks for a change to the mod downloader, where I'd simply like a sort order on the Mods list for the current instance.

**Comment by Trial97** [comment]
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/962
