### ISSUE TITLE
Updating Resourcepack

### ISSUE THREAD

**Issue by RealmKebab** [PrismLauncher/PrismLauncher#2085]
### Role

removes the hassle of going thru links

### Suggestion

make it possible to update resourcepacks whilst the game isn't booted on

### Benefit

once again, this removes the hassle of links

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/1207
