### ISSUE TITLE
Mod Check for Update Error

### ISSUE THREAD

**Issue by 2568176665** [PrismLauncher/PrismLauncher#2086]
### Operating System

Windows

### Version of Prism Launcher

8.0

### Version of Qt

6.6.0

### Description of bug

The automatic update process for mods within an instance will stop at the second step when checking for updates. If I manually click "Stop" before reaching the second step, the program will crash.
lastlog：https://mclo.gs/uudpulb

### Steps to reproduce

PrismLauncher-Windows-MSVC-Portable-8.0.zip
1. Update all the mods in the instance by selecting them all.
2. Click "Cancel" when prompted with metadata not found.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This most probably was solved by: https://github.com/PrismLauncher/PrismLauncher/pull/1694
Can you try to reproduce this using the nightly builds:
You can download unstable builds [here](https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop).

  

>   :warning: Caution
>     Unstable builds have more bugs and are therefore more likely to break! By using the latest commit you are using software which has not been properly tested. For this reason we recommend using Portable or AppImage builds, or least making a backup.

**Comment by 2568176665** [comment]
The program is working fine now.Thank you
