### ISSUE TITLE
Create `iconthemes` folder

### ISSUE THREAD

**Issue by RuiNtD** [PrismLauncher/PrismLauncher#209]
### Role

I want to customize Prism Launcher

### Suggestion

Prism Launcher should create the `iconthemes` folder

### Benefit

The folder isn't created by default, which can create confusion for new users

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The `iconthemes` folder is used to load custom icons.

**Comment by lynrayy** [comment]
You already can load custom icons

**Comment by RuiNtD** [comment]
> You already can load custom icons

Yes, but currently the `iconthemes` folder needs to be manually created by the user. I'm suggesting that Prism Launcher should automatically create the folder, so the user knows where custom icons go.

**Comment by lynrayy** [comment]
What is "iconthemes" at all? I'm just add new icons in launcher icons folder (when choosing icons there are add icon button)

**Comment by RuiNtD** [comment]
> What is "iconthemes" at all? I'm just add new icons in launcher icons folder (when choosing icons there are add icon button)

It allows you to customize the UI icons and default instance icons.

**Comment by lynrayy** [comment]
>**It allows you to customize the UI** icons and default instance icons.
Oh, didnt know about UI. Sounds cool
