### ISSUE TITLE
Prism Launcher is unable to detect the java version which installed by homebrew

### ISSUE THREAD

**Issue by EchoEllet** [PrismLauncher/PrismLauncher#2092]
### Operating System

macOS

### Version of Prism Launcher

8.0

### Version of Qt

6.6.0

### Description of bug

Prism Launcher is unable to detect the java version which installed by homebrew and already added to the environment variable path in `.zshrc`
using
`export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"`

<img width="963" alt="image" src="https://github.com/PrismLauncher/PrismLauncher/assets/73608287/35dc4ba8-88f1-450b-9411-564adbcb0965">

But I can use the path manually (`/opt/homebrew/opt/openjdk@17/bin/java`):

<img width="953" alt="image" src="https://github.com/PrismLauncher/PrismLauncher/assets/73608287/a8fa0d36-d77b-46db-ab06-500a4470b970">

however I'm not big fan of hardcoded things and I don't think anyone should hardcode such things:

### Steps to reproduce

1. Install Prism launcher using `brew install --cask --no-quarantine prismlauncher`
2. Install openjdk@17 using `brew install openjdk@17`
3. Add it to your `.zshrc` using `# Java 17 (Open JDK)
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"`
4. Try to auto detect java version in Prism launcher in the settings

### Suspected cause

It might because I installed the launcher and openjdk@17 using home-brew
or it because of my shell or something like that

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by akasnowmaaan** [comment]
I'm having the same issue - every time I restart Prism, I have to select the Java version I have installed. 
This only started happening recently, within the past few months, after running flawlessly for over a year.

MacOS Sonoma 14.2.1, Macbook M2 Pro, and a Zulu 17 Java install. Most recent Prism update.

**Comment by EchoEllet** [comment]
> I'm having the same issue - every time I restart Prism, I have to select the Java version I have installed. This only started happening recently, within the past few months, after running flawlessly for over a year.
> 
> MacOS Sonoma 14.2.1, Macbook M2 Pro, and a Zulu 17 Java install. Most recent Prism update.

I also facing the same issue in IntelliJ IDEA, I'm not sure if this problem is related to homebrew or some local configurations

**Comment by NwE0kmCE** [comment]
I am also having this issue! Still have not found a way to get Prism to detect my OpenJDK install

**Comment by NwE0kmCE** [comment]
I fixed this with `sudo ln -sfn /opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-17.jdk`

**Comment by EchoEllet** [comment]
> I fixed this with `sudo ln -sfn /opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-17.jdk`

Thanks, I found this in Homebrew cask info when installing `openjdk`

When installing it from other vendors like Amazon corretto, it will manage the symbolic link automatically 

It's looks like this issue is not related to Prism Launcher

it's still helpful to others in case they have the same issue
