### ISSUE TITLE
Modconfig editing

### ISSUE THREAD

**Issue by Arbee4ever** [PrismLauncher/PrismLauncher#2094]
### Role

I play and develop Minecraft Mods.

### Suggestion

I'd like the Instance Editing window to have a Section showing all Mod Configs.

### Benefit

To quickly and easily change mods configs without needing some ingame config editor or manually editing files.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
It's not really possible to have a gui for changing individual options if that's what you want. Why not just open the config folder?

**Comment by TheKodeToad** [comment]
I don't think this is happening
