### ISSUE TITLE
“One of the tasks failed” when checking for mod updates

### ISSUE THREAD

**Issue by fenhl** [PrismLauncher/PrismLauncher#2095]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

Attempting to check for mod updates displays an error window with the text “One of the tasks failed!”. This error did not occur previously, and no further explanation is given. After clicking “OK” in that window, another window with the text “The mod updater was aborted!” is displayed.

### Steps to reproduce

* Create a custom instance with Minecraft 1.20.4 and Fabric 0.15.6
* Download the Fabric API mod (version 0.95.4+1.20.4 at the time of this report)
* Click “Check for Updates”

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TH3N3WN00B** [comment]
Heppens to me too, Windows 11 Pro

![image](https://github.com/PrismLauncher/PrismLauncher/assets/10799738/990dc6a0-41ca-4bf4-9289-6baeffb056c4)

**Comment by antieksi** [comment]
Same issue. I suspect that it is happening because of one of the mods that I have installed.

**Comment by antieksi** [comment]
That's interesting — seems to be an issue on the side of Modrinth. The Mod Menu in-game doesn't show any updates for me.

**Comment by RuiNtD** [comment]
> That's interesting — seems to be an issue on the side of Modrinth.

```
Runninng  "https://api.modrinth.com/v2/version_files/update"
Failed  "https://api.modrinth.com/v2/version_files/update"  with reason  QNetworkReply::ContentAccessDenied
Request failed in previous step: "https://api.modrinth.com/v2/version_files/update"
Error while parsing JSON response from ModrinthCheckUpdate at  0  reason:  "illegal value"
```

Yep. I also get an error when I try to ping that API endpoint using the example in their documentation.
![](https://i.imgur.com/wTRz3XH.png)

**Comment by RuiNtD** [comment]
From the Modrinth Discord's #announcements channel:
> ⚠️ Minor API outage: the `https://api.modrinth.com/v2/version_file/{hash}/update` route is currently returning 403 responses due to an issue with the route. The goal is to get it fixed within a few hours

**Comment by fenhl** [comment]
I would recommend adding more detail to the error message.

**Comment by DrDoctor13** [comment]
+1 to adding a more detailed error message for if the mod updater fails. The current error message is frustratingly vague.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/11695921/fbe44eb4-3367-42a6-a45b-0e159c6a4509)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/11695921/a9d5464e-4f82-40f5-bbf0-5e460a8170c5)

**Comment by mhmatthewhugley** [comment]
> +1 to adding a more detailed error message for if the mod updater fails. The current error message is frustratingly vague. ![image](https://private-user-images.githubusercontent.com/11695921/302137547-fbe44eb4-3367-42a6-a45b-0e159c6a4509.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTUzNTUsIm5iZiI6MTcwNzA5NTA1NSwicGF0aCI6Ii8xMTY5NTkyMS8zMDIxMzc1NDctZmJlNDRlYjQtMzM2Ny00MmE2LWE0NWItMGUxNTljNmE0NTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAxMDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYmY5OGFhYzk2ODM1NmY3OWYzMGM1NDEyZjc3MTdiNTRlMzE5YjJiNjUwZDJhNTE4MmI3NWQ4ZWQ0YmU5OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nQaP3yIvG2PfcoN0mXFEF9EhBGrsJUu9vvgrZP8kog0) ![image](https://private-user-images.githubusercontent.com/11695921/302137554-a9d5464e-4f82-40f5-bbf0-5e460a8170c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTUzNTUsIm5iZiI6MTcwNzA5NTA1NSwicGF0aCI6Ii8xMTY5NTkyMS8zMDIxMzc1NTQtYTlkNTQ2NGUtNGY4Mi00MGY1LWJiZjAtNWU0NjBhODE3MGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAxMDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NGRhNmZlNjEwOTdlZmJjOWU3ZWE0NWFhMzUyZGY0ZjA3YTc4Y2Q5M2E4MmM2YWQ2ZThmYjA0MmE2YzZlMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZwTx6nGFzlejr4mzE0ssqIduXI8cO5lp7THAxVDESVk)

And a button showing the entire log for that error or open whatever log file at the lines that the error starts at.

**Comment by Aces-and-Jacks** [comment]
> > +1 to adding a more detailed error message for if the mod updater fails. The current error message is frustratingly vague. ![image](https://private-user-images.githubusercontent.com/11695921/302137547-fbe44eb4-3367-42a6-a45b-0e159c6a4509.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTUzNTUsIm5iZiI6MTcwNzA5NTA1NSwicGF0aCI6Ii8xMTY5NTkyMS8zMDIxMzc1NDctZmJlNDRlYjQtMzM2Ny00MmE2LWE0NWItMGUxNTljNmE0NTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAxMDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYmY5OGFhYzk2ODM1NmY3OWYzMGM1NDEyZjc3MTdiNTRlMzE5YjJiNjUwZDJhNTE4MmI3NWQ4ZWQ0YmU5OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nQaP3yIvG2PfcoN0mXFEF9EhBGrsJUu9vvgrZP8kog0) ![image](https://private-user-images.githubusercontent.com/11695921/302137554-a9d5464e-4f82-40f5-bbf0-5e460a8170c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTUzNTUsIm5iZiI6MTcwNzA5NTA1NSwicGF0aCI6Ii8xMTY5NTkyMS8zMDIxMzc1NTQtYTlkNTQ2NGUtNGY4Mi00MGY1LWJiZjAtNWU0NjBhODE3MGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAxMDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NGRhNmZlNjEwOTdlZmJjOWU3ZWE0NWFhMzUyZGY0ZjA3YTc4Y2Q5M2E4MmM2YWQ2ZThmYjA0MmE2YzZlMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZwTx6nGFzlejr4mzE0ssqIduXI8cO5lp7THAxVDESVk)
> 
> And a button showing the entire log for that error or open whatever log file at the lines that the error starts at.

Wouldn't that be in the prism launcher log? Since it has to do with the application and not a launched minecraft instance. That should be in the Launcher Root folder under the logs folder.

**Comment by SheanlR** [comment]
after i clicked add instance this happeneds![Image](https://github.com/user-attachments/assets/5a5b930b-d6cf-4f4e-accd-90fa1a03d3c4)
