### ISSUE TITLE
2 Minecraft instances infinite loading screen

### ISSUE THREAD

**Issue by xFr0z3n** [PrismLauncher/PrismLauncher#2096]
### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.3.0

### Description of bug

I launched 2 instances of Minecraft to play splitscreen everything works fine (for example both instances were in a single player world) but as soon as I try to join via LAN I get a infinite loading screen ”logging in“ 

### Steps to reproduce

Launch 2 Minecraft instances and join via LAN

### Suspected cause

I restarted my pc and driver I maybe thought it’s the ram but allocating more didn’t help

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment]
I tried launching two instances on one computer and joined the other instance via LAN. Works if I use two different accounts, however if I use the same account I get `Failed to connect to the server. That name is already taken` which would make sense. Are you using the same account or two different accounts?

**Comment by Aces-and-Jacks** [comment]
Also I just noticed you're using an older version of Prism Launcher. Try using Prism Launcher 8.0 and see if the problem occurs again, since Prism Launcher 5.0 would most likely not be supported.

**Comment by Trial97** [comment]
Please try using the latest version of the launcher before you report an issue(there may be a fix already)
Also, this doesn't look like a prism issue, so closing this for now.
