### ISSUE TITLE
Instance shortcuts

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [PrismLauncher/PrismLauncher#210]
### Role

I create a lot of instances.

### Suggestion

I would like a way to be able to create a shortcut for any instance

### Benefit

So I can quickly launch and play an instance without having to directly open up the launcher

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I would like a way to create a .desktop for an instance so I can launch an instance directly from my application menu withiut needing to open up the launcher.

**Comment by Leo40Git** [comment]
The required command line argument for this already exists (`--launch <instanceID>`). You could make .desktop files manually, but I do agree that having an option for Prism Launcher to create desktop shortcuts would be convenient...

**Comment by glowiak2** [comment]
Made a prototype https://github.com/glowiak2/PolyMC/blob/develop/launcher/InstanceShortcutCreation.cpp

**Comment by Wahx** [comment]
https://youtu.be/ChSsAInTi0Y?t=130 also works on PrismLauncher

**Comment by Den4enko** [comment]
I also propose to add that you can drag the modpack icon from launcher to the desktop or taskbar.

**Comment by Leo40Git** [comment]
I don't think this is possible in Qt?
