### ISSUE TITLE
Add a option to make the launcher minimize automatically when launching a instance

### ISSUE THREAD

**Issue by AtomicLugia** [PrismLauncher/PrismLauncher#2101]
### Role

I tend to minimize the launcher by myself whenever I launch a instance

### Suggestion

A checkbox to enable the launcher to minimize by itself when you launch a instance

### Benefit

May be not a big feature but still nice to have for convenience

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Another checkbox to tell the launcher to pop up after you closed the instance (or when it crashed) would be also nice to have.

**Comment by Aces-and-Jacks** [comment]
Already a thing. Go to settings>Minecraft>Miscellaneous>Close the launcher after game window opens. 

That would minimize the launcher when you launch an instance and when it crashes it'll pop back up

**Comment by Trial97** [comment]
As mentioned this is already there, so closing this.

**Comment by Keemam** [comment]
Late to the party but came across this because i couldn't for the life of me find the setting. I think it would help to put the option in the launcher settings, as it does not affect the behavior of Minecraft, but the launcher.
