### ISSUE TITLE
Download mods filter options doesn't work without clearing the text field

### ISSUE THREAD

**Issue by EchoEllet** [PrismLauncher/PrismLauncher#2102]
### Operating System

macOS

### Version of Prism Launcher

8.0

### Version of Qt

6.6.0

### Description of bug

Download mods filter options doesn't work without clearing the text field, once I change the filter options and click search it doesn't search once again, we need to clear the text field (of search query) and type it once again

https://github.com/PrismLauncher/PrismLauncher/assets/73608287/daafe3cd-b426-41ea-a54c-dd40ab0b59f0

### Steps to reproduce

1. Create a new instance with the latest version of minecraft and a mod loader (fabric or forge)
2.  Edit instance and go to Mods, then click download mods
3. Search for a mod that is not compatible with the current version of minecraft (outdated)
4. Change the filter options to any version and click search, you will notice that the filter options doesn't take affect

A quick way to fix it is to clear the text field and type it again, it will work

### Suspected cause

I'm unfamiliar with this repo and QT in general

Simple fix: to fix this in code, the click search button should check if the filter options has changed, or re search anyway even if the search query didn't changed

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Fixed by: https://github.com/PrismLauncher/PrismLauncher/pull/1728
