### ISSUE TITLE
ATM9 mods getting deleted when trying to update the pack in the launcher

### ISSUE THREAD

**Issue by MrRobsterr** [PrismLauncher/PrismLauncher#2108]
### Operating System

Windows

### Version of Prism Launcher

Prism launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

every time i try to update the atm9 modpack to a newer version it deletes mod files that i think should be getting updated as it's different mods that get deleted in each update. which gives an error when trying to load the game that i don't have the correct mods installed.

this has happened through multiple update versions for me. not just going to a specific update

here is the log from the launcher: https://mclo.gs/k2jCvLK

here is a reddit post i made with a dev of ATM9 speculating a cause: https://www.reddit.com/r/PrismLauncher/comments/1amc8fn/updating_atm9_modpack_deletes_mods_in_the_pack/

### Steps to reproduce

update the atm9 mod pack to a newer updated version

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by oculosdanilo** [comment]
i'm also getting the same errors and when i try to reinstall the deleted mods my minecraft crashes after mod loading

**Comment by Trial97** [comment]
Can you(MrRobsterr) post the prismlauncher logs from when you update the pack?

**Comment by TheKodeToad** [comment]
Is this related to https://github.com/PrismLauncher/PrismLauncher/issues/1023

**Comment by datsme** [comment]
I have the same issue with ATM9 I think it started happening when they launched "Atm9 - No Frills" version. I have suspected (but not sure how to validate) that it is trying to install the "ATM9 - No Frills" version over the regular ATM9. 
I reported this issue on the ATM9 Discord and the response was "this is a known issue" and "switch launcher".
The most helpful was,
 "Make a new instance at the latest version and Copy the "keys.txt" "options.txt" "local" "journeymap" and "saves" files/folders"
So thought I would report that here so the Devs are aware that it is indeed an issue with many people. Unfortunately most players won't take the time to find and signup on Github to report it.  Maybe in the update code the above process/files can be implemented?

**Comment by MrRobsterr** [comment]
> Can you(MrRobsterr) post the prismlauncher logs from when you update the pack?

Trial97 where and how would i find that log? the log i sent is the log in the launcher from when i loaded minecraft after the update and got the error message, is it a different one from that?

**Comment by TheKodeToad** [comment]
We've already received logs from some users and nothing was obvious

**Comment by MrRobsterr** [comment]
> Is this related to #1023

it sounds very similar to that, although i haven't check if it happens on other modpacks as i've only tried atm9

**Comment by mixednutts** [comment]
I believe this issue is also related:

#2111

**Comment by landaro** [comment]
I think I can confirm the timeline mentioned by @datsme, that is the issues began when the No frills version of ATM9 appeared. I have been updating my ATM 9 instance repeatedly in the past through prism 8.0 without hiccups, but now every update atmpt fails in the described manner.

Prism reports some kind of modpack ID and they appear to be distinct for full ATM9 and ATM9 - No Frills, but maybe the modpack to modlist resolution process is broken somewhere?

... Or curseforge has messed up something on their end ... (Though fresh installs of ATM 9 don't appear to affected 🤔 )
