### ISSUE TITLE
[Possible Bug] cannot find libcmark, but cannot install it too?

### ISSUE THREAD

**Issue by XDuskAshes** [PrismLauncher/PrismLauncher#2113]
### Operating System

Linux

### Version of Prism Launcher

Not sure, I'm pretty sure latest.

### Version of Qt

Not sure here either, frankly. Going to assume latest.

### Description of bug

When I try to launch Prism via the command line, this lovely little error pops up:
![Screenshot_20240210_151523](https://github.com/PrismLauncher/PrismLauncher/assets/101196233/e05d6496-2fb1-4ae7-be31-c29c820b0230)

(``prismlauncher: error while loading shared libraries: libcmark.so.0.30.3: cannot open shared object file: No such file or directory`` (this is here for people who can't see the image))

Launching it via anything else gives nothing, as is very expected. I suspected it revolved around the ``cmark`` package, so I ran ``sudo pacman -S cmark`` and still nothing. I checked for ``libcmark`` and just ``cmark`` with ``yay``, and installing ``cmark`` **via ``yay``** then trying to run Prism again returns similarly. I am requesting help out of a simple "I give up."

### Steps to reproduce

Try to run Prism, at least on my machine.

### Suspected cause

``libcmark.so.0.30.3`` missing somewhere, if I had to make a non-vague shot in the dark.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by XDuskAshes** [comment]
**NOTE**: Currently re-installing ``prismlauncher`` from the AUR.

**Comment by Trial97** [comment]
Arch doesn't really like prism: the reinstall should do the trick (you may need to add `--rebuild` flag to your aur helper)

**Comment by Akeianova** [comment]
The problem to me actually seems to be that the latest version of libcmark is 0.31.0.0, which prismlauncher seemingly does not recognize. I have this version installed and that seems to be the issue to me.

**Comment by Trial97** [comment]
Just rebuild prism: prism doesn't recognize the version because when was built it was linked against the old one, and once you updated it the link was broken, that's the reason you need to recompile/rebuild it.
