### ISSUE TITLE
Modrinth version numbers are not parsed correctly

### ISSUE THREAD

**Issue by DrDoctor13** [PrismLauncher/PrismLauncher#2115]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

The mod updater does not catch new versions of mods installed from Modrinth. You can manually go to the Download Mods screen to pull the latest version, but the auto updater will not see it. This does not happen with CurseForge mods.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/11695921/bc9f4baf-5998-4fdb-84a7-491b3a46f746)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/11695921/7674735f-7d91-4feb-8974-306cfa54afad)

### Steps to reproduce

1. Create an instance with an older version of Minecraft (used 1.20.1 in testing)
2. Install a mod from Modrinth for that Minecraft version (used Fabric API 0.91.1+1.20.1 in testing)
3. Change the Minecraft version to the latest one.
4. Check for updates - no updates will be found
5. Install an older version of the same mod from CurseForge
6. Check for updates - it will find the newest version

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is an issue with modrinth API, if you use curseforge mods this will work.
See https://discord.com/channels/734077874708938864/734084055225597973/1206305646337593465

**Comment by glektarssza** [comment]
> This is an issue with modrinth API, if you use curseforge mods this will work. See https://discord.com/channels/734077874708938864/734084055225597973/1206305646337593465

Can we get a link other than a Discord link, @Trial97? Or a screenshot? That link goes nowhere unless you're in whatever server it points to.

**Comment by Trial97** [comment]
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/a738e3f0-67b5-417f-93a9-2b88dc5a2337)
And here is the invite link:https://discord.com/invite/EUHuJHt

**Comment by Trial97** [comment]
Should be solved now:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/9621b428-4c15-424d-a3ed-7a13bddea026)
So closing this as complete.
