### ISSUE TITLE
Link to the modpack on CurseForge in the CurseForge tab

### ISSUE THREAD

**Issue by Svish** [PrismLauncher/PrismLauncher#2119]
### Role

I play on and host a modded minecraft server

### Suggestion

I want an easy way to get to the webpage for the modpack on CurseForge

### Benefit

So that I can easily find and download the server pack that is hosted as Additional Files

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

When I edit an instance, there's a CurseForge-tab where I can select version and "Update pack". This is great, but I also need to update my standalone server, which means I currently need to open up my browser, search for the pack, find the correct version, go to additional files, and then finally download the server-pack.

Would be great if Prism Launcher could reduce those steps. In increasing level of reduction:

1. Make the name of the pack a link to the pack on CurseForge.  
In my current case of "All the Mods 9 - No Frills", that would be https://www.curseforge.com/minecraft/modpacks/all-the-mods-9-no-frills
2. Make the version of the pack a link to the version of the pack on CurseForge.  
In my current case of "0.1.6", that would be https://www.curseforge.com/minecraft/modpacks/all-the-mods-9-no-frills/files/5102062
3. Just straight up show me the "Additional Files" belonging to the selected version within the CurseForge tab.
In my current case, instead of only showing the "Changelog", it would show me the "Additional Files", with links to download them.

Just having 1 would be a great help, 2 would also be super great. 3 would probably go a bit far and be a bit unnecessarily complicated.

<img width="720" alt="image" src="https://github.com/PrismLauncher/PrismLauncher/assets/142162/3b8caf0e-7180-4c0e-b8b8-2f00c137461d">

**Comment by Trial97** [comment]
Sounds like https://github.com/PrismLauncher/PrismLauncher/issues/2097 is already implemented on develop.
And if you say that the locations differ I'm pretty sure that is hard to get: aka the link to version file

**Comment by Svish** [comment]
Ah, cool, tried to search for duplications, but guess we've used different lingo. I'll just watch for next release then. 😊
