### ISSUE TITLE
Cat Overlay Breaks Small Box

### ISSUE THREAD

**Issue by Desoroxxx** [PrismLauncher/PrismLauncher#212]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

The cat button breaks the rendering of small boxes behind the instances name:

![image](https://user-images.githubusercontent.com/82710983/197281761-27278ad9-c394-4887-af6c-95a2f062ee8f.png)

![image](https://user-images.githubusercontent.com/82710983/197281799-92d7e284-6152-4989-9208-956dfe7c4f7d.png)

It has always done that just never done a bug report

### Steps to reproduce

Press the cat button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
has always been the case. Will probably disappear with #30

**Comment by TheKodeToad** [comment]
Fixed by #1127
