### ISSUE TITLE
Add instances that connect directly to the server via QuickPlay

### ISSUE THREAD

**Issue by Lolothepro** [PrismLauncher/PrismLauncher#2124]
### Role

Minecraft player

### Suggestion

Add instances that connect directly to the server via QuickPlay

### Benefit

To quickly connect to a server when you have an instance for a specific server

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

(Like a Hypixel instance, which connects directly to mc.hypixel.net)

**Comment by Trial97** [comment]
Do you mean: Select Instance>Edit>Settings>Miscellaneous>Set server to join on launch ?
Ps that doesn't work on the latest versions see: https://github.com/PrismLauncher/PrismLauncher/pull/1164

**Comment by Lolothepro** [comment]
> Do you mean: Select Instance>Edit>Settings>Miscellaneous>Set server to join on launch ? Ps that doesn't work on the latest versions see: #1164

oh yeap
(but there's no open feature request on Github?)
