### ISSUE TITLE
Can't click and drag scrollbar in text viewers

### ISSUE THREAD

**Issue by JasonHorkles** [PrismLauncher/PrismLauncher#2125]
### Operating System

Windows

### Version of Prism Launcher

8.0

### Version of Qt

6.6.0

### Description of bug

When trying to scroll by clicking and dragging the scrollbar in text viewers such as logs/crash reports/etc, it doesn't actually move the scrollbar with your mouse

### Steps to reproduce

1. Open an instance settings page
2. Navigate to the logs
3. Try clicking and dragging on the scrollbar

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
What do you mean by it doesn't move it with your mouse?

https://github.com/PrismLauncher/PrismLauncher/assets/57493648/6cb1953d-de7e-43b6-ad01-82a4dbf523fe

**Comment by JasonHorkles** [comment]
Honestly forgot I'm using a theme lmao
Looks like it's an issue with the theme I'm using
