### ISSUE TITLE
Prisim Launcher crashes while using minecraft 1.20.1 Linux

### ISSUE THREAD

**Issue by Orlando189** [PrismLauncher/PrismLauncher#2133]
### Operating System

Linux

### Version of Prism Launcher

prisim 8.0

### Version of Qt

Qt 5.15.10.

### Description of bug

Minecraft version: 1.20.1
Mod Loader: Fabric Loader 
Mods: Fabric API, Axiom
system: Linux (unbutu 20.04) Operating system: zorion os
Description of bug: When i click launch it opens the minecraft log and opens a window where it downloads the requierd library files for fabric. It gose from 80% done to 53% done to 93% and the to 100% done but doesn't open minecraft.

log:  Native libraries:

Mods:
  [✔] Axiom-2.4.2-for-MC1.20.1
  [✔] fabric-api-0.92.0+1.20.1

Params:
  --username  --version 1.20.1 --gameDir /home/orlando/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.20.1/.minecraft --assetsDir /home/orlando/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 92

Exception caught from launcher
java.lang.ClassNotFoundException: net.fabricmc.loader.impl.launch.knot.KnotClient
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:94)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:86)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR
Process exited with code 2.

### Steps to reproduce

<html><body><ul>
	<li><a href="https://modrinth.com/mod/P7dR8mSH">Fabric API</a></li>
	<li><a href="https://modrinth.com/mod/N6n5dqoA">Axiom</a></li>
</ul></body></html>

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This doesn't look like a prism issue at all and also it works on my machine, so I'm tempted to close this. 
But can you provide the full logs:
Please send logs! The recommended site to upload your logs to is [mclo.gs](https://mclo.gs/).
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/4e4fe260-d891-4ab2-b928-1ac3ed89ae53)

**Comment by Trial97** [comment]
Closing this as the logs were not provided
