### ISSUE TITLE
Prism Launcher consistently kills X, sometimes Wayland too.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [PrismLauncher/PrismLauncher#2139]
### **Operating System**

[`cpe:/o:opensuse:tumbleweed:20240131`](https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-NET-x86_64-Snapshot20240131-Media.iso?mirrorlist)

### **Version of Prism Launcher**

8.0

```PS1
flatpak install 'https://dl.flathub.org/repo/appstream/org.prismlauncher.PrismLauncher.flatpakref' && `
flatpak update 'app/org.prismlauncher.PrismLauncher/x86_64/stable' --commit=369388b1bb5a75de1e5181d85810ae42c0302fb344eea63511bfe9326d06f146
```

### **Version of Qt**

https://github.com/qt/qtbase/releases/tag/v5.15.10-lts-lgpl

### **Description of bug**

Firstly, the display freezes. Soon after, it becomes black. Then, the PC fans momentarily cease to operate, and the display becomes artefacted as the fans resume:

1.	> ![image](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/e9ddd61c-ba3b-4fa4-83ed-e5b7bb6304d1)
1.	> ![image](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/9f7037b1-7100-4d09-bcc4-f72a79e1d250)

It always eventually crashed the system.

...except once, the latest time. This latest time, the behaviour was very strange. Per https://bugzilla.opensuse.org/show_bug.cgi?id=1220043#c0:

<blockQuote>

1. The X server crashed (see the last line of the log at https://mclo.gs/H1b3oft).
1. Discord and Prism became 10% opacity.
1. When I logged out, I remained in TTY3 rather than TTY2, and switching manually to TTY2 demonstrated that the handover hadn’t occurred. I had to use TTY4 to systemctl reboot.

</blockQuote>

### **Steps to reproduce**

Play the game for some time.

### **Suspected cause**

The video driver, because although the system responds (<kbd>Alt</kbd>+<kbd>SysReq</kbd>+<kbd>B</kbd> performs `systemctl reboot`) <kbd>Alt</kbd>+<kbd>F3</kbd> doesn't switch from the display server to a TTY. `journalctl --boot=-1 -e` produces:

1.  [+2024-02-18T16:08:24+00:00.txt.MD](https://github.com/PrismLauncher/PrismLauncher/files/14333262/%2B20240218T160824%2B0000.txt.MD)
1.  [+2024-02-19T15:00:03+00:00.txt.MD](https://github.com/PrismLauncher/PrismLauncher/files/14333249/%2B20240219T150003%2B0000.txt.MD)

...which contain quite a notable stack trace pertaining to what I describe, although it's actually XWayland which crashes there. However, this also occurs on X11, and the effect upon the system is identical.

### **This issue is unique**

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PrismLauncher/PrismLauncher/issues/2139#issue-2141081956

https://forums.opensuse.org/t/where-to-report-xwayland-crash-the-cause-matters-right/172543/1

**Comment by Trial97** [comment]
And you are sure it is Prism Launcher's fault? Like did you try to reproduce this using other launchers(atlauncher,modrinth launcher)?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PrismLauncher/PrismLauncher/issues/2139#issuecomment-1951815873

@Trial97, I'm solely as certain as the evidence demonstrates, which is a significant but unverified *correlation*. I've not attempted to replicate the bug using other launchers. I shall evaluate them, and report to here the results. It's another excuse to play, after all. However, note that as https://flathub.org/apps/com.atlauncher.ATLauncher#:~:text=in%20the%20directory-,legacy%20windowing%20system,-Uses%20a%20legacy and https://github.com/flathub/flathub/pull/4950#ref-issue-1838041992 demonstrate, these aren't directly comparable in certain manners (providing diagnostic advantages and disadvantages).

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PrismLauncher/PrismLauncher/issues/2139#issuecomment-1951815873

@Trial97, I've uploaded a new log from a crash a few minutes ago (https://github.com/PrismLauncher/PrismLauncher/files/14333249/%2B20240219T150003%2B0000.txt.MD). It's still from Prism Launcher, but this time `journalctl` mentions Prism by name at the start of the log, so it may assist introspection somewhat.

**Comment by Trial97** [comment]
Just to make sure: when you are referring to that prism killing X/Wayland are you meaning that you have only prismlauncher open and no other application open(not even minecraft) and then the display manager crashes?
If the crash happens only with minecraft open then it may be minecraft or a mod that crashes your system. Did you try with another launcher to see if you can reproduce it or not?
P.S. Nothing from your logs suggests that prism is crashing your system. Is more likely that the instance you are trying to play is too big: has too many mods or you allocated too many resources for it making the other applications( like X server or the wayland compositor) unable to respond fast enough causing the crash:
`Key repeat discarded, Wayland compositor doesn't seem to be processing events fast enough!$`

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PrismLauncher/PrismLauncher/issues/2139#issuecomment-1959037194

@Trial97, I've only allocated 16 GiB of my maximum 30.5 available GiB of RAM. There's no way Wayland or XWayland would use 16 GiB, surely? However, I have noticed https://github.com/ValveSoftware/Proton/issues/7136#issue-1915780665 and have had a crash playing https://store.steampowered.com/app/236390/War_Thunder/ via https://github.com/ValveSoftware/Proton/releases/tag/proton-8.0-5c, so perhaps https://gitlab.freedesktop.org/mesa/mesa/-/issues/10645 is of some relevance?

Could I ask you to test

```sh
flatpak install https://dl.flathub.org/repo/appstream/org.prismlauncher.PrismLauncher.flatpakref && `
flatpak update app/org.prismlauncher.PrismLauncher/x86_64/stable --commit 369388b1bb5a75de1e5181d85810ae42c0302fb344eea63511bfe9326d06f146
```

on `cpe:/o:opensuse:tumbleweed:20240220` to reproduce it? I don't have another machine I can easily test it on with similar hardware.

**Comment by Trial97** [comment]
Sorry, but I'm unable to reproduce your issue at all(also I do not have `cpe:/o:opensuse:tumbleweed:20240220`).
And this may not be RAM related but CPU related.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PrismLauncher/PrismLauncher/issues/2139#issuecomment-1959671376

@Trial97, does Prism possess control over CPU resource allocation to any extent which might interfere with OS operation? I don't see any relevant configuration options via its GUI. I believed that was the sole purview of the OS unless deliberately and meticulously intercepted. I've a 12-thread "AMD Ryzen 5 7600X 6-Core Processor", so I doubt hardware is a bottleneck here.

**Comment by Trial97** [comment]
The only control that Prism has over the spawned minecraft process is if is running or not.
Did you test with other launchers?

**Comment by Ceikry** [comment]
FWIW, though I likely don't have the same hardware as OP, I also use OpenSUSE Tumbleweed with upstream MultiMC and have never had issues.

**Comment by DioEgizio** [comment]
> sometimes Wayland too. 

Prism can't kill Wayland as Wayland is just a protocol

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PrismLauncher/PrismLauncher/issues/2139#issuecomment-1976442762

@DioEgizio, as is X. My specific packages are, for Wayland:

1.	https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/kwin5-5.27.10-2.3.x86_64.rpm
1.	https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/kwayland-5.115.0-1.2.x86_64.rpm
1.	https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/kwayland-integration-5.27.10-1.3.x86_64.rpm

...and for X:

1.	```sh
	zypper info --type pattern 'x11'
	```
	
1.	<blockQuote>
	
	```log
	Loading repository data...
	Reading installed packages...
	
	
	Information for pattern x11:
	----------------------------
	Repository      : Main Repository (OSS)
	Name            : x11
	Version         : 20200505-47.1
	Arch            : x86_64
	Vendor          : openSUSE
	Installed       : Yes
	Visible to User : Yes
	Summary         : X Window System
	Description     : 
	    The X Window System provides the only standard platform-independent networked graphical window system bridging the heterogeneous platforms in today's enterprise: from network servers to desktops, thin clients, laptops, and handhelds, independent of operating system
	    and hardware.
	Contents        : 
	    S  | Name                       | Type    | Dependency
	    ---+----------------------------+---------+------------
	    i+ | patterns-base-base         | package | Required
	    i+ | patterns-base-x11          | package | Required
	    i+ | xf86-input-libinput        | package | Required
	    i+ | xorg-x11-fonts-core        | package | Required
	    i+ | xorg-x11-server            | package | Required
	    i+ | dejavu-fonts               | package | Recommended
	       | gdm                        | package | Recommended
	    i+ | google-noto-sans-fonts     | package | Recommended
	       | lightdm                    | package | Recommended
	    i  | patterns-base-x11_enhanced | package | Recommended
	    i+ | sddm                       | package | Recommended
	       | sddm-qt6                   | package | Recommended
	    i+ | tigervnc                   | package | Recommended
	    i+ | x11-tools                  | package | Recommended
	    i+ | xdmbgrd                    | package | Recommended
	    i+ | xf86-input-vmmouse         | package | Recommended
	    i+ | xf86-input-wacom           | package | Recommended
	    i+ | xorg-x11-Xvnc              | package | Recommended
	    i+ | xorg-x11-driver-video      | package | Recommended
	    i+ | xorg-x11-essentials        | package | Recommended
	    i+ | xorg-x11-fonts             | package | Recommended
	    i+ | xorg-x11-server            | package | Recommended
	    i+ | xorg-x11-server-extra      | package | Recommended
	    i+ | xterm                      | package | Recommended
	    i+ | xtermset                   | package | Recommended
	
	```
	
	</blockQuote>

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PrismLauncher/PrismLauncher/issues/2139#issue-2141081956

I'm going to close this, because as https://discussion.fedoraproject.org/t/random-indefinite-system-hang/110020/1#related-issues-3 appears to demonstrate, this is probably an underlying issue.
