### ISSUE TITLE
Allow grouping loader mods into separate categories

### ISSUE THREAD

**Issue by mudkipdev** [PrismLauncher/PrismLauncher#2140]
### Role

I like creating and playing large modpacks with 100+ mods

### Suggestion

Allow you to organize loader mods, resource/texture packs, and shader packs into multiple groups like you can with instances, they could be collapsible so it's easier to see a group of mods at a time

### Benefit

Easier to group fix, QoL, content and other types of mods into separate categories.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I don't know how this would be done but the file hash would probably have to be saved in an instance settings file somewhere

**Comment by Trial97** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1431 or https://github.com/PrismLauncher/PrismLauncher/issues/154
