### ISSUE TITLE
BTA Languagepacks

### ISSUE THREAD

**Issue by AndusDEV** [PrismLauncher/PrismLauncher#2144]
### Role

I think it would be easier for people to add languages to BTA

### Suggestion

Add another category in Console Window specifically for BTA versions to add languages to the language folder (Like Screenshots, mods, etc.)

### Benefit

It's just a quality of life feature

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TayouVR** [comment]
can you be more specific? what are you referring to when you say "BTA", and which languages folder do you mean? As far as I'm aware languages in minecraft are provided by resourcepacks. None of my minecraft instances have a folder for languages.

**Comment by mudkipdev** [comment]
Better than Adventure is a mod for b1.7.3, it's way too niche to have support for it in this launcher

**Comment by AndusDEV** [comment]
@mudkipdev Maybe you're right

**Comment by Trial97** [comment]
You are 100 percent right: this looks like it is `too niche to have support for it in this launcher`.

**Comment by Luis909551** [comment]
spanish pls, im in spain
