### ISSUE TITLE
Unable to connect via LAN without InterNet connection due to initially mandatory authentication server poll.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [PrismLauncher/PrismLauncher#2145]
### Operating System

Linux

### Version of Prism Launcher

8.0

### Version of Qt

5.15.10

### Description of bug

As https://gaming.stackexchange.com/a/406240/225782 explains, attempting to join a LAN game without an internet connection causes it to state that it is unable to connect to the authentication servers, whereas solely one user being connected to the internet causes it to state that the session is invalid. Noteworthily, if I use mods when I induce this error, I see a third message: "The authentication are currently down for maintenance".

Regardless of whether using any modifications or not, an internet connection on both client and host is necessary to connect, yet once client and host are connected, the internet connection is unnecessary.

An Internet connection shouldn't be necessary when connecting via LAN.

### Steps to reproduce

1.	Install Prism Launcher:

	1.	On the Windows host, `winget install --id=PrismLauncher.PrismLauncher -e`.
	1.	On the cpe:/o:opensuse:tumbleweed:20240131 client, `flatpak install https://dl.flathub.org/repo/appstream/org.prismlauncher.PrismLauncher.flatpakref && flatpak update app/org.prismlauncher.PrismLauncher/x86_64/stable --commit 369388b1bb5a75de1e5181d85810ae42c0302fb344eea63511bfe9326d06f146`.

1.	*	> Invalid session
	
		*	**Windows**
		
			1.	*Enable* InterNet connection.
			1.	Enable LAN connection.
			1.	Host.

		*	**cpe:/o:opensuse:tumbleweed:20240131**
		
			1.	*Disable* InterNet connection.
			1.	Enable LAN connection.
			1.	Connect.
	
	*	To see
	
		> Unable to connect to authentication server
	
		Disable LAN on both devices.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PrismLauncher/PrismLauncher/issues/2145#issue-2143007403

I've filed https://bugs.mojang.com/browse/MC-268676 upstream because it's reproducible on https://launcher.mojang.com/download/Minecraft.tar.gz too.

**Comment by Trial97** [comment]
So to summarize this is not an issue with the launcher but Minecraft itself, right?
Can we close this then?
