### ISSUE TITLE
Mangohud toggle greyed out

### ISSUE THREAD

**Issue by Enchilada5528** [PrismLauncher/PrismLauncher#2147]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0 (Flatpak)

### Version of Qt

Qt 5.15.10

### Description of bug

I installed flatpak Prism Launcher 8.0, then mangohud from its github page under releases (version 0.7.1). I configured MangoHud. Then I opened Prism Launcher to enable MangoHud, but the MangoHud toggle was greyed out. ![Screenshot from 2024-02-19 20-47-11](https://github.com/PrismLauncher/PrismLauncher/assets/160567240/2bdf972f-0d3f-4eb7-aab8-b5193f3a8b17)
I've tried compiling MangoHud manually and installing the "system package" version of MangoHud. I've tried adding "MangoHud --dlsym" as a wrapper command, which created a new error.
![Screenshot from 2024-02-19 20-46-46](https://github.com/PrismLauncher/PrismLauncher/assets/160567240/7e6d01ca-a4b0-4b43-9917-adb5bb1401ac)
I've also tried adding this: "xdg-config/MangoHud:ro" to Prism Launcher via FlatSeal, and doing a similar thing using the command line. 
I've looked through all of the previous related issues on here but wasn't able to implement anything that solved my issue.

### Steps to reproduce

1. Install Prism Launcher & add instances
2. Install MangoHud from GitHub
3. Go to Prism Settings
4. "Enable MangoHud" is greyed out

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Enchilada5528** [comment]
In case anyone finds this thread in the future and is having the same issue, here's how I solved this: I went [here](https://flathub.org/apps/org.freedesktop.Platform.VulkanLayer.MangoHud), installed MangoHud branch 21.08 and 23.08 manually using the command line (exact command is: flatpak install flathub org.freedesktop.Platform.VulkanLayer.MangoHud), opened flatseal, and added MANGOHUD=1 in the Environment section under "Variables" for the Prism Launcher application. This also allowed me to toggle MangoHud on in Lutris, which had previously also been greyed out. I found this solution in [this reddit thread](https://www.reddit.com/r/Lutris/comments/ysohwz/lutris_flatpak_how_to_enable_mangohub/).

**Comment by username-generic** [comment]
@Enchilada5528's workaround didn't work, and the option is still grayed out for me. 
 
Edit: Never mind, I just had to `flatpak remove` the non-`24.08` versions of `org.freedesktop.Platform.VulkanLayer.MangoHud`. Odd!

**Comment by GurkiGames** [comment]
i'm still having such issue, i installed the 21.08 and 23.08, pasted the command inside of flatseal, but still nothing, it's still grayed out, i may have done something wrong as i'm a rookie, but i find it odd, if anyone could help that'd be amazing, thanks.

**Comment by username-generic** [comment]
@GurkiGames Have you tried installing the `24.08` package only?
```sh
flatpak remove runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/21.08 runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/23.08 &&
flatpak install runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/24.08
```

**Comment by parkerlreed** [comment]
Neither 21 nor 24 work for current Prism Flatpak. Still greyed out. Is there a newer version available?

**Comment by username-generic** [comment]
@parkerlreed You may check for available versions by running:

```sh
flatpak search org.freedesktop.Platform.VulkanLayer.MangoHud
```

If memory serves right, the solution was having **only a single** branch of MangoHud installed. So I recommend you remove all currently installed versions of the package via `flatpak remove MangoHud`, and then install the latest one (`25.08` as of writing).

This behavior is odd nonetheless. As such, I think this issue should be reopened and investigated properly.

**Comment by aaaxxxeee** [comment]
I have this issue on SteamOS
