### ISSUE TITLE
One block mc error

### ISSUE THREAD

**Issue by BRUNCHPVP** [PrismLauncher/PrismLauncher#2148]
### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

I do not know

### Description of bug

Mod pack launcher for a second and crashes

### Steps to reproduce

[Uploading One Block MC.zip…]()

### Suspected cause

https://mclo.gs/7GaOfgz

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Try manually changing the Forge version to the latest under Edit -> Version -> Select Forge -> Change version

**Comment by Trial97** [comment]
Not a launcher issue.
Also you would get more help on discord with this kind of problems: https://prismlauncher.org/discord
