### ISSUE TITLE
Add PissMC as one of the default modloader options

### ISSUE THREAD

**Issue by Gcat101** [PrismLauncher/PrismLauncher#2149]
### Role

I am the lead developer of PissMC

### Suggestion

I think PissMC should be one of the default modloader options in Prism

### Benefit

PissMC is the only active modloader for rd-132211 and there are no alternatives for the players who prefer this version

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Hello, my name is G_cat, I am the creator and CEO of a modpack organization that cannot stop developing side projects.

One of these sideprojects is a modloader for rd-132211 (the oldest version available in the launcher) called PissMC (please do not laugh this is very serious). The project is currently in late beta almost ready for full release, though the development has recently slowed down because of other side projects. I think this would be a great addition to the Prism Launcher Project because the only other modloader for rd-132211 that exists and I know of is [NilLoader](https://github.com/unascribed/NilLoader), but as far as I am aware it has no active mods developed for it outside of a few prototypes, and it also focuses on supporting all minecraft versions instead of just rd-132211. This version has a very small but loyal playerbase that is dying for you to add this as a default modloader option. Right now the only way to install PissMC is [through its own installer](https://github.com/Modern-Modpacks/PissMC/releases/tag/i(III)), which works but requires having git installed and a bit of technical know-how. I hope you recognize my request and see the concerns behind it. Either way, thank you.

To try to convince you a bit more, here is just a small demonstration of what our modloader is capable of:

https://github.com/PrismLauncher/PrismLauncher/assets/79367505/9ed6c28f-3e9d-4924-8142-4898dbad803d

![image](https://github.com/PrismLauncher/PrismLauncher/assets/79367505/d554b5be-41fe-4e10-bb9a-8b450f122e91)

![image](https://github.com/PrismLauncher/PrismLauncher/assets/79367505/651dd1ec-2fdd-4edc-b423-6be41594e6df)

![image](https://github.com/PrismLauncher/PrismLauncher/assets/79367505/11f66d8e-ba2e-465c-a382-88ce2ca6b430)

I also want to include a couple of resources that might help you when researching our product:

* [Public repository](https://github.com/Modern-Modpacks/pissmc)
* [Source code of various example mods](https://github.com/Modern-Modpacks/PissMC/tree/main/mods)
* [Official website](https://pissmc.modernmodpacks.site)
* [Our maven repository](https://github.com/Modern-Modpacks/PissMC/tree/maven)
* [Our discord server](https://discord.modernmodpacks.site/)

Again, thank you for spending your time on this issue, we appriciate it. Hopefully you will take this matter seriously and let me know if you want me to change anything.

Take care,
G_cat

**Comment by TheKodeToad** [comment]
Hello, my name is TheKodeToad, I am a maintainer of the popular Minecraft launcher "Prism Launcher".

After thorough discussion, we came to the conclusion that we cannot add the mod loader to the launcher's mod loader menu - it is so good that nobody would ever want to play modern versions.

**Comment by Gcat101** [comment]
Understandable, have a great day

**Comment by Yoshiman5551** [comment]
💀💀💀💀💀💀
