### ISSUE TITLE
Symlinks Don't Carry Over Upon World Creation

### ISSUE THREAD

**Issue by catter1** [PrismLauncher/PrismLauncher#2156]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 5.15.3

### Description of bug

When adding a **symlinked** datapack to a singleplayer world in the world creation, the symlink does not get carried over after the initial chunk generation that occurs upon clicking "Create World". I expect the symlink to properly be copied over upon world creation.

Do keep in mind that just because the symlinked datapack applied itself initially during chunk generation does not mean it is properly enabled. Function datapacks will not have their functions, and worldgen datapacks will not have their changes take effect in new chunks (and will crash if you exit/reenter the world without activating the datapack).

### Steps to reproduce

1. Start to create a new world
2. Go to the "add datapacks" screen
3. Inside the temporary directory ("Open Pack Folder"), create a symlink
![image](https://github.com/PrismLauncher/PrismLauncher/assets/63272345/f0c5365d-959e-428d-996e-5fd8fe2cedc7)
5. Observe the datapack is properly in place, and activate it
![image](https://github.com/PrismLauncher/PrismLauncher/assets/63272345/064c6173-1110-43b4-baf6-0ed0a440c9ad)
7. Create the world
8. Once in game, observe the datapack initially did take effect
![image](https://github.com/PrismLauncher/PrismLauncher/assets/63272345/31823c07-6d25-43d1-bacf-125464f11eeb)
10. Do `/datapack list` and see the datapack missing
![image](https://github.com/PrismLauncher/PrismLauncher/assets/63272345/dc68e3d4-247f-46a3-81da-8aa48540d312)
12. View the save's datapack folder and see the symlink is broken
![image](https://github.com/PrismLauncher/PrismLauncher/assets/63272345/8500ec8c-5b5f-4ae1-879a-7a8e6ea3ab0e)

### Suspected cause

I'm assuming that when the world is moved from a temp folder to the instance's saves folder, it is not coded to properly copy over symlinks.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is not a  prism launcher issue
