### ISSUE TITLE
Follow system time format settings instead of choosing based on language

### ISSUE THREAD

**Issue by vrad-exe** [PrismLauncher/PrismLauncher#216]
### Role

I use Prism Launcher to manage multiple modded and vanilla Minecraft instances

### Suggestion

Time and date formats used in Prism Launcher's menus should follow the system settings, instead of being based on the app language

### Benefit

I have my system set to ISO 8601 formatted times (YYYY-MM-DD and 24 hour time), and would like apps to match this without having to change to a different variation of English, or another language entirely.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Since there are probably people out there who prefer the current behavior, this can be made an option in the language tab of Prism Launcher's settings, allowing you to choose whether to select time formats based on the app language or the system settings.

(Issue migrated from PolyMC issue tracker)

**Comment by purple512** [comment]
I was just about to file a bug nearly identical to this, glad I searched.

I would like to just echo that this is still broken. Like the poster I set my system for ISO 8601 but Prism Launcher does not honor it.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/79816784/d2673a3f-d3fd-4d96-ae83-a3612f53cf9a)

![image](https://github.com/PrismLauncher/PrismLauncher/assets/79816784/f12d3c9a-993f-4b9b-b6c9-1ec30f33f01c)

PrismLauncher 7.0 / Windows 11 22H2

I really hope this can be investigated. These default formats are terrible to look at.

**Comment by Ashlytical** [comment]
Hi, I know this issue has been closed for a while, but for some reason prism is refusing to follow my time format?

<img width="1131" height="679" alt="Image" src="https://github.com/user-attachments/assets/f6f38818-0255-4b19-9bf0-5edb357dae3a" />

<img width="185" height="145" alt="Image" src="https://github.com/user-attachments/assets/58511a0b-434f-44cd-89b6-0f4b6b1422ab" />

<img width="1506" height="828" alt="Image" src="https://github.com/user-attachments/assets/a1d2a88b-63dc-44d6-8811-b62868ea799f" />

Am I missing something? I'm a bit confused
