### ISSUE TITLE
FTB Modpack Import from zip file

### ISSUE THREAD

**Issue by alexsch01** [PrismLauncher/PrismLauncher#2163]
### Role

I want to play FTB modpack on Prism Launcher

### Suggestion / Benefit

Import FTB modpack zip file without extracting to $HOME/.ftba/instances
- also prevents needing $HOME/.ftba to begin with if you get the zip file from a different machine

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
Not feasible: there is no way to differentiate between prism packs and ftb zips.
Also with the implementation of https://github.com/PrismLauncher/PrismLauncher/issues/1830 you will be able to specify the directory from where you want to import the ftb pack(it will not be hardcoded to a specific path).

**Comment by TheKodeToad** [comment]
> Not feasible: there is no way to differentiate between prism packs and ftb zips.

Can't we check for the instance.json?

**Comment by Trial97** [comment]
> Can't we check for the instance.json?

Do we want to create and maintain a new pack format?
Like if we already have support for ftb app import why not on the machine that you have the ftb installed: import the pack in prism and then export it using curseforge or modrinth? 

In my opinion, this is useless and just adds more caveats to our current pack import, so feel free to reopen it if you want.

**Comment by TheKodeToad** [comment]
Huh? Prism packs use instance.cfg, and FTB packs use instance.json.
It should be simple to check for the latter, shouldn't it?

**Comment by Trial97** [comment]
Maybe it is just a simple check but do we want to create and maintain a new pack format?
As I mentioned in the above comment: if you find this as a possible useful feature feel free to reopen this issue.
