### ISSUE TITLE
Getting online mode with old versions

### ISSUE THREAD

**Issue by glea94** [PrismLauncher/PrismLauncher#2164]
### Role

I play different versions with ease

### Suggestion

adding the possibility to get online mode on old version (server beta)

### Benefit

to get ony premium access to old beta server

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
Already added, it will come in 8.1 (make sure to enable Online Fixes)!
