### ISSUE TITLE
Prism Launcher fails to locate loader install file

### ISSUE THREAD

**Issue by JackJones8** [PrismLauncher/PrismLauncher#2175]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 5.15.10

### Description of bug

Launcher has trouble installing forge loader, version of minecraft 1.18.2, tried both with modpack and with forge only, tried latest and recomended forge, log indicates failure to locate loader install file

### Steps to reproduce

- add new forge 1.18.2 instance to launcher
- run instance

### Suspected cause

files are misplaced, mislabeled, or locator fails to exectute correctly

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by BamsyTheSergal** [comment]
Copy of #2170 lol

**Comment by TheKodeToad** [comment]
They're correct yeah
