### ISSUE TITLE
没有购买游戏

### ISSUE THREAD

**Issue by UncleMax** [PrismLauncher/PrismLauncher#2179]
### Version of Prism Launcher

8.0

### Version of Qt

none

### Description of bug

![QQ截图20240301125149](https://github.com/PrismLauncher/PrismLauncher/assets/29654195/d093c6e0-9b64-4a04-b2de-69e1a714a4db)

### Steps to reproduce

运行游戏的时候出现

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Please open issues in English.

**Comment by Aces-and-Jacks** [comment]
Prism Launcher doesn't support piracy. You need to buy the game first. It does let you play a demo version of the game, but after that you need to pay for the full version

**Comment by Aces-and-Jacks** [comment]
Actually never mind. It looks like you're already signed in, sorry for the misunderstanding. I think that bug has been fixed in the newest release though. But yeah, if you haven't already then you should open an issue in english
