### ISSUE TITLE
Wrong version number is being displayed

### ISSUE THREAD

**Issue by netceil** [PrismLauncher/PrismLauncher#2189]
### Version of Prism Launcher

Prism Launcher 8.1

### Version of Qt

Qt 6.6.2

### Description of bug

The new 8.1 version is still displayed as 8.0 in the launcher which is wrong, and also causes the fact that pressing the update button while on the newest version tries to update to 8.1 (which you are already on). After the update it says "successfully updated to 8.0" and if you press the update button again, the process repeats. Kind of an update loop.

### Steps to reproduce

* Download Prism Launcher 8.1 and run it;
* The version is displayed as 8.0 everywhere in the launcher.

### Suspected cause

Someone overlooked this and PrismLauncher 8.1 was released without changing version numbers in the code.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Already fixed with #2188
