### ISSUE TITLE
The search bar is too close to the modpack listings

### ISSUE THREAD

**Issue by stantios** [PrismLauncher/PrismLauncher#2190]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 8.1

### Version of Qt

Qt 6.6.2

### Description of bug

In the modrinth modpacks tab, the search bar is too close to the modpack listings. I think it should be raised up to the same size as other tabs like the CurseForge modpacks.

Screenshots:

CurseForge:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/98621617/a404fa12-40eb-454e-bcfd-3c688e61f6b5)

Modrinth:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/98621617/a1c1e1d4-90bd-4fe4-8473-b0071be4d119)

### Steps to reproduce

1. Click 'Add Instance'
2. Go to the 'Modrinth' tab
3. You will see that the search bar is close to the modpack listings

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment]
I don't get this in 8.2. Probably got fixed

<img width="913" alt="Screen Shot 2024-03-04 at 1 41 22 AM" src="https://github.com/PrismLauncher/PrismLauncher/assets/106651342/392642ef-0271-4176-b199-ce860d35d6c9">

**Comment by stantios** [comment]
This issue still occurs for me in 8.2. Are you sure you're using either 8.1 or 8.2?

Screenshot:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/98621617/8f903b92-304c-4553-b621-26dd59217dc7)

**Comment by Scrumplex** [comment]
I can confirm this behavior on develop on Linux

**Comment by Aces-and-Jacks** [comment]
> This issue still occurs for me in 8.2. Are you sure you're using either 8.1 or 8.2?
> 
> 
> 
> Screenshot:
> 
> ![image](https://github.com/PrismLauncher/PrismLauncher/assets/98621617/8f903b92-304c-4553-b621-26dd59217dc7)
> 
> 

I recently updated after 8.2 got released. MacOS. I mean I'm on an older OS, maybe that has something to do with it? MacOS 12

**Comment by DioEgizio** [comment]
I think it's theme dependant, which is probably why I didn't notice this in #2063 (you're using the macos theme while OP is using fusion+ our palette)

**Comment by Trial97** [comment]
fixed by https://github.com/PrismLauncher/PrismLauncher/pull/2450
