### ISSUE TITLE
Prism Launchr update ignores / removes portable.txt

### ISSUE THREAD

**Issue by LunaLycan287** [PrismLauncher/PrismLauncher#2191]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0 -> 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

After updating from 8.0 to 8.2 configuration window pops up with defaults and not previous configuration. After finishing the configuration no instances are displayed and all previous settings are lost.
This is because there is no portable.txt in the folder any more and prism is looking in the wrong directories for the files / folders.

It can be easily fixed by recreating the portable.txt inside the Prism Launcher folder, but should not be required to do every update.

### Steps to reproduce

- Install Prism Launcher 8.0
- Create portable.txt inside Prism Launcher folder
- Create some instances / change some settings (e.g.: default ram usage is a good one to see in configuration)
- Click on Update to install newest version (8.2 in my case)
- After going through install the portable.txt will be missing, instances will be gone and changes reset.

### Suspected cause

portable.txt removed during install process and not recreated after.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LunaLycan287** [comment]
It seems this can not be reproduced with the steps provided. There might be some other more complex reasons why it happened.

**Comment by derrod** [comment]
I ran into the same issue, if the `manifest.txt` file is missing a default list of files to move to the backup folder is constructed, which includes `portable.txt`: https://github.com/PrismLauncher/PrismLauncher/blob/794a60b684b3053875101ed44dedd7f5006b65a7/launcher/updater/prismupdater/PrismUpdater.cpp#L1121
This will then lead to the file being missing when the launcher starts up, resulting in it running in non-portable mode. That this happened was confirmed by checking my updater log file.

I'm not familiar with Prism's updater mechanism, so I'm not sure why the manifest wasn't there.

**Comment by DelofJ** [comment]
I can confirm the issue is still there

**Comment by Trial97** [comment]
Do not install prism globally and add portable.txt to the folder where the exe is that's not how the updater is meant to be used.
But a quick fix download any portable build and copy from inside the zip folder the manifest file and paste it near the `portable.txt` file.

**Comment by DelofJ** [comment]
About the global install, which is another topic btw, why we shouldn't do it ? With MultiMC it was perfectly supported and even the main behavior, why it shouldn't here ?
Now about the main topic, why we should not be able to auto update our portable installation of PrismLauncher ?
I have an installation of Prism 5.0 on an USB key, I went ton the process of manually updating to 8.x so I could have it auto update only for it to not be supported ? To be honest I don't really see why this shouldn't be fixed
And finally, about your quick fix, you're saying copying the `manifest.txt` of the portable build and replace it after the auto update will fix it ? But this would be the same thing as copying and pasting the `portable.txt` if I understand correctly ?

**Comment by Trial97** [comment]
It looks like there are some misunderstandings:


> About the global install, which is another topic btw, why we shouldn't do it ? With MultiMC it was perfectly supported and even the main behavior, why it shouldn't here ?

The global installation is supported.


> Now about the main topic, why we should not be able to auto update our portable installation of PrismLauncher ?

I did not say that you should not be able to update portable.



> And finally, about your quick fix, you're saying copying the `manifest.txt` of the portable build and replace it after the auto update will fix it ? But this would be the same thing as copying and pasting the `portable.txt` if I understand correctly ?

No it is not. The updater uses the information from the manifest file to know what files it needs to backup.
If it is not present the updater has some defaults that include the `portable.txt`. On update, prism moves out the file but doesn't move it back.

Sorry for the misunderstanding, I will reopen it as the fix is just removing of that mentioned line.
