### ISSUE TITLE
Crash: "CRITICAL TAMPERING WITH MINECRAFT"

### ISSUE THREAD

**Issue by literon36** [PrismLauncher/PrismLauncher#2193]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0 (Flatpak)

### Version of Qt

Qt 5.15.10

### Description of bug

Starting the modpack Agrarian Skies results in the following crash from Forge: "_(java class) appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!_"
It suggests adding JVM arguments, but since Forestry does another check it also doesnt really help.
Regular Agrarian Skies: https://mclo.gs/IE3qVkZ
W/ arguments: https://mclo.gs/s8QPSbf

### Steps to reproduce

Add Instance > CurseForge > download Agrarian Skies > Launch

### Suspected cause

I've read about similar crashes online, it might require a specific version of Java 8 (?)
But in case Prismlauncher is injecting something... maybe that?

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Splago** [comment]
This is an issue with Java 8u362 and later, and forge for MC 1.4.7 to 1.6.4 according to these posts:

https://github.com/PrismLauncher/PrismLauncher/issues/747#issuecomment-1850676378
https://gist.github.com/ThePixelbrain/a0fe3231b9a9d71d910e7f71895e0196

Had the same issue with Agrarian Skies and Crash Landing when I updated java to 8u412 (was on 8u312). After searching for a bit, found the above posts, followed their instructions, and managed to load both modpacks on Java 8u412 without issues.

**Comment by Trial97** [comment]
This will not be fixed in prism.
Added documentation about how to fix it on the website: https://github.com/PrismLauncher/prismlauncher.org/pull/490

**Comment by literon36** [comment]
Thanks for your help! I will try the fixes in the next couple days / weeks depending on when i got time!

P.S. minor spelling mistake in the first sententence of your PR: "modpacks that crashe" :)


P.P.S. why can't this be fixed inside of Prism? Couldn't you detect a crash like this and then just place the file there? 🤔

Again, ty!

**Comment by Trial97** [comment]
> P.P.S. why can't this be fixed inside of Prism? Couldn't you detect a crash like this and then just place the file there? 🤔

https://github.com/PrismLauncher/PrismLauncher/pull/2560#pullrequestreview-2142297557 and I share the same view you already can do that using prism without needing to go the extra mile to hardcode it inside the launcher.



> P.S. minor spelling mistake in the first sententence of your PR: "modpacks that crashe" :)

Thank you fixed it.
