### ISSUE TITLE
Remember saved options for exporting the mrpack format.

### ISSUE THREAD

**Issue by NetUserGet** [PrismLauncher/PrismLauncher#2198]
### Role

I make a modpack.

### Suggestion

I would like a option added to set the defaults for the "export modrinth pack" dialog or for it to remember my changes for that specific instance. 

### Benefit

For ease of updating and use of the aformentioned dialog.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by armuell** [comment]
It's odd, when you export to a prism zip it remembers your last selected options. But when exporting to either modrinth mrpack or curseforge zip is doesn't. This would make pack development a lot nicer.

**Comment by Trial97** [comment]
This should already be there.
I tested on the latest nightly and the fields are saved
Implemented by https://github.com/PrismLauncher/PrismLauncher/pull/1519
