### ISSUE TITLE
Sponsor is still linked to polymc

### ISSUE THREAD

**Issue by C0D3-M4513R** [PrismLauncher/PrismLauncher#22]
The sponsor link is still linked to polymc.
Donations will probably go to the wrong place.
open_collective [opencollective.com/polymc](https://opencollective.com/polymc)

**Comment by CutestNekoAqua** [comment]
working on it

**Comment by flowln** [comment]
Fixed in https://github.com/PrismLauncher/PrismLauncher/commit/3f2e5633b456daaabe7de28293a73c55d8ae1a06 :)
