### ISSUE TITLE
Forge won't load at all on 1.6.4

### ISSUE THREAD

**Issue by 13spacemen** [PrismLauncher/PrismLauncher#2201]
### Version of Prism Launcher

8.2

### Version of Qt

6.6.2

### Description of bug

Can't play any 1.6.4 modpacks or mods due to Forge never loading

Tried Forge universal jar, directly adding Forge classes to MC client.jar, using "Add Loader" feature

### Steps to reproduce

Make fresh 1.6.4 instance, try to install Forge, 1.6.4 loads up vanilla and never loads Forge

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by JustRed23** [comment]
I cannot reproduce this as I cannot even launch 1.6.4...
https://mclo.gs/EZXL8m7

Yes I already tried deleting the libraries folder and the jar as well

**Comment by Trial97** [comment]
This will not be fixed in prism.
Added documentation about how to fix it on the website: https://github.com/PrismLauncher/prismlauncher.org/pull/490
