### ISSUE TITLE
Updating mods from Modrinth reports no updates available despite updates being available

### ISSUE THREAD

**Issue by glektarssza** [PrismLauncher/PrismLauncher#2212]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

Attempting to update mods that have updates on Modrinth, Prism Launcher reports that no updates are available.

For example, attempting to update Embeddium (v0.3.7 for 1.20.1) reports:

![image](https://github.com/PrismLauncher/PrismLauncher/assets/94402525/11d4f030-f784-4811-b050-62558d4ed911)

Going to Emebeddium on Modrinth, though, we can see the latest version of 0.3.9, posted today.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/94402525/a7627a56-320a-42b1-878b-0365fae02f21)

### Steps to reproduce

1. Create a new Minecraft 1,20.1 instance using Forge 47.2.0 as the mod loader.
2. Download Embeddium 0.3.7 through Prism Launcher
3. Check for updates to mods

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is an issue with modrinth, so you need to wait for them to fix it on their end.

There was yet an official notification regarding this but it looks like they changed the update API in "dummy mode":
https://discord.com/channels/734077874708938864/734077874708938867/1216809292892737536
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/b45f6dd8-f9bb-48ad-a98a-e94807028d33)

This is similar to: https://github.com/PrismLauncher/PrismLauncher/issues/2115

**Comment by glektarssza** [comment]
Looks like, as of time of writing, this has been resolved on Modrinth's end. Closing.
