### ISSUE TITLE
Launcher crashes after attempting to select file

### ISSUE THREAD

**Issue by nootisyes124** [PrismLauncher/PrismLauncher#2214]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

Prism Launcher crashes when uploading skin instead of uploading the skin and not crashing.

### Steps to reproduce

Navigate to "Manage accounts" menu
Click on any account
Click upload skin
Click browse
Select skin texture
It should crash now

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
I can't seem to reproduce this.
Can you upload the prism logs from when this happens?
Also if you could can you upload the image that crashes?

**Comment by nootisyes124** [comment]
Here is a video of the crash occurring 

https://github.com/PrismLauncher/PrismLauncher/assets/72772944/5583f5b8-5c8f-4419-846f-f9546674b794

**Comment by Trial97** [comment]
I do understand that it crashes, but if I can not reproduce it I require some kind of logs to determine what happens.
I also requested the image in the hope I can try to reproduce it myself.

**Comment by nootisyes124** [comment]
There is no log in the `/.local/share/PrismLauncher/logs` folder
Any image that I attempt to upload causes a crash

**Comment by Scrumplex** [comment]
How did you install Prism Launcher?

Maybe you can try to run it from a terminal and see if there is some log output right when it crashes

**Comment by nootisyes124** [comment]
I installed prism launcher using the aur package 
This is what the terminal outputs right after I select the image file and the launcher crashes

```
    52.885 D | [kf.kio.kfilewidgets.kfilewidget]: Tokenizing: "Funfetti-Cake-Humanoid-on-planetminecraft-com.png"
    52.961 D | [kf.service.sycoca]: Opening ksycoca from "/home/noot/.cache/ksycoca6_en_taOgp3lULfqKc3fbbmXN2wVtaFM="
    53.070 D | [kf.kio.core.dirlister]: lister: KDirLister(0x5da5a315ce40) silent= false
    53.070 D | [kf.kio.core.dirlister]: KDirLister(0x5da5a315ce40)  url= QUrl("file:///home/noot/Downloads")
    53.455 D | [kf.kio.core.dirlister]: ~KCoreDirLister KCoreDirLister(0x5da5a315ce40)
    53.455 D | [kf.kio.core.dirlister]: lister: KCoreDirLister(0x5da5a315ce40) silent= false
    53.455 D | [kf.kio.core.dirlister]: KCoreDirLister(0x5da5a315ce40)  url= QUrl("file:///home/noot/Downloads")
    53.455 D | [kf.kio.core.dirlister]: KCoreDirLister(0x5da5a315ce40)
    53.455 D | [kf.kio.core.dirlister]: Iterating over dirs QList(QUrl("file:///home/noot/Downloads"))
    53.455 D | [kf.kio.core.dirlister]: KCoreDirLister(0x5da5a315ce40)  _url:  QUrl("file:///home/noot/Downloads")
    53.455 D | [kf.kio.core.dirlister]: KCoreDirLister(0x5da5a315ce40) item moved into cache: QUrl("file:///home/noot/Downloads")
    53.456 D | [kf.kio.core.dirlister]: ~KCoreDirLister KCoreDirLister(0x5da5a26209a0)
    53.456 D | [kf.kio.core.dirlister]: lister: KCoreDirLister(0x5da5a26209a0) silent= false
    53.456 D | [kf.kio.core.dirlister]: KCoreDirLister(0x5da5a26209a0)  url= QUrl("tags:/")
    53.458 D | [kf.kio.core.dirlister]: KCoreDirLister(0x5da5a26209a0)
    53.458 D | [kf.kio.core.dirlister]: Iterating over dirs QList(QUrl("tags:/"))
    53.458 D | [kf.kio.core.dirlister]: KCoreDirLister(0x5da5a26209a0)  _url:  QUrl("tags:/")
    53.458 D | [kf.kio.core.dirlister]: KCoreDirLister(0x5da5a26209a0) item moved into cache: QUrl("tags:/")
    53.468 D | Paged dialog close requested
    53.468 D | Sorting icon list...
    53.469 D | Detecting proxy settings...
    53.469 D | Using no proxy is an option!
    53.469 D | Paged dialog close approved
    53.469 D | Paged dialog geometry saved
QIODevice::write (QFile, "logs/PrismLauncher-0.log"): device not open
    53.470 D | Paged dialog close requested
QIODevice::write (QFile, "logs/PrismLauncher-0.log"): device not open
    53.470 D | Sorting icon list...
QIODevice::write (QFile, "logs/PrismLauncher-0.log"): device not open
    53.470 D | Detecting proxy settings...
QIODevice::write (QFile, "logs/PrismLauncher-0.log"): device not open
    53.470 D | Using no proxy is an option!
QIODevice::write (QFile, "logs/PrismLauncher-0.log"): device not open
    53.470 D | Paged dialog close approved
QIODevice::write (QFile, "logs/PrismLauncher-0.log"): device not open
    53.470 D | Paged dialog geometry saved
QIODevice::write (QFile, "logs/PrismLauncher-0.log"): device not open
    53.569 D | Discovering instances in "/home/noot/.local/share/PrismLauncher/instances"
QIODevice::write (QFile, "logs/PrismLauncher-0.log"): device not open
    53.571 D | Found instance ID "Nomifactory CEu"
QIODevice::write (QFile, "logs/PrismLauncher-0.log"): device not open
    53.571 D | Found instance ID "1.12.2"
QIODevice::write (QFile, "logs/PrismLauncher-0.log"): device not open
    53.571 D | Found instance ID "Simply Optimized"
QIODevice::write (QFile, "logs/PrismLauncher-0.log"): device not open
    53.572 D | Should keep and soft-reload "Nomifactory CEu"
QIODevice::write (QFile, "logs/PrismLauncher-0.log"): device not open
    53.573 D | Should keep and soft-reload "1.12.2"
QIODevice::write (QFile, "logs/PrismLauncher-0.log"): device not open
    53.573 D | Should keep and soft-reload "Simply Optimized"
    53.703 D | [kf.kio.core]: aborting worker thread for  "file://"
    53.703 D | [kf.kio.core]: aborting worker thread for  "file://"
    53.703 D | [kf.kio.core]: aborting worker thread for  "file://"
    53.703 D | [kf.kio.core]: killing worker process pid 35917 ( "tags://" )
    53.703 D | [kf.kio.core]: killing worker process pid 35924 ( "thumbnail://" )
    53.703 D | [kf.kio.core.dirlister]: 
    53.704 D | [kf.coreaddons.kdirwatch]: path= "/home/noot" sub_entry: 0x0
    53.704 D | [kf.coreaddons.kdirwatch]: path= "/home/noot/Downloads" sub_entry: 0x0
    53.704 D | [kf.coreaddons.kdirwatch]: path= "/home/noot/Desktop" sub_entry: 0x0
    53.704 D | [kf.coreaddons.kdirwatch]: path= "/home/noot/.local/share/PrismLauncher" sub_entry: 0x0
```

**Comment by horror-proton** [comment]
I think is is not an issue of prismlauncher. Telegram desktop app (also in Qt6) also "`exit(0)`" immediately after choosing files. I believe this is an issue of qt6 or kio, or perhaps there's something wrong with my xdg-desktop-portal config (for I'm using Hyprland with `QT_QPA_PLATFORMTHEME=qt5ct`, not sure what would happen in KDE)

if you are also using `QT_QPA_PLATFORMTHEME` there's a workaround to run `qt6ct` and choose something different from `KDE` in "Appearance" tab -> "Standard dialogs"

**Comment by Trial97** [comment]
From the https://github.com/PrismLauncher/PrismLauncher/issues/2235 looks like all the OpenFile dialogs are affected

**Comment by mhzen** [comment]
> I think is is not an issue of prismlauncher. Telegram desktop app (also in Qt6) also "`exit(0)`" immediately after choosing files. I believe this is an issue of qt6 or kio, or perhaps there's something wrong with my xdg-desktop-portal config (for I'm using Hyprland with `QT_QPA_PLATFORMTHEME=qt5ct`, not sure what would happen in KDE)

I think might be the case too, when i launch prism with `XDG_CURRENT_DESKTOP=gnome prismlauncher` it worked flawlessly except for the theme obviously not following the system

**Comment by horror-proton** [comment]
I didn't figure out a proper way to debug, what I'm doing now is attaching gdb to qt app and add breakpoints at something like `QEventLoop::exit`

**Comment by Trial97** [comment]
> I didn't figure out a proper way to debug, what I'm doing now is attaching gdb to qt app and add breakpoints at something like `QEventLoop::exit`

If you want to debug this using gdb my suggestion is first to set up a breakpoint here: https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/ui/dialogs/SkinUploadDialog.cpp#L124 if the breakpoint is not trigger but it still crashes when you select the skin: it is most probably qt fault not prism.
And if you want to dig deeper add a breakpoint on a previous line(https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/ui/dialogs/SkinUploadDialog.cpp#L122) and proceed inside QFileDialog::getOpenFileName to determine the exact cause.

**Comment by CrabbyDisk** [comment]
I am currently having the same issue and I have found that this happens also happens when dragging a file into the window (ex: loading a mod from the Downloads folder)

**Comment by smowtenshi** [comment]
This may be related to changes made in KDE6. Please see [KDE Issue #483439](https://bugs.kde.org/show_bug.cgi?id=483439) and https://github.com/strawberrymusicplayer/strawberry/issues/1401.
