### ISSUE TITLE
The exported courseforge's modpack cannot be downloaded properly by other launchers！

### ISSUE THREAD

**Issue by zirran** [PrismLauncher/PrismLauncher#2216]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

The exported courseforge's modpack cannot be downloaded by other launchers, but the exported modrinth's modpack can be downloaded normally！！！

### Steps to reproduce

[Dominated by fear.zip](https://github.com/PrismLauncher/PrismLauncher/files/14617779/Dominated.by.fear.zip)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
What is the error when trying to import into other launchers?

**Comment by Trial97** [comment]
From what I see in the manifest the forge version is not populated as it should

**Comment by zirran** [comment]
输入字符串的格式不正确。
在 PCLModDownloadLib.McDownloadForgeLoaderString Version, String lnherit, DIForgeVersionEntry
Downloadlnfo, String McFolder, LoaderCombo' ClientDownloadLoader, String ClientFolder, Boolean FixLibrary
在 PCL.ModDownloadLib.MclnstallLoader(MclnstallReguest Reguest, Boolean DontFixLibraries)
在 PCLModModpack.nstalPackCurseForge(String FileAddress,ZipArchive Archive, String ArchiveBaseFolder
String VersionName,String Logo)
在PCL.ModModpack.Modpacklnstall(String File, String VersionName, Boolean ShowHint,String Logo)
错误类型: SvstemFormatException
