### ISSUE TITLE
just downloaded but can't add xbox account

### ISSUE THREAD

**Issue by sweetishlemon** [PrismLauncher/PrismLauncher#2220]
### Operating System

Windows

### Version of Prism Launcher

prism launcher 8.2

### Version of Qt

?

### Description of bug

I just downloaded prism launcher and it says  "Failed to get authorization for Xbox services: Operation canceled"

### Steps to reproduce

add microsoft account.
log in normally.
It just doesn't work.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ChocoFleece** [comment]
same with you, just Login with Xbox and "Failed to get authorization for Xbox services: Operation canceled".

**Comment by ChaoticGooose** [comment]
Seems to be a windows only issue too, I'm using the QT5 release on Arch Linux and not having any issues, Yet my mate on Windows 10 can't seem to login

**Comment by ChocoFleece** [comment]
> Seems to be a windows only issue too, I'm using the QT5 release on Arch Linux and not having any issues, Yet my mate on Windows 10 can't seem to login

No, i just in ArchLinux and meet this problem. But i solve it when i changed to another Microsoft Account which have Minecraft. Maybe is a Xbox Account Age<18 problem

**Comment by Trial97** [comment]
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2302
