### ISSUE TITLE
I cant play my instance 

### ISSUE THREAD

**Issue by Matypo** [PrismLauncher/PrismLauncher#2223]
### Operating System

Windows

### Version of Prism Launcher

Prism launcher 8.2

### Version of Qt

QT 6.6.2

### Description of bug

I cant play 
Échec de la mise à jour de l'instance. Raison : Échec de la mise à jour du jeu : les bibliothèques requises n'ont pas pu être récupérées.
Raison :
Une ou plusieurs tâches secondaires ont échoué

### Steps to reproduce

![capture_240319_155201](https://github.com/PrismLauncher/PrismLauncher/assets/88747954/ff5da96b-8705-421e-8355-deb97b173254)

### Suspected cause

Une ou plusieurs tâches secondaires ont échoué

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Duplicate of: https://github.com/PrismLauncher/PrismLauncher/issues/2170

Remove the `meta` folder that is inside prism root folder and try again.
Also next time try creating the issue in English.

**Comment by Matypo** [comment]
Ok ,thanks for the help and i'm sorry for the mess
