### ISSUE TITLE
No discrete GPU option on intel iMac

### ISSUE THREAD

**Issue by leahanderson1** [PrismLauncher/PrismLauncher#2228]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

I'm attempting to use my AMD Radeon R9 card installed in my 2015 iMac, however, there is no option to enable it.
<img width="1039" alt="image" src="https://github.com/PrismLauncher/PrismLauncher/assets/144633084/b9409714-c2a9-468a-8337-466fb5ed205c">

### Steps to reproduce

* go to settings
* select Minecraft
* select Tweaks

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
That option is only for linux, and all it does is set some environmental variables for that process.
On mac I'm pretty sure that you can't enable that without manually setting the preferred GPU for the java executable.
