### ISSUE TITLE
Combat Test Snapshots missing

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#2229]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

Prism Launcher is missing the experimental CTS snapshots `Combat Test 7c`, `Combat Test 8b` and `Combat Test 8c`. 
![image](https://github.com/PrismLauncher/PrismLauncher/assets/70875007/a71a9fb6-12a0-452b-8dc6-b7130d0237ac)

### Steps to reproduce

- Click on ‘Add instance’
- In the ‘Version’ prompt, Search for `1.16_combat-7c`, `1.16_combat-8b`, and `1.16_combat-8c` _(either search manually or using the search bar; filter by experiments for ease)_
- The snapshots will not be shown

### Suspected cause

Prism has not officially added support for these snapshots

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
I can't even find it on the official Minecraft launcher so I'm pretty sure that doesn't exist on the Minecraft meta.
Also checked other launchers(Modrinth, Curse, Atlauncher, and GDLauncher) for this but without luck.
So I'm gonna close this as there is nothing prism can do if is not in the Minecraft meta.

**Comment by Scrumplex** [comment]
These snapshots were not part of Mojang's meta

**Comment by Scrumplex** [comment]
https://github.com/PrismLauncher/meta/blob/main/static/mojang/minecraft-experiments.json

They are all listed in this file.

@GlassOfAnarchy look for 1_16_combat-6 which should be 8c
