### ISSUE TITLE
Description string in "download mods" dialog overlaps title string

### ISSUE THREAD

**Issue by MadByteDE** [PrismLauncher/PrismLauncher#223]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 5.0 (AppImage)

### Version of Qt

Qt 6.2.4

### Description of bug

When going to (on instance) edit ↪ Mods ↪ Download mods ... the spacing between newlines of the description text seem too large which causes the description text to overlap with the title of the mod entry.

![Image](https://i.imgur.com/xcdQJ3J.png)

- I'm on my Steam Deck in desktop mode (KDE Plasma)
- Other apps don't have UI issues like this

### Steps to reproduce

See description

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
This was fixed in #39. Version 5.1 will include the fix
