### ISSUE TITLE
For installer, detect if the specified folder contains instances folder.

### ISSUE THREAD

**Issue by aMelonRind** [PrismLauncher/PrismLauncher#2230]
### Role

I'm prism launcher user that was on older version and didn't have auto update enabled.

### Suggestion

I want the installer to warn the user if the specified folder contains instances folder.

### Benefit

so the user won't accidently delete their instances. (assuming if the installer actually deletes old files)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

tldr: I'm dumb and almost deleted all my instances, although I do have some backups.

The accident:
I need to test a mod with NeoForge, and found out NeoForge support is on prism 8.0, so I need to update the launcher.
I might be blind, but I didn't see the update button in 7.2.
Look into the help menu, didn't find anything related to updates. then noticed the news at the bottom says:
> Prism Launcher Release 8.2, now available

Click into it, read it, and the last line says:
> You can [grab the latest download here](https://prismlauncher.org/download/) for your respective platform.

So, I thought downloading the installer is the only way to update.
Downloaded and open the installer, it says select a folder. I open the mods folder from a shortcut, then noticed the path is slightly different from the default one in the installer, and the folder name is the same, then I thought I need to change the path, and I did it.
Then the installation ran for a minute, the progress says there's 1.2gb of files, and it's continually increasing. I think something went terribly wrong, the cancel button is not active, so I terminated the installer in task manager.

Good news is that I didn't lose any file because free space didn't increase, and it still launches correctly.

**Comment by Trial97** [comment]
Prism installer doesn't delete the instance folder, nor does the uninstall of prism.
Usually, prism has two folders that it cares about: 
- where the executable is located
- and the data directory = where your configs and instances are usually located

So when reinstalling/uninstalling prism the only affected folder is where the executable is located and even there the files that are modified are limited to the ones created by the prism installer.
 So when you install my suggestion is if you do not have a reason to change the install path do not do it. But if you do prism will not care about where is installed as the data directory will always point toward the same location on the system.
I will close this as not planned.
If you have trouble installing/updating let me know in this issue or better you can join Prism discord and ask there.
Here is the invite link if needed: https://prismlauncher.org/discord

**Comment by aMelonRind** [comment]
I see. Appreciate your answer.
> So when you install my suggestion is if you do not have a reason to change the install path do not do it.

Normally I won't do that, but I thought I should because at the past I'm using portable version of MultiMc which is in a custom location, so I thought my prism install might be on custom location too, so I looked up the path and changed it.

Good to know that it doesn't actually remove other files! But why is it scanning all the files, although they will remain untouched?

**Comment by aMelonRind** [comment]
> If you have trouble installing/updating let me know in this issue or better you can join Prism discord and ask there.

Thanks, I've already installed it correctly before opening this issue.

**Comment by Trial97** [comment]
> Good to know that it doesn't actually remove other files! But why is it scanning all the files, although they will remain untouched?

I will presume that is to collect the files that need to be deleted.
The portable update is another story as you usually just need to extract over the old portable(there may be caveats to that like before extracting you would need to delete some files)
