### ISSUE TITLE
Hwlp

### ISSUE THREAD

**Issue by Gamerperson5567** [PrismLauncher/PrismLauncher#2238]
### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.3.0

### Description of bug

Won't install

### Steps to reproduce

gamerperson@localhost:~/pi-apps$ cd apps gamerperson@localhost:~/pi-apps/apps$ ~/pi-apps/manage install 'Minecraft Java Prism Launcher' ◢◣ WARNING: YOUR SYSTEM IS UNSUPPORTED: Pi-Apps is not supported on Android. Some apps will work, but others won't. The ability to send error reports has been disabled. Waiting 10 seconds... (To cancel, press Ctrl+C or close this terminal) Installing Minecraft Java Prism Launcher...  Will install these packages: mesa-utils https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Downloading prismlauncher_8.2-1_armhf.deb to /tmp/prismlauncher_8.2-1_armhf.deb... 03/24 00:00:31 [ERROR] CUID#6 - Download aborted. URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb   -> [AbstractCommand.cc:799] errorCode=19 CUID#6 - Name resolution for github.com failed:No address returned b77407|ERR |        n/a|/tmp/prismlauncher_8.2-1_armhf.deb (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.  Failed to download: https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Please review errors above. ◢◣ WARNING: Package download failed. (Attempt 1 of 3) Downloading prismlauncher_8.2-1_armhf.deb to /tmp/prismlauncher_8.2-1_armhf.deb... 03/24 00:00:31 [ERROR] CUID#6 - Download aborted. URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb   -> [AbstractCommand.cc:799] errorCode=19 CUID#6 - Name resolution for github.com failed:No address returned dc9c12|ERR |        n/a|/tmp/prismlauncher_8.2-1_armhf.deb (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.  Failed to download: https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Please review errors above. ◢◣ WARNING: Package download failed. (Attempt 2 of 3) Downloading prismlauncher_8.2-1_armhf.deb to /tmp/prismlauncher_8.2-1_armhf.deb... 03/24 00:00:31 [ERROR] CUID#6 - Download aborted. URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb   -> [AbstractCommand.cc:799] errorCode=19 CUID#6 - Name resolution for github.com failed:No address returned cf1f10|ERR |        n/a|/tmp/prismlauncher_8.2-1_armhf.deb (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.  Failed to download: https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Please review errors above. ◢◣ WARNING: Package download failed. (Attempt 3 of 3) install_packages(): Downloaded package does not exist! (/tmp/prismlauncher_8.2-1_armhf.deb)  Failed to install Minecraft Java Prism Launcher! ◢◣Need help? Copy the ENTIRE terminal output or take a screenshot. Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose Or on Discord: https://discord.gg/RXSTvaUvuu date: option requires an argument -- 'd' Try 'date --help' for more information. gamerperson@localhost:~/pi-apps/apps$ ~/pi-apps/manage install 'Minecraft Java Prism Launcher" > ^C gamerperson@localhost:~/pi-apps/apps$ ~/pi-apps/manage install 'Minecraft Java Prism Launcher' ◢◣ WARNING: YOUR SYSTEM IS UNSUPPORTED: Pi-Apps is not supported on Android. Some apps will work, but others won't. The ability to send error reports has been disabled. Waiting 10 seconds... (To cancel, press Ctrl+C or close this terminal) Installing Minecraft Java Prism Launcher...  Will install these packages: mesa-utils https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Downloading prismlauncher_8.2-1_armhf.deb to /tmp/prismlauncher_8.2-1_armhf.deb... 03/24 00:01:21 [ERROR] CUID#6 - Download aborted. URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb   -> [AbstractCommand.cc:799] errorCode=19 CUID#6 - Name resolution for github.com failed:No address returned                                                     e33df7|ERR |        n/a|/tmp/prismlauncher_8.2-1_armhf.deb                                                  (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.  Failed to download: https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb                                           Please review errors above. ◢◣ WARNING: Package download failed. (Attempt 1 of 3) Downloading prismlauncher_8.2-1_armhf.deb to /tmp/prismlauncher_8.2-1_armhf.deb...                          03/24 00:01:21 [ERROR] CUID#6 - Download aborted. URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb            -> [AbstractCommand.cc:799] errorCode=19 CUID#6 - Name resolution for github.com failed:No address returned 6f4aff|ERR |        n/a|/tmp/prismlauncher_8.2-1_armhf.deb (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.  Failed to download: https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Please review errors above. ◢◣ WARNING: Package download failed. (Attempt 2 of 3) Downloading prismlauncher_8.2-1_armhf.deb to /tmp/prismlauncher_8.2-1_armhf.deb... 03/24 00:01:22 [ERROR] CUID#6 - Download aborted. URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb   -> [AbstractCommand.cc:799] errorCode=19 CUID#6 - Name resolution for github.com failed:No address returned 88a2ac|ERR |        n/a|/tmp/prismlauncher_8.2-1_armhf.deb (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.  Failed to download: https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Please review errors above. ◢◣ WARNING: Package download failed. (Attempt 3 of 3) install_packages(): Downloaded package does not exist! (/tmp/prismlauncher_8.2-1_armhf.deb)  Failed to install Minecraft Java Prism Launcher!

### Suspected cause

I don't know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Gamerperson5567** [comment]
gamerperson@localhost:~/pi-apps$ cd apps gamerperson@localhost:~/pi-apps/apps$ ~/pi-apps/manage install 'Minecraft Java Prism Launcher' ◢◣ WARNING: YOUR SYSTEM IS UNSUPPORTED: Pi-Apps is not supported on Android. Some apps will work, but others won't. The ability to send error reports has been disabled. Waiting 10 seconds... (To cancel, press Ctrl+C or close this terminal) Installing Minecraft Java Prism Launcher...  Will install these packages: mesa-utils https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Downloading prismlauncher_8.2-1_armhf.deb to /tmp/prismlauncher_8.2-1_armhf.deb... 03/24 00:00:31 [ERROR] CUID#6 - Download aborted. URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb   -> [AbstractCommand.cc:799] errorCode=19 CUID#6 - Name resolution for github.com failed:No address returned b77407|ERR |        n/a|/tmp/prismlauncher_8.2-1_armhf.deb (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.  Failed to download: https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Please review errors above. ◢◣ WARNING: Package download failed. (Attempt 1 of 3) Downloading prismlauncher_8.2-1_armhf.deb to /tmp/prismlauncher_8.2-1_armhf.deb... 03/24 00:00:31 [ERROR] CUID#6 - Download aborted. URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb   -> [AbstractCommand.cc:799] errorCode=19 CUID#6 - Name resolution for github.com failed:No address returned dc9c12|ERR |        n/a|/tmp/prismlauncher_8.2-1_armhf.deb (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.  Failed to download: https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Please review errors above. ◢◣ WARNING: Package download failed. (Attempt 2 of 3) Downloading prismlauncher_8.2-1_armhf.deb to /tmp/prismlauncher_8.2-1_armhf.deb... 03/24 00:00:31 [ERROR] CUID#6 - Download aborted. URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb   -> [AbstractCommand.cc:799] errorCode=19 CUID#6 - Name resolution for github.com failed:No address returned cf1f10|ERR |        n/a|/tmp/prismlauncher_8.2-1_armhf.deb (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.  Failed to download: https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Please review errors above. ◢◣ WARNING: Package download failed. (Attempt 3 of 3) install_packages(): Downloaded package does not exist! (/tmp/prismlauncher_8.2-1_armhf.deb)  Failed to install Minecraft Java Prism Launcher! ◢◣Need help? Copy the ENTIRE terminal output or take a screenshot. Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose Or on Discord: https://discord.gg/RXSTvaUvuu date: option requires an argument -- 'd' Try 'date --help' for more information. gamerperson@localhost:~/pi-apps/apps$ ~/pi-apps/manage install 'Minecraft Java Prism Launcher" > ^C gamerperson@localhost:~/pi-apps/apps$ ~/pi-apps/manage install 'Minecraft Java Prism Launcher' ◢◣ WARNING: YOUR SYSTEM IS UNSUPPORTED: Pi-Apps is not supported on Android. Some apps will work, but others won't. The ability to send error reports has been disabled. Waiting 10 seconds... (To cancel, press Ctrl+C or close this terminal) Installing Minecraft Java Prism Launcher...  Will install these packages: mesa-utils https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Downloading prismlauncher_8.2-1_armhf.deb to /tmp/prismlauncher_8.2-1_armhf.deb... 03/24 00:01:21 [ERROR] CUID#6 - Download aborted. URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb   -> [AbstractCommand.cc:799] errorCode=19 CUID#6 - Name resolution for github.com failed:No address returned                                                     e33df7|ERR |        n/a|/tmp/prismlauncher_8.2-1_armhf.deb                                                  (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.  Failed to download: https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb                                           Please review errors above. ◢◣ WARNING: Package download failed. (Attempt 1 of 3) Downloading prismlauncher_8.2-1_armhf.deb to /tmp/prismlauncher_8.2-1_armhf.deb...                          03/24 00:01:21 [ERROR] CUID#6 - Download aborted. URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb            -> [AbstractCommand.cc:799] errorCode=19 CUID#6 - Name resolution for github.com failed:No address returned 6f4aff|ERR |        n/a|/tmp/prismlauncher_8.2-1_armhf.deb (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.  Failed to download: https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Please review errors above. ◢◣ WARNING: Package download failed. (Attempt 2 of 3) Downloading prismlauncher_8.2-1_armhf.deb to /tmp/prismlauncher_8.2-1_armhf.deb... 03/24 00:01:22 [ERROR] CUID#6 - Download aborted. URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb   -> [AbstractCommand.cc:799] errorCode=19 CUID#6 - Name resolution for github.com failed:No address returned 88a2ac|ERR |        n/a|/tmp/prismlauncher_8.2-1_armhf.deb (ERR):error occurred. aria2 will resume download if the transfer is restarted. If there are any errors, then see the log file. See '-l' option in help/man page for details.  Failed to download: https://github.com/Pi-Apps-Coders/files/releases/download/large-files/prismlauncher_8.2-1_armhf.deb Please review errors above. ◢◣ WARNING: Package download failed. (Attempt 3 of 3) install_packages(): Downloaded package does not exist! (/tmp/prismlauncher_8.2-1_armhf.deb)  Failed to install Minecraft Java Prism Launcher!

**Comment by Trial97** [comment]
Looks like you are trying to install prism on android: `◢◣ WARNING: YOUR SYSTEM IS UNSUPPORTED: Pi-Apps is not supported on Android.` 
We do not provide support for prism on android.
The error you are receiving is that the package manager is not able to download the deb file so this is not a prism issue.

**Comment by Gamerperson5567** [comment]
Thank you
