### ISSUE TITLE
VirusTotal reports 1 of 72 vendors detecting malware in 8.2 installer

### ISSUE THREAD

**Issue by the-vindex** [PrismLauncher/PrismLauncher#2239]
### Version of Prism Launcher

8.2

### Version of Qt

no idea, it's installer before installation

### Description of bug

VirusTotal reports 1/72 malware detection in 8.2 installer
https://www.virustotal.com/gui/file/aa3c568c88329c4dd471492c0db25a6c299b4346562d63e850e3064902d86d69/detection

### Steps to reproduce

Upload installer to VirusTotal

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
false positive
