### ISSUE TITLE
Exception caught from launcher

### ISSUE THREAD

**Issue by ff6f8d68** [PrismLauncher/PrismLauncher#2245]
### Operating System

macOS

### Version of Prism Launcher

prism launcher 8.0

### Version of Qt

6.6.0

### Description of bug

Exception caught from launcher
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:94)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:86)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR

### Steps to reproduce

1.make new instance with Minecraft snapshot 24w12a or any other not release version
2.start the game (without forge ect.)

### Suspected cause

a error in Minecraft/PrismLauncher itself (java.lang.ClassNotFoundException: **net.minecraft.client.main.Main**)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This doesn't happen on the latest version of prism:8.2
Please update and then upload the full log to https://mclo.gs/.

**Comment by ff6f8d68** [comment]
https://mclo.gs/xHBuz7I

**Comment by Trial97** [comment]
My recommendation still stands: update the launcher to the latest version
Solution:
- start the game using an online account
- or right-click on the instance>Edit>Versions>Download All

**Comment by ff6f8d68** [comment]
ok works on newest prism launcher version thanks

**Comment by maskersss** [comment]
> This doesn't happen on the latest version of prism:8.2 Please update and then upload the full log to https://mclo.gs/.

it does for me, https://mclo.gs/FyzrtqQ
unless i'm misunderstanding what did you mean

**Comment by Trial97** [comment]
> it does for me, https://mclo.gs/FyzrtqQ
> unless i'm misunderstanding what did you mean

@maskersss did you try the solutions proposed by me?
If you start for the first time a version you need to download the game assets (this can not happen if you try to play with an offline account)

**Comment by maskersss** [comment]
yeah i know what the issue is, i just thought you were saying that prism 8.2 doesn't have this issue at all

**Comment by Trial97** [comment]
I always recommend that if you have an issue with the launcher: try to update the launcher to the latest version, as the issue may be solved.
