### ISSUE TITLE
exit code 6 modded Minecraft forge 1.20.1

### ISSUE THREAD

**Issue by ff6f8d68** [PrismLauncher/PrismLauncher#2246]
### Operating System

macOS

### Version of Prism Launcher

prism launcher 8.2

### Version of Qt

6.6.2

### Description of bug

**-download-**
[download](https://www.mediafire.com/file/3frfn9d8zjr5imw/Skyward+Colonies-+Explore+the+Skies+with+Eureka+and+Create.zip/file)

**-info-**
macOS: 14.3.1 (Sonoma)
chip: m2
memory: 8gb

**-bug-**
exit code 6 (anything with server thread even if I am in singleplayer

### Steps to reproduce

1.install the linked modpack
2.launch the game
3. create a new world or enter a world
4. game crash with exit code 6

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ff6f8d68** [comment]
just wait until the mudpack is uploaded

**Comment by Trial97** [comment]
Closing this as this is not a launcher issue.

**Comment by ff6f8d68** [comment]
can anyone help me?

**Comment by Trial97** [comment]
try on our discord: 
https://prismlauncher.org/discord
