### ISSUE TITLE
Support for headlessmc 

### ISSUE THREAD

**Issue by pizzav-xyz** [PrismLauncher/PrismLauncher#2251]
### Role

I want to launch my prism instances headless

### Suggestion

Allow launching instances with headlessmc

### Benefit

Useful 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

https://github.com/3arthqu4ke/headlessmc

**Comment by Trial97** [comment]
Yeah, let's not: launching a launcher from another launcher is a little too much
