### ISSUE TITLE
Minecraft Forge libraries are not downloaded

### ISSUE THREAD

**Issue by R2kip** [PrismLauncher/PrismLauncher#2259]
### Version of Prism Launcher

8.2

### Version of Qt

6.6.2

### Description of bug

95.731 C | [launcher.task.net.download]: "{0d9533d6-288c-4821-9b1c-6ac3b47a9325}" Failed  "https://maven.minecraftforge.net/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar"  with reason  QNetworkReply::UnknownNetworkError
    95.731 C | [launcher.task.net.download]: "{b2db1f9d-60c9-4e38-8efc-ed581bebcf48}" Failed  "https://maven.minecraftforge.net/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar"  with reason  QNetworkReply::UnknownNetworkError
    95.731 C | [launcher.task.net.download]: "{867c8020-7609-4a5c-878a-a80d4ba02ef8}" Failed  "https://maven.minecraftforge.net/com/typesafe/config/1.2.1/config-1.2.1.jar"  with reason  QNetworkReply::UnknownNetworkError
    95.732 C | [launcher.task.net.download]: "{423b2966-ea6d-44d4-91a5-0500d31593e0}" Failed  "https://maven.minecraftforge.net/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar"  with reason  QNetworkReply::UnknownNetworkError
    95.732 C | [launcher.task.net.download]: "{6aebe8d1-608e-410d-a351-a6d9266ca74a}" Failed  "https://maven.minecraftforge.net/jline/jline/2.13/jline-2.13.jar"  with reason  QNetworkReply::UnknownNetworkError
    95.733 C | [launcher.task.net.download]: "{4c797f94-79f7-4dfb-9357-c35898c6bcc5}" Failed  "https://maven.minecraftforge.net/net/minecraftforge/forge/1.8.9-11.15.1.2318-1.8.9/forge-1.8.9-11.15.1.2318-1.8.9-universal.jar"  with reason  QNetworkReply::UnknownNetworkError
    

### Steps to reproduce

I do not know, most likely the problem is in my computer

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Are you in Russia?
If yes it may be related to: https://github.com/PrismLauncher/PrismLauncher/issues/2260
Either way try a VPN.

**Comment by R2kip** [comment]
![image](https://github.com/PrismLauncher/PrismLauncher/assets/56793105/35c97292-669f-423f-8f6f-617ac2bb1b5f)
Website working

**Comment by R2kip** [comment]
I tried with a proxy, it didn't help

**Comment by lordofpipes** [comment]
> Website working

Even if the website works, the launcher can still fail if you're running on an operating system that doesn't support TLSv1.3. Web browsers bring their own TLS, whereas PrismLauncher uses the one included with the OS.

**Comment by R2kip** [comment]
Cool, why not TLSv1.2?
It's just that Windows 10 does not support TLSv1.3

**Comment by R2kip** [comment]
I found how to enable tls v1.3 on windows 10. Thanks for the help

**Comment by lordofpipes** [comment]
For future reference, here is a workaround: https://github.com/PrismLauncher/PrismLauncher/issues/2260#issuecomment-2029399835
