### ISSUE TITLE
When duplicating an instance, the playtime is kept.

### ISSUE THREAD

**Issue by TheCharlsen** [PrismLauncher/PrismLauncher#2262]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

6.6.2

### Description of bug

When duplicating an Instance, the instances playtime is kept. Therefore faking the overall playtime.

### Steps to reproduce

1. Right click on instance
2. Press Copy
3. Click on copied instance and see in the botton info banner, that the playtime is the same of the original instance

### Suspected cause

It just duplicates everything. My suggestion is to reset the playtime of the new copied instance. When copying an instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
![20240401_235425](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/1af8d80b-fc9c-4292-8242-c256c695aba2)
Did you uncheck that?
