### ISSUE TITLE
Prism crashes when trying to import a pack with 0 mods

### ISSUE THREAD

**Issue by Gcat101** [PrismLauncher/PrismLauncher#2264]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.2.4

### Description of bug

If you try to import a cf pack that doesn't have any mods using the zip, Prism briefly shows a "retrieving mod ids" modal and then crashes.

### Steps to reproduce

* Create a zip with a pack in the cf format that contains 0 mods though any means (I used packwiz)
* Import it into Prism by drag-and-dropping or right clicking, pressing "create instance" > "import from zip", then selecting the zip you've created and pressing "OK"
* Watch the crash happen

### Suspected cause

The bug is likely happening because the JSON parser that Prism uses expects to get at least one object in the "files" array inside manifest.json:

![image](https://github.com/PrismLauncher/PrismLauncher/assets/79367505/ce07c774-ef71-46ed-8fb9-17baa40b5bc2)
 
When it can't find anything, it panics and crashes. This is a pretty niche edgecase so this bug might've not been discovered before. Log and the pack I used are attached.

[Empty Pack-1.0.0.zip](https://github.com/PrismLauncher/PrismLauncher/files/14843230/Empty.Pack-1.0.0.zip)
[log.txt](https://github.com/PrismLauncher/PrismLauncher/files/14843237/log.txt)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Update prism before reporting bugs, as they may be already resolved.
Here is the link where you can download the new prism version: https://prismlauncher.org/download?from=button
I will close this for now as it is not happening on 8.2.
