### ISSUE TITLE
Java 21 on Flathub

### ISSUE THREAD

**Issue by MaledictYtb** [PrismLauncher/PrismLauncher#2265]
### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

Java 21 isn't packaged in the flathub prism launcher. It's impossible to launch the latest snapshot. 

### Steps to reproduce

Install prism from flathub and try playing the latest snapshot. 

### Suspected cause

No java 21

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by byquanton** [comment]
https://github.com/flathub/org.prismlauncher.PrismLauncher/pull/54
