### ISSUE TITLE
Wrong cursor in Plasma 6

### ISSUE THREAD

**Issue by MaledictYtb** [PrismLauncher/PrismLauncher#2266]
### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

![image](https://github.com/PrismLauncher/PrismLauncher/assets/94766634/30307ddc-edaf-4274-a739-1c7d3d383114)

As you can see I have a big weird cursor. 

![image](https://github.com/PrismLauncher/PrismLauncher/assets/94766634/3026ba13-f4f6-46e1-b959-bfcaa17a4aa6)

Outside prism I have my normal cursor. 

### Steps to reproduce

Install prism from flathub with Plasma 6

### Suspected cause

Plasma 6 ? 

I only have this problem since I've updated from Fedora Kinoite 39 (Plasma 5) to Fedora Kinoite 40 (Plasma 6)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Are you sure you're using the qt6 build?

**Comment by MaledictYtb** [comment]
I'm using the latest flatpak version.

**Comment by DioEgizio** [comment]
Since you're on flatpak you're still using the qt5 build. Try using the flatpak from flathub beta as that should be qt6

**Comment by MaledictYtb** [comment]
It's fixed in the beta, thanks !
