### ISSUE TITLE
A Java version selector in the "New Instance" menu

### ISSUE THREAD

**Issue by Remdrift** [PrismLauncher/PrismLauncher#2271]
### Role

I sometimes want to quickly create an instance and launch it immediately

### Suggestion

An option to select the Java version while creating an instance

### Benefit

I would not need to take the extra step of editing the Java version of an instance after creating it

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by draeath** [comment]
A means to set the other java parameters during this process (memory and arguments) would also be welcome.

**Comment by Krutonium** [comment]
As a rider to this I think it would be an automatic selection of the correct java version if it's installed, but not selected when you try to launch the game.

**Comment by Aces-and-Jacks** [comment]
While it's not an option in the "New Instance" menu, version 9.0 of prism has a feature that auto detects the version of java needed with that instance

**Comment by Trial97** [comment]
Closing in favor of the 9.0 java autodetect
