### ISSUE TITLE
Modrinth packs don't install all mods

### ISSUE THREAD

**Issue by donottellmetonottellyou** [PrismLauncher/PrismLauncher#2274]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.0/8.2 nixpkgs

### Version of Qt

Qt 6.6.3

### Description of bug

Installing The Vanilla Experience 7.7 from Modrinth fails massively, only installing 32 of the 139 mods. Installing The Vanilla Experience from Curseforge seems to work fine as far as I can see.

### Steps to reproduce

Download The Vanilla Experience 7.7 from the Modrinth portal. Download The Vanilla Experience 7.7 from the Curseforge portal. Compare.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
see: https://github.com/PrismLauncher/PrismLauncher/pull/2142#issuecomment-1953146452

**Comment by Trial97** [comment]
Also tested with modrinth launcher and is happening the same: it downloads only 32 mods.
So this is an issue with the pack not prism

**Comment by donottellmetonottellyou** [comment]
So if the env is
```json
{
        "server": "unsupported",
        "client": "required"
}
```
It installs it. Hence the 32 mods:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/115233539/15d1230b-9ead-4a73-9e0f-8813f0808a81)

But if the env is
```json
{
        "server": "required",
        "client": "unsupported"
}
```

It doesn't install it.
That doesn't seem consistent to me, especially if "server" is assumed for a "client" install. I could mention this to "The Vanilla Experience" author Serilium and this could be fixed there, but I do feel that it would make sense at least for `"server": "required"` to override `"client": "unsupported"`, just like how `"client": "required"` overrides `"server": "unsupported"`. At least to me, it seems to violate [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). Though I don't know who should fix it as I don't know much. Should this be reported to Serilium, or is this a Prismlauncher issue? Or is this an issue best brought up to the Modrinth team?

**Comment by donottellmetonottellyou** [comment]
Sorry, didn't see your comment :) will report this to Serilium
