### ISSUE TITLE
Flathub page gives 404

### ISSUE THREAD

**Issue by Kingproone** [PrismLauncher/PrismLauncher#2284]
### Operating System

-

### Version of Prism Launcher

-

### Version of Qt

-

### Description of bug

https://flathub.org/apps/org.prismlauncher.PrismLauncher
i also submitted an issue on:
https://github.com/flathub/org.prismlauncher.PrismLauncher/issues/55

### Steps to reproduce

open https://flathub.org/apps/org.prismlauncher.PrismLauncher

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
https://github.com/flathub/org.prismlauncher.PrismLauncher/issues/55 is the right place to report this
