### ISSUE TITLE
can't launch online with cloudflare warp 

### ISSUE THREAD

**Issue by Thanoid1** [PrismLauncher/PrismLauncher#2285]
### Operating System

Windows

### Version of Prism Launcher

prism launcher 8.2

### Version of Qt

qt 6.6.2.

### Description of bug

When launching instances, prism launcher fails to connect to any internet. When I turn off my vpn, it works. It used to work fine a few days ago, but it doesn't work anymore

### Steps to reproduce

1. turn on cloudflare vpn
2. launch any instance
3. wait for loading

### Suspected cause

Cloudflare warp is causing the issue, but it worked until a few days ago.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
If it worked before it is the VPN issue, not Prism.
Also if it works without it means that the VPN is blocking some requests.
Closing this as there is no way Prism can fix your VPN.

**Comment by Thanoid1** [comment]
it works for my friends that also use the same vpn

**Comment by TheFruxz** [comment]
Verified, that this issue still persists
