### ISSUE TITLE
Changing Minecraft folder when updating instance

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#2299]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.4.2

### Description of bug

I have instance **Fabulously Optimized 5.9.0** with
```
Minecraft folder is:
/home/<redacted>/.local/share/PrismLauncher/instances/Fabulously Optimized/minecraft
```

Right click instance -> **Edit** -> **Modrinth** -> Select **5.9.1** -> Click **Update pack** -> Say **Yes** to update name
Launch it!
And...

```
Minecraft folder is:
/home/<redacted>/.local/share/PrismLauncher/instances/Fabulously Optimized/.minecraft
```

Minecraft folder is now changed *(and because of that my worlds is not visible now)*!

### Steps to reproduce

I was unable to reproduce it with new **Fabulously Optimized 5.9.0** instance

### Suspected cause

Maybe **Prism Launcher** is not checking already existing folder name - **minecraft** or **.minecraft** - before extracting new files?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Can you reproduce it consistently? Like if you create a new instance from 0 does it still happen?
Can you share the prism logs from when this happened?
Does your instance work after the update?

**Comment by ghost** [comment]
> Can you reproduce it consistently?

Yes, i have backup of that instance **(Fabulously Optimized 5.9.0)** and if i update that instance to **5.9.1** i can reproduce it

> Like if you create a new instance from 0 does it still happen?

No

> Does your instance work after the update?

When i first encountered this issue - no, and in **.minecraft** folder was only one mod - **Polytone** (of course without dependencies it crashed) _(i don't have logs or backup when this happened, sorry)_
When i tried to reproduce issue - **yes**, instance is working

**Comment by Trial97** [comment]
This may be already solved in the nightly builds and most probably it will be official in the 9.0.
But the strange thing is that prism doesn't create the "minecraft" folder for modrinth instances, only on dev build is this happening. So my question is did you manually renamed the folder after you installed the modpack or did you install the modpack with a dev build ?

**Comment by ghost** [comment]
> did you install the modpack with a dev build ?

Yes :)
