### ISSUE TITLE
Downloading mods from browser windows

### ISSUE THREAD

**Issue by MbtMarco** [PrismLauncher/PrismLauncher#2300]
### Role

I create modpack.

### Suggestion

Download mods from browser windows without having to search for them from the launcher.

### Benefit

If I open a lot of windows in the browser because I am looking for a lot of mods to put in and I want to see the full Modrinth/Curseforge interface for all the information, it would be handy to be able to download them all by simply dragging/copying the link in a launcher window.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

(In case dragging and dropping them is not possible, the launcher window should allow you to paste multiple links and separate them with a ; or similar without doing it individually for each mod)

**Comment by Trial97** [comment]
For curseforge this is already possible by clicking the Install button:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/d28052f3-f5f1-406d-ad32-4ebb2177a724)

Sadly for modrinth they do not provide any button that would let us do that.

But I consider dragging the URL inside the launcher to download the mods to be harder than searching for them inside the Download Mods dialog and for you as you would need to confirm for each on what instance to install.
