### ISSUE TITLE
Allow mods to be downloaded directly from the source using the index files

### ISSUE THREAD

**Issue by SimplisticGH** [PrismLauncher/PrismLauncher#2301]
### Role

I play modded Minecraft, and build modpacks sometimes.

### Suggestion

This is essentially mrpack and "cfpack" but as a toggle option for normal zip exports. Because as far as I'm aware you cant mix CF and Modrinth packs.

### Benefit

It seems pointless for me to have to essentially own a CDN to host large ~1 GiB sized modpacks when they can be directly downloaded from the sources on the client side

### This suggestion is unique

- [ ] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This is most likely a duplicate, but I couldn't find anything with the search terms i was using.

**Comment by Trial97** [comment]
My suggestion here is to use packwiz (the index files should be usable in the packwiz):
- https://github.com/PrismLauncher/PrismLauncher/issues/591
- https://github.com/PrismLauncher/PrismLauncher/issues/2117
But regarding creating our pack format see: https://github.com/PrismLauncher/PrismLauncher/issues/1182
Closing this as the mentioned tickets should cover your use case.
