### ISSUE TITLE
Version section empty after system has no more storage

### ISSUE THREAD

**Issue by kevinyyca** [PrismLauncher/PrismLauncher#2306]
### Operating System

Linux

### Version of Prism Launcher

`Prism Launcher 8.2`

### Version of Qt

Qt 5.15.10

### Description of bug

# Playing the game
I was just playing Minecraft when i got a Java error i ignored it.
then i decided to create a short replay in Replay Mod

# The error
I disconnected from the server i was on and Replay mod gave me an error.
I tried restarting my game but when i started the game again it gave me a error.

# No more storage
A bit after the errors i tried to install a Flatpak and realized i didn't have anymore storage 100% used

# Their gone (Main part)
The next day. After i delete 4 Timeshift backups. And i tried playing Minecraft it gave me an error **different** from the one i got when trying to restart the game.

I selected my instance and did `ctrl` + `i`. I went to the **version section** and saw...
![image](https://github.com/PrismLauncher/PrismLauncher/assets/121273910/b35ec74b-980b-415a-8631-a39b7be6d4e4)

The section was **empty**!
My mod loader was gone! And my Minecraft i couldn't change the version of it or anything!

### Steps to reproduce

1. Enter a world
2. Use up all of your storage
3. Restart your game
4. Get a error
5. Restart the launcher???
6. Look in your instance and go to the `version section`
7. Their gone

8. This probaly doesn't work i don't know how this happened

### Suspected cause

Storage used up???

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by maskersss** [comment]
it sounds like `mmc-pack.json` and/or `instance.cfg` got corrupted? would it be possible for prism to do something differently so they don't get corrupted when running out of disk space?

**Comment by Trial97** [comment]
Prism can't prevent corruption of the files due to running out of disk space.
Prism needs to change the files like config to log the time played so there is nothing that can be done.
