### ISSUE TITLE
Prism uses wrong LWJGL architecture

### ISSUE THREAD

**Issue by maskersss** [PrismLauncher/PrismLauncher#2308]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

I expected the instance to launch. It crashed :(

### Steps to reproduce

- make a 1.18.2 instance with Forge
- change LWJGL version to 3.3.1
- launch the instance
- it should crash

### Suspected cause

Prism/Minecraft for some reason tries to use LWJGL for ARM?
for me:
- this crash doesn't happen without Forge, happens on Forge 40.2.0 and 40.2.18
- this crash only happens with LWJGL 3.3.1, 3.3.2, 3.3.3; but not with 3.2.2
- this crash doesn't seem to happen on multimc: https://mclo.gs/dNY59L8

prism log: https://mclo.gs/orAJsDb
prism log with `-Dorg.lwjgl.util.Debug=true`: https://mclo.gs/OByVAPX

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
IIRC Forge didn't support the new natives format used in LWJGL 3.3.x. It should work fine with Forge versions for Minecraft 1.19 onwards.

We can't really fix old Forge versions in this regard

**Comment by maskersss** [comment]
oh, i see
to run multimc with LWJGL 3.3.1, i did `Edit instance > Version > LWJGL > Edit > Customize` > {paste the contents of https://raw.githubusercontent.com/MultiMC/meta-multimc/master/org.lwjgl3/3.3.1.json}; which, i guess, significantly differs from what prism uses? i tried doing the same thing with prism, and prism worked with LWJGL 3.3.1 as well

**Comment by Scrumplex** [comment]
MultiMC's LWJGL works, because they never implemented the new way of dealing with natives. They are stuck on a release of 3.3.1 that doesn't support arm64 like this

**Comment by maskersss** [comment]
i see, makes sense; ig you can close the issue if it's not going to be fixed
