### ISSUE TITLE
Build won't start

### ISSUE THREAD

**Issue by nmsltr** [PrismLauncher/PrismLauncher#2313]
### Operating System

windows 10

### Version of Prism Launcher

prism 8.2

### Version of Qt

6.6.2

### Description of bug

I downloaded one mod through the official loader, and the assembly just stopped loading. The last thing the launcher does when turned on is load the mod, then just stop (saw it through the minecraft magazine). Moreover, the rest of the assemblies work quietly.

### Steps to reproduce

Starting the build ._.

### Suspected cause

Perhaps because I downloaded the mod through the launcher and some error occurred, but I'm not sure.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
The thing you describe as the build I will presume is the instance itself: aka after adding a mod to the instance your instance doesn't start anymore. 
Solution disable the mod and try again. If you want to use that mod ask about the crash on their support channel. 
This doesn't sound like a prism issue but one with the mod and that specific instance so I will close this.

**Comment by nmsltr** [comment]
> The thing you describe as the build I will presume is the instance itself: aka after adding a mod to the instance your instance doesn't start anymore. Solution disable the mod and try again. If you want to use that mod ask about the crash on their support channel. This doesn't sound like a prism issue but one with the mod and that specific instance so I will close this.

I removed this mod but the build still doesn't work.

**Comment by nmsltr** [comment]
Here is the complete list of mods. Maybe you can find some discrepancy
![Uploading image.png…]()

**Comment by Trial97** [comment]
For this kind of issue feel free to ask in Prism discord: https://prismlauncher.org/discord
