### ISSUE TITLE
Windows Defender detection upon selecting certain Mods

### ISSUE THREAD

**Issue by CytricAcid** [PrismLauncher/PrismLauncher#2315]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.2 

### Version of Qt

QT 6.6.2

### Description of bug

While browsing mods to install, Windows Defender detects a trojan horse in the cache files.

### Steps to reproduce

* Edit an Instance of Minecraft 1.20.1 with Fabric 0.15.9
* In the Mods tab, go to Download Mods
* Under Modrinth, search up Ad Astra
* Click on the mod Ad Astra
* Windows Defender should automatically detect and quarantine a Trojan:Win32/Casdet!rfn

### Suspected cause

Genuinely not sure if the mod itself is compromised or something in Prism's code is causing this. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Prism doesn't host any mods so this is a issue with that specific mod.
