### ISSUE TITLE
Discord RPC integration?

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#232]
### Role

I use it as my main method of playing Minecraft, and like people knowing how I'm playing.

### Suggestion

I want Prism Launcher to forward the player status (what instance is running, what version, how long they've been playing, possibly how many mods are installed) to Discord Rich Presence.

### Benefit

This could allow for a more universal way to announce your status to Discord friends, rather than downloading mods for different versions.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I do think if it is implemented it might do good to have a flag per instance, in case the user does prefer to have status updates from a mod in their instance.

In terms of determining what instance is running, maybe the last launched?

Adding the option for custom Discord application tokens, just like the Microsoft authentication, would also be great!

**Comment by snoweuph** [comment]
We Need this

**Comment by madeline0706** [comment]
would love this

**Comment by Adaliciously** [comment]
This would be awesome, we have mods but you would need to install them separately for each instance and set configs.

**Comment by TheKodeToad** [comment]
Discord's SDK is unforunately closed source... but there are some open source reimplementations out there! I'm not sure if there's a C++ one though.

**Comment by TheKodeToad** [comment]
After doing some research it seems like the old https://github.com/discord/discord-rpc still works fine.

**Comment by TheKodeToad** [comment]
Little update: it seems like this is unlikely to be a feature in the launcher as mods can do this better.

**Comment by Adaliciously** [comment]
> Little update: it seems like this is unlikely to be a feature in the launcher as mods can do this better.

Thats assuming user has mods, what if they don’t?

**Comment by Scrumplex** [comment]
We can not add Discord's RPC SDK to Prism Launcher as it's proprietary and therefore incompatible with our software license.
Apart from that, the launcher doesn't know a lot of what you are doing in-game, so any Discord RPC mod is going to be able to provide more information than the launcher. I would therefore say that this is out of scope for Prism Launcher.

**Comment by TheKodeToad** [comment]
https://github.com/MultiMC/Launcher/blob/develop/libraries/launcher/org/multimc/onesix/OneSixLauncher.java#L81
Maybe we should implement something like this?
Maybe in the Prism namespace - although multimc could be added too for compat I suppose

**Comment by qaptivator** [comment]
honestly just showing what instance is currenlty running and its playtime would be nice

**Comment by gamiel-7-2** [comment]
couldn't we have something like Modrinth , where it would show the launcher's logo, the instance running and its playtime?

**Comment by CompeyDev** [comment]
There has been some development in this space since the last decision was made, there is [a library](https://github.com/EclipseMenu/discord-presence) to do this in C++. 

As @gamiel-7-2 said, it would be worth having something similar to Modrinth's Launcher, which also uses a community Rust library to deal with the RPC. Can we consider reopening this issue now?

**Comment by TheKodeToad** [comment]
This was also stated in the reason for closing:

>  Apart from that, the launcher doesn't know a lot of what you are doing in-game, so any Discord RPC mod is going to be able to provide more information than the launcher. I would therefore say that this is out of scope for Prism Launcher.

Also, the linked library is C++23 only

**Comment by Sonic3Modder** [comment]
Also, It seems many other launchers include this including, Modrinth, Curseforge, and Lunar, most likely persuading most people to go for the others

**Comment by stephen304** [comment]
> Apart from that, the launcher doesn't know a lot of what you are doing in-game

What if I just want it to say I'm playing Minecraft? I don't use mods and just want people to know that I'm playing. Is there an easy way to accomplish that without futzing with mods?

> Also, It seems many other launchers include this

I'm actually trying curseforge for this, but hilariously out of the box it only seems to show rich presence for what I'm doing in the manager app (like "choosing  a game" and "managing mods"), but nothing when I'm actually playing a vanilla minecraft game. I'll keep trying others.

**Comment by MCTMS8** [comment]
> > Apart from that, the launcher doesn't know a lot of what you are doing in-game
> 
> What if I just want it to say I'm playing Minecraft? I don't use mods and just want people to know that I'm playing. Is there an easy way to accomplish that without futzing with mods?
> 
> > Also, It seems many other launchers include this
> 
> I'm actually trying curseforge for this, but hilariously out of the box it only seems to show rich presence for what I'm doing in the manager app (like "choosing a game" and "managing mods"), but nothing when I'm actually playing a vanilla minecraft game. I'll keep trying others.

Modrinth has a Modrinth RPC and the base Minecraft RPC
@stephen304

**Comment by NyteWL** [comment]
RPC mods can not resovle the issue that Discord's game overlay don't works in game because discord still can not detect the real game.

**Comment by gamiel-7-2** [comment]
> RPC mods can not resovle the issue that Discord's game overlay don't works in game because discord still can not detect the real game.

yup.
