### ISSUE TITLE
Skin manipulation for offline accounts.

### ISSUE THREAD

**Issue by kjukmar2** [PrismLauncher/PrismLauncher#2321]
### Role

I play modded minecraft and prefer to do it through an offline account

### Suggestion

Manage local skins for offline accounts through PrismLauncher

### Benefit

so that people won't have to rely on microsoft for their identity and skins.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Sometimes microsoft servers won't allow me to connect and use my online account. In such cases i would have to play with an offline account and deal with microsoft's new default skin selection, which isn't quite pleasant. I tried to modify the accounts.json file and the files in ~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/assets to no result. I just want to be the default Steve again, even offline.

**Comment by Trial97** [comment]
There are mods and resource packs that achieve this so this will not be implemented in prism

**Comment by Alexprox7** [comment]
I think it would be best to do it without mod, would be great with maybe a little gui. Prism has it all expect for this

**Comment by LunaticWasTaken** [comment]
> I think it would be best to do it without mod, would be great with maybe a little gui. Prism has it all expect for this

The actual ingame-skin system is managed by the game itself, not by prism, or any launcher. There's no way to handle those from outside the game, even if someone wanted to.
All that prism does e.g. on online skins is to send requests the the Mojang/Microsoft Servers to change the skin that ***the game*** loads.

If you want modified skins in offline mode, what you need is either A: A Resourcepack, or B: A modified Client (e.g. through a mod). And Prism won't inject custom code into your client jar.

**Comment by Alexprox7** [comment]
> > I think it would be best to do it without mod, would be great with maybe a little gui. Prism has it all expect for this
> 
> The actual ingame-skin system is managed by the game itself, not by prism, or any launcher. There's no way to handle those from outside the game, even if someone wanted to.
> All that prism does e.g. on online skins is to send requests the the Mojang/Microsoft Servers to change the skin that ***the game*** loads.
> 
> If you want modified skins in offline mode, what you need is either A: A Resourcepack, or B: A modified Client (e.g. through a mod). And Prism won't inject custom code into your client jar.

Got it thank you
