### ISSUE TITLE
Modpack to Server Side only

### ISSUE THREAD

**Issue by MbtMarco** [PrismLauncher/PrismLauncher#2323]
### Role

I create modpacks.

### Suggestion

Allow you to create an instance from a modpack with only server side mods to make it easier to create servers from a modpack. 

### Benefit

When creating a modded server it is preferable to only insert mods for the server, those for the client are useless and increase occupied memory and startup time. In the case i want to upload a modpack to a server I have to manually identify and delete all useless mods (Client side only). If there was the possibility of having the launcher do it in a few seconds it would make the job much faster and safer. (No chance of being wrong) 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I take the idea from here:
https://github.com/modrinth/theseus/issues/1124

**Comment by Trial97** [comment]
This falls under https://github.com/PrismLauncher/PrismLauncher/issues/864 so I will gonna close this as duplicate
