### ISSUE TITLE
Can't detect java bundled with launcher on mac

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#2332]
### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

According to the pr there should be a path pointing to the java bundled with the minecraft launcher

### Steps to reproduce

Open minecraft launcher.
Launch game. 
detect java on prism (before or/and after game launch)
No path shows

### Suspected cause

Mac issue?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment]
#1685 I didn't see any issue related to this for mac

**Comment by Trial97** [comment]
Can you check the `~/Library/Application Support/.minecraft/runtime` path? Does it exist? Does it contain java?

**Comment by Aces-and-Jacks** [comment]
`/Users/****/Library/Application Support/minecraft/runtime/java-runtime-gamma/mac-os-arm64/java-runtime-gamma/jre.bundle/Contents/Home/bin/java` this is where it's located, I think

**Comment by Trial97** [comment]
Ok I did change the path for mac: hope it works with that patch

**Comment by Aces-and-Jacks** [comment]
Thanks. Hope I was correct
