### ISSUE TITLE
Auto-detection of Java installed through SDKMAN! on macOS

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#2336]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.6.3

### Description of bug

This issue is very similar to #1477, but on macOS. Launcher won't detect jdks installed through sdkman. 

### Steps to reproduce

- Install the launcher through Homebrew
- Download sdkman via curl [sdkman download docs](https://sdkman.io/install)
- Install any jdk through sdkman on macOS 
<img width="326" alt="image" src="https://github.com/PrismLauncher/PrismLauncher/assets/152516748/1db3c587-d0a1-4c39-8cdd-de1266ced7a5">

- Try to auto-detect java installations in the launcher
<img width="388" alt="image" src="https://github.com/PrismLauncher/PrismLauncher/assets/152516748/3561c3d0-e852-48af-bd7c-cb77430c3357">

### Suspected cause

Maybe something similar to #1477?
Seems like #1682 was implemented incorrectly or affects only Linux.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is not a bug: sdkman was not supported on mac by prism

**Comment by dqfan2012** [comment]
@Trial97 

This is from the sdkman website: [sdkman install page](https://sdkman.io/install)

![image](https://github.com/PrismLauncher/PrismLauncher/assets/3586389/33148c28-6fc8-4248-a015-f1af0a0a1c73)

sdkman isn't supported on Mac? That's not what their website seems to indicate.

Update

I thought this was an excellent moment to contribute to open source software and I created a pull request to address this situation in MacOs.

**Comment by Trial97** [comment]
What I meant is that prism did not support sdkman on Mac,like the original issue only required to implement it for Linux, so the issue is not a bug but an enchantment. 
My statement was strictly directed to the label of the issue.
