### ISSUE TITLE
Breeze Light/Dark are inverted in MacOS

### ISSUE THREAD

**Issue by MbtMarco** [PrismLauncher/PrismLauncher#2338]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 8.3

### Description of bug

<img width="978" alt="Screenshot 2024-04-24 alle 16 48 28" src="https://github.com/PrismLauncher/PrismLauncher/assets/124934175/ed0d1d16-c5b3-46c7-9d8d-b072fd4ca008">

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Not an issue: they are meant to be used with the corresponding themes so the light icons are for the dark theme and the dark icons are for the light, that is why the names are reversed
