### ISSUE TITLE
official launcher java doesn't get auto-detected since 8.3

### ISSUE THREAD

**Issue by maskersss** [PrismLauncher/PrismLauncher#2342]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3 does not work
Prism Launcher 8.2 does work

### Version of Qt

Qt 6.6.3

### Description of bug

I have Java installed from the official launcher in `...\AppData\Local\Packages\Microsoft.4297127D64EC6_8wekyb3d8bbwe\LocalCache\Local\runtime\java-runtime-gamma\windows-x64\java-runtime-gamma\bin\javaw.exe` and in `...\AppData\Local\Packages\Microsoft.4297127D64EC6_8wekyb3d8bbwe\LocalCache\Local\runtime\jre-legacy\windows-x64\jre-legacy\bin\javaw.exe`. I expected it to get autodetected by Prism.
It didn't get autodetected by Prism.

### Steps to reproduce

- install official launcher through whichever way i did it (no clue lol)
- launch the game to make it install java
- press Auto-Detect in prism

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
fixed by https://github.com/PrismLauncher/PrismLauncher/pull/2337
