### ISSUE TITLE
Desktop enviroment crashing

### ISSUE THREAD

**Issue by shaweel** [PrismLauncher/PrismLauncher#2343]
### Operating System

Arch Linux with the KDE Plasma 6.0.4 desktop enviroment using the X11 graphics server

### Version of Prism Launcher

Prism Launcher 8.2 - I have downloaded it from the Arch User Repository

### Version of Qt

Qt 6.7.0

### Description of bug

I am using Arch Linux with the KDE Plasma 6.0.4 using the X11 graphics server. Sometimes my desktop enviroment randomly freezes with you not being able to do anything, it only happens while using Prism Launcher, my friend also tried Prism Launcher and started experiencing the same issue, so he stopped using the launcher and the issue went away.

### Steps to reproduce

* Install Arch Linux with the KDE Plasma 6 desktop enviroment using the X11 graphics server
* Install the prism-launcher package from the Arch User Repository
* Open Prism Launcher
* Launch Minecraft
* In some time your desktop enviroment will freeze

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ItsTheNumberH** [comment]
Exactly the same issue here.

Linux Mint 21.3, Cinnamon

Have experienced with any number of windows/applications open, even with only the single window for Minecraft via Prism launcher. No specific situation seems to specifically cause it, seems random here too.
Appears to happen more when another application is opened or switched to, but that's possibly coincidental.

**Comment by shaweel** [comment]
> Exactly the same issue here.
> 
> Linux Mint 21.3, Cinnamon
> 
> Have experienced with any number of windows/applications open, even with only the single window for Minecraft via Prism launcher. No specific situation seems to specifically cause it, seems random here too. Appears to happen more when another application is opened or switched to, but that's possibly coincidental.

for me it stopped doing it after some updates

**Comment by ItsTheNumberH** [comment]
I hate to comment on a closed issue, but this is still a problem. Latest version, it still causes the same freezing problem as before. Nothing in either Minecraft logs, nor system logs, to help identify it either annoyingly.
If this helps:
NVidia 970, driver: 550.107.02-0ubuntu0.22.04.1
No other software has encountered this issue so I'm struggling to identify what in Prism launcher might trigger it.

**Comment by alaestor** [comment]
This is the first thing I found while looking for this bug... NixOS Plasma 6 X11 amdgpu. The problem is very reproducible in my case. Given that multiple people have experienced this, I'll make a new issue...

**Comment by alaestor** [comment]
Woops... In my case, I narrowed it down to the FPS-monitor mod and opened an issue over there. Good luck folks.
