### ISSUE TITLE
FTB App Import

### ISSUE THREAD

**Issue by spookytea** [PrismLauncher/PrismLauncher#235]
### Role

Playing curseforge packs

### Suggestion

Import from FTB App

### Benefit

Easier to install without having to manually install mods

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
how is installing a separate electron buggy launcher better than just using the one you're currently using? i don't agree

**Comment by TheAirBlow** [comment]
@DioEgizio does the FTB App bypass Curse ToS or does FTB have some special agreement with Curse? Can you please explain this?

**Comment by DioEgizio** [comment]
They have a deal with overwolf. In fact, that's why part of the ads in it goes to overwolf/creators

**Comment by Poopooracoocoo** [comment]
> how is installing a separate electron buggy launcher better than just using the one you're currently using? i don't agree

For some people it's easier than using the CF workaround in Prism. 
MultiMC has implemented FTB App importing, might I add. See their [wiki](https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks) and their [post](https://multimc.org/posts/0-6-16-update.html). 
And as discussed on the Prism Launcher Discord server, it takes a long time to load FTB modpacks in Prism Launcher.

**Comment by DioEgizio** [comment]
> It takes a long time to load FTB modpacks in Prism Launcher.

As much if not less than the FTB app

**Comment by TheAirBlow** [comment]
> > how is installing a separate electron buggy launcher better than just using the one you're currently using? i don't agree
> 
> For some people it's easier than using the CF workaround in Prism. MultiMC has implemented FTB App importing, might I add. See their [wiki](https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks) and their [post](https://multimc.org/posts/0-6-16-update.html). And as discussed on the Prism Launcher Discord server, it takes a long time to load FTB modpacks in Prism Launcher.

The CF workaround works perfectly. Just get some addon like Fast Forward, which will skip the 5 second delay. Additionally, it will skip other annoyances like adfly, and warn you about IP loggers.

**Comment by TheAirBlow** [comment]
Following up, they implemented all of that because they had problems with Curseforge API ToS (as said in their post), and probably something similar with FTB. So it was a targeted attack on that launcher, because it's not giving them the yummy ad money.

**Comment by DioEgizio** [comment]
We'll need this because of https://github.com/PrismLauncher/PrismLauncher/pull/1040

**Comment by Nik-Kot** [comment]
Isn't MultiMC already capable of importing FTB app packs? Can we port the code from there and adapt it?

**Comment by Nik-Kot** [comment]
https://github.com/MultiMC/Launcher/tree/develop/launcher/ui/pages/modplatform/import_ftb

**Comment by DioEgizio** [comment]
> Isn't MultiMC already capable of importing FTB app packs? Can we port the code from there and adapt it?

No because mspl

**Comment by Nik-Kot** [comment]
> > Isn't MultiMC already capable of importing FTB app packs? Can we port the code from there and adapt it?
> 
> No because mspl

The licenst says some parts are Apache 2.0 and only some are MSPL. Concidering how similar the code would be if we whote it from a scratch - this is worth looking into.

**Comment by DioEgizio** [comment]
> > > Isn't MultiMC already capable of importing FTB app packs? Can we port the code from there and adapt it?
> > 
> > 
> > No because mspl
> 
> The license says some parts are Apache 2.0 and only some are MSPL. Concidering how similar the code would be if we wrote it from a scratch - this is worth looking into.
> 
> Edit: I have noticed the files themselves have MSPL license. This is bad (and why?).

No, every new file is mspl
And yes it is bad, mspl and GPL are incompatible, so we can't use them here

**Comment by Nik-Kot** [comment]
> No, every new file is mspl And yes it is bad, mspl and GPL are incompatible, so we can't use them here
Asked about this on MultiMC discord and found out tht they are against GPL because it is too invasive/restrictive. What a needess license battle while everyone authoring the code is not actually against forks using it.

**Comment by DioEgizio** [comment]
This isn't the place for that endless drama. Just note that we can't pull from there nor they can pull from us. At this point every discussion about it is just useless drama that it's just a time waste

**Comment by Nik-Kot** [comment]
> This isn't the place for that endless drama. Just note that we can't pull from there nor they can pull from us. At this point every discussion about it is just useless drama that it's just a time waste

Sorry for this, was my first time encountering something like this. I can delete my comments is needed.

**Comment by mkaito** [comment]
One of the main reasons I use Prism, aside from it actually being a good launcher, is Apple Silicon support. While the FTB App runs on these chips, its Minecraft instances do not. Could you please keep this in mind when you get around to working on importing FTB instances?

**Comment by TheKodeToad** [comment]
I don't think there will be an issue as they are converted into native prism instances (#1359)
