### ISSUE TITLE
The prismlauncher aur package still uses java 17

### ISSUE THREAD

**Issue by chrrybmb64** [PrismLauncher/PrismLauncher#2356]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.7.0

### Description of bug

This isn't necessarily a bug, but I've brought this up in the package's comments and in the Prism Launcher discord and gotten no response in either place. The `prismlauncher` aur package still requires Java 17, meaning I am forced to keep it installed even though I do not play any Minecraft version that uses it.
### Steps to reproduce

1. install `prismlauncher` from the aur using your preferred aur helper

2. it asks you to install java 17

### Suspected cause

The maintainers forgot to change it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Java 17 is still needed for a good part of the Minecraft versions. Java 21 is only supported by the latest version of Minecraft so it may not be a high priority to change that yet.

**Comment by chrrybmb64** [comment]
Java 17 can be made an optional dependency, just as Java 8 is. I understand your point though.

**Comment by chrrybmb64** [comment]
Closing since Prism Launcher is now in the official extra repository and can use any java version.
