### ISSUE TITLE
[RFC] Support vanilla instance format

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#236]
### Goal

Add a toggle in options to convert all existing instances and make all new ones in the vanilla instance format.

### Motivation
The MMC instance format is good for managing multiple instances at once, but it has its downsides:
- It takes most direct control out of the hands of the user. One can't use a conventional modloader installer on MMC/Prism, instead they must have very advanced knowlege to fiddle with .json files, maybe try getting the jar by creating a vanilla launcher instance, do a lot more banging against a wall, etc. just to install an exotic mod loader which does not provide excplit support for MMC.
 - The user is dependant on the launcher's UI. Unless you want and can fiddle with jsons, you have to act on the instance through the UI, which may be buggy or inintuitive at times (especially when it comes to custom .jar-s and jarmods)
 - It's confusing for newbies.

### Specification

Add a toggle in the settings to switch to the vanilla instance format 
(so, for example, one can use an installer to install a modloader into Prism Launcher, the jars and the assets are stored separately in each instance's folder, a launcher profiles index file is present and synced with the actual instances so loader installers work, etc.)
Such a toggle will have to automaticially convert all existing instances to the other format, so it should have a popup warning applied that it may be a destructive and lengthy action.

### Drawbacks

Additional development and maintenance burden.

### Unresolved Questions

How exactly would such a convertion go through, from the sides of backend and frontend?
Should the vanilla instance format be used by default?

### Alternatives Considered

A simple option to import instances from vanilla launcher, see #244 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TayouVR** [comment]
I don't understand why you would need this... You can install custom jar mods via the UI and all common mod loaders can be installed directly. For more weird things like Optifine its a bit more complicated as you have to unpack the optifine installer before adding the jar mods, but changing how the minecraft jar files are stored doesn't make a lot of sense. The existing folder structure is close to vanilla, only the "versions" folder is elsewhere... I suppose what we could do is symlink the jars into the instance folder... but I think this is such a rarely needed thing, that you might as well do it yourself.

I am talking from my experience, if its way more common than I think please do prove me wrong though!

**Comment by ghost** [comment]
> 

It's just for exotic cases and some installers. Also, it's way off from vanilla - there isn't a versions index, the jar-s are stored elsewhere, etc.

**Comment by Madis0** [comment]
I think this would need way too many things to be reworked without a clear benefit to the launcher itself. What about simply importing "installations" from the vanilla launcher to Prism Launcher?

**Comment by ghost** [comment]
That would be a good alternative solution. I think there already is an issue for this + i'll add this to the alternatives list now.

**Comment by ghost** [comment]
Closing this because it's stupid
