### ISSUE TITLE
Beta/Alpha versions missing

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#2362]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt version 5.15.10

### Description of bug

When selecting the Beta and Alpha categories of versions, no versions appear in the list:
![Screenshot_20240430_125650](https://github.com/PrismLauncher/PrismLauncher/assets/26670632/0735474c-d32e-4cf2-b0b5-cf06c3e985f8)

### Steps to reproduce

* Create a new or edit an existing instance,
* Check the Beta, Alpha or both tick marks,
* No relevant versions appear in the list.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is due to a meta change that we did recently.
The alpha and betas are still there but the filter checkbox doesn't work. 
So you will need to find them manually.
This was already fixed in the latest develop and will be released in 8.4.
