### ISSUE TITLE
Mod metadata parser does not respect installed loader for instance

### ISSUE THREAD

**Issue by isXander** [PrismLauncher/PrismLauncher#2364]
### Version of Prism Launcher

8.2

### Version of Qt

6.6.2

### Description of bug

When parsing the mod metadata in the below method:

https://github.com/PrismLauncher/PrismLauncher/blob/bfac12604e9cd0884987ca89f34a455cf16c543c/launcher/minecraft/mod/tasks/LocalModParseTask.cpp#L462-L593

An arbitrary order is used for trying the various formats, `mods.toml` first, `fabric.mod.json` later.

Some mods, such as YACL 3.4.2 Fabric, happen to include both in the same jar; this can be done for multiple reasons. For YACL, it is purely done to make the buildscript less complex, others may provide compatibility for multiple loaders in the same jar.

In most cases where this bug manifests, users may not even notice this since the metadata might be the same for both loaders. In YACL's case, variables are not filled in the other loads, resulting in the mod appearing to be called `${name}`.

Obviously this is trivial to fix on my end, I just thought it was worth reporting if you wanted to fix it at a launcher level. 

### Steps to reproduce

* Create a jar with both `mods.toml` and `fabric.mod.json` (or use YACL 3.4.2 fabric)
* Use different metadata for each
* Notice always `mods.toml` data is used.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
I don't really know how this should work. How could the launcher know which file is more correct?

**Comment by isXander** [comment]
> I don't really know how this should work. How could the launcher know which file is more correct?

It knows what loader is installed in the instance, just correlate it.

**Comment by Trial97** [comment]
In 9.0 this may not longer the case as you would be able to download mods for all loader types so that is not a option. 
So my suggestion here is to sugest the change in the mod, or identify a way for us to determine the correct loader based on content of the jar.

**Comment by isXander** [comment]
You can identify a fabric jar through its manifest. Here's an example:
```
Manifest-Version: 1.0
Fabric-Jar-Type: classes
Fabric-Loom-Mixin-Remap-Type: static
Fabric-Gradle-Version: 8.6
Fabric-Loom-Version: 1.6.11
Fabric-Mixin-Compile-Extensions-Version: 0.6.0
Fabric-Minecraft-Version: 1.20.5
Fabric-Tiny-Remapper-Version: 0.10.1
Fabric-Loader-Version: 0.15.9
Fabric-Mixin-Version: 0.12.5+mixin.0.8.5
Fabric-Mixin-Group: net.fabricmc
Fabric-Mapping-Namespace: intermediary
```

**Comment by TheKodeToad** [comment]
I don't think this should be necessary - I believe this is Loom-specific behaviour and relying on it doesn't seem like the best plan in case of changes for example. Does your mod file not confuse [Neo]Forge?

**Comment by TheKodeToad** [comment]
IMO you should definitely consider fixing this on your end - any change on our end doesn't feel like it should be necessary TBH.

**Comment by Djspac3** [comment]
This behavior doesn't matter. It should not act like that. May be an issue on The Mods end if the mod like in the reference one I made which i didn't know at the time was the same issue it's.  Actually more of  a mixed issue as i see it it's an issue of prism checking the file even though it shouldn't for a different mod loader and the mod for having a file It shouldn't in that version. That's how I'm thinking about it, though.  Probably doesn't matter

**Comment by Djspac3** [comment]
its checking for one data before another probably
soo its IG checking for forge then fabric but it finds useless data (for fabric ver) and reads it like fabric data then moves on to the next mod showing up as ${name} with its version being ${version}

**Comment by TheKodeToad** [comment]
closing for now
