### ISSUE TITLE
'Check for Updates' replaces unknown mods with those for incompatible loader

### ISSUE THREAD

**Issue by EntityinArray** [PrismLauncher/PrismLauncher#2367]
### Operating System

Windows 10 Pro

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

After adding a mod as a file, from unknown provider. Clicking Check for Updates causes Prism Launcher to replace Fabric mods with Forge mods. It doesn't check the current modloader when it resolves unknown mods!

### Steps to reproduce

* Download some mods manually
* Create new instance with Fabric loader
* Add your mod files by clicking 'Add file' in the Mods section
* Click 'Check for Updates'
* Prism Launcher will ask whether it should try to search and resolve unknown mods, agree.
* If your mod has a Forge version on the site, Prism Launcher will grab that instead of Fabric version
* Your modpack is ruined

### Suspected cause

Prism Launcher doesn't care about currently used modloader when it resolves unknown mods

Even better, make sure that you compare hash of the current mod and file that you found on the site before replacing them. Report that no mod was resolved if no file with same hash was found.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Before reporting you should always check if it happens on the latest available version of the launcher.
Also without naming the mod that you added there is no way for us to try to reproduce it.
Can you also share a screenshot of the instance version tab( edit instance >Versions)?

**Comment by EntityinArray** [comment]
i'm really sorry, it turns out my friend accidentally sent me forge mods
