### ISSUE TITLE
Can't add microsoft account

### ISSUE THREAD

**Issue by ThChatz** [PrismLauncher/PrismLauncher#2369]
### Operating System

Linux

### Version of Prism Launcher

current flake version

### Version of Qt

current flake version

### Description of bug

Logging in with a microsoft account does nothing

### Steps to reproduce

I followed the steps and logged in on my microsoft account but the launcher didn't react. It keeps writing
`PollServer::onPollTimeout:` retrying` on the terminal

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ThChatz** [comment]
Closing as this is a microsoft issue after all (indie company, guys, don't bully them)

**Comment by Trial97** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2302
