### ISSUE TITLE
Use dark theme as default

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#237]
### Role

I use the launcher and sometimes recommend it to others - and when I do so, I always have to mention how they should go to settings and set the UI to dark theme with flat icons for it to look good.

### Suggestion

I want the dark theme with flat icons to be set as default on Windows systems, as system theme detection there doesn't work properly yet and so it makes sence to fallback to the least eye-straining theme instead of the most.

### Benefit

The launcher would look much more modern and visually pleasing out of the box for Windows users (who do matter, as those are the majority of Minecraft players and users overall).

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Make an additional step in the setup wizard to let the user choose their preferred color theme right off - it would be especially helpful for newbies who are not initially able to navigate to UI settings.

**Comment by DioEgizio** [comment]
i think just using it as a default is a bad idea, but for the wizard, hell yes

**Comment by TayouVR** [comment]
there was an issue on PolyMC about that, but I can't be bothered to find it now. 
I suggested a interface in the wizard similar to how popular IDEs do it (little rectangles showcasing the various themes, that exist by default)

Just not sure how to implement it. But a simpler version of that really shouldn't be too hard to do.

**Comment by jn64** [comment]
:-1: Should follow the system theme by default.

**Comment by theofficialgman** [comment]
> I want the dark theme with flat icons to be set as default no matter the system theme.

I wholeheartedly disagree. If you want your applications to be dark themed then your system theme should be a dark theme to your liking already. If you don't like the system theme in prism launcher, thats the fault of your system theme not prism launcher.

edit: to give an example. here is my system them showing directly through in prism launcher. all my applications (even the electron based one) all use the same theme

![image](https://user-images.githubusercontent.com/28281419/197371905-93a13180-2bf7-4cfc-bc32-ac6f76c880ed.png)

and another system showing multiple QT applications and GTK applications following the system theme
![Screenshot from 2022-10-22 23-30-27](https://user-images.githubusercontent.com/28281419/197372348-a6668740-e6de-4a0c-8742-14ad44b61442.png)

**Comment by ghost** [comment]
> I wholeheartedly disagree. If you want your applications to be dark themed then your system theme should be a dark theme to your liking already. If you don't like the system theme in prism launcher, thats the fault of your system theme not prism launcher.

From my experience, unless you use Linux, it does not work this way. For a lot of people it always detects as light theme, no matter the system theme.

The system theme detection is imperfect. It should not be relied on.

**Comment by DioEgizio** [comment]
> > I wholeheartedly disagree. If you want your applications to be dark themed then your system theme should be a dark theme to your liking already. If you don't like the system theme in prism launcher, thats the fault of your system theme not prism launcher.
> 
> From my experience, unless you use Linux, it does not work this way. For a lot of people it always detects as light theme, no matter the system theme.
> 
> The system theme detection is imperfect. It should not be relied on.

it actually works perfectly. The only case where it doesn't use the dark theme is on windows; Qt uses the windows xp-era API for getting the palette, and it doesn't support dark mode yet, so I don't get what you're trying to say here. The detection is perfect

**Comment by ghost** [comment]
Yes, unless you are on windows. And Windows is the system most people use on a daily basis.

basically said "it doesn't work at all on windows, it's perfect!" Given that Windows is a popular system among general consumers (I'm sure at least 60% of the launcher's userbase use it!), it should be accounted for.

**Comment by jn64** [comment]
So your idea to help Windows users is to _ignore **all** users who have their system set to light mode_, and default PrismLauncher to dark mode?

It's a Qt bug. If you want to help Windows users please direct your efforts here: https://bugreports.qt.io/browse/QTBUG-72028

**Comment by ghost** [comment]
Always defaulting to dark theme is at least better than always defaulting to light theme: the user would not get uncomfortable by having a dark mode window in a light mode system, but would by having a light mode window in a dark mode system (my eyes!), so if we can't properly detect the system theme, it makes sence to fallback to dark theme and not light theme.
Let's have a compromise. Only Windows users get default dark mode until Qt fixes their stuff, and there is an additional step in the setup wizard that allows the user to pick their color theme right off.

**Comment by ghost** [comment]
I edited the initial post to reflect that summary.

**Comment by TheKodeToad** [comment]
For accessibility reasons this won't be considered; #362 is a much better solution
