### ISSUE TITLE
Potential Fix for "blocked" mods

### ISSUE THREAD

**Issue by Advik-B** [PrismLauncher/PrismLauncher#2372]
### Role

I used to play modded minecraft, also I am a dev myself

### Suggestion

Potential fix for 'blocked'/404 mods by some string manuplation

### Benefit

So that there are less 'blocked' instances and will overall benifit the user

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

# Some backstory
I was once developing a curseforge modpack downloader: [Advik-B/CMPDL](https://github.com/Advik-B/CMPDL)
But It needed a proper backend library because, at that time. I was using HTML parsing, **NOT** the curseforge API

However, when I started developing the backend to interact this the API, I realised that it would be easier to maintain it in a separate python package: [Advik-B/Curseforge-API](https://github.com/Advik-B/CurseForge-API)
```python
pip install curseforge # This is my wrapper around the curseforge API
```

# The problem

While testing, I ran into a problem:
The metadata from:
```python
http://api.curseforge.com/v1/mods/{addon_id}/files/{file_id}
```
Sometimes had the `download_url` attribute missing **Which I am assuming is what gets '_blocked_'**
After slamming my head on the desk for days. I got an idea in my sleep. which I implemented immediately at 3:00 in the morning

# The fix

(Assuming you know string manipulation in python)

```py
MOD_BASE_URL = "https://edge.forgecdn.net/files/%(file_id_1)s/%(file_id_2)s/%(file_name)s"
```
And
```py
def get_mod_file(self, addon_id: int, file_id: int) -> CurseModFile:
        mod = CurseModFile.from_dict(self.fetch(f"mods/{addon_id}/files/{file_id}"))
        if mod.download_url is None:
            # Guess the download url
            file_id = str(file_id)[1:] if str(file_id).startswith("0") else str(file_id)
            file_id_1 = file_id[:4]
            file_id_2 = file_id[4:7]
            mod.download_url = MOD_BASE_URL % {
                "file_id_1": file_id_1,
                "file_id_2": file_id_2,
                "file_name": mod.file_name
            }
        return mod
```

Translated into C++ is:
```cpp
#include <iostream>
#include <string>
#include <sstream>

using namespace std;

string guess_download_url(int addon_id, int file_id, string file_name) {
    const string MOD_BASE_URL = "https://edge.forgecdn.net/files/%(file_id_1)s/%(file_id_2)s/%(file_name)s";
    
    ostringstream file_id_stream;
    file_id_stream << file_id;
    string file_id_str = file_id_stream.str();

    if (file_id_str[0] == '0') {
        file_id_str.erase(0, 1);
    }

    string file_id_1 = file_id_str.substr(0, 4);
    string file_id_2 = file_id_str.substr(4, 3);

    size_t pos = MOD_BASE_URL.find("%(file_id_1)s");
    MOD_BASE_URL.replace(pos, 13, file_id_1);

    pos = MOD_BASE_URL.find("%(file_id_2)s");
    MOD_BASE_URL.replace(pos, 13, file_id_2);

    pos = MOD_BASE_URL.find("%(file_name)s");
    MOD_BASE_URL.replace(pos, 13, file_name);

    return MOD_BASE_URL;
}
```
Tests
```cpp
int main() {
    int addon_id = 12345;
    int file_id = 67890;
    string file_name = "example_mod.zip";

    string download_url = guess_download_url(addon_id, file_id, file_name);
    cout << "Guessed Download URL: " << download_url << endl;

    return 0;
}
```
# Explanation
> Taken from ChatGPT because I dont know how to explain my code to professional devs (im just a student)

Let's break down the Python function guess_download_url which performs the guessing feature for constructing a download URL based on the provided template:
```py
def guess_download_url(addon_id, file_id, file_name):
    # Template for the base URL
    MOD_BASE_URL = "https://edge.forgecdn.net/files/%(file_id_1)s/%(file_id_2)s/%(file_name)s"
    
    # Convert file_id to string
    file_id_str = str(file_id)
    
    # Remove leading zeros if present
    if file_id_str.startswith('0'):
        file_id_str = file_id_str[1:]
    
    # Extract file_id_1 and file_id_2 from file_id_str
    file_id_1 = file_id_str[:4]
    file_id_2 = file_id_str[4:7]
    
    # Replace placeholders in the base URL template with actual values
    download_url = MOD_BASE_URL % {
        "file_id_1": file_id_1,
        "file_id_2": file_id_2,
        "file_name": file_name
    }
    
    return download_url
```
Parameters:
- `addon_id`: An integer representing the ID of the addon or mod.
- `file_id`: An integer representing the ID of the specific file of the addon.
- `file_name`: A string representing the name of the file to be downloaded.

Function Body:

1. Define Template URL:
```python
MOD_BASE_URL = "https://edge.forgecdn.net/files/%(file_id_1)s/%(file_id_2)s/%(file_name)s"
```
This line defines a string MOD_BASE_URL which serves as the template for the base URL. Placeholders %(file_id_1)s, %(file_id_2)s, and %(file_name)s are used to represent parts of the URL that will be replaced with actual values.

2. Convert file_id to String and Remove Leading Zeros:
```python
file_id_str = str(file_id)
if file_id_str.startswith('0'):
    file_id_str = file_id_str[1:]
```
This code snippet converts the integer file_id to a string and removes any leading zeros from it

3. Extract file_id_1 and file_id_2:
```python
file_id_1 = file_id_str[:4]
file_id_2 = file_id_str[4:7]
```
The file_id string is then split into two parts: file_id_1 containing the first 4 characters and file_id_2 containing the next 3 characters.

4. Replace Placeholders in URL Template:
```python
download_url = MOD_BASE_URL % {
    "file_id_1": file_id_1,
    "file_id_2": file_id_2,
    "file_name": file_name
}
```
This part of the code replaces the placeholders in the template URL (MOD_BASE_URL) with the actual values obtained earlier.

5. Return Constructed URL:

Finally, the constructed URL is returned as a string.
```python
return download_url
```

**Example Usage:**
```python
addon_id = 12345
file_id = 67890
file_name = "example_mod.zip"

download_url = guess_download_url(addon_id, file_id, file_name)
print("Guessed Download URL:", download_url)
```

That's all I can say about this. I don't know if this has already been implemented or not, but I hope this helps :))

**Comment by Trial97** [comment]
The only downside of this is that to determine if the URL is valid or not we would need to request the file or at least call [HEAD](https://developer.mozilla.org/en-US/docs/web/http/methods/head) before displaying to the user the option.
So either guess all missing URLs and give an error on download if the URL is not accessible or before displaying the option verify the URL using the  HEAD request. 
But this would indeed be nice if the guessed URL is always correct.

**Comment by Trial97** [comment]
Other than the fact that there is no way to tell the user that the download failed due to a guessed URL, I managed to draft a PR regarding this. Once I figure out how to alert the user about this stuff I will mark it ready to review.
Thanks for your suggestion!

**Comment by Scrumplex** [comment]
This is against CF's ToS and would bypass their "DRM"

**Comment by Scrumplex** [comment]
See https://github.com/PolyMC/PolyMC/pull/621

**Comment by Advik-B** [comment]
> This is against CF's ToS and would bypass their "DRM"

How would this be bypassing their "DRM".
Its just some basic string manipulation
(Please correct me if im wrong)

> Also, can you preferably quote the part of their TOS that says this

**Comment by Trial97** [comment]
> Also, can you preferably quote the part of their TOS that says this

Sorry I did not look it up before starting working but here is the part (more exactly the c part):
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/31c69ceb-15ea-4e0e-b9bd-4e389f6c941a)
Found here: https://docs.curseforge.com/#curseforge-for-studios-terms-of-use

**Comment by Advik-B** [comment]
This is unbelievable (I shouldn't use this language but), a-hole behaviour from CurseForge

Hopefully, in the (not-so-distant) future, Prism can have a plugin system (which I know is a lot of work by itself)
So that we can make a plugin to "bypass" this so-called "DRM"

PS: Thanks for the link to the TOS :)

**Comment by DioEgizio** [comment]
> > This is against CF's ToS and would bypass their "DRM"
> 
> How would this be bypassing their "DRM". Its just some basic string manipulation (Please correct me if im wrong)
> 
> > Also, can you preferably quote the part of their TOS that says this

We even tried doing this in the past and they asked us to stop
