### ISSUE TITLE
option to not show already downloaded mods in `Download mods` menu

### ISSUE THREAD

**Issue by maskersss** [PrismLauncher/PrismLauncher#2376]
### Role

I play modded Minecraft.

### Suggestion

I want the `Download mods` menu to be less cluttered,

### Benefit

so that it's faster to find the right mod.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

right now Prism highlights the mods that you have already downloaded with italic and a white border, imo it would be nice to have an option to completely remove them from the search here: ![image](https://github.com/PrismLauncher/PrismLauncher/assets/97827489/e2d66bcf-7cef-41f5-bc5b-129d3b5f8bdd)

not sure if it should be enabled by default or not

i also found #1902 but it seems like a different suggestion

**Comment by Trial97** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1260
