### ISSUE TITLE
Can't install Neoforge on Technic packs

### ISSUE THREAD

**Issue by AqueousDog** [PrismLauncher/PrismLauncher#2380]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.6.3

### Description of bug

I made a modpack for me and some friends and uploaded it to Technic for update support. Upon loading the modpack it loads to vanilla. Replacing the "modpack.jar" with a Forge version fixed the issue. I am on 1.20.1 using Forge 47.2.30 and Neoforge 47.1.105.

### Steps to reproduce

Create two Technic-style modpacks using a Neoforge and a Forge "modpack.jar". Import the .zip into Prism and try to load into them. Only the Forge pack will be modded.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
can you provide an example of neoforge technicpack? (either point us to your uploaded pack if is public or upload a small one here)

**Comment by AqueousDog** [comment]
[neoforge modpack.zip](https://github.com/PrismLauncher/PrismLauncher/files/15255388/neoforge.modpack.zip)
Here's a modpack with only the Neoforge .jar and JEI.

**Comment by DrSnone** [comment]
Hi, i can`t use Neoforge 1.21 for the Technic Launcher, it load diverse stuff and i land on the start screen from the launcher. I have checked the 1.20.1 version of Neoforge and that works fine with the launcher.
Can anyone help?

**Comment by Trial97** [comment]
Are you using 8.4?
If yes can you name the pack that you are trying to install?

**Comment by DrSnone** [comment]
oh my fault sorry, i have install prism launcher done yet.
