### ISSUE TITLE
Can't Resize "New Instance" Window

### ISSUE THREAD

**Issue by Jacobplo** [PrismLauncher/PrismLauncher#2381]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.6.3

### Description of bug

The "New Instance" window should be able to be resized, however resizing the window vertically was not possible. I am on a laptop, so the bottom of the window does not fit fully on the screen, making it difficult to press the buttons located at the bottom of the window.
<img width="602" alt="Screenshot 2024-05-07 222059" src="https://github.com/PrismLauncher/PrismLauncher/assets/84536096/6108774e-6596-4130-b641-9400ca71c1e8">

### Steps to reproduce

- Press the "Add Instance" button.
- The window that is opened cannot be resized.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by GitTrippin101** [comment]
same

**Comment by Trial97** [comment]
Duplicate https://github.com/PrismLauncher/PrismLauncher/issues/2242
