### ISSUE TITLE
Update Button for Resource Packs

### ISSUE THREAD

**Issue by Mortycio** [PrismLauncher/PrismLauncher#2391]
### Role

Having many resource packs

### Suggestion

Add a "Check for Updates" button

### Benefit

Save a loooot of time

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Preamble: these are the links of "similar" issues already present on this GitHub, very old posts left to die like this without a worthy response.

https://github.com/PrismLauncher/PrismLauncher/issues/1017

https://github.com/PrismLauncher/PrismLauncher/issues/1207

My request is very simple: add a button to update all resource packs together, just like it happens for mods.

There is a button to update all the mods together,

![mods update button](https://github.com/PrismLauncher/PrismLauncher/assets/113641947/73afa208-5dd4-4702-9987-988d00040968)

but there isn't one for the resource packs, nor for the shaders, let alone for resources like "LWJGL" or "Fabric Loader" (in my case, since I use Fabric).

![version missing update button](https://github.com/PrismLauncher/PrismLauncher/assets/113641947/2b56f016-957d-4eec-9060-fd2c15a128a3)

By now, I've accumulated 39 resource packs, most of them are the classic "better x", "better y", etc., others make specific objects 3D, others completely change textures or add animations...
In short, to keep them updated I have to go back and re-download them, and ABOVE ALL Prism doesn't tell me the exact version installed (it only shows numbers like 15, 18, 22 etc.)

![rp missing update button](https://github.com/PrismLauncher/PrismLauncher/assets/113641947/9f260d08-1e78-4359-a2ab-aee3d879281a)

so I have to open the links on Modrinth/Curseforge, go to the "versions" section, check which version I have by filtering the Minecraft version, and from there figure out which one is the right one.

ㅤ
ㅤ

P.S. when trying to download resource packs, there is no button to filter the results based on the Minecraft version of the instance.

![mods filter button](https://github.com/PrismLauncher/PrismLauncher/assets/113641947/98b84d00-d8f4-483b-904f-a3bce1651401)
![rp missing filter button](https://github.com/PrismLauncher/PrismLauncher/assets/113641947/0f1c6bd7-381e-4f72-ac65-3f76ed335847)

ㅤ
ㅤ

P.P.S. the shader packs installed don't appear on the screen.

![shader missing update button](https://github.com/PrismLauncher/PrismLauncher/assets/113641947/8a9723ea-552b-40e6-aa26-e7deb10d26d4)

**Comment by TheKodeToad** [comment]
This is pretty much what is being implemented for #1207!

**Comment by Mortycio** [comment]
> This is pretty much what is being implemented for #1207!

That one specify "Allow you to link a github to a resource pack and add update button". I don't want this, I want a simple update button like the mods one. I don't know if it works with modrinth/curseforge links..

**Comment by TheKodeToad** [comment]
Fair enough! I kind of interpreted that issue as something like this lol
Would rather not move stuff to this so I will probably just update the other issue

**Comment by Yoshiman5551** [comment]
I want this too!!!!!!!!!!!!!!1111
