### ISSUE TITLE
Error when attempting to upload game log (Ubuntu 23.10, local install of PrismLauncher)

### ISSUE THREAD

**Issue by genderneutralnoun** [PrismLauncher/PrismLauncher#2400]
### Operating System

Ubuntu Linux 23.10 (KDE Ubuntu/Kubuntu)

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 5.15.10

### Description of bug

When clicking the upload button in the Minecraft Log section of an instance window, I receive the normal "You are about to upload..." warning, then after clicking Yes, I get this error: `Error while reading: error:0A0003FC:SSL routines::sslv3 alert bad record max`

Intriguingly, it suddenly started working while I was testing to get the error message so I could post it here.

### Steps to reproduce

* Start an instance
* Exit instance (or it crashes) 
* Click "Upload" in the "Minecraft Log" section of the instance window
* Click "Yes"
* Receive error 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by iivusly** [comment]
Is it possible the error that you were receiving was "sslv3 alert bad record mac" ? After doing some research it seems to be a problem with the host that the launcher is trying to connect to and not the launcher itself. Try changing the upload provider in the launcher's settings and see if you keep getting the same error.

**Comment by Trial97** [comment]
Not a launcher issue: this is related to the paste provider that you tried and it was temporary so closing this.
