### ISSUE TITLE
unable to connect to certain servers

### ISSUE THREAD

**Issue by starstriker0** [PrismLauncher/PrismLauncher#2406]
### Operating System

Windows

### Version of Prism Launcher

Prism launcher 8.3

### Version of Qt

Qt 6.6.3

### Description of bug

i am unable to connect to certain servers using prism launcher, i tried atlauncher, curseforge launcher, and the regular Minecraft launcher, they work fine, i reinstalled prism launcher twice and still have the same problem. other servers like hypixel work but others don't, the bottom one is whimcraft.org, it can't connect. I've also tried on 2 different networks so no domain i being blocked anywhere
![image](https://github.com/PrismLauncher/PrismLauncher/assets/92127521/0a7a7402-fb4e-4f03-bc0a-6c8329aad737)

### Steps to reproduce

start up and mc version(i mainly used 1.20.4) and try to connect to these servers in the server list pryormc.co or whimcraft.org(whitelist only so don't try to join)

### Suspected cause

i have no clue what could possibly be the cause of this

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Nagol12344** [comment]
Seems to work for me, ~~I would check your firewalls and see if its blocked.~~ I cant read, ignore
![image](https://github.com/PrismLauncher/PrismLauncher/assets/63481547/d002f61a-873e-448f-b267-69b0db8df799)

**Comment by starstriker0** [comment]
nvm, i figured it out, it was DNS servers, i had my wireless card's DNS servers set to 1.1.1.1 and 1.0.0.1
