### ISSUE TITLE
Why don't you support offline accounts without microsoft login?

### ISSUE THREAD

**Issue by Blayung** [PrismLauncher/PrismLauncher#2407]
### Goal

Allow to launch the game without a microsoft account.

### Motivation

I have no idea where does the decision not to allow this come from.

It's a free and open source project, and I think that you shouldn't force people into buying the game.

Second thing is convenience. What if I'd like to play the game at school? I don't wanna log into my microsoft account there. Why should I use some crappy unupdated fork instead of the og launcher? What if I want to start playing without internet? That's really crappy.

Also, I understand that you or somebody from multimc might have wanted to support mojang and drive people away from piracy, but the truth is that if you don't make that small, simple change then all these people will just go away to use some different launcher or use diegiwg's fork. It's just a stupid inconvenience coming from your side. Besides, microsoft is a huge corporation and bill gates can wipe his ass with the amount of money he'll earn with these few people buying the game. As you may know, they have also shown little care for the community lately. Chat reporting is a great example - does it ring the bell? I don't know if I want to support them that much.

Btw I do own minecraft - I have paid for it. (https://namemc.com/profile/_Blay_.3)

### Drawbacks

None, maybe somebody's fragile feelings.

### Unresolved Questions

Can't think of any.

### Alternatives Considered

None.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Blayung** [comment]
Dude, this was supposed to be discussion! You just slapping a 'not planned' label on it?

**Comment by Trial97** [comment]
Reason: supporting offline accounts without at least one account that owns Minecraft would circumvent Microsoft DRM.
This would result in Microsoft shutting down the project. 
So, offline accounts are not an option and never will be.

**Comment by Blayung** [comment]
But there are countless other projects that allow for this! Microsoft never seemed to fight against such stuff. Maybe in a few extreme cases like minecraftforfree.com and eaglercraft. Maybe trying wouldn't hurt? You can always comply with their demands later.

**Comment by Trial97** [comment]
Then use those other countless projects.

**Comment by Blayung** [comment]
Why not prism launcher? You're omitting the point.

**Comment by TheKodeToad** [comment]
This isn't going to go anywhere
