### ISSUE TITLE
Change skin upload wording to Wide/Slim

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#2409]
### Role

I play Minecraft

### Suggestion

I want the skin option to say Wide/Slim instead of Steve/Alex

### Benefit

So I won't be confused

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I didn't see any other issue made about this, so sorry if it's a duplicate. 

Anyway, while I do like how it is atm I feel like it'd create confusion for anyone doing a skin change. Took me a minute to figure out which is which, but currently minecraft shows it as wide/slim. So I feel changing the wording to match would be best

**Comment by Trial97** [comment]
This will be fixed in https://github.com/PrismLauncher/PrismLauncher/pull/1609
But the naming is classic/Slim

**Comment by Aces-and-Jacks** [comment]
Oh ok. Well that's just as good, thank you

**Comment by Fleepe** [comment]
I hope this feature will be available very soon because skin management is the only thing that makes me use the default minecraft launcher.
