### ISSUE TITLE
Modrinth Mod search stops working when editing the search box

### ISSUE THREAD

**Issue by AmberIsFrozen** [PrismLauncher/PrismLauncher#241]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

**Expected**
In the Mod Downloader (Modrinth), when I edit the text in search box, it should soon auto refresh with a new mod list depending on my search criteria.

**Reality**
Sometimes (Usually editing the search box when it's already fetching the data), the entire downloader would stop working with a blank page. It will remain like this unless I close the window then reopen it again. (Curseforge are unaffected)
(The log says `Task "NetJob(Modrinth::Search)" aborted while not running!!!!`)

![image](https://user-images.githubusercontent.com/28094366/197358612-a2d7f043-74c4-4364-b66f-b6e91cc3be48.png)

### Steps to reproduce

Keep editing the search box (For me it usually happens when deleting characters, don't think this affect the reproducibility though)
On the right timing it will stop working

### Suspected cause

Something aborted the task when fetching the data, and that search job is meant to be reused once first started?
```
20.881 C Aborted  "https://api.modrinth.com/v2/search?offset=0&limit=25&query=Minec&index=relevance&facets=[[%22categories:forge%22],[%22versions:1.19.2%22],[%22project_type:mod%22]]"
20.881 D Download aborted in previous step: "https://api.modrinth.com/v2/search?offset=0&limit=25&query=Minec&index=relevance&facets=[[%22categories:forge%22],[%22versions:1.19.2%22],[%22project_type:mod%22]]"
20.881 D Task "NetJob(Modrinth::Search)" aborted.
21.390 C Task "NetJob(Modrinth::Search)" aborted while not running!!!!
21.791 C Task "NetJob(Modrinth::Search)" aborted while not running!!!!
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by sybenx** [comment]
this is an issue on steamdeck. Only workaround I've found is pasting in search terms
