### ISSUE TITLE
Have Multiple Java versions possibly based on Instnance

### ISSUE THREAD

**Issue by Negative-light** [PrismLauncher/PrismLauncher#2417]
### Role

I use it to play multiple version of Minecraft both modded and un modded that require different versions of Java.

### Suggestion

I would like to add a method to have a instance either override the default Java version or the ability to add multiple Java versions that can be detected allowing the user to not need to go and manually swap the Java version when changing between versions.

### Benefit

This is more of a QOL issue and probably not high weight. This being said I think it would save the users a lot of time and would greatly benefit non-technical users.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I have analyzed the issues, but there isn't one that describes this specifically to my knowledge. This being said somewhat adjacent issues would include the following:
- #789 - adding multiple Java Profiles would solve the problem as you could create a Java 17 profile and a Java 21 profile you could then tie the appropriate profile to the correct instance.
- #762 - this is very close to my issue this being said I would like something that is more targeted for non-technical users.
- #335 - this is 90% of my current issue but still not 100%.

Overall this could be considered an aggregate of the three issues above. I think adding prompting for the user to download a version of Java and allowing users to have multiple would be great. The JVM args are more technical than here and the automatic switching is the base concept but I think allowing players to override it may still be theoretically useful (though no use case has come to mind).

A simple solution may be to just have the user set a "parent folder" for their Java installs assuming that the installs would all be under some directory and follow a logical format such that you could have paths like `<parent folder>/[Java version]/...`.

**Comment by Trial97** [comment]
Hi you can already override java per instance: right click on the instance>Edit>Settings>Java
Other than that the second part regarding selecting a java based on the Minecraft version https://github.com/PrismLauncher/PrismLauncher/issues/762 covers it.

**Comment by Negative-light** [comment]
I do apologize for wasting your time. I thought I had checked through all of these. Thank you.
