### ISSUE TITLE
Terminal --profile Option requires the name to match Capitalization

### ISSUE THREAD

**Issue by Bedlessdeus** [PrismLauncher/PrismLauncher#2421]
### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.2.4

### Description of bug

Attempting to use the Command
./PrismLauncher.AppImage --launch "1.8.9(1)" --server "0:25402" --profile Bedlessdeus

Doesnt Launch Instance, but if changed to
./PrismLauncher.AppImage --launch "1.8.9(1)" --server "0:25402" --profile BedlessDeus

It works, from this reasoning I deduct, that it requires the exact same capitalization that is recorded in the Launcher, it would be usefull, if this arg was passed into #toLowerCase() before checking if it matches.

### Steps to reproduce

run
./PrismLauncher.AppImage --launch "%yourInstance%" --profile "%yourProfileNameIgoringCaps%"

### Suspected cause

Name Match is checking for matching caps

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
That is intended
