### ISSUE TITLE
Exporting misspelling: "compresing"

### ISSUE THREAD

**Issue by Golfavel** [PrismLauncher/PrismLauncher#2430]
### Operating System

Linux

### Version of Prism Launcher

8.3

### Version of Qt

Qt 6.7.0

### Description of bug

"Compressing" is misspelled as "Compresing" when exporting an instance with .zip

### Steps to reproduce

 1. Export an instance normally (.zip)
 2. Notice the term "Compresing" instead of "Compressing"

### Suspected cause

Misspelling

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by lordofpipes** [comment]
It's fixed in a future version by 853e4a13abfc2da266d505663c3784278ea5afad

**Comment by Trial97** [comment]
Fixed by https://github.com/PrismLauncher/PrismLauncher/pull/2217
