### ISSUE TITLE
is this fork of poly mc? why

### ISSUE THREAD

**Issue by User0918173** [PrismLauncher/PrismLauncher#2444]
### Operating System

Windows, Other

### Version of Prism Launcher

is this fork of poly mc? why

### Version of Qt

is this fork of poly mc? why

### Description of bug

is this fork of poly mc? why

### Steps to reproduce

is this fork of poly mc? why

### Suspected cause

is this fork of poly mc? why

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
Yes: https://prismlauncher.org/news/moving-on/

**Comment by TheKodeToad** [comment]
whoops, I got the wrong link!
That describes the situation with PolyMC, this relates more to Prism Launcher: https://prismlauncher.org/wiki/overview/faq/#why-did-our-community-choose-to-fork
