### ISSUE TITLE
Unable to launch OptiFine on 1.20.1 with Prism 8.3

### ISSUE THREAD

**Issue by vbuarque** [PrismLauncher/PrismLauncher#2445]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.6.3

### Description of bug

I'm trying to open minecraft with OptiFine_1.20.1_HD_U_I6, but I'm getting an error and it won't open.

### Steps to reproduce

My step-by-step to install optifine was this:

I edit my minecraft instance > I access the “Version” option > I add it to minecraft.jar > I take the extracted optifine file and confirm it

My Versions:
![optifine_version](https://github.com/PrismLauncher/PrismLauncher/assets/69692614/ecfdef20-3a3b-467f-be6b-6bd475162abc)

Error when started:
![optifine_error](https://github.com/PrismLauncher/PrismLauncher/assets/69692614/14d31a1c-5896-458f-8930-ba4cdfc6c011)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
Remove OptiFine from the version page and add original JAR (not extracted) as a Forge mod!
