### ISSUE TITLE
"640 3" spamming latest.log

### ISSUE THREAD

**Issue by CalaMariGold** [PrismLauncher/PrismLauncher#2456]
### Operating System

Windows

### Version of Prism Launcher

8.3

### Version of Qt

6.6.3

### Description of bug

On my modpack TREPIDATION (v0.4.5), the latest.log is being spammed with "640 3"
![image](https://github.com/PrismLauncher/PrismLauncher/assets/57605926/9535ec3d-e35e-48e2-b1c5-5f8ff25208a2)

https://www.curseforge.com/minecraft/modpacks/trepidation
Latest.log: https://mclo.gs/0zSgUOm

This only occurs when using Prism. Using any other launcher like CurseForge has no log spamming.

### Steps to reproduce

Launch TREPIDATION (and probably other modpacks) on Prism
Open latest.log
Notice "640 3" spamming

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Not a launcher issue.

**Comment by CalaMariGold** [comment]
Why would this only occur when installing via Prism then? Any ideas would be appreciated.

**Comment by Trial97** [comment]
Don't know it may be optifine or another mod that's spamming that
