### ISSUE TITLE
When exporting a modpack, the curseforge site or app does not accept it

### ISSUE THREAD

**Issue by esstoma** [PrismLauncher/PrismLauncher#2458]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.6.3

### Description of bug

When exporting a modpack, the curseforge site or app does not accept it.
The site gives the following error: Invalid archive.
This is the case with any modpack. But if you export the modpack from Prism Launcher first. Import to ATLauncher (for example) and export again, then curseforge site will accept it.
![msedge_VLZXE1H97d](https://github.com/PrismLauncher/PrismLauncher/assets/170931394/0868aa15-ee48-4e28-9ca2-36d79a101167)

### Steps to reproduce

1) Choose a modpack
2) Click the export button
2.1 Select the CurseForge (zip) sub-item
3) Attempt to upload it to the CurseForge Launcher or website

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
already fixed in nightly builds.
Solutions:
- update to nightly builds
- downgrade to 8.2
- take the zip file generated by prism extract it and archive it again

**Comment by darkphan** [comment]
I do not think this is fixed. The manifest.json and modlist.html files do not have any file permissions, and thus when Curseforge's automated system unpackages the zip file it can not read the manifest.json file.

**Comment by Trial97** [comment]
Is this happening on latest nightly build?

**Comment by darkphan** [comment]
It appears that it is working after all. Sorry about adding to this post. (I was posting on behalf of the person submitting a modpack, an update was getting rejected due to an invalid manifest because it could not be read, however after deleting all the previous attempts and trying again it finally was successful)
