### ISSUE TITLE
Mod updater doesn't properly deliniate between versions

### ISSUE THREAD

**Issue by anoraktrend** [PrismLauncher/PrismLauncher#246]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Flatpak

### Description of bug

The mod updater should download only the latest version that's compatible with the instance's Minecraft version.

### Steps to reproduce

Attempt to update on an older (say, 1.16.5) instance.

### Suspected cause

The mod updater checks if the mods are compatible with the mod loader version instead of the Minecraft version.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
This is a CF API bug

**Comment by anoraktrend** [comment]
It was Modrinth Mods

**Comment by DioEgizio** [comment]
prism just gives the info to the modrinth API, soooo

**Comment by DioEgizio** [comment]
What mod
