### ISSUE TITLE
Лаунчер не запускает майнкрафт

### ISSUE THREAD

**Issue by fooooooy** [PrismLauncher/PrismLauncher#2460]
### Version of Prism Launcher

Prism launcher 8.3

### Version of Qt

Qt 6.6.3

### Description of bug

При попытке запуска майнкрафта вылезает ошибка что нету лицензии на данном аккаунте майкрасофт при этом у меня лицензия майнкрафта получена с помощью подарочного кода 

### Steps to reproduce

* Нажмите на кнопку "Запустить"
* Увидьте окно об ошибке с текстом "Эта учётная запись не владеет Minecraft. Чтобы поиграть, вам нужно сначала купить игру."

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2302
And please use English.
