### ISSUE TITLE
Unknow error

### ISSUE THREAD

**Issue by fooooooy** [PrismLauncher/PrismLauncher#2465]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher

### Version of Qt

Qt 6.6.3

### Description of bug

I tried to launch the modpack and got an error

> Exception caught from launcher
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR

### Steps to reproduce

* Launch the modpack
* Get an error

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
I'm going to assume that you are playing offline, so edit the instance, navigate to the versions tab, and hit the Download All button.
If that did not do the trick try also deleting the meta folder( and try the above again).
If you did all that then a full log may help.

**Comment by fooooooy** [comment]
Your advice didn't help

**Comment by Trial97** [comment]
Please send logs! The recommended site to upload your logs to is [mclo.gs](https://mclo.gs/).
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/864719e8-e812-43c7-a05f-5d2a5479928a)
And I want full logs not just the error.
Also if you insist that is a issue with prism I will also need the Prism logs found here:
 - name: Portable (Windows / Linux)
    value: '`./logs/PrismLauncher-0.log` In the PrismLauncher folder'
  - name: Windows
    value: '`%APPDATA%/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Scoop
    value: '`%HOMEPATH%\scoop\persist\prismlauncher\logs\PrismLauncher-0.log`'
  - name: macOS
    value: '`~/Library/Application Support/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Linux
    value: '`~/.local/share/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Flatpak
    value: '`~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/logs/PrismLauncher-0.log`'

**Comment by fooooooy** [comment]
https://mclo.gs/MW81QWz
[PrismLauncher-0.log](https://github.com/user-attachments/files/15533341/PrismLauncher-0.log)

**Comment by Trial97** [comment]
You have the wrong java version selected: you need java 8.
This is not a launcher issue.

**Comment by fooooooy** [comment]
Thank you
