### ISSUE TITLE
Adding your music to the launcher

### ISSUE THREAD

**Issue by Laptritic** [PrismLauncher/PrismLauncher#2468]
### Role

I like to customize my instance in the launcher

### Suggestion

please make it possible to insert your music into the launcher

### Benefit

more enjoyable time in the launcher

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

when you launch Minecraft, the music from the launcher will stop, you can make a sequence of music, when you start the launcher, the music will gradually increase the volume to the one you set

**Comment by Trial97** [comment]
It's never gonna happen. This is a Minecraft launcher, not Winamp.
