### ISSUE TITLE
Keep "Settings" available while the instance is running

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#247]
### Role

I use the launcher.

### Suggestion

I want the settings tab to not be hidden while the instance is running, as those settings only apply on startup and have no effect on runtime.

### Benefit

There's a period of time after the game closes while the instance is still considered running; this suggestion being implemented would allow one to get to adjusting their startup options a second or two earlier (trust, it's way more annoying than you think to wait those few seconds). Also adds consistency to the UI.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by iTrooz** [comment]
+1, I never really understood when the "settings" button showed or not, this issue just taught me

EDIT : Or at least please gray the option when the game is running, so we know we didn't forgot where the settings are
