### ISSUE TITLE
Can't add a Microsoft account.

### ISSUE THREAD

**Issue by GustavoJadson** [PrismLauncher/PrismLauncher#2482]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.7.1

### Description of bug

Error trying to add a Microsoft account

### Steps to reproduce

Here's the log file:
![Screenshot_20240607_125722](https://github.com/PrismLauncher/PrismLauncher/assets/55543826/9ad1f390-5fd4-4afe-aa1e-7f8e259cc0c1)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by GustavoJadson** [comment]
[PrismLauncher-0.log](https://github.com/user-attachments/files/15742126/PrismLauncher-0.log)

**Comment by Samalando** [comment]
It seems the authentication servers are having issues again -- this does not just affect Prism Launcher so it seems that it's not an launcher issue! If you are not able to log in all you can do is try again or wait.
-prism launcher discord

**Comment by Trial97** [comment]
Duplicate

**Comment by GustavoJadson** [comment]
Makes sense. I tried to launch Minecraft from the original launcher on another PC few days ago, didn't worked, but thought it was because of Windows 7
