### ISSUE TITLE
Prism can't transfer my profile

### ISSUE THREAD

**Issue by LuGB18** [PrismLauncher/PrismLauncher#2493]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

qt 6.71

### Description of bug

so i downloaded it and tried login in with my microsoft acc so i waited and this error poped up:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/108163082/f2832da6-7e24-40bf-9bea-9002b444cae1)
so i tried searching any type of problem some one had like this and i didint find so can someone help me?

### Steps to reproduce

press the acount button > add microsoft account > get redirected to microsoft page > log in > prism tries to log in > error.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/108163082/c114f874-5de8-4516-9620-15a645fd51ee)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
See https://bugs.mojang.com/browse/WEB-7179
