### ISSUE TITLE
endlees checking java version

### ISSUE THREAD

**Issue by XEdramon** [PrismLauncher/PrismLauncher#2501]
### Operating System

Windows

### Version of Prism Launcher

Prism laucher 7.2

### Version of Qt

Qt 6.5.1.

### Description of bug

Prism Launcher version: 7.2 (official)

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.60]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::44, 13.107.246.44]

api.mojang.com resolves to:
    [13.107.246.60]

Minecraft folder is:
C:/Users/kiril/AppData/Roaming/PrismLauncher/instances/1.20.1/.minecraft

Java path is:
C:/Program Files/Eclipse Adoptium/jre-21.0.3.9-hotspot/bin/javaw.exe

Checking Java version...
Java is version 21.0.3, using 64 (amd64) architecture, from Eclipse Adoptium.

### Steps to reproduce

*press the cat button 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
That is not a version that is maintained anymore, please update to latest version

**Comment by XEdramon** [comment]
oh thx you
