### ISSUE TITLE
Failed to get authorization for Xbox services: Operation canceled

### ISSUE THREAD

**Issue by mohammadaboalnadar** [PrismLauncher/PrismLauncher#2512]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt version 6.6.3.

----------------------

I made a new issue since commenting on [this thread](https://github.com/PrismLauncher/PrismLauncher/issues/1049) didn't reopen the issue

----------------------

### Description of bug

Login has been failing for about 6 months for me on prism launcher. I only have this issue on prism launcher and other similar launchers, I can log in to the official Minecraft launcher without issue. I tried looking up the problem multiple times and tried lots of solutions including

- Whitelisting the launcher on my firewall (Shouldn't be an issue anyway because all online functions are working perfectly fine except log in
- Restarting the launcher, my PC, and my home network router multiple times on multiple occasions
- Uninstalling and reinstalling prism launcher
- Waiting for an update and successfully downloading and installing it
- Uninstalling Xbox services and reinstalling them
- Changing my DNS
- Changing the network I'm connected to while trying to log in
- Changing the browser I'm using to confirm the Microsoft login
- Using the recent nightly version as per the notification about regional issues with logging in using the recommended log in and the legacy log in and neither worked
- Using a VPN and trying to log in using the stable release launcher and the nightly version launcher using the legacy and the recommended logins and all of them produce the same error `Failed to get authorization for Xbox services: Operation canceled`

none of those attempts resulted in anything changing. The only launcher I'm able to use other than the official Minecraft launcher is the Forge launcher which sucks.

### Log File

[PrismLauncher-0.log](https://github.com/user-attachments/files/15837656/PrismLauncher-0.log)

### Steps to reproduce

- Add Microsoft account
- Proceed with instructions
- Launcher hangs for a minute on the `Logging in as an Xbox user` step
![image](https://github.com/PrismLauncher/PrismLauncher/assets/60301549/4834e544-0fbb-4a3e-b5fe-b14a42fbe33f)
- Launcher times out with an error reading: `Failed to get authorization for Xbox services: Operation canceled`
![image](https://github.com/PrismLauncher/PrismLauncher/assets/60301549/54dc5448-135f-4ecd-90a1-1b4cd86fd56c)

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
duplicate https://github.com/PrismLauncher/PrismLauncher/issues/1049
and https://github.com/PrismLauncher/PrismLauncher/issues/2302

**Comment by mohammadaboalnadar** [comment]
bruh

**Comment by Trial97** [comment]
I have a general issue for all the login stuff: https://github.com/PrismLauncher/PrismLauncher/issues/2302 as in most cases if not all cases is not prism fault

**Comment by ratatik337** [comment]
i think i have found a solution to the problem. When i couldnt register on prism launcher, i decided to play through multimc. I repeated the same steps as when registering in prism launcher and it wrote to me that i need to register using an xbox family. I registered and everything worked out for me in mmc, after that i tried to do the same thing in prismlauncher and everything worked there too.

**Comment by ratatik337** [comment]
maybe its because i live in russia idk

**Comment by Maculous** [comment]
> возможно, это потому, что я живу в России idk

Здарова, такая же проблема, по поводу входа, можешь помочь?
