### ISSUE TITLE
Add ability to share the same instance folder for different instances

### ISSUE THREAD

**Issue by Paulboy002** [PrismLauncher/PrismLauncher#2518]
### Role

I use Prism launcher to play multiple different versions of minecraft and have quick access to mod updates

### Suggestion

give me the ability to have 2 instances share the same folder (so i can keep the same worlds, recourse packs, key binds, and servers)

### Benefit

so it can retain some of the functionality the the official mincraft launcher has, and also convenience

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Obviously this wouldnt work if you shared an folder between 2 different modded instances. But i mainly want this so i can have the ability to relog on the same instance on say, a vanilla version, where the original instance was made on a fabric version. Or maybe i want to have the same servers throughout all my 1.20 instances, so i can have them all share the same folder.

**Comment by Trial97** [comment]
You can copy using symlinks on supported filesystems
