### ISSUE TITLE
1.21 is missing

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#2527]
### Version of Prism Launcher

6.3

### Version of Qt

idk im on windows

### Description of bug

it should auto fill with 1.21? latest says 24w21b

### Steps to reproduce

a

### Suspected cause

not sure how prism launcher populates versions, im assuming directly from mojang somewhere? maybe mojang changed the api

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
updated to latest prism launcher 8.3 and 1.21 is still missing

**Comment by Desyncfy** [comment]
Qt exists on windows. See [here](https://doc.qt.io/qt-6/windows.html).

**Comment by CyberFlameGO** [comment]
Can not reproduce this issue - have you tried refreshing?

**Comment by Trial97** [comment]
Try the following steps:
- ensure that the Metadata Server setting is empty(Settings>APIs>Services>Metadata Server)
- delete the meta folder that is inside the prism root directory( in your case delete `%APPDATA%/PrismLauncher/meta`)
- try portable
- ensure that nothing is blocking prism to access the network
- upload here the logs file found at '`%APPDATA%/PrismLauncher/logs/PrismLauncher-0.log`' (I suggest to use [mclo.gs](https://mclo.gs/))

**Comment by ghost** [comment]
Issue fixed itself it seems, how often does the metadata refresh and is there a button to manually refresh in future?

**Comment by Trial97** [comment]
no, but we plan to validate it on launch automatically.
