### ISSUE TITLE
Remove Launch Offline and Launch Demo buttons for checkboxes in startup settings

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#253]
### Role

I use the launcher.

### Suggestion

I want the demo and offline launch buttons removed and replaced with checkboxes in Settings --> Miscellaneous

### Benefit

So the UI is less messy with less mostly unneeded and unused buttons present in important areas.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flowln** [comment]
The demo button, maybe. But I do think offline launch is used enough / is useful enough to warrant the space it occupies.

In the instance settings, that space is already pretty empty, so I don't see much problem leaving them both there.

In the launch sub-menu, maybe a better approach to de-clutter it would be to turn the profiler things into checkboxes instead.

**Comment by Scrumplex** [comment]
What about restructuring the Launch button instead?

I was thinking about something like this:

![image](https://user-images.githubusercontent.com/11587657/197390701-6ee6cca8-3422-4659-beb5-a88dd58f490b.png)

Mockup: https://excalidraw.com/#json=J0YaczlkeNa2R3yme3Lhq,nphPtBWX9s3KlAC3QsIhHQ

**Comment by ghost** [comment]
Hey it could actually be a good solution.

**Comment by TheKodeToad** [comment]
Scrumplex's solution will be used
