### ISSUE TITLE
error prisma launcher does not run minecraft

### ISSUE THREAD

**Issue by kesha-trhk** [PrismLauncher/PrismLauncher#2530]
### Version of Prism Launcher

prism launcher 7.2

### Version of Qt

Qt 6.3.0

### Description of bug

when you run the build from an offline account, it is displayed that the build is running, but the game is not running, while the prisma launcher shows that it is running

### Steps to reproduce

I don't know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
update prism and play at least once online on that instance
