### ISSUE TITLE
Prism doesn't handle LWJGL version changes automatically.

### ISSUE THREAD

**Issue by Neekodesu** [PrismLauncher/PrismLauncher#2539]
### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.6.3

### Description of bug

https://discord.com/channels/602796788608401408/1252420001764212747 (Sodium discord)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/47283957/7ade7637-562d-4b6e-abb2-0ad368db8d4d)
Basically every prism user won't be able to use latest sodium update (0.5.10) if they don't manually change their LWJGL to 3.3.2
3.3.1/3.3.3 won't work. 3.3.2 works. But Prism should automatically do this.
In first case why would Prism use 3.3.1 from March-2023 instead 3.3.2?

### Steps to reproduce

Update to latest Sodium 0.5.10-1.20.1

### Suspected cause

Prism doesn't handle LWJGL version changes automatically.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neekodesu** [comment]
According to Sodium's discord, a Fabric 1.20.1 instance should be using 3.3.2 (and Prism is just setting 3.3.1 as default for no reason)

**Comment by Trial97** [comment]
Mojang says otherwise:https://piston-meta.mojang.com/v1/packages/b8055b5cf9c36f1f62fdf8338bff372368fea83e/1.20.1.json 
Prism uses Mojang meta to associate the LWJGL with a Minecraft version.
Yes you can change it in versions but by default for 1.20.1 the 3.3.1 is associated.
