### ISSUE TITLE
Changing minecraft version does not automatically change LWJGL, Intermediary Mappings, Fabric Loader, etc

### ISSUE THREAD

**Issue by theofficialgman** [PrismLauncher/PrismLauncher#2540]
### Role

all types of minecraft players

### Suggestion

I would like for all entries in the "Version" tab to automatically change to the correct version when the Minecraft version is manually changed.

### Benefit

So users don't change the Minecraft version without changing dependencies (eg: LWJGL) causing issues with the base game and mods.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This would be a big quality of life improvement. Right now, I go to the meta repo on github to determine what the correct matching version of LWJGL is for a particular version of minecraft when I change my instance version (eg: 1.21 https://github.com/PrismLauncher/meta-launcher/blob/master/net.minecraft/1.21.json#L478). This is tedious and causes issues if not done with the base game and mods.

**Comment by theofficialgman** [comment]
additionally, the suggested version information is available in the meta (see above link) and should be starred or otherwise highlighted within the version change dialog

**Comment by theofficialgman** [comment]
CC @topia @Neekodesu continuation of https://github.com/PrismLauncher/PrismLauncher/issues/2539 since that was incorrectly closed (likely due to lack of explanation)

**Comment by theofficialgman** [comment]
https://github.com/PrismLauncher/PrismLauncher/assets/28281419/3d9a27a2-1e14-4928-91fc-342d3492bdbb

**Comment by Ryex** [comment]
I could have sworn this was a fixed issue. can you replicate it on the latest nightly?
also #2539 was closed because they were wanting minecraft 2.21 to use lwjgl to 3.3.2  contrary to mojang's suggested version

**Comment by theofficialgman** [comment]
> can you replicate it on the latest nightly?

yes, it also happens on latest nightly

**Comment by Trial97** [comment]
Just me linking other issues here: https://github.com/PrismLauncher/PrismLauncher/issues/562 and https://github.com/PrismLauncher/PrismLauncher/issues/1358 
Could you use one of the mentioned issues?

**Comment by theofficialgman** [comment]
Neither of the other issues mention updating lwjgl, fabric loader, etc

this issue is better formatted in describing the problem (even it it does contain the contents of the other two issues).

**Comment by Trial97** [comment]
none mentioned the lwjgl but 562 mentioned the need to update the loader (not that fabric would need it ) and 1358 mentioned the exact component that needs to be updated in case of fabric.
Either way, when one is solved all three will be solved.

**Comment by jellysquid3** [comment]
This has been causing us [significant pain](https://github.com/CaffeineMC/sodium-fabric/issues/2561) with Sodium, since upgrading from MC 1.20.x to MC 1.21 seems to not update LWJGL to version 3.3.3, which our mod is built against. I've not been counting, but probably there has been a dozen reports of the issue across Discord servers in the past week or so, excluding our issue tracker.

**Comment by Ryex** [comment]
were working on it in #2528 and #2547
