### ISSUE TITLE
Config file resets after crash

### ISSUE THREAD

**Issue by Ultimatecreeper4** [PrismLauncher/PrismLauncher#2545]
### Operating System

Windows

### Version of Prism Launcher

Prism 8.3

### Version of Qt

Qt 6.3.3

### Description of bug

After playing on a server, the entire world stopped rendering. Then I left the server which crashed my game and when I rebooted it up all my settings and configs were reset. This has happened to me multiple times.

### Steps to reproduce

-world stops loading
-disconnect from server and game crashes
-load minecraft again to find out it all my settings have been reset.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is not a prism issue but a Minecraft one so I am closing this.
