### ISSUE TITLE
Total time played format setting.

### ISSUE THREAD

**Issue by eff3ry** [PrismLauncher/PrismLauncher#2546]
### Role

I play modded minecraft

### Suggestion

I want to be able to change the format in which the total playtime is displayed

### Benefit

Most game platforms like Steam show the total playtime in just hours so id like a setting to choose a custom format to display the total playtime. i.e 459.4hrs, or 459h 24m instead of the 19d 3h 24m

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/18133966/1c8e03dc-f083-4305-b650-daffa6e0f427)

**Comment by Cartrigger** [comment]
Go to Settings, Minecraft and change the option "Show time spent playing in hours" to on
