### ISSUE TITLE
The "Help" button in instance settings leads to a 404 page

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#255]
### Operating System

Windows

### Version of Prism Launcher

5.0-develop

### Version of Qt

5.15.6

### Description of bug

The "Help" button in the botton left corner of instance settings leads to a [nonexistent page.](https://prismlauncher.org/wiki/help-pages/Instance-Version)

### Steps to reproduce

Open an instance's "Edit Instance"

Click the help button in the bottom left corner.

### Suspected cause

The button not being tested and updated after a major website overhaul.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
this is because the website doesn't have every help page. this was a issue on polymc too

**Comment by DioEgizio** [comment]
opened https://github.com/PrismLauncher/prismlauncher.github.io/issues/97 on the website
