### ISSUE TITLE
After an update it is impossible to open the launcher

### ISSUE THREAD

**Issue by LoweredgamesDev** [PrismLauncher/PrismLauncher#2555]
### Operating System

Windows

### Version of Prism Launcher

8.3/8.4 - latest

### Version of Qt

6.6.3

### Description of bug

After downloading the update and closing the launcher, I can't open it anymore. I tried uninstalling it but nothing.

### Steps to reproduce

1. click on the update button
2. click on the update installer
3. after you close it and reopen it it doesn't open

### Fix (temporary solution)

> I am experiencing the same issue after updating this morning _(the update of 06.23.2024)_, I have temporarily downgraded to version [8.0.0](https://github.com/PrismLauncher/PrismLauncher/releases/tag/8.0) which resolved the problem.
> by @QuinnH2O 

### Suspected cause

It could be caused by the application or the shortcut? or installation?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LoweredgamesDev** [comment]
👍

**Comment by Trial97** [comment]
Try installing vs red
Like most apps on Windows, you have to install vcredist for Prism to run. Depending on what version of Prism you are using, you may need a different version.

You need:

- [vcredist 2022 x64](https://aka.ms/vs/17/release/vc_redist.x64.exe) if you're using PrismLauncher-Windows-MSVC (the recommended version for Windows 10 64 bit/Windows 11).
- [vcredist 2022 arm64](https://aka.ms/vs/17/release/vc_redist.arm64.exe) if you're using PrismLauncher-Windows-MSVC-arm64 (the recommended version for Windows 10/11 on ARM).

See the [wiki page](https://prismlauncher.org/wiki/overview/frequent-issues/#%22msvcp140_2.dll-was-not-found%22) on Prism's website for more information.

**Comment by LoweredgamesDev** [comment]
> Try installing vs red Like most apps on Windows, you have to install vcredist for Prism to run. Depending on what version of Prism you are using, you may need a different version.
> 
> You need:
> 
> * [vcredist 2022 x64](https://aka.ms/vs/17/release/vc_redist.x64.exe) if you're using PrismLauncher-Windows-MSVC (the recommended version for Windows 10 64 bit/Windows 11).
> * [vcredist 2022 arm64](https://aka.ms/vs/17/release/vc_redist.arm64.exe) if you're using PrismLauncher-Windows-MSVC-arm64 (the recommended version for Windows 10/11 on ARM).
> 
> See the [wiki page](https://prismlauncher.org/wiki/overview/frequent-issues/#%22msvcp140_2.dll-was-not-found%22) on Prism's website for more information.

I have the 2022 version. Is it still ok?

**Comment by LoweredgamesDev** [comment]
It doesn't work even if it's already installed

**Comment by Trial97** [comment]
Even if you install the latest one?

**Comment by LoweredgamesDev** [comment]
> Even if you install the latest one?

yes

**Comment by QuinnH2O** [comment]
I am experiencing the same issue after updating this morning, I have temporarily downgraded to version 8.0 which resolved the problem.

**Comment by Trial97** [comment]
Strange we had similar reports and for all after installing the vscred again it worked. Try to see if the shortcut is good. If is then prism logs would be nice (they are inside the prism root folder inside the logs) the one that ends with 0. If empty then is vscred

**Comment by LoweredgamesDev** [comment]
> Strange we had similar reports and for all after installing the vscred again it worked. Try to see if the shortcut is good. If is then prism logs would be nice (they are inside the prism root folder inside the logs) the one that ends with 0. If empty then is vscred

if it is empty things? it's empty. I have to reinstall vcred

**Comment by LoweredgamesDev** [comment]
> Strange we had similar reports and for all after installing the vscred again it worked. Try to see if the shortcut is good. If is then prism logs would be nice (they are inside the prism root folder inside the logs) the one that ends with 0. If empty then is vscred

I downgraded to 8.0 and it works now. I think there is a problem with the installation dependencies or the update schedule. I'll keep it open until it's resolved.

**Comment by LoweredgamesDev** [comment]
> I am experiencing the same issue after updating this morning, I have temporarily downgraded to version 8.0 which resolved the problem.

thanks 👍

**Comment by WizardNB** [comment]
I encountered the same situation.I downgraded to 8.3 and it functions again.

**Comment by SilveradoTDS** [comment]
I have the same issue myself with 8.4 on my windows 10 PC, and it seems to be only windows 10/11..

Linux Mint (which is a debian distro) opens 8.4 just fine

**Comment by FriskTheFallenHuman** [comment]
I've tested this problem and i found out that the MinGW builds do not have this sort of crash rn

**Comment by Djspac3** [comment]
SAME so there's a visual stuidio install? that I need to get so it works?

**Comment by Ryex** [comment]
For everyone here, the main issue is that there was a VC2022 redistributable update in may and Github updated the visual studio version in CI so our latest build end up using this verison. To use the MSVC version you simply need to reinstall the latest version of the 2015-2022 C++ Redistributable 

X64 | [Microsoft Visual C++ Redistributable 2022 x64](https://aka.ms/vs/17/release/vc_redist.x64.exe)
Arm64 | [Microsoft Visual C++ Redistributable 2022 arm64](https://aka.ms/vs/17/release/vc_redist.arm64.exe)

Latest version as of this message is version 14.40.33.8.10

In the future there will be better testing to catch this kind of thing and we'll be looking into installation methods

**Comment by Djspac3** [comment]
kind of wished this was packed with the launcher tbh

**Comment by Ryex** [comment]
> kind of wished this was packed with the launcher tbh

Microsoft does not generally allow the VC++ redistributable to be repackaged.

**Comment by fantahund** [comment]
Maybe you should issue a warning if it's missing? I mean some of us know how github works and find out what the bug is. But the normal end user can't find the section here and especially not when the issue is closed.

**Comment by Ryex** [comment]
> Maybe you should issue a warning if it's missing? I mean some of us know how github works and find out what the bug is. But the normal end user can't find the section here and especially not when the issue is closed.

such a check could only ever be done in the installer/updater before installing the new version by detecting which version of the redist the new version needs. This detection is next to impossible to do reliably. 

We are looking to change the windows packaging format in a manor to allow the redist to be included.

**Comment by Djspac3** [comment]
Ty that would be SUPER nice

**Comment by icd-t** [comment]
Ive got all the prerequisites installed, yet the prism executable just does nothing...
(Yes, I have the newest VC Redist)

**Comment by randomidiot2887** [comment]
installing vcredist fixed it for me
