### ISSUE TITLE
account expired

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#2559]
### Operating System

Windows

### Version of Prism Launcher

prism launcher 8.4

### Version of Qt

dont know doesnt say

### Description of bug

i have a couple accounts and they all expire like every 1-3 days so i gotta login again all the time

### Steps to reproduce

try to play game > account expired

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This means that the refresh token is no longer valid: most probably it was regenerated by another prism. Do you share your account? If not my suggestion is to change your password, remove prism permissions and then relogin in prism.

**Comment by ghost** [comment]
i dont share my account

**Comment by Trial97** [comment]
then follow the steps with changing the password and regarding access to prism.
This should only happen if the refresh token is invalidated(happens when you log in using the same app but on a different device).

**Comment by ghost** [comment]
ok but where can i find what apps have access to my microsoft account and i also dont have password on the account

**Comment by Trial97** [comment]
Here :https://answers.microsoft.com/en-us/outlook_com/forum/all/managing-apps-and-services-connected-to-our/63b5d3aa-30b9-49dd-a729-9ba13df4e1eb

But if you do not have the password it may not work.

**Comment by ghost** [comment]
now it happens everyday and i only play on the account so i gotta re login each day nothing is working

**Comment by Trial97** [comment]
Yep nothing we can do if you can't access your account to change your password

**Comment by ghost** [comment]
i changed all the password and signed out everywhere still happening :(
