### ISSUE TITLE
Let the user know of the "Disable Java compatibility checks" option.

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#256]
### Role

I use the launcher.

### Suggestion

I want the launcher to inform the user of how and where they can disable the Java compatibility check and where they can download the needed version of Java whenever the check doesn't let the instance start up.

### Benefit

so it's more intuitive for new users.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ghost** [comment]
> I want the launcher to inform the user of how and where they can disable the Java compatibility check

Disabling the Java compatibility check won't be a very good idea, because using an incompatible Java version would make the instance very unstable if it doesn't crash on startup

> and where they can download the needed version of Java whenever the check doesn't let the instance start up.

It already does that:
![image](https://user-images.githubusercontent.com/110736028/197567351-fe8aa6ab-a42f-4a8c-90b5-db6bbcf8d865.png)

**Comment by ghost** [comment]
> It already does that:

No, it does not, it just tells the user to use java 8 with no hint at how the user can download it.

**Comment by Scrumplex** [comment]
Fixed in #346
