### ISSUE TITLE
[MacOS] Prism doesn't currently located Java installations located in /Library/Java/JavaVirtualMachines

### ISSUE THREAD

**Issue by porterporter** [PrismLauncher/PrismLauncher#2563]
### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.6.3

### Description of bug

https://github.com/dqfan2012/PrismLauncher/blob/adf0cfdebf2d27148139da2965900a9b3c1ec389/launcher/java/JavaUtils.cpp#L355

Something about this directory walk function isn't quite working.
For example, /Users/porter/Library/Java/JavaVirtualMachines/azul-1.8.0_372/Contents/Home/bin/java isn't located.

Maybe switching to something similar to the SDKMAN folder would work
`FS::PathCombine(home, "/Users/porter/Library/Java/JavaVirtualMachines/")`
and then walking that directory.

### Steps to reproduce

* Install JDK to Library>Java>JavaVirtualMachines
* Click auto-detect in instance java config
* JDK doesn't show up

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is most probably because we do not search that path

**Comment by Aces-and-Jacks** [comment]
This can probably be closed now since it works
