### ISSUE TITLE
Prism Launcher Will Not Open After Updating

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [PrismLauncher/PrismLauncher#2568]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

IDK, I can't access Help -> About Prism Launcher -> About Qt.

### Description of bug

When try to open Prism Launcher (Through the desktop shortcut, the little pinned taskbar icon, or the C:\Prism Launcher\prismlauncher.exe) it does not open. If I looko in task manager it does show up for ~1-3 seconds and then disappears.

https://github.com/PrismLauncher/PrismLauncher/assets/69123018/e45ec5e8-c6aa-4986-ae4c-c8e429d199fb

### Steps to reproduce

Update Prism Launcher from 8.2 to 8.4
Open Prism Launcher
(It doesn't open)

### Suspected cause

I got no idea man. Maybe it's because I updated from 8.2 to 8.4 rather than from 8.2 to 8.3 to 8.4.

NOTE: after updating and it not opening, I also tried using the installer from the website, but that seemed to have no effect on the issue.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
duplciate of https://github.com/PrismLauncher/PrismLauncher/issues/2555
use mingvw version if nothing works
