### ISSUE TITLE
при попытке войти в аккаунт Microsoft в лаунчере появляется окно с надписью обработка и ползунок загрузки не движется и так бесконечно 

### ISSUE THREAD

**Issue by 432lk** [PrismLauncher/PrismLauncher#2575]
### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.3 

### Description of bug

при попытке войти в аккаунт Microsoft в лаунчере появляется окно с надписью обработка и ползунок загрузки не движется и так бесконечно  

### Steps to reproduce

добавить учётную запись

### Suspected cause

незнаю 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Please use English.
You need to open that link and log into your Microsoft account in the browser.
That progress dialog symbolizes how long you have left until the provided code expires.
If you have any other issues regarding login please first try the solutions mentioned here: https://github.com/PrismLauncher/PrismLauncher/issues/2302
As the login procedure is external, I will close this issue in favor of the one mentioned.
PS. From the reports I got so far is that Microsoft may block IP from Russia I suggest you use a VPN to connect(please do try the other solution before reporting back).
