### ISSUE TITLE
Allow zooming in and out in minecraft log

### ISSUE THREAD

**Issue by Loedje** [PrismLauncher/PrismLauncher#2576]
### Role

I play modded minecraft

### Suggestion

I want to zoom in or out in the minecraft log

### Benefit

For me the launcher is weirdly zoomed in, so for me it would increase readability

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/324
