### ISSUE TITLE
Autoupdater does not work on Linux systems

### ISSUE THREAD

**Issue by mrmelon54** [PrismLauncher/PrismLauncher#2586]
### Role

I use Linux

### Suggestion

Fix autoupdater

### Benefit

Just makes updating easier

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

```
[pid 34208] 01:07:12 execve("/tmp/PrismLauncher-Linux-Qt5-8.4.tar.gz", ["/tmp/PrismLauncher-Linux-Qt5-8.4"...], 0x7fff7c096ac8 /* 63 vars */ <unfinished ...>
[pid 34207] 01:07:12 +++ exited with 1 +++
[pid 34178] 01:07:12 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=34207, si_uid=1000, si_status=1, si_utime=0, si_stime=0} ---
[pid 34208] 01:07:12 <... execve resumed>) = -1 ENOEXEC (Exec format error)
```
Running the autoupdater on Linux systems tries to execute the tar.gz archive as a binary. That obviously doesn't work. Maybe some code should be added to properly extract the archive into the directory the binary was executed from?

Looks like modifying this line could resolve the issue:
https://github.com/PrismLauncher/PrismLauncher/blob/196b2b5a3ed20dc4a23f4c2d62e1f46e886aba6a/launcher/updater/prismupdater/PrismUpdater.cpp#L1023

I just tested 8.3 portable version and it works fine there. Not sure why running the non-portable version would be any different, except for the line linked above.

**Comment by Ryex** [comment]
The app updater  was never designed to work with a non portable Linux installation. the assumption is that if your running on linux with the updater enabled in the build your using an appimage or a portable install. it is also completely missing the libraries it would need to extract tar archives.

If your running an install from a package manger this is a packaging error,

**Comment by mrmelon54** [comment]
I am not using the MPR packaging version because I don't want to install the openjdk jre as I already have loads of JDKs installed.
I am not using the portable version because I am not using it in a portable environment (I want it to use the default `~/.local/share` directory).
According to the source code the portable version just runs the tar binary to extract the archive:
https://github.com/PrismLauncher/PrismLauncher/blob/196b2b5a3ed20dc4a23f4c2d62e1f46e886aba6a/launcher/updater/prismupdater/PrismUpdater.cpp#L1190-L1195

If you are not willing to make this change, please at least add an error message. As currently the updater just exists as if everything went fine. But the updated version of the application has not replaced the older version.
Also can this be reclassified as a bug instead of an enhancement.

I would test the windows non-portable version but I just get unknown network errors in my VMs.

I hope someone actually bothers to read this....

**Comment by Ryex** [comment]
> I am not using the portable version because I am not using it in a portable environment (I want it to use the default ~/.local/share directory).

If this is the behavior you want,  then once  #1529 makes it into a release use the portable version and create a path next to the `portable.txt` called `UserData` and symlink it to wherever you want.

**Comment by mrmelon54** [comment]
That honestly just feels like a worse solution that fixing the updater by changing that one condition check to find ".tar.gz" as an archive. (For my specific usecase)
https://github.com/PrismLauncher/PrismLauncher/blob/196b2b5a3ed20dc4a23f4c2d62e1f46e886aba6a/launcher/updater/prismupdater/PrismUpdater.cpp#L1023

**Comment by Ryex** [comment]
Well, the use case is cursed, and I'm betting there will packaging issues down the line. but there no real reason it *won't* work. I apparently wrote the logic robust enough to find the correct build artifact.

**Comment by mrmelon54** [comment]
It also finds the AppImage.zsync as a valid download target. Which obviously won't work properly.

> I'm betting there will packaging issues down the line

Maybe a special file like `portable.txt` but in `/etc/prismlauncher/package-manager.txt` which disables the auto updater.

Or just disabling the updater if the binary file isn't writable by the current user?

**Comment by Ryex** [comment]
still not sure how your not triggering this check though

https://github.com/PrismLauncher/PrismLauncher/blob/196b2b5a3ed20dc4a23f4c2d62e1f46e886aba6a/launcher/updater/prismupdater/PrismUpdater.cpp#L583-L587

**Comment by mrmelon54** [comment]
Just checked the logs, I'm pretty sure this explains it
```
0.000 D | Build Artifact             :  "Linux-Qt5"
```
