### ISSUE TITLE
Play Prism Launcher through Steam Link with PC Big Picture Mode

### ISSUE THREAD

**Issue by GlydetheSurfer** [PrismLauncher/PrismLauncher#2587]
### Role

I play modded minecraft. <-- Quite literally all the time.

### Suggestion

Support Steam Big Picture on "PC"

### Benefit

To play it through Steam Link anywhere I'm at.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I've been trying to find a way to play modded minecraft at someone elses house from my own pc at home without actually being there. (using Steam Link) I really want this to be a thing, but no matter where i look I always see "Steam Deck" instead... Google doesn't show me the results I want. and it aggravates me. I've been looking everywhere for a solution to do this and have found none...

**Comment by Trial97** [comment]
Not gonna happen: the best you can look at https://github.com/PrismLauncher/PrismLauncher/issues/817 or https://github.com/PrismLauncher/PrismLauncher/issues/1936 
But mostly they are dead ends as the valve will not allow the launcher on Steam without approval from Microsoft

**Comment by GlydetheSurfer** [comment]
Ah ok.. that's unfortunate.. at least i got an answer from somewhere... (unlike google). thanks for the help anyways.
