### ISSUE TITLE
An option to disable playtime bar

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#259]
### Role

I use the launcher.

### Suggestion

I want there to be a section in UI settings to toggle some of the not nessesary UI elements (such as news or playtime)

### Benefit

More choice, less clutter.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Scrumplex** [comment]
You can disable news and the sidebar already

**Comment by DioEgizio** [comment]
<img width="171" alt="image" src="https://user-images.githubusercontent.com/83089242/204306486-ea71b419-1295-49ce-964b-9aef81e1af38.png">

as scrumplex said, you can already do that

**Comment by DioEgizio** [comment]
the playtime one not though, so gonna keep this open
