### ISSUE TITLE
Prism Launcher 8.4 not launching on Windows OS

### ISSUE THREAD

**Issue by CRxFT** [PrismLauncher/PrismLauncher#2591]
### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Program will not run

### Description of bug

Program not launching/running on windows os

### Steps to reproduce

Prism launcher not running on windows os

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2564

**Comment by Pacomatic1** [comment]
They did something with the C++ Redistributables, so go to prismlauncher.org and see the download page. It'll show what C++ Redistributables you need to download.

**Comment by CRxFT** [comment]
Solved. Thanks for the help guys.
