### ISSUE TITLE
Prism fails to start Seaopolis 2

### ISSUE THREAD

**Issue by metalim** [PrismLauncher/PrismLauncher#2594]
### Operating System

macOS

### Version of Prism Launcher

Prism 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

Prism installs Seaopolis 2 from CurseForge, but fails to start it with error: `Instance update failed because: Game update failed: it was impossible to fetch the required libraries.`
Log file: https://mclo.gs/muBYfYI

### Steps to reproduce

Install Seaoplis 2 in Prism 8.4 from CurseForge, try to launch it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Delete meta folde:`/Users/********/Library/Application Support/PrismLauncher/meta`
Ensure that Settings>APIs>Metadata Server is empty
Restart prism
Then try again
If that doesn't work then upload prims logs `/Users/********/Library/Application Support/PrismLauncher/logs/PrismLauncher-0.log`
PS. make sure that prism is not blocked by firewall or something.

**Comment by metalim** [comment]
That helped. Thanks

**Comment by Trial97** [comment]
Ok then I will close this issue if the issue was fixed
