### ISSUE TITLE
Automatically continue downloading mods and delete them from downloads folder when found.

### ISSUE THREAD

**Issue by merll002** [PrismLauncher/PrismLauncher#2595]
### Role

I download modpacks

### Suggestion

Automatically continue downloading mods and delete them from downloads folder when found.

### Benefit

Extremely convenient

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

When installing a modpack that requires mods to be manually downloaded, it would be very convenient for it to remove the mods from the download folder and automatically start downloading.

**Comment by Trial97** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/874
