### ISSUE TITLE
Error logging into microsoft [Solved: Xbox servers are down]

### ISSUE THREAD

**Issue by Zexerif** [PrismLauncher/PrismLauncher#2602]
### Operating System

Windows

### Version of Prism Launcher

8.4

### Version of Qt

6.6.3

### Description of bug

Whenever i try to log into my microsoft account it got "errored". I logged out and tried to log back in and then this happened: 
![image](https://github.com/PrismLauncher/PrismLauncher/assets/86855558/31e64f86-c7c5-447d-a875-2643b7d3804e)
I have tried to reopen the launcher but it still didnt work. 

### Steps to reproduce

Log in

### Suspected cause

Mabye microsoft's servers are down? Im not sure

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by IzeAack** [comment]
Same issue

**Comment by Zexerif** [comment]
> Same issue

Server might be down then...

**Comment by Zexerif** [comment]
didnt mean to do that

**Comment by IzeWare** [comment]
sorry unintentionally deleted the comment 
original comment "same issue"

**Comment by oxydisia** [comment]
Same 
![image](https://github.com/PrismLauncher/PrismLauncher/assets/174511820/dbc9b7c2-5860-4943-b7ea-d98ad87ff504)

**Comment by ruineka** [comment]
Same error here as well. The Xbox Live servers say they are all online.

**Comment by benthetechguy** [comment]
Same issue; I think they don't realize yet.
The fact that logging into https://xbox.com gives me an infinite loop instead of an account page means this isn't a Prism Launcher problem.
https://downdetector.com/status/xbox-live/

**Comment by Zexerif** [comment]
so uh.. while we wait, hows the wife?

**Comment by oxydisia** [comment]
Before that, try to play the game, but after some attempts, I logged out my account from the launcher
I don't have wife, so feels free

**Comment by IzeWare** [comment]
The official launcher doesn't work too 
![Screenshot 2024-07-02 145619](https://github.com/PrismLauncher/PrismLauncher/assets/114884311/eed376cb-2d66-4935-ae49-80a520e17fc1)

**Comment by Zexerif** [comment]
Servers are down

**Comment by Zexerif** [comment]
(sorry this is so messy, its really early in the morning for me)

**Comment by Bandanakeks** [comment]
According to the Discord, 
![image](https://github.com/PrismLauncher/PrismLauncher/assets/96304272/e28cca41-d5fd-4628-ac93-2d19cd43f2df)
I also have the same problem

**Comment by Nanianmichaels** [comment]
Can confirm, same issue, but not just limited to Prism Launcher. The Fallout 76 launcher also complains of not being able to log in to XBOX, and downdetector is showing a rather large spike starting about an hour ago for XBOX Live, with logins being affected.

So, this doesn't seem to be an issue on Prism's side, it will probably resolve itself soon(TM).

**Comment by oxydisia** [comment]
![image](https://github.com/PrismLauncher/PrismLauncher/assets/174511820/dfe081e3-55d9-46aa-905a-f7fdbe83a100)
Just one screen. Microsoft servers is dead

**Comment by Zexerif** [comment]
![image](https://github.com/PrismLauncher/PrismLauncher/assets/86855558/dec4a163-7b90-41aa-976c-bdadc1f1ab34)

**Comment by benthetechguy** [comment]
Could I have a link to that page?

**Comment by Zexerif** [comment]
> Could I have a link to that page?

https://support.xbox.com/en-CA/xbox-live-status

**Comment by benthetechguy** [comment]
lmao you have to impossibly log in to get notified when it's fixed

**Comment by dantaeusb** [comment]
I missed the part where the 3rd party launcher prevents me from playing LAN in my home because there's some super mega 999999999 SLA AI cloud platform somewhere is down again.
Basically, fair to say that "play offline" is not offline, even in FOSS? That's some cursed timeline.

**Comment by benthetechguy** [comment]
Log in once to prove you own the game, then play offline all you want. The only time you can't actually play offline is if you delete that login like we all did while troubleshooting, and then Prism Launcher doesn't have a way to know that you own the game, so it doesn't let you play.

**Comment by dantaeusb** [comment]
@benthetechguy I clearly used "Launch Offline" on an account I've bought the game several years ago from the official store, and played for several hours recently. I did not delete anything. #2603 is another confirmation of such behavior, and if that's behavior intended by Prism contributions and not a bug, I feel very wrong about this situation.
I have absolutely the same behavior on another computer, where an online account was too used recently (two days ago) and it clearly asks for permission from Microsoft to start the game when using "Launch Offline" option. – corrected to the language used in Launcher so there are no misunderstandings.

**Comment by benthetechguy** [comment]
I believe for play offline to truly work offline, you need to add your account as an "offline account" when you initially log in.
