### ISSUE TITLE
Failed to get authorization for xbox services. Error Code %2

### ISSUE THREAD

**Issue by frumpymussel13** [PrismLauncher/PrismLauncher#2604]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.3.3

### Description of bug

![Screenshot 2024-07-02 153707](https://github.com/PrismLauncher/PrismLauncher/assets/108240500/b7ff46af-d43b-4b1a-9e8e-45ab9bce59cf)

### Steps to reproduce

*remove account

*add account | i think

### Suspected cause

IDK

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Servers are down

**Comment by frumpymussel13** [comment]
Help i wanna play mc

**Comment by timitoerner** [comment]
If you are already logged in you can play offline if you turn off wifi or disconnect your LAN cable

**Comment by icarosadero** [comment]
The error message should at least tell that the login servers are unreachable. Outputting just `%2` doesn't tell anything and should be taken as a bug.

**Comment by Trial97** [comment]
> The error message should at least tell that the login servers are unreachable. Outputting just `%2` doesn't tell anything and should be taken as a bug.

This should be fixed in dev builds
