### ISSUE TITLE
Fix freeze associated with mod icons.

### ISSUE THREAD

**Issue by Fleepe** [PrismLauncher/PrismLauncher#2606]
### Role

I play modded Minecraft.

### Suggestion

Load and save instance mod icons.

### Benefit

With a large number of mods there will be no freeze when loading mod icons..

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

<details><summary>Detailed description:</summary>
<p>
I have ~130 mods in my instance and almost every mod has its own icon. Prism Launcher loads these icons when I go to the Mods tab, causing a very noticeable freeze. I suggest you make Prism Launcher download and save these icons somewhere to remove this freeze. I understand that, of course, this can be fixed by limiting the number of simultaneous tasks and downloads, but in my opinion, it is better to just save these icons and not load them every time.
</p>
</details>

**Comment by Trial97** [comment]
The icons are not downloaded but extracted from the mod file itself.
And this was already suggested here: https://github.com/PrismLauncher/PrismLauncher/issues/1506
