### ISSUE TITLE
I want to see Skin Changer Roll like a Minecraft Official Launcher

### ISSUE THREAD

**Issue by Linaryx** [PrismLauncher/PrismLauncher#2608]
### Role

I play any version of minecraft

### Suggestion

I want to see Skin Changer Roll

### Benefit

so you don't have to go to the official launcher

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I want to see Skin Changer Roll like a Minecraft Official Launcher

**Comment by Trial97** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/330
ps also implemented in nightly
