### ISSUE TITLE
Unable to launch any version of Minecraft through Prism Launcher

### ISSUE THREAD

**Issue by neelayplays** [PrismLauncher/PrismLauncher#2614]
### Operating System

Microsoft Windows 10 Enterprise LTSC 
System Type	x64-based PC
Processor	Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz, 2527 MHz,
JAVA version    jre-8.0.412.8-hotspot

### Version of Prism Launcher

PrismLauncher-Windows-MSVC-Setup-8.4.exe
(https://github.com/PrismLauncher/PrismLauncher/releases/download/8.4/PrismLauncher-Windows-MSVC-Setup-8.4.exe)

### Version of Qt

Qt 6.7.1

### Description of bug

Unable to Launch any version of Minecraft Through Prism Launcher 
before you tell me go and update my Graphics Drivers they are already updated 
NOTE: i am only unable to launch Minecraft (any version) Through prism launcher 
I am perfectly fine launching MC through other launchers such as ATLauncher, SKLauncher 
Logs from Prism launcher - https://mclo.gs/bALubcB
Log from ATLauncher - https://paste.atlauncher.com/view/665a9084-8ec1-4d0d-b263-885438db3cfa

### Steps to reproduce

Not sure if it can be replicated as this is an Issue i have only seen on my system 
Priem Launcher works flawlessly on My friend's laptop

### Suspected cause

Not Sure, Maybe something to do with OpenGL as i receive the same error when launching Minecraft 1.17+ as it requires a higher version of OpenGL than what is supported by my system

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
try using the same java in prism as you do in atlauncher: `**USERSDIR**\runtimes\minecraft\jre-legacy\windows-x64\jre-legacy`

Also not related but you can try enabling Native libraries: Instance Settings>Workarounds>Use System installation of GLFW

**Comment by neelayplays** [comment]
> try using the same java in prism as you do in atlauncher: `**USERSDIR**\runtimes\minecraft\jre-legacy\windows-x64\jre-legacy`
 
This fixed it thankyou so much 
before i Mark this as closed can someone tell me what is jre-legacy cause I didn't install it myself

**Comment by Trial97** [comment]
> before i Mark this as closed can someone tell me what is jre-legacy cause I didn't install it myself

Is the java installed by Minecraft standard launcher(or by ATLauncher).
