### ISSUE TITLE
Prism Launcher wont connect using Starlink

### ISSUE THREAD

**Issue by jjconroy** [PrismLauncher/PrismLauncher#2615]
### Operating System

Windows

### Version of Prism Launcher

https://github.com/PrismLauncher/PrismLauncher/releases/download/8.4/PrismLauncher-Windows-MSVC-Setup-8.4.exe

### Version of Qt

6.6.3

### Description of bug

After getting annoyed with Curseforge sometime ago on my old PC I switched to using prism launcher and it was working great until it randomly stopped being able to connect to the internet. After some troubleshooting I found the cause appeared to be switching to using Starlink internet. If I switched back to my old ISP, prism could connect fine. That PC was running Windows 10 Pro.

I did some digging and tried a few fixes like rolling back my version and deleting various files. Also tried reinstalling a few times but the problem would always come back very quickly. Sometimes I couldn't even get a Microsoft account connected as it would just get stuck on ‘Working…’ for ever.

I found a post about someone having similar issues with another third-party launcher for a different game (can't seem to find the post now) and someone suggested using Cloudflare Warp as a workaround. That did seem to work but I don't have the technical knowledge to know why.

I’ve been reminded to try and solve this issue as I just got a new PC with a fresh Windows 10 Home install and installed fresh prism 8.4 which is having the same issue. I uninstalled prism with Geek Uninstaller and reinstalled a fresh copy of 8.4 again. After adding an account and getting the status to ‘Ready’ I closed and re-opened the launcher and now am back to being stuck offline. Also unable to browse any modpacks.

Across both PCs I have tried at least prism versions 6.3, 8.3, 8.4 and possibly some others in between, all resulting in the same issue. I would appreciate some assistance from in trying to solve this. Happy to provide any logs/screenshots/etc that might be of use.

I did find two similar issues already raised but I am still unsure how to solve the issue:
https://github.com/PrismLauncher/PrismLauncher/issues/1248 
https://github.com/PrismLauncher/PrismLauncher/issues/2074

### Steps to reproduce

- Connect to Starlink
- Install Prism Launcher 
- Add Microsfot account
- Restart Prism Launcher 
- Can no longer connect to the internet

### Suspected cause

It seems like the cause of the problem is trying to use Prism Launcher over Starlink internet but I have no idea why that should cause any issues.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
can you try the nightly version and provide some logs from that( the logs on 8.4 and lower are not so verbose) 
 https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop 
 the logs can be found inside the logs folder that is inside the prism root data folder(the file that ends with 0 is the most recent
also because you already determined that it works with other isp maybe Starlink blocks some of the prism traffic

**Comment by jjconroy** [comment]
Insalled this build https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop/PrismLauncher-Windows-MSVC-Setup-330c95e-Debug.zip

Trying it using Starlink I get stuck when trying to link an account:
![Screenshot 2024-07-06 220117](https://github.com/PrismLauncher/PrismLauncher/assets/39813175/c07bca44-ef53-4143-9482-a85baa5d9b8c)

If I switch back to my old ISP it seems to work fine and brings up the QR code window.

**Comment by Trial97** [comment]
This is not an issue with the launcher but with the ISP: from the logs all network requests are blocked.
Suggestion stick with the old ISP
