### ISSUE TITLE
I can't fix error code 1 and i cant switch between java versions

### ISSUE THREAD

**Issue by Thestorm142** [PrismLauncher/PrismLauncher#2621]
### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

6.6.3

### Description of bug

I try and change the java version, the star isn't on the selected one

### Steps to reproduce

edit>settings>java version> auto detect

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
The star on java is not important choose the correct version for your instance:
    Java 8 for 1.16.5 and older
    Java 17 for 1.17 until 1.20
Java 17 for 1.21 and newer
