### ISSUE TITLE
Shader stopped working

### ISSUE THREAD

**Issue by ssscott75044** [PrismLauncher/PrismLauncher#2624]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 5/6

### Description of bug

I've been running SEUS shaders on steam deck for a couple years now with iris. Last month when I started the game, it didn't display correctly.  The screen is split into two flickering triangles.  Some semblance of what's supposed to be displayed can be seen, in some directions, but essentially blind.  The only thing I changed was to accept Prism being updated.  I think that was version 8.3.  The latest update had no apparent impact on this problem.  I've had to disable shaders to continue playing.  I've observed that when I try to open any folders through Prism, nothing happens.  So, I wonder if there's a permissions problem.  But the game runs fine with shaders disabled.  I've tried to search for an answer to this problem, with no luck.

### Steps to reproduce

I had been playing Minecraft 1.20.1, and reproduced the problem only by trying to re-enable shaders, with I believe Prism 8.3 and Prism 8.4. I finally upgraded to Minecraft 1.20.2, with the same result.  I then upgraded to 1.21, and when I tried to enable shaders, nothing happened at all.  With the log enabled, it said the shaders weren't compatible.  I had been loading a SEUS PTGI file on my system.  I then tried loading BSL through modrinth, but the behavior is the same.  By rebuilding the instance I've been able to get it to not give an error when enabling either shader, but the division of the screen into two flickering triangles still happens.

### Suspected cause

Maybe permissions are the problem, as nothing happens when I click any of the "open folder" buttons in Prism.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ssscott75044** [comment]
Clicking the "open shaders folder" button in minecraft also makes nothing happen.  I've had some difficulty getting anything to happen when clicking "open shader settings", but I'm not sure of the cause and effect.  Sometimes it works.

**Comment by ssscott75044** [comment]
Qt 6.7.2

**Comment by Trial97** [comment]
Open folders action will fail if qt doesn't find a program that can open that path(also this was already reported somewhere) 
The shaders are not changed in any way or form by Prism, so if the game tells you they are incompatible, it is not Prism's fault( we can't do anything to change that).

**Comment by ssscott75044** [comment]
Hold on a freaking second here. How is this closed? I still have a problem that occurred when Prism was updated. I attempted to provide information to help discover what the problem is. If I'm wrong, that doesn't mean there's not a problem. I still can't create a new instance with shaders that works.

**Comment by Trial97** [comment]
If you go back a few versions of prism to see where this doesn't happen?
But again prism doesn't modify the files so there is no way this happens because of the prism update.
I closed it because even if you have a problem it doesn't look like a prism issue.

**Comment by ssscott75044** [comment]
Will older versions of Prism be compatible with Minecraft 1.21?  I don't know how to revert the Prism version, but I could try it.  Also, I would appreciate some kind of tip as to where to look for help otherwise.

**Comment by Trial97** [comment]
More or less they should be compatible with Minecraft 1.21.
Use a portable prism, not the installer one.
You can find old releases here: https://github.com/PrismLauncher/PrismLauncher/releases

**Comment by ssscott75044** [comment]
I don't know what portable means, and I find no download for earlier versions at the page referenced.  Everything points to latest release.

**Comment by ssscott75044** [comment]
Okay, I found it.  I don't think I can install this without causing problems.  I've had to redirect instances away from the primary drive because it doesn't have enough space.  Also, I haven't understood how it's accessing Java because the listed path doesn't exist.  When I try to install it asks for the Java path, so I don't know what to put.  If I extract the gz to a secondary drive, will it be runnable from there and will it be able to find java 21?

**Comment by ssscott75044** [comment]
Additionally, if you're confident this isn't a prism problem, maybe you have confidence to suggest what actually is the problem.  After all, it's prism that I'm having a problem with as the end-user.

**Comment by Trial97** [comment]
Portable is the artifacts that end with the `Portable` suffix:
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/308f8c1a-b87a-4faa-8bea-a01281fe94ea)
All you need to do is unzip the archive and double-click on the Prismlauncher executable from the new folder. Portable also means that all the files and settings will be in the extracted folder and will not influence global installation in any way
 

Regarding java please consult our documentation https://prismlauncher.org/wiki/getting-started/installing-java/ and https://prismlauncher.org/wiki/help-pages/java-settings/

I'm confident is not a prism issue because to be a prism issue that would imply that prism modifies in any shape or form the shaders, which it doesn't the only stuff prism does with the files is list them.
And no I don't know why shaders decided to not work: maybe is the mod that loads them(Prism is not responsible for loading the shaders).

For issues that are not related to the launcher, I recommend joining our discord channel https://prismlauncher.org/discord and asking inside the support channels.

**Comment by ssscott75044** [comment]
You're saying the problem is with Iris, I guess. If that's true, how could the shaders stop working when I changed nothing?  I have to actively update Iris, and I didn't. I wasn't even aware that Minecraft 1.21 existed at the time, let alone 1.20 beyond .1. 

If the problem isn't with Prism, I think it has to be the OS or some other update that incidentally impacts the operation of how I'm playing Minecraft. I can't put the genie back in the bottle with my regular game, because I've changed to the latest versions in the hope of fixing this problem. I do have my instance that I was running of Minecraft 1.20.1 when this problem occurred. If you can think of any experiment I can perform with that to help reveal the problem, I would appreciate it.

**Comment by Trial97** [comment]
> how could the shaders stop working when I changed nothing?

That is my question but with prism in mind:  `How could the shaders stop working when Prism doesn't change the shaders files?`



> If you can think of any experiment I can perform with that to help reveal the problem, I would appreciate it.

Did you try with a previous version of prism like I suggested?
Also discord would be better for this kind of stuff so go ask there for more suggestions.
If you want you can also go ask on Iris discord if you are not satisfied with prism: https://jellysquid.me/discord
