### ISSUE TITLE
CurseForge API ToS violation

### ISSUE THREAD

**Issue by YukariWaffle** [PrismLauncher/PrismLauncher#263]
https://support.curseforge.com/en/support/solutions/articles/9000207405-curse-forge-3rd-party-api-terms-and-conditions

I believe that Prism Launcher is in violation of the following clause in the CurseForge API ToS:
2.2: `each Developer will be issued a unique API Key (the “API Key”), which is non-transferable and may not be shared with any third party. Developer may not disclose the API Key to any third party`
This is because the API key is shared/disclosed in the source code and binary distributions.

In addition the developers are unable to implement the following in case of termination of the ToS due to anyone being able to download the source code or any binary releases of the launcher:
9.b: `Developer shall ... promptly delete or destroy all copies of any API Key`

In order to oblige with the CurseForge ToS, Prism Launcher would have to not include the the CurseForge API key in its source code nor in its binary releases. Instead Prism Launcher would have to send the request to a dedicated server which in turn would hold the API key and perform the actual request (as is the industry standard).

Note that according to my understanding of the ToS this solution would not violate 3.1.e as long as:
- The server that performs the request belongs to or is acting on behalf of the developers.
- The server that performs the request is not itself using a proxy server or VPN to perform the request (it may use a proxy server or VPN to accept the request from the client however).

This is because said clause uses the term "your identity", and "You" in context of the ToS is defined as the developer, so it needs to be the developer's "identity or geographic location" that is not concealed.

What prompted me to investigate this issue were the various comments by Scrumplex and a few others in this thread: https://github.com/flathub/flathub/issues/3600. If I understand the comments correctly, violations of the CurseForge API ToS might endanger Prism Launcher's participation in Flathub https://github.com/flathub/flathub/pull/3596.

I believe that this issue applies to both Prism Launcher and PolyMC, as well as any PolyMC fork that is modern enough to include the CurseForge integration, excluding fn2006's PollyMC fork as it has removed the API keys.

**Comment by DioEgizio** [comment]
cf said that it's fine to have the API key in plaintext, and following perfectly their ToS is (intentionally?) impossible anyways

**Comment by YukariWaffle** [comment]
@DioEgizio Thank you for the clarification. Are you aware if this exception applies only to Prism Launcher or does it apply to all Prism Launcher forks? It might be desirable to document this somewhere so that any fork maintainers will be aware of what legal responsibilities they have with regards to CurseForge, as well as a possible legal defense if CurseForge decides to act against a fork due to this.

**Comment by DioEgizio** [comment]
> @DioEgizio Thank you for the clarification. Are you aware if this exception applies only to Prism Launcher or does it apply to all Prism Launcher forks? It might be desirable to document this somewhere so that any fork maintainers will be aware of what legal responsibilities they have with regards to CurseForge, as well as a possible legal defense if CurseForge decides to act against a fork due to this.

To every launcher using the API. But forks have to change key anyways

**Comment by YukariWaffle** [comment]
> To every launcher using the API.

Thank you again for the response. Could the interaction with CurseForge that established this be published somewhere for the reasons that I described in my last comment?

**Comment by DioEgizio** [comment]
https://discord.gg/Q4bB5zE75f this is the most near your can get ig
