### ISSUE TITLE
Launcher crash when [Yes Steve Model] mod installed

### ISSUE THREAD

**Issue by dolooXu** [PrismLauncher/PrismLauncher#2632]
### Version of Prism Launcher

Prism launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

When only [Yes Steve model]  and its dependencies are enabled. Launcher fail to launch the game with the following error message [https://mclo.gs/pT7RObc]. The mod however is launch-able with official launcher. 

### Steps to reproduce

my spec: M3 chip Mac. Minecraft version 1.21. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
did you read the error: `org.apache.commons.lang3.NotImplementedException: Mac OS X is not supported`?
Most probably the java you selected in prism has a different version than the one Mojang uses in the official launcher.
This is not a Prismlauncher issue.
