### ISSUE TITLE
Alpha 1.2.6 fails to download.

### ISSUE THREAD

**Issue by CharlotteCross1998** [PrismLauncher/PrismLauncher#2634]
### Operating System

Linux

### Version of Prism Launcher

8.4

### Version of Qt

5.15.14

### Description of bug

Failed to add READ_ME_I_AM_VERY_IMPORTANT
Failed to add pack.mcmeta
java.io.FileNotFoundException: http://s3.amazonaws.com/MinecraftResources/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1898)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
	at java.net.URL.openStream(URL.java:1093)
	at bn.run(SourceFile:28)
Process was killed by user.

### Steps to reproduce

Attempt to download alpha 1.2.6

### Suspected cause

The bucket is down.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
it works for me .
If the files are no longer accessible then this can't be fixed by the launcher

**Comment by CharlotteCross1998** [comment]
> it works for me . If the files are no longer accessible then this can't be fixed by the launcher

Tried it again and it works, though still gives the above error? I guess sometimes it doesn't launch and sometimes it does.
