### ISSUE TITLE
Even I change the langauge of the launcher, it still use -duser.langauge=en of Java 

### ISSUE THREAD

**Issue by Tsaitou7361** [PrismLauncher/PrismLauncher#2637]
### Role

Playing Minecraft with Fabric, but forgot to install dependencies

### Suggestion

Auto detect App language and change the value of -duser.language and -duser.country

### Benefit

Those people who wanted to play mods but don't understand English can even understand it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://github.com/user-attachments/assets/0b8c8965-33cd-4097-b951-ed8412f44a59)

**Comment by Kationor** [comment]
That option was added over a decade ago (91faaa5) to fix logging with different system locales. It shouldn't, and from my limited testing doesn't, affect the game in any way.

That being said, I tried running older versions with the option unset or set to `de`, and I couldn't find any logging issues. Doesn't mean there aren't any, I just couldn't find them.
