### ISSUE TITLE
Prism Launcher Flatpak - "Couldn't load the instance profile"

### ISSUE THREAD

**Issue by emmaexe** [PrismLauncher/PrismLauncher#2641]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4 - Flatpak version

### Version of Qt

Qt 6.7.2

### Description of bug

The Flatpak version of Prism Launcher can no longer launch the game, create new instances, etc.
This is caused by it not being able to save data to some files:
* `~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/<instancename>/mmc-pack.json` (`Couldn't save "/home/e/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.19_SMP_fabric/mmc-pack.json" because: "Unknown error"`)
* `/home/e/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/accounts.json` (`Failed to save accounts to "accounts.json"`)
* `An access error occurred (e.g. trying to write to a read-only file).`

Some screenshots (not mine, from the thread on discord discussing this bug):

![image](https://github.com/user-attachments/assets/0f013bcf-1d29-4aba-8f5c-1d4db776f6bc)

![image](https://github.com/user-attachments/assets/87a6e933-9a13-41f3-a016-eaf917d0a2b9)

![image](https://github.com/user-attachments/assets/e2765e74-6a7b-4952-befa-5e01e00855bd)

### Steps to reproduce

* Ensure you have the latest version of apparmor with `/etc/apparmor.d/bwrap-userns-restrict` installed
* Open Prism Launcher
* Try any of the following:
  * Create a new instance
  * Launch the game
  * Add an account
  * … (there are probably more ways to reproduce)

### Suspected cause

This definitely affects all ubuntu-based distros. Recently, apparmor was updated and with it a new profile was added - "bwrap-userns-restrict". This profile applies restrictions to bwrap in a way that can break some flatpak apps. This includes the Prism Launcher Flatpak. I have not tested any other distros.

Relevant apparmor issue: https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2072811

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by emmaexe** [comment]
I have confirmed a workaround that allows the flatpak to function normally.

Run the following command:
```sudo ln -s /etc/apparmor.d/bwrap-userns-restrict /etc/apparmor.d/disable```

This will disable the recently added `bwrap-userns-restrict` apparmor profile and after a reboot bwrap, and by extent flatpak apps and Prism Launcher, will no longer be confined by apparmor. This fixes the issues of the flatpak being unable to write to its files.

**Comment by TacticalLaptopBag** [comment]
Having the same issue since yesterday, also using the flatpak. I temporarily fixed it by manually selecting my instance, mods, and icons folders in settings, but that doesn't seem to work anymore :/
I downgraded to 8.2, allowed access to all files on my system, and made sure my instance, mods, and icons folders were in Flatseal. None of these worked. 



> I have confirmed a workaround that allows the flatpak to function normally.
> 
> Run the following command: `sudo ln -s /etc/apparmor.d/bwrap-userns-restrict /etc/apparmor.d/disable`

This also didn't work for me. I noted that `/etc/apparmor.d/disable` already existed on my machine as an empty directory. Running the command without removing it didn't work, and running it with the directory removed didn't work either...

Gonna try AppImage or tar distribution if AppImage also suffers the same fate

**Comment by emmaexe** [comment]
> Having the same issue since yesterday, also using the flatpak. I temporarily fixed it by manually selecting my instance, mods, and icons folders in settings, but that doesn't seem to work anymore :/
> I downgraded to 8.2, allowed access to all files on my system, and made sure my instance, mods, and icons folders were in Flatseal. None of these worked. 
> 
> 
> 
> > I have confirmed a workaround that allows the flatpak to function normally.
> > 
> > Run the following command: `sudo ln -s /etc/apparmor.d/bwrap-userns-restrict /etc/apparmor.d/disable`
> 
> This also didn't work for me. I noted that `/etc/apparmor.d/disable` already existed on my machine as an empty directory. Running the command without removing it didn't work, and running it with the directory removed didn't work either...
> 
> Gonna try AppImage or tar distribution if AppImage also suffers the same fate

Disable is supposed to exist on every machine using apparmor, its a directory with links to disabled apparmor profiles. Did you ensure that /etc/apparmor.d/bwrap-userns-restrict exists? Also what distro are you on?

**Comment by katabame** [comment]
> Run the following command: `sudo ln -s /etc/apparmor.d/bwrap-userns-restrict /etc/apparmor.d/disable`

This worked for me on `Ubuntu 24.04 LTS`.
don't forget after command executes, reboot your system

**Comment by emmaexe** [comment]
A fix has been pushed to the ubuntu 24.04 apparmor package. Run an update to resolve the issue.
