### ISSUE TITLE
Add an option to change the default account per instance

### ISSUE THREAD

**Issue by Blayung** [PrismLauncher/PrismLauncher#2642]
### Role

I have a specific modded instance for playing on a non-premium server and I've recently changed my nick.

### Suggestion

I want prism launcher to have an option to make me always use my old nick in offline mode on that instance.

### Benefit

I don't need to restart minecraft after I've realized I launched it in premium mode.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
Already there: Edit>Settings>Miscellaneous>Override default account

**Comment by Blayung** [comment]
I guess I didn't look well enough :D
