### ISSUE TITLE
A Mod called "dark-matter" ???

### ISSUE THREAD

**Issue by Sparrow231129** [PrismLauncher/PrismLauncher#2647]
I have been rebuilding all my Instances since JAVA 17 vs. JAVA 21 and Neoforge ver. x.x.76 stopped running  and needed to be updated to ver. x.x.86 because it was quarreling with JAVA 21 (neither of which was your fault, but once the problems started happening, they began to cascade, so I wiped JAVA, Neoforge, Forge, Fabric, Minecraft, and PrismLauncher from my computer: first with System>Apps>[Uninstall], then with Norton Registry Cleanup, then with Powershell 7 search and destroy (manual wipe of left-over files), then with Norton Shredder. Then I reinstalled Minecraft, then PrismLauncher, then began rebuilding Instances.)

I am now solving inevitable crashes, collisions, finding incompatible mods and so forth.

One of my Mods is "Mod Menu", which is displaying a disturbing bit of information. All the mods listed during game play by Mod Menu have creation information, author credits, and links to mod webpages.... All that is, except for a mod called "Dark-Matter". No description, no links, no nothing. Furthermore, there is no "Dark-Matter*.*" file in the Mods folder for this Instance, no "dark-matter" text in any of the config files in the Config folder, and no information about something called "dark-matter" on Norton's virus and phishing news web pages.

I realize that this conversation should include (and be directed to) the "Mod Menu" mod team but accessing their github page was less than helpful and I neither have, nor want, a Discord account. I am hoping that this discovery of "dark-matter" showing up through PrismLaunchers' excellent tools and "Mod Menu"'s excellent job of finding a reference to "dark-matter" is as alarming to you good folks as it is to me.

Please get back to me with any comment, anything from "No comment" to "Talk to Mod Menu" to "We found nothing" to "We found something" to "WTF!" to "Action to take" will be appreciated.

**Comment by Trial97** [comment]
Be aware that some mods embed inside them other mods: for example more-red includes jumbo furnaces.
Why they do that I don't know. Also I don't know what mods add your dark-mater mod.
Closing this as is not related to the launcher.

**Comment by Kationor** [comment]
Adding a bit more detail:
[Dark Matter](https://modrinth.com/mod/dark-matter) ([GitHub](https://github.com/constellation-mc/dark-matter)) is a library mod that provides some utilities. If you want to figure out what mod(s) bundle Dark Matter, a good place to start would be to look at [other mods by the same author](https://modrinth.com/user/melontini/mods).
