### ISSUE TITLE
Screenshot upload can't be aborted

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#265]
### Operating System

Windows

### Version of Prism Launcher

5.0-develop

### Version of Qt

5.15.6

### Description of bug

In an instance's screenshots tab, you can press the "Upload" button to upload a screenshot to Imgur. However, there is no way to abort the upload once you have clicked this button.

### Steps to reproduce

Go to the screenshots tab

Select an existing screenshot and click "Upload" on the right sidebar

There won't be an abort button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by NotAlexNoyle** [comment]
This causes Prism to suspend when the screenshot it is attempting to upload is too large.
