### ISSUE TITLE
Add option for packs to use installed Java version in edit pack settings

### ISSUE THREAD

**Issue by Nerxxy** [PrismLauncher/PrismLauncher#2651]
### Role

General use, if i play a 1.12.2 pack it needs Java 8, or if i play a newer version pack, it might need Java 17

### Suggestion

Add an option in the options panel on the left saying "Java" so that it will use that version instead of having to change the Java version for all packs, if that makes sense

### Benefit

Dont need to keep on changing the Java version in general settings if i play a pack/MC version that requires a different Java version

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![prism example](https://github.com/user-attachments/assets/b3a56abe-0865-4096-8c4c-d5925f0c2842)

Essentially like this, i personally have a StoneBlock 2 instance and a Vanilla 1.24.4 instance, both of which use different Java Versions, if one day i decide to play both one after each other as a break from one another then it becomes tedious to have to keep changing the Path and Arguments, so having it like this and requiring the user to set it up there make it easier if u wanna just switch quickly to another pack/mc vanilla version.

i hope it all makes sense.

**Comment by maskersss** [comment]
is settings > java in that menu not what you're asking for

**Comment by Trial97** [comment]
This is already there: you can change the java settings per instance in the settings
