### ISSUE TITLE
Unable to authenticate user with Microsoft

### ISSUE THREAD

**Issue by trickjarrett** [PrismLauncher/PrismLauncher#2657]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

I am trying to authenticate a Microsoft account in Prism and after successfully logging in, Prism is unable to get tokens from the server.

### Steps to reproduce

I add a user, complete login in the browser, and after successfully logging in I am given an error screen as attached.

![Screenshot 2024-07-18 165628](https://github.com/user-attachments/assets/52494fc0-200c-4b8f-8982-25ceb3b07ad5)

The login is successful on Microsoft, I get an email notifying me of the login.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Shiver-J** [comment]
Having this same issue on the Linux Flatpak, the game refused to launch so I assumed my credentials had expired and refreshed my login only for it to give me another error.

**Comment by trickjarrett** [comment]
Upon further investigation, it may be an issue with Microsoft. I re-installed MultiMC to try and get it up and running but am finding that I also can't authorize the account there.
