### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ItzLoonie** [PrismLauncher/PrismLauncher#2659]
### Operating System

Windows 10

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

So I went to load up Minecraft and got hit with #2658, so I thought, ok, I'll remove and re-add my Microsoft account, and was hit with the following error:
![image](https://github.com/user-attachments/assets/ceb8d8fa-4b3a-461f-9cbe-a29cbd9ac170)
(Yes this is the whole error, server replies with nothing)

### Steps to reproduce

1. Manage Accounts
2. Add Microsft
3. Open linking website and paste code
4. Enter password
5. Continue with authorization
6. Error

### Suspected cause

I suspect the API is down, but idk.
This was working last night.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Kationor** [comment]
NAB, Microsoft's servers are down
https://support.xbox.com/xbox-live-status

**Comment by KujouShiori** [comment]
Yes, Microsoft blew up :(

**Comment by Ryex** [comment]
Main microsoft auth server are down.
