### ISSUE TITLE
I cant upload my skin

### ISSUE THREAD

**Issue by Calvinlovesnugget** [PrismLauncher/PrismLauncher#2664]
### Operating System

Windows

### Version of Prism Launcher

prism launcher 9.0

### Version of Qt

Qt 5/6

### Description of bug

it always shows an error when i try to upload my skin 
![2024_07_12_classic-enderman-in-a-suit--revamped--22686776 (1)](https://github.com/user-attachments/assets/5a19e3a3-92a1-4276-9ad4-e84859c5eee1)
this is the skin 

### Steps to reproduce

it doesnt works

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Calvinlovesnugget** [comment]
Please help developers

**Comment by Trial97** [comment]
Try again then right after upload prism logs.
The logs can be found:
  - name: Portable (Windows / Linux)
    value: '`./logs/PrismLauncher-0.log` In the PrismLauncher folder'
  - name: Windows
    value: '`%APPDATA%/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Scoop
    value: '`%HOMEPATH%\scoop\persist\prismlauncher\logs\PrismLauncher-0.log`'
