### ISSUE TITLE
Instance Version Java Version Swapping

### ISSUE THREAD

**Issue by ThePansmith** [PrismLauncher/PrismLauncher#2665]
### Role

General QoL for people that play a variety of versions

### Suggestion

Allow a user to tell prism to use a specific version of java when initally installing/building a pack

### Benefit

Streamlines the experience of installing/building modpacks a little more

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Little mockup of what it could look like. 
![asdasd](https://github.com/user-attachments/assets/53fc984f-ed4d-4b90-b591-a1e4003f4cac)

**Comment by Samalando** [comment]
There is already a feature in the works for auto switching and having Java be installed with prism so that would not be needed

**Comment by ThePansmith** [comment]
Ah, good to hear.
