### ISSUE TITLE
when i try to open prism luncher it shows me a labymod that says oops minecraft crached

### ISSUE THREAD

**Issue by zuchos123** [PrismLauncher/PrismLauncher#2671]
### Version of Prism Launcher

C:/Program Files/Eclipse Adoptium/jre-8.0.412.8-hotspot/bin/javaw.exe

### Version of Qt

i dont know

### Description of bug

my minecraft craches when i try to open it

### Steps to reproduce

-

### Suspected cause

i dont know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
We do not ofer support for labymod

**Comment by Aces-and-Jacks** [comment]
Labymod 3 I think works but labymod 4 isn't supported on prism launcher. Labymod isn't supported by prism launcher devs, nor does labymod devs support prism launcher. Labymod 3 just happened to work, at least from the last time I used it. 

Gonna have to use multmc if you want to play labymod on a third party launcher
