### ISSUE TITLE
Ability duplicate instances

### ISSUE THREAD

**Issue by agedplato** [PrismLauncher/PrismLauncher#2674]
### Role

Management of many different modpacks.

### Suggestion

A faster way to duplicate an instance, I.E. a button.

### Benefit

I find myself often neeeding to have a duplicate version of an instance and hate exporting a pack just to dupe it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Currently as far as I have been able to tell there is no way to duplicate an instance of Minecraft other than exporting and re-importing a pack or duping it in file explorer. (which has its own caveats. i.e. folder name mismatching)
I suggest an addition to the right click menu that basically runs through the import process for a pack duplicating the pack in the process.

**Comment by Trial97** [comment]
Right-click instance>Copy
