### ISSUE TITLE
Allow grouping/categorizing  of mods

### ISSUE THREAD

**Issue by n0proxy** [PrismLauncher/PrismLauncher#2679]
### Role

I play modded minecraft with a LOT of mods and find browsing through the whole list tedious

### Suggestion

I would like my list of currently-installed mods to have groups/subfolders/categories that will cluster them together on the list

### Benefit

I would love to be able to hide/minimize groups of mods. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I do a lot of 'disable this whole group of mods, run game, come back and enable that group, disable another group of mods' etc in troubleshooting my mods, and 'oh the modpack updated and includes X mod now that it's updated, did I install a temp replacement for X that I should now find and disable?'. I really wish I had a way to organize the modlist into categories/groups/subfolders and then minimize/expand groups as needed to look only at one type/group of mods at a time.

I'm not sure my wording makes sense so here's an example (cropped image of device manager). 
![Capture](https://github.com/user-attachments/assets/d43f9a48-45e5-4b86-8ab9-4d1b5f137e99)

Most of the groups/categories are 'minimized' in the image, but the Keyboards 'group' and Monitors 'group' are expanded so you can see the individual things (mods) inside. Ideally, moving mods into a group or from one group to another would be as simple as dragging them into it, and each group would also have a global checkbox for 'enable/disable all mods in this group'.

**Comment by Trial97** [comment]
Already suggested
