### ISSUE TITLE
Other language support to searching mods

### ISSUE THREAD

**Issue by xiaoliziawa** [PrismLauncher/PrismLauncher#2680]
### Role

Download minecraft mods

### Suggestion

Please support other language to searching mods not English only

### Benefit

If you can't remember the English name of a mod, you can search for the description of the mod in the local language

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Add more language mod searches for Prism to facilitate better mod searches for players

**Comment by Trial97** [comment]
Well this is not possible: the search is done via the curseforge/modrinth API so Prism can't change that
