### ISSUE TITLE
Allow Import from Google Drive

### ISSUE THREAD

**Issue by Cyranos** [PrismLauncher/PrismLauncher#2682]
### Role

I play modded mc as well make custom packs a lot for my friends

### Suggestion

As per title, I was hoping it would be possible to allow me to send my friends a google drive link and they were able to use that in the import section to import the pack

### Benefit

So that it makes it easier on my friends so they don't need to download & then delete the zip everytime I make a pack.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
Use packwiz

**Comment by Cyranos** [comment]
I have checked packwiz, it does not do what I am asking, it does it in a round about sense, but I don't want my friends to have to add the argument & as well download yet more things to even be able make it work. It's so much more setup for friends who are not as tech savvy.

**Comment by Trial97** [comment]
you can set those arguments yourself and include packwiz executable inside the exported instance.
If you export as prismlauncher all settings are retained.
The other solution would be to publish the pack to modrinth or curseforge.
