### ISSUE TITLE
Verify Dependants Button

### ISSUE THREAD

**Issue by Kevin-Marsh** [PrismLauncher/PrismLauncher#2686]
### Role

I develop modpacks

### Suggestion

A button similar to verify dependencies that verifies dependents.

### Benefit

Installing a mod in a modpack that pulls down a dependency and eventually removing the mod may leave the library orphaned in the pack. A button that highlights all mods with uninstalled dependents would help to identify orphaned libraries. It would be sufficient for it to not output anything as long as it matches at least one dependent to ensure the mod isn't orphaned.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
The identification of what mods depends on what is already suggested.
And if you want a button to delete the mods that do not depend on anything, that will not be added as we have 0 way to determine if it is a lib or an actual mod.
