### ISSUE TITLE
support for exporting to Modrinth modpacks

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#269]
### Role

I manage a modpack.

### Suggestion

I want it to be possible to export instances into .mrpack or a curseforge .zip for that matter.

### Benefit

so I don't have to have a separate packwiz folder on my desktop for building the modpack.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by LuciusofLegend** [comment]
I was about to make an issue about this myself.  This is a must-have feature IMO.

**Comment by ghost** [comment]
since packwiz is already integrated for the mod updater it would be easy to do simular for modpack export

**Comment by intergrav** [comment]
Highly agree! My use case here: while I probably wouldn't use this myself for _making_ modpacks, it would be super helpful to be able to send a very small mrpack file that lets me share my mods with other people. Currently, exporting as zip makes a really big file that usually can't be sent through sites like Discord, so this would be a convenient feature for me and many others. 👍

**Comment by codefreak558** [comment]
What could possibly be done is that the export button becomes a dropdown similar to the launch button where by default it exports as Prism/MultiMC .zips and then in the drop down have 3 buttons each for .mrpack and curseforge .zip files. With this it could become easier to mange modpacks for curseforge for example as you wouldn't need to have the curseforge launcher installed

**Comment by Frontear** [comment]
Would also be nice to create Modrinth packs. iirc packwiz already supports it, so since we have packwiz we can add functionality relatively easily

**Comment by dwnsdp** [comment]
This is a must have

**Comment by HyperSoop** [comment]
https://twitter.com/modrinth/status/1622285182303715336 ??? prism bruh

**Comment by Cartrigger** [comment]
mrpack would be great, meaning that i dont have to use different software

**Comment by ghost** [comment]
why is this still not a thing, this post was made last year bro

**Comment by intergrav** [comment]
it's being worked on - please be patient :p

**Comment by ToasterUwU** [comment]
+1 I want this to be a thing, so i can export and import the instances on different PCs, different Operating systems, and still get really good performance. Currently i have lag issues when using the pack i exported on Linux and than used on Windows, and the same issue with the other way around. Even exporting on Ubuntu 22.10 and than importing on Ubuntu 23.04 (Same machine) leads to performance issues.

So having a "clean" way of importing, would be nice.

**Comment by TheKodeToad** [comment]
I don't know how well my mrpack exporting code works (it didn't seem to work well for kosma at all), but it's now been merged in to the `develop` branch meaning it should be available at some point :p

I don't think anyone's even begun work on CurseForge export

**Comment by ToasterUwU** [comment]
@TheKodeToad Hey, I just noticed that the Milestone 7.0 (which your PR was a part of) is done.
So what's the process here, does that mean 7.0 will be released as soon as someone with the permission has time to press the button? Or is there something that needs to be waited for first?

**Comment by Scrumplex** [comment]
We are currently in the process of getting 7.0 tested by some of our Discord members. We will probably release it today.

**Comment by ToasterUwU** [comment]
> We are currently in the process of getting 7.0 tested by some of our Discord members. We will probably release it today.

Wonderful, thanks

**Comment by TheKodeToad** [comment]
I changed the issue's title so this won't be open forever.
If anyone has additional requests please open another issue!
