### ISSUE TITLE
Cannot connect account, "Failed to get Minecraft access token: The bound address is already in use"

### ISSUE THREAD

**Issue by ShelkaBelka** [PrismLauncher/PrismLauncher#2698]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

QT 6.6.3

### Description of bug

I try to add a microsoft account, and after connecting to the microsoft account, it keeps saying, "Failed to get Minecraft access token: The bound address is already in use."

### Steps to reproduce

Open prism launcher, go into manage accounts, click the add Microsoft, add the microsoft account from the explorer page, and then the message comes.

### Suspected cause

It could maybe be because I had the account linked, but I unlinked it and it does say that there is no account associated with it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is not a prism issue: it is probably due to the current outrage.
also see https://github.com/PrismLauncher/PrismLauncher/issues/2302 for more fixes
