### ISSUE TITLE
Why did you make the icons oversimplified?

### ISSUE THREAD

**Issue by Blayung** [PrismLauncher/PrismLauncher#2699]
### Role

I play majkraft

### Suggestion

I want you to delete the oversimplified icons

### Benefit

So that you make the world a happier place

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Why do you contribute to this horror?

**Comment by Samalando** [comment]
You do know you can change the icon right?

**Comment by Blayung** [comment]
@Samalando I do.
