### ISSUE TITLE
Error when launching Forge (NeoForge) above 1.20.1 in Java 21

### ISSUE THREAD

**Issue by 3th-penguin06329** [PrismLauncher/PrismLauncher#2701]
### Operating System

Windows 10 Pro

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.3.0

### Description of bug

It's just like the name says.
No errors with Fabric, Quilt and vanilla
![ERROR](https://github.com/user-attachments/assets/a1c4bd89-47a6-4461-8633-fef740a796a2)

### Steps to reproduce

Unknown

### Suspected cause

Java 21 bugs?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This doesn't look like a prism issue(that dialog is a java thing: so either the game or neoforge displays that)

**Comment by Lilith-In-Starlight** [comment]
Happens with other minecraft versions too, so it is not a java 21 bug

**Comment by Ryex** [comment]
This is almost certainly not a Prism issue. But if your convinced it is, please upload both the Prism Logs and the Minecraft logs here.

**Comment by 3th-penguin06329** [comment]
Sorry, I reinstalled Java 21 and changed the path to "C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe" and that cured it. Sorry about that.
