### ISSUE TITLE
"One or more subtasks failed" while trying to import modpack instances

### ISSUE THREAD

**Issue by BowBoy1** [PrismLauncher/PrismLauncher#2704]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

[PrismLauncher-0.log](https://github.com/user-attachments/files/16488803/PrismLauncher-0.log)

Prism suddenly appears to be failing to install all mods into instances. Deleting all files relating to Prism after an uninstall and reinstalling Prism, reinstalling the C++ redistributables, and restarting computer do not work to fix the issue.

### Steps to reproduce

Not entirely sure how to reproduce. The problem occurred without any prior warning.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
![image](https://github.com/user-attachments/assets/ed4e7a0a-acd1-4e2b-8011-f174b3fa9202)
Your ISP may be blocking modtinth if the solution suggested in image doesn't work use a vpn
