### ISSUE TITLE
Cannot add a Microsoft account [regression]

### ISSUE THREAD

**Issue by edgars-cirulis** [PrismLauncher/PrismLauncher#2705]
### Operating System

Windows

### Version of Prism Launcher

GIT: https://github.com/PrismLauncher/PrismLauncher/commit/0308710211f88ac15f84b99c3cd2bad7788c553d

### Version of Qt

QT 6.7.2

### Description of bug

![image](https://github.com/user-attachments/assets/27b9a360-1c46-44e8-92f5-890c5507e2c9)

### Steps to reproduce

* Add a new Microsoft.

### Suspected cause

Regression introduced by this merge: https://github.com/PrismLauncher/PrismLauncher/commit/9d684dcb82e8a8a82e5f5a47419d61df77b2df95

I have tested with and without this merge.

With the merge: Broken.
Without the merge: Works.

### Without merge

![image](https://github.com/user-attachments/assets/f1a478b0-f595-455e-9831-843d21ea4f18)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Edgars-Cirulis** [comment]
Also here you can download and see yourself.

[With the merge](https://github.com/Edgars-Cirulis/PrismLauncher/releases/tag/9.0-d3ca8864)

[Without the merge](https://github.com/Edgars-Cirulis/PrismLauncher/releases/tag/9.0-ffc6a4f9)
