### ISSUE TITLE
The launcher is always launching in full-screen

### ISSUE THREAD

**Issue by BRW19** [PrismLauncher/PrismLauncher#2709]
### Version of Prism Launcher

one of the newest versions
![cafsfgs](https://github.com/user-attachments/assets/7e760cc2-dcc1-4f55-9dd4-cbd5adc4c595)

### Version of Qt

idk

### Description of bug

its annoying

### Steps to reproduce

idk what my friend did and he cant seem to replicate it or fix it.

### Suspected cause

probably my own stupidity, also have checked everywhere no one has had this problem or posted about it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is not a prism bug as prism doesn't offer any way to full-screen the app.
This is most probably an OS thing. And as I see you did not even complete that part:

> ### Operating System
> 
> _No response_
