### ISSUE TITLE
Neoforge modpacks not being recognized.   

### ISSUE THREAD

**Issue by InarticulateVerbosity** [PrismLauncher/PrismLauncher#2711]
### Operating System

Windows

### Version of Prism Launcher

Prism launcher 7.2

### Version of Qt

>The version of Qt used in the bug report. You can find it in Help -> About Prism Launcher -> About Qt.

no such location

### Description of bug

Prism doesn't recognize the Neoforge jar as a mod launcher. 

### Steps to reproduce

in prism download All-the-mods10 modpack. Launch modded game after install. Get vanilla minecraft. 

There is no way to add Neoforge to the install on Versions screen. 
Need an  "Add Neoforge" button exactly like the 'Install Forge' button or add Neoforge to the forge dropdown list. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Update to the latest version of prismlauncher https://prismlauncher.org/download/?from=button

**Comment by InarticulateVerbosity** [comment]
new bug; prism doesn't tell me that a new version is available in the info bar anymore 

apologies for wasting your time

**Comment by Trial97** [comment]
Update as maybe it is fixed(that bar tells the news and if you removed it then there are no news to see)

**Comment by InarticulateVerbosity** [comment]
Yep, Fixed the issue insofar as I was able to manually add the loader.
