### ISSUE TITLE
Prism Laucher won't start

### ISSUE THREAD

**Issue by BUBUSTEIN13** [PrismLauncher/PrismLauncher#2715]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.7.2

### Description of bug

After I updated the linux610-nvidia to 550.107.02 and reboot the system, the Prism Launcher won't start

### Steps to reproduce

Update all your packages (including your linux610-nvidia) and reboot the system, from start menu open Prism Launcher.

### Suspected cause

Incompatibility with the new driver

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by BUBUSTEIN13** [comment]
I have Manjaro Linux with X11. I downloaded the prismlauncher from the AUR.

**Comment by GaucovyAero** [comment]
yeah i had to downgrade `cmark` to 0.31.0-2 from 0.31.1-1

i guess if you have the same issue you can do this if you have the old file

```
sudo pacman -U /var/cache/pacman/pkg/cmark-0.31.0-2-x86_64.pkg.tar.zst
```

btw heres what prismlauncher is saying when it doesnt work
```
~ $ prismlauncher 
prismlauncher: error while loading shared libraries: libcmark.so.0.31.0: cannot open shared object file: No such file or directory
~ $ 
```

i dont think this issue is related to the nvidia driver but please delete my comment if it is

**Comment by BUBUSTEIN13** [comment]
you're right, the problem is with cmark. i had a lot of packages to update today (136) and i didn't see the cmark package

**Comment by Trial97** [comment]
Closing this as completed.
