### ISSUE TITLE
scale the cat with window size

### ISSUE THREAD

**Issue by jitterdev** [PrismLauncher/PrismLauncher#273]
### Role

I like cats.

### Suggestion

Scale the cat with the size of the window

### Benefit

So the cat will always be visible

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

As of right now the cat doesn't scale with the size of the window:
![image](https://user-images.githubusercontent.com/64605731/197406818-f3e8304b-1cdf-459f-9693-291ae9749562.png)

The cat should become smaller if it doesn't fit into the window, or become bigger to fill the space so there isn't just an empty void.
![image](https://user-images.githubusercontent.com/64605731/197406835-e825d3d4-7ab4-4c66-9fb0-d666e2beb5ee.png)

**Comment by jitterdev** [comment]
this can be integrated with #99

**Comment by ghost** [comment]
this would make it so cursed when scaling the cat up and so good when scaling the cat down

**Comment by jitterdev** [comment]
> this would make it so cursed when scaling the cat up and so good when scaling the cat down

well asssuming the aspect ratio of the image is locked it should be fine but if the cat just gets squished it would be cursed 💀

**Comment by LordMZTE** [comment]
I suggest that background cat should not get larger than normal, only smaller if the window is an insufficient catbox.
