### ISSUE TITLE
Prism Server Manager - Using Prism for managing self-hosted servers

### ISSUE THREAD

**Issue by sarpuser** [PrismLauncher/PrismLauncher#2747]
### Goal

Create a new app that serves up a web interface to manage self-hosted Minecraft servers, including Modrinth/Curseforge modpacks.

### Motivation

Prism launcher makes it very easy to download new modpacks, update them, and add/remove mods/saves/resource packs to them. This feature is not available on any of the self hosted minecraft server solutions.

The most popular option for self hosting minecraft servers right now is Crafty Controller. I will be focusing on contrasting with Crafty in this post, but all of the self hosted server solutions have the same problems. Crafty is an open source application that resides on a machine in your network and runs two services: a web server to manage MC server installations and the MC servers themselves. It allows you to create simple MC servers such as empty Fabric/Forge/Spigot, and Vanilla Servers. It does not however, have any sort of way to automatically set up modpack servers, or easily add/remove mods to existing ones.

The general flow of creating a modpack server is as follows:
 1. Download the server files zip from the modpack page
 2. unzip the files
 3. Run the provided bash script to start up the server for the first time. This first run of the server generates all the important files, **including the forge/fabric-server.jar.**
 4. Once the files are generated, stop the server by exiting out of the running shell script (the shell script is the server terminal and allows for commands to be sent)
 5. Create a new server instance on Crafty Controller and point it to the server executable (the jar file).

After the server is created and Crafty is pointed to the executable, it is possible to use Crafty to start/stop the server, view logs, send commands, and upload/delete/edit server files, such as config files, mods etc. While this is not a very difficult process, where Crafty fails, and where Prism excels, is the easy updating of the modpacks, and easily finding compatible mods.

Crafty does not have any way of keeping track of the metadata of modpacks (it does not hook into Modrinth/Curseforge in any way). This makes it extremely difficult to update server mods or modpacks without deleting the entire thing, downloading the newest server packs from the modpack website, using the shell script to again generate the required files, and re-set up the Crafty server, all the while trying to move over all the world data, player data, etc. without accidentally overwriting something.

I would like to propose a new Prism app that, like Crafty, resides on a local machine in your network, and serves up a web interface that allows you to create new Minecraft server instances. I think that given that MC servers are nothing more than simple jar files, Prism should be able to achieve this goal without very major modifications to the underlying code.

### Specification

This would need to be a new app, either command line based for people who want to run it as a Linux service, or graphical for those who want to run their minecraft servers on a Mac/Windows machine. For the command line version, the application should come bundled with a HTTTP/S web server to allow for remote server configuration (this could also be included in the graphical version but the people using the command line version are more likely to care about remote access). 

Either way, the server manager app needs to be able to do the following (either on the GUI or through the web interface):
 - Create/delete server instances
 - Browse Modrinth/CurseForge for modpacks (as in the Prism Launcher app)
 - Easily update modpacks (as in the Prism Launcher app)
 - Easily add/remove/disable mods/resource packs/saves (as in the Prism Launcher app)
 - View the server log (as in the Prism Launcher app) and send server commands
 - Easily upload/download files (such as config files)
 - Start/Stop/Restart servers
 - Auto/manual backup and restore the servers (this could be implemented at a later date but I would argue this is an important feature)

In addition, the following are nice-to-have features that are not necessarily required:
 - View current online player count and list
 - View server MOTD and icon
 - Ability to edit text files with a built in text editor (very useful for changing one line in a config)
 - Ability to add players to ops/whitelist/banlist graphically (without editing the corresponding text files)
 - Ability to configure server options (such as render distance, game difficulty, etc) graphically (without editing the corresponding text files)

### Drawbacks

 - This might split development resources between the 2 apps. Ideally, most of the underlying code could be reused and a server wrapper built on top.
 - It might be difficult to organize the repositories if both applications share code

### Unresolved Questions

 - I am not a CPP developer and was not able to look through/understand the Prism codebase. I do not know if it would be simple to port the features I mentioned above to work with servers.
 - I am not sure if Curseforge/Modrinth APIs can be used for servers, and if so, if they can be setup as easily as the local modpacks.

### Alternatives Considered

The only options for automatically setting up modpack servers (as far as I can tell) are the paid server providers. These look and feel very similar to Crafty but will update a modpack by deleting the required files, and installing the new ones. In all these cases, you are still provided with a screen where you select which files are deleted when updating a modpack. While the required files are pre-selected, it is very easy to accidentally delete something important like the world. These services also include the ability to browse modpacks, but not mods. They are also paid and do not offer any software for self hosting.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
Not in scope

**Comment by TayouVR** [comment]
yeahh, there are already tools for this out there, several.
I'm not active in the hosting scene so I'm not sure what their names are, but building *another one* just so its prism branded, not a good idea.
If you have a custom instance you can export it as mrpack or cf pack and load that into whatever server hosting system.
if its on curseforge or modrinth those web frontends often have a way to download the packs, otherwise you can always just use packwiz and dump the files in the right dir.

If you want a desktop app for this (like prism launcher), ATLauncher afaik can do server instances. its not a web app intended to run on a real server. its just so you can host one on your PC easily
