### ISSUE TITLE
Cursor is not scaled on Wayland

### ISSUE THREAD

**Issue by flexagoon** [PrismLauncher/PrismLauncher#275]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 5.15.6

### Description of bug

On a 4K screen, when using Wayland, the cursor is not scaled and is very tiny

### Steps to reproduce

- Use Wayland
- Use a 4k screen
- Launch Prism Launcher

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
try running prism in wayland (run with QT_QPA_PLATFORM=wayland)

**Comment by flexagoon** [comment]
@DioEgizio it is running in Wayland. When I disable Wayland access in Flatseal and force it to use X11, the issue does not happen.

**Comment by Scrumplex** [comment]
This might be an issue with your Qt platform theme. We do not control cursor size within our codebase

**Comment by michaelgosling** [comment]
running with `XCURSOR_SIZE=24` fixes it for me. Seems like an issue with QT and Wayland. If compositor doesn't set `XCURSOR_SIZE` it defaults to 32, and at least on GNOME Wayland `XCURSOR_SIZE` is unset by default.

**Comment by gander-code** [comment]
For anyone coming across this in the future: running with `XCURSOR_SIZE=24` fixes it for me. Seems like an issue with QT and Wayland. If compositor doesn't set `XCURSOR_SIZE` it defaults to 32, and at least on GNOME Wayland `XCURSOR_SIZE` is unset by default. You can substitute 24 for whatever your cursor size is (might have to experiment a bit) but that size matches my cursor on GNOME Wayland.

edit: On Manjaro I was able to put `XCURSOR_SIZE=24` in my `/etc/environment` file so its set globally now. I think that file works for most, if not all, linux distros.

**Comment by flexagoon** [comment]
@gander-code yes, that's how I solved it myself, I forgot to mention the solution here.

For anyone using the Flatpak version, the `XCURSOR_SIZE=24` option should be added in the "Variables" section of Prism Launcher in Flatseal
