### ISSUE TITLE
Latest version does not work on linux

### ISSUE THREAD

**Issue by EnderiumSmith** [PrismLauncher/PrismLauncher#2766]
### Operating System

Linux

### Version of Prism Launcher

8.4

### Version of Qt

Qt6.

### Description of bug

In the latest version networking is borked. Upon first start it will only show the default english version. Trying to add an account the progress will halt on the first step for 10 minutes before finally opening the microsoft on browser. It will never manage to log in past the first sync, probably timing out before actually sending the request. Trying to download a modpack, the thumbnail never loads and the download hangs similarly to the add account one, only sometimes actually succeding at downloading.

Downgrading to version 8.2 it works just fine. This happens even on a new install of the OS.

### Steps to reproduce

Install the latest version

### Suspected cause

This could possibly have something to do with Qt, as when prism got update by the software updater, some Qt library were missing and i had to install it manually, while prism 8.2 says its using Qt5

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Try reinstalling prism with all the libraries present, also make sure that the firewall is not blocking the requests.
 If it does work please provide prism logs. They should be located at:

  - name: Portable (Windows / Linux)
    value: '`./logs/PrismLauncher-0.log` In the PrismLauncher folder'
  - name: Windows
    value: '`%APPDATA%/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Scoop
    value: '`%HOMEPATH%\scoop\persist\prismlauncher\logs\PrismLauncher-0.log`'
  - name: macOS
    value: '`~/Library/Application Support/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Linux
    value: '`~/.local/share/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Flatpak
    value: '`~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/logs/PrismLauncher-0.log`'
---

Please send logs! The recommended site to upload your logs to is [mclo.gs](https://mclo.gs/).

**Comment by artiomvisc** [comment]
Can confirm Im having the same issues.

**Comment by artiomvisc** [comment]
Seems like proget.makedeb.org is down.

**Comment by ronking159** [comment]
It now seems to resolve itself by reinstalling.

**Comment by Trial97** [comment]
Closing this. If you still have the issue please provide the logs as mentioned
