### ISSUE TITLE
"Use system locales" setting does not work on Linux

### ISSUE THREAD

**Issue by Tiagoquix** [PrismLauncher/PrismLauncher#2767]
### Operating System

Linux

### Version of Prism Launcher

8.4

### Version of Qt

6.7.2

### Description of bug

"Use system locales" does not work on Linux.

Tested on the native version from Fedora Linux COPR.
Same thing was happened on the Flatpak version, but I have since switched to the native stable version.

### Steps to reproduce

- Use American English as the language.
- Enable "Use system locales" setting.
- See dates not following system formats.

### Suspected cause

I also noticed MangoHud having commas instead of dots; probably also related to ignoring system locale. Does not happen in any other game.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is not an issue with Prism: you(or the app you used) did not set the locales correctly on your linux distribution

**Comment by Tiagoquix** [comment]
I don't think my locales are not correctly configured.

When using `export` in the terminal, I can see the values of the env. vars. Prism is the only app that is not respecting those vars.

**Comment by Trial97** [comment]
We are using the standard C++ [std::locale](https://en.cppreference.com/w/cpp/locale/locale/name) to retrieve it and then pass that string directly to QLocale::setDefault.
So either the C++ standard function doesn't return the locale correctly or you do not have the locale configured correctly.

**Comment by Tiagoquix** [comment]
Tested with system-wide locales (matching user-wide locales) by using `/etc/locale.conf` and rebooting the PC. SDDM, for instance, is affected, but PrismLauncher is not.
