### ISSUE TITLE
"Use discrete GPU" should only display when more are detected

### ISSUE THREAD

**Issue by Tiagoquix** [PrismLauncher/PrismLauncher#2768]
### Role

N/A

### Suggestion

"Use discrete GPU" should only display when more are detected

### Benefit

N/A

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The option "Use discrete GPU" is shown even though I only have one GPU and it is the discrete one. I don't have integrated graphics.

This option should only be shown if more than one GPU is detected, and if the additional detected GPU is an iGPU.

Otherwise, the option should be greyed out and checked (so we don't cause confusion to users to why it's unchecked).

**Comment by Trial97** [comment]
This is not planned.

**Comment by Tiagoquix** [comment]
Why not?

**Comment by Trial97** [comment]
> Why not?

Too much complexity for too little to gain: is hard to get the number of GPUs and make it cross-platform(for all Linux distributions). If you are a linux user already you should know if you have more than one GPU(if you need that setting or not)
If there is a need for this(more users want this, or another maintainer wants it) it may be considered. Also, pull requests are accepted.
