### ISSUE TITLE
Icon theme is not respected on KDE Plasma

### ISSUE THREAD

**Issue by Tiagoquix** [PrismLauncher/PrismLauncher#2769]
### Operating System

Linux

### Version of Prism Launcher

8.4

### Version of Qt

6.7.2

### Description of bug

When using `Icons: Simple (Colored)` and `Widgets: System` with Breeze style and a custom icon pack, the custom icon pack is ignored.

In my case, I use [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme), and it's ignored.

### Steps to reproduce

1. Use Papirus icon theme.
2. Go to settings and try to change the download folder by clicking on the change folder button. You will notice the icon pack is not applied.

This is also not only true for folders icon etc., but also for buttons, since icon packs can also change them.

### Suspected cause

Some kind of sandbox Prism is creating or isn't looking for the correct variables from the host system.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Icons are not fetched from the system

**Comment by Tiagoquix** [comment]
Following other applications' standards, they would be, because Prism invokes the KDE file picker.

Can we transform this into a feature request then instead of a bug?

**Comment by Trial97** [comment]
> Can we transform this into a feature request then instead of a bug?

I don't think this is needed.
If any other maintainer does want this please feel free to reopen it.

**Comment by TheKodeToad** [comment]
The file picker should already be showing the correct icons... I am not sure why this is not already the case

**Comment by Tiagoquix** [comment]
@TheKodeToad Do you mean the system (user) icons?

**Comment by TheKodeToad** [comment]
Yes... even when it doesn't use the system file picker it still uses the system icons... on my machine™

**Comment by Janfel** [comment]
This is an actual bug. I’m using Plasma on Fedora and all icons not provided by PrismLauncher use the Adwaita (GNOME) theme instead of the system theme (Breeze). This is visible in the file picker and on the Help button on the settings page. No other Qt application on my system has this issue.

**Comment by TheKodeToad** [comment]
Well... when I said system icons I meant Adwaita icons which was correct in my case

![image](https://github.com/user-attachments/assets/3f353121-2d11-4118-a94e-81844c805ff5)

**Comment by TheKodeToad** [comment]
If I change the icons in GNOME tweak tool it doesn't seem to be doing anything
Fair enough

But we won't change the icons in the launcher itself - or at least I don't think we should since it would create inconsistency.

**Comment by TheKodeToad** [comment]
Although I'm sure I have seen the icons in KDE plasma

**Comment by Janfel** [comment]
> But we won't change the icons in the launcher itself - or at least I don't think we should since it would create inconsistency.

If you’re talking about changing the Prism Launcher icon theme (Simple, Flat, OSX) based on the system icon theme, then I generally agree with you. I do believe that switching between light-mode and dark-mode variants could be handled automatically, but choosing the theme should be left to the user.

> Although I'm sure I have seen the icons in KDE plasma.

You might have been using the Flatpak. In that case the file picker is provided by the system (KDE Plasma) through an XDG portal and is completely independent from the application.

**Comment by TheKodeToad** [comment]
I think we have a fix! Stay tuned for Prism 9.2 (which follows the usual law of: whenever a Prism version should be released, it will be released a lot later than that)

**Comment by Janfel** [comment]
I will, thanks for the incredibly quick response on this.
