### ISSUE TITLE
Add back support for Offline Mode without an account

### ISSUE THREAD

**Issue by code-irisnk** [PrismLauncher/PrismLauncher#277]
### Role

I own Minecraft, but I also playtest modpacks and for that I sometimes need two instances of it running with two different usernames.

### Suggestion

Before PrismLauncher was born, this fork of PolyMC was active, which added back account-less Offline Mode support: https://github.com/EvilToasterDBU/PolyMC-Offline

### Benefit

If Prism did this natively, without the need to setup a totally different fork of it, that'd save time to me and many other people. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ghost** [comment]
I don't think this could be added because it violates [Mojang's EULA](https://www.minecraft.net/en-us/eula).

Also see this issue on MultiMC https://github.com/MultiMC/Launcher/issues/1512

**Comment by MMK21Hub** [comment]
Isn't your use-case covered by Prism's ability to add more than one offline account?
