### ISSUE TITLE
Add light cat button icon

### ISSUE THREAD

**Issue by Tiagoquix** [PrismLauncher/PrismLauncher#2770]
### Role

N/A

### Suggestion

Add light cat button icon.

### Benefit

So that I can always see a cat when I want to.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

On KDE Plasma with Breeze theme, the black cat icon doesn't have good contrast and can be hard to see. Would be good to add a light variant of it.

![image](https://github.com/user-attachments/assets/aefe6b8a-b266-4536-821b-26a48ed56108)

**Comment by Trial97** [comment]
That is controlled by the icon theme: suggestion make your own icon theme
