### ISSUE TITLE
i cant run minecraft multiplayer

### ISSUE THREAD

**Issue by AmineGm73** [PrismLauncher/PrismLauncher#2778]
### Operating System

Linux

### Version of Prism Launcher

prism launcher 9.0

### Version of Qt

Qt version 6.2.4.

### Description of bug

when i run they told me the name i type the name then i got this error:
Le serveur a retourné l'erreur suivante :

Could not create profile

### Steps to reproduce

i press the cat i fond cat

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Due to missing information, I will let you know to check https://github.com/PrismLauncher/PrismLauncher/issues/2302 for possible issues with the login mechanism.

Also because of the same missing information I will close it.
