### ISSUE TITLE
Additional java provider

### ISSUE THREAD

**Issue by DemwE** [PrismLauncher/PrismLauncher#2780]
### Role

User

### Suggestion

I would like to add new provider for java BellSoft liberica

### Benefit

more available options for the user

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

BellSoft main page link - https://bell-sw.com/ 
BellSoft java downloads link - https://bell-sw.com/pages/downloads/

**Comment by Trial97** [comment]
Mo we will not add more java providers for the time being
