### ISSUE TITLE
Curseforge Custom Modpacks

### ISSUE THREAD

**Issue by Alyaqdhans** [PrismLauncher/PrismLauncher#2781]
### Operating System

Windows

### Version of Prism Launcher

8.4

### Version of Qt

6.6.3

### Description of bug

The custom made modpacks on Curseforge aren't showing up, and even when trying to use the link to import, it says this:
![image](https://github.com/user-attachments/assets/fc6c518a-0a85-4c7e-ad4c-06b53b9c8e02)

And yes if you are asking if I enabled third-party distribution, I did:
![image](https://github.com/user-attachments/assets/2c8429dd-17a7-4f8b-b696-bc5b8f57035f)

### Steps to reproduce

Example my modpack: https://www.curseforge.com/minecraft/modpacks/essenstials

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
well, the link is supposed to work with direct zip download links, not random Curseforge mods.
Also if you have trouble finding a project on curseforge modpack import page then just search after the project id like so: `#967517`.

**Comment by Alyaqdhans** [comment]
The searching trick worked, but what do you mean by direct zip download link? is it this? https://www.curseforge.com/minecraft/modpacks/essenstials/download/5691882
because it still says the same error.

**Comment by Trial97** [comment]
I mean this link: https://mediafilez.forgecdn.net/files/5691/882/EssentialsV7.1.zip

**Comment by Alyaqdhans** [comment]
How do you get that link format

**Comment by Trial97** [comment]
After I downloaded the zip in browser I right clicked the file (in the downloads) and selected copy download link
