### ISSUE TITLE
__imp_PlaySoundA

### ISSUE THREAD

**Issue by ILYAS128** [PrismLauncher/PrismLauncher#2786]
### Operating System

Windows in vs code

###Goal
make  Google Assistant

#include <stdio.h>
#include <windows.h>
#include <mmsystem.h>
int main()
{
    LPCTSTR SongFile="D:\\programme\\AI\\hello_ser_can_i_help_you.wav";
    PlaySound(SongFile,NULL,SND_NODEFAULT);
    return 0;
}

When I run, this message appears

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\BOUKHE~1\AppData\Local\Temp\ccVKWQyI.o:AI.c:(.text+0x2d): undefined reference to `__imp_PlaySoundA'

### Steps to reproduce

*

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by edgars-cirulis** [comment]
Did you link  winmm on your compiler environment?
