### ISSUE TITLE
NetworkAuth not found when building from source

### ISSUE THREAD

**Issue by danrybir** [PrismLauncher/PrismLauncher#2788]
### Operating System

Linux

### Version of Prism Launcher

Commit [828acef7e938800a693343a0bb51e5fcd7349680](https://github.com/PrismLauncher/PrismLauncher/commit/828acef7e938800a693343a0bb51e5fcd7349680)

### Version of Qt

6.4.2+dsfg-10

### Description of bug

Cloned the repository, ran the first command from wiki, got hit with this:
```
CMake Error at CMakeLists.txt:312 (find_package):
  Found package configuration file:

    /usr/lib/aarch64-linux-gnu/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find required Qt component "NetworkAuth".

  Expected Config file at
  "/usr/lib/aarch64-linux-gnu/cmake/Qt6NetworkAuth/Qt6NetworkAuthConfig.cmake"
  does NOT exist

  

  Configuring with --debug-find-pkg=Qt6NetworkAuth might reveal details why
  the package was not found.

  Configuring with -DQT_DEBUG_FIND_PACKAGE=ON will print the values of some
  of the path variables that find_package uses to try and find the package.
```
(both Qt 5 and Qt 6 don't work)

### Steps to reproduce

* `git close --recursive` this repo
* Run the first command from the [building instructions](https://prismlauncher.org/wiki/development/build-instructions/linux/)

### Suspected cause

Building on ARM64 (unsupported) architecture, though I highly doubt it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
Development builds now require QtNetworkAuth. as this is an un released change the documentation has not been updated . itstall the appropriate package.

**Comment by danrybir** [comment]
<details><summary>Old comment</summary>
<p>

Still get hit with a `-- Could NOT find Qt6NetworkAuth (missing: Qt6NetworkAuth_DIR)`.
`sudo apt install libqt6networkauth6` output:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libqt6networkauth6 is already the newest version (6.4.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

</p>
</details>

Nvm wrong package but I got a different error, that's progress

EDIT: for the future me, the package is qt6-networkauth-dev
