### ISSUE TITLE
Allow Multiple instances of the Prism Launcher itself to be run simultaneously

### ISSUE THREAD

**Issue by Justfines** [PrismLauncher/PrismLauncher#279]
### Role

I use Prism Launcher (on windows)

### Suggestion

Have an option that allows multiple instances *of the launcher itself* to be run simultaneously. 

### Benefit

Having this be an option would allow proper usage of running the same instance twice with seperate accounts, among other things.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This sort of behavior (multiple instances of the same program) is normally what happens (and is expected) when one tries to run an application on Windows (including but not limited to dolphin, cemu, pcsx2, firefox etc) multiple times, though some might have an option to prevent it. It is odd that it isnt allowed (even if there are issues), in any form. This behavior seems to be inherited from the MultiMC days, and I'm not sure why it was implemented this way.
	
This would also technically enhance the usability for testing (like shown in #277 )  with multiple offline mode instances without violating nor providing a way to violate the EULA.

**Comment by code-irisnk** [comment]
I'd love this!

**Comment by ghost** [comment]
Or they could just add the ability to run the same instance of Minecraft twice instead of having to run multiple instances of the same launcher

**Comment by ghost** [comment]
#250 tho

**Comment by Justfines** [comment]
#250 seems *similar* but this is pretty much the inverse of that request. They both are solutions to some of the same problems though. I'll leave it open for a bit longer, but I might just close it, since that does enough; though this solution would require less UI work to accommodate.

If you still think its too similar I'll definitely close this by tomorrow

**Comment by Justfines** [comment]
closing it in favor of #250 . Solves similar issues *use case* after all
