### ISSUE TITLE
Keeping track of how an instance is modified, what was modified, and for what purpose

### ISSUE THREAD

**Issue by LaTrissTitude** [PrismLauncher/PrismLauncher#2790]
### Role

I produce content using various sometimes experimental mods

### Suggestion

an 'History' tab with added / removed / updated mods, resource packs etc. + ideally, a way to add notes / labels to each mod, resource pack, etc

### Benefit

It would greatly help me keeping track of instance modifications, and their purpose :) 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by LaTrissTitude** [comment]
I can elaborate if needed :)

**Comment by Trial97** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/1661

Also in my opinion there are already better tools for this kind of stuff (git,packwiz).
If you just want the instance for yourself just use a git repo.

**Comment by LaTrissTitude** [comment]
the linked #1661 refers to a single mod update history though, not instance wide history, accross mods, resource packs and settings. 

Also, #1661 doesn't mention element-wise notes / labelling

**Comment by LaTrissTitude** [comment]
![image](https://github.com/user-attachments/assets/ca61991c-1bbe-47af-b297-282f2f923676)
To clarify : This is an example of element-wise labelling I could find on the vortex mod manager :)

**Comment by LaTrissTitude** [comment]
Also setting up git would be overkill; I don't need rollbacks nor snapshots, those already exist within prismlauncher. 
A simple instance-level change-tracking history filled up whenever an 'apply' impacts an instance would be enough for my needs
