### ISSUE TITLE
I opened the settings menu and minecraft crashed

### ISSUE THREAD

**Issue by nobhkybsh** [PrismLauncher/PrismLauncher#2792]
### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

I opened the settings menu and minecraft crashed
https://mclo.gs/HvX0QEe

### Steps to reproduce

I opened the settings menu and minecraft crashed

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by nobhkybsh** [comment]
Windows 10

**Comment by Trial97** [comment]
It's not a launcher issue. Please join the Prism Discord server at https://prismlauncher.org/discord, and maybe somebody knows how to help you there.
