### ISSUE TITLE
Hope to add server download function

### ISSUE THREAD

**Issue by jiahuli** [PrismLauncher/PrismLauncher#2794]
### Role

I play modded Minecraft.

### Suggestion

Hope to add download server functionality, such as one-click download of modpacks on curseforge. Or download the vanilla server (and provide a script to run it)

### Benefit

This function is not complicated and can provide more convenience for players

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
Duplicate of a issue that is still open
