### ISSUE TITLE
[Feature Request] A config browser, similar to Gale Mod Manager

### ISSUE THREAD

**Issue by Snooziepup** [PrismLauncher/PrismLauncher#2796]
### Role

Configuring various mods

### Suggestion

Include a menu in an instance to edit text-based config files in a convinient manner

### Benefit

Ease of use browsing and editing mod configs

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
Not gonna happen. Prism already has an open config folder button, and I'm sure we do not want to make prism a text editor.

**Comment by Trial97** [comment]
Also duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2094

**Comment by TheKodeToad** [comment]
> Not gonna happen. Prism already has an open config folder button, and I'm sure we do not want to make prism a text editor.

I think the idea is to display configs in a UI with sliders and text boxes etc.. But that's not really viable with any of the current mod loaders I don't think...

**Comment by TayouVR** [comment]
I like the idea, but unless all mods agree on a single config scheme this isn't viable.

right now there are like 15 different libraries for config handling in minecraft mods and some mods just doing their own things...
