### ISSUE TITLE
Resolution problem

### ISSUE THREAD

**Issue by JaC0bWeb** [PrismLauncher/PrismLauncher#2797]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

When I start Minecraft in different resolutions, it always makes the window, that corner of the screen is Minecraft and the other is just my desktop (btw the resolution is 1280x1024)

![image](https://github.com/user-attachments/assets/7a5b9f8c-b242-4f01-90be-1e05643911e5)

### Steps to reproduce

start Minecraft on 1.8 (idk if it works for you)

### Suspected cause

idk

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Not a launcher issue
