### ISSUE TITLE
modlist image and enabled column is too wide when window is not maximized; causes mod name tab to be too small

### ISSUE THREAD

**Issue by EnderMelody** [PrismLauncher/PrismLauncher#2801]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

QT 6.6.3

### Description of bug

when editing a modpack, the columns for both the enabled and image are unnecessarily wide which crowds out the other columns from being displayed properly. this is mainly a problem for the names column as that is probably the most important one to display. you can manually resize the columns, but the program seems to randomly reset the config for it and the default column widths are loaded again.

### Steps to reproduce

- create modpack and add mods
- edit the modpack and open the "mods" tab.

### Suspected cause

bad default config/ bad saving of config

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ZekeZDev** [comment]
![image](https://github.com/user-attachments/assets/fe036a9e-1b07-4a65-a260-2d0ea9ce9285)
I am assuming this is what you are meaning, I can agree the sizing is not ideal. I am not sure what the best way would be without cutting off the text at the top but this can likely be something to consider after 9.0.

**Comment by EnderMelody** [comment]
yes that is exactly what i mean. even just keeping the column width saved would be perfectly acceptable now as currently it resets every single time you close the window. i dont know what limit is currently making the columns default to this width but imo they should be only as wide as the image, and for the enabled column it should be as small as possible.

**Comment by EnderMelody** [comment]
dont know about the default column width but the width i set it too seems to be saving now since i updated so ill mark this as complete. thanks for the fix!
