### ISSUE TITLE
Option to compare instances

### ISSUE THREAD

**Issue by ShadowTech99001** [PrismLauncher/PrismLauncher#2802]
### Role

Troubleshooting

### Suggestion

I want to be able to compare two instances which will show me a list of the each of their mods side-by-side with like mods next to each other and the rest below .

### Benefit

Troubleshooting and figuring out differences between instances

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

None

**Comment by Trial97** [comment]
Use [meld](https://meldmerge.org/) on the instance folder.
If you want to just compare the mods then export them as text and then compare them with meld
