### ISSUE TITLE
unable to log in

### ISSUE THREAD

**Issue by nyxar77** [PrismLauncher/PrismLauncher#2804]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt version 6.7.1

### Description of bug

![Screenshot_20240913_000044](https://github.com/user-attachments/assets/fc26fbf6-dc77-4908-84da-b72681b7c9f1)

### Steps to reproduce

just log in :)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by squillwah** [comment]
I'm also having this issue on SteamOS, using the flatpak release of Prism 8.4.

**Comment by nyxar77** [comment]
I just checked their discord server everybody got the same issue too

**Comment by Ryex** [comment]
auth network issue
