### ISSUE TITLE
Add lunar client friendslist

### ISSUE THREAD

**Issue by marc-weber1** [PrismLauncher/PrismLauncher#2805]
### Role

I play multiplayer minecraft, with friends running friends-only lunar client hosted worlds

### Suggestion

The prism launcher should be able to send lunar client friend requests to other users, and potentially display a list of friends to check if the request was accepted

### Benefit

Currently, to use the prism client to join a friends-only lunar client world, you need to temporarily download the lunar client and add them, when this could be done 100% in prism

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Looks like prism uses an oauth client to login with microsoft, I could look into it with wireshark or electron debug tools and post more about the requests that it makes once I find more details

**Comment by marc-weber1** [comment]
ok this might be a lot harder than I thought, I snooped on the lunar client requests for a while and all i can tell is that maybe the client ID for microsoft oauth is 00000000402B5328 (and id is 290794?)

**Comment by ZekeZDev** [comment]
Hi, 

Unfortunately I don't think that this is something we would consider, It doesn't seem to be something lunar wants other clients/launchers doing. If you wish to use something similar to play with friends there are plenty of mods that function in a more open way and have similar functionality, such as:

- [World Host](https://modrinth.com/mod/world-host)
Provides a friends list system and joining players worlds without hosting a dedicated server, has option to output ip for vanilla clients.
- [e4mc](https://modrinth.com/mod/e4mc)
Replaces open to lan with open to friends and provides a ip to connect with.

*I'll be adding a multiplayer section on the prism wiki soon, just haven't got around to it yet.*

I would recommend using these instead, however if you wish to use lunar friend worlds, how you are currently doing it will likely have to be the only way we support.
