### ISSUE TITLE
opening instance "settings" page changes the version of java used to an incompatible version without any user input

### ISSUE THREAD

**Issue by theofficialgman** [PrismLauncher/PrismLauncher#2810]
### Operating System

Linux

### Version of Prism Launcher

Develop (latest at time of post)

### Version of Qt

5.15.2

### Description of bug

When launching an instance where the global version of java is not the version needed to run the version of minecraft, the text in the instance setting for java installation does not match the actual version of java that gets used for the first launch (as observed in the gamelog). Subsequent launches get attempted with the text seen on the settings page and thus fail (since its the wrong version).

### Steps to reproduce

1. Enable automatic java downloader
2. Install a version of java that is not appropriate for one version of minecraft
3. Select the global settings java the java from 2
4. Launch a version of minecraft where the version of java needed is not the one in the global settings
5. Observe java is automatically downloaded from online but the text in the "java installation" under instance settings does not match the version downloaded and used

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by theofficialgman** [comment]
6. After visiting the tab in step 5, the instance will no longer launch do to being automatically updated to the wrong version of java. No text was edited by the user, only the "Settings" tab under the instance was opened.

**Comment by theofficialgman** [comment]
edit: this issue occurs regardless of the "Auto-download Mojang Java" being enable or not. The issue lies with the "Autoetect Java version" I assume.

**Comment by Trial97** [comment]
Maybe I'm missing some steps: I did go from 1 to 5 but the game launched with the correct java and the settings changed.
Did you perhaps override the java in the instance settings before you tried to start the game?

**Comment by theofficialgman** [comment]
> Maybe I'm missing some steps: I did go from 1 to 5 but the game launched with the correct java and the settings changed.

thats correct. the game launches first time. Open the settings page on the instance and launch again. You will see the java version has changed to the "global version" and won't launch now. (ie: step 6)

**Comment by Trial97** [comment]
ok thanks for clarification

**Comment by theofficialgman** [comment]
https://github.com/user-attachments/assets/81f1159b-43b0-407e-ba0f-ff91c392a849

here is a video that shows the steps

**Comment by Trial97** [comment]
I already have a fix in working for this

**Comment by Trial97** [comment]
https://github.com/PrismLauncher/PrismLauncher/pull/2813
