### ISSUE TITLE
Auto detecting java doesn't show javas in prisms java folder for macOS

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#2814]
### Operating System

macOS

### Version of Prism Launcher

9.0

### Version of Qt

6.7.2

### Description of bug

After downloading java, when I auto detect it shows other locations but doesn't show prism's java menu

### Steps to reproduce

1. Download java
2. auto detect
3. doesn't appear

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Hit refresh

**Comment by Aces-and-Jacks** [comment]
Doesn't fix

**Comment by Aces-and-Jacks** [comment]
I closed and opened prism, hit refresh, still doesnt show

**Comment by Aces-and-Jacks** [comment]
It might be the path is wrong for macOS? 
<img width="681" alt="Screen Shot 2024-09-13 at 6 36 12 PM" src="https://github.com/user-attachments/assets/dc226acf-5962-44b7-a434-b35935c164d5">

**Comment by Aces-and-Jacks** [comment]
<img width="1081" alt="Screen Shot 2024-09-14 at 8 32 14 PM" src="https://github.com/user-attachments/assets/2cc0afec-2f78-4da4-a935-06303c3162bc">

There's also this

**Comment by Trial97** [comment]
@Aces-and-Jacks can you try this build: https://github.com/PrismLauncher/PrismLauncher/actions/runs/10888582649?pr=2820 and let me know if this fixes your issue

**Comment by Aces-and-Jacks** [comment]
It does
