### ISSUE TITLE
Unsupported download type browser for DNS Techpack 6.x from ATLauncher

### ISSUE THREAD

**Issue by bensuperpc** [PrismLauncher/PrismLauncher#282]
### Operating System

Windows, Linux

### Version of Prism Launcher

Prism Launcher 5.0 Portable

### Version of Qt

Qt 6.3.0

### Description of bug

Unable to download DNS techpack 6.6.x from ATLauncher

![Screenshot_20221024_081234](https://user-images.githubusercontent.com/28039927/197459984-76cabc69-f372-446d-8bc3-6f2018ca8ac9.png)

### Steps to reproduce

* Add new instance
* Go to ATLauncher
* Install DNS Techpack 6.x

### Suspected cause

Related :

- https://github.com/MultiMC/Launcher/pull/3314
- https://github.com/MultiMC/Launcher/issues/4374

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
yep this is a missing feature of our implementation of the ATLauncher modpack format
