### ISSUE TITLE
Skin Manager crashes launcher when any skin file name contains more than one "."

### ISSUE THREAD

**Issue by RivoDani** [PrismLauncher/PrismLauncher#2823]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.0-develop
Commit: ef768945873cd4b4f7b8fae2ef4516ef9de5f715

### Version of Qt

Qt 6.7.2

### Description of bug

When opening the skin manager the whole launcher crashes if there's any skin file with a "." in it's name. (excluding the file extension ".")

### Steps to reproduce

Add a .png file with a "." in the middle of it's name to the skin folder (example "skin1.8.png")
Try to open the skin manager
Whole launcher freezes and crashes and a index.json.<randomcharacters> file keeps being created and deleted in the skin folder

### Suspected cause

The launcher probably is trying to generate a new index.json but can't parse the files with more than the default one "." of the file extension, because before crashing the manager displays the file name until the first "." then cuts the rest of it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
can you provide prism logs and the skin or an image you can reproduce this?

**Comment by RivoDani** [comment]
Yup, here they are:
[PrismLauncher-1.log](https://paste.gg/p/anonymous/94225d840ee64c39a489a912f436f409)
[Skin 1.8-.png](https://github.com/user-attachments/assets/763a432a-6d4c-458a-8abb-bf912864b529)

**Comment by Trial97** [comment]
@RivoDani from the logs is either the writing of the index throwing an exception or the fact that the dialog tries to scale the skin but the pixmap is null.
As I'm yet able to reproduce this crash on my end can you test the following build:https://github.com/PrismLauncher/PrismLauncher/actions/runs/10881420557?pr=2825 (at the end of the page should be the artifacts for the PR)

**Comment by RivoDani** [comment]
The build you provided fixed the problem, it no longer crashes and shows the whole name. (at least until a limit, i guess that's how it's supposed to work)
Shall I close this issue or you'll close it when 9.0 releases officially?

**Comment by Ryex** [comment]
then the PR merges this issue will close automatically
