### ISSUE TITLE
Have a `Minecraft log` tab before the instance is launched too

### ISSUE THREAD

**Issue by maskersss** [PrismLauncher/PrismLauncher#2824]
### Role

I ask others to send logs.

### Suggestion

I want there to always be a Minecraft log tab,

### Benefit

so that people aren't confused why it isn't there.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

i don't know how much does it make sense to have some placeholder text before the instance is launched in the place of a log like "Launch the instance to get started" and/or if it makes sense to change Upload's behaviour, but i think just having this tab exist there would help with the confusion.
to elaborate, it's not uncommon for someone to ask for help with an issue and try to send a log after, for instance, restarting the launcher, and they often end up sending a random (possibility unrelated) log from Other logs instead

**Comment by Aces-and-Jacks** [comment]
<img width="142" alt="Screen Shot 2024-09-16 at 9 41 43 PM" src="https://github.com/user-attachments/assets/7762382a-1b85-46ec-8825-31b8d55e9dfd">

So not this?

**Comment by maskersss** [comment]
yes, "Minecraft log", not "Other logs"
