### ISSUE TITLE
RLCraft error 255

### ISSUE THREAD

**Issue by VovaplusEXP** [PrismLauncher/PrismLauncher#2835]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.4.2

### Description of bug

The error was found on the RLCraft build.
The loading of the world is completed, followed by an instant exit from it with a subsequent Minecraft crash.

Log: https://mclo.gs/chuy9CL

I will point out that this build used to work fine before, and I no longer remember at what point something broke.

### Steps to reproduce

- Start the RLCraft v2.9.3 build.
- Create any world.
- Try to enter the created world.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Not a launcher issue.
