### ISSUE TITLE
Custom Commands do not work

### ISSUE THREAD

**Issue by nathlrowe** [PrismLauncher/PrismLauncher#2836]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

Instance custom commands, such as pre-launch or wrapper commands, do not work. Windows 11.

### Steps to reproduce

1. Create new instance (I'm using old versions, specifically beta 1.8)
2. Set a custom command that you know for sure works, e.g. `dir`
3. Try to launch game

My output for the above:
```
Running Pre-Launch command: dir
The process failed to start.
Pre-Launch command failed with code 0.
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Kationor** [comment]
`dir` is a builtin in cmd and an alias in powershell, not an actual program prism can run.
To quote the [QProcess](https://doc.qt.io/qt-6/qprocess.html#finding-the-executable) documentation:
> QProcess does not support directly executing *[...]* Windows command interpreter built-in functions, such as cmd.exe's dir command *[...]*. To run those commands, one should explicitly execute the interpreter with suitable options. *[...]* For Windows, due to the non-standard way cmd.exe parses its command-line, use [setNativeArguments](https://doc.qt.io/qt-6/qprocess.html#setNativeArguments)() (for example, "/c dir d:").

**Comment by Trial97** [comment]
Close due to the above: ^^^
