### ISSUE TITLE
Updating modpack creates new folder

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#2841]
### Operating System

MacOS

### Version of Prism Launcher

9.0-develop (dc67807-Debug)

### Version of Qt

6.7.2

### Description of bug

When I update a modpack from prism launcher 8.4, it creates a new minecraft folder. 

<s>It also doesn't do #2583</s>  
I don't know what happened, I updated a modpack from 8.4, created a new folder along with everything else not being there. I renamed the minecraft folder a few times suspecting `.minecraft` and `minecraft`, however after testing other folders and returning it suddenly worked. I know a few times I had to relaunch prism for metadata to show...no clue. Prism log got lost in a bunch opening and closing

### Steps to reproduce

Download modpack from 8.4
update prism to 9.0 develop
update modpack
check files (new `Minecraft` folder and `.Minecraft` folder) 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment]
I know it was changed from `.Minecraft` to `Minecraft` in the 9.0 version. But it doesn't rename preexisting folders to that

**Comment by Trial97** [comment]
The only affected provider of this is Modrinth as only for them can we update the packs and previously used `.minecraft`
