### ISSUE TITLE
Automatically download compatible Java version for instance if the version is not found

### ISSUE THREAD

**Issue by SwordSt0ne** [PrismLauncher/PrismLauncher#2849]
### Role

I play modpacks very often.

### Suggestion

If a compatible Java version is not found upon launch of an instance, automatically delay the launch and download the compatible Java version before proceeding with the launch.

### Benefit

So that I don't need to worry about installing the correct version of Java.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Samalando** [comment]
9.0 will have automatic Java version switch and installation from within the launcher

**Comment by SwordSt0ne** [comment]
Ok, thank you.
