### ISSUE TITLE
Resourcepack Detection Issue

### ISSUE THREAD

**Issue by RecRivenVI** [PrismLauncher/PrismLauncher#2850]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher develop branch Build #4394 or Commit dc67807

### Version of Qt

Qt 6.7.2

### Description of bug

If some comments are added to the end of the pack.mcmeta file in the resourcepack, PrismLauncher will not be able to recognize this resource pack file normally and it will not be displayed in the resource pack list.

pack.mcmeta looks like this:
![image](https://github.com/user-attachments/assets/05e42a5e-e30e-4ecf-bcb3-6bd0f60985a9)
and result:
![image](https://github.com/user-attachments/assets/8b2068b7-9140-4ac7-809b-f340192a1ad5)

### Steps to reproduce

Download the SPBR resource pack from Modrinth and see if it appears in the resourcepack interface.

### Suspected cause

Maybe the resourcepack detection part is not flexible enough.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
I could not find any mentions of pack.mcmeta as anything other than a JSON file and JSON doesn't support comments.
If you can point towards a site that mentions the comments in that file we may consider it. Otherwise, this is a bug with the resource pack.

**Comment by RecRivenVI** [comment]
> I could not find any mentions of pack.mcmeta as anything other than a JSON file and JSON doesn't support comments.
> If you can point towards a site that mentions the comments in that file we may consider it. Otherwise, this is a bug with the resource pack.

Got it, I will inform the resourcepack author of this bug.

**Comment by RecRivenVI** [comment]
gonna fixed at #4331
