### ISSUE TITLE
Modpack not working

### ISSUE THREAD

**Issue by Kollensan** [PrismLauncher/PrismLauncher#2852]
### Operating System

Linux

### Version of Prism Launcher

Prism launcher 8.3

### Version of Qt

Qt version 5.15.10

### Description of bug

Not launching

### Steps to reproduce

install Cave Factory 

### Suspected cause

frame work mod for 1.16.5 not available and light overlay not available for 1.16.5

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Kollensan** [comment]
Older versions are being tested

**Comment by Trial97** [comment]
Not a issue with the launcher
