### ISSUE TITLE
Add Nexus Mods support

### ISSUE THREAD

**Issue by RubberSpring** [PrismLauncher/PrismLauncher#2854]
### Role

I play modded minecraft

### Suggestion

I want the mod explorer to to show a “Nexus Mods” tab

### Benefit

so that i can download Minecraft mods from Nexus Mods

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Nexus Mods hosts Minecraft mods, adding a “Nexus Mods” tab alongside the CurseForge and Modirinth tabs on the mod explorer window, there are many cool mods at Nexus Mods

**Comment by Kationor** [comment]
> there are many cool mods at Nexus Mods

Please show examples. The Minecraft section of the website has less than 400 "mods" (most of them are not actually mods) and most of the higher-quality entries I could find were re-uploads.

**Comment by Trial97** [comment]
I don't think is possible to do so:
>  NEVER share your personal API keys with any other user, or include it as part of your own software.

source: https://app.swaggerhub.com/apis-docs/NexusMods/nexus-mods_public_api_params_in_form_data/1.0#/

So even if we provide a browser for them, the users will need to request a personal API and that is not convenient at all

**Comment by blryface** [comment]
...Interesting mods
![image](https://github.com/user-attachments/assets/c4b2ea6b-a346-43c0-8134-ce726a7597f2)

**Comment by blryface** [comment]
other mods i see on the `?tab=popular+%28all+time%29` page mostly arent even mods

**Comment by Trial97** [comment]
Closing this for now if enough people want this we may open it again.
