### ISSUE TITLE
Non-standard packwiz properties

### ISSUE THREAD

**Issue by TheKodeToad** [PrismLauncher/PrismLauncher#2858]
Since https://github.com/PrismLauncher/PrismLauncher/pull/1728 we store `mcVersion` and `loaders`. This is not supported by https://packwiz.infra.link/reference/pack-format/mod-toml/ so we should add an `x-prismlauncher` prefix (and also use kebab-case) as done in #1588 for `x-prismlauncher-version-number`.

**Comment by TheKodeToad** [comment]
I don't think we need to keep support for the old prefixless properties as 9.0 is not out yet and it could cause problems if packwiz introduces a property with the same name but different value in the future (even if it seems unlikely).

**Comment by Trial97** [comment]
I have two reasons why we should not care:
- as packwiz doesn't use the why should even bother
- I don't even think we are compatible with the format itself: we have the files but don't think we can use them in an actual packwiz pack
- I do plan to refactor that part to store all the mod configs in one file: I can argue that opening and closing files is one of the reasons why we are so unstable on the mods tab (https://github.com/PrismLauncher/PrismLauncher/issues/2822)

Regardless is just a string change so whatever(you will get a PR in a few hours)
