### ISSUE TITLE
[Feature Request] Sub-Folder support within the "Instances" folder

### ISSUE THREAD

**Issue by ItzMarni** [PrismLauncher/PrismLauncher#2866]
### Role

For people who use a lot of different instances.

### Suggestion

For people who often access minecraft files but have a lot of instances like me, it gets kinda painful to manage. Having subfolders (more explained down below) would make this process a lot easier.

### Benefit

Makes it hell of a lot easier to manage instances

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This feature would be similar to the "groups" you can already create in the Prism Launcher interface itself, it would be nice for this to be possible within the actual instance folder as well like this:

```
instances/
    ├── beta/
    ├   └── beta instance 1
    │   └── beta instance 2
    ├── survival/
    ├   └── survival instance 2
    └── anarchy/
        └── anarchy instance 1
        └── anarchy instance 2
        └── anarchy instance 3
```

I have asked about this in the Discord as well and have received positive feedback about it:
https://discord.com/channels/1031648380885147709/1031648381514289175/1288489303415984170

**Comment by Trial97** [comment]
I will vote a no on this:
- I don't find it useful 
- we already have groups inside the app
- due to recursive search we need to do to identify them this would make the app more slow(and bring back more similar issues)
- on discord there was only one user (no so much as a feedback)
I'm tempted to close this but let's hear another maintenar opinion on this.

**Comment by ItzMarni** [comment]
> I will vote a no on this:
> 
>     * I don't find it useful
> 
>     * we already have groups inside the app
> 
>     * due to recursive search we need to do to identify them this would make the app more slow(and bring back more similar issues)
> 
>     * on discord there was only one user (no so much as a feedback)
>       I'm tempted to close this but let's hear another maintenar opinion on this.

While it is a niche feature, performance issues could easily be mitigated by making this a toggleble option I'm assuming

**Comment by Ryex** [comment]
I'm gonna say this is a bad idea. recursive directory walks are notoriously slow, and hiding that slowness behind a toggle doesn't help.

**Comment by Trial97** [comment]
Closing this
