### ISSUE TITLE
wayland connection breaks on chromeOS

### ISSUE THREAD

**Issue by lanxiangcai** [PrismLauncher/PrismLauncher#2868]
### Operating System

chromeOS

### Version of Prism Launcher

prism launcher 8.4  (flatpak)

### Version of Qt

don't know. probably is the latest, the bug won't let me view it.

### Description of bug

on chromeOS, the following error is placed when preforming basic functions, such as adding an account or adding mods to an instance.
`The Wayland connection broke. Did the Wayland compositor die?`
immediately after prism launcher closes.

p.s. i'm currently trying to use xpra to bypass this. however my limited programming and linux knowledge is not helping.

### Steps to reproduce

* borrow a chromebook
* open prism
* try to use the app

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
That is a qt issue not prism related: the framework doesn't like Wayland.
Use flatpak or appimage

**Comment by lanxiangcai** [comment]
> That is a qt issue not prism related: the framework doesn't like Wayland. Use flatpak or appimage

you clown
i said specifically "flatpak" in the "version of prism launcher* field

edit: sorry for being mean >.<

**Comment by Trial97** [comment]
Try: https://github.com/PrismLauncher/PrismLauncher/issues/2388#issuecomment-2294819865

**Comment by lanxiangcai** [comment]
> Try: [#2388 (comment)](https://github.com/PrismLauncher/PrismLauncher/issues/2388#issuecomment-2294819865)

thanks, this worked for me
but instead of disabling X11 i disabled wayland

**Comment by Trial97** [comment]
Closing this as resolved then.

**Comment by khalathur** [comment]
Using X11 does work, but many things such as the mod downloader and updater seemingly freeze the app

Using the portable version along with QT_QPA_PLATFORM=xcb seems to fix this
