### ISSUE TITLE
Forge version is outdated.

### ISSUE THREAD

**Issue by Shadowblitz16** [PrismLauncher/PrismLauncher#2872]
### Version of Prism Launcher

8.4

### Version of Qt

5.15.13

### Description of bug

![image](https://github.com/user-attachments/assets/eaba9410-d002-45a3-8aa1-a19aaf9e6b50)
![image](https://github.com/user-attachments/assets/153ff8d6-6263-4798-9441-28e17bcfaf2d)

### Steps to reproduce

Install prism launcher on ubuntu through this...
```
sudo apt install lsb-release # install if not installed
curl -q 'https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg 1> /dev/null
echo "deb [signed-by=/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg] https://proget.makedeb.org prebuilt-mpr $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/prebuilt-mpr.list
sudo apt update
sudo apt install prismlauncher
```

### Suspected cause

The list if just outdated. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by maskersss** [comment]
both screenshots show 52.0.16 as latest? wdym

**Comment by Shadowblitz16** [comment]
it was saying my version was for 1.20 and I was getting errors for  >= 1.20 and < 1.20.1 my bad.
