### ISSUE TITLE
Preserve search queries 

### ISSUE THREAD

**Issue by Samalando** [PrismLauncher/PrismLauncher#2873]
### Role

I play modded minecraft

### Suggestion

I want it where if I type a mod(pack) name into one download site, it also appears on the other.

### Benefit

It gets very tedious typing mod(pack) names over and over again trying to find it and this would be very good.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This is a post for discord user patoviinet as they don’t really know how to use the GitHub interface. This was also in 5.2 however I don’t know if this was a bug or became a deprecated feature

**Comment by Ryex** [comment]
@Trial97 didn't you fix this in dev last week?

**Comment by Trial97** [comment]
If you mean this: https://github.com/PrismLauncher/PrismLauncher/pull/2863 is only for resource download and is under https://github.com/PrismLauncher/PrismLauncher/issues/1925 
Regarding modpack search I want to look into https://github.com/PrismLauncher/PrismLauncher/issues/2105 first before making that change(the modpack equal search term is not yet an issue)

**Comment by Samalando** [comment]
Ah did not see #1925 and #2485

**Comment by Trial97** [comment]
prepared a fix for modpack here: https://github.com/PrismLauncher/PrismLauncher/pull/2874
