### ISSUE TITLE
Modpacks don't work.

### ISSUE THREAD

**Issue by Shadowblitz16** [PrismLauncher/PrismLauncher#2876]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4 Debian

### Version of Qt

5.15.13

### Description of bug

I can install mod packs but when I run the game there is no change.

### Steps to reproduce

- Download this... https://modrinth.com/modpack/create.ultimate
- Create a new Instance of minecraft 1.20.1
- Install forge (the star icon version)
- Make sure java is version 17
- Run game
- See there is no create button in the main menu
- GoTo mods list
- See there are no mods except for minecraft and forge

### Suspected cause

Idk 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Not a launcher issue

**Comment by Shadowblitz16** [comment]
@Trial97 this is a launcher issue because it doesn't export mods properly either

**Comment by Trial97** [comment]
The modpack you pointed out is not even a proper modrinth pack(even the modrinth app doesn't accept it) so this remains closed.

Also please do not expect me to understand what you mean about mods export stuff.

**Comment by Shadowblitz16** [comment]
@Trial97 I mean when I do Instance -> Export -> Prism Launcher Zip it doesn't work either.
In fact I have tried all four method and they don't work when adding them to the mods menu.
mrpack's can be clicked on and imported as an prism instance though.

**Comment by Trial97** [comment]
Steps to export:
Get a instance with mods
Right click on it
Export
(select type: Prism only works with prism launcher;Curseforge for curseforge website; Modrith for modrinth website)
 on the next dialog make sure you have checked the mods folder
then hit ok 
save it somewhere

PS. if the instance has no mods installed no mods will be exported
This should be the steps to export 
Are these the steps you take?
If no please describe them(as detailed as possible so I can reproduce it)
If yes, and still doesn't work please provide a screenshot of the export dialog(where you select what folders you export)
e.g.
![image](https://github.com/user-attachments/assets/ca5b448b-eeac-4b97-bdd4-307833cca67d)

Also please be aware that you complained that you were not able to install a pack in the initial comment and not about any export issue, so this issue will remain closed until there is a confirmation is a issue or just user error.

**Comment by Shadowblitz16** [comment]
@Trial97 the issue is modpacks cannot be imported though the mods folder only when I click on them in my file explorer.
I haven't tested with when I first create an instance if I can or not probably.

But again you can't import modpacks thought instance -> edit -> mods -> drag and drop.
This makes modpacks unable to be combined after testing them.

**Comment by Trial97** [comment]
That is not an issue modpacks can't be imported through the mods folder.
The only way to import/create a modpack is through the Add Instance dialog, where you can either create a custom instance(first page), import it from the file(second page), or directly from a provider(on the page marked with them).

**Comment by Shadowblitz16** [comment]
@Trial97 Then why is it allows with drag n drop?

Also when I export mods as a mrpack file I don't get the mods at all even though I chunk them in the export settings.
It just exports a list of them

Look!
![image](https://github.com/user-attachments/assets/26a241e4-bed6-4846-b7d6-04986bf7c08c)
![image](https://github.com/user-attachments/assets/7fed8c49-a10e-469a-bca5-d9bd3632e6c3)

Thats what I get when I export a mrpack file with mod checked.
Its not working.

And clearly this is not the intended usage because other people tell me diffrent in discord like they can do it just fine.

Btw ignore Shadowblitz16's Super Modpack.mrpack it's not relivent I basicly just renamed Shadowblitz16's Modpack.mrpack to be Shadowblitz16's Modpack.zip and extracted it

**Comment by Trial97** [comment]
Drag and drop functionality on mods page is to add individual mods.
Drag and drop functionality on instance view should open "Add instance dialog".
Do me a favor do a screen recording of:
- you open instance edit window(that you want to export)
- show mods view
- close it 
- right click on that instance 
- and export it(and use modrinth for starters as that is the one you mentioned)
- then open the exported file

PS. usually when you export to a format like mrpack/curse you will not get the mods in overrides folder that is because the platform recognizes the mod and instead of uploading large modpack (with all the jar) the format will just create an index(not the name of the file) file that contains a list of the exported mods.

**Comment by Shadowblitz16** [comment]
@Trial97 I can't find a screen recorder but if you message me on the prism discord I can screen share with you
Or you can give me more time to try to find a screen recorder program for my system

**Comment by Shadowblitz16** [comment]
@Trial97 https://imgur.com/J62IAGq

**Comment by Ryex** [comment]
Looks like it's working as intended to me.

**Comment by Trial97** [comment]
Works as intended
