### ISSUE TITLE
Make launcher use correct qt style for kde

### ISSUE THREAD

**Issue by Shadowblitz16** [PrismLauncher/PrismLauncher#2877]
### Role

I play modded minecraft

### Suggestion

I want the launcher to look native to my os

### Benefit

so my ocd doesn't drive me nuts.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This is how my os looks...
![image](https://github.com/user-attachments/assets/ee97a929-69ee-4774-bf54-9f6196ae713e)

This is how prism looks...
![image](https://github.com/user-attachments/assets/11d7d201-3171-46b0-bb10-138e303a74bf)

**Comment by Trial97** [comment]
Please ensure that the qt config files are correct for your qt version.
From your previous issues, I see that you use the qt5 version of Prism, and the KDE themes currently use qt6, so your inconsistency is bound to happen.
Also from my perspective, the themes look alike: except for some accents.

**Comment by TayouVR** [comment]
from the screenshots it looks like you are using plasma 6. Plasma 6 uses Qt6 and the breeze style and widgets are all updated to work with the new Qt version.

if you have the `prismlauncher-qt5` package from your package manager installed, uninstall it and switch to the `prismlauncher` package. 
The widgets you see in prismlauncher are the default Qt widget style; Fusion.

(reopen the issue if I'm wrong)

**Comment by Shadowblitz16** [comment]
@TayouVR 
```bash
shadowblitz16@shadowblitz16-desktop:/opt$ prismlauncher-qt5 --version
prismlauncher-qt5: command not found
shadowblitz16@shadowblitz16-desktop:/opt$ prismlauncher --version
PrismLauncher 8.4

```


Also...
![image](https://github.com/user-attachments/assets/0410196e-5c23-4f8e-be0c-b21c6241c8a2)

**Comment by Shadowblitz16** [comment]
> Please ensure that the qt config files are correct for your qt version. From your previous issues, I see that you use the qt5 version of Prism, and the KDE themes currently use qt6, so your inconsistency is bound to happen. Also from my perspective, the themes look alike: except for some accents.

Config files are fine other apps work fine.

**Comment by Shadowblitz16** [comment]
I fixed it by removing prismlauncher and installing prismlauncher-qt5

**Comment by TayouVR** [comment]
ah, the other way around, somehow the settings layout made me think its plasma 6
sry about that, but yeah, the qt5 version it is then.
