### ISSUE TITLE
Any line that has the keyword ERROR in it is printed in red.

### ISSUE THREAD

**Issue by Shadowblitz16** [PrismLauncher/PrismLauncher#2878]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

5.15.13

### Description of bug

If the log lines in Minecraft Log tab have they keyword  "Error" in it it is printed in red when it's actually a warning.

An example would be like this...
```
[19:12:41] [main/WARN]: Error loading class: io/vram/frex/base/renderer/context/render/EntityBlockRenderContext (java.lang.ClassNotFoundException: io/vram/frex/base/renderer/context/render/EntityBlockRenderContext)
```

while something like this is printed in yellow...
```
[19:12:41] [main/WARN]: Reference map 'supermartijn642configlib.mixins.refmap.json' for supermartijn642configlib.mixins.json could not be read. If this is a development environment you can ignore this message
```

### Steps to reproduce

Install a few mods your bound to get something that throws a warning with the word Error in it..

### Suspected cause

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
That is intended.
Right now Prism compares checks each line if it contains the "error" string coloring them appropriately.

**Comment by TheKodeToad** [comment]
This behaviour should probably be changed, should the log level in [main/WARN] not take precedence?

**Comment by Trial97** [comment]
I am pretty sure that we need to implement either: https://github.com/PrismLauncher/PrismLauncher/issues/453 or https://github.com/PrismLauncher/PrismLauncher/issues/745 for this to work so we can keep it as close in favor of the mentioned two

**Comment by Trial97** [comment]
But if you disagree please reopen this.
