### ISSUE TITLE
Copy/Paste from the log in Windows (10) replaces new line with garbage chars

### ISSUE THREAD

**Issue by MeeniMc** [PrismLauncher/PrismLauncher#288]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

This program uses Qt version 6.4.0.

### Description of bug

Log copy-pasted from the Log window is missing newlines and may have some garbage chars inserted in place of the newline chars. 

### Steps to reproduce

1. Open the Log for an instance
2. Select some text with the mouse
3. hit ctrl-c
4. open an editor (e.g., a github issue box)
5. hit ctrl-v
6. the text is missing newline chars and invalid chars may have been inserted instead. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by 678435021** [comment]
Works fine on linux

**Comment by ghost** [comment]
This is related to https://github.com/PrismLauncher/PrismLauncher/issues/278. This issue is only present for Qt 6.4.0

**Comment by MeeniMc** [comment]
Issue is resolved in release 5.2

**Comment by Xetaxheb** [comment]
Not resolved in 5.2... still has qt6.4.0 and it is using Paragraph Separator (PS) U+2029 instead of CRLF U+000D,U+000A

**Comment by MeeniMc** [comment]
You are right, this is indeed not fixed. I used the 'copy' button and that copies the text correctly (and thus I thought it was fixed), but using mouse selection and ctrl-c, ctrl-v still copies the wrong newlines.

**Comment by DioEgizio** [comment]
Qt 6.4.1 has a serious scaling issue so... I guess we'll have to wait 6.4.2

**Comment by MeeniMc** [comment]
What about using 6.2? It's LTS.

**Comment by DioEgizio** [comment]
Would probably have some more bugs and no dark titlebar by default on dark theme

**Comment by TayouVR** [comment]
6.4.2 will have a nicer way to do dark titlebar too, so if Qt manages to not break even more stuff we should switch to that when it releases.

**Comment by Xetaxheb** [comment]
or could do a kludge and replace U+2029 with U+000D,U+000A in the output, at least in the meantime
