### ISSUE TITLE
curse & modrinth search syncing.

### ISSUE THREAD

**Issue by averythepyro** [PrismLauncher/PrismLauncher#2884]
### Role

I play modded minecraft.

### Suggestion

i would like for the curseforge and modrinth search bars to sync.

### Benefit

So that i can use the search feature more efficiently

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

If i am looking for a mod and i type it into the search bar for curseforge, it doesnt show up, i often click the modrinth button to see if modrinth has it, when i click modrinth it resets the search bar. it would be easy to implement and you could even have a toggle setting.

**Comment by Trial97** [comment]
Is duplicate and already implemented
