### ISSUE TITLE
I can't register with Microsoft

### ISSUE THREAD

**Issue by timurkazack** [PrismLauncher/PrismLauncher#2889]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.7.1

### Description of bug

Ru:
Чтобы начать играть, мне пришлось зарегистрироваться в Microsoft, войти в свою учетную запись, и я получаю сообщение об ошибке "Не удалось выполнить проверку подлинности пользователя Microsoft".
En:
In order to start playing, I had to register with Microsoft, log into my account and I get the error "Microsoft user authentication failed."

### Steps to reproduce

Ru:
*Учетные записи
*Управление учетными записями...
*Войдите в систему через Microsoft
En:
*Accounts
*Account Management...
*Log in via Microsoft

### Suspected cause

Lags

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Duplicate.
See pined issues
