### ISSUE TITLE
Instance update failed?

### ISSUE THREAD

**Issue by jwols123** [PrismLauncher/PrismLauncher#2898]
### Version of Prism Launcher

8.4

### Version of Qt

Qt 6.6.3

### Description of bug

The instance crashed with the log saying at the bottom, "Instance update failed because: Component metadata update task failed while downloading from remote server:
One or more subtasks failed"
[Full Log](https://mclo.gs/gO9sA6P)

### Steps to reproduce

Use a exported modpack (I used a Modrinth export as I was transferring from it), upload it to your Prism launcher, click play.

### Suspected cause

I believe it's either the export file type, something that happened on Modrinth's end, or a corrupted mod/file.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jwols123** [comment]
SOLUTION FOUND:
It turns out the profiles I had exported were broken because of a Modrinth update. Since in the export file I exported EVERYTHING, the broken files were included in the export.
Fixed by going back to Modrinth and repairing the installation before exporting it again.

**Comment by Dfg-22** [comment]
Experiencing the same issue, but nothing anyone has suggested so far has helped, and I can't launch any instance, create a new instance or even launch the game on a different launcher. Logs: https://pastebin.com/xzkxnrRS password: U2GWj3qwYp

<img width="440" height="130" alt="Image" src="https://github.com/user-attachments/assets/3d5ac35f-97b5-4fdc-a673-444812b008c7" />

<img width="720" height="474" alt="Image" src="https://github.com/user-attachments/assets/b584c08a-fc7c-4285-9dc8-e8763fbb733f" />

**Comment by jwols123** [comment]
This issue was specifically based around broken files that were transferred from modrinth to prism. Did you move broken export files over?
This issue was specifically caused by modrinth updating, breaking the java versions for all my modpacks.
It was fixed by going into the modpack options on modrinth, selecting the redownload/fix or whatever it was, then re-exporting.

**Comment by Dfg-22** [comment]
It’s possible, but I can’t create a new vanilla instance on prism or other launchers, so I doubt it. I posted here because it’s the same error message.

**Comment by jwols123** [comment]
Different issue then though. I give you the best of luck.

**Comment by Dfg-22** [comment]
Thanks 😂
