### ISSUE TITLE
"Search for app in the store?" error when trying to launch

### ISSUE THREAD

**Issue by Ikethepro18** [PrismLauncher/PrismLauncher#2903]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.0 (Developer)

### Version of Qt

Can't open the app to find out

### Description of bug

When launching a clean installation of Prism 9.0 on a Windows Sandbox, a prompt appears telling me I need to install an app for this "task". Prism Launcher does not launch
![image](https://github.com/user-attachments/assets/c7e9ed8c-f0f0-4615-bd04-db629a17ddfd)

### Steps to reproduce

* Enable Windows Sandbox in Option Features
* Restart your computer and launch a Windows Sandbox
* Download and extract the 9.0 developer build
* Run `prismlauncher.exe`

### Suspected cause

I'm guessing there's some sort of obscure dependency that's not available in Windows Sandbox, as it is an incredibly barebones build

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ikethepro18** [comment]
Also thought it'd be appropriate to point out that 8.4 works perfectly fine and this issue does not occur

**Comment by marrrrrrme6** [comment]
vcredist2022 is required.
Have you installed it in your sandbox?

**Comment by Ikethepro18** [comment]
> vcredist2022 is required.
> Have you installed it in your sandbox?

Yes, VC Redist is installed

**Comment by marrrrrrme6** [comment]
Which Actions did you download this from?

**Comment by Ikethepro18** [comment]
> Which Actions did you download this from?

I'll just give the link because I'm not sure of the difference
`https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/10853924976/PrismLauncher-Windows-MSVC-Portable-ef76894-Debug.zip`

**Comment by marrrrrrme6** [comment]
Hmmm... Okay.
Then I'd like you to right click on the exe file, open the properties and show me what the security tab looks like.

**Comment by Ikethepro18** [comment]
The account has full permission to access and modify the file etc

**Comment by Ryex** [comment]
i'll reiterate my suggestion from discord. attempt to run the exe from a terminal running in the sandbox. and let's us know what output you get.

**Comment by Ikethepro18** [comment]
It works perfectly as expected, how peculiar

**Comment by Ryex** [comment]
> It works perfectly as expected, how peculiar

not a launcher issue.
your sandbox is broken.
