### ISSUE TITLE
Dangling file handle

### ISSUE THREAD

**Issue by cappyprime** [PrismLauncher/PrismLauncher#2915]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

When importing a mod from file, if aborted by the user prior to completion the file handle for the zip is left open indefinitely/ until reboot

### Steps to reproduce

- [ ] Download and install from prism launcher website
- [ ] install on Windows 11, version 23H2
- [ ] launch prism launcher
- [ ] add instance
- [ ] import from file
- [ ] choose file from local machine
        Specifically used Terra Firma Craft off github downloaded as zip
- [ ] abort import prior to completion
results in file being unable to be moved from source folder, held by prism launcher even post close

### Suspected cause

 Dangling file pointer and/or orphaned process

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
What format?(Prism, Modrinth, Curseforge, or all)

**Comment by Trial97** [comment]
Also can this be reproduced on nightly(there were some code changes on instance import)?
Where can I download unstable builds of Prism Launcher?
You can download unstable builds [here](https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop).

    :warning: Caution
    Unstable builds have more bugs and are therefore more likely to break! By using the latest commit you are using software which has not been properly tested. For this reason we recommend using Portable or AppImage builds, or least making a backup.

**Comment by cappyprime** [comment]
It would have been curse forge specifically.  Tried git source as well just
to see

**Comment by Trial97** [comment]
> Tried git source as well just to see

And I presume is still reproduced with nightly builds right?
