### ISSUE TITLE
An update of mrpack will completely overwrite the CONFIG.

### ISSUE THREAD

**Issue by hu-ja-ja** [PrismLauncher/PrismLauncher#2918]
### Operating System

Windows

### Version of Prism Launcher

[PrismLauncher-Windows-MinGW-w64-Portable-5685bc3-Debug](https://github.com/PrismLauncher/PrismLauncher/actions/runs/11312214295)
9.0-dev

### Version of Qt

Qt 6.7.2

### Description of bug

If a **config** from a previous modpack is not included in the new modpack, all previous configs will be removed.
This can be disastrous if accidentally UPDATED by a player who does not know how it works.
I think we should be able to choose which files we want to keep, but this is a tricky problem.

I thought this #2304 would be an improvement, but it was not.

### Before
![image](https://github.com/user-attachments/assets/ec7eb198-fb11-4834-b1ec-54af3d9953ac)

### After

**The file is empty**

![image](https://github.com/user-attachments/assets/71299686-d044-4e26-9dd4-923a73f6e3d2)

### Steps to reproduce

1, Import some older version of mrpack.
2, Update to the latest version of mrpack.

Using [Vulpeus Modpack](https://modrinth.com/modpack/vulpeus-modpack), this can be reproduced by doing [[MC1.17.1_v24.8.1](https://modrinth.com/modpack/vulpeus-modpack/version/MC1.17.1_v24.8.1)] -> [[MC1.18.2_v24.10.10.1](https://modrinth.com/modpack/vulpeus-modpack/version/MC1.18.2_v24.10.10.1)].

This test was done with the [Vulpeus Modpack](https://modrinth.com/modpack/vulpeus-modpack).
I am the author of this modpack and have tried to deal with this config being overwritten by not including the config file (specifically, using Configured Defaults and only including that file), but this produced worse results.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
If the modpack update doesn't contain the configs then is a issue with the modpack itself

**Comment by hu-ja-ja** [comment]
Should this issue have been erected in Suggestion...?
I don't think forcibly overwriting the config is a good move.

**Comment by Trial97** [comment]
All the other launcher do that so that is no.
As usually by updating you need the new configs(maybe the old ones break the game if present)
So for a normal user this decision should be taken by the modpack creator because by keeping the configs may break stuff.

**Comment by TheKodeToad** [comment]
> If the modpack update doesn't contain the configs then is a issue with the modpack itself

We currently clear all overrides on update regardless of change
