### ISSUE TITLE
Gray out 'Start Minecraft maximized' option for versions that don't support it

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#292]
### Role

I use Prism Launcher

### Suggestion

The 'Start Minecraft maximized' option seems to be broken on all Minecraft versions above 1.5.2 (see https://github.com/PrismLauncher/PrismLauncher/issues/181 and https://github.com/MultiMC/Launcher/issues/2770#issuecomment-515713767).

So it would make sense to just gray it out for all Minecraft versions above 1.5.2.

### Benefit

So that people won't be confused by it not working (like what happened here: https://github.com/PrismLauncher/PrismLauncher/issues/181).

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This is the option I'm talking about:

![image](https://user-images.githubusercontent.com/110736028/197589310-9b016da0-b9ab-4a28-b13e-72102e89b914.png)

**Comment by ghost** [comment]
please don't take control out of the hands of the user

**Comment by ghost** [comment]
> please don't take control out of the hands of the user

The option literally does not work so it won't change anything if it gets grayed out

**Comment by ghost** [comment]
> > please don't take control out of the hands of the user
> 
> The option literally does not work so it won't change anything if it gets grayed out

what is someone makes a mod to make it work? aha! the launcher is now bad for modding... etc...

**Comment by MMK21Hub** [comment]
In that case, there should probably at least be a message to say that modern Minecraft versions don't support that option. The current situation is very confusing - users expect options to do what their label says.

**Comment by TheKodeToad** [comment]
> > > please don't take control out of the hands of the user
> > 
> > 
> > The option literally does not work so it won't change anything if it gets grayed out
> 
> what is someone makes a mod to make it work? aha! the launcher is now bad for modding... etc...

Mods cannot detect the flag. Anyway, a better option would be to get it working if possible, but it doesn't look that realistic.

**Comment by ToothyDev** [comment]
Why would you make a mod for it to work instead of just setting it to fullscreen or pressing f11? What? Why overcomplicate so much

**Comment by MMK21Hub** [comment]
A solution to the modding "problem" would be to allow the input of custom arguments to give to the Client.jar, and then you can easily use any arbitrary CLI argument that any mod may add.

At the end of the day, the launcher expects the game to function more-or-less like the vanilla game. If a mod decides to redirect log files to another directory or do something else weird, you wouldn't expect the launcher to handle that.

**Comment by BloodyRain2k** [comment]
Why can't the launcher just wait for the game window to start showing up and tell the OS to maximize the window at that point?

**Comment by TheKodeToad** [comment]
> Why can't the launcher just wait for the game window to start showing up and tell the OS to maximize the window at that point?

That is a possible solution, just maybe a bit hacky.

**Comment by SkilledAlpaca** [comment]
I attempted [this](https://github.com/PrismLauncher/PrismLauncher/issues/181#issuecomment-1289310451) fix on Windows 10 with GT: New Horizons and I can get the window to scale properly but it still isn't opening "maximized." I understand this may not be something that can be fixed but thought I'd at least chime in with what I've done.

**Comment by BloodyRain2k** [comment]
> That is a possible solution, just maybe a bit hacky.

Hackier than creating an AutoHotKey script that watches for a Minecraft window appearing and maximizing it once?
Because that's my current "solution". It works, but it's kinda "meh" when the launcher could just do the same and not require additional effort from the user.
