### ISSUE TITLE
[Suggestion] Downgrade-ability

### ISSUE THREAD

**Issue by sayore** [PrismLauncher/PrismLauncher#2923]
### Role

Modpack building

### Suggestion

Enable me to downgrade a mod / multiple mods in the Mods List.

### Benefit

It makes it quicker to check for problems.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

There are 2 Parts to this:

Imagine updating all the mods by the update button.
You see the pack crashes, but doesn't really give any good logs to hint as to why.

Now, there is only one way to go about with this: either have a backup, or be smart enough to downgrade the right mods AND dependencies.

What would help in this case is two things: procedurally downgrade each mod, find the fitting match to the fitting fabric/forge/.. Version AND that doesn't crash.

This is extremely time-consuming.

So what i would love to see is: 
- A partial downgrade button. (Select mod(s) to downgrade to the Version the pack had before)
  - Maybe take a snapshot of versions, and make the mods be able to jump between them. Maybe even named snapshots.
- A button to downgrade to /any/ Version before.

Currently, only upstream is a possibility(no downgrade) - or - writing down all the mods you want to downgrade, their Version and redownload them from the store.

**Comment by Trial97** [comment]
Prism already has a button that allows you to change the version of a mod(in nightly)
