### ISSUE TITLE
[Suggestion] Auto check crashes

### ISSUE THREAD

**Issue by sayore** [PrismLauncher/PrismLauncher#2924]
### Role

Testing modpacks

### Suggestion

Enable each mod one after another, wait for minecraft to fully launch.

### Benefit

Checking for compatibility issues of mods in a modpack that gets updated.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The launcher could (semi)easily achieve being a mod pack checker by doing the following:

Sort mods by their dependencies into a dependency tree via the info in the jar.
(If there have been new ones added, sort them like this as well)

Start Minecraft and wait for the loading Screen in the logs, given a maximum timeout time.

#### Binary Tree method
Activate half the dependencies with their children, see if they work.
Activate the next half, see if they work.
If both work => test full build.
If any do not work => try eliminating by starting with half the dependencies and children in the fail group.

This should require about 2 to 10 restarts usually, and is really tiresome to do manually. 
(There is probably an even better way like pattern matched activation, or binary tree style activation)

#### Alternatively
Try activating each of the new mods one by one, if one fails do not load it again, repeat until all mods are active. 

#### Why?
Writing down all the information for this process by hand can be extremely tiresome, firstly.
Secondly, this can help the process of finding incompatibilities if it could be automated via cli.
Given this information could be saved, we would also be able to have Prism Launcher even check a database to request incompatibility information to modders extremely quickly even if the logs do not give information directly.

If there is a tool like this, and I'm missing it, redirect me there, I am really looking for a solution that doesn't involve checking 100 times manually 🥴

**Comment by Trial97** [comment]
This was already suggested. Close as duplicate

**Comment by sayore** [comment]
> This was already suggested. Close as duplicate

So it's not planned at all or is there an issue open?
Asking if i am going to try to make this myself if it isnt something you are planning to do. 
Also thanks for the quick responses :)

**Comment by Trial97** [comment]
This issue: https://github.com/PrismLauncher/PrismLauncher/issues/1924
