### ISSUE TITLE
windows scaling issue with catpack

### ISSUE THREAD

**Issue by diggingforce** [PrismLauncher/PrismLauncher#2925]
### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

version 6.6.3

### Description of bug

Windows Catpack shown blurry/pixelated if viewed at a higher windows scale than 100%.

### Steps to reproduce

Set windows display scale to 150% shows blurry catpack images. (CUSTOM IMAGES ONLY)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
That is an issue with your files: use higher resolution images. Both custom cats and default ones displayed the same.

**Comment by diggingforce** [comment]
> That is an issue with your files: use higher resolution images. Both custom cats and default ones displayed the same.

Not files, i tried everything, nothing fixed the pixelated images but the 100% scale on display.

My images are of highest res.

**Comment by Haskellered** [comment]
> That is an issue with your files: use higher resolution images. Both custom cats and default ones displayed the same.

This isn't an issue with images, this is an issue with the windows display scale. ~~I can't confirm is this is an issue on linux too right now.~~

This affects scaling on wayland kde plasma too, tested at 150% scale.

**Comment by diggingforce** [comment]
> > That is an issue with your files: use higher resolution images. Both custom cats and default ones displayed the same.
> 
> This isn't an issue with images, this is an issue with the windows display scale. ~I can't confirm is this is an issue on linux too right now.~
> 
> This affects scaling on wayland kde plasma too, tested at 150% scale.

Indeed, it is an issue with scaling but my laptop screen isn't big enough for 100% scale so it needs to be 150%, any way this can be fixed?

**Comment by diggingforce** [comment]
Fixed in 9.0

**Comment by Trial97** [comment]
Found the duplicate of it that was fixed in 9.0: https://github.com/PrismLauncher/PrismLauncher/issues/1816

**Comment by diggingforce** [comment]
> Found the duplicate of it that was fixed in 9.0: #1816

Yes, fixed in 9.0, Thank you.
