### ISSUE TITLE
Skins api not responding to HTTP requests making launcher hang for a minute

### ISSUE THREAD

**Issue by maxsupermanhd** [PrismLauncher/PrismLauncher#2928]
### Operating System

Windows, macOS, Linux, Other

### Version of Prism Launcher

8.4 Flatpak

### Version of Qt

Qt 6.7.3

### Description of bug

Unable to launch any instance, hangs on "Fetching the Minecraft profile"

Player head images are missing (defaults to grayscale one)

![image](https://github.com/user-attachments/assets/aea26611-7134-4f1b-80cc-e73aed757642)

### Steps to reproduce

Start launcher
Attempt to start an instance

### Suspected cause

For me recently skins API simply does not respond to HTTP requests rendering my bot fleet unable to fetch player head (skin) images. Fixed it by finding and replacing first `http://` with `https://` prior to executing request.

Servers and other locations however still provide non-https links.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Did you just change http://xboxlive.com to https://xboxlive.com ?
ore were more strings that you changed?
Or what did you change?

**Comment by maxsupermanhd** [comment]
> Or what did you change?

https://github.com/maxsupermanhd/BlockBridge/commit/a412beeb41e2bc6f2c943df6d3a66af57b96e42f

This fixed my issue
