### ISSUE TITLE
Prism Launcher does not check if it has regained internet access

### ISSUE THREAD

**Issue by SilverAndro** [PrismLauncher/PrismLauncher#293]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

If you start prism launcher without internet access, and then later re-gain internet access, prism launcher continues to assume its offline and will not recheck until restarted.

### Steps to reproduce

1. Turn off your internet
2. Start Prism Launcher
3. Note that Prism Launcher prompts for an offline name when launching an instance
4. Enable internet (and wait for it to connect)
5. Prism Launcher continues to assume it is offline when launching an instance

### Suspected cause

Best guess is the check is only done once on startup rather than each time required.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Apocalypsing** [comment]
I've experienced this same problem before back in the MultiMC and PolyMC days, specifically with Microsoft accounts under Windows 10. Connectivity checks seem fine under Linux though as I've never experienced the same issue there.

**Comment by ModProg** [comment]
> Connectivity checks seem fine under Linux though as I've never experienced the same issue there.

Actually I have the issue on Linux :D, not sure if it might be related to having it set up as autostart which results in it being started before the network is connected.

**Comment by TheKodeToad** [comment]
I get this even when I'm connected to the internet the whole time.

**Comment by JakeyPrime** [comment]
+1 to this, it lost internet randomly one time and now it continously thinks I'm offline, despite closing and reopening and force stopping (on W11). News won't load, accounts are "offline". Typing this from the same computer so I do have an active connection now.

**Comment by fernyjbh** [comment]
I had this after updating to 6.3, but after an uninstall and reinstall, the internet connection was detected again, in case that helps anything/anybody

**Comment by Madis0** [comment]
The interesting part is that even the Modrinth modpack update checker works after a while, but instance launching still asks what offline username I want.
