### ISSUE TITLE
Minecraft instance has no icon on GNOME 47 Wayland

### ISSUE THREAD

**Issue by 64-bitman** [PrismLauncher/PrismLauncher#2931]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4 from Terra 41 repos

### Version of Qt

Qt 6.7.2

### Description of bug

Running an instance of minecraft has no window/desktop icon, uses default system icon instead.

### Steps to reproduce

Open prism launcher
Run any instance

### Suspected cause

Seems like prism launcher creates a desktop file in ~/.local/share/applications, but the `Icon` key doesn't seem to work (I have verified that the icon `minecraft` exists on my system). Possibly because `Exec` is just the true command, and exits immediately, preventing the icon from showing?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by 64-bitman** [comment]
A hacky workaround I found is copying the desktop file that prism launcher creates when starting an instance, removing the Exec line and changing Hidden to false. Then make it read only so prism launcher can't delete it

**Comment by 64-bitman** [comment]
Turns out the desktop file creation was due to the WayFix mod, but even if it's disabled there still is no icon for the running instance anyways

**Comment by Trial97** [comment]
Not a launcher issue(the launcher doesn't set the icon of the mc process it's spawning)

**Comment by ReillyBrogan** [comment]
I've opened [a PR in the GLFW repo](https://github.com/glfw/glfw/pull/2811) to address this. That will allow Prism Launcher to set an environmental variable to propagate the Prism Launcher appId to the launched Minecraft windows which will allow for them to be correctly associated with Prism Launcher by the window manager.

**Comment by ReillyBrogan** [comment]
BTW here's it working after patching GLFW:

<img width="3214" height="1890" alt="Image" src="https://github.com/user-attachments/assets/6a7ce817-1955-4626-b29e-8280cfb0bae6" />
