### ISSUE TITLE
Linux unportable mode

### ISSUE THREAD

**Issue by mrmelon54** [PrismLauncher/PrismLauncher#2941]
### Operating System

Linux

### Version of Prism Launcher

Updating from Prism Launcher 8.4 to Prism Launcher 9.0

### Version of Qt

Qt 6.2.4

### Description of bug

When downloading the Linux portable install and attempting to run with the `portable.txt` file deleted, the current directory is still used as if the `portable.txt` file exists.

This seems to be caused by the `-d` argument shown in the snippet below.

https://github.com/PrismLauncher/PrismLauncher/blob/a8c3a49cb9d12c41cbdaab85e09d38a071bb7560/launcher/Launcher.in#L43

My pain of trying to update to 9.0:

> I was attempting to update Prism to 9.0. After having no success, I attempted to use my old script to update Prism.
> 
> I finally noticed that the prebuilt non-portable Linux downloads were missing from the release assets.
> 
> I have since noticed the single line at the bottom of the change log. This references a PR contains the comment https://github.com/PrismLauncher/PrismLauncher/pull/2358#issuecomment-2087225964 . Clearly the issue was not announced very well if I only found out after a long while of attempting to update Prism.
> 
> Unfortunately contrary to https://github.com/PrismLauncher/PrismLauncher/pull/2358#issuecomment-2085353723 , I was using the auto-updating feature with the prebuilt tar.gz Linux install.

I am quite annoyed about this after my issues regarding the auto-updater were resolved in response to [my issue](https://github.com/PrismLauncher/PrismLauncher/issues/2586)

Is it possible to remove the `-d` argument from the launcher script and provide a download with both portable and non-portable builds for Linux. Should be as simple as providing a download with and without `portable.txt`.

### Steps to reproduce

* Provided above

### Suspected cause

This seems to be caused by the `-d` argument shown in the snippet below.

https://github.com/PrismLauncher/PrismLauncher/blob/a8c3a49cb9d12c41cbdaab85e09d38a071bb7560/launcher/Launcher.in#L43

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ZekeZDev** [comment]
Thanks for the report, removing of the non portable versions was intentional as the idea was that portable.txt could be removed and system packages should be prefered. However this is not the intended behaviour, I have added it to the 9.1 patch release milestone.

**Comment by mrmelon54** [comment]
Is it possible that the auto-updating feature will break if it tries to download the non-portable version because there is no `portable.txt`. Will the updater accidentally recreate `portable.txt` when updating?

**Comment by ZekeZDev** [comment]
afaik portable and non portable version are the same and just rely on the portable.txt, with the exception or the packaging flag iirc.

**Comment by mrmelon54** [comment]
Does this cause conflict with the auto-updater if running without `portable.txt`?
