### ISSUE TITLE
Process crashed with exitcode -1073741819.

### ISSUE THREAD

**Issue by huntindeed** [PrismLauncher/PrismLauncher#2946]
### Operating System

Windows

### Version of Prism Launcher

9.0

### Version of Qt

6.7.3

### Description of bug

Game crashes at startup/world creation

### Steps to reproduce

Create instance
Start it

### Suspected cause

New version

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by huntindeed** [comment]
https://pastebin.com/X9yadm8d

**Comment by Trial97** [comment]
Not a launcher issue.
Based on last line: `Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.` check your shaders.
