### ISSUE TITLE
Add a generic "Launch and wait" function rather than it only being avalible through external tools like profilers

### ISSUE THREAD

**Issue by SilverAndro** [PrismLauncher/PrismLauncher#295]
### Role

I'm a mod developer who occasionally need to debug things in prod

### Suggestion

The ability to launch the game and wait without having to also launch a profiler or similar tool

### Benefit

Attaching a remote debugger to debug launch stuff currently requires launching an entirely seperate program to get the "waiting" box, and this would remove that

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Ive been doing some production debugging, and the inability to pause the game launch to connect my remote debugger without having to launch an extra, unnecessary tool slows me down quite a bit. You also can't always just launch normally because sometimes bugs are so early that the time it takes to switch to your debugger and tell it too connect is too long.

**Comment by Scrumplex** [comment]
Maybe you can try to run your debugger using a wrapper command?

**Comment by SilverAndro** [comment]
I launch it through IDEA so I can have it jump to source, not sure that sort of communication is available functionally?

**Comment by Scrumplex** [comment]
Would it be fine if you could for example set a JVM arg to enable this feature?

Something like
```
-Dlauncher.wait=true
```

**Comment by SilverAndro** [comment]
That could work, although I'd probably make the name less generic

**Comment by Scrumplex** [comment]
We like to avoid using the name of the launcher, as we want to allow other projects to fork this project without needing to replace so many instances of the launcher name in user-facing parts.

**Comment by SilverAndro** [comment]
Makes sense
