### ISSUE TITLE
Version for a mod is just ${version}

### ISSUE THREAD

**Issue by wolfieboy09** [PrismLauncher/PrismLauncher#2957]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

When I downloaded KubeJS, it also downloads Rhino (needed to run).
When I look at the version for Rhino, it shows it unformatted.
![image](https://github.com/user-attachments/assets/3af4a403-a6ee-40a2-8e0a-92a1563645a1)

### Steps to reproduce

I don't really know. It just does it in this one profile with that one mod

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Issue with the mod not prism(they left the config for another loader inside the archive)
It was already reported and closed with same conclusion.
