### ISSUE TITLE
Java stuff

### ISSUE THREAD

**Issue by Alyaqdhans** [PrismLauncher/PrismLauncher#2965]
### Role

having multiple minecraft instances

### Suggestion

Multiple Java paths

### Benefit

So we can utilize our already installed Java packs

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

- First of all, why is java 16 available? because the minecraft versions that needs java 16 works on 17, isn't it useless?
![image](https://github.com/user-attachments/assets/9d875fd0-1146-4acd-9180-3280d5229483)

<hr>

- Secondly, can we have multi java paths so we can utilize our already installed java packs, it's also because I have JDKs to use for servers and it will auto download the JREs too, having multiple copies for nothing.

   Examples: 
   > Curseforge
![image](https://github.com/user-attachments/assets/8e5fe433-6c51-4432-9ebe-36ee0831eefe)

   > Modrinth
![image](https://github.com/user-attachments/assets/1d0a850f-47c6-4841-955b-2ab38520e4b0)

<hr>

- Lastly, I have my instances custom configured java, can we have reset all instances to global setting option?

**Comment by Trial97** [comment]
Java 16 exist because there is a version of mc that mojang says it supports.
Separate java paths is already sugested

**Comment by Alyaqdhans** [comment]
> Java 16 exist because there is a version of mc that mojang says it supports.

But it works with java 17 so why have extra files to download??

**Comment by Alyaqdhans** [comment]
> Separate java paths is already sugested

Which issue??

**Comment by Trial97** [comment]
> But it works with java 17 so why have extra files to download??

You do not need to download it.





> Which issue??

https://github.com/PrismLauncher/PrismLauncher/issues/1720

**Comment by Alyaqdhans** [comment]
> You do not need to download it.

I'm not talking about me downloading it, it will get auto downloaded when you play (ex v1.17) whereas you can just route it to use java 17 instead of downloading more files.

**Comment by Trial97** [comment]
Good look finding the exact mc version that needs it.
This is there because it was in Mojang meta and we wanted feature parity with the official launcher.

**Comment by Alyaqdhans** [comment]
I think it's only 1.17.X that uses Java 16, although it works with 17
1.16 uses Java 8
1.18 uses Java 17 if not mistaken
