### ISSUE TITLE
Mods compatibility checker with new Minecraft version

### ISSUE THREAD

**Issue by Naezr** [PrismLauncher/PrismLauncher#2969]
### Role

I play modded minecraft

### Suggestion

I want mod upgrade assistant similar to GNOME Extension manager

### Benefit

This will make it more convenient to update your own instances to newer versions of the game

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://github.com/user-attachments/assets/f50de0ea-b6d4-4df8-8a2b-ea502071df4b)

So, GNOME extensions are essentially very similar to Minecraft mods in nature. And there's a feature that lets you check if your extensions are compatible with the new version of GNOME. I would like to see a similar feature in Prism Launcher.

For example, I have an instance with certain mods for version 1.21.1. And then 1.21.2 comes out, and I want to upgrade, but I don't know if all my mods are compatible. This feature will help in the upgrade process by letting you know which mods have updated to the new version of Minecraft and which have not.

**Comment by Trial97** [comment]
In 9.0 you have a new column representing the mod's Minecraft version.
I will close this issue as not planned but if more users want this we will consider it and reopen.
