### ISSUE TITLE
Unable to set my skin with a cape

### ISSUE THREAD

**Issue by PopSikle23** [PrismLauncher/PrismLauncher#2977]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.0

### Version of Qt

6.7.3

### Description of bug

Whenever I try to change my skin with a different cape design it doesnt save the cape design but it does save and change the skin 

### Steps to reproduce

Open the skin manager from the Accounts tab in Settings
Select a skin and change the cape
Save the cape and skin
Load into a game and see no cape

### Suspected cause

I have no idea what could be causing this but it could be an issue with how the skin manager works now in full release because this was not an issue in the dev builds of 9.0

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by SuanOrange** [comment]
I'm having this issue as well, but I think something is wrong with Mojang's servers

**Comment by suferius** [comment]
I have the same issue

**Comment by Trial97** [comment]
Do any of you want to share their prism logs from when this happened?
Logs can be found at:
- name: Portable (Windows / Linux)
    value: '`./logs/PrismLauncher-0.log` In the PrismLauncher folder'
  - name: Windows
    value: '`%APPDATA%/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Scoop
    value: '`%HOMEPATH%\scoop\persist\prismlauncher\logs\PrismLauncher-0.log`'
  - name: macOS
    value: '`~/Library/Application Support/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Linux
    value: '`~/.local/share/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Flatpak
    value: '`~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/logs/PrismLauncher-0.log`'

please do not dump them here as text walls but instead, upload them to a website like [mclo.gs](https://mclo.gs/) or Pastebin

Also no changes were made to the Skin management on the release(compared to the dev builds).

**Comment by suferius** [comment]
https://mclo.gs/5wSZBok

If I select the cape on the minecraft website, in the official launcher or in the prism launcher, I don't have the cape when I enter the world. 
But if I select the cape in the official launcher and run minecraft through it, the cape is there

When I go to “manage skins” it says “no cape”. I can select it there and press "OK", but when I go back to ”manage skins” the cape is no longer selected. 

I realized that if I run minecraft in the official launcher with the cape on me and then just open prism launcher, the cape is gone again

EDIT: I found out that "Vanilla" and "Migrator" capes change correctly, and stay selected. But "Cherry Blossom", "Follower's", "MCC 15th Year", "Purple Heart" and "15th Anniversary" do not

**Comment by SuanOrange** [comment]
> https://mclo.gs/5wSZBok
> 
> 如果我在 minecraft 网站、官方启动器或棱镜启动器中选择披风，那么当我进入世界时，我没有披风。但是如果我在官方启动器中选择披风并通过它运行 minecraft，那么披风就在那里
> 
> 当我去“管理皮肤”时，它说“没有斗篷”。我可以在那里选择它并按“确定”，但是当我返回“管理皮肤”时，披风不再被选中。
> 
> 我意识到，如果我在官方启动器中运行 minecraft，然后打开棱镜启动器，那么 cape 又消失了

https://bugs.mojang.com/browse/MCL-24727
Someone has tested that if you open the official launcher, select the cape, then close the launcher and open it again, the cape disappears

**Comment by ghost** [comment]
I currently only have the ability to select the Vanilla, Migrator and Purple Heart capes. The Follower's and 15th Anni capes I own cannot be applied through the launcher but do seem to work on minecraft.net. Console says nothing out of the ordinary.

**Comment by SuanOrange** [comment]
https://bugs.mojang.com/projects/WEB/issues/WEB-7522

**Comment by ghost** [comment]
> https://bugs.mojang.com/projects/WEB/issues/WEB-7522

Bug tracker helper has confirmed this bug.

**Comment by SuanOrange** [comment]
> > https://bugs.mojang.com/projects/WEB/issues/WEB-7522
> 
> Bug tracker helper has confirmed this bug.

The reporting interface for this issue is no longer open, but the problem still occurs

**Comment by PopSikle23** [comment]
issue has been fixed on mojangs side
