### ISSUE TITLE
AUR/Appimage/9.0 Portable being super slow at fetching url links

### ISSUE THREAD

**Issue by SkyLLerGithub** [PrismLauncher/PrismLauncher#2978]
### Operating System

Linux

### Version of Prism Launcher

PrismLauncher 9.0

### Version of Qt

Qt6/5

### Description of bug

AUR/Appimage and 9.0 portable launcher is slow, by "slow" i mean the amount of time it takes to fetch urls and download files or check for asset index, logging into microsoft, fetching the launcher news or whatever. This has been happening even before 9.0 for 8.4 AUR/Appimage version, Portable version of 8.4 doesn't have this issue, however 9.0 does.

For instance here's a video for comparision:
On 9.0 portable
https://files.catbox.moe/mi6sas.mp4

On 8.4 portable
https://files.catbox.moe/7la3la.mp4

You can see that both launcher version doing the same task on 8.4 its almost 10x faster, logging into microsoft account is slow, downloading is slow, fetching launcher news is slow on 9.0.

[PrismLauncher-1.log](https://github.com/user-attachments/files/17500529/PrismLauncher-1.log)

The same issue has been reported once, however it was closed without the knowledge of what was the cause or issue and the solution.

https://github.com/PrismLauncher/PrismLauncher/issues/1855

Note: I have to tick the checkbox in order to submit an issue, but the issue has been reported before and was not solved.
![image](https://github.com/user-attachments/assets/e4e10e29-d567-4b61-b138-3f34185a2f29)

### Steps to reproduce

Launch prism AUR/Appimage/9.0 portable
Use as normal, slow fetching speeds for url and downloads from servers.

### Suspected cause

None

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
I'll be honest. this looks like you just have horrendously slow DNS resolusion.
there nothing the launcher does that / that has been changed since 8.4 that should affect this.

It *might* be an issue with qt / the older version the portable version builds with? (we are building on Ubuntu 20.4 and so bundles it's qt in portable and appimage)

does this happen if you compile Prism yourself?

**Comment by SkyLLerGithub** [comment]
> I'll be honest. this looks like you just have horrendously slow DNS resolusion. there nothing the launcher does that / that has been changed since 8.4 that should affect this.
> 
> It _might_ be an issue with qt / the older version the portable version builds with? (we are building on Ubuntu 20.4 and so bundles it's qt in portable and appimage)
> 
> do this happen if you compile Prism yourself?

i see, thanks for the reply
when trying to compile cmake just complains that there's no cmakelists.txt in libnbtplusplus
![image](https://github.com/user-attachments/assets/4034860f-85f7-4a16-a906-ff0c8f046450)
what am i supposed to do with this?

**Comment by Ryex** [comment]
make sure to get the submodules too
```
git submodule update --init --recursive
```

**Comment by SkyLLerGithub** [comment]
> make sure to get the submodules too
> 
> ```
> git submodule update --init --recursive
> ```

Ah i see, after compiling the issue persists, is there really no way around it?

**Comment by Ryex** [comment]
hmm. well I personally have no clue where to even start looking to see what's going on here. clearly *something* changed if you say 8.4 doesn't reproduce the issue...
we'll see if any of the other have an idea.

**Comment by SkyLLerGithub** [comment]
> hmm. well I personally have no clue where to even start looking to see what's going on here. clearly _something_ changed if you say 8.4 doesn't reproduce the issue... we'll see if any of the other have an idea.

8.4 Portable* it happens on the AUR and Appimage version
Using a VPN works however, not sure why that is.

**Comment by Ryex** [comment]
yeah, it sounds like a DNS issue.
this may be related so how some people can;t get prism to access the internet...

**Comment by SkyLLerGithub** [comment]
> yeah, it sounds like a DNS issue. this may be related so how some people can;t get prism to access the internet...

i tried switching cloudflare DNS on and off but however that didnt work? I'm not even sure it it has anything to do with this at all, I'm gonna try poking around and see what workarounds I can find for now.

**Comment by ZekeZDev** [comment]
I saw this in search after making my issue #2998 and it seems very similar I would not be surprised if its the same cause. It also doesn't seem to be related directly to the DNS or network for that matter as even the offline operations are signifcantly slower such as unpacking.

**Comment by SkyLLerGithub** [comment]
> I saw this in search after making my issue #2998 and it seems very similar I would not be surprised if its the same cause. It also doesn't seem to be related directly to the DNS or network for that matter as even the offline operations are signifcantly slower such as unpacking.

I tried the flatpak release, also have the same issue.

**Comment by SkyLLerGithub** [comment]
Issue isn't happening on 9.1 AUR/Flatpak, will try portable later.

**Comment by SkyLLerGithub** [comment]
Nevermind, nothing changed. Just forgot to turn off my vpn
