### ISSUE TITLE
give the upload log button a confirmation prompt

### ISSUE THREAD

**Issue by eluna7** [PrismLauncher/PrismLauncher#298]
### Role

developing datapacks

### Suggestion

option to disable the upload console log button, or ask for a confirmation box before uploading the log.

### Benefit

when i go to hit the clear button to investigate errors, i misclick upload. this would also let me quickly close the extra prompt by having an instant "would you like to upload log?" prompt, instead of having to wait for the log to upload regardless of my choice.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://user-images.githubusercontent.com/72943642/197665421-94896486-c06f-4034-99c6-98b096ea2fd4.png)

this evil little button, give it a confirmation box!

**Comment by ghost** [comment]
give an abort button to log upload

**Comment by TheKodeToad** [comment]
I know it's late, but this was fixed in #618.
