### ISSUE TITLE
Installing Curseforge ressource packs makes prism launcher crash / cause errors

### ISSUE THREAD

**Issue by Dodo19DBG** [PrismLauncher/PrismLauncher#2985]
### Operating System

Windows 11
### Version of Prism Launcher

Prism launcher 9.1 / 9.0

### Version of Qt

6.7.2

### Description of bug

When installing some ressource packs with curseforge, shows an error about the URL and fail to install the ressource pack
(and if click on yes makes the launcher crash but only in prism 9.0).

### Steps to reproduce

1. Go to download ressource packs on any version (im using 1.20.1 so idk for others)
2. Download some ressource packs like fresh animations and some more
3. Download and see the *URL not found for: .* bug
4. click on yes to make the launcher crash (on prism 9.0)

### Suspected cause

Im sorry but i don't really know what could cause the problem. Maybe the curseforge API.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
Could you provide some logs of the crash?

Logs can be found at:
- name: Portable (Windows / Linux)
    value: '`./logs/PrismLauncher-0.log` In the PrismLauncher folder'
  - name: Windows
    value: '`%APPDATA%/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Scoop
    value: '`%HOMEPATH%\scoop\persist\prismlauncher\logs\PrismLauncher-0.log`'
  - name: macOS
    value: '`~/Library/Application Support/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Linux
    value: '`~/.local/share/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Flatpak
    value: '`~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/logs/PrismLauncher-0.log`'

**Comment by Trial97** [comment]
This sounds like https://github.com/PrismLauncher/PrismLauncher/issues/2945 but for resource packs.
Also, I have never heard of ` URL not found for: . bug`, is that the exact text displayed(at least the prefix)?
And because, as I mentioned sounds like an solved issue can you fetch the portable build from https://github.com/PrismLauncher/PrismLauncher/actions/runs/11498965728 and try to reproduce it?
(bottom of the page there should be a  `PrismLauncher-Windows-MSVC-Portable-8904153-Debug ` file )

If is still reproduced with the dev build can you provide the prism logs from when that happens?

**Comment by Dodo19DBG** [comment]
[PrismLauncher-0.log](https://github.com/user-attachments/files/17512688/PrismLauncher-0.log)
[PrismLauncher-1.log](https://github.com/user-attachments/files/17512689/PrismLauncher-1.log)
[PrismLauncher-2.log](https://github.com/user-attachments/files/17512692/PrismLauncher-2.log)
[PrismLauncher-3.log](https://github.com/user-attachments/files/17512693/PrismLauncher-3.log)
[PrismLauncher-4.log](https://github.com/user-attachments/files/17512694/PrismLauncher-4.log)
Here are the logs

**Comment by Dodo19DBG** [comment]
![image](https://github.com/user-attachments/assets/8aae1bb8-d456-49fb-b86b-d913130547a9)
here is an image of the bug, the crash was in 9.0

**Comment by Trial97** [comment]
From the logs it doesn't look like the build I mentioned can you try with that build?
Is that dialog presented when you download the resource pack or when browsing them?
If is when downloading can you identify a subset of packs (preferably just one) where that dialog is displayed?

**Comment by Dodo19DBG** [comment]
sorry i have a bad connection it's still downloading

**Comment by Dodo19DBG** [comment]
and the bug happen when the packs are downloading

**Comment by Dodo19DBG** [comment]
![image](https://github.com/user-attachments/assets/777241af-4fba-44dd-906c-e194d7d705a4)

**Comment by Dodo19DBG** [comment]
![image](https://github.com/user-attachments/assets/bb594aec-7d66-43e0-b298-18679b411343)
Still happening on the version i've downloaded.
Here are the logs : 
[PrismLauncher-0.log](https://github.com/user-attachments/files/17512834/PrismLauncher-0.log)
[PrismLauncher-4.log](https://github.com/user-attachments/files/17512835/PrismLauncher-4.log)

**Comment by Dodo19DBG** [comment]
[PrismLauncher-1.log](https://github.com/user-attachments/files/17512938/PrismLauncher-1.log)
there is one more

**Comment by Trial97** [comment]
Ok last question what is the name of resource packs that you try to download and crashes?
As I may know what is the issue but want to be able to reproduce it myself before I try to  fix it .

**Comment by Dodo19DBG** [comment]
It's not a precise ressource pack, but i just figgured out that it's not happening randomly. im sure that mandala's gui and spooky raids aren't working but there are other ones.

**Comment by Trial97** [comment]
How? like literally both the mentioned packs do not have any version available to download(aka. curseforge third-party block)
So how are you able to select them?

**Comment by Dodo19DBG** [comment]
huhhhhhhh
![image](https://github.com/user-attachments/assets/1fbe81d6-895f-4d9d-ae65-d6d1262c09f4)
what the heeellll
"no valid version found"

**Comment by Trial97** [comment]
Yeah I know that is my surprise

**Comment by Dodo19DBG** [comment]
what should i do ?

**Comment by Dodo19DBG** [comment]
may i send you my version of prism ?

**Comment by Trial97** [comment]
Download it manually from curseforge: here is the reason
```
CurseForge added a new option to block third party clients like Prism Launcher from accessing mod files, and they started to enforce this option lately. We can't allow you to download those mods directly from CurseForge because of this. However, Prism Launcher offers a workaround to enable the downloading of these mods, by allowing you to download these mods from your browser and automatically importing them into the instance. We highly encourage asking authors that opted out of client downloads to stop doing so.
```

**Comment by Dodo19DBG** [comment]
Oh ok well i was already downloading from internet but thanks. Sorry if i made you wast time, i should have seen that. good night.

**Comment by Trial97** [comment]
No issue I did find a bug never the less(but not sure if it was yours or not).
