### ISSUE TITLE
If possible, add a resource pack picker and shader pack picker akin to the mod picker

### ISSUE THREAD

**Issue by GoldenFurredFox** [PrismLauncher/PrismLauncher#299]
### Role

I commonly use shader packs and resource packs at random for certain review purposes, and downloading them using my browser can be a hassle.

### Suggestion

I want Prism Launcher to repurpose the mod picker in the edit instance window for picking resource and/or shader packs, preferably both.

### Benefit

It would help me immensely in pack review since I would have to go through fewer steps to download and review packs.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TayouVR** [comment]
somewhat Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/153

(maybe rename to only shaderpacks, as those are not already mentioned in the other issue)

**Comment by DioEgizio** [comment]
shaderpacks cannot be downloaded from the curseforge api anyways

**Comment by DioEgizio** [comment]
Duplicate of #153
