### ISSUE TITLE
Download/Unpacking operations very slow in portable linux builds.

### ISSUE THREAD

**Issue by ZekeZDev** [PrismLauncher/PrismLauncher#2998]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 9.0

### Version of Qt

QT 6.2.4

### Description of bug

Likely related to #2978

I have checked this isn't related to DNS

Flatpak is able to download at network speed, portable is significantly slower.

My connection is 1000mbps

**Portable**
![image](https://github.com/user-attachments/assets/5e90ebde-7f0b-4cfe-8e8b-6dc76ea1db7e)

**Flatpak**
![image](https://github.com/user-attachments/assets/fdd0b63b-c071-4761-848f-be8eaa15a763)

### Steps to reproduce

- Test with portable and with Flatpak from Flathub. 
- Download a modpack

### Suspected cause

This seems to be something related to operations similar to the issue with have with debug builds. Ignoring the constraints of download speed the unpacking of files is also significantly slower when the download is cached on portable. 

Launcher Logs:
https://mclo.gs/D7lZ42L

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by SkyLLerGithub** [comment]
Are you using Flathub system or Flathub user?

**Comment by ZekeZDev** [comment]
> Are you using Flathub system or Flathub user?

system, I havent tried as user. does the issue happen as user for you?

**Comment by SkyLLerGithub** [comment]
> > Are you using Flathub system or Flathub user?
> 
> system, I havent tried as user. does the issue happen as user for you?
> 

Haven't tried user yet, but try 9.1. It isn't happening for me on 9.1 anymore.

**Comment by SkyLLerGithub** [comment]
> > > Are you using Flathub system or Flathub user?
> > 
> > 
> > system, I havent tried as user. does the issue happen as user for you?
> 
> Haven't tried user yet, but try 9.1. It isn't happening for me on 9.1 anymore.

Nvm, its still as slow as ever

**Comment by SkyLLerGithub** [comment]
Does this happen if you use a vpn?

**Comment by ZekeZDev** [comment]
it does for me but yours could be a different issue
