### ISSUE TITLE
OptiFine errors and does not load correctly on 1.18.2 and below - Only occurs with the AUR version

### ISSUE THREAD

**Issue by aquagoose** [PrismLauncher/PrismLauncher#300]
### Operating System

Arch Linux

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

I am making this report on behalf of drax, as they do not have a GitHub account, and have asked me to leave a bug report here.

OptiFine refuses to load, and errors, on any version of Minecraft they tried that is 1.18.2 or below. I've attached the error report they sent here:
[javaerrors-prismlauncher-aurversion.txt](https://github.com/PrismLauncher/PrismLauncher/files/9859738/javaerrors-prismlauncher-aurversion.txt)

They are using Java 19 OpenJDK, using Forge. This only seems to occur on the AUR version, both the binary and the compiled version, and it doesn't occur via Flatpak.

I have tested both 1.18.2 and 1.19 with the AUR version, and while the 1.19 version loads fine, 1.18.2 produces a similar error log to the one I attached. I am also using Forge and Java 19 OpenJDK.

### Steps to reproduce

* Download the OptiFine version for the Minecraft version you are using (1.18.2 or below)
* Using forge, go to `mods -> add file` and select the OptiFine jar file
* Does not load, errors in the log window.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Don't use Java 19 with Forge. It is not compatible yet.
