### ISSUE TITLE
Trying to Reinstall Mod Crashes if No Valid Version Found

### ISSUE THREAD

**Issue by Avakining** [PrismLauncher/PrismLauncher#3001]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.7.3

### Description of bug

Expected either:
- The reinstall button is greyed out and unclickable
- The reinstall button reinstalls the mod, ignoring minecraft versions

What happens:
- Prism crashes

Why is this incorrect:
- Prism should never hard crash

### Steps to reproduce

1. Edit instance
2. Go to 'Mods' tab
3. Select a mod that is for an older version (or whose updated version cannot be found on Modrinth/Curseforge)
4. Click "Change Version"
5. Note that the window says "No valid version found."
6. Click "Reinstall"
7. Prism crashes
https://github.com/user-attachments/assets/affb0e47-4037-48f7-a751-a1426a0830b9

### Suspected cause

I assume Prism tries to download a file that does not exist, which causes a crash

Crash report:
[prismlauncher-2024-10-26-162042.ips.zip](https://github.com/user-attachments/files/17531923/prismlauncher-2024-10-26-162042.ips.zip)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Franco227** [comment]
can confirm
