### ISSUE TITLE
make skin manager?

### ISSUE THREAD

**Issue by BussyBakks** [PrismLauncher/PrismLauncher#3011]
### Role

uh more convenience

### Suggestion

skin manager like minecraft launcher like this
![image](https://github.com/user-attachments/assets/57097338-7c40-4ed6-91c4-d163264f2951)

### Benefit

yeh it make changing skin more quickly

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
Already did that
