### ISSUE TITLE
Launcher crash when launching an instance

### ISSUE THREAD

**Issue by maskersss** [PrismLauncher/PrismLauncher#3018]
### Operating System

Windows 10

### Version of Prism Launcher

9.0-develop portable mingw debug (1f8ce9e)

### Version of Qt

Qt 6.8.0

### Description of bug

i imported a modpack (add instance > curseforge > rlcraft), and when i launched the instance, prism crashed after some time. it doesn't happen to my old instances, and i can't reproduce it anymore with the same instance.
the crash happened before downloading libraries.
[gdbcrash.log](https://github.com/user-attachments/files/17544942/gdbcrash.log) from https://github.com/Trial97/prism_gdb
end of PrismLauncher-0.log: https://mclo.gs/eeZQ0YG

### Steps to reproduce

* import RLCraft from curseforge
* press Launch

tried reproducing it again and prism crashed again. reopening prism and launching the instance works again.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
@maskersss can you test this again with this build:https://github.com/PrismLauncher/PrismLauncher/actions/runs/11559146707?pr=3019
From the crashlog the issue is that we try to delete a object twice, the proposed change makes it so that specific object(mentioned in the crashlog) to not be deleted twice.

**Comment by maskersss** [comment]
lgtm, couldn't reproduce with `PrismLauncher-Windows-MinGW-w64-Portable-55585bd-Debug.zip`

**Comment by edgars-cirulis** [comment]
How your using qt 6.8 when it's not even shipped?

**Comment by Ryex** [comment]
> How your using qt 6.8 when it's not even shipped?

it's arm version not default installable via the aqt github action yet. however mingw and others can still install it
