### ISSUE TITLE
File drag and drop borken on flatpak version

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#302]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 5.0 (flatpak)

### Version of Qt

Qt 5.15.6

### Description of bug

File drag and drop does not work on the flatpak version.

and this error gets logged in the terminal:

```
  165.853 W Caught attempt to install non-existing file or file-like object: "/home/joe/Documents/Test/OptiFine_1.18.2_HD_U_H7.jar"
```

### Steps to reproduce

https://user-images.githubusercontent.com/110736028/197779888-33152023-edcd-476f-a672-e9f59206ba95.mp4

### Suspected cause

Weird flatpak permissions

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TayouVR** [comment]
I think this is simply related to permissions... Try giving Prism access to your home folder via e.g. flatseal.

**Comment by ghost** [comment]
> I think this is simply related to permissions... Try giving Prism access to your home folder via e.g. flatseal.

That fixed it. Thanks
