### ISSUE TITLE
Installing Modrinth resource packs makes prism launcher crash / cause errors

### ISSUE THREAD

**Issue by kubo6472** [PrismLauncher/PrismLauncher#3023]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt version 6.7.3.

### Description of bug

Looks exactly like #2985 Prism Launcher crashes, but when downloading a handful (7 I think) resource packs from Modrinth

### Steps to reproduce

1. Edit instance
2. Resource packs
3. Download packs
4. Make a selection
5. Observe crash
6. [Logs](https://gist.github.com/kubo6472/7cc538946a94357591ccc4c559d45aef)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Can you see if it is reproduced with the nightly build: https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop (recomandation file that starts with PrismLauncher-Windows-MinGW-w64-Portable-)

If yes I will prepare a zip archive that also include a crash reporter for windows

**Comment by Rafii2198** [comment]
I personally have similar issue but actually with downloading anything, I tried to download like 100 mods in one go, and it crashed, then I tried to at least verify dependencies, so I can launch the game but when it was downloading them it crashed again and at that point I came here and found this.

I tried the nightly build and downloaded over 100 mods again, and it didn't crash, so I assume it is fixed, tho I noticed some other bugs in that build unrelated to this issue

**Comment by Trial97** [comment]
I prepared a portable debug build: https://media.githubusercontent.com/media/Trial97/prism_gdb/refs/heads/master/PrismLauncher-Windows-MinGW-w64-Portable-ba07a13-Debug.zip?download=true (portable build + debuger)

Download and extract that file.
Start prism using the gdbprismlauncher.bat file(the extension may be missing), not the normal executable; do not touch the opened command prompt(black thing with text)
Try to reproduce the crash;if the application is stuck leave it a few minutes(it takes a while to generate all the backtrace)

Once it completely closes there will be a gdbcrash.log file. Please share that file( is a stacktrace of the crash)

The source code for how I created that zip can be found here https://github.com/Trial97/prism_gdb/tree/master

**Comment by kubo6472** [comment]
[New Thread 10408.0x16bc]
[New Thread 10408.0x1780]
[New Thread 10408.0x1f50]
[New Thread 10408.0x16d0]
[New Thread 10408.0xa50]
[New Thread 10408.0x2944]
[New Thread 10408.0x293c]
[New Thread 10408.0x2948]
[New Thread 10408.0x2888]
[New Thread 10408.0x2adc]
[New Thread 10408.0x1d8c]
[New Thread 10408.0x7e0]
[New Thread 10408.0x2878]
[New Thread 10408.0x29f4]
[New Thread 10408.0x2ad0]
[New Thread 10408.0x1594]
[New Thread 10408.0x2a94]
[New Thread 10408.0x1904]
[New Thread 10408.0x2b4c]
[New Thread 10408.0x2784]
[Thread 10408.0x2948 exited with code 0]
[New Thread 10408.0x176c]
[Thread 10408.0x176c exited with code 0]
[New Thread 10408.0x2b90]
[New Thread 10408.0x91c]
[New Thread 10408.0x1e48]
[New Thread 10408.0x1fd4]
[New Thread 10408.0xc04]
[New Thread 10408.0x1028]
[Thread 10408.0xc04 exited with code 0]
[Thread 10408.0x1fd4 exited with code 0]
[New Thread 10408.0x2224]
[New Thread 10408.0x2b50]
[New Thread 10408.0x3c0]
[Thread 10408.0x2784 exited with code 0]
[Thread 10408.0x2ad0 exited with code 0]
[Thread 10408.0x7e0 exited with code 0]
[Thread 10408.0x1f50 exited with code 0]
[Thread 10408.0x16bc exited with code 0]
[Thread 10408.0x1780 exited with code 0]
[Thread 10408.0x1594 exited with code 0]
[Thread 10408.0x2b4c exited with code 0]
[Thread 10408.0x1904 exited with code 0]
[Thread 10408.0x2a94 exited with code 0]
[Thread 10408.0x2224 exited with code 0]
[Thread 10408.0x2b50 exited with code 0]
[Thread 10408.0x3c0 exited with code 0]
[Thread 10408.0x16d0 exited with code 0]
[Thread 10408.0x1028 exited with code 0]
[New Thread 10408.0x29b4]
[New Thread 10408.0x8a4]
[New Thread 10408.0x2a3c]
[New Thread 10408.0x2a7c]
[New Thread 10408.0x2b9c]
[Thread 10408.0x1e48 exited with code 0]
[Thread 10408.0x91c exited with code 0]
[Thread 10408.0x2944 exited with code 0]
[Thread 10408.0x2b90 exited with code 0]
[Thread 10408.0x2a7c exited with code 0]
[Thread 10408.0x29b4 exited with code 0]
[Thread 10408.0x2a3c exited with code 0]
[Thread 10408.0x8a4 exited with code 0]
[Thread 10408.0x1d8c exited with code 0]
[Thread 10408.0x2888 exited with code 0]
[Thread 10408.0x2878 exited with code 0]
[Thread 10408.0x2adc exited with code 0]
[Thread 10408.0x293c exited with code 0]
[Thread 10408.0xa50 exited with code 0]
[Thread 10408.0x29f4 exited with code 0]
[Thread 10408.0x2b9c exited with code 0]
[Inferior 1 (process 10408) exited normally]
.gdbinit:5: Error in sourced command file:
No stack.

for me it did not crash

**Comment by Trial97** [comment]
Then I will consider it as complete as it no longer crashes with the mentioned build(there were some bug fixes on the build that will be released on 9.2)
Feel free to reopen it if you encounter it again but please post the crashlog.
