### ISSUE TITLE
I can't update mods

### ISSUE THREAD

**Issue by Kadircan9090** [PrismLauncher/PrismLauncher#3025]
I can't update the mods, it gives an error
![Ekran Görüntüsü (13)](https://github.com/user-attachments/assets/15afa340-be57-476b-a989-31b4c1a14f29)

**Comment by Trial97** [comment]
Click no on that dialog. 
This happens because we try to get the mod information from modrinth and fails. 
That dialog is asking if you want to retry a certain action.

**Comment by hl2jeep** [comment]
> Click no on that dialog. This happens because we try to get the mod information from modrinth and fails. That dialog is asking if you want to retry a certain action.

i have this issue too, its not a single case senario, i checked and it seems modrinth is returning an empty response
