### ISSUE TITLE
Data location (scoop installation) seems not to work

### ISSUE THREAD

**Issue by SiriosDev** [PrismLauncher/PrismLauncher#3026]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.7.3

### Description of bug

I was trying to migrate the configuration from normal installation to the scoop version, pasting the cfg file into the `%HOMEPATH%\scoop\persist\prismlauncher` folder as mentioned by the guide, it does not cause anything, in fact it seems that `persist` is totally unrelated to the respective files

### Steps to reproduce

* Install 9.1
* try altering (or copying) the cfg
* open prism launcher

### Suspected cause

May be something related to the scoop bucket, but I'm just guessing

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
6.1 is long unsupported.
No bugfixes will happen on that version

**Comment by SiriosDev** [comment]
sorry my total bad
typo

**Comment by SiriosDev** [comment]
I was convinced I wrote 9 not 6 😅, now is fixed

**Comment by Trial97** [comment]
From what I know we did not change anything regarding the path or stuff in 9.0 or 9.1.
From the history of the package on scoop-games I see https://github.com/Calinou/scoop-games/pull/1171 that did some changes but I'm not sure.
Also this doesn't look like a Prism issue but a packaging issue on scoop side.
@getchoo can you have a look?(I'm not familiar with this)

**Comment by TayouVR** [comment]
~~the way that scoop handles persistent data it creates symlinks between the persist folder and the apps/prismlauncher/<version> folder. if you manually paste config files and such you may need to create the symlink manually too, I'm not sure...~~

~~actually now that I look at my install I don't think prismlauncher.cfg or accounts.json is persisted correctly....
I'm not sure why the above mentioned PR removed the config files from persist...~~

okay I have no clue... the PR says, that it just changed how the files are persisted, not that they are, but in my install they aren't persisted either...
the files in persist are hardlinks
![image](https://github.com/user-attachments/assets/d7e62871-2415-4590-b12b-e0ffa80e91ac)
but not to the 9.0 or 9.1 folder, I think the above mentioned PR may have broken this...
![image](https://github.com/user-attachments/assets/ca4b8964-cbd9-4c4f-bd9c-f2b93baa6a2d)

normally scoop uses junctions for directory mounts from persist:
![image](https://github.com/user-attachments/assets/e804ac64-901f-46e6-8264-636f3dae6024)

**Comment by getchoo** [comment]
An issue should be opened in https://github.com/Calinou/scoop-game if that's the case. This doesn't seem like something we can fix upstream
