### ISSUE TITLE
cant play old versions using Igpu 

### ISSUE THREAD

**Issue by El-Nice** [PrismLauncher/PrismLauncher#3037]
### Operating System

Windows

### Version of Prism Launcher

prism launcher 9.1

### Version of Qt

Qt 6.7.3

### Description of bug

Every time I try to play older versions of Minecraft like 1.6.4, in this case, the game opens for a second and then closes immediately with error code 1 

### Steps to reproduce

creating an instance with an old version 
starting the instance

### Suspected cause

its an error caused by this line of the code `XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump` 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
Could you upload a log?

**Comment by El-Nice** [comment]
> Could you upload a log?

https://mclo.gs/p8omz4y

**Comment by El-Nice** [comment]
> Could you upload a log?

`<html>
<body>

Prism Launcher version: 9.1 (official)
--
2 |  
3 |  
4 | Launched instance in online mode
5 |  
6 | login.microsoftonline.com resolves to:
7 | [**.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**]
8 |  
9 |  
10 | session.minecraft.net resolves to:
11 | [**.**.**.**]
12 |  
13 |  
14 | textures.minecraft.net resolves to:
15 | [**.**.**.**]
16 |  
17 |  
18 | api.mojang.com resolves to:
19 | [**.**.**.**]
20 |  
21 |  
22 | Minecraft folder is:
23 | C:/Users/********/AppData/Roaming/PrismLauncher/instances/legacyfabric-1.6.4 loader.0.15.6/.minecraft
24 |  
25 |  
26 | Java path is:
27 | C:/Users/********/AppData/Roaming/PrismLauncher/java/java-runtime-gamma/bin/javaw.exe
28 |  
29 |  
30 | Java is version 17.0.8, using 64 (amd64) architecture, from Microsoft.
31 |  
32 |  
33 | Main Class:
34 | net.fabricmc.loader.impl.launch.knot.KnotClient
35 |  
36 | Native path:
37 | C:/Users/********/AppData/Roaming/PrismLauncher/instances/legacyfabric-1.6.4 loader.0.15.6/natives
38 |  
39 | Traits:
40 | traits noapplet
41 | traits legacyServices
42 |  
43 | Libraries:
44 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
45 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
46 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
47 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
48 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
49 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
50 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
51 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
52 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
53 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
54 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/argo/argo/2.25_fixed/argo-2.25_fixed.jar
55 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar
56 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/google/guava/guava/14.0/guava-14.0.jar
57 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
58 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
59 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar
60 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/legacyfabric/intermediary/1.6.4/intermediary-1.6.4.jar
61 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar
62 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
63 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
64 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
65 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
66 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5 mixin.0.8.5/sponge-mixin-0.12.5 mixin.0.8.5.jar
67 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/fabric-loader/0.15.6/fabric-loader-0.15.6.jar
68 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/mojang/minecraft/1.6.4/minecraft-1.6.4-client.jar
69 |  
70 | Native libraries:
71 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
72 | C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
73 |  
74 | Mods:
75 | [✔] btw-fabric-3.0.0-beta-snapshot-3a-release
76 | [✔] legacy-fixes-1.0.1
77 |  
78 | Params:
79 | --username  --session  --version 1.6.4 --gameDir C:/Users/********/AppData/Roaming/PrismLauncher/instances/legacyfabric-1.6.4 loader.0.15.6/.minecraft --assetsDir C:/Users/********/AppData/Roaming/PrismLauncher/assets/virtual/legacy
80 |  
81 | Window size: 854 x 480
82 |  
83 | Launcher: standard
84 |  
85 | Java major version is incompatible. Things might break.
86 | Java Arguments:
87 | [-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4576m, -Duser.language=en]
88 |  
89 |  
90 | Minecraft process ID: 10936
91 |  
92 |  
93 | [22:04:06] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.6.4 with Fabric Loader 0.15.6
94 | [22:04:06] [WARN] [FabricLoader/Metadata]: Mod btw uses the version 3.0.0 Beta Snapshot 3a which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0 Beta Snapshot 3a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
95 | [22:04:07] [INFO] [FabricLoader/]: Loading 13 mods:
96 | - btw 3.0.0 Beta Snapshot 3a
97 | \|-- com_google_code_gson_gson 2.8.9
98 | \|-- grossfabrichacks 6.1-btw
99 | \|    \|-- net_auoeke_reflect 6.3.0
100 | \|    \|-- net_auoeke_unsafe 1.7.3
101 | \|    \-- net_bytebuddy_byte-buddy-agent 1.14.18
102 | \|-- org_apache_logging_log4j_log4j-api 2.19.0
103 | \-- org_apache_logging_log4j_log4j-core 2.19.0
104 | - fabricloader 0.15.6
105 | \-- mixinextras 0.3.2
106 | - java 17
107 | - legacy-fixes 1.0.1
108 | - minecraft 1.6.4
109 | Oct 31, 2024 10:04:07 PM net.devtech.grossfabrichacks.GrossFabricHacks <clinit>
110 | INFO: no good? no, this man is definitely up to evil.
111 | Oct 31, 2024 10:04:07 PM net.devtech.grossfabrichacks.GrossFabricHacks <clinit>
112 | WARNING: KnotClassLoader, you fool! Loading me was a grave mistake.
113 | [22:04:07] [INFO] [FabricLoader/Mixin]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5 mixin.0.8.5/sponge-mixin-0.12.5 mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
114 | [22:04:08] [INFO] [FabricLoader/Mixin]: Compatibility level set to JAVA_17
115 | Loaded 28097 patches for 2027 classes
116 | Applying patch N/A
117 | Oct 31, 2024 10:04:13 PM org.spongepowered.asm.mixin.transformer.HackedMixinTransformer <clinit>
118 | INFO: MixinTransformer found! org.spongepowered.asm.mixin.transformer.MixinTransformer@6a0a0f12
119 | Oct 31, 2024 10:04:13 PM org.spongepowered.asm.mixin.transformer.HackedMixinTransformer <clinit>
120 | INFO: Unsafe cast mixin transformer success!
121 | [22:04:13] [WARN] [FabricLoader/Mixin]: Reference map 'grossfabrichacks-refmap.json' for grossfabrichacks.mixins.json could not be read. If this is a development environment you can ignore this message
122 | [22:04:16] [INFO] [FabricLoader/MixinExtras\|Service]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
123 | Found Minecraft class
124 | Injected startClient call
125 |  
126 | MCPatcherUtils initialized:
127 | Minecraft directory: C:\Users\********\AppData\Roaming\.minecraft
128 | (assets, libraries, versions)
129 | Game directory:      C:\Users\********\AppData\Roaming\.minecraft
130 | (resourcepacks, saves)
131 | Minecraft version:   1.6.4
132 | MCPatcher version:   5.0.3
133 | Max heap memory:     4576.0MB
134 | Oct 31, 2024 10:04:18 PM net.fabricmc.loader.impl.launch.knot.UnsafeKnotClassLoader loadClass
135 | WARNING: Failed to load class sun.misc.VM from KnotClassLoader, CREATE A DUMMY CLASS
136 | WARNING: configuration file C:\Users\********\AppData\Roaming\.minecraft\mcpatcher.json not found, using defaults
137 | WARNING: could not determine selected profile, defaulting to MCPatcher
138 | Launcher profile:  MCPatcher
139 |  
140 | 2024-10-31 22:04:19 [CLIENT] [INFO] Setting user: Nice
141 | 2024-10-31 22:04:19 [CLIENT] [INFO] (Session ID is token:****************:****************)
142 | ...Add-On Handler Initializing...
143 | Classloader: net.fabricmc.loader.impl.launch.knot.UnsafeKnotClassLoader
144 | Skipping double loading addon btw.BTWMod
145 | Skipping double loading addon emi.dev.emi.emi.EMIPostInit
146 | Loading addon: btw
147 | Loading addon: com_google_code_gson_gson
148 | Loading addon: fabricloader
149 | Loading addon: grossfabrichacks
150 | Loading addon: java
151 | Loading addon: legacy-fixes
152 | Loading addon: minecraft
153 | Loading addon: mixinextras
154 | Loading addon: net_auoeke_reflect
155 | Loading addon: net_auoeke_unsafe
156 | Loading addon: net_bytebuddy_byte-buddy-agent
157 | Loading addon: org_apache_logging_log4j_log4j-api
158 | Loading addon: org_apache_logging_log4j_log4j-core
159 | Loaded 2 addons
160 | Better Than Wolves Community Edition Version 3.0.0 Beta Snapshot 3a Initializing...
161 | Better Than Wolves Initialization Complete.
162 | EMI for Better Than Wolves 3.0.0 Beta Snapshot 3a Initializing...
163 | Oct 31, 2024 10:04:32 PM net.fabricmc.loader.impl.launch.knot.UnsafeKnotClassLoader loadClass
164 | WARNING: Failed to load class dev.emi.emi.platform.fabric.EmiAgnosBTWFabric from KnotClassLoader, CREATE A DUMMY CLASS
165 | ...Add-On Handler Initialization Complete...
166 | Hello from MinecraftMixin!
167 | Completely ignored arguments: [--accessToken, FabricMC, --versionType, Fabric]
168 | 2024-10-31 22:04:33 [CLIENT] [INFO] LWJGL Version: 2.9.4
169 | 2024-10-31 22:04:34 [CLIENT] [INFO] Reloading ResourceManager: Default
170 |  
171 | Starting up SoundSystem...
172 | [Texture Pack] INFO: initializing HD Font...
173 | Initializing LWJGL OpenAL
174 | (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
175 | OpenAL initialized.
176 |  
177 | #
178 | # A fatal error has been detected by the Java Runtime Environment:
179 | #
180 | #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc13042ee7, pid=10936, tid=5292
181 | #
182 | # JRE version: OpenJDK Runtime Environment Microsoft-8035246 (17.0.8 7) (build 17.0.8 7-LTS)
183 | # Java VM: OpenJDK 64-Bit Server VM Microsoft-8035246 (17.0.8 7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
184 | # Problematic frame:
185 | # C  [ig7icd64.dll 0x22ee7]
186 | #
187 | # No core dump will be written. Minidumps are not enabled by default on client versions of Windows
188 | #
189 | # An error report file with more information is saved as:
190 | # C:\Users\********\AppData\Roaming\PrismLauncher\instances\legacyfabric-1.6.4 loader.0.15.6\.minecraft\hs_err_pid10936.log
191 | #
192 | # If you would like to submit a bug report, please visit:
193 | #   https://aka.ms/minecraftjavacrashes
194 | # The crash happened outside the Java Virtual Machine in native code.
195 | # See problematic frame for where to report the bug.
196 | #
197 | AL lib: (EE) alc_cleanup: 1 device not closed
198 | Process exited with code 1.
199 | Log upload triggered at: 31 Oct 2024 22:04:39  0100


</body>
</html>Prism Launcher version: 9.1 (official)


Launched instance in online mode

login.microsoftonline.com resolves to:
    [**.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**]


session.minecraft.net resolves to:
    [**.**.**.**]


textures.minecraft.net resolves to:
    [**.**.**.**]


api.mojang.com resolves to:
    [**.**.**.**]


Minecraft folder is:
C:/Users/********/AppData/Roaming/PrismLauncher/instances/legacyfabric-1.6.4 loader.0.15.6/.minecraft


Java path is:
C:/Users/********/AppData/Roaming/PrismLauncher/java/java-runtime-gamma/bin/javaw.exe


Java is version 17.0.8, using 64 (amd64) architecture, from Microsoft.


Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Users/********/AppData/Roaming/PrismLauncher/instances/legacyfabric-1.6.4 loader.0.15.6/natives

Traits:
traits noapplet
traits legacyServices

Libraries:
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/java/jinput/jinput/[2](https://mclo.gs/p8omz4y#L2).0.5/jinput-2.0.5.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/paulscode/codecjorbis/2010102[3](https://mclo.gs/p8omz4y#L3)/codecjorbis-20101023.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/paulscode/librarylwjglopenal/2010082[4](https://mclo.gs/p8omz4y#L4)/librarylwjglopenal-20100824.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/argo/argo/2.2[5](https://mclo.gs/p8omz4y#L5)_fixed/argo-2.25_fixed.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/google/guava/guava/14.0/guava-14.0.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/legacyfabric/intermediary/1.[6](https://mclo.gs/p8omz4y#L6).4/intermediary-1.6.4.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5 mixin.0.8.5/sponge-mixin-0.12.5 mixin.0.8.5.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/fabric-loader/0.15.6/fabric-loader-0.15.6.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/com/mojang/minecraft/1.6.4/minecraft-1.6.4-client.jar

Native libraries:
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Mods:
  [✔] btw-fabric-3.0.0-beta-snapshot-3a-release
  [✔] legacy-fixes-1.0.1

Params:
  --username  --session  --version 1.6.4 --gameDir C:/Users/********/AppData/Roaming/PrismLauncher/instances/legacyfabric-1.6.4 loader.0.15.6/.minecraft --assetsDir C:/Users/********/AppData/Roaming/PrismLauncher/assets/virtual/legacy

Window size: 854 x 480

Launcher: standard

Java major version is incompatible. Things might break.
Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx45[7](https://mclo.gs/p8omz4y#L7)6m, -Duser.language=en]


Minecraft process ID: 10936


[22:04:06] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.6.4 with Fabric Loader 0.15.6
[22:04:06] [WARN] [FabricLoader/Metadata]: Mod btw uses the version 3.0.0 Beta Snapshot 3a which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0 Beta Snapshot 3a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[22:04:07] [INFO] [FabricLoader/]: Loading 13 mods:
	- btw 3.0.0 Beta Snapshot 3a
	   |-- com_google_code_gson_gson 2.[8](https://mclo.gs/p8omz4y#L8).[9](https://mclo.gs/p8omz4y#L9)
	   |-- grossfabrichacks 6.1-btw
	   |    |-- net_auoeke_reflect 6.3.0
	   |    |-- net_auoeke_unsafe 1.7.3
	   |    \-- net_bytebuddy_byte-buddy-agent 1.14.18
	   |-- org_apache_logging_log4j_log4j-api 2.19.0
	   \-- org_apache_logging_log4j_log4j-core 2.19.0
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- java 17
	- legacy-fixes 1.0.1
	- minecraft 1.6.4
Oct 31, 2024 [10](https://mclo.gs/p8omz4y#L10):04:07 PM net.devtech.grossfabrichacks.GrossFabricHacks <clinit>
INFO: no good? no, this man is definitely up to evil.
Oct 31, 2024 10:04:07 PM net.devtech.grossfabrichacks.GrossFabricHacks <clinit>
WARNING: KnotClassLoader, you fool! Loading me was a grave mistake.
[22:04:07] [INFO] [FabricLoader/Mixin]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/********/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.[12](https://mclo.gs/p8omz4y#L12).5 mixin.0.8.5/sponge-mixin-0.12.5 mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[22:04:08] [INFO] [FabricLoader/Mixin]: Compatibility level set to JAVA_17
Loaded 28097 patches for 2027 classes
Applying patch N/A
Oct 31, 2024 10:04:[13](https://mclo.gs/p8omz4y#L13) PM org.spongepowered.asm.mixin.transformer.HackedMixinTransformer <clinit>
INFO: MixinTransformer found! org.spongepowered.asm.mixin.transformer.MixinTransformer@6a0a0f12
Oct 31, 2024 10:04:13 PM org.spongepowered.asm.mixin.transformer.HackedMixinTransformer <clinit>
INFO: Unsafe cast mixin transformer success!
[22:04:13] [WARN] [FabricLoader/Mixin]: Reference map 'grossfabrichacks-refmap.json' for grossfabrichacks.mixins.json could not be read. If this is a development environment you can ignore this message
[22:04:16] [INFO] [FabricLoader/MixinExtras|Service]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
Found Minecraft class
Injected startClient call

MCPatcherUtils initialized:
Minecraft directory: C:\Users\********\AppData\Roaming\.minecraft
  (assets, libraries, versions)
Game directory:      C:\Users\********\AppData\Roaming\.minecraft
  (resourcepacks, saves)
Minecraft version:   1.6.4
MCPatcher version:   5.0.3
Max heap memory:     4576.0MB
Oct 31, 2024 10:04:18 PM net.fabricmc.loader.impl.launch.knot.UnsafeKnotClassLoader loadClass
WARNING: Failed to load class sun.misc.VM from KnotClassLoader, CREATE A DUMMY CLASS
WARNING: configuration file C:\Users\********\AppData\Roaming\.minecraft\mcpatcher.json not found, using defaults
WARNING: could not determine selected profile, defaulting to MCPatcher
Launcher profile:  MCPatcher

2024-10-31 22:04:19 [CLIENT] [INFO] Setting user: Nice
2024-10-31 22:04:19 [CLIENT] [INFO] (Session ID is token:****************:****************)
...Add-On Handler Initializing...
Classloader: net.fabricmc.loader.impl.launch.knot.UnsafeKnotClassLoader
Skipping double loading addon btw.BTWMod
Skipping double loading addon emi.dev.emi.emi.EMIPostInit
Loading addon: btw
Loading addon: com_google_code_gson_gson
Loading addon: fabricloader
Loading addon: grossfabrichacks
Loading addon: java
Loading addon: legacy-fixes
Loading addon: minecraft
Loading addon: mixinextras
Loading addon: net_auoeke_reflect
Loading addon: net_auoeke_unsafe
Loading addon: net_bytebuddy_byte-buddy-agent
Loading addon: org_apache_logging_log4j_log4j-api
Loading addon: org_apache_logging_log4j_log4j-core
Loaded 2 addons
Better Than Wolves Community Edition Version 3.0.0 Beta Snapshot 3a Initializing...
Better Than Wolves Initialization Complete.
EMI for Better Than Wolves 3.0.0 Beta Snapshot 3a Initializing...
Oct 31, 2024 10:04:32 PM net.fabricmc.loader.impl.launch.knot.UnsafeKnotClassLoader loadClass
WARNING: Failed to load class dev.emi.emi.platform.fabric.EmiAgnosBTWFabric from KnotClassLoader, CREATE A DUMMY CLASS
...Add-On Handler Initialization Complete...
Hello from MinecraftMixin!
Completely ignored arguments: [--accessToken, FabricMC, --versionType, Fabric]
2024-10-31 22:04:33 [CLIENT] [INFO] LWJGL Version: 2.9.4
2024-10-31 22:04:34 [CLIENT] [INFO] Reloading ResourceManager: Default

Starting up SoundSystem...
[Texture Pack] INFO: initializing HD Font...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc13042ee7, pid=10936, tid=5292
#
# JRE version: OpenJDK Runtime Environment Microsoft-8035246 (17.0.8 7) (build 17.0.8 7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-8035246 (17.0.8 7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [ig7icd64.dll 0x22ee7]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\********\AppData\Roaming\PrismLauncher\instances\legacyfabric-1.6.4 loader.0.[15](https://mclo.gs/p8omz4y#L15).6\.minecraft\hs_err_pid10936.log
#
# If you would like to submit a bug report, please visit:
#   https://aka.ms/minecraftjavacrashes
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 1.
Log upload triggered at: 31 Oct [20](https://mclo.gs/p8omz4y#L20)24 [22](https://mclo.gs/p8omz4y#L22):04:39  0100`

**Comment by El-Nice** [comment]
> Could you upload a log?

here [https://mclo.gs/p8omz4y](url)

**Comment by TheKodeToad** [comment]
It's probably due to using Java 17 - Java 8 or lower is optimal for older versions

**Comment by El-Nice** [comment]
> It's probably due to using Java 17 - Java 8 or lower is optimal for older versions

This is the optimal Java version to use as better than Wolves Mod creator recommends to use
