### ISSUE TITLE
1.12 mods don't update properly

### ISSUE THREAD

**Issue by Oregano1963** [PrismLauncher/PrismLauncher#3040]
### Operating System

Linux

### Version of Prism Launcher

9.0/9.1 and not 8.4

### Version of Qt

unknown

### Description of bug

When updating mods, most of them don't have any data available (where they once did) and some mods show older versions when selecting which mods to update

### Steps to reproduce

Make a 1.12 forge instance and download a mod like aetherium ashen armor. Then check for updates--you should notice that some mods don't have data available and ashen armor itself updates to an old version.

### Suspected cause

Unsure but this is unique to Prism 9.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Puggicorn** [comment]
Encountered this bug myself I clicked the "Check for updates button" and it set my e4mc and Resourceful Lib versions lower than latest, despite having the latest already installed.

e4mc  5.2.1 -> 4.0.1
Resourceful Lib 2.1.29 -> 2.1.4

Notable connections made:
- Affected mods are missing their image icon
- Re-downloading the mod manually without using "Check for updates" uses the correct version

Using: 
- Windows OS
- Prism launcher version 9.1

**Comment by Oregano1963** [comment]
This is unfortunately not fixed with 9.2.

**Comment by freopt** [comment]
Yep still broken
