### ISSUE TITLE
When updating mods make a option to delete/remove no valid version mods 

### ISSUE THREAD

**Issue by flikrheist** [PrismLauncher/PrismLauncher#3047]
### Role

I make Minecraft modpacks on Prism and its a nuisance to manually delete every single "no valid version found" mod.

### Suggestion

Add a option to delete invalid mods when updating.

### Benefit

So that it's easier and quicker to make modpacks.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
On 9.x versions you have a few columns added to the mods view: loader and mcversion(you may need to enable them by right clicking on the table header). So no there will not be an option to automatically delete incompatible mods.
You can take this decision based on the information we provided.
