### ISSUE TITLE
build type option

### ISSUE THREAD

**Issue by connorfrancey** [PrismLauncher/PrismLauncher#3050]
### Role

Developer

### Suggestion

Option to decide if prism should use nightly (dev) builds or release builds

### Benefit

This would greatly improve my dev experience, as i find myself constantly switching between releases.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/3029
