### ISSUE TITLE
I can't play the game

### ISSUE THREAD

**Issue by GameNight1436** [PrismLauncher/PrismLauncher#3054]
### Operating System

Windows

### Version of Prism Launcher

The latest prism launcher

### Version of Qt

1.20.1

### Description of bug

I can't join any servers and it keeps saying auth servers down sorry!

### Steps to reproduce

Idk it just started doing that a few days ago

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Not prism fault
