### ISSUE TITLE
Add option to remove cat

### ISSUE THREAD

**Issue by leftmove** [PrismLauncher/PrismLauncher#3059]
### Role

In my opinion, the cat is obtrusive.

### Suggestion

I want an option to remove the cat button.

### Benefit

The UI will look much cleaner.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I understand that many people like the cat, and to each their own, but I think the UI could look a lot more clean if there was no cat.

I'd appreciate the ability to disable the cat.

**Comment by twojapiez** [comment]
can't you just click the cat button to disable the cat or are you mad at the button aswell?
edit: i misread and i think you can drag out the cat button not sure tho

**Comment by ZenithRogue** [comment]
Just click the cat button, it turns off the cat
![PrismLauncher-cat-button](https://github.com/user-attachments/assets/e547c61c-fffb-4887-be3f-3fca54203e9c)

**Comment by Trial97** [comment]
There was no follow-up on this to clarify if you want the button to be removed.
I'm gonna close this as right now there is no desire to remove that button.

**Comment by leftmove** [comment]
Why would I need to follow-up in order to clarify I still want it removed? If there is confusion about whether I am talking about the cat pop-up or the cat button itself - I am talking about the button.

I just thought the interface would look cleaner if there wasn't a random unrelated PNG next to the important stuff. I just didn't know people were religious about the cat 😭 😭 😭 😭

If anyone could point me to the where the settings and navigation UI is stored, I will change the code and pull request myself.

**Comment by Airbus-A330-bruh** [comment]
why u want to remove da cat :(
