### ISSUE TITLE
Pack icon doesn't export with the pack itself

### ISSUE THREAD

**Issue by shinji257** [PrismLauncher/PrismLauncher#306]
### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

When exporting a pack the icon is not exported along with the rest of the pack itself.  This results in a pack that won't have an icon when imported even though it is defined.

Secondary bug: If you import a zip that has an icon defined but isn't in the zip itself and that icon already exists in the icons folder it will be deleted instead of re-used.  This results in all other instances that happened to use that icon to revert to a default icon instead.

### Steps to reproduce

Import or create a pack and set an icon.  The effect is more apparent if you set a custom icon since it won't be in the default set.

Workaround: You can copy the set icon to the root of the instance folder (along with the mmc-pack.json file) and it will be saved into the exported package.  When imported the file gets correctly copied and used.

### Suspected cause

In MultiMC the icon for the pack was always included in the export zip.  I'm thinking this got lost when the packaging format was changed?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Is this bug still applicable to the latest version(7.2)?
I'm not able to reproduce this with the following steps:
- create an instance
- add a custom icon(not build in)
- export using PrismLauncher format
- then import it

Checked the zip file generated and has the icon inside.
I also tried to delete the icon and then import again(it still works)

Also the other bug I'm not able to reproduce it:
- have the icon still defined in prism 
- manually deleted from the zip file
- then import

Doesn't remove already existing icon but instead reuses it

**Comment by shinji257** [comment]
I kinda forgot about this but I'll check when I get a moment.

**Comment by octanervoc** [comment]
I can confirm it's still present.

1. Export instance on `PC 1`.
2. Send it to `PC 2`.
3. When importing said instance on `PC 2`, it will not have an icon.
4. If the exported instance is instead imported on `PC 1`, it will have the icon

From what I understand, Prism checks the /icons folder for the `IconKey`. Wouldn't it be sufficient for it to check `/instances/<instance_name>/icon.png` instead when explicitly importing zip files?

**Comment by Trial97** [comment]
@octanervoc what version are you using? 
I tried using both the latest develop and the 7.2 portable version and it works as expected for me.

**Comment by octanervoc** [comment]
@Trial97 I really should have given more information. Sorry about that.

System:    
```
Kernel: 5.15.0-86-generic x86_64 
bits: 64 
compiler: N/A 
Desktop: Xfce 4.16.0 
tk: Gtk 3.24.20 
wm: xfwm4 
dm: LightDM 
Distro: Linux Mint 20.3 Una
base: Ubuntu 20.04 focal
```

Qt: `apt policy qt5-default` returns:

```
qt5-default:
  Installed: (none)
  Candidate: 5.12.8+dfsg-0ubuntu2.1
  [...]
```

I'm using ` PrismLauncher-Linux-7.2-x86_64.AppImage`

**Comment by Trial97** [comment]
Can you post a minimal pack export that does that?

If not what export type are you using?(modrinth or prism)
Do you selectthe icon file to be exported with the pack?
