### ISSUE TITLE
Allow Search to show mods with only Alpha/Beta versions

### ISSUE THREAD

**Issue by Rosethorns** [PrismLauncher/PrismLauncher#3063]
### Role

Pack making and assembly

### Suggestion

Allow Search to show mods with only Alpha/Beta versions

### Benefit

Greater availability via search for pack makers who know what they are doing.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This feature should be an off by default option in Prisms settings, however those who choose to enable it will be shown search results for mods that only have beta/alpha results. (a current example as of writing of a mod that does not show up in search is Player Animator)

**Comment by Trial97** [comment]
Not fully possible: the curse/modrinth API do not expose that as a filter.
The best we can do right now (and is already implemented on nightly) is to add a filter that once you select a mod it will populate the versions list with only alpha or beta( but doesn't display only mods that have such version).

**Comment by Rosethorns** [comment]
Unfortunate, thank you. Seems like a suggestion I should make to those providers.
