### ISSUE TITLE
Allow Prism to update mods from outside the specific instance version

### ISSUE THREAD

**Issue by Rosethorns** [PrismLauncher/PrismLauncher#3064]
### Role

Pack making and assembly

### Suggestion

Allow Prism to update mods from outside the specific instance version

### Benefit

QoL for those who are aware of mixing mods of different MC versions

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Filtered search allows the user to download mods from outside of the MC version. For example on a 1.21.1 instance the user can use the launcher mod search to search and download any version of a mod from a specific version (for example 1.21.0)

However the launcher will then not update mods from outside the instance version leaving the user who downloaded the mod through prism to either delete the mod and redownload it to update. Or manually seek out the mod page to update the mod.

This appears to be an inconsistency in user experience (availability vs maintenance) and resolving this would greatly improve QoL for those who are aware of inter version operation.

**Comment by Trial97** [comment]
I know you can play with mods from different loaders([Sinytra Connector](https://modrinth.com/mod/connector)), but what benefit would you have to update a mod to a mc version different than the one the instance is?
I do not know any mod that would be playable if the mc version is different.

If the mod is compatible with other versions but is not reported in the provider(like in your example is for 1.21.0 but also compatible with 1.21.1) then this is an issue on that mod/provider.

Right now the behavior of update mods is a follows: try to get the latest version of the mod for the current loader and mcVersion if there is one then prompt the user, if not just ignore the mod.

In comparison other launchers, like Modrtinth refuse to update the mods downloaded with a different mcVersion.

**Comment by Rosethorns** [comment]
I suppose the issue is, if the onus is on the author to update their tags then the likelihood they will do so with user reminders MIGHT work but it might also drive authors insane.

Meanwhile if the mod exists on a database, and Prism already clearly recognises that users should have the option to filter for "out of version" mods in that database, that it is a much smaller and more automated step for Prism to then continue its update maintenance service for that mod which was already aquired through Prism.
