### ISSUE TITLE
Crash with segfault when attempting to load a mod from the modrinth api that has a release which is missing the `files` array

### ISSUE THREAD

**Issue by solonovamax** [PrismLauncher/PrismLauncher#307]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 5.0-develop, commit `318f657c31f95d8dda37fd9b21771f073e4409a2`

### Version of Qt

Qt 5.15.6

### Description of bug

Crash when attempting to download mod, if the response from the modrinth api contains an empty `file` array.

### Steps to reproduce

Launch prism launcher
Create an mc instance with fabric/quilt, on the latest version of minecraft
Go to the "Mods" page
Select "Download mods"
Change the "Filter options" to include "Any version"
Search "Oh My Minecraft Client"
Upon clicking on "Oh My Minecraft Client", the launcher will crash with a segmentation fault:
```
   62.544 D Download succeeded: "https://api.modrinth.com/v2/search?offset=0&limit=25&query=oh my&index=relevance&facets=[[%22categories:quilt%22,%22categories:fabric%22],[%22project_type:mod%22]]"
   62.544 D Task "NetJob(Modrinth::Search)" succeeded
   90.721 D [HttpMetaCache] Saving metacache with 20 entries
  104.158 D "Loading Modrinth mod versions"
  104.158 D Task "NetJob(ModVersions(oQgSAEhD))" starting for the first time
  104.158 D "Loading Modrinth mod info"
  104.158 D Task "NetJob(oQgSAEhD::GetProject)" starting for the first time
  104.158 D Task "Net::Download(0x55570f9a9cf0)" starting for the first time
  104.158 D Downloading  "https://api.modrinth.com/v2/project/oQgSAEhD"
  104.160 D Task "Net::Download(0x55570f9ae8b0)" starting for the first time
  104.160 D Downloading  "https://api.modrinth.com/v2/project/oQgSAEhD/version?game_versions=[]&loaders=[%22quilt%22,%22fabric%22]"
  104.252 D Download succeeded: "https://api.modrinth.com/v2/project/oQgSAEhD"
  104.252 D Task "NetJob(oQgSAEhD::GetProject)" succeeded
  104.253 D Loading mod info
  104.357 D Download succeeded: "https://api.modrinth.com/v2/project/oQgSAEhD/version?game_versions=[]&loaders=[%22quilt%22,%22fabric%22]"
  104.357 D Task "NetJob(ModVersions(oQgSAEhD))" succeeded
Segmentation fault (core dumped)
```

### Suspected cause

This is caused by attempting to query element 0 from an empty array.

If the modrinth api returns a response containing an empty `files` array:
```json
{
    "id": "NyI18WXo",
    "project_id": "oQgSAEhD",
    "author_id": "UmS2fiql",
    "featured": false,
    "name": "0.3.1-1.17.1",
    "version_number": "0.3.1-1.17.1",
    "changelog": "",
    "changelog_url": null,
    "date_published": "2021-07-13T18:06:48.858754Z",
    "downloads": 0,
    "version_type": "release",
    "files": [],
    "dependencies": [],
    "game_versions": [
        "1.17.1"
    ],
    "loaders": [
        "fabric"
    ]
}
```
then, prism will attempt to look up element 0 in this array, and segfault.

The cause of the issue is right here: https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/modplatform/modrinth/ModrinthPackIndex.cpp#L148-L164

In the file, it states:
```cpp
// Find correct file (needed in cases where one version may have multiple files)
// Will default to the last one if there's no primary (though I think Modrinth requires that
// at least one file is primary, idk)
// NOTE: files.count() is 1-indexed, so we need to subtract 1 to become 0-indexed
```

However, this is false, and can be seen when requesting a version such as `NyI18WXo`: `https://api.modrinth.com/v2/version/NyI18WXo` (This is contained in the request for `https://api.modrinth.com/v2/project/oQgSAEhD/version?game_versions=[]&loaders=[%22quilt%22,%22fabric%22]`, which is what causes the crash).

The appropriate fix would be to just check the size of the array before querying it.
I won't PR myself, as I'm not up to date with c++ code style bc I'm not a c++ dev, and this is such a minor fix, it's not worth me spending 30 minutes to learn that lol

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
https://api.modrinth.com/v2/project/NyI18WXo/version doesn't seem to display anything anymore, I think it was a mistake on modrinth's side

**Comment by DioEgizio** [comment]
I got confirm from the modrinth team that this is indeed not supposed to happen

**Comment by solonovamax** [comment]
Whether or not it should happen, bad data from modrinth shouldn't segfault the launcher.

**Comment by txtsd** [comment]
Yea, malformed API responses should result in a normal error, not a segfault. We should fix this.
