### ISSUE TITLE
Prism Launcher crashing after trying do double click select mod which has no valid version

### ISSUE THREAD

**Issue by FeineKatze** [PrismLauncher/PrismLauncher#3075]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.0

### Version of Qt

Qt 6.7.3

### Description of bug

When I am in the mod menu to add mods (the modrinth mod page and fabric instance 1.21.3, don't know if taht matters) and I try to select a mod with double click (left) Prism crashes if the mod says "no valid version found"
On the curseforge page mods with "no valid version found" can still be double clicked to select and can be installed (which is also kind of a bug, i guess)

### Steps to reproduce

-open a (fabric) instance
-go in the mod adder menu
-try to double click a mod with "no valid version found" in the modrinth page
-launcher crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
can you see if is reproduced with the latest nightly version: https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop
As this sounds as: https://github.com/PrismLauncher/PrismLauncher/issues/3001 and it was already fixed

**Comment by shrapnelnet** [comment]
i'd be happy to give this a look. could you tell me the name of a mod that has an invalid version so i could reproduce this?

**Comment by Trial97** [comment]
I will reopen if the original user replies that is not fixed with the latest develop
