### ISSUE TITLE
Add an option for Discord RPC

### ISSUE THREAD

**Issue by Mohammad99X** [PrismLauncher/PrismLauncher#3078]
### Role

I use Prism Launcher

### Suggestion

Add it as a togglable option in the settings somewhere, maybe in the "Launcher" or "Java" tab, not sure what would be best

### Benefit

It would allow Instances launched through Prism to be detected by Discord, even without using Discord RPC mods

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Add an option for Discord RPC using this java argument
`-DAllowMcDiscordDetection=net.minecraft.client.main.Main`

I got it from [here](https://discord.com/channels/1031648380885147709/1118165588200657006/1285002727650234488) and also saw it mentioned differently [here](https://discord.com/channels/1031648380885147709/1118165588200657006/1204722514174017556), which lead me to giving it that name (AllowMcDiscordDetection) since I find it to be the clearest.

Also, apparently, Discord RPC mods, such as [CraftPresence](https://modrinth.com/mod/craftpresence), work properly for others without that argument, but for me, they don't unless I use it (idk why)

**Comment by Trial97** [comment]
Not gonna happen:  by adding that argument it allows Minecraft to be detected by Nvidia and that may cause other issues. See https://github.com/PrismLauncher/PrismLauncher/issues/1137#issuecomment-1629146459 for more discussions regarding that.
And as conclusion no we are not gonna add a button to automatically add that if there is a possibility to break users game, better done manually but the user.

**Comment by Mohammad99X** [comment]
welp
