### ISSUE TITLE
Broken Download Button

### ISSUE THREAD

**Issue by Coversboy** [PrismLauncher/PrismLauncher#3082]
### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.7.3

### Description of bug

The download button disappeared and won't come back even after a computer reboot/

### Steps to reproduce

1. downloading the modpack called terrafirmagreg
2. adding and removing a mod (might not recreate it)

### Suspected cause

No idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
You can enable/disable all the actions on that toolbar you just need to right click it and select/deselect what buttons are visible.

**Comment by Coversboy** [comment]
Thank you so much I guess I was just being a dumbass
