### ISSUE TITLE
Sharing mods

### ISSUE THREAD

**Issue by om3ga6400** [PrismLauncher/PrismLauncher#3092]
### Role

I play modded mincraft

### Suggestion

be abel to compile all the mods in my mods folder and send it to another user that can use that file and download all the mod skipping the upload step

### Benefit

makes sharing mods much faster

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
Why is exporting as a Modrinth or CurseForge modpack not sufficient for your use-case?

**Comment by om3ga6400** [comment]
> Why is exporting as a Modrinth or CurseForge modpack not sufficient for your use-case?

where do I export my mods as a modpack? if that requires me to upload stuff then that defeats the purpose

**Comment by Trial97** [comment]
Prism will never host mods/modpacks: this is a launcher.
The best option is to just share exported instances.
