### ISSUE TITLE
[SUGGESTION] Add check for missing dependencies in mod updater

### ISSUE THREAD

**Issue by Onako2** [PrismLauncher/PrismLauncher#3099]
### Role

I used the updater to update all my mods and [Remove Reloading Screen](https://modrinth.com/mod/rrls) had an update that requires [Forge Config API Port](https://modrinth.com/mod/forge-config-api-port) which wasn't downloaded by the updater and I had to manually download it

### Suggestion

The launcher should check if dependencies have been changed when updating the mods

### Benefit

Users don't need to manually download dependencies when updating. This would make the experience more smooth

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
Already there: under the update mods menu

**Comment by Onako2** [comment]
Oh, really?
Then why isn't it enabled by default?

**Comment by Trial97** [comment]
Because some other user requested it to not be: you still get the dialog if you have a dependency from curseforge but the mod that requested it is from modrinth.
