### ISSUE TITLE
Update the skins feature of the account to make choosing a skin that has been previously uploaded (or a default) easier

### ISSUE THREAD

**Issue by surfie** [PrismLauncher/PrismLauncher#311]
### Role

I use my account with my 3 children, all on the same PC, and all of whom want to use different skins (and mod lists). Switching to the default launcher just to change a skin seems silly.

### Suggestion

Either change the existing upload and delete a skin feature to allow for selection of the default/previously uploaded skins, or allow each individual instance to have its own "instance skin" that is uploaded at time of opening that instance.

### Benefit

It will allow less mucking around switching between applications just to change a skin, and allow for an easier time changing instances.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
I feel that this would make sense with #330; therefore I have "merged" the issues
