### ISSUE TITLE
Add an option to bulk import your skins from namemc

### ISSUE THREAD

**Issue by EyaeM** [PrismLauncher/PrismLauncher#3115]
### Role

General

### Suggestion

I want there to be a button to easily import your skins from namemc

### Benefit

it is easier to bulk import than to download each skin indivually and import them manually

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I have alot of skins i tend to use and would like a feature to import all my skins from my username in name mc
the way this would work is you put a Minecraft username and checks namemc (or any other service which saves old skin Idk anything else) for the skins and you get to choose which ones to import

**Comment by Trial97** [comment]
No: you can already do that with an external tool(if it is one), just add the downloaded files to the skins folder and the skin manager should pick them up.
