### ISSUE TITLE
Update resource packs

### ISSUE THREAD

**Issue by om3ga6400** [PrismLauncher/PrismLauncher#3116]
### Role

I play modded mincraft

### Suggestion

i want it to be able to update resource packs like im able to do with the mods

### Benefit

makes it so we dont need to redownload the packs 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
Already done in upcoming version

**Comment by om3ga6400** [comment]
> Already done in upcoming version

will the update also include all the other options that are currently mod-exclusive like change version?

**Comment by TheKodeToad** [comment]
Yes

**Comment by om3ga6400** [comment]
> Yes

yooooo

**Comment by om3ga6400** [comment]
> Yes

ok its been a bit and this still is not a feature

**Comment by om3ga6400** [comment]
> Already done in upcoming version

@TheKodeToad are you sure that this is already in an upcoming version?

**Comment by TheKodeToad** [comment]
Yes. I'm responsible. It will be out in 10.0.0.
