### ISSUE TITLE
qt6 causing issues

### ISSUE THREAD

**Issue by popcornman209** [PrismLauncher/PrismLauncher#3121]
### Operating System
Arch linux

### Version of Prism Launcher

brand new install, 9.1-1 from pacman and the newest from aur.

### Version of Qt

qt 6.8.0 and 6.7.2

### Description of bug

im trying to run the program and im getting the error that i need qt 6.7.2, i install said version and suddenly it requires 6.8.0, i install 6.8.0 and suddently it needs 6.7.2 again. im probably just understanding this very wrong but im just very confused. heres a copy past from terminal:

╰─❯ prismlauncher
prismlauncher: /usr/lib/libQt6Core.so.6: version `Qt_6.8' not found (required by prismlauncher)
prismlauncher: /usr/lib/libQt6Core.so.6: version `Qt_6.8' not found (required by /usr/lib/libQt6NetworkAuth.so.6)
╰─❯ sudo pacman -S qt6-base
resolving dependencies...
looking for conflicting packages...

Packages (1) qt6-base-6.8.0-1

Total Installed Size:  58.98 MiB
Net Upgrade Size:       2.65 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                                                 [############################################################################] 100%
(1/1) checking package integrity                                                                                               [############################################################################] 100%
(1/1) loading package files                                                                                                    [############################################################################] 100%
(1/1) checking for file conflicts                                                                                              [############################################################################] 100%
(1/1) checking available disk space                                                                                            [############################################################################] 100%
:: Processing package changes...
(1/1) upgrading qt6-base                                                                                                       [############################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
╰─❯ prismlauncher
Cannot mix incompatible Qt library (6.7.2) with this library (6.8.0)
fish: Job 1, 'prismlauncher' terminated by signal SIGABRT (Abort)

### Steps to reproduce

run the program on arch with qt 6.7.2 or 6.8.0 installed

### Suspected cause

most likely me not installing qt6 right honestly

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Prism is in arch extra already: https://archlinux.org/packages/extra/x86_64/prismlauncher/
You can use that not the aur version.
Also from what I see, it is more of an issue with your PC: try reinstalling prism

**Comment by popcornman209** [comment]
yeah ive tried reinstalling it a few times now, using both that version, and the aur version. neither work for me :/
im not exactly sure what to do to fix this

also forgot to mention, this happens on multiple of my arch installs across computers.
