### ISSUE TITLE
Installing optifine on prism launcher on linux mint 

### ISSUE THREAD

**Issue by Steakob97** [PrismLauncher/PrismLauncher#3126]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.8.0

### Description of bug

I'm trying to install optifine standalone on minecraft 1.7.2. I followed the steps in the guide for this, however attempting to extract the .jar file to any location results in the error message "minecraft version 1.7.2 not found, you need to start the version 1.7.2 manually once". I have already manually started it, but the message remains, and it refuses to extract. 

### Steps to reproduce

- Download optifine 1.7.2 Ultra F7 to a folder
- Run installer
- Choose file location to extract
- Press extract

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
This is not related to Prism Launcher. You must start Minecraft 1.7.2 in Minecraft's official launcher!
