### ISSUE TITLE
Option to Group Mods within an instance

### ISSUE THREAD

**Issue by mhGandhi** [PrismLauncher/PrismLauncher#3131]
### Role

I sometimes make modpacks and distribute them to my friends.

### Suggestion

I would like to be able to group content like mods or resource packks within the instance.

### Benefit

so I can indicate to people using my pack what set of mods do what

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Sometimes, my friends don't want to play with some client mods, and in that case it would be cool if there was some way to (manually) group the mods in the pack. For Example, a pack creator might have the groups "Necessary, Client Performance, Client Amenities", so the end user has a better idea of how they can modifey their experience themselves.

**Comment by Trial97** [comment]
Duplicate
