### ISSUE TITLE
Can't play any instance

### ISSUE THREAD

**Issue by NEVARLeVrai** [PrismLauncher/PrismLauncher#3133]
### Operating System

Windows

### Version of Prism Launcher

9.1

### Version of Qt

6.8.0

### Description of bug

Cant play any instances

### Steps to reproduce

import an instance and play
![image](https://github.com/user-attachments/assets/b37c3999-0052-43f7-adda-9fa8934a8350)
[message.txt](https://github.com/user-attachments/files/17893919/message.txt)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Xtuber14** [comment]
I use CachyOS (Arch Linux based) and i have the same issue here, probably something to do with forge because with Fabric and Vanilla it works without any issue. The only thing we can do is to wait, even using the latest commit (Nighly Build) it doesn't work.

**Comment by Xtuber14** [comment]
i opened the links manually and maybe it has something to do with cloudflare protection.

**Comment by ExistingExpert** [comment]
The forge site seems to be [down](https://status.minecraftforge.net/) (maven.minecraftforge.net). The only option seems to be to wait until they get it fixed.

**Comment by Xtuber14** [comment]
![immagine](https://github.com/user-attachments/assets/1ffc91fe-8176-474b-941b-23f5fae57d65)
Somehow i got it working but this happens.
Maybe waiting forge will fix it

**Comment by Trial97** [comment]
For more info regarding this https://discord.com/channels/1129059589325852724/1129077934330744882/1310250466415743068

**Comment by Trial97** [comment]
This should be fixed now as the forge maven was fixed.
I will close this, but let me know if you are still experiencing this.
