### ISSUE TITLE
Raspberry Pi 5 support

### ISSUE THREAD

**Issue by RlabsLLC** [PrismLauncher/PrismLauncher#3141]
### Version of Prism Launcher

Prisim launcher 9.0 and 9.1

### Version of Qt

QT 5

### Description of bug

Before Version 9.0, the Raspberry Pi 5 was able to run Minecraft. But now, it fails to create the window! I looked at the code before, and it said "No driver card, assuming GPU doesn't support 3D accereration. Bypassing..."

### Steps to reproduce

make the system be able to bypass the GPU check

### Suspected cause

Minecraft Java on Pi's for everybody... again!

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
Does it work with AppImage version ([download](https://github.com/PrismLauncher/PrismLauncher/releases/download/9.1/PrismLauncher-Linux-x86_64.AppImage))?

**Comment by RlabsLLC** [comment]
sorry, I did something to the Pi software making it not run the game. So, I
resolved the issue myself with a new flash of it.

**Comment by RlabsLLC** [comment]
Also, I better try that AppImage file to see if that works better. for my
primary raspbain drive
