### ISSUE TITLE
When removing mod remove all files/folder related to it

### ISSUE THREAD

**Issue by om3ga6400** [PrismLauncher/PrismLauncher#3153]
### Role

i want to have a clean instance without a bunch of random files

### Suggestion

Delete all files and folder related to a mod when deleting that mod

### Benefit

So theres not a bunch of random useless files in the instance

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by om3ga6400** [comment]
and also remove all dependencies required by it unless there required by other mods

**Comment by Kationor** [comment]
> Delete all files and folder related to a mod when deleting that mod

Not possible unless Prism just guesses what *might* be related. Definitely shouldn't be default behaviour, either.

**Comment by Trial97** [comment]
Not possible to automatically remove files generated by the mod.
The dependency stuff there is another issue open that requests that
