### ISSUE TITLE
Build Option for custom Minecraft Manifest

### ISSUE THREAD

**Issue by PublicVoidUpdate** [PrismLauncher/PrismLauncher#3161]
Minecraft's manifest is of course designed with x86/64 in mind, but for aarch64 i am SOL, i have a custom manifest intended for my architecture, but i need to slot it in in replacement to the version_manifest.json. Using the old Multimc launcher its as simple as a make config, but Multimc (or at least the one i tried) doesn't support Microsoft logins. Is there a build option for Prism that works the same? or a variable i could change in the code before compile?

**Comment by Trial97** [comment]
the version manifest should be the same as Multimc(as prism is a fork of it).
You may encounter the need to change your arch to match your operating system one(in Multimc that wasn't the case as it would only care about  x86/64).

Regarding login, PrismLauncher requires and will always require you to log in with at least one Microsoft account that owns the game before allowing you to play it. And no, we can't help you circumvent that, as that would violate the Minecraft TOS and possibly bring down the launcher itself.

**Comment by PublicVoidUpdate** [comment]
No i mean multimc only allows pre migration login, I own a Minecraft account, but it is tied to my microsoft which Multimc doesn't support. I did take a look at the cmake options and didn't find anything related to the Minecraft version manifest, is there a code reference i could change?

**Comment by Trial97** [comment]
Prism allows only Microsoft accounts( the migration accounts are no longer supported by Minecraft).

Regarding that create a instance> right click on it >edit>Version>Click on the component you want to change>Customize> Edit (should be now available).
That should open the file located at `/path/to/instances/<instance name>/patches/net.minecraft.json` (or the component you choose)
You can now edit that how you see fit. Other than that I do not know Multimc/Prismlauncher to be able to customize the Minecraft version stuff.
