### ISSUE TITLE
No instances launch - error code 2

### ISSUE THREAD

**Issue by computerfan0** [PrismLauncher/PrismLauncher#3162]
### Operating System

Linux Mint 22

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.8.0

### Description of bug

When I install an instance and try to start it, it returns to a console with output shown [here.](https://mclo.gs/MZHbXpb) This occurs for multiple instances. I have ensured that Java is installed. I am using the Flatpak version of the program on Linux Mint.

### Steps to reproduce

* Install the latest Flatpak version of the program through the Linux Mint software manager
* Install an instance of Minecraft
* Attempt to launch it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by maskersss** [comment]
![image](https://github.com/user-attachments/assets/7fa3017e-3784-426c-bb15-c22b7bac2f4f)

**Comment by computerfan0** [comment]
Thank you! Somehow the launcher ended up in offline mode despite me being connected to the internet. Logging into my Microsoft account again fixed the issue. A more clear indication would have been helpful.
