### ISSUE TITLE
Can't log in and can't run game

### ISSUE THREAD

**Issue by dah950** [PrismLauncher/PrismLauncher#3165]
### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.4.2

### Description of bug

Whenever I try to log into Microsoft, it takes me to the login page but Prism ignores the approval to log in. Also when I am finally logged in, I can't play the game. 

### Steps to reproduce

First issue: Click "add Microsoft", enter account info
Second issue: Open any Minecraft instance.

### Suspected cause

I did recently update from Ubuntu 22.04 to 24.04

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Sounds a bit like https://github.com/PrismLauncher/PrismLauncher/issues/2302
How is it different from that one?
Are you able to login?
