### ISSUE TITLE
Constant SIGSEGV errors crashing game on launch, regardless of modpack or game version

### ISSUE THREAD

**Issue by rabbitscreams** [PrismLauncher/PrismLauncher#3168]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt version 6.8.1

### Description of bug

loading up any minecraft instance that is modded, even with just a mod loader installed, will cause it to crash with a SIGSEGV error. the rate at which it crashes is not consistent but increases with the Minecraft version, with my tests on 1.7.10 crashing the least and 1.20.1 crashing very consistently. this could just be coincidence, though, as it crashes at random and most commonly during the startup process.

during the rare occasions where the instance starts fully to the menu screen, often attempting to load into world triggers the crash. sometimes, i am allowed to play for up to a few hours (though usually only minutes) before it crashes with a SIGSEGV. these crashes do not generate crash logs, only hs_errs, which i have a google drive folder of and can provide if asked for/needed.

additional information:
with the exception of my cobblemon packs and the vanilla-ish tests i did, all of these are modpacks i had no issue playing with at all prior to 9.1 (i cant recall what version i was using prior to this, unfortunately) and have many hours in several of them.

most of these hs_err logs were generated by me repeatedly opening and closing my test instances, and occasionally trying to open worlds. the hs_errs in the cobblemon packs are from a mix of opening the game and random crashes during attempted gameplay.

things i have tried:
installing different versions or sources of java
uninstalling and reinstalling prismlauncher
binary testing with mods in and out of a test instance

things i have not tried yet:
creating a fresh instance and putting the mods and save data into it
installing mods directly into the minecraft i have on my computer and testing mods there

MORE INFO ABOUT MY MACHINE:
Distro: Linux Mint 21.1 Vera
CPU: 13th Gen Intel Core i7-13700K
GPU: NVIDIA GA106 [GeForce RTX 3060 Lite Hash Rate]
GPU driver: NVIDIA driver 550
RAM: 31.2 GB
Prismlauncher Source: Flatpak at the Software Manager

### Steps to reproduce

unsure if this is reproducable on other machines but:

step 1: download any version of minecraft, put any modloader on it (mods not required)
step 2: attempt to launch
step 3: explode into SIGSEGV hell

### Suspected cause

i have been undergoing issues with my CPU that could be linked to this, as 13th gen Intel cards have been found to have issues and mine was manufactured before these issues were caught and patched, but it may also be an issue of 9.1 not working properly with my device

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by rabbitscreams** [comment]
if this isnt the place to ask, or you know a better place to ask around about it, feel free to let me know. i would prefer not to join any discords if possible

**Comment by Trial97** [comment]
This sounds more like a Java issue: your game starts but segfaults.
If you think it was introduced in 9.1, you can try reproducing this with [older releases](https://github.com/PrismLauncher/PrismLauncher/releases).
However, Minecraft crashes are usually not related to the launcher.
I do not know exactly what may cause this but you can also try to open a thread in the Prism discord server: https://discord.com/channels/1031648380885147709/1032130809055940690

**Comment by rabbitscreams** [comment]
i actually should have mentioned i see "libjvm" the most during these errors in the original post. honestly, being pointed to the idea that its a java issue is already way more helpful than everything else ive looked at this past week. i will do some testing on mojang's launcher and with older versions of prism and come back with updates

**Comment by rabbitscreams** [comment]
so ive done some testing:

i loaded up prismlauncher 8.4 and put my most problematic child on it: my cobblemon forge modpack. the first two times, loaded up like a dream. no errors, i could play without any crashes, even while doing things that normally invoke crashes like opening inventory, switching tools, walking, using waystones, or interacting with cobblemon. i closed both these instances after about an hour of gameplay and reopened them to see if it wasnt a fluke, and i was at first pretty convinced that maybe i had cured my issue. 
the third time, however, the SIGSEGV came for me and has been ruining my life all day since.

as for vanilla minecraft from the official mojang launcher: i attempted to load up the latest version, 1.21.4, and what do you know. SIGSEGV also arrived here.

i've trawled duckduckgo for as many arrangements of "SIGSEGV minecraft linux mint" as i can on this issue. so i can only conclude that it must be my java that is gravely ill and not prismlauncher, like you suggested. sorry for wasting y'all's time, i'll see what i can glean from the linux mint forums about this. feel free to close this issue or leave it open. i can come back and leave an update with a link to the forum thread if the issue gets solved there in case other people get the same problems if you'd prefer

**Comment by brisingraerowing** [comment]
Are you using the Mojang Java distribution? I also have segfaults with it, except in game with certain mods. I switched Prism to use Adoptium and the crashes went away.

**Comment by rabbitscreams** [comment]
@brisingraerowing i have tried switching java versions and distributions, from adoptium to azul to back to mojang. unfortunately i think this is a hardware issue for me unless the java versions im getting ahold of are somehow also affecting the vanilla minecraft launcher, which also crashes with SIGSEGV.

ive tested at least 6 or 7 different solutions so far and no fruit has been borne (the linux mint forum folks are VERY patient and helpful), but if i ever narrow down the issue or find the solution, i will update this thread with that information. my running theory is its due to my faulty CPU OR its a category 10 user error.

**Comment by brisingraerowing** [comment]
Hm. Yeah, probably a hardware issue then. That's annoying.

**Comment by rabbitscreams** [comment]
so i've narrowed down the problem; to all those on this thread from the future who are having SIGSEGV plague your life, and youre using an intel 13th or 14th gen CPU, **make sure your BIOS is updated**. it wont cure the problem 100% but it will triage the CPU's overvolting issues until youre able to get a new one. now granted, my SIGSEGV was due to hardware problems, so if yours is for a different reason, this may not help as much, but its always worth it to keep things updated especially when using hardware known to be faulty.

if you want the full readup on what i did to solve this, here's the linux mint forum thread. otherwise, godspeed to all of you dealing with SIGSEGV. not an easy issue to troubleshoot.
https://forums.linuxmint.com/viewtopic.php?t=435840
