### ISSUE TITLE
Replace the Icon for modpacks imported from .mrpack files with the default Grass Block

### ISSUE THREAD

**Issue by Arbee4ever** [PrismLauncher/PrismLauncher#317]
### Role

I use Prism Launcher to launch Modpacks

### Suggestion

When importing a modpack from a .mrpack file, it should use the default Grass Block icon, because .mrpacks can be distributed from anywhere and are not certainly endorsed by modrinth.

### Benefit

Doesn't associate every modpack from whichever Source with modrinth

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://user-images.githubusercontent.com/45911516/198361416-360d5488-5e06-466b-95e3-6e7c7c8e8b88.png)
As Prospector states in the message above, in the modrinth Discord Server, not all .mrpack's should be affiliated with Modrinth. (Side note: I made a Suggestion for modrinth to add an Icon field to .mrpack files, so they can have custom Icons in the Future)

**Comment by Fjox** [comment]
id like to point out the fact that mrpack was created by modrinth so it makes sense to give them the modrinth icon
