### ISSUE TITLE
Add support for FTB www.feed-the-beast.com mod packs

### ISSUE THREAD

**Issue by thisishalloweentek** [PrismLauncher/PrismLauncher#3180]
### Role

I would like to play FTB mod packs since they have been removed from CurseForge

### Suggestion

I want Prism to add support to install mod packs from Feed The Beast website feed-the-beast.com.

### Benefit

To play the latest FTB mod packs since FTB official packs have been removed from CurseForge

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

For example: the 1.20 DireWolf20 mod pack has been removed from CurseForge. The mod packs must be downloaded from feed-the-beast.com using the FTB app.
https://www.feed-the-beast.com/modpacks/119-ftb-presents-direwolf20-120
https://www.curseforge.com/minecraft/search?page=1&pageSize=20&sortBy=relevancy&class=modpacks&search=direwolf20

The latest version of FTB mod packs are being posted to feed-the-beast.com first. Not sure if they are being delayed to CurseForge, or not coming over at all.
Example: FTB Evolution is 1.4.1 on FTB, and 1.3.0 on CurseForge.
https://www.feed-the-beast.com/modpacks/125-ftb-evolution?tab=versions
https://www.curseforge.com/minecraft/modpacks/ftb-evolution/files/all?page=1&pageSize=20

**Comment by idiot-shinuki** [comment]
Hi, I'm no contributor or anything. But I don't think what you're asking for is possible due to conflicts with the license FTB modpacks are under. I do believe the only way to download a FTB modpack is through the FTB app, but after you've downloaded it, when you click "Add Instance" in the top left of your Prism Launcher, you can import modpacks you've already downloaded through the FTB app using the "FTB App Import" button on the left side. Hope this helps!

**Comment by Trial97** [comment]
We had that in the past, and it was requested to be removed from the launcher. Read this: https://prismlauncher.org/news/ftb-removal/
As mentioned by [idiot-shinuki](https://github.com/idiot-shinuki)  we added the possibility of importing FTB APP instances (you need to download the packs using the [FTB App](https://www.feed-the-beast.com/ftb-app) then in prism you can Import it in the 'FTB App Import') no there is no way to update the packs imported(it was requested on another GH issue)

**Comment by thisishalloweentek** [comment]
Ok, thank you for the context. I missed that this function was intentionally removed. I will give the import option a try.

**Comment by furtabs** [comment]
> We had that in the past, and it was requested to be removed from the launcher. Read this: https://prismlauncher.org/news/ftb-removal/ As mentioned by [idiot-shinuki](https://github.com/idiot-shinuki) we added the possibility of importing FTB APP instances (you need to download the packs using the [FTB App](https://www.feed-the-beast.com/ftb-app) then in prism you can Import it in the 'FTB App Import') no there is no way to update the packs imported(it was requested on another GH issue)

the new FTB ceo is fine if yall add this back

**Comment by Trial97** [comment]
> the new FTB ceo is fine if yall add this back

Without him or somebody else from FTB side contacting us about this Prism will not add that back. Similar on how we were contacted to take it down we expect them to notify us if we can add it back.
The world of a random internet person is not enough for this.

**Comment by furtabs** [comment]
Atlauncher added it back
