### ISSUE TITLE
Mod updater prefers older Quilt-tagged version of mod over newer version tagged only with Fabric

### ISSUE THREAD

**Issue by malSet** [PrismLauncher/PrismLauncher#3182]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.8.0

### Description of bug

On a Quilt instance, the mod updater seems to prefer the latest version of a mod that's tagged with Quilt over a later version that's tagged with only Fabric (despite Quilt having compatibility with Fabric). This prevents automatically updating some mods and could cause users to accidentally downgrade mods.

### Steps to reproduce

1. Create a Quilt 1.20.1 instance.
2. Download the current latest instance of Trinkets for 1.20.1 (3.7.2) from Modrinth.
3. Download version 1.7.16 of Spectrum from Modrinth.
4. Check for updates on both Trinkets and Spectrum.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is intended:
If a mod has both quilt and fabric alternatives for a given Minecraft version, the launcher would prioritize the ones that are the same as the instance loader.
In this case, the launcher has no idea that the new fabric version is still compatible with the quilt. If it is, the mod author should have marked it as such.
Here is the issue that was solved by this behavior: https://github.com/PrismLauncher/PrismLauncher/issues/818
