### ISSUE TITLE
Add a toggle/filter for showing only uninstalled mods/resourcepacks/shaders/datapacks when browsing them

### ISSUE THREAD

**Issue by Czekoloczek** [PrismLauncher/PrismLauncher#3190]
### Role

I often like to add new mods that i don't have installed

### Suggestion

I want to have a filter to view only mods that i don't have installed yet

### Benefit

Because it's easier to download new mods that aren't installed yet + less scrolling

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

When I have a quick look at the mod list, it's sometimes quite hard to see which mod is installed and which isn't, especially when there's 1 mod that isn't installed, and it's in between mods that are installed

**Comment by Kationor** [comment]
Already a thing! (it's in the download dialog under filter options, at the very bottom)

**Comment by Czekoloczek** [comment]
oh i didn't see it, thx <3
