### ISSUE TITLE
Crash on quitting the game

### ISSUE THREAD

**Issue by RedstoneTrail** [PrismLauncher/PrismLauncher#3194]
### Operating System

Arch linux
uname -a:

> Linux arch 6.12.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 x86_64 GNU/Linux

### Version of Prism Launcher

9.1

### Version of Qt

6.8.1

### Description of bug

On quitting the game through the main menu, the game then crashes and freezes on the dirt background. The log output is always the same:

> A fatal error has been detected by the Java Runtime Environment:
> 
>  SIGBUS (0x7) at pc=0x0000730daa85163c, pid=90778, tid=90780
> 
> JRE version: OpenJDK Runtime Environment Microsoft-8035246 (17.0.8+7) (build 17.0.8+7-LTS)
> Java VM: OpenJDK 64-Bit Server VM Microsoft-8035246 (17.0.8+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
> Problematic frame:
> C  [libnvidia-glcore.so.565.57.01+0xa5163c]
> 
> Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/redstonetrail/.local/share/PrismLauncher/instances/2/.minecraft/core.90778)
> 
> An error report file with more information is saved as:
> /home/redstonetrail/.local/share/PrismLauncher/instances/2/.minecraft/hs_err_pid90778.log
> 
> If you would like to submit a bug report, please visit:
>   https://aka.ms/minecraftjavacrashes
> The crash happened outside the Java Virtual Machine in native code.
> See problematic frame for where to report the bug.
> 

### Steps to reproduce

Launch an instance and quit the game. (playing on 1.19.2)

### Suspected cause

Something between prismlauncher and the nvidia gpu driver, I have tried launching the game using the integrated graphics on my laptop and through the official minecraft launcher and using an unmodded instance.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
not a launcher issue

**Comment by ChickenIQ** [comment]
Add "__GL_THREADED_OPTIMIZATIONS=0" to your environment variables, it should fix it.

**Comment by RedstoneTrail** [comment]
That seems to have fixed it, thanks!
