### ISSUE TITLE
Mod updater doesn`t load 

### ISSUE THREAD

**Issue by meronicly** [PrismLauncher/PrismLauncher#3200]
### Operating System

Windows

### Version of Prism Launcher

9.1

### Version of Qt

6.7.3

### Description of bug

Trying to update mods and it doesn`t load anything.
Mod browser and Modrinth site seems to be working.
![Screenshot 2024-12-13 160052](https://github.com/user-attachments/assets/5db9476f-d77d-4d28-bfc5-6adf47e95a84)

### Steps to reproduce

- Open Prism
- Edit instance
- Select mods
- Click Check For Updates

### Suspected cause

I don`t know what may be causing this

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by meronicly** [comment]
After cleaning mods index this error appears
![Screenshot 2024-12-13 160709](https://github.com/user-attachments/assets/3d305ef8-8f39-4b8f-833e-42d17dab7287)

**Comment by Trial97** [comment]
https://status.modrinth.com/ modrith is down
