### ISSUE TITLE
Default download for 64bit portable is MinGW-w64 build instead of MSVC build?

### ISSUE THREAD

**Issue by TonyAki** [PrismLauncher/PrismLauncher#3207]
### Role

I'm installing Prism Launcher

### Suggestion

Change default download for 64bit portable to MSVC build

### Benefit

So that users are directed to the more stable build

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Hi,

For 9.1, the [official Prism Launcher download page](https://prismlauncher.org/download/windows/) presents four main options for Windows:

- 64bit installer
- 64bit portable
- ARM64 installer
- ARM64 portable

Of these, all of them point to the GitHub download for their respective MSVC builds, except for the 64bit portable option which points to the download page for [the MinGW-w64 build](https://github.com/PrismLauncher/PrismLauncher/releases/download/9.1/PrismLauncher-Windows-MinGW-w64-Portable-9.1.zip).

Given that the page suggests that MinGW-w64 builds are less tested (and thus that MSVC builds are probably more stable), I'm wondering whether this is intentional? The GitHub releases page _does_ have [an MSVC build](https://github.com/PrismLauncher/PrismLauncher/releases/download/9.1/PrismLauncher-Windows-MSVC-Portable-9.1.zip) for 64bit portable, should the download button not point to that instead?

**Comment by Trial97** [comment]
this is intended

**Comment by Kationor** [comment]
To give a bit more detail than "this is intended": #2879

**Comment by TonyAki** [comment]
Thanks both for the answer, and apologies for the duplicate! (I did search though Issues before posting but didn't think to search Discussions)

A quick follow-up question: I'm using the "Portable" version just so that I can install all of Prism on a different internal drive (my games drive, G: – rather than in AppData which is on the C: drive), but I'm not planning on actually moving the program's files around at all, they will stay right where they are (as will the C: drive with the Visual C++ installation on it). In this case presumably it's fine to use the 64bit Portable MSVC build, right?

Thanks :)
