### ISSUE TITLE
CurseForge import does not catch all mods that are disallowed from being auto-downloaded, leading to broken/incomplete modpacks

### ISSUE THREAD

**Issue by Frontear** [PrismLauncher/PrismLauncher#321]
### Operating System

Windows 10

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

When downloading a modpack from curseforge, some mods do not allow a client to auto download them. Prism catches this and opens the links for you so that you can download and copy-paste them yourself, however I have noticed that with Medieval MC, the latest version will _consistently_ miss some mods (notably the deeperanddarker mod), and will _not_ mention it. Although it seems to be installed, it does not function in any way unless manually reinstalled. This issue does not occur with any other client that allows curse importing, making me believe it is unique to Prism.

### Steps to reproduce

Create Instance
Select CurseForge
Select Medieval MC 1.19.2, v9
Attempt to run mod, check Modlist in-game for Deeper and Darker
It does not load, nor will it exist in game

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by staviq** [comment]
Wait, I've seen this,

For me, the deeperdarker mod was downloaded but the file was invalid so it didn't load properly and didn't show ingame

Check if you have the mod file physically in the mod folder, and compare the file size with one downloaded from curseforge  manually

**Comment by Frontear** [comment]
yep, thats my exact experience. i believe it installed the wrong mod file, or maybe it was broken idk, but it caused problems. other launchers correctly identified it as a mod that couldnt be auto-downloaded, and had me open a browser to download

**Comment by flowln** [comment]
The issue here is that, noticing that the mod was blocked on CF, we try to search for the same mod on Modrinth, and in this case we found a match. However, on Modrinth it actually downloaded the wrong file (it downloaded the one for Forge instead of the one for Fabric). So, the Fabric Loader couldn't identify the mod itself when loading the game, and so it acted as if the mod didn't exist.
