### ISSUE TITLE
HTTP 400 from Modrinth when trying to update mods

### ISSUE THREAD

**Issue by StShAzzy** [PrismLauncher/PrismLauncher#3211]
### Operating System

Windows

### Version of Prism Launcher

PrismLauncher 9.1

### Version of Qt

Qt 6.7.2.0

### Description of bug

updating mods from Modrinth returns HTTP 400

### Steps to reproduce

- Install any number of mods for 1.12.2
  - Then attempt to updating said mods

### Suspected cause

might be something to do with being Minecraft's version 1.12.2 as trying to update a list of mods from 1.21.4 worked just fine

![error](https://github.com/user-attachments/assets/c3b751dc-818d-408c-9c86-183bc6415a2f)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
First that is not `HTTP 400` second this days Modrith reported some outrages.
https://status.modrinth.com/
![image](https://github.com/user-attachments/assets/eb9131f7-d634-410b-9e21-e747d12c497a)
Is this error still happening now?

**Comment by StShAzzy** [comment]
> First that is not `HTTP 400` 

    10.681 D | [launcher.task.net.upload]: "{16e4c744-8627-4494-b310-9af5f3763dc7}" Runninng  "https://api.modrinth.com/v2/version_files"
    10.950 C | [launcher.task.net.upload]: "{16e4c744-8627-4494-b310-9af5f3763dc7}" Failed "https://api.modrinth.com/v2/version_files" with reason QNetworkReply::ProtocolInvalidOperationError
    10.950 C | [launcher.task.net.upload]: "{16e4c744-8627-4494-b310-9af5f3763dc7}" HTTP Status 400 ;error "Error transferring https://api.modrinth.com/v2/version_files - server replied: "
    10.950 D | [launcher.task.net.upload]: "{16e4c744-8627-4494-b310-9af5f3763dc7}" Request failed in previous step: "https://api.modrinth.com/v2/version_files"

it was HTTP 400
also still happens, just tested

**Comment by Trial97** [comment]
Ok looking a bit the mod https://www.curseforge.com/minecraft/mc-mods/betterfps doesn't exist on modrinth: you get the retry dialog. But on nightly that dialog no longer appears (it was removed in a previous PR) 
So the fact that Modrinth returns 400 is not a bug.
PS. Curseforge also doesn't recognize it either for some weird reason(but the update meta works with other mods so I will say is something on curse side)
