### ISSUE TITLE
Modpacks not launching.

### ISSUE THREAD

**Issue by Jilmoire** [PrismLauncher/PrismLauncher#3213]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.8.1

### Description of bug

After trying to launch an instance of Nomifactory or Skyfactory 4 modpack, the log will open and give an error: Process crashed with exit code 6.

This applies to curseforge or atlauncher selection.

### Steps to reproduce

1. Add instance of Skyfactory 4 or Nomifactory (or any modpack).
2. After the launcher does its job in gathering the required resources, launch the instance.
3. Wait for a while and the process will crash.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Jilmoire** [comment]
https://mclo.gs/MkxaONM

Link to the log if needed

**Comment by Trial97** [comment]
This doesn't look like a launcher issue. Because this is flatpak  it may be caused by missmatched drivers or something.

**Comment by maskersss** [comment]
maybe helpful

![IMG_20241216_135302](https://github.com/user-attachments/assets/22814e93-d770-4fc7-bf6b-3183671f0faa)

**Comment by Jilmoire** [comment]
> maybe helpful
> 
> ![IMG_20241216_135302](https://github.com/user-attachments/assets/22814e93-d770-4fc7-bf6b-3183671f0faa)
> 

Thank you for the idea!
Maybe if i try to install the mods manually with configs and other things? I'll try it when I have time
