### ISSUE TITLE
auto file verification

### ISSUE THREAD

**Issue by holden93274** [PrismLauncher/PrismLauncher#3229]
### Role

when I replace a file in \PrismLauncher\libraries\com\mojang\authlib, when I run MC  the file is being reinstalled

### Suggestion

I want to check the check box for files.

### Benefit

I can put whatever I want on and it will work.

### This suggestion is unique

- [ ] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

add a check mark for auto-check so that you can replace the files in prism and that it does not reinstall them.

**Comment by Trial97** [comment]
Nope
