### ISSUE TITLE
Homebrew Support

### ISSUE THREAD

**Issue by finlayjn** [PrismLauncher/PrismLauncher#323]
### Role

I want to install Prism Launcher through Homebrew

### Suggestion

Prism Launcher should have a Homebrew cask

### Benefit

This would improve compatibility with and ease of installation on macOS

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Suggestion is pretty self explanatory. MinecraftMachina's ManyMC had a Homebrew cask and since this ManyMC has merged with Prism it would be great to see this feature.

Thanks for continuing the project!

**Comment by ryanccn** [comment]
https://formulae.brew.sh/cask/prismlauncher

**Comment by DioEgizio** [comment]
prismlauncher already is on brew

**Comment by finlayjn** [comment]
Wow that's embarrassing, I must be blind. Appreciate the responses!
