### ISSUE TITLE
Mod Filter "Hide Installed Items" Does Not Hide Mods Installed With Modpacks

### ISSUE THREAD

**Issue by Llohgun** [PrismLauncher/PrismLauncher#3236]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.7.3

### Description of bug

Clicking the "Hide installed items" under Modrinth filter options does not hide mods installed with a premade modpack. Seemingly works correctly for mods installed outside of the modpack.

Example: Downloading "Better F3" for the modpack "Fabulously Optimized" only hides Better F3, and none of the mods already downloaded with Fabulously Optimized.

### Steps to reproduce

 - Edit downloaded modpack
 - Mods
 - Downloaded mods
 - Filter options
 - Hide installed items

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
The mods need to have metadata. For modapacks installed before 9.x the mods metadata was not generated when the modpack was imported. So it should work if you create a new instance or you manually update the instance mods.

**Comment by Llohgun** [comment]
Ah! That makes sense, thank you.
