### ISSUE TITLE
profile problem

### ISSUE THREAD

**Issue by werym** [PrismLauncher/PrismLauncher#3238]
### Version of Prism Launcher

9.1

### Version of Qt

6.7.3

### Description of bug

i was omw to play some minecraft on prism l because i had trouble signing in curseforge because it said that i dont own the game on this account even tho i played before without the game, same thing here i cant play cuz its askingme for profile with bought minecraft even tho this is a cracked launcher if im not mistaking, i cant play my game in peace, help asap

### Steps to reproduce

ion know whats that srry

### Suspected cause

i really dont know, it happened on curseforge too witch i could play minecraft on before too, ive tried different accs but it doesnt work, please help i wana play

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
THis is not a cracked launcher

**Comment by werym** [comment]
dont have to be so rude

**Comment by werym** [comment]
atleast recommend some cracked ones? i really do wana play

**Comment by Trial97** [comment]
We don't tolerate piracy!
Prism Launcher has always been legal, legitimate & appropriate. We don't and never will have features such as offline login without an official account.
