### ISSUE TITLE
pressing shift to move stacks of items does not work in MC 1.5.2

### ISSUE THREAD

**Issue by detscadosu24** [PrismLauncher/PrismLauncher#3241]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.2.4

### Description of bug

pressing shift to move items between the inventory, hotbar, chest, creafting table, furnace, etc. does not work.
crouching does work, and I have tried enabling and then disabling touchscreen mode. this issue is present only in MC 1.5.2, and it is not present with other launchers. I tried launching the latest version of MC using Prism and the issue is not present. Using Ubuntu 24.04.1 LTS

### Steps to reproduce

press shift to move stacks of items between the inventory and hotbar, using Ubuntu 24.04.1 LTS and MC 1.5.2

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Not a launcher issue

**Comment by detscadosu24** [comment]
it only happens with Prism launcher, SKLauncher works fine...
