### ISSUE TITLE
Filter Mods List

### ISSUE THREAD

**Issue by ShadowTech99001** [PrismLauncher/PrismLauncher#3247]
### Role

Sorting through mods in general

### Suggestion

I want a way to filter your mods list into showing client sided mods or server sided mods apart

### Benefit

Easier way of seeing which mods you can update that are client side without not being able to join a server with a modpack.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
There is a column already that gives you that information (you may need to enable it by right clicking on the table header)

**Comment by ShadowTech99001** [comment]
Didn't even know that existed! Thanks
