### ISSUE TITLE
Automatic backup of screenshots and saves

### ISSUE THREAD

**Issue by Ghost-chu** [PrismLauncher/PrismLauncher#3251]
### Role

I play both vanilla and modded Minecraft

### Suggestion

Automatic backup of screenshots and saves

### Benefit

I play a lot of instances of Minecraft, both Vanilla and Modded, and it would be great if Prism Launcher could support this!

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

For me, saves and screenshots are an important part of my nostalgia for the past, but sometimes cleaning up an instance accidentally deletes the saves and screenshot files it contains, and disk corruption can lead to irreversible and permanent loss of this data. Backing up an entire instance would contain a lot of unnecessary files, so it would be nice to be able to back up this data separately.  
Prism Launcher, as a multi-instance launcher, is the perfect entry point for maintaining these files. It would be great if these files could be backed up regularly (e.g. once every 7 days) to a USB storage device or OneDrive, Prism Launcher just needs to do the basic per-instance file copying (or go one step further and compress the saves when backing them up).

**Comment by Trial97** [comment]
This was proposed already so close as duplicate
