### ISSUE TITLE
when i play a single player world it crashes every time i press the escape key or even head to that menu

### ISSUE THREAD

**Issue by bryso703** [PrismLauncher/PrismLauncher#3258]
### Version of Prism Launcher

prism launcher version 8.4

### Version of Qt

i dont know

### Description of bug

i expected the game to play fine and not crash when i pressed esc key and delete my inventory and replace it with what i had in it before loading onto the world again and duping whats in my chest if i put stuff from other things like shulkers into other chest they dupe 

### Steps to reproduce

i played i click esc key crash error code -1  only happens in single player

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Not launcher issue.
Also do not complain about issues on versions that are not maintained anymore(only the latest version of prism is maintained;at the moment 9.1)
