### ISSUE TITLE
Useless translation strings on Weblate

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#326]
### Role

I translate PrismLauncher to Russian

### Suggestion

Delete lines that have the same exact translation / do not require translation

### Benefit

No more useless warnings on Weblate

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Some lines do not require translation, but are still visible on Weblate
Here is a link to translations into Russian, but there may be more in other languages:
https://hosted.weblate.org/translate/prismlauncher/launcher/ru/?q=has:dismissed-check

Direct links to strings (from Weblate):
1. https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/minecraft/MinecraftInstance.cpp#L898
2. https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/ui/pages/global/MinecraftPage.h#L62
3. https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/ui/pages/modplatform/ModPage.cpp#L348
4. https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/ui/pages/modplatform/modrinth/ModrinthPage.cpp#L278
5. https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/ui/pages/modplatform/modrinth/ModrinthPage.h#L62
6. https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/ui/dialogs/NewComponentDialog.ui#L37
7. https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/ui/pages/modplatform/VanillaPage.ui#L200
8. https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/ui/pages/modplatform/VanillaPage.ui#L210
9. https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/ui/pages/modplatform/VanillaPage.ui#L220
10. https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/ui/pages/modplatform/VanillaPage.ui#L230

**Comment by Scrumplex** [comment]
Some languages might translate some of those. E.g. Minecraft has a Chinese translation

**Comment by ethanwillis** [comment]
Yea I think the problem here is that it's "seeing" that the source language and target language typically use different character sets. Like if it was transliterated into the cyrillic character set to be Микрософт I think it would "think" that it is translated.
