### ISSUE TITLE
Allow for multiple custom themes

### ISSUE THREAD

**Issue by Rafii2198** [PrismLauncher/PrismLauncher#327]
### Role

I play modded minecraft.

### Suggestion

Multiple user-made themes in the launcher instead of one custom entry

### Benefit

Remove the need for manual replacing of files if one wants to change a theme

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Instead of just having one custom folder, I think it would be better if possible for the launcher to scan all folders in the `theme` category and each valid theme would be added into the launcher's theme selection box.

**Comment by forkiesassds** [comment]
#149

**Comment by Rafii2198** [comment]
I always forget to check pull requests, apologies!
