### ISSUE TITLE
Automatic Java Switching.

### ISSUE THREAD

**Issue by LividJava** [PrismLauncher/PrismLauncher#335]
### Role

Playing Modded minecraft across various game versions

### Suggestion

The ability for Prism launcher at instance creation, to determine the game version you are using, automatically set the correct Java version if present, and if not prompt the user to install the correct java version by means appropriate for the context (IE point windows users to java website or point linux users to their package manager)

### Benefit

Allows a One-Click installation setup for the End user with minimal friction regarding the management of multiple Java versions (really it saves like 30 seconds).

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

As it stands presently. Prism Launcher will just let you launch an instance using the default settings. Which is okay if you were ever only going to run the latest version. But as with most people who download instance managers, We run wildly varying versions of Minecraft which require different versions of Java to be installed.

I'm not asking to automatically download java, Just if various versions are present. to automatically switch to the appropriate java based on the game version you are running. This removes some friction for users who are unaware and just click play, and wonder why its not working.

**Comment by timoreo22** [comment]
Planned in #285

**Comment by LividJava** [comment]
Ahh! i didn't see the PR wouldn't have opened this otherwise. I'll leave it open unless someone else closes it.
