### ISSUE TITLE
GNOME Prism Launcher not responding

### ISSUE THREAD

**Issue by Lobo6780** [PrismLauncher/PrismLauncher#339]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 5.0 Flatpak version

### Version of Qt

Qt 5.15.6

### Description of bug

When you launch instance of your Minecraft (in my case 1.19.2) I get two times info that Prism Launcher is not responding, but after I click wait launcher is working as it should work. I get this info two times and it stops showing again to next instance launch, I cannot reproduce it on KDE Plasma, GNOME version 43.0.

### Steps to reproduce

1. Launch Prism Launcher.
2. Start instance of Minecraft.
3. When Minecraft is loading you will get information on screen that Prism Launcher is not responding.
4. Click wait and the same second info will show, click wait and enjoy your game.

### Suspected cause

It looks like it's only present on GNOME DE, on KDE I never got that error.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by AshtakaOOf** [comment]
This happens on most Minecraft launcher's that I have ever used on gnome.
I don't think this can be fixed, since gnome is just not detecting any movement in the game for a moment.
So basically this is not a Prism bug but more a Minecraft java + gnome bug.

**Comment by ghost** [comment]
You can change the `not responding` timeout (default is 5 seconds)

```bash
gsettings set org.gnome.mutter check-alive-timeout 10000 #10 seconds
```

**Comment by Lobo6780** [comment]
> You can change the `not responding` timeout (default is 5 seconds)
> 
> ```shell
> gsettings set org.gnome.mutter check-alive-timeout 10000 #10 seconds
> ```

Thanks! I will check that!
