### ISSUE TITLE
Use the current activity and media focus!

### ISSUE THREAD

**Issue by PaxJaromeMalues** [PrismLauncher/PrismLauncher#34]
### Role

Survival

### Suggestion

Setup Sponsor and Patreon immediately

### Benefit

Use the current flow to build a base for future crowd support, this chance will not come back that soon

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Sorta unique. Linked to #22

**Comment by Scrumplex** [comment]
We have OpenCollective now: https://opencollective.com/prismlauncher
