### ISSUE TITLE
Setting to allow switching accounts based on instance

### ISSUE THREAD

**Issue by Thanos1716** [PrismLauncher/PrismLauncher#341]
### Role

I use multiple Minecraft accounts

### Suggestion

I suggest the addtion of a tab, or similar in an instances settings page, to allow specifying a specific account override (like the java settings)

### Benefit

This would save me a lot of time in waiting for my heavily modded instances to launch and then realising that I'm using the wrong acount

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I often accidentally launch an instance with the wrong account after playing on another instance where I need to use a different account. This is annoying, especially when I only realise after logging into my server and being at spawn, and although I could probably set a prelaunch command to fix this, I would much rather a native implementation :)

**Comment by byteduck** [comment]
I've been wanting the same thing. I'm not at all familiar with this codebase, but I may poke around sometime and submit a PR to add this :)

**Comment by byteduck** [comment]
I've submitted a PR #685 with this implemented!

**Comment by flowln** [comment]
This got implemented in #685 and will be available in the next stable version!
