### ISSUE TITLE
Custom Curseforge modpacks requiring Quilt doesn't automatically install quilt

### ISSUE THREAD

**Issue by jacekjarosz55** [PrismLauncher/PrismLauncher#343]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 5.15.6

### Description of bug

My custom modpack (made in packwiz), when exported as a curseforge package and imported, installs all of the mods except the quilt loader itself. Fabric on the other hand doesn't have this issue.

### Steps to reproduce

* Create a modpack in packwiz
* Select 'quilt' as the mod loader
* Export as curseforge package
* Import the modpack in prism launcher

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
The CurseForge modpack format doesn't support quilt at all. Packwiz puts the quilt word like it was forge or fabric, but the format doesn't support it
