### ISSUE TITLE
Minecraft 1.19.2 not launching with Java 19, but is compatible with it (tested with MultiMC).

### ISSUE THREAD

**Issue by enderprism** [PrismLauncher/PrismLauncher#344]
### Role

I play Minecraft 1.19.2 with Fabric mods.

### Suggestion

I want the launcher to mark Java 19 as "compatible" with Minecraft 1.19.x.

### Benefit

so users of Arch Linux and Arch-based distros like me can use Minecraft 1.19 without needing to use an "old" version of Java (Java 17 or Java 18 in this case).

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
Java 19 is known to have broken some mods

**Comment by enderprism** [comment]
Thanks for the answer. Could it be possible to indicate this in the console when trying to launch Minecraft with Java 19 instead of just saying that we need to modify the Java version? I didn't know this, as none of my mods break with Java 19.

**Comment by Scrumplex** [comment]
Just use Java 17 if you are on Arch, as that's a LTS release

**Comment by TayouVR** [comment]
> so users of Arch Linux and Arch-based distros like me can use Minecraft 1.19 without needing to use an "old" version of Java (Java 17 or Java 18 in this case).

you may still use java 19 if you wish, you need to head to the instance settings and enable "Disable Java Compatibility Checks"

maybe we could change the warning text to add something along the lines of `If you know your version will work, {click here to disable the java compatibility checks|go to instance settings -> "Disable Java Compatibility Checks"}`

**Comment by enderprism** [comment]
> > so users of Arch Linux and Arch-based distros like me can use Minecraft 1.19 without needing to use an "old" version of Java (Java 17 or Java 18 in this case).
> 
> you may still use java 19 if you wish, you need to head to the instance settings and enable "Disable Java Compatibility Checks"

I already knew about the "disable compatibility checks" option and I am using it.

> maybe we could change the warning text to add something along the lines of `If you know your version will work, {click hereto disable the java compatibility checks|go to instance settings -> "Disable Java Compatibility Checks"}`

Yes! That's what I was looking for.

**Comment by ghost** [comment]
I can run minecraft fine with java 19(no warnings)
I have `skip java compatibilty checks` disabled 🤔

**Comment by ghost** [comment]
@Scrumplex Are you supposed to get a warning window if you are using java 19?

**Comment by Scrumplex** [comment]
I did enable Java 19 in our metadata a while ago, and it should work. If it doesn't, it's probably because you either don't use our official metadata server, or your cache is broken because of the PolyMC migration

**Comment by ghost** [comment]
> I did enable Java 19 in our metadata a while ago, and it should work

So are you saying java 19 suppose to work? If so that is correct, it works for me.
