### ISSUE TITLE
[Suggestion] Launch instance on double-click instead of single-click

### ISSUE THREAD

**Issue by zeroxoneafour** [PrismLauncher/PrismLauncher#345]
### Role

I like to configure my instances before starting them sometimes.

### Suggestion

Launch the instance on double-click instead of single click.

### Benefit

So I don't have to rush and hit the abort button before the instance launches and gets in the way of the window.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I'm pretty sure this used to be the default behavior, a while ago.

**Comment by ghost** [comment]
It already does that tho

**Comment by ghost** [comment]
It already does that tho

**Comment by zeroxoneafour** [comment]
It doesn't for me

**Comment by zeroxoneafour** [comment]
Never mind, had to do with a separate setting on my computer (kde plasma double-click)
