### ISSUE TITLE
CurseForge mods distributed as .zip get downloaded to the resourcepacks folder

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#349]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

When importing CF modpacks, some mods which are distributed as .zip files (e.g. Mo' Creatures, Custom Mob Spawner for 1.7.10) get downloaded to the resourcepacks folder instead of the mods folder.

### Steps to reproduce

1. Create a CurseForge modpack with e.g. Mo' Creatures 1.7.10
2. Import it to Prism
3. Click the "Folder" button and go to "resourcepacks"

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ryanccn** [comment]
https://github.com/PrismLauncher/PrismLauncher/blob/87b0d3fe11c1134bf17e1027fda7125f77e09821/launcher/modplatform/flame/PackManifest.cpp#L79-L85

hmm, I did make a heuristic that's supposed to fix this...

**Comment by DioEgizio** [comment]
> https://github.com/PrismLauncher/PrismLauncher/blob/87b0d3fe11c1134bf17e1027fda7125f77e09821/launcher/modplatform/flame/PackManifest.cpp#L79-L85
> 
> hmm, I did make a heuristic that's supposed to fix this...

Nope, here the problem is different

**Comment by DioEgizio** [comment]
mods aren't supposed to be in .zips, and since curseforge doesn't offer a simple way to check if something is a mod or a resource pack, we just check if it's a .zip to place in resourcepack

**Comment by Ryex** [comment]
Why not just double check .zip files by loading them as a `ResourcePack` and use `ResourcePackUtils::processZIP` to detect which it is? (I'm tracing the code paths on the `ModFolderModel` to come up with this and it gets a bit harry so I may be wrong here)

**Comment by DioEgizio** [comment]
> Why not just double check .zip files by loading them as a `ResourcePack` and use `ResourcePackUtils::processZIP` to detect which it is? (I'm tracing the code paths on the `ModFolderModel` to come up with this and it gets a bit harry so I mad be wrong here)

when that logic was created that thing didn't exist

**Comment by Ryex** [comment]
> > Why not just double check .zip files by loading them as a `ResourcePack` and use `ResourcePackUtils::processZIP` to detect which it is? (I'm tracing the code paths on the `ModFolderModel` to come up with this and it gets a bit harry so I may be wrong here)
> 
> when that logic was created that thing didn't exist

Ah, so it's a possible solution now?

**Comment by ryanccn** [comment]
Related to #336, we could also use that function to smartly identify whether a .zip is an instance or a resourcepack using this
