### ISSUE TITLE
Download mods and Check for Updates buttons don't become greyed out after launching an instance

### ISSUE THREAD

**Issue by Steveplays28** [PrismLauncher/PrismLauncher#35]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.4.1

### Version of Qt

Qt 6.3.0

### Description of bug

The "Download mods" and "Check for Updates" buttons don't become greyed out after launching the instance.

![image](https://user-images.githubusercontent.com/62797992/196432782-194b427b-afe3-4a27-addd-d4c1cbf97c0c.png)

You can see that the instance has been launched, but the two buttons on the right are not greyed out, even though they do nothing.

### Steps to reproduce

Go to the mods tab of an instance, and launch the instance. You should see the bug in action.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by aprilthepink** [comment]
I can work on that!

**Comment by Steveplays28** [comment]
Awesome! Was looking through the code and found this file, which is most likely where the issue is
https://github.com/PlaceholderMC/PrismLauncher/blob/develop/launcher/ui/pages/instance/ModFolderPage.cpp#L67-L113

**Comment by aprilthepink** [comment]
@Steveplays28 okay so, I build from source and I didn't encounter this issue.

**Comment by ghost** [comment]
Fuck no. We have enough buttons grayed out; if an action does not break the game while it's running, it should be avaivable to the user.

**Comment by aprilthepink** [comment]
> Fuck no. We have enough buttons grayed out; if an action does not break the game while it's running, it should be avaivable to the user.
A) Why the swearing.
B) if you are saying this you probably don't know what the updating of a mod while the mod is executed does to the client..

**Comment by ghost** [comment]
> > Fuck no. We have enough buttons grayed out; if an action does not break the game while it's running, it should be avaivable to the user.
> > A) Why the swearing.
> > B) if you are saying this you probably don't know what the updating of a mod while the mod is executed does to the client..

I know: it does nothing. the mod is pre-loaded.
And I'm not even talking this button; the issue is so prominent in the launcher overall - it doesn't even let you open the mods directory while the instance is running.
Adding resource packs or worlds on runtime is literally absolutely supported by the game and should not be disallowed by the launcher. Adding mods on runtime won't do anything.
The settings tab gets entirely removed, though those settings only apply on startup and won't ever do anything in changed on runtime.
And there are a lot more examples you can see.

**Comment by aprilthepink** [comment]
> > > Fuck no. We have enough buttons grayed out; if an action does not break the game while it's running, it should be avaivable to the user.
> > > A) Why the swearing.
> > > B) if you are saying this you probably don't know what the updating of a mod while the mod is executed does to the client..
> 
> I know: it does nothing. the mod is pre-loaded. And I'm not even talking this button; the issue is so prominent in the launcher overall - it doesn't even let you open the mods directory while the instance is running.

Not true

> Adding resource packs or worlds on runtime is literally absolutely supported by the game and should not be disallowed by the launcher. Adding mods on runtime won't do anything.

The launcher isn't disallowing adding resource packs

> The settings tab gets entirely removed, though those settings only apply on startup and won't ever do anything in changed on runtime. And there are a lot more examples you can see.

These are startup settings, and if you wanna change them you need to restart minecraft anyways for them to apply.

**Comment by Steveplays28** [comment]
> @Steveplays28 okay so, I build from source and I didn't encounter this issue.

@CutestNekoAqua Ah cool, I'm on 1.4.1 which is slightly outdated so maybe it was already fixed. I'll download a build and test it on my end as well. Thanks!
