### ISSUE TITLE
Is it safe to transfer files and config files from PolyMC to PrismLauncher?

### ISSUE THREAD

**Issue by jdev082** [PrismLauncher/PrismLauncher#350]
So I heard of some questionable things happening with PolyMC and switched to PrismLauncher. Am I safe if I copied all the files in appdata (C:\Users\Jayden\AppData\Roaming\PolyMC) to the PrismLauncher folder?

**Comment by Scrumplex** [comment]
Yep should be fine. There might be issues with some caching stuff though, so make sure to delete `metacache` `cache` and `meta` files and folders.

Also verify that the metadata server in your "APIs" setting points to `https://meta.prismlauncher.org/v1/` (the default when empty)

**Comment by jdev082** [comment]
I have deleted both `cache` and `meta` folders but can't seem to find a `metacache` folder. I have also verified that the API in use is `https://meta.prismlauncher.org/v1`
