### ISSUE TITLE
Make Auto-Detect for Java also look inside the launchers folder

### ISSUE THREAD

**Issue by flleeppyy** [PrismLauncher/PrismLauncher#355]
### Role

.

### Suggestion

Search the PrismLauncher directory for Java instances

### Benefit

So local java runtimes show up in the auto-detect window, and it make's it easier instead of having to browse, find the prismlauncher folder, go to your jre folder, double click a bunch of stuff (aka I'm lazy)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Maybe have a dedicated folder for JRE's that polymc can search through, instead of cluttering up your prismlauncher folder with a bunch of java sdks and runtime. 

I use an old laptop with an Intel Graphics 4000, and some modpacks will just not run with some version of Java, so I have to pick different old versions of Java.

**Comment by theofficialgman** [comment]
What is this issue asking for that doesn't already exist? If you have a `java` folder in your prismlauncher directory, that already gets searched (on Linux)

https://github.com/PrismLauncher/PrismLauncher/blob/d89a541a8d6837b0010eac2e638914acfbb3c374/launcher/java/JavaUtils.cpp#L448-L449

**Comment by flleeppyy** [comment]
> 



> What is this issue asking for that doesn't already exist? If you have a `java` folder in your prismlauncher directory, that already gets searched (on Linux)
> 
> https://github.com/PrismLauncher/PrismLauncher/blob/d89a541a8d6837b0010eac2e638914acfbb3c374/launcher/java/JavaUtils.cpp#L448-L449

welp.... didn't know that. I thought it just searched folders outside of the launchers folder.

Maybe put a tip somewhere in the auto-detect windows that lets the user know they can create a java folder with all their java runtimes and the launcher will try to find the?
