### ISSUE TITLE
Mod icons in mod list

### ISSUE THREAD

**Issue by thornySoap** [PrismLauncher/PrismLauncher#356]
### Role

I don't play modpacks, but make my collection of mods per hand.

### Suggestion

What about showing the icons of mods in the list fetched from MOD.jar/\*.png or MOD.jar/assets/NAME/\*.png

### Benefit

Just easier to look at and manage

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ghost** [comment]
Should make it only show the icon when selecting a mod (like what it does with resource/texture packs)

![resource](https://user-images.githubusercontent.com/110736028/199062510-f2d1a0d3-08d1-411a-abc6-743389356cde.png)
