### ISSUE TITLE
Can't play online at all

### ISSUE THREAD

**Issue by Jorma17** [PrismLauncher/PrismLauncher#357]
Operating system
Windows 10

PrismLauncher version
5.0

Whenever I try to launch any instance, the launcher says "Please select your offline player name" even though I have an internet connection. When Minecraft launches, I can't play on any server and get the message "Invalid session (please try restarting your game and the launcher)" which doesn't help. Why doesn't it work? This is prob a Windows specific issue since it works on Linux for me.

**Comment by ghost** [comment]
happened to me on linux. restarting the launcher fixed it for me

https://github.com/PrismLauncher/PrismLauncher/issues/293 caused it i think

**Comment by mei1212123** [comment]
similar issue happened to me and I tried to re login but now I can't even login even after restarting the launcher

**Comment by Jorma17** [comment]
I just updated to 5.2 and it works now

**Comment by bendevnull** [comment]
After updating to 6.3, I'm having this issue once again. I'm on Windows 11, and allowing it through the firewall did not change my results. I've restarted my PC and my launcher several times to no avail. Checking the network activity through Task Manager shows that it is not using any network, despite being able to connect to the internet through other apps.

EDIT: This issue does not occur on the Linux build, and downgrading to 6.0 solved the issue on Windows for the time being.
