### ISSUE TITLE
Clicking modrinth or curseforge links from the mod downloader should load that mods page

### ISSUE THREAD

**Issue by Un1q32** [PrismLauncher/PrismLauncher#363]
### Role

I use the mod downloader

### Suggestion

I want curseforge and modrinth links to open in the mod downloader instead of the browser

### Benefit

Convinence

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
I don't understand, if you are on the mod downloader, you're already loading the mod??????

**Comment by Un1q32** [comment]
> I don't understand, if you are on the mod downloader, you're already loading the mod??????

![image](https://user-images.githubusercontent.com/57970114/199180604-712da387-6598-4676-b2df-2ce77bfd0228.png)
what i mean is if i click the cloth config link here i should view cloth config in the mod downloader instead of a web browser

**Comment by DioEgizio** [comment]
I don't think that's possible to detect, for example clicking mod links on the top of a mod would reopen the same mod?

**Comment by TheKodeToad** [comment]
I think they meant clicking on cloth config would jump to cloth config inside the mod download dialog as opposed to the user's web browser.

**Comment by TheKodeToad** [comment]
[Screencast from 2022-11-01 14-08-40.webm](https://user-images.githubusercontent.com/57493648/199253444-a0a98592-6442-4691-a04a-3177dd9cd169.webm)

Here is a (slightly hacky) implementation, and I did manage to get it to detect reopening the same mod. Maybe searching for the slug isn't ideal.

I couldn't work out how to switch the page though, so it can end up searching for the CurseForge slug on Modrinth and vice-versa.
