### ISSUE TITLE
Prism Launcher icon invisible in About Dialog

### ISSUE THREAD

**Issue by AmberIsFrozen** [PrismLauncher/PrismLauncher#364]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.1

### Version of Qt

Qt 6.4.0

### Description of bug

There should be an icon on top of **Prism Launcher**, which no longer exist in PrismLauncher 5.1
![image](https://user-images.githubusercontent.com/28094366/199225358-6537c391-6cb9-4ae7-ac68-0a6ffdf52c98.png)

### Steps to reproduce

* Open Prism Launcher
* Go to the About dialog

### Suspected cause

#342

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Relevant code: https://github.com/PrismLauncher/PrismLauncher/blob/04b39294ba012721279ca9d009f99f75178fd57a/launcher/ui/dialogs/AboutDialog.cpp#L147

**Comment by lemonzest79** [comment]
Can confirm on Linux AppImage also

**Comment by tobimori** [comment]
Can confirm on macOS.
<img width="797" alt="CleanShot 2022-11-01 at 18 49 49@2x" src="https://user-images.githubusercontent.com/29142128/199302970-5838bc0a-5873-44d4-b4f5-4e28249bfc79.png">

**Comment by fn2006** [comment]
Oh shit I broke this, sorry.

**Comment by Scrumplex** [comment]
> Oh shit I broke this, sorry.

And I approved :skull:
