### ISSUE TITLE
Add a way to update 2 instances that are the same modpack with Modrinth

### ISSUE THREAD

**Issue by stantios** [PrismLauncher/PrismLauncher#369]
### Role

I play as a Modded Minecraft user

### Suggestion

Add a dialogue for which instance to update. Even though the Modpack Updater GUI is coming in 6.0, currently it's annoying to update 2 instances that are the same modpack.

### Benefit

So, it's easier to update 2 instances that are the same modpack.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
https://github.com/PrismLauncher/PrismLauncher/pull/32 ?

**Comment by stantios** [comment]
> #32 ?

I know, and as I said in my original issue that there is a Modpack Update GUI coming in PrismLauncher 6.0, but it would be great if there could be atleast an option to select which instance to update.

**Comment by stantios** [comment]
Closed as #32 is nearly done and I realised there is no point as the modpack updater GUI is being introduced in 6.0.
