### ISSUE TITLE
FTB Installs on macOS install to a hidden directory.

### ISSUE THREAD

**Issue by Goobaroo** [PrismLauncher/PrismLauncher#375]
### Operating System

macOS

### Version of Prism Launcher

5.1

### Version of Qt

QT 6.3.0

### Description of bug

When installing FTB packs on macOS, the Minecraft directory created in the instance dir is a hidden directory `.minecraft`.

Renaming the directory manually still launches the pack so it seems that this would be a quality of life change.

### Steps to reproduce

Install a FTB pack with the current version of their installer.

### Suspected cause

I suspect this is a change in the FTB installer that is probably being invoked by PrismLauncher.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
> When installing FTB packs on macOS, the Minecraft directory created in the instance dir is a hidden directory .minecraft.

That's what we do everywhere

**Comment by Goobaroo** [comment]
I don't understand your response. Can you clarify?

**Comment by ghost** [comment]
> I don't understand your response. Can you clarify?

The Minecraft folder is always `.minecraft`. Not just for FTB

**Comment by Goobaroo** [comment]
Something has changed.  Normally installing a pack creates a directory containing the instance.cfg, mmc-pack.json and a visible minecraft directory without the leading period that hides it.

Installing for instance Vault Hunters from curse creates a standard Minecraft dir.
```
~/Library/Application Support/PrismLauncher/instances/Vault Hunters - Official Modpack
% tree -L 1
.
├── flame
├── instance.cfg
├── minecraft
├── mmc-pack.json
└── modlist.html
```

But a FTB based pack, creates a hidden one, making it harder to get to in order to copy in missing modpacks that have to be manually downloaded.
```
~/Library/Application Support/PrismLauncher/instances/FTB Presents Stoneblock 2
% tree -L 1 -a
.
├── .DS_Store
├── .minecraft
├── instance.cfg
└── mmc-pack.json
```

There already seems to be code when launching the pack to check for both `.minecraft` and `minecraft`.  I'm just suggesting at the end of install to rename the directory on the users behalf.

**Comment by ghost** [comment]
> Something has changed. Normally installing a pack creates a directory containing the instance.cfg, mmc-pack.json and a visible minecraft directory without the leading period that hides it.
> 
> Installing for instance Vault Hunters from curse creates a standard Minecraft dir.
> 
> ```
> ~/Library/Application Support/PrismLauncher/instances/Vault Hunters - Official Modpack
> % tree -L 1
> .
> ├── flame
> ├── instance.cfg
> ├── minecraft
> ├── mmc-pack.json
> └── modlist.html
> ```
> 
> But a FTB based pack, creates a hidden one, making it harder to get to in order to copy in missing modpacks that have to be manually downloaded.
> 
> ```
> ~/Library/Application Support/PrismLauncher/instances/FTB Presents Stoneblock 2
> % tree -L 1 -a
> .
> ├── .DS_Store
> ├── .minecraft
> ├── instance.cfg
> └── mmc-pack.json
> ```
> 
> There already seems to be code when launching the pack to check for both `.minecraft` and `minecraft`. I'm just suggesting at the end of install to rename the directory on the users behalf.

I think it's only curse forge that uses `minecraft` instead of `.minecraft` everything else (including vanilla) uses `.minecraft`

**Comment by Rags56** [comment]
I think we can close this issue

**Comment by Trial97** [comment]
Is this issue related to the removed FTB modpack support?

**Comment by Avakining** [comment]
> I think it's only curse forge that uses `minecraft` instead of `.minecraft` everything else (including vanilla) uses `.minecraft`

Not on macOS. The *vanilla launcher* uses `~/Library/Application Support/minecraft` not `~/Library/Application Support/.minecraft`.

As far as I've seen, only Prism (of the launchers I have) seem to use a hidden directory for its instance folder.
