### ISSUE TITLE
Failed to update quilt mod when one mod's quilt version and fabric version are hosted on the same page

### ISSUE THREAD

**Issue by arenekosreal** [PrismLauncher/PrismLauncher#386]
### Operating System

Linux

### Version of Prism Launcher

5.1

### Version of Qt

6.4.0

### Description of bug

If a quilt mod also has a fabric version, and both versions are hosted on the same page(like [wthit](https://www.curseforge.com/minecraft/mc-mods/wthit)), the launcher tries to download fabric version instead of quilt version.

### Steps to reproduce

- Find a quilt mod which can be upgraded and has a fabric version on the same page(like [wthit](https://www.curseforge.com/minecraft/mc-mods/wthit))
- Install the quilt mod  in a quilt instance
- Try upgrade it
- The launcher tries to upgrade to fabric version

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
if you're using cf, we don't support quilt on cf yet; if on modrinth, we just send the hashes to the api and say to check updates for both fabric and quilt

**Comment by tobfos2611** [comment]
I have the same issue when trying to update the Simple Voice Chat downloaded from here https://modrinth.com/mod/simple-voice-chat/version/quilt-1.19.3-2.3.21

**Comment by arenekosreal** [comment]
It seems that managing mods completely with the launcher can fix this. Just using the launcher for searching, downloading, installing and upgrading mods, at least it works on my game instances.
