### ISSUE TITLE
Better theming under KDE

### ISSUE THREAD

**Issue by hifinerd** [PrismLauncher/PrismLauncher#387]
### Role

I use Prism Launcher on Linux, using KDE.

### Suggestion

I want Prism Launcher to adhere to KDE's application theme.

### Benefit

To allow for a more consistent UI for KDE users.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I don't work with Qt, so there's probably some technical limitation as to why this can't be done, but since Prism relies on the Qt framework, and so does KDE, there should be a means for Prism to use the same application theme as KDE, to allow for a more consistent user experience.

**Comment by DioEgizio** [comment]
Use the qt5 build, we can't do magic, plasma doesn't support qt6 theming yet

**Comment by luluco250** [comment]
In case anyone comes to this issue looking for a fix, I ended up installing qt6ct on my Arch system and then globally setting `QT_QPA_PLATFORMTHEME=qt6ct` in `/etc/environment` + using a Kvantum theme, which supports QT6.

It doesn't seem to cause issues with KDE apps unlike qt5ct (although there is/was a patched version of it in the AUR with KDE fixes), so I get a nice consistent theme systemwide.
