### ISSUE TITLE
GUI looks uglier compared to PolyMC and the icon is gone

### ISSUE THREAD

**Issue by TheAirBlow** [PrismLauncher/PrismLauncher#388]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 5.1

### Version of Qt

Qt 6.4.0

### Description of bug

![image](https://user-images.githubusercontent.com/68467762/199817939-1513dcee-150e-4678-9c71-bbc11ee370c7.png)

### Steps to reproduce

I installed `prismlauncher-bin` from AUR, that's it

### Suspected cause

idk really

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Try prismlauncher-qt5-bin. KDE Plasma's theme does not support Qt 6 yet.

**Comment by TheAirBlow** [comment]
> Try prismlauncher-qt5-bin. KDE Plasma's theme does not support Qt 6 yet.

Very quick reply... And yeah it fixed the problem. You should probably tell about it on the website (including KDE version that doesn't support QT6)

**Comment by TheAirBlow** [comment]
@Scrumplex but why the icon is missing?

**Comment by DioEgizio** [comment]
> > Try prismlauncher-qt5-bin. KDE Plasma's theme does not support Qt 6 yet.
> 
> Very quick reply... And yeah it fixed the problem. You should probably tell about it on the website (including KDE version that doesn't support QT6)

We already have it

**Comment by DioEgizio** [comment]
https://prismlauncher.org/wiki/getting-started/installing-prismlauncher/#prism-launcher-isn't-using-my-system-theme

**Comment by TheAirBlow** [comment]
> https://prismlauncher.org/wiki/getting-started/installing-prismlauncher/#prism-launcher-isn't-using-my-system-theme

People usually just head to downloads and not the wiki

**Comment by theofficialgman** [comment]
> @Scrumplex but why the icon is missing?

@TheAirBlow icon missing is a bug in 5.1 (it was there in 5.0). it's already been fixed and will be coming to 5.2 or 6.0 release, whichever happens first
