### ISSUE TITLE
Set default Max Ram under the system Ram amount

### ISSUE THREAD

**Issue by theofficialgman** [PrismLauncher/PrismLauncher#390]
### Role

Users with 4GB and lower ram amounts exist

### Suggestion

change default max ram to be dynamic instead of hardcoded

### Benefit

users don't crash from not changing the ram amount from default when their actual system has 4GB of ram

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

the below should not be hardcoded to 4GB:
https://github.com/PrismLauncher/PrismLauncher/blob/2cf4d5f8ecd4afb1179b5a4e3bf694bcd359b628/launcher/Application.cpp#L569

this should be a function of the system ram (like already obtained in other parts of the codebase, eg: 
https://github.com/PrismLauncher/PrismLauncher/blob/a9d4370ad462b4ad3dd91f6bc38b40262967b5b2/launcher/ui/widgets/JavaSettingsWidget.cpp#L27

something like the below sudo-code would be nice for the default MaxMemoryAlloc that the user will see in the initial setup GUI:

```
if (Sys::getSystemRam() / Sys::mebibyte) < (4096 * 1.5); then
  MaxMemoryAlloc = Sys::getSystemRam() / Sys::mebibyte / 1.5
else
  MaxMemoryAlloc = 4096
fi
```

that will only set MaxMemoryAlloc to 4GB if the system ram is greater than 1.5X4GB (6GB). if the system ram is less than that, then it sets the default max to the system ram divided by 1.5

**Comment by jn64** [comment]
Does the official launcher do anything in this regard?

I imagine a significant portion of vanilla Minecraft players have low specs. The minimum requirements are 2GB and recommended 4GB. https://help.minecraft.net/hc/en-us/articles/4409225939853-Minecraft-Java-Edition-Installation-Issues-FAQ#h_01FFJMSQWJH31CH16H63GX4YKE

**Comment by theofficialgman** [comment]
> Does the official launcher do anything in this regard?

no, they just set xmx to 2GB and call it a day...

**Comment by jn64** [comment]
So for reference:

- Official launcher: 2GB
- [MultiMC: 1GB](https://github.com/MultiMC/Launcher/blob/301b44d1c437ea93089daa482008e08f4290127a/launcher/Application.cpp#L701) (which [we used until this year](https://github.com/PrismLauncher/PrismLauncher/commit/b19e3156154ba0dd232a3d165b1759c57e2858f2))
- [ATLauncher: roughly `min(RAM/2, 8GB)`](https://github.com/ATLauncher/ATLauncher/blob/956a50de485805e9cd5354584379c30e48158f51/src/main/java/com/atlauncher/data/Settings.java#L408)
