### ISSUE TITLE
Bypass Curseforge third-party lock

### ISSUE THREAD

**Issue by TheAirBlow** [PrismLauncher/PrismLauncher#394]
### Role

Modded modpack experience

### Suggestion

Is this section for people that didn't read the title?

### Benefit

No need for user to do something manually

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Public download URL is `https://www.curseforge.com/minecraft/mc-mods/{mod-id}/download/{file-id}`
Direct link URL is `https://mediafilez.forgecdn.net/files/{first-4-numbers-of-file-id}/{numbers-that-go-after}/{filename}`

As an example Kube Utils public download link is `https://www.curseforge.com/minecraft/mc-mods/kube-utils/download/4058552`, therefore the direct link is `https://mediafilez.forgecdn.net/files/4058/552/kube-utils-forge-0.1.3%2Bmc1.18.2.jar` (filename is URL-encoded)

**Comment by DioEgizio** [comment]
We can't do it because of cf's ToS

**Comment by TheAirBlow** [comment]
> We can't do it because of cf's ToS

oh shit

**Comment by jbalme** [comment]
Do it anyways. If they're already blocking half the mods on the site, just skip going through the API entirely, be just another user agent, and scrape everything.

Otherwise why bother supporting Curse mods in the first place? It just gives the illusion that Curse is an open platform.
