### ISSUE TITLE
Remove "couldn't find mod" prompt

### ISSUE THREAD

**Issue by Madis0** [PrismLauncher/PrismLauncher#395]
### Role

I use Prism Launcher to update mods

### Suggestion

Remove the "could not check or get..." prompt

### Benefit

The user does not need to know or care about this when they batch update the mods, they can't do anything about it anyway. You should only display this in some way if they are trying to update only that specific mod.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://user-images.githubusercontent.com/8611110/200017907-d0a241a6-7aad-4685-b664-4875cf93c44b.png)

**Comment by TayouVR** [comment]
I would say we should make it less intrusive. not get rid of it entirely.
E.g. the names of the mods could be highlighted in a color and on hover it could show the text it shows here.

**Comment by Frontear** [comment]
i disagree with this. a user would want to know if a mod cant be updated, as the functionality of updating all mods is, well, to be updated.

perhaps an alternative would be to mark certain mods as "do not update", that way the updater can skip them over, and it would functionally provide a better feature if certain people prefer an older version of a mod. it would additionally fix this as well by letting you mark your mod as such

**Comment by zjhendryx** [comment]
I agree with TayauVR and Frontear, in that we shouldn't get rid of it.
As an example useage where I certernly would want this notification: imagaine 1.20 is out, but some critical mods that I use haven't been updated for it yet. In that case, I would rather have Prism let know the problem - and then I as the user can make the choice as to if I wish to still load that instance with mods that might be broken or wait until they've been updated.

I would rather have something like Frontear's suggestion where there is some way to mark certain mods as being excluded from automatic updates, with maybe an option added anytime the client can't find metadata or update information for a mod for "exclude from automatic updates"?

**Comment by TheAirBlow** [comment]
> The user does not need to know or care about this when they batch update the mods, they can't do anything about it anyway. You should only display this in some way if they are trying to update only that specific mod.

This prompt would tell the user that the mod was not yet updated, so they don't continue with the operation, and in case some mod that adds some critical content is not yet updated the entire world may get fucked up. Please close this issue.
