### ISSUE TITLE
Show source in mod list

### ISSUE THREAD

**Issue by Madis0** [PrismLauncher/PrismLauncher#402]
### Role

I use Prism

### Suggestion

The mod list view could have another column for source - CurseForge, Modrinth or unknown  

### Benefit

So I can know if it was found in any platform and whether it can auto-update

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TechPro424** [comment]
+1
This feature would be really useful for people like me who are trying to move to Modrinth from CF
