### ISSUE TITLE
CLANG64 build : non-absolute msvc file 'api-ms-win-crt-runtime-l1-1-0.dll' returning type 'system'

### ISSUE THREAD

**Issue by djkcyl** [PrismLauncher/PrismLauncher#408]
I am trying to build prismlauncher myself, but after running `cmake --install build` with `CLANG64` I get a lot of warnings like `info: non-absolute msvc file 'api-ms-win-crt-time-l1-1-0.dll' returning type 'system'` and I can't start it.

I have installed `Windows 11 SDK` and `Universal Windows Platform Development` using Visual Studio Installer

![image](https://user-images.githubusercontent.com/59153990/200159929-74555960-9a63-4845-a4da-dccf9d3a06a3.png)
![image](https://user-images.githubusercontent.com/59153990/200160049-f1a99f6a-93ed-479d-b5ce-b5631c1b32c5.png)

**Comment by DioEgizio** [comment]
The warnings are normal, I don't know why is it failing to run but it should work

**Comment by DioEgizio** [comment]
about running the app, make sure you're running the one installed and not the one without the dependencies installed

**Comment by djkcyl** [comment]
> The warnings are normal, I don't know why is it failing to run but it should work

But it doesn't work, If I use `mingw32`, I don't have this problem

**Comment by djkcyl** [comment]
> about running the app, make sure you're running the one installed and not the one without the dependencies installed

I read this [guide](https://prismlauncher.org/wiki/development/build-instructions/#windows) performed the other steps in order without any problems

**Comment by DioEgizio** [comment]
> > The warnings are normal, I don't know why is it failing to run but it should work
> 
> But it doesn't work, If I use `mingw32`, I don't have this problem

That's because mingw32 doesn't use the ucrt. Anyways, I don't know why this issue happens, and it shouldn't, but since recently you can build with MSVC, so I would recommend doing that. We still have to update the build instructions

**Comment by djkcyl** [comment]
> > > The warnings are normal, I don't know why is it failing to run but it should work
> > 
> > 
> > But it doesn't work, If I use `mingw32`, I don't have this problem
> 
> That's because mingw32 doesn't use the ucrt. Anyways, I don't know why this issue happens, and it shouldn't, but since recently you can build with MSVC, so I would recommend doing that. We still have to update the build instructions

okey, thx! I'll try.

**Comment by TayouVR** [comment]
with mingw64 or clang64 it should just run from the install dir, if you wanted to run from the build dir you would need to do the install step at least once and grab all the dlls and folders and copy them in the build dir.
I build with mingw64 for the most part, though I might see how switching to msvc works. 

I have asked @TheLastRar to write some documentation for MSVC (and Visual Studio), to add to our build instructions and IDE/Tooling section

**Comment by djkcyl** [comment]
> with mingw64 or clang64 it should just run from the install dir, if you wanted to run from the build dir you would need to do the install step at least once and grab all the dlls and folders and copy them in the build dir. I build with mingw64 for the most part, though I might see how switching to msvc works.
> 
> I have asked @TheLastRar to write some documentation for MSVC (and Visual Studio), to add to our build instructions and IDE/Tooling section

but .... why?
![image](https://user-images.githubusercontent.com/59153990/200172862-e2793477-5f48-45a8-b857-6191a7bf9914.png)

**Comment by DioEgizio** [comment]
are you sure your git clone is updated?

**Comment by djkcyl** [comment]
> are you sure your git clone is updated?

yep, I've re-cloned many times, but it doesn't start properly.
`git clone --recursive https://github.com/PrismLauncher/PrismLauncher.git`

**Comment by DioEgizio** [comment]
Can you try running the exe from the command line and sending here what it says?

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/200173344-83b221f5-58d6-4d3c-8be9-1ca40c3f1438.png)

**Comment by TayouVR** [comment]
can you send a screenshot of that install folder? (can do `ls` too)

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/200173615-3e3016b7-b3a0-4a7f-a638-5129a752ccc7.png)
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2022/11/6     17:23                jars
-a----         2022/11/6     17:23          38171 libb2-1.dll
-a----         2022/11/6     17:23         144123 libbrotlicommon.dll
-a----         2022/11/6     17:23          55152 libbrotlidec.dll
-a----         2022/11/6     17:23         105784 libbz2-1.dll
-a----         2022/11/6     17:23          83390 libdouble-conversion.dll
-a----         2022/11/6     17:23         800273 libfreetype-6.dll
-a----         2022/11/6     17:23         145607 libgcc_s_dw2-1.dll
-a----         2022/11/6     17:23        1469995 libglib-2.0-0.dll
-a----         2022/11/6     17:23         161663 libgraphite2.dll
-a----         2022/11/6     17:23        1222115 libharfbuzz-0.dll
-a----         2022/11/6     17:23        1120784 libiconv-2.dll
-a----         2022/11/6     17:23       31266523 libicudt72.dll
-a----         2022/11/6     17:23        3321641 libicuin72.dll
-a----         2022/11/6     17:23        1950581 libicuuc72.dll
-a----         2022/11/6     17:23         147235 libintl-8.dll
-a----         2022/11/6     17:23          87452 libmd4c.dll
-a----         2022/11/6     17:23         356137 libpcre2-16-0.dll
-a----         2022/11/6     17:23         391497 libpcre2-8-0.dll
-a----         2022/11/6     17:23         262821 libpng16-16.dll
-a----         2022/11/6     17:23         262583 libquazip1-qt6.dll
-a----         2022/11/6     17:23        2224520 libstdc++-6.dll
-a----         2022/11/6     17:23          71838 libwinpthread-1.dll
-a----         2022/11/6     17:18            297 portable.txt
-a----         2022/11/6     17:23       28260297 prismlauncher.exe
-a----         2022/11/6     17:23              1 qt.conf
-a----         2022/11/6     17:23        8975205 Qt6Core.dll
-a----         2022/11/6     17:23         535924 Qt6Core5Compat.dll
-a----         2022/11/6     17:23       12158093 Qt6Gui.dll
-a----         2022/11/6     17:23        3038266 Qt6Network.dll
-a----         2022/11/6     17:23       10890723 Qt6Widgets.dll
-a----         2022/11/6     17:23         241316 Qt6Xml.dll
-a----         2022/11/6     17:23         125113 zlib1.dll
```

**Comment by DioEgizio** [comment]
this is clang64 right? Did you cmake --install ? I feel like you didn't -DCMAKE_OBJDUMP=/mingw64/bin/objdump.exe when configuring :/

**Comment by TayouVR** [comment]
huh
this is what it looks like for me (on mingw64, but should be roughly the same on clang64):
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        10/29/2022   5:34 PM                iconengines
d-----        10/29/2022   5:34 PM                imageformats
d-----        10/30/2022   7:48 PM                jars
d-----        10/30/2022   7:48 PM                platforms
d-----        10/29/2022   5:34 PM                styles
d-----        10/29/2022   5:34 PM                tls
-a----        10/29/2022   5:37 PM          34372 libb2-1.dll
-a----        10/29/2022   5:37 PM         143397 libbrotlicommon.dll
-a----        10/29/2022   5:37 PM          51852 libbrotlidec.dll
-a----        10/29/2022   5:37 PM          99146 libbz2-1.dll
-a----        10/29/2022   5:37 PM          70709 libdouble-conversion.dll
-a----        10/29/2022   5:37 PM         749498 libfreetype-6.dll
-a----        10/29/2022   5:37 PM         107699 libgcc_s_seh-1.dll
-a----        10/29/2022   5:37 PM        1354383 libglib-2.0-0.dll
-a----        10/29/2022   5:37 PM         154163 libgraphite2.dll
-a----        10/29/2022   5:37 PM        1111134 libharfbuzz-0.dll
-a----        10/29/2022   5:37 PM        1114369 libiconv-2.dll
-a----        10/29/2022   5:37 PM       31265798 libicudt72.dll
-a----        10/29/2022   5:37 PM        2916371 libicuin72.dll
-a----        10/29/2022   5:37 PM        1804704 libicuuc72.dll
-a----        10/29/2022   5:37 PM         136724 libintl-8.dll
-a----        10/29/2022   5:37 PM         424123 libjasper.dll
-a----        10/29/2022   5:37 PM         755631 libjpeg-8.dll
-a----        10/29/2022   5:37 PM          83137 libmd4c.dll
-a----        10/29/2022   5:37 PM         353858 libpcre2-16-0.dll
-a----        10/29/2022   5:37 PM         389729 libpcre2-8-0.dll
-a----        10/29/2022   5:37 PM         239942 libpng16-16.dll
-a----        10/29/2022   5:37 PM         239978 libquazip1-qt6.dll
-a----        10/29/2022   5:37 PM        2025245 libstdc++-6.dll
-a----        10/29/2022   5:37 PM         795793 libwebp-7.dll
-a----        10/29/2022   5:37 PM          24421 libwebpdemux-2.dll
-a----        10/29/2022   5:37 PM          76372 libwebpmux-3.dll
-a----        10/29/2022   5:37 PM          58109 libwinpthread-1.dll
-a----        10/30/2022   7:44 PM      318260366 prismlauncher.exe
-a----        10/30/2022   7:48 PM              1 qt.conf
-a----        10/29/2022   5:37 PM        8620285 Qt6Core.dll
-a----        10/29/2022   5:37 PM         511830 Qt6Core5Compat.dll
-a----        10/29/2022   5:37 PM       11495743 Qt6Gui.dll
-a----        10/29/2022   5:37 PM        3038821 Qt6Network.dll
-a----        10/29/2022   5:37 PM         595342 Qt6Svg.dll
-a----        10/29/2022   5:37 PM       10637516 Qt6Widgets.dll
-a----        10/29/2022   5:37 PM         229073 Qt6Xml.dll
-a----        10/29/2022   5:37 PM         119026 zlib1.dll
```
looks like some folders are missing

**Comment by djkcyl** [comment]
No, this is my new environment, clang64 is similar to it

**Comment by DioEgizio** [comment]
what environment

**Comment by djkcyl** [comment]
mingw32

> what environment

**Comment by DioEgizio** [comment]
> huh this is what it looks like for me (on mingw64, but should be the same on clang64):
> 
> ```
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> d-----        10/29/2022   5:34 PM                iconengines
> d-----        10/29/2022   5:34 PM                imageformats
> d-----        10/30/2022   7:48 PM                jars
> d-----        10/30/2022   7:48 PM                platforms
> d-----        10/29/2022   5:34 PM                styles
> d-----        10/29/2022   5:34 PM                tls
> -a----        10/29/2022   5:37 PM          34372 libb2-1.dll
> -a----        10/29/2022   5:37 PM         143397 libbrotlicommon.dll
> -a----        10/29/2022   5:37 PM          51852 libbrotlidec.dll
> -a----        10/29/2022   5:37 PM          99146 libbz2-1.dll
> -a----        10/29/2022   5:37 PM          70709 libdouble-conversion.dll
> -a----        10/29/2022   5:37 PM         749498 libfreetype-6.dll
> -a----        10/29/2022   5:37 PM         107699 libgcc_s_seh-1.dll
> -a----        10/29/2022   5:37 PM        1354383 libglib-2.0-0.dll
> -a----        10/29/2022   5:37 PM         154163 libgraphite2.dll
> -a----        10/29/2022   5:37 PM        1111134 libharfbuzz-0.dll
> -a----        10/29/2022   5:37 PM        1114369 libiconv-2.dll
> -a----        10/29/2022   5:37 PM       31265798 libicudt72.dll
> -a----        10/29/2022   5:37 PM        2916371 libicuin72.dll
> -a----        10/29/2022   5:37 PM        1804704 libicuuc72.dll
> -a----        10/29/2022   5:37 PM         136724 libintl-8.dll
> -a----        10/29/2022   5:37 PM         424123 libjasper.dll
> -a----        10/29/2022   5:37 PM         755631 libjpeg-8.dll
> -a----        10/29/2022   5:37 PM          83137 libmd4c.dll
> -a----        10/29/2022   5:37 PM         353858 libpcre2-16-0.dll
> -a----        10/29/2022   5:37 PM         389729 libpcre2-8-0.dll
> -a----        10/29/2022   5:37 PM         239942 libpng16-16.dll
> -a----        10/29/2022   5:37 PM         239978 libquazip1-qt6.dll
> -a----        10/29/2022   5:37 PM        2025245 libstdc++-6.dll
> -a----        10/29/2022   5:37 PM         795793 libwebp-7.dll
> -a----        10/29/2022   5:37 PM          24421 libwebpdemux-2.dll
> -a----        10/29/2022   5:37 PM          76372 libwebpmux-3.dll
> -a----        10/29/2022   5:37 PM          58109 libwinpthread-1.dll
> -a----        10/30/2022   7:44 PM      318260366 prismlauncher.exe
> -a----        10/30/2022   7:48 PM              1 qt.conf
> -a----        10/29/2022   5:37 PM        8620285 Qt6Core.dll
> -a----        10/29/2022   5:37 PM         511830 Qt6Core5Compat.dll
> -a----        10/29/2022   5:37 PM       11495743 Qt6Gui.dll
> -a----        10/29/2022   5:37 PM        3038821 Qt6Network.dll
> -a----        10/29/2022   5:37 PM         595342 Qt6Svg.dll
> -a----        10/29/2022   5:37 PM       10637516 Qt6Widgets.dll
> -a----        10/29/2022   5:37 PM         229073 Qt6Xml.dll
> -a----        10/29/2022   5:37 PM         119026 zlib1.dll
> ```
> 
> looks like some folders are missing

shouldn't be the same on clang64, e.g. on clang based msystems you should have libc++.dll, not libstdc++.dll.

**Comment by TheLastRar** [comment]
You are missing the various qt plugin folders

Did you specify a build type (Release/Debug) when you configured?

**Comment by djkcyl** [comment]
> shouldn't be the same on clang64, e.g. on clang based msystems you should have libc++.dll, not libstdc++.dll.

Please wait, I'll try again with clang64

**Comment by djkcyl** [comment]
> You are missing the various qt plugin folders
> 
> Did you specify a build type (Release/Debug) when you configured?

no
`cmake -Bbuild -DCMAKE_INSTALL_PREFIX=install -DENABLE_LTO=ON -DLauncher_QT_VERSION_MAJOR=6 -DCMAKE_OBJDUMP=/mingw64/bin/objdump.exe -G Ninja`

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/200174060-38c7c270-a4b2-4a18-854f-99b1defa80d1.png)

Can I use this step-by-step build?

**Comment by TheLastRar** [comment]
As of https://github.com/PrismLauncher/PrismLauncher/commit/f8ad1a052f78cb201aee3599214faa7ab644ee06, you need to specify `-DCMAKE_BUILD_TYPE=Release` or `-DCMAKE_BUILD_TYPE=Debug` when using Ninja or else the qt plugins won't get copied

It's something I didn't notice until recently

**Comment by djkcyl** [comment]
Okay, I'm trying

**Comment by DioEgizio** [comment]
> As of [f8ad1a0](https://github.com/PrismLauncher/PrismLauncher/commit/f8ad1a052f78cb201aee3599214faa7ab644ee06), you need to specify `-DCMAKE_BUILD_TYPE=Release` or `-DCMAKE_BUILD_TYPE=Release` when using Ninja or else the qt plugins won't get copied
> 
> It's something I didn't notice until recently

You mean -DCMAKE_BUILD_TYPE=Release or -DCMAKE_BUILD_TYPE=Debug ?

**Comment by TheLastRar** [comment]
Oh, woops, yeah I did, let me fix that

**Comment by djkcyl** [comment]
Like this?
`cmake -Bbuild -DCMAKE_INSTALL_PREFIX=install -DENABLE_LTO=ON -DCMAKE_BUILD_TYPE=Debug -DLauncher_QT_VERSION_MAJOR=6 -DCMAKE_OBJDUMP=/mingw64/bin/objdump.exe -G Ninja`

**Comment by DioEgizio** [comment]
Yes

**Comment by djkcyl** [comment]
thx, it`s working.
![image](https://user-images.githubusercontent.com/59153990/200174810-1409a188-9a3c-40d8-a6f8-6ec0dbe25fb5.png)
