### ISSUE TITLE
Crash when clicking on Bushy Biomes Resource Pack

### ISSUE THREAD

**Issue by RuiNtD** [PrismLauncher/PrismLauncher#409]
### Operating System

Windows

### Version of Prism Launcher

Occurs on both Prism Launcher 5.1 and 6.0-develop (126bbd67f7bdeb26905520a068d8dc1968f2659c)

### Version of Qt

Qt 6.4.0

### Description of bug

Clicking on the [Bushy Biomes](https://modrinth.com/resourcepack/bushybiomes) resource pack in an instance's "Resource packs" list causes Prism Launcher to crash

### Steps to reproduce

* Create a new 1.19.2 instance
* Download the [Bushy Biomes RP](https://modrinth.com/resourcepack/bushybiomes/version/2.2) to the instance's `resourcepacks` folder
* Edit the instance and go to the "Resource packs" list
* Click on "BuhsyBiomesV2.2" (misspelled lol)

### Suspected cause

I believe this may be happening when Prism tries to render the information panel at the bottom of the window.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
Backtrace:

[backtrace.txt](https://github.com/PrismLauncher/PrismLauncher/files/9945438/backtrace.txt)

**Comment by RuiNtD** [comment]
No longer crashing on Prism Launcher 6.0, but it does silently fail to load the icon.
