### ISSUE TITLE
Name suggestion

### ISSUE THREAD

**Issue by TheOPtimal** [PrismLauncher/PrismLauncher#41]
### Role

PrismLauncher is a sort of a long name, and doesn't follow the "Multiple" theme of previous forks

### Suggestion

Replace PlaceholderMC/PrismLauncher with OmniMC. 

### Benefit

It keeps in line with the "Multiple" theme (Multi, Poly)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Evrey** [comment]
I think Prism is an LGBTastic pun, for the most prominent use for prisms is to split a ray of white light up into a rainbow. So let’s keep it. This one’s multiplicativity lies in diversity.

However, i do agree that »PrismLauncher« is a mouthful and misses the block game connection. We could roll with »PrismMC« instead. Though really i’m fine with PrismLauncher.

**Comment by TheOPtimal** [comment]
I like that it's an LGBT pun, but it still feels sort of out of place for me, OmniMC fits better in my opinion. What about PanMC? Fits with the "Multiple" theme and also works as an LGBT-inspired name.

**Comment by Evrey** [comment]
If anything, given the twice now fork history, maybe it’s not the best idea to embrace the old naming convention. Also »omni« and »pan« mean »all«, not »many«, so these two suggestions are already technically out of tradition. And PrismMC/PrismLauncher has the better potential for a nice logo. Like a blocky rainbow shooting out of a triangular glass block.

**Comment by TheOPtimal** [comment]
> If anything, given the twice now fork history, maybe it’s not the best idea to embrace the old naming convention. Also »omni« and »pan« mean »all«, not »many«, so these two suggestions are already technically out of tradition. And PrismMC/PrismLauncher has the better potential for a nice logo. Like a blocky rainbow shooting out of a triangular glass block.

Ooh, what if the class block also looked like Prismarine? I'll fire up Inkscape

**Comment by Infinidoge** [comment]
I don't think the name will (or should, though that's subjective) change.
The community on Discord voted for the name, and Prism Launcher was the very clear winner. 
(I believe the channel has subsequently been deleted, but last I checked Prism Launcher was 100 votes or so above the second place of PlaceholderMC, and multiple hundreds above OmniMC or PrismMC)

**Comment by TheOPtimal** [comment]
> I don't think the name will (or should, though that's subjective) change. The community on Discord voted for the name, and Prism Launcher was the very clear winner. (I believe the channel has subsequently been deleted, but last I checked Prism Launcher was 100 votes or so above the second place of PlaceholderMC, and multiple hundreds above OmniMC or PrismMC)

Should I close the issue then?

**Comment by TheEvilSkeleton** [comment]
I personally like @Evrey's PrismMC as MC emphasizes Minecraft. It's shorter, clearer and shares the motivation of the original name (PrismLauncher). Someone who regularly plays/played Minecraft will easily associate MC to Minecraft. While the community voted for PrismLauncher, they already know what PrismLauncher is as they were part of the voting process. However, a wanderer will have a harder time understanding PrismLauncher as this name doesn't convey much; they will have to read a bit more.

We shouldn't lose anything from changing the name, as this project was created yesterday. It's best to change to (in my opinion) a better alternative before it becomes a lot more popular.

**Comment by Infinidoge** [comment]
I should note that PrismMC was on the list of names that were put to a vote, and it got less than 1/10th (and maybe less than 1/20th) of the votes of Prism Launcher.

(For me personally, I think the `-MC` suffix is *way* too overused)

(I should note that I am not a maintainer of the repository and thus have no actual say, but I'm pretty sure the name has been pretty firmly set by the community lol)

**Comment by TheEvilSkeleton** [comment]
I'm not a maintainer or decision maker of this project either - I was making a suggestion as well. Both names are fine, but I vastly prefer PrismMC personally, despite being overused.

**Comment by TheEvilSkeleton** [comment]
If we keep the name as is, will it be "PrismLauncher" or "Prism Launcher"? I've seen both in the project. I'm confused which one is the correct and recommended name. I suggest to stick with one in particular for consistency.

**Comment by Infinidoge** [comment]
My understanding is that "Prism Launcher" is correct, and "PrismLauncher" is used when spaces aren't allowed.
(The former is used all over the website)

**Comment by TheEvilSkeleton** [comment]
Thanks! I discovered some occurrences of "PrismLauncher" in metadata files that allowed spaces, which got me confused. I'll wait for an official response before I start editing.

**Comment by TayouVR** [comment]
what infinidoge said is indeed correct, Scrumplex clarified that some time ago on discord.
The name "PrismLauncher" or "prismlauncher" are pretty much only for backend facing, technical places. Anything user facing, e.g. UI, markdown files or a website or anything like that should use "Prism Launcher"

That is to my knowledge the idea.

**Comment by Evrey** [comment]
Yeah, there’s a whole commit just for turning all `PrismLauncher` into `Prism Launcher` in the readme or what was it.

Also yes, this can be closed. After all, it’s all over the codebase now, it won community votes, a domain has been bought, packages have been reserved, etc. That’s a ton of infrastructure work. Also i guess the step away from `MC` and towards `Launcher` is a sign to disassociate from its history. Other MC launchers also follow this other naming scheme, like `ATLauncher`, so there is precedence.

**Comment by Scrumplex** [comment]
We have settled on Prism Launcher. We already got domains and created accounts on multiple platforms.

I am sure most people will just call it Prism anyway

**Comment by TheOPtimal** [comment]
aight
