### ISSUE TITLE
Use libdecor for window decorations

### ISSUE THREAD

**Issue by evanmohr** [PrismLauncher/PrismLauncher#413]
### Role

I use Prism Launcher on Gnome Wayland, which doesn't support server side window decorations

### Suggestion

I want PrismLauncher to use libdecor

### Benefit

By using libdecor, PolyMC would look better on Gnome desktops since the titlebar would match the user's GTK theme

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![Screenshot from 2022-11-06 12-41-44](https://user-images.githubusercontent.com/80165419/200186493-4ec4796b-7cbe-484a-bfca-945a34a41c30.png)

In this picture my file manager is using the Yaru GTK theme but PrismLauncher is using a client side decoration that is based on the old, pre-libadwaita style.

Libdecor recently accepted a [merge request](https://gitlab.gnome.org/jadahl/libdecor/-/merge_requests/43) that addresses this issue.

**Comment by DioEgizio** [comment]
prism just uses Qt; this is something on Qt's end, not ours

**Comment by Scrumplex** [comment]
This probably isn't a Prism issue. I assume QGnomePlatform is used on your desktop. We don't have any custom handling of window decorations at all.
