### ISSUE TITLE
Java agent selection

### ISSUE THREAD

**Issue by TheKodeToad** [PrismLauncher/PrismLauncher#414]
### Role

I like messing with Java agents 😈

### Suggestion

Allow selection of agents in the instance settings.

### Benefit

This can already be done in the JVM arguments, but it would allow for easy toggling and selection of agents as how can be done with mods.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Would be useful for some agents such as https://github.com/betacraftuk/legacyfix. In newer versions most people will use mod loaders, but it's still handy.

~~Could be implemented by having a global agents settings, and one in instances that takes precedence. These agents would be passed as an argument to `java` as `-javaagent:/path/to/agent=<options>` (the options being an extra column). The files could potentially be validated by checking the MANIFEST.MF to ensure that users do not try to use regular mods.~~

A better alternative is to add a button underneath Replace Minecraft.jar that adds a single patch/component adding the agent.

**Comment by Scrumplex** [comment]
You can add agents as custom components. See https://github.com/PolyMC/PolyMC/pull/175

**Comment by TheKodeToad** [comment]
I was aware of this - I thought it would be good to add to instance settings as well as the version file, in the same way there is both `+jvmArgs` and an instance setting that does the same thing. This would allow for a GUI.

Edit: I updated the issue description to have a better solution.

**Comment by Frontear** [comment]
I don't personally see enough people using this for it to deserve a full gui and support going forward. It seems like a lot of extra workload for not very much gain

**Comment by TheKodeToad** [comment]
> I don't personally see enough people using this for it to deserve a full gui and support going forward. It seems like a lot of extra workload for not very much gain

A similar amount of people would use this to the Replace Minecraft.jar feature. Adding a button underneath which adds a version component with just the agent should be fairly trivial.

I've opened a pull request, as you can see below. Hopefully this will be easier to maintain since it uses an existing GUI.
