### ISSUE TITLE
Account errored

### ISSUE THREAD

**Issue by Rios5733** [PrismLauncher/PrismLauncher#420]
I want to play minecraft but my account says erorred.
![9IsWzXH](https://user-images.githubusercontent.com/98148025/200507778-d8edec9a-9aba-4de2-97b1-19a76797811b.png)

**Comment by Scrumplex** [comment]
Microsoft servers are having issues. This is not on us

**Comment by Scrumplex** [comment]
https://twitter.com/MojangStatus/status/1589822938995621888
