### ISSUE TITLE
Cannot use offline mode if account cannot be added because of network problems

### ISSUE THREAD

**Issue by LuciusV** [PrismLauncher/PrismLauncher#421]
### Version of Prism Launcher

Prism Launcher 5.1

### Version of Qt

6.4.0

### Description of bug

I cannot login and play, probably because M$ messed things up.
This is of course unacceptable behaviour - I own the game legit - offline mode must be allowed in any case of network problems.
![屏幕截图 2022-11-08 184546](https://user-images.githubusercontent.com/11925386/200545573-8480588e-cfec-4b91-a262-612b4fac6253.jpg)

### Steps to reproduce

Not always reproducible

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by surfaceflinger** [comment]
It's broken for me too right now

**Comment by TheKodeToad** [comment]
This can also occur if the account is already added (the message appears in the logs). This causes playing to get stuck in a loop and prompt the user to cancel after three tries.

**Comment by LuciusV** [comment]
I just logged in after many many tries, but main point of issue is that offline mode should not be restricted in case of such problems.

**Comment by ghost** [comment]
Well, they have to somehow confirm that you own Minecraft in order to let you use offline accounts because of [Mojang's EULA](https://www.minecraft.net/en-us/eula).

Also see this issue on MultiMC https://github.com/MultiMC/Launcher/issues/1512

**Comment by pranshuthegamer** [comment]
i think not being able to play online multiplayer is punishment enough for pirates.

I'm personally in support of piracy of videogames if the game is from a big corp.
also prismlauncher is just a launcher, im not sure how adding offline mode without signing in is breaking it

also guys theres lots of forks if you want offline mode.

my biggest point:
you're not breaking minecraft's eula if you never agreed to it or bought it since well its a license agreement plus noone is distributing it, mojang is the one with the jars

**Comment by Scrumplex** [comment]
> you're not breaking minecraft's eula if you never agreed to it or bought it since well its a license agreement plus noone is distributing it, mojang is the one with the jars

You are breaking copyright law, which is way worse than some stupid EULA.

> I'm personally in support of piracy of videogames if the game is from a big corp.

Cool for you. Don't need to brag about it. No matter who you are stealing from, this is still stealing.

Marking my own comment as off-topic as well because it is, well, off-topic.

**Comment by ghost** [comment]
>The one major rule is that you must not distribute anything we've made unless we specifically agree to it. By "distribute anything we've made" what we mean is:
>
>    - give copies of our Game to anyone else;
>    - make commercial use of anything we've made;
>    - try to make money from anything we've made; or
>    - **let other people get access to anything we've made in a way that is unfair or unreasonable**;

The launcher would still be breaking the EULA

**Comment by TheKodeToad** [comment]
The vanilla launcher does not let you play under these circumstances either afaik.

**Comment by Trial97** [comment]
Closing this as prism should not allow you to play Minecraft without confirming at least once that you own the game.
