### ISSUE TITLE
Queue mods to download while instance is still running

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#424]
### Role

I enjoy spontaneously downloading mods.

### Suggestion

Let mods from the built in mod downloader queue mods for download even if the instance is running.

### Benefit

Less relaunching (see below)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Sometimes you want to download some mods while Minecraft is running, but then you might reopen Minecraft and you suddenly think of another mod to download. This would allow you to keep playing Minecraft while you queue mods to download in the meantime, and when you think that you got a sufficient amount of mods, you could relaunch and they would all load with one relaunch :)

**Comment by TheKodeToad** [comment]
This *kind of* relates to #247. I think in general having access to everything while the instance is running would be good.

**Comment by lunofe** [comment]
This would be awesome. Working on a modpack and not being able to download/update/remove mods just because Minecraft is still running is tedious and this would be a giant QoL/UX improvement.
