### ISSUE TITLE
Error loading mods

### ISSUE THREAD

**Issue by Yeethan14** [PrismLauncher/PrismLauncher#425]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 5.1

### Version of Qt

Qt 6.3.0

### Description of bug

Every time I try to load the mod pixelmon 9.0.11, it says error loading mod. I don't know if this is a software issue or just the launcher. Whenever I load pixelmon 9.0.11 on the official Minecraft client it works. It is also just pixelmon because other mods I have tried worked.

<img width="851" alt="Screen Shot 2022-11-08 at 5 52 23 PM" src="https://user-images.githubusercontent.com/117789817/200717290-a12b592b-902f-43ea-a37d-756e680b319a.png">

### Steps to reproduce

Just download and load Pixelmon 9.0.11 on 1.16.5 macos
Then try to launch and it should pop up but now sure if its only me.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Frontear** [comment]
Which version of Java are you using, and can you send a log file, if possible?

**Comment by Yeethan14** [comment]
> Which version of Java are you using, and can you send a log file, if possible?


are you talking about this?
<img width="751" alt="Screen Shot 2022-11-09 at 1 53 12 PM" src="https://user-images.githubusercontent.com/117789817/200949752-53a79e8b-df4c-4fe7-a1e9-bad9bc478663.png">

I hope this is the right log file
https://mclo.gs/3Z9uMHA

**Comment by DioEgizio** [comment]
this is an issue between the pixelmon mod and apple silicon macs

**Comment by ghost** [comment]
> this is an issue between the pixelmon mod and apple silicon macs

They said it worked for them on the official launcher tho

**Comment by DioEgizio** [comment]
> > this is an issue between the pixelmon mod and apple silicon macs
> 
> They said it worked for them on the official launcher tho

The official launcher doesn't have arm natives on 1.16
