### ISSUE TITLE
Suggestion with hardwere reserved memory laptops.

### ISSUE THREAD

**Issue by edgars-cirulis** [PrismLauncher/PrismLauncher#426]
### Role

To be simple / play modpacks.

### Suggestion

A checkbox that bypass a checkJVMArgs()

### Benefit

So I can finnaly use PrismLauncher instead of GDLauncher.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The main issue is blocked JVM Args,
My hardwere has 6.9 GB Ram because 1.1 is hardwere reserved I am using zram for extra ram.

I am alaways using -Xmx -Xms args to allocate memory higher then 6.9. Some modpacks will crash unlikly if I dont allocate 8 GB Ram (Tested with Project Ozone 3) thats modpack is RAM Hungry. 

Sorry for my bad english.

**Comment by Frontear** [comment]
Can you explain what you mean by skipping the "checkJVMArgs()"? What does GDLauncher do here that you're asking for

**Comment by ghost** [comment]
> Can you explain what you mean by skipping the "checkJVMArgs()"? What does GDLauncher do here that you're asking for

The launcher stops him from allocating more than 6.9 GB of his 8 GB ram because 1.1 GB is hardware reserved. So he tried using the `-Xmx` `-Xms` JVM args to allocate it but the launcher doesn't let him do that aswell
![image](https://user-images.githubusercontent.com/110736028/200905137-efffeb04-006a-4a12-99be-f81385384772.png)

**Comment by edgars-cirulis** [comment]
> Can you explain what you mean by skipping the "checkJVMArgs()"? What does GDLauncher do here that you're asking for

That's a bool in source code where it checks whenever you use JVM Args.

**Comment by Scrumplex** [comment]
We can keep this open. It will be closed automatically, once #436 is merged
