### ISSUE TITLE
Automatically download mod dependencies

### ISSUE THREAD

**Issue by TheAirBlow** [PrismLauncher/PrismLauncher#429]
### Role

Modded minecraft experience

### Suggestion

Read the damn title

### Benefit

No need to check for dependencies every single time

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

idk

**Comment by flowln** [comment]
Duplicate of #116. Also, don't troll, or you'll be blocked from creating new issues.
