### ISSUE TITLE
New Instance, Version selected dropdown options not aligned with button they originated from when versions list too big

### ISSUE THREAD

**Issue by JordanPlayz158** [PrismLauncher/PrismLauncher#432]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 5.1

### Version of Qt

Qt 5.15.6

### Description of bug

When you click on the version selected dropbox, it opens up a list of version selected options but... the list of versions are a couple hundred pixels above the actual button although Qt appears to think it is in the right position as well as the wrong position as you can change which entry while being off the actual selected items "box" (don't know UI design, not sure what you call it) but if you go to the actual visible box, it snaps back control to the mouse hovering in the "box".

It is hard to explain so I provided a video:
https://user-images.githubusercontent.com/22566618/201248577-2c8b22a6-b3fe-4fb4-bec3-315f37d3a1f2.mp4

Upon further testing, there appears to be a close enough related bug that I think it's appropriate to also be in this issue, although I will make a separate second issue if asked.

The other bug is, if the list is too big, even with a single click on the Version selected dropdown, it will select whichever one is right over the dropdown, you can prevent this by clicking the dropdown but getting out of the pixels of the box (it generates) or if you click and drag.

Here is a video of the other bug:
https://user-images.githubusercontent.com/22566618/201250093-5aaac128-9056-40d4-9c41-ffe135930458.mp4

### Steps to reproduce

- Open Prism Launcher 5.1 (via flatpak, not sure if that is related to the issue but I doubt it)
- Hit Add Instance
- Click Technic on the left most side (It appears the modpack needs to have a big enough list of versions so it might be on all others but technic appears to have modpacks with a big number of versions)
- Choose a modpack with a long list of versions like, "Tekxit 3.1.4 Pi (Official)", or "Tekkit Lite" like my example video shows
- Click on "Version selected:" dropdown and see the misaligned box with the versions

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by theofficialgman** [comment]
the issues are not prismlauncher isssues but QT issues with wayland that manifest on many DEs

(edited for clarification)

**Comment by JordanPlayz158** [comment]
Ah ok, sorry about that, at least now there is an issue for the future when people search

**Comment by theofficialgman** [comment]
this is the original QT5/6 bug https://bugreports.qt.io/browse/QTBUG-85297

its been fixed in QT6 dev and should be in QT 6.5 when that releases.
