### ISSUE TITLE
Open All button should close the popup

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [PrismLauncher/PrismLauncher#438]
### Role

I play modded Minecraft.

### Suggestion

I want the open all button on the popup for mods that prism cant download to close the popup, rather than also having to press ok

### Benefit

I dont have to use energy to click the other button

### This suggestion is unique

- [ ] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Ryex** [comment]
With the merging of #304 and potential of #439 this would not be a good idea.

**Comment by DioEgizio** [comment]
Yeah with https://github.com/PrismLauncher/PrismLauncher/pull/304 being merged this is a terrible idea

**Comment by BeansBeefBroccoli** [comment]
Ok
