### ISSUE TITLE
Discord link not working

### ISSUE THREAD

**Issue by AlexFigas** [PrismLauncher/PrismLauncher#44]
### Operating System

Windows 11

### Version of PolyMC

...

### Version of Qt

...

### Description of bug

![image](https://user-images.githubusercontent.com/65889776/196449409-efb40ba4-9983-478d-983a-110f716a7862.png)

### Steps to reproduce

Click on the link:
https://discord.com/invite/hX4g537UNE

And try accepting it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by thecnoNSMB** [comment]
I am also experiencing this problem.

**Comment by tobimori** [comment]
It was temporarily disabled due to 4chan raiders.

**Comment by Moth-Tolias** [comment]
~~this is intentional - invites are currently restricted so the moderators can deal with the huge influx of people. you should be able to try again later, when things have calmed down~~
got ninja'd lol

**Comment by veryredpp** [comment]
> got ninja'd lol

ninja'd? did they open the server up again?

**Comment by thecnoNSMB** [comment]
> > got ninja'd lol
> 
> ninja'd? did they open the server up again?

they mean tobimori said the same thing first. server's still down

**Comment by AlexFigas** [comment]
Okey then.
Please let me know when it's opened.

Thanks

**Comment by P3rf3ctXZer0** [comment]
I wanted to join as well as I was using PolyMC I await with bated breath.

**Comment by fritogotlayed** [comment]
I would also like a notification when the discord link is back. I'm a PolyMC user myself and would love to switch after the recent shenanigans.

**Comment by thecnoNSMB** [comment]
It's working now!
