### ISSUE TITLE
Automatically download Java from Adoptium

### ISSUE THREAD

**Issue by zoeleu** [PrismLauncher/PrismLauncher#442]
Instead of prompting the user only for local java installs, it would be nice to have it automatically download JREs from adoptium.net. It would make helping tech-illiterate friends install minecraft MUCH easier.

**Comment by ghost** [comment]
This is already being done https://github.com/PrismLauncher/PrismLauncher/pull/285

**Comment by zoeleu** [comment]
Thanks
