### ISSUE TITLE
Flatpak Prism - Forge breakage due to Java 8 update 321 can't be worked around

### ISSUE THREAD

**Issue by planetguy32** [PrismLauncher/PrismLauncher#446]
### Operating System

Linux

### Version of Prism Launcher

5.1

### Version of Qt

5.15.6

### Description of bug

The Flatpak'd launcher offers only OpenJDK 8u345 (as well as Java 17). But OpenJDK version 321 broke Forge mod loading. There's a [recommended workaround](https://prismlauncher.org/wiki/getting-started/installing-java/#forge-1.16.5-and-java-8u321+), but the Flatpak version of Prism isn't able to use external Java installations.

### Steps to reproduce

* Install Prism from Flathub
* Install e.g. Create: Above and Beyond from CurseForge
* Install a pre-321 OpenJDK - e.g. `sudo apt install openjdk-8-jre-headless=8u312-b07-0ubuntu1`
* Choose a correct-version system binary - e.g. navigate to and click `/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java`
 
This results in Java test failure when clicking the Test button:

`/run/user/1000/doc/20084bb5/java: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory`

Pasting the Java path doesn't work either:

`The java binary "" couldn't be found. Please fix the java path override in the instance's settings or disable it.`

### Suspected cause

I'd guess Flatpak breaks the workaround by doing some kind of path remapping.

Bundling Java 8 from before version 321 seems like it would fix this, and it would be a nice "batteries included" feature to have.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by theofficialgman** [comment]
the recommended workaround is to update forge. as the wiki says, only old 1.16.5 versions are affected. Newer releases of forge for 1.16.5 correct the issue.

also you misunderstand flatpaks, they are NOT meant to access the system libraries, so the issue you have with the shared libraries not loading when trying to access the system java is due to flatpak denying access as it should

**Comment by DioEgizio** [comment]
Just update forge, the reason why it doesn't work is that you have to give the flatpak permission with flatseal to access the jre

**Comment by barraIhsan** [comment]
Flatpak Prism stores java in
`/var/lib/flatpak/app/org.prismlauncher.PrismLauncher/current/active/files/jdk`
and in prism it will be replaced as `/app/jdk/`.

You can just simply install Java there.
