### ISSUE TITLE
Enhancement for mod management 

### ISSUE THREAD

**Issue by edgars-cirulis** [PrismLauncher/PrismLauncher#447]
### Role

To be simple / play modpacks.

### Suggestion

On "Download mods" Hide mods on instance that are already installed.

### Benefit

Would be better to browse mods that is not in the pack. Usless you add duplicated mod.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheAirBlow** [comment]
This is impossible as there is no way to get a mod ID directly from Curse. It is the only unique identifier mods have in JARs.

**Comment by TheAirBlow** [comment]
The only way to implement that is saving all mod IDs (the curse one, different from forge mod ID) into a file. But it is just unreliable because it would make importing mods indirectly or from a different source a bad thing to do (for example you need a DEV build, but add mods search would still show the mod)

**Comment by txtsd** [comment]
![767303-1299603875](https://user-images.githubusercontent.com/768728/201585615-ac81b398-73a9-4be3-b328-8cacd6472449.jpg)

**Comment by edgars-cirulis** [comment]
> This is impossible as there is no way to get a mod ID directly from Curse. It is the only unique identifier mods have in JARs.

I've used GDLauncher it had this feature. Doesn't mix-up mods that's already added.
It didn't hide but at least it had checkmark that indicates it's already installed on the instance.

**Comment by DioEgizio** [comment]
> This is impossible as there is no way to get a mod ID directly from Curse. It is the only unique identifier mods have in JARs.

That's not true and we already store mod metadata information so it's indeed possible

**Comment by flowln** [comment]
Hiding the mods doesn't seem like a good option. I'd rather have it indicated somewhere that the mod is already installed, but still show it.
