### ISSUE TITLE
libspdlog.so.1 library missing when trying to launch instance

### ISSUE THREAD

**Issue by jschenke488** [PrismLauncher/PrismLauncher#449]
### Operating System

Linux

### Version of Prism Launcher

5.1

### Version of Qt

6.4.0

### Description of bug

Launching an instance shows an error about missing libraries

```
/usr/lib64/jvm/zulu-18/bin/java: error while loading shared libraries: libspdlog.so.1: cannot open shared object file: No such file or directory 
Process exited with code 127.
```

### Steps to reproduce

Launch an instance with any distribution of Java

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Update/Rebuild Mangohud

**Comment by edgars-cirulis** [comment]
Install spdlog dependency

**Comment by TheAirBlow** [comment]
Not really related to Prism Launcher but to the Java VM you're using to run Minecraft.
In this case a little bit of googling tells us that you need `spdlog` library.

**Comment by Scrumplex** [comment]
OP is probably using MangoHud, and LD_PRELOAD causes the java process to load libMangoHud which depends on spdlog. If you are on Arch Linux, you need to rebuild MangoHud on library updates, as it is not automatically rebuilt otherwise. So rebuilding MangoHud fixes the issue.
