### ISSUE TITLE
Show mod count in mods tab

### ISSUE THREAD

**Issue by TheAirBlow** [PrismLauncher/PrismLauncher#451]
### Role

Improve modded minecraft experience

### Suggestion

Show mod count near the "help" button

### Benefit

Just because why not

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Here's a lazy mockup:
![image](https://user-images.githubusercontent.com/68467762/201536365-70186fef-1d0d-43f8-93c2-9566f5ab6846.png)

**Comment by Poopooracoocoo** [comment]
... Why?

**Comment by JLUsr** [comment]
Would love to see an additional string of text that shows how many mods have been selected (in the event you select more than one) too.

**Comment by TheKodeToad** [comment]
Maybe the heading could read Mods (count)?

**Comment by TheAirBlow** [comment]
> Maybe the heading could read Mods (count)?

The title is already fat enough. It will just make it show zero info when the window size is not big enough

**Comment by TheKodeToad** [comment]
I mean the heading inside the window.

**Comment by TheAirBlow** [comment]
> I mean the heading inside the window.

Oh. The "Mods" text? Yeah, more reasonable and easier to implement

**Comment by ColonelGerdauf** [comment]
**Mods [112 installed, 3 selected]**

In the top above the list. This may require support for dynamic text in the QT main window.
