### ISSUE TITLE
Import from PolyMC and MultiMC

### ISSUE THREAD

**Issue by TheOPtimal** [PrismLauncher/PrismLauncher#46]
### Role

Switchied from MultiMC to PolyMC, now jumping ship again.

### Suggestion

Make an "Import" button that just copies the data from MultiMC or PolyMC's data folders.

### Benefit

Makes it easier to switch from these launchers.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This might be a bit harder to do with Flatpak and Snap sandboxing. Maybe an Open Folder dialog that asks the user to navigate to the proper folder? Dunno.

**Comment by NotNite** [comment]
Worth noting [this commit](https://github.com/PrismLauncher/PrismLauncher/commit/6db3f68ae18098d96ef63cec5ffc666b6150304b) should fall back to using PolyMC's data directories for the initial release. I've heard in the Discord that a migration system is planned.

**Comment by DownloadableFox** [comment]
How would this be made? There's so many ways to get PolyMC installed and in a lot of different operative systems. I'm no expert but I'm sure that Flatpack alongside other possible tools save their program files in different directories. 

How is a select folder dialog different from copying the instances folder manually :(

**Comment by NotNite** [comment]
There's more to Prism than just instances - you also have your global settings and accounts. Selecting the directory your MultiMC-like launcher is installed in and importing settings could be very useful, compared to telling users "copy these specific files to this directory".

**Comment by DownloadableFox** [comment]
Of course. I completely forgot about that. Yeah user configuration makes sense.

**Comment by TheOPtimal** [comment]
> How would this be made? There's so many ways to get PolyMC installed and in a lot of different operative systems. I'm no expert but I'm sure that Flatpack alongside other possible tools save their program files in different directories.
> 
> How is a select folder dialog different from copying the instances folder manually :(

Flatpak usually stores application data in ~/.var/app/{APP_NAME}

And the select folder dialog would automatically point you to the right folder, you just need to click "Open". Maybe there would be a dialog beforehand telling the user that all they need to do is click "Open".

**Comment by Octelly** [comment]
I've been using the same instance directories since MultiMC personally
![image](https://user-images.githubusercontent.com/29976879/196465713-c7a299e9-5b64-4e27-8b99-29b960d39481.png)
