### ISSUE TITLE
No audio in Flatpak version

### ISSUE THREAD

**Issue by Quack-Sparrow** [PrismLauncher/PrismLauncher#460]
### Operating System

Linux

### Version of Prism Launcher

Prism launcher 5.2

### Version of Qt

Qt 5.15.6

### Description of bug

[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)

Note: Sound IS working using the AppImage. Error above not thrown using AppImage.

### Steps to reproduce

Fresh install Fedora 37 KDE Plasma
Install Nvidia drivers
Install PrismLauncher through Flatpak
Attempt to load instance

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
Did sound work in the previous 5.1 release? This seems unlikely to be a bug in the flatpak package.

If you need to downgrade to test use this:

```
sudo flatpak update --commit=0b45a5b7fd52630fab79fcd53fe455fcabe65120a9b6fd8142ce7cb1cb67b9d3 org.prismlauncher.PrismLauncher
```

**Comment by ghost** [comment]
> [ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)

This error isn't related to sound not working. But it might cause some audio latency.

**Comment by lemonzest79** [comment]
Is this a new install of Fedora 37? Cos if it has updated to Pipewire 0.3.60-1 then Minecraft will lose sound (did for me) need to roll back to 0.3.59 or wait for 0.3.60-3 for sound to be fixed

**Comment by Quack-Sparrow** [comment]
> Did sound work in the previous 5.1 release? This seems unlikely to be a bug in the flatpak package.
> 
> If you need to downgrade to test use this:
> 
> ```
> sudo flatpak update --commit=0b45a5b7fd52630fab79fcd53fe455fcabe65120a9b6fd8142ce7cb1cb67b9d3 org.prismlauncher.PrismLauncher
> ```

It did not, tried it first with the 5.1 install, updated later to 5.2.

**Comment by Quack-Sparrow** [comment]
> Is this a new install of Fedora 37? Cos if it has updated to Pipewire 0.3.60-1 then Minecraft will lose sound (did for me) need to roll back to 0.3.59 or wait for 0.3.60-3 for sound to be fixed

Yes, it is a fresh install. I don't know how to roll it back though. A friend updated his Fedora 36 instance to 37 as well but he doesn't have any sound issues.

**Comment by lemonzest79** [comment]
> > Is this a new install of Fedora 37? Cos if it has updated to Pipewire 0.3.60-1 then Minecraft will lose sound (did for me) need to roll back to 0.3.59 or wait for 0.3.60-3 for sound to be fixed
> 
> Yes, it is a fresh install. I don't know how to roll it back though.

try sudo dnf downgrade pipewire*

**Comment by jn64** [comment]
[pipewire-0.3.60-4 has *just* been submitted for stable in F37](https://bodhi.fedoraproject.org/updates/FEDORA-2022-acc112c777). It should be available in your updates within 12-24 hours.

**Comment by lemonzest79** [comment]
> [pipewire-0.3.60-4 has _just_ been submitted for stable in F37](https://bodhi.fedoraproject.org/updates/FEDORA-2022-acc112c777). It should be available in your updates within 12-24 hours.

It should work, cos 0.3.60-3 worked for my "No sound in Minecraft" issue with the AppImage

**Comment by Quack-Sparrow** [comment]
> 

This resolved the issue! Audio is now being transmitted properly. The error, however, is still being thrown when changing audio devices.

**Comment by tristan-f-r** [comment]
For any future viewers, do note that after updating to Fedora 37, if the issue still persists and the pipewire version is updated, make sure to restart your computer.
