### ISSUE TITLE
[Suggestion] Instance Deletion Confirmation Dialogue

### ISSUE THREAD

**Issue by Lylythii** [PrismLauncher/PrismLauncher#462]
### Role

Deleting & Managing modpack instances.

### Suggestion

Request confirmation before deleting a modpack instance. (Configurably?)

### Benefit

Avoids accidental loss of modpack instances.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Deletion of an instances without confirmation dialogue could result in accidental deletion of important instances.
In-turn. It appears PrismLauncher will highlight the next available instance after deleting the currently highlighted instance. Accidental double-clicking may lead to loss of instances when intentionally deleting another.

**Comment by Scrumplex** [comment]
Instances are never deleted without confirmation. If available, the launcher will move your instances to your system trash/recycle bin. If it is not available, it will ask for confirmation to delete.

**Comment by PanoptesDreams** [comment]
> Instances are never deleted without confirmation. If available, the launcher will move your instances to your system trash/recycle bin. If it is not available, it will ask for confirmation to delete.

No. That does not happen. I went to file a bug report and ended up here.

So. I had a heart attack ~5 mins ago when I almost deleted a dev pack, luckily I had it open in a terminal so it was safe.
I followed up to check to make sure there was **NOT** a confirmation dialogue, deleted a *random* pack, and sure enough it deleted it with zero confirmation and didn't end up in the Bin either.

### What Happened:
1. Delete button is pressed
2. Pack is deleted/removed
3. No confirmation dialogue is shown
4. Pack is not in the Recycle bin

OS - Win 10 19044.2251
Java - MS openJDK 17.0.3 2022-04-19 LTS
Prism - 5.0

P.S oh... I have Prism 5.0 will update and see if the behavior persists

P.P.S edit: Maintaining post originality for searchability for future issue seekers

**Comment by PanoptesDreams** [comment]
Update: On 5.2 the only difference is that instances **ARE** sent to the Bin. ***However*** there is **no** confirmation dialogue

**Comment by PanoptesDreams** [comment]
So.. my request is that there is ALWAYS a confirmation dialogue.

**Comment by Scrumplex** [comment]
> However there is no confirmation dialogue

Same as most file managers. We can look into adding a visual indication that the instance was just moved to the trash to save people from heart attacks. But IMO, a confirmation dialog for a non-destructive action might be annoying.

**Comment by Lylythii** [comment]
> Same as most file managers. We can look into adding a visual indication that the instance was just moved to the trash to save people from heart attacks.

I think I agree with this as a potential middle-ground.
For extra context, I initially opened this issue after having mistakenly deleted a dev instance (after having deleted an unwanted instance), & only realised several days *after* the fact.
Had I set my recycling to auto-clear itself semi-frequently, I would've lost an important project, without any realisation as to how.
In contrast, a 20-tick delay between deletion of instances would help avoid double-click mistakes like this in the future.

> But IMO, a confirmation dialog for a non-destructive action might be annoying.

This is where a potential "disable this dialogue" option could be useful. You'd be opting into the risk.

**Comment by PanoptesDreams** [comment]
> a confirmation dialog for a non-destructive action might be annoying.
You telling me deleting a file is 'non-destructive?'
There can be many edge cases where deleting something can awry. Whether it be the systems fault or operator error.

How about an internal '.trash' folder to (re)move instances into. And a GUI icon that brings up or switches to 'trashed' instances. From there someone may choose to 'Empty Trash', recover a pack, or open the trash folder.

Settings for the trash should include:
[] Always display confirmation dialogue?
[] Move straight to system trash (do not use internal trash)
and a path choice for trash like the instances folder

**Comment by PanoptesDreams** [comment]
> Same as most file managers
And a competent file manager will also let you choose if you want that dialogue

It may even depend on what system I'm using on whether or not I want that dialogue

**Comment by TheKodeToad** [comment]
> How about an internal '.trash' folder to (re)move instances into. And a GUI icon that brings up or switches to 'trashed' instances. From there someone may choose to 'Empty Trash', recover a pack, or open the trash folder.
> 
> Settings for the trash should include: [] Always display confirmation dialogue? [] Move straight to system trash (do not use internal trash) and a path choice for trash like the instances folder

I could just do a reaction, but this sounds like a *really* good idea to me. Edit: I just realised this doesn't *really* add anything so it's probably going to be marked as off-topic. Sorry.

**Comment by TurkishAhmet4545** [comment]
> If available, the launcher will move your instances to your system trash/recycle bin.<

I was about to open a new issue like this but i searched after reading the checkbox and i checked my bin after seeing this.
YAAAAY!
