### ISSUE TITLE
The launcher freezes/crashes when hitting Edit after right-clicking an instance.

### ISSUE THREAD

**Issue by MagmaSlime123** [PrismLauncher/PrismLauncher#463]
### Operating System

Windows

### Version of Prism Launcher

5.2.

### Version of Qt

6.4.0.

### Description of bug

The launcher freezes/crashes when hitting Edit after right-clicking an instance.

### Steps to reproduce

Make an instance, start and run that instance, close the game, right-click the instance, hit edit.
Launcher will sometimes freeze/crash.

### Suspected cause

Don't know.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RhythmicSys** [comment]
Also having this issue

For me, it happens on a very specific instance
When the launcher downloads [this modpack](https://modrinth.com/modpack/accessibility/versions) - I cannot click edit or it'll crash the launcher. 

If I download the pack from modrinth and upload it to the launcher manually, there is no issue
If I upload my local pack generated by packwiz, also no issue
If I move the mods from the folder of the instance generated by prism, into a new instance, I can hit edit on the new instance

**OS**
Linux - Debian

**Prism Version**
`5.2`

**QT version**
`5.15.3`

**Comment by MagmaSlime123** [comment]
> Also having this issue
> 
> For me, it happens on a very specific instance When the launcher downloads [this modpack](https://modrinth.com/modpack/accessibility/versions) - I cannot click edit or it'll crash the launcher.
> 
> If I download the pack from modrinth and upload it to the launcher manually, there is no issue If I upload my local pack generated by packwiz, also no issue If I move the mods from the folder of the instance generated by prism, into a new instance, I can hit edit on the new instance
> 
> **OS** Linux - Debian
> 
> **Prism Version** `5.2`
> 
> **QT version** `5.15.3`

This happens with any instance on my end.

**Comment by DioEgizio** [comment]
as i explained in https://github.com/PrismLauncher/PrismLauncher/issues/633, it's b/c the log file is full of stuff and prism tries to load all of it at once

**Comment by MagmaSlime123** [comment]
Oh.

**Comment by TechPro424** [comment]
I'm having this issue too

**Comment by Scrumplex** [comment]
Can you try to replicate this bug with Prism Launcher 6.3 and then send in the `PrismLauncher-0.log` file located in the data directory (i.e. `%appdata%\PrismLauncher`)

**Comment by TechPro424** [comment]
Does not happen on 6.3

**Comment by MagmaSlime123** [comment]
> Can you try to replicate this bug with Prism Launcher 6.3 and then send in the `PrismLauncher-0.log` file located in the data directory (i.e. `%appdata%\PrismLauncher`)

Still happens. I'm guessing this issue is caused by Prism scanning the entire latest.log file, and with how big those can be on modded instances, it'll freeze the launcher.

[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/11183955/PrismLauncher-0.log)
