### ISSUE TITLE
Resource Pack downloader

### ISSUE THREAD

**Issue by UltraBlackLinux** [PrismLauncher/PrismLauncher#466]
### Role

I use resource packs; quite a few of them actually.

### Suggestion

There should be a resource pack downloader similar to the one used for mods

### Benefit

it's hard to keep track of resource pack updates when nobody tells you about then

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ghost** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/153

**Comment by UltraBlackLinux** [comment]
wat - the search bar needs fuzzy find support, it's so  bad

**Comment by UltraBlackLinux** [comment]
Just thought I accidentally closed this, I didn't
