### ISSUE TITLE
Launcher crashes when attempting to 'check for mod updates' when there are no mods/no modloader

### ISSUE THREAD

**Issue by Frontear** [PrismLauncher/PrismLauncher#468]
### Operating System

Windows 10

### Version of Prism Launcher

Prism Launcher 5.2

### Version of Qt

Qt 6.4.0

### Description of bug

Attempting to press the button to check for mod updates in the Mods tab of an instance will cause a crash if there is no mods/no modloader for that instance

### Steps to reproduce

* Create a new instance, WITHOUT a modloader
* Navigate to the mods tab
* Press the check for mod updates button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
can't reproduce

if there's no mods it's grayed out

<img width="108" alt="image" src="https://user-images.githubusercontent.com/83089242/206427880-919d2623-7778-4c97-90bd-be532f92cdb7.png">


if there's mods but no modloader it doesn't crash either?

**Comment by Frontear** [comment]
I can't reproduce either.., wish I had a log from then but its been far too long. I don't know why its not happening, but I no longer have the correct reproduction steps.
