### ISSUE TITLE
Delete text in filter mods tab with x icon

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#469]
### Role

I play modded Minecraft

### Suggestion

In the Mods section of the console window when your typing in filter it'd be nice if the was a way to delete text at once. So like a little x icon that when clicked would delete what you typed

### Benefit

Add a little x icon to filter search for mod section in console window. So you can do binary searches easier with less effort

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

In the Mods section of the console window when your typing in filter it'd be nice if the was a way to delete text at once. So like a little x icon that when clicked would delete what you typed

**Comment by Aces-and-Jacks** [comment]
<img width="837" alt="Screen Shot 2022-11-17 at 3 23 28 AM" src="https://user-images.githubusercontent.com/106651342/202394276-a2322b05-7721-4f39-994f-ec9b69be1c27.png">

**Comment by Aces-and-Jacks** [comment]
<img width="837" alt="Screen Shot 2022-11-17 at 3 23 28 AM" src="https://user-images.githubusercontent.com/106651342/202394541-90a21651-933a-4d57-a945-0627f5fb7d28.png">

**Comment by TheKodeToad** [comment]
This feature was present in 5.1, but it was removed.

**Comment by Aces-and-Jacks** [comment]
bump

**Comment by flowln** [comment]
See https://github.com/PrismLauncher/PrismLauncher/issues/849#issuecomment-1435022820

**Comment by Aces-and-Jacks** [comment]
Well that's a bummer 
But if it improves performance by removing it then that's good I suppose
