### ISSUE TITLE
Custom UI font setting

### ISSUE THREAD

**Issue by voidlynx** [PrismLauncher/PrismLauncher#475]
### Role

General-purpose usage, also i like customization

### Suggestion

To have a setting to change the UI font in the launcher 

### Benefit

So that it can be further customized for power-users who want a uniform look with the rest of the system

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

So far you're only able to customize the console font, but the UI font customization could be a good thing in that case.

If it is already implemented as a user-config thing, where you have to set it up somewhere in the system - a guide to do that would be nice. Especially for unix users.

**Comment by Trial97** [comment]
Merged in: https://github.com/PrismLauncher/PrismLauncher/issues/324

**Comment by lifehome** [comment]
Hi I don't think this is a proper merge as #324 is regarding UI size, not font settings.
Can we reopen this?

**Comment by PioneersProd** [comment]
developers who insist on 6pt font have inverted peepee
