### ISSUE TITLE
Failed to get Minecraft access token (Still happens after 2 days)

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#478]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.2

### Version of Qt

Qt 6.4.0

### Description of bug

I could not start any of my instances because prism could not login to my account.  
I removed it and re-logged but I keep getting this popup.  
I've also waited a full 24 hours cycle before retrying.  

![image](https://user-images.githubusercontent.com/111307478/202856720-8a11b6f3-4a51-4961-8b11-b13a55102b86.png)

The issue started happening 2 days ago.  

### Steps to reproduce

Add a microsoft account to Prism Launcher.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
This is an issue on Microsoft/Mojang's. You can reproduce that on the official launcher too

**Comment by ghost** [comment]
> This is an issue on Microsoft/Mojang's. You can reproduce that on the official launcher too

The official one works fine though. I am using it right now. That's why I thought it might be an issue with Prism Launcher.

**Comment by DioEgizio** [comment]
Well, the error is saying Mojang/Microsoft rate limited you. Are you sure it doesn't happen on the vanilla launcher on the same pc/IP?

**Comment by ghost** [comment]
> Well, the error is saying Mojang/Microsoft rate limited you. Are you sure it doesn't happen on the vanilla launcher on the same pc/IP?

It let's me launch the game normally, but I just noticed that I can't connect to any servers. So probably it is an issue on my end. Sorry for wasting your time.

-- UPDATE --

I used TOR as a proxy and it logged in normally.
