### ISSUE TITLE
Auto Java Selection

### ISSUE THREAD

**Issue by Itrixykk** [PrismLauncher/PrismLauncher#479]
if i create a instance for 1.17 it auto selects java 19
and if i create a instance for 1.12.2 it auto selects java 8 

Its very Annyoing For A person Like Me who Changes Versions From A instance all the time

Thanks, Best Regards.

**Comment by DioEgizio** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/335
