### ISSUE TITLE
Security incident on the MPR

### ISSUE THREAD

**Issue by hwittenborn** [PrismLauncher/PrismLauncher#488]
Hey, I'm just send a message that there's been a security incident on the MPR, and there's been a mandatory password reset that's been put in place before anyone can log in. All SSH keys have also been revoked on all accounts, and will need to be added back to any accounts before they can be used again.

Just sending a heads up in case package uploads start randomly not working (I'm assuming that's managed by @Scrumplex since you're the maintainer of the MPR package). Feel free to ask any questions if you have any - there's also an incident report available if you'd like to look at it: https://www.makedeb.org/news/security-incident-on-the-mpr.

**Comment by Scrumplex** [comment]
Thanks for the heads-up. I will deal with my account later today.

This must be a stressful situation for you, so I wish you the best!

**Comment by txtsd** [comment]
Thanks for notifying us!

**Comment by Scrumplex** [comment]
Restored my account and added my SSH key again
