### ISSUE TITLE
Cachix subsitutor

### ISSUE THREAD

**Issue by yavko** [PrismLauncher/PrismLauncher#491]
### Role

I use NixOS and the official PrismLauncher nix flake

### Suggestion

I would like it if cachix binary caching could be added to the CI

### Benefit

I dont need to compile PrismLauncher every time I update my NixOS

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by yavko** [comment]
A good example of this can be see with Hyprland https://github.com/hyprwm/Hyprland/blob/main/.github/workflows/nix-build.yaml

**Comment by Scrumplex** [comment]
cachix is a good idea! I will look into setting it up

**Comment by yavko** [comment]
Thanks!
