### ISSUE TITLE
Make removed icons go to trash bin

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#494]
### Role

I play modded Minecraft

### Suggestion

When removing an icon I think it'd be good if it went into the trash bin on your pc instead of deleted instantly

### Benefit

So I don't accidentally delete an icon I added like I just did now

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
Isn't this already the behaviour?

Edit: :facepalm: yet again I take things too literally.

**Comment by Aces-and-Jacks** [comment]
Not when I removed an icon
