### ISSUE TITLE
Shows a group multiple times

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#495]
### Operating System

macOS

### Version of Prism Launcher

5.2

### Version of Qt

6.3.0

### Description of bug

I expected it to only show the group once

### Steps to reproduce

1. Add a modpack and select which group it should go

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment]
<img width="960" alt="SCR-20221121-iy" src="https://user-images.githubusercontent.com/106651342/202972848-01e64b3f-be85-469c-8c34-023fa05678db.png">

**Comment by ghost** [comment]
The first group is the most recently used group followed by all groups in alphabetical order

**Comment by Aces-and-Jacks** [comment]
oh ok then. So that's purposeful
