### ISSUE TITLE
(snap) Pressing "open folder" freezes prism launcher.

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#497]
In snap version of prism, pressing "open folder" freezes prism launcher. while pressing "open folder" in resource packs section of minecraft works as expected.

**Comment by ghost** [comment]
Some additional details, sorry for forgetting:
OS: Ubuntu 22.10
Prism version: 2022-11-19 6.0 develop

**Comment by Ryex** [comment]
so, to clarify, your using one of the development snap builds?

**Comment by ghost** [comment]
yep, this is the only one available

**Comment by Trial97** [comment]
It still happens on latest version?

**Comment by ghost** [comment]
> It still happens on latest version?

I don't see the snap version in github actions or the snap store. How would I go about doing it?

**Comment by Trial97** [comment]
> > 
> 
> I don't see the snap version in github actions or the snap store. How would I go about doing it?

https://snapcraft.io/prismlauncher

*Sorry for not mentioning the version: 8.0

**Comment by ghost** [comment]
It doesn't freeze but it doesn't open anything either.
OS: Ubuntu 22.04

**Comment by Trial97** [comment]
If it doesn't open the folder then is related to: https://github.com/PrismLauncher/PrismLauncher/issues/1490 or https://github.com/PrismLauncher/PrismLauncher/issues/993 so closing this as complete.
