### ISSUE TITLE
About page does not contain PolyMC contributors

### ISSUE THREAD

**Issue by NotNite** [PrismLauncher/PrismLauncher#50]
The about page contains `2012-2021 MultiMC Contributors` and `2021-2022 Prism Launcher Contributors`. We overwrote the slot for PolyMC instead of adding a new one, so the contributors to PolyMC aren't explicitly recognized.

Considering this is a fork of PolyMC, it's implicit, but I think we should specify credits to PolyMC like we did for MultiMC (and like we did in COPYING.md).

**Comment by DioEgizio** [comment]
https://github.com/PrismLauncher/PrismLauncher/pull/13#discussion_r998033969

**Comment by NotNite** [comment]
Oh. lol
