### ISSUE TITLE
Add backup management

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#504]
### Role

I play modded Minecraft

### Suggestion

Add a backup management system

### Benefit

Makes it easier to backup instances when updating modpacks and when messing with world saves etc

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It should probably be a tab somewhere here

![image](https://user-images.githubusercontent.com/110736028/203177784-12ba5e6b-cdeb-484b-88c3-f8c576b86775.png)

**Comment by Frontear** [comment]
Can't we just Export the instance? How would your system be any different from that
