### ISSUE TITLE
Rough logo sketches suggestion/ideas

### ISSUE THREAD

**Issue by fizzzydev** [PrismLauncher/PrismLauncher#51]
### Role

I play modded Minecraft

### Suggestion

2 rough logo designs

### Benefit

No logo yet

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://user-images.githubusercontent.com/116093367/196459967-dc04026c-4c8b-4b39-afef-464aa7b23e93.png)

**Comment by fizzzydev** [comment]
Just 2 Ideas

**Comment by Evrey** [comment]
Related: #41 

> And PrismMC/PrismLauncher has the better potential for a nice logo. Like a blocky rainbow shooting out of a triangular glass block.

And:

> Ooh, what if the [g]lass block also looked like Prismarine?

**Comment by Octelly** [comment]
Related PR: https://github.com/PrismLauncher/PrismLauncher/pull/52

**Comment by LauraWebdev** [comment]
Throwing the concept from PR #52 in here as well. As discussed, it would be cool to have this as an open discussion.

![image](https://user-images.githubusercontent.com/7365286/196473334-3bf9992b-3800-4b14-8046-d7ee0d2ecc70.png)
![image](https://user-images.githubusercontent.com/7365286/196473376-71b3f374-bb67-41b5-919f-abe016d010b3.png)

**Comment by Aproxia-dev** [comment]
> Throwing the concept from PR #52 in here as well. As discussed, it would be cool to have this as an open discussion.
> 
> ![image](https://user-images.githubusercontent.com/7365286/196473334-3bf9992b-3800-4b14-8046-d7ee0d2ecc70.png) ![image](https://user-images.githubusercontent.com/7365286/196473376-71b3f374-bb67-41b5-919f-abe016d010b3.png)

Already said my thoughts in #52, I feel like the grass block green doesn't really fit with the name, and it reminds me of Ethereum way too much.

**Comment by LauraWebdev** [comment]
Also created a second concept based on the comments in that PR. A flatter icon with less resemblance to ethereum, sampling the colors of the Amethyst block instead of grass.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/7365286/196478204-0ea1f6cf-a9b2-4fa2-8b88-afbb02435d55.png">

**Comment by Octelly** [comment]
@LauraWebdev that's very solid
i think it would be awesome if someone from the dev team could make the colour of the logo customisable, but otherwise, I don't have much to complain about

**Comment by Aproxia-dev** [comment]
> Also created a second concept based on the comments in that PR. A flatter icon with less resemblance to ethereum, sampling the colors of the Amethyst block instead of grass.

I. FREAKING. LOVE THAT!!!!!!!
small change i'd add, the upper right corner of the gradient triangle looks a bit off, probably because it doesn't have the gap like the left corner does, but i'd add that gap to the outline triangle instead. on that note, that triangle deserves some color too imo lol

**Comment by Aproxia-dev** [comment]
> I. FREAKING. LOVE THAT!!!!!!! small change i'd add, the upper right corner of the gradient triangle looks a bit off, probably because it doesn't have the gap like the left corner does, but i'd add that gap to the outline triangle instead. on that note, that triangle deserves some color too imo lol

kinda like this if you couldn't make it out out of my attempt at describing it
![image](https://user-images.githubusercontent.com/53254254/196480821-99c3c4b6-2830-4843-880a-f212f6b25f7c.png)

**Comment by Octelly** [comment]
@Aproxia-dev yeah, that's actually not a bad idea
I thought it look fine before, but this might be a bit better

**Comment by LauraWebdev** [comment]
<img width="259" alt="image" src="https://user-images.githubusercontent.com/7365286/196481419-a821da4c-1d25-4ab5-b934-c6b65eb1135b.png">
Kinda like this?

**Comment by Aproxia-dev** [comment]
also @LauraWebdev the discord invite is open now!
(thanks @dynamyc010 for notifying me)

**Comment by Aproxia-dev** [comment]
> @LauraWebdev Kinda like this?

YES EXACTLY that looks great actually!!!
also i still think the black outline triangle deserves some spark but i don't know how that could be made lol

**Comment by jn64** [comment]
![out](https://user-images.githubusercontent.com/23169302/196481988-87516a31-24e3-47ac-8b9b-71b6c4a32918.gif)

```sh
#!/bin/bash

wget -q https://github.com/LauraWebdev/PrismLauncher/raw/70a9c57f806270ba5a47a0bdee61d100a85b9695/docs/branding/logo_icononly-64px.png -O 0.png

declare n=$(( 300 - (100 / 7 * 2 ) ))
for i in {0..5}; do
	convert "$i.png" -modulate 100,100,$n "$(( ++i )).png"
done

convert -alpha opaque -delay 10 -loop 0 *.png out.gif
```

**Comment by Octelly** [comment]
@jn64 lol

**Comment by Evrey** [comment]
(Obligatory mention that a prism is not a pyramid, but an extruded polygon.)

**Comment by Evrey** [comment]
Can be closed, for an official logo poll on Discord just ended. I gotta say, the winner was my favourite and its creator is worth paying for.

**Comment by dynamyc010** [comment]
> Can be closed, for an official logo poll on Discord just ended. I gotta say, the winner was my favourite and its creator is worth paying for.

Not gonna lie, I was hoping I could vote in the actual voting as well

Instead it happened while I was asleep lmao

**Comment by TheOPtimal** [comment]
> Can be closed, for an official logo poll on Discord just ended. I gotta say, the winner was my favourite and its creator is worth paying for.

Well, this is infuriating. Lots of us who want to contribute don't have access to Discord, or don't want to. Is there a Matrix bridge at least?

**Comment by DennaGherlyn** [comment]
> Is there a Matrix bridge at least?

Yes, the website says there is.

![grafik](https://user-images.githubusercontent.com/13550824/196602643-e7840ea5-a538-4e5d-aa78-bdae944e919d.png)
 [Link](https://matrix.to/#/#prismlauncher:matrix.org)

**Comment by Johnystar** [comment]
@ImSimplySuperior please close

**Comment by Scrumplex** [comment]
> Lots of us who want to contribute don't have access to Discord, or don't want to. Is there a Matrix bridge at least?

Not yet. We are not able to moderate so many platforms at once. We will set this up soon. Right now it's Discord only
