### ISSUE TITLE
"Use system installation of GLFW" not working on NixOS

### ISSUE THREAD

**Issue by hacker1024** [PrismLauncher/PrismLauncher#512]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 5.2

### Version of Qt

Qt 6.4.1

### Description of bug

NixOS uses non-standard locations for libraries. The [Nix package for Prism Launcher](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/prismlauncher/default.nix#L87) adds the GLFW libray folder to `LD_LIBRARY_PATH`.

When the "Use system installation of GLFW" setting is enabled, though, it seems to take no effect. As far as I can tell, the packaged GLFW is not used.

Futhermore, the "Native libraries" list in the instance log is empty (although maybe this is unrelated?).

### Steps to reproduce

1. Install Nix or NixOS
2. Use a custom version of GLFW (see an example with Wayland support below)
3. Enable the "Use system installation of GLFW" setting
4. Start an instance

Example of custom, Wayland-enabled GLFW in use:
```nix
with pkgs; prismlauncher.override {
  glfw = (let
    mcWaylandPatchRepo = fetchFromGitHub {
      owner = "Admicos";
      repo = "minecraft-wayland";
      rev = "370ce5b95e3ae9bc4618fb45113bc641fbb13867";
      sha256 =
        "sha256-RPRg6Gd7N8yyb305V607NTC1kUzvyKiWsh6QlfHW+JE=";
    };
    mcWaylandPatches = map (name: "${mcWaylandPatchRepo}/${name}")
      (lib.naturalSort (builtins.attrNames (lib.filterAttrs
        (name: type:
          type == "regular" && lib.hasSuffix ".patch" name)
        (builtins.readDir mcWaylandPatchRepo))));
  in glfw-wayland.overrideAttrs (previousAttrs: {
    patches = previousAttrs.patches ++ mcWaylandPatches;
  })
```

### Suspected cause

I suspect that the GLFW library is not being searched for in the `LD_LIBRARY_PATH`. How does Prism Launcher look for GLFW?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Are you on 1.19+? There it doesn't work anywhere

**Comment by hacker1024** [comment]
Ah, my bad. It works as expected on 1.18.2. Is the 1.19+ issue noted or tracked anywhere?

**Comment by Scrumplex** [comment]
> issue noted or tracked anywhere?

This used to be tracked in a PolyMC issue. I just created a new one: #513
