### ISSUE TITLE
System installation overrides don't work for Mojang's split natives

### ISSUE THREAD

**Issue by Scrumplex** [PrismLauncher/PrismLauncher#513]
### Operating System

Linux

### Version of Prism Launcher

N/A

### Version of Qt

N/A

### Description of bug

Enabling "Use system installation of GLFW" or "Use system installation of OpenAL" does not work for components that use Mojang's new split natives format (Minecraft 1.19-pre1+, LWJGL 3.3.1).

### Steps to reproduce

Enable `Use system installation of GLFW`
Start an instance with LWJGL 3.3.1

### Suspected cause

Natives are just loaded into classpath. So the old method of not extracting natives we want to override doesn't work any more.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

Originally from PolyMC/PolyMC#643

**Comment by theofficialgman** [comment]
I'm not familiar with how the current override works, but does adding this as a java arg still function?
```
-Dorg.lwjgl.glfw.libname=/usr/lib/libglfw.so
```
(using the correct path depending on the distro/OS ofc)

edit: yes this does still work as is likely what the launcher should be doing for all versions

**Comment by hacker1024** [comment]
If this is implemented, it'd be great if the (default) library location could be set as a build-time variable.

Nix/NixOS, for example, uses non-standard library locations known at build time that aren't easily discoverable at runtime.

**Comment by Scrumplex** [comment]
I was looking into this today, and I can't find a good way to figure out library paths. LWJGL will always try to load the bundled one if we don't give it an absolute path here.

The power of AI gave me this code, which seems to be fine after reading the manpages for dlopen and dladdr, but the `dladdr` call doesn't work :(

```cpp
#include <dlfcn.h>
#include <iostream>

int main() {
    // Open the shared library using dlopen
    void* handle = dlopen("libopenal.so", RTLD_NOW);
    if (!handle) {
        std::cerr << "Error: failed to open shared library: " << dlerror() << std::endl;
        return 1;
    }

    std::cout << handle;

    // Use dladdr to get information about the shared library
    Dl_info info;
    if (dladdr(handle, &info) == 0) {
        std::cerr << "Error: failed to get address information: " << dlerror() << std::endl;
        return 1;
    }

    // Print the absolute path of the shared library
    std::cout << "Absolute path: " << info.dli_fname << std::endl;

    // Close the shared library
    dlclose(handle);

    return 0;
}

```

**Comment by theofficialgman** [comment]
what would be wrong with simply having a text input box under the checkmark for the user to input their own path?

I think that honestly makes more since, because GLFW needs to be built from the master branch at this commit or later https://github.com/glfw/glfw/commit/97da62a027794d9ff0f4512268cb9a73a8fb5073 on lwjgl 3.3.1+ otherwise the game crashes due to missing functionality.

I repeat, none of the distros that I am aware of ship GLFW from the master branch, they all use the latest stable 3.3.8 tag which does NOT work and does not have the functionality necessary to boot the game

**Comment by Scrumplex** [comment]
> what would be wrong with simply having a text input box under the checkmark for the user to input their own path?

Well then we could just remove the checkbox altogether and tell people to set JVM args.

**Comment by theofficialgman** [comment]
> Well then we could just remove the checkbox altogether and tell people to set JVM args.

fair, thats probably what should be done. the existance of the checkbox always caused more issues than it solved. (ie: users clicking it when they didn't have any glfw installed and on older versions that just caused glfw to be missing entirely)

simply documenting the java args on the website/wiki would be enough

**Comment by Scrumplex** [comment]
All LWJGL3 versions support setting absolute paths using system properties.

LWJGL2 does NOT support such system properties. I am not sure if we want to keep these checkboxes around just for LWJGL2 (which only ships with OpenAL as the only one affected anyway)

**Comment by theofficialgman** [comment]
I do potentially see benefit to having the override for openal for lwjgl2. that version is very old and I actually had problems with it not initializing audio for only some hardware on my end on arm64.

the openal binary in lwjgl2 is actually newer on linux-arm64 and linux-arm32 jars for that reason

**Comment by hacker1024** [comment]
What if someone wants to make a package including Prism Launcher and a custom GLFW?

I think it would be nice to keep a checkbox in the launcher, with the option to override the default library path (which could perhaps be set with a build-time or environment variable).

Alternatively, does the launcher support adding general custom launch arguments from an environment variable?

> I repeat, none of the distros that I am aware of ship GLFW from the master branch, they all use the latest stable 3.3.8 tag which does NOT work and does not have the functionality necessary to boot the game

Tweaking the GLFW package to use the master branch is trivial on platforms like Arch Linux and NixOS, and arguably more convenient than leaving a manually built library somewhere to use with Prism Launcher.

**Comment by theofficialgman** [comment]
> Tweaking the GLFW package to use the master branch is trivial on platforms like Arch Linux and NixOS, and arguably more convenient than leaving a manually building a library somewhere to use with Prism Launcher.

for users that have the knowledge and ability to modify system packages, they also don't need a checkbox, they are fully capable of using java args.

**Comment by hacker1024** [comment]
> > Tweaking the GLFW package to use the master branch is trivial on platforms like Arch Linux and NixOS, and arguably more convenient than leaving a manually building a library somewhere to use with Prism Launcher.
> 
> for users that have the knowledge and ability to modify system packages, they also don't need a checkbox, they are fully capable of using java args.

Of course, but my point is more that the location of GLFW installed with a package may not be very easy to manually configure. On NixOS, for example, the location of the library changes with every update.

I'd like there to be a mechanism that allows a library path to be supplied programmatically in some way, through an environment or build-time variable, so that no manual configuration is required.

**Comment by theofficialgman** [comment]
> Of course, but my point is more that the location of GLFW installed with a package may not be very easy to manually configure. On NixOS, for example, the location of the library changes with every update.
> 
> I'd like there to be a mechanism that allows a library path to be supplied programmatically in some way, through an environment or build-time variable, so that no manual configuration is required.

its reallly not proper to depend on a system override to get something to work on your system at all.

there is no guarantee that glfw master branch doesn't break backwards compat with the particular commit that lwjgl 3.3.1 depends on.

if your intention is to fix the build of GLFW lwjgl 3.3.1 so that it runs on NixOS, then your best course of action would be creating natives for it and shipping it as part of the prism meta repo. alternativly, actuallly go a fix the compat layers you use to support GLIBC functions from 2012...

**Comment by hacker1024** [comment]
> its reallly not proper to depend on a system override to get something to work on your system at all.

I didn't say anything about system overrides. I'm talking about the potential for a package that packages Prism Launcher with a custom build of GLFW in a non-standard location.

> if your intention is to fix the build of GLFW lwjgl 3.3.1 so that it runs on NixOS, then your best course of action would be creating natives for it and shipping it as part of the prism meta repo. alternativly, actuallly go a fix the compat layers you use to support GLIBC functions from 2012...

This is not my intention. Minecraft's LWJGL works fine on NixOS; I want to use a patched of GLFW version with better Wayland compatibility.

**Comment by Aleksanaa** [comment]
> > its reallly not proper to depend on a system override to get something to work on your system at all.
> 
> I didn't say anything about system overrides. I'm talking about the potential for a package that packages Prism Launcher with a custom build of GLFW in a non-standard location.
> 
> > if your intention is to fix the build of GLFW lwjgl 3.3.1 so that it runs on NixOS, then your best course of action would be creating natives for it and shipping it as part of the prism meta repo. alternativly, actuallly go a fix the compat layers you use to support GLIBC functions from 2012...
> 
> This is not my intention. Minecraft's LWJGL works fine on NixOS; I want to use a patched of GLFW version with better Wayland compatibility.

same for me, but I'm using Arch Linux with the exact issue you encountered

**Comment by theofficialgman** [comment]
> I didn't say anything about system overrides. I'm talking about the potential for a package that packages Prism Launcher with a custom build of GLFW in a non-standard location.

prism launcher does not come with glfw packaged in it, period. the launcher meta repo (https://github.com/PrismLauncher/meta-launcher/tree/master/org.lwjgl3) points to where the lwjgl-glfw jar comes from. if you want to "package" prism launcher with a custom glfw, then you are automatically talking about a system override since that is the only concept the launcher has for glfw. if you want to include a custom jar for nixOS, arch, or whatever have you, thats a meta script generation addition (https://github.com/PrismLauncher/meta) , not a launcher addition.

I honestly don't see much wrong with a "custom wayland patched" glfw jar being hosted in the meta repo for each version of lwjgl3 as long as the launcher has a toggle added to switch between the default jar and the "custom wayland patched" jar when the launcher is running in wayland mode

**Comment by Scrumplex** [comment]
> I honestly don't see much wrong with a "custom wayland patched" glfw jar being hosted in the meta repo for each version of lwjgl3 as long as the launcher has a toggle added to switch between the default jar and the "custom wayland patched" jar when the launcher is running in wayland mode

I don't see an easy way of doing this in the meta repo that wouldn't be specific to this situation.

**Comment by hacker1024** [comment]
> If you want to "package" prism launcher with a custom glfw, then you are automatically talking about a system override since that is the only concept the launcher has for glfw.

At the moment, the "system" GLFW seems to be located using the `LD_PRELOAD_PATH` environment variable. It can be packaged with a wrapper script that launches Prism Launcher after setting that variable.

The only thing that makes a library a "system" library is its installation in a standard system-wide location. That is not necessary here, nor was it ever suggested.

All I am asking for is a way to retain behaviour similar to this, such that the launcher can be configured to use a custom GLFW library though an environment variable.

**Comment by theofficialgman** [comment]
> All I am asking for is a way to retain behaviour similar to this, such that the launcher can be configured to use a custom GLFW library though an environment variable.

it already can be, read the first reply. java args exist for this purpose https://github.com/PrismLauncher/PrismLauncher/issues/513#issuecomment-1336454960

**Comment by RossComputerGuy** [comment]
This option doesn't work with the Flatpak. I dug inside the Flatpak and can't find `libglfw.so` in any of the library directories.

**Comment by MenacingPerson** [comment]
My personal opinion is that the launcher should have multiple options, like:
```
Native OpenAL library/dll override
[x] [________________________] [autodetect]
Native GLFW library/dll override
[x] [________________________] [autodetect]
Java args
[x] [________________________]
```

etc, also for java 17+ path and java 8 path, memory alloc, etc
