### ISSUE TITLE
INFO: Exiting with 1

### ISSUE THREAD

**Issue by eki-github** [PrismLauncher/PrismLauncher#516]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.2

### Version of Qt

Qt 6.4.0

### Description of bug

https://mclo.gs/NOxX3eR

### Steps to reproduce

I installed java oracle and it didn't work so i installed adoptium.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Does this still happen on the latest release?
Did you try to reinstall Forge from the Version tab?

**Comment by Trial97** [comment]
There were no updates on this for a long time: so I will presume this is fixed.
Please feel free to reopen this if you can reproduce it on the latest release(7.2).
