### ISSUE TITLE
Some modpacks dont have a version available in the new instance menu

### ISSUE THREAD

**Issue by Frontear** [PrismLauncher/PrismLauncher#517]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.2

### Version of Qt

Qt 6.4.0

### Description of bug

When searching for certain modpacks in the new instance menu, Prism cant find a version for them when versions exist online on curseforge

### Steps to reproduce

* New instance
* Search Light Craft on CurseForge
* Select Light Craft 1.19.2 (842% blah blah)
* No versions are found
* On curse, there are versions

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
no versions were found because that modpack is opted out (imagine doing a FO clone and blocking mod distribution LMAOOOOO) but yeah that's why
