### ISSUE TITLE
Prism Launcher modern desing

### ISSUE THREAD

**Issue by ilgrandeanonimo** [PrismLauncher/PrismLauncher#523]
### Role

I don't use prism launcher

### Suggestion

I suggest to make a modern design, like windows 11, macOS, Ubuntu apps. The actual is KDE Style that is not adapt on other platforms/desktop envoirment

### Benefit

This change will be make Prism Launcher better

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I don't use prism launcher for the old desing, i will use it if you redesing it.

**Comment by DioEgizio** [comment]
... what?

**Comment by theofficialgman** [comment]
> ### Role
> I don't use prism launcher
> I don't use prism launcher for the old desing, i will use it if you redesing it.

If you can't bother to even use the launcher then you have no business making suggestions about it.

> I suggest to make a modern design, like windows 11, macOS, Ubuntu apps

There is no such thing as Ubuntu design. The official Ubuntu image uses gnome so maybe you mean using gtk for the UI but that isn't feasible. The QT theming on gtk distros already matches system theming so no issue there.

> The actual is KDE Style

Incorrect. There is nothing KDE about prism Launcher at all. Prism Launcher (and all multimc based launchers) are built using the QT5/6 toolkit. The QT toolkit is used for desktop applications on multiple Linux distros like KDE and LXQT. It is also widely utilized to develop software on embedded systems and on MacOS and Windows.

**Comment by txtsd** [comment]
> I don't use prism launcher

:expressionless:

**Comment by ilgrandeanonimo** [comment]
I installed and tried it but i don't use it normally. MultiMC style is horrible, i suggest to make a minecraft style GUI.

**Comment by meisme-dev** [comment]
> I installed and tried it but i don't use it normally. MultiMC style is horrible, i suggest to make a minecraft style GUI.

That is much more complicated than you might think.

**Comment by ilgrandeanonimo** [comment]
i'm a developer to

**Comment by theofficialgman** [comment]
> i'm a developer to

if you were an actual developer working on QT apps, you would not all the mistakes here: https://github.com/PrismLauncher/PrismLauncher/issues/523#issuecomment-1327939221

your are implying that you know what needs to be done and the amount of effort that it would take to do it.
this issue is closed, if you are a actually developer like you state you are and want it done, do it yourself.

you have not given any constructive feedback in this issue.
simply stating: "MultiMC style UI BAD and _modern design_ UI GOOD" is not constructive

**Comment by ilgrandeanonimo** [comment]
Not QT. However it was just an idea.

**Comment by Secret-chest** [comment]
Quote from my Linux Mint review:
> I may be old-school, but I like the "classic" UI that's not a web browser and is themeable.
