### ISSUE TITLE
Support more languages.

### ISSUE THREAD

**Issue by Cjhcr** [PrismLauncher/PrismLauncher#53]
### Role

l use the PolyMC by other language.

### Suggestion

l want to use the other languages.

### Benefit

I think PolyMC can usually do this.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I would like to use PrismLauncher in other languages, so I think this needs to be added in.

**Comment by DioEgizio** [comment]
i think we already support multilang but the translations link has to be updated

**Comment by TayouVR** [comment]
translations are here: https://hosted.weblate.org/projects/prismlauncher/launcher/

**Comment by Cjhcr** [comment]
ok, so we can translate our language?

**Comment by Cjhcr** [comment]
> translations are here: https://hosted.weblate.org/projects/prismlauncher/launcher/

ok thanks, so basically we can change the language in the formal edition?

**Comment by TayouVR** [comment]
yeah, as Dio said I think just the link somewhere in the translation code needs to be updated, thats all

**Comment by Cjhcr** [comment]
ok thanks for your explanation

**Comment by DioEgizio** [comment]
should be up at this point
