### ISSUE TITLE
Add confirmation button when deleting pack

### ISSUE THREAD

**Issue by OveR1337XD** [PrismLauncher/PrismLauncher#530]
### Role

I play moded Minecraft

### Suggestion

Add confirmation button when deleting pack

### Benefit

So I dont accidentally misclick and delete pack

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

A confirmation button when deleting a pack would be great for use so we don't accidentally delete the pack by miss-clicking. I find it really annoying that it just deletes all pack and save files without confirmation and can lead to accidentally deleting all world and lose everything in one second.

**Comment by Scrumplex** [comment]
See #192 

Instances are not deleted but actually just moved to trash.

**Comment by PanoptesDreams** [comment]
Please close this issue. It is complete as of version 6.0
