### ISSUE TITLE
GTNH modpack: Gamebreak visual bug

### ISSUE THREAD

**Issue by Solaris2565** [PrismLauncher/PrismLauncher#533]
### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.3.0

### Description of bug

Any instance of Gregtech New Horizons I load, once into a world, all that appears is a single color that changes based on where I look. Even supercedes menus, so I can't press any menu buttons.

### Steps to reproduce

Simply load a new GTNH world off the technic portion of the launcher.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by IdrisQe** [comment]
This... doesn't sound like a launcher issue. You should probably report this to GTNH instead.

**Comment by Scrumplex** [comment]
Yeah. If you can reproduce the same issue with a different launcher, then this is an issue with the modpack.
