### ISSUE TITLE
Imported pack icons do not have file extensions

### ISSUE THREAD

**Issue by IdrisQe** [PrismLauncher/PrismLauncher#535]
### Operating System

Windows

### Version of Prism Launcher

5.2

### Version of Qt

6.4.0

### Description of bug

Icons downloaded when selecting a pack from a different site/launcher in the import menu have no file extension, and while they work fine in the launcher, they appear as blank "File" type files in Windows Explorer.

![image](https://user-images.githubusercontent.com/40530630/205019101-4a4a539f-679b-4c76-a879-642dcd2153a0.png)

This can be remedied manually by adding an extension such as .png at the end via a rename, at which point they will function correctly in Windows Explorer and other programs too.

### Steps to reproduce

1. Go to the pack import menu
2. Go to Curseforge, ATLauncher, FTB, FTB Legacy, Modrinth, or Technic sections, and select a pack
3. Either click the pack icon selector do download the icon, or install the pack to download the icon
4. The icon will show up without a file type in the Icons folder

### Suspected cause

Presumably PrismLauncher just downloads the icon and saves it without giving it an actual extension, not sure why.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This should be fixed by https://github.com/PrismLauncher/PrismLauncher/pull/1456
