### ISSUE TITLE
prism can't handle cf modpacks without files in their manifest.json

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#537]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.2

### Version of Qt

Qt 6.4.0

### Description of bug

When downloading FTB Retro SSP from CurseForge the launcher crashes, it shouldn't crash even if the pack is no longer usuable due to breakages by CF.

### Steps to reproduce

Click Add Instance
Select Curseforge
Search for and select FTB Retro SSP
Click OK
Wait for Crash

### Suspected cause

CurseForge seems to be returning invalid or non json data when json data is expected from a specific API end point. (see logs)
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/10134997/PrismLauncher-0.log)

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
i know what's happening here: currently prism can't handle cf modpacks without mods in their manifest
