### ISSUE TITLE
Handle non-downloadable Curseforge modpacks using QTWebEngine

### ISSUE THREAD

**Issue by orowith2os** [PrismLauncher/PrismLauncher#542]
### Goal

Currently, from what I've been told, PrismLauncher handles (or will handle) non-downloadable Curseforge mods/modpacks by the user downloading them, and Prism then checking the downloaded file + checksum to use that.

I want to handle this in a "better" way, as checking the downloaded file can pose potential issues, such as inside of a sandbox (on Linux, Prism has read-only access to ~/Downloads, but this could allow to remove that perm, paired with the use of xdg-desktop-portal for drag n drop, which I think should be handled by QT).

### Motivation

See the end portion of the goal I stated; relying on the user to download mods and reading those files can be an issue inside of a restricted sandbox.

### Specification

I don't have much experience with QT, so this is more or less just an idea....

Detect if Prism is running inside of a sandbox

If running inside of a sandbox, use bundled QTWebEngine (there's a Flatpak baseapp for it, so I don't think using that would be an issue, aside from potentially larger download sizes.)

If not inside of a sandbox, resume with downloading mods as normal (native Linux packages, Windows, etc.)

### Drawbacks

Potentially larger Flatpak/Sandboxed app download sizes

Code complexity, maybe? I don't think there'd be much

### Unresolved Questions

Mainly just concerns over download size, and how it'll be handled over time. Ideally, it'll be deduplicated, but not many apps use the QTWebEngine Flatpak baseapp, I'm pretty sure. 

### Alternatives Considered

Continue to use the (to-be) current method of handling non-downloadable Curseforge mods, which could pose issues if a mod isn't downloaded to ~/Downloads

I have also noticed that there is a QTWebKit baseapp, though I don't think that would be useful if CurseForge doesn't like it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The QTWebEngine Flatpak baseapp is listed here: https://github.com/flathub/de.shorsh.discord-screenaudio/blob/master/de.shorsh.discord-screenaudio.yml

**Comment by barraIhsan** [comment]
So like there is an embedded web browser inside of prism that will download all the mods? That's look easier to the user. Just like what GDLauncher did to non-downloadable Curseforge mods.

**Comment by orowith2os** [comment]
There isn't a browser embedded, but what I'm suggesting would be to hook into one for sandboxed Linux builds to ensure mod downloading works as intended without too many downsides.

**Comment by barraIhsan** [comment]
oh, but why you run prism on a sandboxed in the first place?
Edit: Isn't the flatpak version of Prism is sandboxed?

**Comment by orowith2os** [comment]
Because it keeps my host system clean, is more secure, and I don't have to worry about dependency hell.

**Comment by flowln** [comment]
I don't think this is being considered as an option for now. Maybe when we start using QML and friends it will be a more enticing option, since we'll already have a JS engine anyway...

Feel free to open this again if you want to resurface the discussion around it.
