### ISSUE TITLE
The launcher keeps crashing after I try to copy an isntance

### ISSUE THREAD

**Issue by stantios** [PrismLauncher/PrismLauncher#545]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 6.0-fe16bf24 (develop)

### Version of Qt

Qt 5.15.2, but also happens in 6.3.0

### Description of bug

I tried to copy an instance of mine and rename it to 'Server v2' but then when I clicked ok, the launcher just crashed. Here are my logs: 
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/10148377/PrismLauncher-0.log)

### Steps to reproduce

1. Create a new instance
2. Press 'Copy' in the sidebar
3. Rename the instance to anyhting you want
4. Press 'OK'
5. You've found the crash!

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by cylian914** [comment]
it crash also on  linux (arch, kde) it only happen when you rename, if its the same name it still work, renaming  after work fine
