### ISSUE TITLE
Confirmation before closing "Download mods" window

### ISSUE THREAD

**Issue by ForeverFloating** [PrismLauncher/PrismLauncher#549]
### Role

I play modded Minecraft.

### Suggestion

I want there to be a configurable setting that prompts the user to confirm closing the "Downloaded mods" window when clicking the "X" button.

### Benefit

This will prevent users from accidentally closing the "Downloaded mods" window if there are already many mods selected for download.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
fixed by https://github.com/PrismLauncher/PrismLauncher/pull/2566
