### ISSUE TITLE
Incorrect shorthand unit for minutes

### ISSUE THREAD

**Issue by victorleblais** [PrismLauncher/PrismLauncher#553]
### Operating System

Windows, macOS, Linux

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

This is a cosmetic UI bug and does not impact the behavior of the launcher.

The playtime is shown as, for example, "3d 4h 26m". This is incorrect. `m` is the unit for meters and meters only.

The unit for minutes is `min`, not `min.`, not `m`, just `min`.

### Steps to reproduce

1. Open Prism Launched
2. Check total playtime in bottom right of the window (or click on an instance and check playtime in bottom left)

### Suspected cause

This is just a simple case of misunderstanding on how units and their symbol work.

Using correct units is important. For example, imagine two people talking about running:

- "How long did you last?"
- "I lasted for 25m"

Which creates a misleading information: did they last for 25 minutes or 25 meters before being too exhausted? You wouldn't use `mi` for minutes because it would create confusion with miles. Anyway, it should be a simple fix, I hope.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by edgarogh** [comment]
This is probably the only file that needs to be changed

https://github.com/PrismLauncher/PrismLauncher/blob/a9d4370ad462b4ad3dd91f6bc38b40262967b5b2/launcher/MMCTime.cpp#L22-L38
