### ISSUE TITLE
certain Curseforge Mods failing to install

### ISSUE THREAD

**Issue by StickyChannel92** [PrismLauncher/PrismLauncher#558]
### Operating System

Windows 11

### Version of Prism Launcher

Prism Launcher 5.2

### Version of Qt

Qt 6.4.0

### Description of bug

Most mods from curseforge don't download, and instead give the error "Error while creating new instance". No error details were provided by error message. Another scenario is where the mod attempts to add mods, while a different error shows that the download is being blocked by something, and my VPN is turned off.

### Steps to reproduce

1. Click Add Instance
2. Click Curseforge
3. Type in "divine journey". (or "enigmatica 2 expert"
4. Install Divine Journey 2 or Enigmatica 2 Expert.
5. Error message appears

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Send prismlauncher-0.log from the prism data path

**Comment by StickyChannel92** [comment]
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/10168907/PrismLauncher-0.log)

**Comment by Ryex** [comment]
You were trying to install `Enigmatica 2: Expert - E2E` correct?

This appears to be the main cause of the failure.
```
  863.055 W Failed to move "C:/Users/sagan/AppData/Roaming/PrismLauncher/instances/.LAUNCHER_TEMP/{1c434915-7540-466e-8138-fa81ca7883aa}" to "C:/Users/sagan/AppData/Roaming/PrismLauncher/instances/Enigmatica 2- Expert - E2E"
  863.055 D Failed to commit instance "Enigmatica 2: Expert - E2E " Initiating backoff: 1
  863.556 W Failed to move "C:/Users/sagan/AppData/Roaming/PrismLauncher/instances/.LAUNCHER_TEMP/{1c434915-7540-466e-8138-fa81ca7883aa}" to "C:/Users/sagan/AppData/Roaming/PrismLauncher/instances/Enigmatica 2- Expert - E2E"
  863.556 D Failed to commit instance "Enigmatica 2: Expert - E2E " Initiating backoff: 2
  864.554 W Failed to move "C:/Users/sagan/AppData/Roaming/PrismLauncher/instances/.LAUNCHER_TEMP/{1c434915-7540-466e-8138-fa81ca7883aa}" to "C:/Users/sagan/AppData/Roaming/PrismLauncher/instances/Enigmatica 2- Expert - E2E"
  864.554 D Failed to commit instance "Enigmatica 2: Expert - E2E " Initiating backoff: 4
  866.555 W Failed to move "C:/Users/sagan/AppData/Roaming/PrismLauncher/instances/.LAUNCHER_TEMP/{1c434915-7540-466e-8138-fa81ca7883aa}" to "C:/Users/sagan/AppData/Roaming/PrismLauncher/instances/Enigmatica 2- Expert - E2E"
  866.555 D Failed to commit instance "Enigmatica 2: Expert - E2E " Initiating backoff: 8
  870.556 W Failed to move "C:/Users/sagan/AppData/Roaming/PrismLauncher/instances/.LAUNCHER_TEMP/{1c434915-7540-466e-8138-fa81ca7883aa}" to "C:/Users/sagan/AppData/Roaming/PrismLauncher/instances/Enigmatica 2- Expert - E2E"
  870.556 C Task "InstanceStaging(0x18bca6c7f10)" failed:  "Failed to commit instance, even after multiple retries. It is being blocked by something."
```

The mod pack get downloaded successfully to it's temporary build locations but  `QDir:rename` fails to copy it to the instance folder.

There are many reasons this could fail. But the main ones are :

  * Target folder `C:/Users/sagan/AppData/Roaming/PrismLauncher/instances/Enigmatica 2- Expert - E2E` already exists 
  * A file in the temp location is open and can't be moved.
  * Considering your on windows, Antivirus is locking things down.

Can you help us narrow down or eliminate any of these possibilities?

**Comment by StickyChannel92** [comment]
Definitely the antivirus. If any file is open in %temp%, then those are generated by Google Chrome. No such folder exists when failing to download the modpack.

I was able to download Divine Journey 2 and E2E with ease.

**Comment by OverwatchReaper** [comment]
the links are very much broken dude the curseforge mod links are busted too
