### ISSUE TITLE
Automatically update mod loader when Minecraft version is changed

### ISSUE THREAD

**Issue by j-tai** [PrismLauncher/PrismLauncher#562]
### Role

I play the latest version of Minecraft with Fabric

### Suggestion

When the user changes the Minecraft version, Prism should automatically update the mod loader (Forge/Fabric/intermediary mappings) to a compatible version.

### Benefit

If the user forgets to update the mod loader, they will get a nasty and confusing crash when launching the game. Updating the mod loader automatically means this crash can't happen.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

After changing the Minecraft version, we get this:

![image](https://user-images.githubusercontent.com/45131430/206068884-93781276-6a2b-4815-88fa-56ea9a3cebf3.png)

The intermediary mappings are incompatible with the chosen Minecraft version, which causes this instance to crash on launch. Ideally, a situation like this should not be possible.

**Comment by ghost** [comment]
mappings yes, loader no

please do not limit user freedom, if they want to run mc with some hilariously outdated loader let them do so

**Comment by j-tai** [comment]
Sorry, I should clarify - I meant that the launcher should automatically update the version if it's incompatible. If the loader is old but compatible then it can be left alone.

And even if it does update the loader, how does that limit user freedom? They can still change the loader version if they want. I never said to remove the ability to choose the version. I just want the launcher to be helpful and automatically resolve incompatibilities.

**Comment by ghost** [comment]
I mean this could be an option in settings for those who need it but prism is really reluctant to add configurable opinionated features for some reason

**Comment by oddvar812** [comment]
When you change version, there can be a small pop-up window that says something like "you have an outdated version of ... would you like to automatically change it to the recommended version". then there is a "yes" and a "no" button, and a "do not ask again" box. I think this would resolve the issue of giving the user less control, while still having the easiest option transparent for less technical users.
