### ISSUE TITLE
Modpack Import/Extract fails when pack has illegal characters in resource pack name

### ISSUE THREAD

**Issue by pog5** [PrismLauncher/PrismLauncher#564]
### Operating System

Windows, Linux

### Version of Prism Launcher

Confirmed on Prism Launcher 5.2
And on Prism Launcher [5ae044d](https://github.com/PrismLauncher/PrismLauncher/actions/runs/3632947251)

### Version of Qt

Qt 6.4.0 running on Windows 10 LTSC 2021

### Description of bug

Trying to download or import a modpack with illegal characters in one of its files (such as some resource packs being pre color-named) [Example: \u00A7 aka §]) will fail with the launcher not being able to extract it.

### Steps to reproduce

Any modpack with a custom colored resource pack should work but for this example I will use (Cottage Witch)[https://www.curseforge.com/minecraft/modpacks/cottage-witch/] with (this release)[https://www.curseforge.com/minecraft/modpacks/cottage-witch/files/4136533] (newest at issue time)
1. Download your modpack through Curseforge from the Create instance dialog on the left or try importing a ZIP 
2. Extraction will fail with something similar to:
```
"C:/Users/*****/AppData/Roaming/PrismLauncher/instances/.LAUNCHER_TEMP/{2429a909-efff-49df-b1d8-c8a9f2e79af7}/overrides/config/paxi/resourcepacks/xksp-naturalize.zip"
   23.043 W Failed to extract file "overrides/config/paxi/resourcepacks/\u00156Breadier Breads\u00158[v1].zip" to "C:/Users/******/AppData/Roaming/PrismLauncher/instances/.LAUNCHER_TEMP/{2429a909-efff-49df-b1d8-c8a9f2e79af7}/overrides/config/paxi/resourcepacks/\u00156Breadier Breads\u00158[v1].zip"
   23.044 C Task "InstanceImportTask(0x1f9eeb02d20)" failed:  "Failed to extract modpack"
   23.120 C Task "InstanceStaging(0x1f9ef5bbce0)" failed:  "Failed to extract modpack"
   ```

### Suspected cause

Unicode characters being able to escape the extraction method's arguments and/or being ignored which makes it point to a invalid file.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Xplodin** [comment]
also still getting this which is forcing me to rename certain files in my modpack.
Prevents the entire installation

**Comment by AoSankaku** [comment]
Still same on PrismLauncher 7.2-Qt6.5.1

**Comment by Trial97** [comment]
> Still same on PrismLauncher 7.2-Qt6.5.1

Are you on linux or windows?
Can you post a link to the failing modpack? With the given link I can not reproduce it on linux.

**Comment by AoSankaku** [comment]
> > Still same on PrismLauncher 7.2-Qt6.5.1
> 
> Are you on linux or windows? Can you post a link to the failing modpack? With the given link I can not reproduce it on linux.

I'm on Windows and I'm experiencing this on my private modpack.
In my modpack (zip for PrismLauncher), a resource pack zip archive file with Chinese name exists. With this zip file, the exported modpack can't be imported. Removing resource packs solved the problem, so the bug appears to be the same.

Sorry for my insufficient information. I hope this is helpful for fixing the issue.

**Comment by TheKodeToad** [comment]
https://github.com/PrismLauncher/PrismLauncher/pull/2225 will fix exported packs not being importable if they have non-ascii characters 

However, [this file](https://www.curseforge.com/minecraft/modpacks/cottage-witch/files/4136533) is broken - it's not technically a launcher issue that it can't be opened. Since it works with CurseForge though, we should probably copy their behaviour of ignoring the invalid characters.
