### ISSUE TITLE
The procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll

### ISSUE THREAD

**Issue by moon91210** [PrismLauncher/PrismLauncher#566]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.2
Windows 7 x64

### Version of Qt

-

### Description of bug

Failed to launch prismlauncher.exe on windows 7, it's giving this error:

The procedure entry point createdxgifactor2 could not be located in the dynamic link library dxgi.dll.

### Steps to reproduce

-

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
https://prismlauncher.org/wiki/overview/frequent-issues/#windows-7-and-8.1
