### ISSUE TITLE
InstanceCopyTask progressbar is broken

### ISSUE THREAD

**Issue by Scrumplex** [PrismLauncher/PrismLauncher#573]
### Operating System

Linux

### Version of Prism Launcher

cb0339b4920011a915fcdb77820b55211c0103fc

### Version of Qt

N/A

### Description of bug

When copying an instance, the progress bar of the task doesn't update

### Steps to reproduce

yes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Most progress bars are broken tbh, just try downloading a modpack and see it never actually updating
