### ISSUE TITLE
The game suddenly went dark after I joined a server (I tried setting it to default but it didn't work)

### ISSUE THREAD

**Issue by EldraTheThird** [PrismLauncher/PrismLauncher#578]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.2

### Version of Qt

Qt 6.4.0

### Description of bug

When I start the game, it looks normal and there are no problems. But when I join a world or a server, the game suddenly goes dark (see the picture to understand what I mean) 
![2022-12-10_19 26 47](https://user-images.githubusercontent.com/108326998/206855085-6bb6c1a5-483a-4581-81de-907d3d51475a.png)
![2022-12-10_19 26 50](https://user-images.githubusercontent.com/108326998/206855088-be9cf8cd-f3a0-467e-9579-0860f6595845.png)
![2022-12-10_19 27 00](https://user-images.githubusercontent.com/108326998/206855090-4241a3c1-9fac-437f-b79f-c9b195bc5acc.png)

### Steps to reproduce

No, i'm only play LabyMod

### Suspected cause

I don't know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by EldraTheThird** [comment]
P/S: and quite interestingly, it only works when I use an Offline account

**Comment by TheKodeToad** [comment]
Maybe some logs will help...

**Comment by EldraTheThird** [comment]
[latest.log](https://github.com/PrismLauncher/PrismLauncher/files/10201410/latest.log)

**Comment by PanoptesDreams** [comment]
I don't think this has anything to do with Prism..

Contact your Pack Developer

**Comment by Trial97** [comment]
> I don't think this has anything to do with Prism..
> 
> Contact your Pack Developer

I agree it doesn't look like a Prism issue
