### ISSUE TITLE
No way to re-enable toolbar and news bar on macOS

### ISSUE THREAD

**Issue by upstroke-version** [PrismLauncher/PrismLauncher#579]
### Operating System

macOS 13

### Version of Prism Launcher

5.2

### Version of Qt

6.3.0

### Description of bug

There is no way to re-enable toolbar and news bar after disabling it on macOS version of prism launcher.

### Steps to reproduce

1. launch prism lancher on mac
2. right click lancher window
3. disable toolbar and news bar
4. now if you right click again there is no option to re-enable it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
right click on the top toolbar

**Comment by upstroke-version** [comment]
> right click on the top toolbar

wow... that was really simple.
I was viewing app's setting, googling the problem, inspecting app's config file for like 30 minutes.
now I feel stupid...
