### ISSUE TITLE
Icons for the sidebar stay aligned to the left

### ISSUE THREAD

**Issue by stantios** [PrismLauncher/PrismLauncher#580]
### Version of Prism Launcher

Prism Launcher 6.0-develop

### Version of Qt

Qt 5.12.2

### Description of bug

All the icons the the sidebar stay aligned to the left as seen in this picture. I'm not sure if this is intended or not: 
![image](https://user-images.githubusercontent.com/98621617/206863616-5cf82889-06c8-4422-962d-f7e75f14a518.png)

### Steps to reproduce

1. Download the latest Github Action (MacOS Legacy version)
2. Extract and Open Prism Launcher
3. Put the sidebar to the left
4. You've found the bug!

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
https://github.com/PrismLauncher/PrismLauncher/blob/4a13d72997d4ed4d7f0df72c80c6e0aaabfea1e0/launcher/ui/MainWindow.cpp#L833

the reason is that else it'd behave weirdly with custom themes (see https://discord.com/channels/1031648380885147709/1033550967154675732/1037783213034188871)

**Comment by stantios** [comment]
I'm not using any custom themes though.

**Comment by DioEgizio** [comment]
i meant that that is there for that reason

**Comment by stantios** [comment]
Oh, I see. I guess this can be closed then
