### ISSUE TITLE
right click- open with- prism launcher (zip/mrpack) doesn't work on linux

### ISSUE THREAD

**Issue by DioEgizio** [PrismLauncher/PrismLauncher#581]
### Operating System

Linux

### Version of Prism Launcher

develop

### Version of Qt

qt 5.15.7

### Description of bug

right click- open with- prism launcher should open the modpack/rpack installing dialog with zip/mrpack, but it just gives... nothing

### Steps to reproduce

- right click- open with- prism launcher on a zip or a mrpack
- see prism launching normally

### Suspected cause

idk but when opening on a terminal 

prismlauncher path/to/file

it gives

QLocalSocket::setServerName() called while not in unconnected state

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Was Prism already running? I assume this isn't passed to the already running app using LocalPeer

**Comment by DioEgizio** [comment]
For the error in terminal yeah, but right click-open with- prism launcher doesn't work even when prism is closed

**Comment by Ryex** [comment]
This is because the open-with command on Linux is relying on the `.desktop` file and not passing the `-I` flag.
Personally I think that if passed a positional argument that is a file path Prism should detect that file type and handle it accordingly.
