### ISSUE TITLE
Some FTB Packs Using Incorrect Icon

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [PrismLauncher/PrismLauncher#582]
### Operating System

Windows

### Version of Prism Launcher

PrismLauncher 5.2

### Version of Qt

Qt 6.4.0

### Description of bug

Some FTB packs, specifically old packs that have newer versions, use the wrong icon. This only happens to packs that are named with a version number.

![FTB Academy](https://user-images.githubusercontent.com/69123018/206873087-8505bb81-7b6e-45cc-8513-ff57d68eec6f.png)
![FTB University](https://user-images.githubusercontent.com/69123018/206873089-700b399f-8f8b-406c-9fb6-aeef2f06f2c3.png)
![FTB Presents Direwolf20](https://user-images.githubusercontent.com/69123018/206873088-ca5fd906-c277-4479-a657-2dd556d5d909.png)
![FTB Unstable](https://user-images.githubusercontent.com/69123018/206873394-9a2d6195-b88b-4727-8bf8-060675cbeff4.png)

### Steps to reproduce

Look at the FTB Packs

### Suspected cause

Probably something somewhere with how FTB names their packs for their API, but honestly I have no clue. I think this because As shown in the 3rd screenshot, the packs that don't use the same naming convention use the correct icons.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
This smells like a bug in modpacks.ch

**Comment by DioEgizio** [comment]
nope it's not an issue with modpacks.ch, the modpacks.ch api returns the right icons hmmm

maybe an issue with caching?

**Comment by Scrumplex** [comment]
As part of dropping FTB support, this issue is no longer relevant. See #1040
