### ISSUE TITLE
Add Prism to the windows list of apps

### ISSUE THREAD

**Issue by MIfoodie** [PrismLauncher/PrismLauncher#583]
### Role

So we can find the program...

### Suggestion

Add it to the list of apps when the

### Benefit

It's easier to find the program and run it..

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
what does this even mean?

**Comment by ghost** [comment]
I think they're talking about the windows start menu

**Comment by Scrumplex** [comment]
You can already let it create a shortcut in your start menu when installing Prism.

If you mean something else, feel free to reopen the issue.
