### ISSUE TITLE
[Feature Request] Filter by Modrinth category when using the mod downloader

### ISSUE THREAD

**Issue by eff3ry** [PrismLauncher/PrismLauncher#588]
### Role

I play modded minecraft

### Suggestion

Add Options to filter mods by category under the filter button in the download

### Benefit

Make finding mods for specific needs easier, i.e. looking for just optimization mods

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Add Options to filter mods by category under the filter button in the download mods window,
these options would be individually toggleable to you can filter for more than one category at once,
If the Modrinth API allows pulling the list of available categories it would be nice for these filters to dynamically update if Modrinth makes changes to their categories, i.e. if a new category is added it will automatically add a filter in PrisimLauncher

Modrinth's API allows searching with categories via facets see: https://docs.modrinth.com/docs/tutorials/api_search/

I've made a mock-up in photoshop as to what this could look like:
![MockUp](https://user-images.githubusercontent.com/18133966/206946559-8f61da84-ed58-453c-93b5-0c5a0137456f.png)

**Comment by eff3ry** [comment]
I've never worked with Qt before so I'm not sure how I'd go about adding the tab in but I believe `launcher/ui/pages/modplatform/ModPage.cpp` possibly even `launcher/ui/widgets/ModFilterWidget.cpp` are relevant to this.

**Comment by goodboy10** [comment]
`launcher\ui\widgets\ModFilterWidget.cpp` `launcher\ui\pages\modplatform\ModPage.cpp` relevant files? I've not really worked with Qt before 😅
