### ISSUE TITLE
Cannot launch in online mode after system is suspended

### ISSUE THREAD

**Issue by wahfl2** [PrismLauncher/PrismLauncher#592]
### Operating System

Windows 10

### Version of Prism Launcher

Prism Launcher 5.1
(assume it still happens in 5.2)

### Version of Qt

Qt 6.4.0

### Description of bug

Launcher works as intended before putting my computer in "sleep" mode.
After "waking" it up, the launcher is unable to launch in online mode, and instead prompts me to play offline.

Note: This is fixed after I restart the launcher. 
I have experienced this bug on a multitude of different Windows devices; have not tested other operating systems.

### Steps to reproduce

Open Prism
Put computer in sleep mode
Turn computer back on
Press launch on an instance

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by J-SoG-YK** [comment]
This problem persists in Prism Launcher 6.0.

I have found a workaround that does not require restarting the launcher.  If you click the Account drop down, select Manage Accounts, select the offline account, and finally click on Refresh, you can then launch instances with the desired account.

Perhaps, this procedure could be shortened by forcing an account refresh on the selection of an account from the Account drop down/keyboard shortcut?

**Comment by ThaBluNate** [comment]
Still in 6.1.

I'm on a _laptop._
All I want is a "`Refresh Account`" button on the offline mode interface
(Below is what I suggest, but I'm no UI designer)
![Untitled](https://user-images.githubusercontent.com/51035517/215272285-26e1bc70-fc89-4b81-880f-50a591993a35.png)

All it needs to do is refresh the currently selected account, close the window, and try to load Minecraft again

**Comment by Xenapte** [comment]
Same problem here. I often put my laptop in the hibernation mode because I have to carry it around, and every time my accounts become offline after resuming. Restarting the launcher or manually refreshing is just too much hassle for me.

**Comment by Spongman** [comment]
I just switch to Prism from MultiMC and started seeing this issue: can't start online after sleep. never saw it with MultiMC.

**Comment by Qwerty-Space** [comment]
Is this bug being worked on at all?

It's making this launcher unusable
