### ISSUE TITLE
Extend the sidebar buttons

### ISSUE THREAD

**Issue by CrimsonFork** [PrismLauncher/PrismLauncher#594]
As of 6.0, the buttons for the selected instance are only as long as their text - it would be a welcome change to extend them all the way to the right.

**Comment by TayouVR** [comment]
we did try that, with varying rates of success. It seems some peoples themes align the text in the center if we stretch the button. i suppose we could just do it anyways and those people will have to fight their theme i guess, but its not ideal...
~~maybe in the future QML can save us?~~

**Comment by he3als** [comment]
would be good if it was centred as well imo

**Comment by CrimsonFork** [comment]
Not a perfect solution, but certainly better than this.
