### ISSUE TITLE
Many of prism's online services do not work with the latest update

### ISSUE THREAD

**Issue by Frontear** [PrismLauncher/PrismLauncher#597]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.0

### Version of Qt

Qt 6.4.1

### Description of bug

Trying to view the modpack update in instance settings, trying to import a new modpack from curse, ftb, modrinth, etc should work as intended. Instead, there is a blank screen and no matter how long you wait, nothing happens

### Steps to reproduce

* Attempt to create a new instance with modpacks
* Alternatively: View a modpack instance and try to update it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Frontear** [comment]
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/10211136/PrismLauncher-0.log)

Unless this is a firewall issue on my end, I'm not sure what's going on. I can view the urls mentioned in the log through chrome fine.

**Comment by DioEgizio** [comment]
you haven't extracted a file (qschannelbackend.dll). Also use the msvc build
