### ISSUE TITLE
Party Cat was moved to the wrong corner

### ISSUE THREAD

**Issue by IC3P3** [PrismLauncher/PrismLauncher#598]
### Version of Prism Launcher

Prism Launcher 6.0

### Version of Qt

Qt 5.15.7

### Description of bug

The cat should be in the top right corner but is instead in the buttom left one and therefore on top under the instance icons.

### Steps to reproduce

The cat was still shown before the start but pressing the button twice to refresh the cat didn't help neither did restarting

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
> The cat should be in the top right corner but is instead in the buttom left one and therefore on top under the instance icons.

expected behaviour since https://github.com/PrismLauncher/PrismLauncher/pull/372
