### ISSUE TITLE
Option to enable checking for updates for disabled mods

### ISSUE THREAD

**Issue by BeeFox-sys** [PrismLauncher/PrismLauncher#603]
### Role

I play modded minecraft

### Suggestion

Allow me to update disabled mods

### Benefit

This allows me to disable mods that aren't up to date, but still check for updates in order to see when they are ready to be enabeld

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ghost** [comment]
i have no idea how updating disabled mods could cause duplication issues which can't be easily fixed
