### ISSUE TITLE
Prism Launcher 6.0 crashes when trying to import a Curseforge modpack from zip

### ISSUE THREAD

**Issue by emkirsh** [PrismLauncher/PrismLauncher#609]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 6.0

### Version of Qt

Qt 6.3.0

### Description of bug

After updating to Prism Launcher 6.0, I tried to import a friend's Forge 1.19.2 modpack using the import zip file button on a new instance. I had never previously had issues importing a curseforge modpack before this update, and importing packs that were exported from Prism still works fine. I also tried importing a pack that worked fine on 5.2. The issue happened with multiple different CurseForge packs that my friends made (two are attached below - one forge and one fabric), but only seems to be affecting imported CurseForge zips -- downloading published packs from the GUI works fine.

### Steps to reproduce

1. Import [this zip file](https://drive.google.com/file/d/19Ti04slzwRqp7GCpzE9aA7Dx-RSvMbI9/view?usp=share_link) on Prism Launcher 6.0 on an M1 macbook ([or this](https://drive.google.com/file/d/1W4NqsNtl9TYs0vZ5u96xcC53dUcMllA9/view?usp=share_link))
2. [Watch it crash](https://gist.github.com/emkirsh/23446a7ce8cef790bfac3f516e6bd488)

### Suspected cause

I think the cause of the bug is the latest 6.0 update. Edit: @unclamped added that this has nothing to do with M1 and was able to get much more helpful system output on their crash to find out that it was a segmentation fault.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by unclamped** [comment]
This has nothing to do with you running on an M1. I am also experiencing the same issue on an x86_64 Arch Linux install, running the latest git version. It is worth mentioning that it is a seg fault causing the crash.
The steps are similar, a CurseForge modpack in version 1.19.2 in zip format.
I suggest you edit the issue's name to express this new information.

Output:
```...
    7.793 D Extracted file "logo.png" to "/home/ducky/.local/share/PrismLauncher/instances/.LAUNCHER_TEMP/{f9673057-3bc1-4dcc-a675-4b10082e1f99}/overrides/resourcepacks/Graphics/logo.png"
    7.794 D Extracted file "lps.png" to "/home/ducky/.local/share/PrismLauncher/instances/.LAUNCHER_TEMP/{f9673057-3bc1-4dcc-a675-4b10082e1f99}/overrides/resourcepacks/Graphics/lps.png"
    7.794 D Extracted file "mojang.png" to "/home/ducky/.local/share/PrismLauncher/instances/.LAUNCHER_TEMP/{f9673057-3bc1-4dcc-a675-4b10082e1f99}/overrides/resourcepacks/Graphics/mojang.png"
    7.794 D Fixing permissions for extracted pack files...
zsh: segmentation fault (core dumped)  prismlauncher```

**Comment by emkirsh** [comment]
Ok will update

**Comment by unclamped** [comment]
Nice! Thanks

**Comment by Dbenjamy** [comment]
I am having the same issue. When I import any modpack from a zip file, the loading bar saying it is extracting the modpack pops up, then the whole program quits.
