### ISSUE TITLE
Please move the cat back to the right, and make it a bit smaller :(

### ISSUE THREAD

**Issue by TheWind32** [PrismLauncher/PrismLauncher#611]
### Role

Yes

### Suggestion

I want to be able to see the cat again

### Benefit

So that I can see the cat whenever I want

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://user-images.githubusercontent.com/67288861/207515770-433353f3-21eb-4e2f-adce-48ed5a00b76c.png)
The 6.0 update made it so the cat is obscured by my instances :(
It would be cool if it was all the way to the right, and a tad bit smaller.

**Comment by PanoptesDreams** [comment]
Counter request, remove the cat.

Explain: Why does it even exist? Let me remove it.
