### ISSUE TITLE
in the pack changelog viewer images aren't displayed and links don't work

### ISSUE THREAD

**Issue by DioEgizio** [PrismLauncher/PrismLauncher#615]
### Operating System

Windows, macOS, Linux, Other

### Version of Prism Launcher

6.0

### Version of Qt

Qt 6.3.0

### Description of bug

in the pack changelog viewer images aren't displayed and links don't work
to see this, try to download the valhelsia 5 pack and go to the cf tab

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/83089242/207584626-3755b21b-c116-4fdd-bb44-3b8f74487f30.png">
as you can see, images aren't displayed and clicking on the link causes
<img width="285" alt="image" src="https://user-images.githubusercontent.com/83089242/207584752-735a5982-36d5-463d-8e5c-0b77d739b098.png">

### Steps to reproduce

.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by scamdotnet** [comment]
Just confirming that I am having the same issue with both images and links, on Windows and Linux. I am using Prism Launcher 7.0, with Qt version 6.5.1 on both OSes. I am noticing this bug occurring not just in Valhelsia 5, but in the changelog for Vault Hunters 3rd Edition as well (which has links, but no images).
