### ISSUE TITLE
Old versions have a resource packs page and are missing a texture pack page

### ISSUE THREAD

**Issue by jopejoe1** [PrismLauncher/PrismLauncher#617]
### Operating System

Linux

### Version of Prism Launcher

e05ccc0e55488837eb8f6f88354a2f8a90ce2474

### Version of Qt

qt 5.15.7

### Description of bug

Version that have texture packs instead of resource packs do not show the texture pack page, but show the resource packs page. Versions that don't support texture or resource packs still show a resource packs page.

### Steps to reproduce

- Edit an Instance of a version that uses texture packs instead of resource packs (1.4.7 for example)
- look for texture pack tab

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
<img width="1215" alt="." src="https://user-images.githubusercontent.com/83089242/207630522-c9a794ee-f7a7-4419-9401-adf7a9d8f65e.png">


cannot reproduce

**Comment by jopejoe1** [comment]
Looks like it was some issue with my meta cache after delting it and refreshing the it works as intended.
