### ISSUE TITLE
Custom Icon Size

### ISSUE THREAD

**Issue by vengent** [PrismLauncher/PrismLauncher#623]
### Role

For Modded Minecraft

### Suggestion

The ability to resize icon size

### Benefit

to see more instances on the screen at once

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Pretty simple request.  An Icon size setting to get more instances on screen at once.

**Comment by Aces-and-Jacks** [comment]
There's a website you can use to resize icons, up to a certain size but I'm not sure what

**Comment by Aces-and-Jacks** [comment]
https://safeimagekit.com/image-resize
this is what I used

**Comment by Aces-and-Jacks** [comment]
Unless you mean both the icons and text size. If you mean that then never mind

**Comment by vengent** [comment]
I mean the size of the button on the main page to launch an instance, not the graphic that is used skin the button.

**Comment by RokeJulianLockhart** [comment]
It should adhere to the system icon size.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/42837531/c5b98d7f-cca5-4872-8d16-4204fba5147e)

**Comment by vengent** [comment]
I'm requesting it to not be system constrained, and available to be modified just in prism.

**Comment by RokeJulianLockhart** [comment]
They're not mutually exclusive. Just provide a checkbox for system adherence, and an input form for a custom value if that checkbox is disabled.

**Comment by Trial97** [comment]
Merged in: https://github.com/PrismLauncher/PrismLauncher/issues/324
