### ISSUE TITLE
Crash when clicking on Resource Packs tab if too many RPs are added

### ISSUE THREAD

**Issue by RuiNtD** [PrismLauncher/PrismLauncher#624]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.0

### Version of Qt

Qt 6.4.0

### Description of bug

Having too many resource packs added to an instance causes Prism Launcher to crash when switching to the Resource Packs tab. Interestingly, this doesn't happen if RPs are added after loading the Resource Packs tab, even if the tab is closed and re-opened. For me, 6 or more RPs is enough to crash Prism Launcher.

### Steps to reproduce

* Open Prism Launcher and create a new instance
* Edit the instance and open the Resource Packs tab
* Click "View Folder" on the bottom right to open the `resourcepacks` folder
* **Fully close** Prism Launcher
* Add a resource pack, such as [Faithful](https://modrinth.com/resourcepack/faithful-32x), to the `resourcepacks` folder
* Select the file from within `resourcepacks` and press `Ctrl-C` to copy the file
* Press `Ctrl-V` about 10 times to create about 10 copies of the resource pack
* Re-open Prism Launcher
* Edit the instance and open the Resource Packs tab

### Suspected cause

funni memory allocation

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TayouVR** [comment]
I can reproduce, this seems to be a regression from 5.2
(I have a global (symlinked) resourcepacks folder with approx. 50 resourcepacks)
