### ISSUE TITLE
When trying to retrieve required library files of Minecraft 1.18.2, it crashes.

### ISSUE THREAD

**Issue by SeyfertGames** [PrismLauncher/PrismLauncher#629]
### Version of Prism Launcher

Prism Launcher 6.0

### Version of Qt

Qt 6.4.0

### Description of bug

When trying to retrieve required library files of Minecraft 1.18.2, it crashes.

### Steps to reproduce

Make a 1.18.2 instance, click launch.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
check if you don't have any broken meta server in settings or smth like that. Either way send PrismLauncher-0.log

**Comment by Trial97** [comment]
Closing this as there were no updates.
