### ISSUE TITLE
AUR PKG?

### ISSUE THREAD

**Issue by mei1212123** [PrismLauncher/PrismLauncher#63]
### Goal

I'm wondering if there is an AUR pkg for the launcher so people on Arch based distros can install Prism 

### Motivation

arch people can install the launcher without building the pkg manually 

### Specification

upload the pkgbuild on the aur or the makefile I don't know the specifics tho 

### Drawbacks

idk 

### Unresolved Questions

idk 

### Alternatives Considered

bin pkg on aur so people don't spend 3 million years compiling 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by mei1212123** [comment]
![image](https://user-images.githubusercontent.com/71238085/196489310-bb00cab0-1823-4146-bc94-8aebe835bf7d.png)
FUCK im stupid

**Comment by RoootTheFox** [comment]
Once the first release is out, there will be AUR packages. Right now there are no releases (rebrand is not finished yet), however prismlauncher-git is a thing

**Comment by mei1212123** [comment]
Will there be a bin pkg?

**Comment by RoootTheFox** [comment]
Yes, I am pretty sure (polymc had one, so prism will likely have one too)

**Comment by jkhsjdhjs** [comment]
> Will there be a bin pkg?

Are you serious? :D
https://aur.archlinux.org/packages?O=0&K=prismlauncher

**Comment by mei1212123** [comment]
> > Will there be a bin pkg?
> 
> Are you serious? :D https://aur.archlinux.org/packages?O=0&K=prismlauncher

its so new idk bruh lmfao but thanks for the link
