### ISSUE TITLE
Prism lags when opening the instance page with long logs

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#633]
### Version of Prism Launcher

6.0

### Version of Qt

6.3.0

### Description of bug

I click edit to go to edit an instance and prism loads for a few minutes before showing the console window. It should've gone to the console window immediately

### Steps to reproduce

1. Click edit
2. Wait a few minutes before it shows

### Suspected cause

I think it may be caused after going out of an instance but I'm not sure cause it's inconsistent. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment]
It's happened on previous versions too I just ignored it at the time

**Comment by Aces-and-Jacks** [comment]
edit: I'm going to take this off then

Here's the log file. Wasn't sure if you'd need this

**Comment by DioEgizio** [comment]
This is because it's a lot of logs to open

**Comment by Aces-and-Jacks** [comment]
oh. so then that's normal behavior sometimes? It's not an issue?

**Comment by Aces-and-Jacks** [comment]
Do I close this then, or leave it open?

**Comment by flowln** [comment]
You can keep it open, it *is* an issue. See https://github.com/PolyMC/PolyMC/issues/604

**Comment by DioEgizio** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/463

**Comment by flowln** [comment]
d-did i get Dioed? or perhaps even Egizioed? :sob:

**Comment by DioEgizio** [comment]
it was a duplicate, sry
