### ISSUE TITLE
Curseforge Workaround seems to have an issue with file names containing plus signs

### ISSUE THREAD

**Issue by RedTechGamer236** [PrismLauncher/PrismLauncher#635]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.0

### Version of Qt

Qt 5.15.7

### Description of bug

The Curseforge workaround seems to have an issue with file names containing the plus sign. I have checked the hash sums for the file it is looking for and, if the workaround displays the SHA1 checksums, both seem to be the same for the file it says is missing after I have downloaded it.

### Steps to reproduce

1. Download a Curseforge modpack (I downloaded Better MC [PLUS]) with a mod that:

- Has third-party distribution disabled
- Has a plus sign in the file name

2. Click the "Open missing" button and let your browser download the missing mods
3. Wait until all the mods are downloaded.
4. All but the mods with plus signs in the file names should be found by the launcher

### Suspected cause

It may be an issue with the way the Curseforge workaround searches for files in Linux. Mods rarely use plus signs in file names.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Hmm weird. I did add additional handling for plus signs. CurseForge's API always gives us the unaltered filename, while their web UI replaces spaces with plus signs. But I guess it also replaces other characters as well?

**Comment by RedTechGamer236** [comment]
I just checked, and apparently the file I did the test with (it was BetterDefaultBiomes Alpha 2.6.1 for Forge 1.16) may actually have a plus sign in the file name. It's either that, or Crostini (I'm on an ARM Chromebook) messing up the Flathub version of Prism Launcher.

**Comment by Scrumplex** [comment]
Yeah. I can confirm this issue. If a mod has a space AND a plus sign in its filename, both will be represented as plus signs in the final download. We might look into checking for filename similarity to address this.

**Comment by Trial97** [comment]
This should be resolved in 7.1
