### ISSUE TITLE
Bug: walking underwater, Metal-Mario style

### ISSUE THREAD

**Issue by SpidFightFR** [PrismLauncher/PrismLauncher#64]
### Operating System

Linux

### Version of PolyMC

5.0-develop (commit: f3db9c392066ae632191658ade4e1946db9d29ee)

### Version of Qt

QT 5.15.6

### Description of bug

When going inside of water, we [fall inside it and walk under it](https://youtu.be/vzu1m6DLDYc) like in Mario64

### Steps to reproduce

just go in water.

### Suspected cause

A bug from the launcher.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by SpidFightFR** [comment]
Also the skin isn't showing as you might barely see here...

**Comment by DioEgizio** [comment]
that's not an issue of the launcher

**Comment by coreknee** [comment]
what minecraft version or mods/modpacks are you using
it might beyour minecraft
(i totally dont want to have that glitch too)

**Comment by SpidFightFR** [comment]
> what minecraft version or mods/modpacks are you using it might beyour minecraft (i totally dont want to have that glitch too)

it's just Fabric, sodium iris and leafculling. Nothing extraordinary.

**Comment by SpidFightFR** [comment]
Nvm it's linked to Fast load mod.
