### ISSUE TITLE
Importing a modpack from zip crashes Prism

### ISSUE THREAD

**Issue by willrun4fun** [PrismLauncher/PrismLauncher#640]
### Operating System

Windows

### Version of Prism Launcher

Prism 6.0

### Version of Qt

6.4.0.

### Description of bug

Importing zip of Nomifactory from https://nightly.link/Nomifactory/Nomifactory/workflows/nightly/dev and Prism crashes while exporting the zip.

### Steps to reproduce

Downloaded the latest nightly and tried to import it into Prism.  Crashes as It's unzipping the pack file.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
known issue, fixed in develop, will be fixed in 6.1
