### ISSUE TITLE
Select downloads folder.

### ISSUE THREAD

**Issue by emorygg** [PrismLauncher/PrismLauncher#641]
### Role

I play modded Minecraft.

### Suggestion

Customize the folder it searches for downloaded mods in.

### Benefit

So I don't have to use any workarounds, or change the default location of the downloads folder.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

When downloading a modpack it tries to find the downloaded mods in the default windows folder. I always change that in chrome to a different drive. Would love to be able to select any folder for it to search through

**Comment by DioEgizio** [comment]
You can already do that though? There's a button for it

**Comment by emorygg** [comment]
It doesn't save the folder selection when you go to download new modpacks
