### ISSUE TITLE
Issue with launching packwiz / older versions on fedora

### ISSUE THREAD

**Issue by Lutitious** [PrismLauncher/PrismLauncher#646]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.0

### Version of Qt

Qt 6.4.1

### Description of bug

I expected to launch minecraft but instead i got a failed launch of https://mclo.gs/U7AgKZR

### Steps to reproduce

On fedora try to launch a pack with packwiz or version older than 1.5.2, using the default jar.

### Suspected cause

A lack of `libawt_xawt.so` in the official redhat jdk breaks it. Using the azul repo instead works, instructions for which can be found [here](https://docs.azul.com/core/zulu-openjdk/install/rpm-based-linux#install-from-azul-rpm-repository). After adding the repo I then installed zulu8-jdk and zulu17-jdk, and i can use them fine.

Installing these by default on fedora/rhel might be a good idea instead of the current jdks that are installed by default.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
install not-headless java

**Comment by Lutitious** [comment]
Non headless java works

**Comment by getchoo** [comment]
thanks!

headless java versions have been replaced by the full package in the [6.1 release](https://pagure.io/prismlauncher-rpm/c/7869d7f684aa29d357823f5f31f0d3b2e7988460?branch=main) :)
