### ISSUE TITLE
Prism Launcher can crash when clicking OK button in update mods screen

### ISSUE THREAD

**Issue by mattp12** [PrismLauncher/PrismLauncher#659]
### Operating System
Windows 11

### Version of Prism Launcher

Prism Launcher 6.1

### Version of Qt

Qt 6.4.0

### Description of bug

When attempting to update mods, Prism may crash. I clicked the check for updates button in the mods section for an instance. There were no updates, but upon clicking OK on the "all mods are up to date" box, Prism crashes.

I wish I could reliably reproduce it, but it seems to happen at random when clicking that OK button.

Additionally, this crash also happened yesterday where there *was* an update to a mod. I said yes to the update and after the launcher still crashed (the update was applied correctly however).

I do not see any indication of a crash being logged in any of the PrismLauncher-<number>.log files, but I do see the crash in the Windows Reliability Monitor (and Event Viewer). I'm not sure how much this would help, but here is an image of what I see there: https://i.imgur.com/h2yS4MQ.png. Looks to have _something_ to do with Qt (although that probably doesn't narrow things down).

The closest I saw to an error is 
` 7.742 W QObject::connect: No such signal QNetworkReplyHttpImpl::error(QNetworkReply::NetworkError)
`,
but I don't know if this would cause a crash like this. 

### Steps to reproduce

- Click an instance 
- Click the mods tab on the side 
- Click check for updates
- The launcher may or may not crash after clicking the OK button in the box saying that all mods are up to date

### Suspected cause

N/A

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by mattp12** [comment]
One thing that I have noticed is that it looks to crash when I click check for updates as the mod list and information on mods is loading.
See video: 
https://user-images.githubusercontent.com/8071273/209607129-20a219bc-e4b6-4276-bd76-bb1f2c619355.mp4

**Comment by mattp12** [comment]
Here is the PrismLauncher-0.log file: (removed)

**Comment by mattp12** [comment]
Here's the PrismLauncher-0.log file, this time with appropriate things redacted (thanks for removing the previous one): 
[PrismLauncher-0_Redacted.log](https://github.com/PrismLauncher/PrismLauncher/files/10316422/PrismLauncher-0_Redacted.log)

I probably redacted way more than I needed to, but better to be safe. I pretty much redacted anything that looked to be remotely sensitive, but I probably overdid it. Hopefully I didn't miss anything.

**Comment by Ompyl** [comment]
same issue on linux

**Comment by MicrocontrollersDev** [comment]
This is happening to me as well quite often. I also got it to happen on the mod downloading page after pressing "OK" on the Confirm Mod Selection screen. Another thing to add is that it seems like the mods update and download correctly. But the launcher crashes afterward.
