### ISSUE TITLE
Is this VirusTotal scan of the .exe a false positive? 

### ISSUE THREAD

**Issue by Im-Kal** [PrismLauncher/PrismLauncher#663]
### Role

NIL

### Suggestion

NIL

### Benefit

NIL

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Hi there,

I've ran a VirusTotal scan on the Windows installer for PrismLauncher. Surprisingly, it comes up as malware. 

Is it a false positive?

https://www.virustotal.com/gui/file/9915886397dcdc3ab005e677c7ecaa2227f107e953a6ce3f0fe9da5aa24e99ba

**Comment by DioEgizio** [comment]
It's a false positive. Remember that many AVs on virustotal are AI-based and unreliable. also I looked at it and it seems like only 2 engines detect it so yeah just a false positive. Prism is free and open source so if you don't trust what I say you can look at the source code yourself
