### ISSUE TITLE
Launcher freezes/crashes after scrolling through Modrinth modpacks (Linux)

### ISSUE THREAD

**Issue by GabrielKarlsson** [PrismLauncher/PrismLauncher#664]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.1

### Version of Qt

Qt 5.15.7

### Description of bug

When adding a new instance and scrolling through the list of Modrinth modpacks, the launcher freezes up and segfaults. It happens consistently when using Linux, though I couldn't replicate it on Windows 10. No other mod provider has this issue.

https://user-images.githubusercontent.com/82874329/209215184-84c06706-bcde-491f-a975-921073737269.mp4

### Steps to reproduce

* Click "Add Instance"
* Select Modrinth
* Scroll the modpack list as far as possible

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Can you try the nightly build(https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/5394098599) and see if this is still reproducing?

**Comment by GabrielKarlsson** [comment]
Unfortunately, yes. I tried the one named "Prism Launcher-x86_64" and it exhibits the same issue as reported here. Not the AppImage one though, if that's any clue. However the original report was made for a Flatpak install. Hard to tell how the packaging formats affect this…
