### ISSUE TITLE
The skin icon in the launcher is steve's face

### ISSUE THREAD

**Issue by SpidFightFR** [PrismLauncher/PrismLauncher#67]
### Operating System

Linux

### Version of PolyMC

PrismLauncher 5.0 (commit: f3db9c392066ae632191658ade4e1946db9d29ee)

### Version of Qt

qt 5.15.6

### Description of bug

When launching the game, the skin is set to the default one (steve).

### Steps to reproduce

Connect to a microsoft account (idk for mojang) and launch the game.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by HugPhiluu** [comment]
Can you confirm that your Skin has been set to Steve by the Launcher?
I believe it may be your individual instance creating odd behaviour.

**Comment by SpidFightFR** [comment]
> Can you confirm that your Skin has been set to Steve by the Launcher?
> I believe it may be your individual instance creating odd behaviour.

Hey, yeah, in the top right hand corner of the launcher (the account button) the skin next to my name is steve’s face…

**Comment by aprilthepink** [comment]
> > Can you confirm that your Skin has been set to Steve by the Launcher?
> > I believe it may be your individual instance creating odd behaviour.
> 
> Hey, yeah, in the top right hand corner of the launcher (the account button) the skin next to my name is steve’s face…

is your skin steve on minecraft.net too? can you try changing the skin on minecraft.net and launching again?

**Comment by SpidFightFR** [comment]
okay so i just tried to setup my skin again in the launcher: it displays fine in game but in the launcher it's still a steve face.

I'll change the name of the issue then.

**Comment by Scrumplex** [comment]
Does this still happen?

**Comment by SpidFightFR** [comment]
Nope it seems it has been fixed
