### ISSUE TITLE
Ordering Groups

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#672]
### Role

Any way

### Suggestion

Add ability to order groups

### Benefit

More customization

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Order the groups (by dragging and dropping, similar to the instances between groups)

**Comment by GabrielKarlsson** [comment]
Seems like a possible duplicate of #316.

**Comment by ghost** [comment]
sorry it is
closing.
