### ISSUE TITLE
Exclude modpack mods from the mod updater

### ISSUE THREAD

**Issue by RaptaG** [PrismLauncher/PrismLauncher#683]
### Role

I play modded MC

### Suggestion

Exclude modpack mods from the mod updater

### Benefit

Modpack mods won't be accidentally updated manually and won't cause trouble

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by fn2006** [comment]
Personally I would prefer a warning that strongly advises against it rather than completely removing the ability to use the mod updater on modpacks.

**Comment by flowln** [comment]
Duplicate of #440
