### ISSUE TITLE
Updating already updated instances crashes the launcher

### ISSUE THREAD

**Issue by maxgamer134** [PrismLauncher/PrismLauncher#689]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.1

### Version of Qt

Qt 6.4.1

### Description of bug

Clicking 'Update Instance' in the CurseForge tab when the instance is already updated crashes the launcher

### Steps to reproduce

1. Download modpack of choice thru the launcher
2. Click on the CurseForge tab of that modpack
3. Update the instance to the latest version

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Can you still reproduce it on the latest version(7.2)?
