### ISSUE TITLE
No Versions Currently Available

### ISSUE THREAD

**Issue by VenOmBoyXOG** [PrismLauncher/PrismLauncher#691]
When I try to make a new instance in Prism Launcher, it just hits me with "NO VERSIONS ARE CURRENTLY AVAILABLE", and I see that whenever someone else installs Prism, they don't get this error. Please get back to me soon, I wanna play Minecraft.

**Comment by DioEgizio** [comment]
Did you update from 5.x to 6.1 and you're on windows? Then reinstall

**Comment by VenOmBoyXOG** [comment]
> Did you update from 5.x to 6.1 and you're on windows? Then reinstall

No, I installed it just now, and it's not working

**Comment by DioEgizio** [comment]
Send PrismLauncher-0.log, but it sounds really like an issue on your end

**Comment by VenOmBoyXOG** [comment]
What's PrismLauncher-0.log? I also uninstalled to reinstall like you suggested, so I'll be back to that in a bit.

**Comment by DioEgizio** [comment]
A file in `%APPDATA%/PrismLauncher`

**Comment by VenOmBoyXOG** [comment]
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/10323825/PrismLauncher-0.log)

**Comment by DioEgizio** [comment]
Can you open https://meta.prismlauncher.org/v1/net.minecraft/index.json in your browser ? Seems like your DNS can't resolve it

**Comment by VenOmBoyXOG** [comment]
I can open it, and the website shows be just a bunch of code.

**Comment by VenOmBoyXOG** [comment]
You fixed it..? It's working now!

**Comment by TheKodeToad** [comment]
Must be magic!

**Comment by VenOmBoyXOG** [comment]
> Must be magic!

yeah
