### ISSUE TITLE
Doesn't recognise Curseforge instances

### ISSUE THREAD

**Issue by SirenGlitch** [PrismLauncher/PrismLauncher#692]
I went into more detail in my [reddit post](https://www.reddit.com/r/PrismLauncher/comments/zyzsjq/instances_help/) so I'll just sum it up here, been using Curseforge app or modding, discovered PrismLauncher from AntVenom video, installed Prism, set it up, and set the instances folder to where my Curse instances were. None showed up in Prism.

**Comment by Scrumplex** [comment]
CurseForge and Prism Launcher have totally separate instance formats and there isn't really an integrated way to migrate them. You can create new instances and move your user data such as saves and settings to the new ones though.

**Comment by DioEgizio** [comment]
you can't just copy and paste instances. However, exporting instances as zip from curseforge and importing on prism will work

**Comment by SirenGlitch** [comment]
Okay thanks @Scrumplex  , I've just finished doing that funnily enough. Now im getting: "Instance update failed because: Null jar is specified in the metadata, aborting." In the log, should i open a seperate issue for that or is it simple enought to help here?
Edit: nvm got it working, thanks for the help guys(or girls/anything else)!
