### ISSUE TITLE
Windows File Association Bug

### ISSUE THREAD

**Issue by barraIhsan** [PrismLauncher/PrismLauncher#700]
### Operating System

Windows

### Version of Prism Launcher

6.1

### Version of Qt

Qt 6.4.0

### Description of bug

Expected : when opening zip / mrpack using prism, it will open the prism import page, and put the correct file path.
Happened : The file path is escaped, and it cannot be imported

### Steps to reproduce

- Download any modpack (rmpack / zip)
- Right click > Open With > Minecraft Modpack
- See the bug

### Suspected cause

For example, the mrpack file is in
`C:\Users\user\Downloads\CreateExtra.mrpack`, the result would be `c:%5CUsers%5Cuser%5CDownloads%5CCreateExtra.mrpack`.
See the problem?
Yes, it's because it's escaping the `\` to be `%5C`.
I think this is a Windows problem.
As you can see in the registry (`HKEY_CLASSES_ROOT\PrismLauncher.App\shell\open\command`)
There is nothing wrong. It just escapes the backslash.

So there is 2 way to solve this problem
1. When prism got the `-l` argument, it searches for any URL Escape (%XX) and will change it to the corresponding character (ex. `%20` ⇒ ` `, `%5C` ⇒ `\`) *Also capitalize the drive letter to make it nicer*
2. or, Prism should handle URL Escaped file path. *But it will look ugly because of the `%` stuff to the user.*

The first one is probably better.

Note: It seems Windows just escape `\`, but does not escape any other special character (ex. $#@!)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
I believe this is actually an artifact of how this was handled internally when converting the path to the QUrl. I'll look into this it should be a simple fix

**Comment by Ryex** [comment]
yep, use of `QUrl::fromLocalFile` and `QDir::toNativeSeparators` it's a 2-4 line fix but my current PR is already modifying this section of the code so I"ll apply the fix there I think
