### ISSUE TITLE
custom instance file location on disks

### ISSUE THREAD

**Issue by Hyppothalamus** [PrismLauncher/PrismLauncher#701]
### Role

I play modded mc

### Suggestion

a setting to select a folder on disk to store and launch instances

### Benefit

to not fill up my main drive and be able to play the same packs on different os' (dual-boot)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I am a dual boot users and I would like to store my instances on a different hard drive in my system so I can use the instances in every ditro and OS I use. I think this would also by appreciated by just one OS users to not clutter and fill their main drive with instances and worlds.

**Comment by TayouVR** [comment]
this is already a thing, just open the settings.
![image](https://user-images.githubusercontent.com/31988415/210339855-f070bc39-1032-4c3c-acbb-8681715da14b.png)

**Comment by Hyppothalamus** [comment]
Well I am terribly sorry for creating this issue I didn't understand those settings.
thank you for helping me out.
