### ISSUE TITLE
Adding Microsoft Account no longer works

### ISSUE THREAD

**Issue by polarfoxDev** [PrismLauncher/PrismLauncher#706]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.1

### Version of Qt

Qt 6.4.0

### Description of bug

When trying to add a Microsoft account, the status gets stuck right away saying "Working..." and nothing happens. Application stays responsive.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/33626498/210572721-59023a50-de96-4fd7-ba46-56e184db5f3b.png">

### Steps to reproduce

* Click Accounts
* Click Manage Accounts...
* Click Add Microsoft

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
You updated form 5.x to 6.1? Then reinstall

**Comment by mcdodge34** [comment]
Same issue, do not ask me to reinstall, fix it, too much work in my folder to simply reinstall all modpacks and such.

**Comment by ar065** [comment]
> You updated form 5.x to 6.1? Then reinstall

Why is this closed? I'm having the same issue as well. My version is currently 6.3 after updating from 6.1.

**Comment by polarfoxDev** [comment]
just fyi: Unfortunately, I can't reproduce it anymore by myself, because I switched machines and did a clean install of 6.1 for that.

**Comment by DownloadableFox** [comment]
I am having the exact same issue :(

**Comment by ABadNameSniper** [comment]
I'm also having the same issue
Edit: I uninstalled and reinstalled with the zip file instead of setup wizard and things are working again.

**Comment by Scrumplex** [comment]
Uninstall, then reinstall again. This is just a symptom of #660

**Comment by cmhulbert** [comment]
For what it's worth, I just installed Prism Launcher for the first time ever (on Ubuntu, via flathub) and also have this issue

**Comment by nightpool** [comment]
I also just installed Prism Launcher for the first time ever on Windows via the installer and have this issue

**Comment by cmhulbert** [comment]
For me the issue ended up being that when it prompted me to log in to Microsoft, it gave me the option of using GitHub to log in. That always failed, but it worked when I logged in manually, with email and password

**Comment by nightpool** [comment]
Ah, I'm also using Github login. However, I've been able to use interactive Microsoft Account auth using Github successfully in the past, e.g. with GeyserMC. Maybe a bug in prism then?

**Comment by cmhulbert** [comment]
Or possibly something changed on Microsoft's end. I have had issues using GitHub auth with other launchers too

**Comment by nightpool** [comment]
Well, thanks for your help anyway. I was able to add a password to my Microsoft account and then use that to log in

**Comment by AffinityGH** [comment]
I had the same issue with version 6.3. Doing a reinstallation using the 64 bit installer worked.

**Comment by zejefferson** [comment]
Just installed Prism for the first time (v6.3 on Windows) and I have the same issue. I couldn't add my M$ account (nothing happens after the sign-on procedure).
Tried a reinstallation and got the same symptom.

**Comment by VerbenaIDK** [comment]
Same problem, EndeavourOS, I installed PrismLauncher 7.2 from AUR using yay and can't add a Microsoft account.

**Comment by lll-Death-lll** [comment]
Same problem, EndeavourOS/Arch. Tried every version from AUR. Adds account only with VPN turned on. When turning off VPN, account stops working and turns offline. Works fine on Windows 11.

**Comment by spoutn1k** [comment]
Same problem on a fresh Linux install from source (aur -git package)

The logs show infinite polling:
```
   126.030 D | AuthFlow: "Logging in with Microsoft account."
   126.030 D | DeviceFlow::link
   126.030 D | DeviceFlow::setLinked: false
   127.584 D | DeviceFlow::onDeviceAuthReplyFinished
   127.584 D | DeviceFlow::onDeviceAuthReplyFinished: Tokens returned:
   127.584 D | "device_code" :  [ gibberish ]
   127.584 D | "expires_in" :  "900"
   127.584 D | "interval" :  "5"
   127.584 D | "message" :  "To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code 6D4796TR to authenticate."
   127.584 D | "user_code" :  "6D4796TR"
   127.584 D | "verification_uri" :  "https://www.microsoft.com/link"
   127.584 D | DeviceFlow::onDeviceAuthReplyFinished: Device auth request response
   127.585 D | Opening URL "https://www.microsoft.com/link?otc=6D4796TR"
   127.586 D | DeviceFlow::startPollServer: device_ and user_code expires in 900 seconds
   132.347 D | PollServer::onPollTimeout: retrying
   138.346 D | PollServer::onPollTimeout: retrying
   144.347 D | PollServer::onPollTimeout: retrying
   150.347 D | PollServer::onPollTimeout: retrying
   156.348 D | PollServer::onPollTimeout: retrying
   162.347 D | PollServer::onPollTimeout: retrying
   168.347 D | PollServer::onPollTimeout: retrying
   174.348 D | PollServer::onPollTimeout: retrying
   180.347 D | PollServer::onPollTimeout: retrying
   186.347 D | PollServer::onPollTimeout: retrying
   197.347 D | PollServer::onPollTimeout: retrying
   203.347 D | PollServer::onPollTimeout: retrying
   209.348 D | PollServer::onPollTimeout: retrying
   215.348 D | PollServer::onPollTimeout: retrying
   221.347 D | PollServer::onPollTimeout: retrying
   227.346 D | PollServer::onPollTimeout: retrying
   233.347 D | PollServer::onPollTimeout: retrying
   239.347 D | PollServer::onPollTimeout: retrying
```

The webpage ends up on the microsoft account page. My microsoft ID was created when they swallowed github so my login goes through github, maybe that is the issue ?

**Comment by rprije** [comment]
When attempting to add my Microsoft account on a fresh install (Linux. Not an update, so unrelated to #660 ) I also get stuck at the "Working" screen with the progress bar stuck at the same point. My logs seem to get less far than the original's:

```
   474.367 D | AuthFlow: "Logging in with Microsoft account."
   474.367 D | DeviceFlow::link
   474.367 D | DeviceFlow::setLinked: false
   474.367 D | [katabasis.credentials]: new refresh token: ""
   474.389 D | DeviceFlow::onDeviceAuthReplyFinished
```

It just stays there until I close the window.

**Comment by z-targz** [comment]
> When attempting to add my Microsoft account on a fresh install (Linux. Not an update, so unrelated to #660 ) I also get stuck at the "Working" screen with the progress bar stuck at the same point. My logs seem to get less far than the original's:
> 
> ```
>    474.367 D | AuthFlow: "Logging in with Microsoft account."
>    474.367 D | DeviceFlow::link
>    474.367 D | DeviceFlow::setLinked: false
>    474.367 D | [katabasis.credentials]: new refresh token: ""
>    474.389 D | DeviceFlow::onDeviceAuthReplyFinished
> ```
> 
> It just stays there until I close the window.

I'm getting the exact same logs. What's weird is that this just started happening today, no update, the launcher has been working fine. What's even weirder is that it seems to work fine on the portable prismlauncher 5.0

**Comment by Helites** [comment]
Perhaps this Solution is working for you too.
I could also not add an Microsoft Account to PrismLauncher (it was working before).

Some how my MS Account had only "Email a Code" as login option. 
After i created a password and logged in with a password the problem was gone.

![image](https://github.com/PrismLauncher/PrismLauncher/assets/9588599/de0d45dd-7e8f-4ee4-b58d-8bab086f8e3a)

**Comment by Snaping14** [comment]
I encountered a similar issue and shared my solution on another GitHub issue: [link](https://github.com/PrismLauncher/PrismLauncher/issues/660#issuecomment-2236045481).

Here's a brief summary of my experience and potential fixes:
1. Just wait... (after clicking "Add Microsoft")
2. Log into your Microsoft account in a browser (this might not need to be done while Prism is "working")
3. Additional steps I tried are detailed in my comment.

You can see the detailed steps and system information in my comment on the other GitHub issue.

PS Sorry for the necro. I figured I'd post in case anyone with this issue finds this while looking for information as I did.
PSS Thanks @Scrumplex for their support with this issue
