### ISSUE TITLE
Forge Technic Packs Past ~1.16.5 Appear Broken

### ISSUE THREAD

**Issue by SalmonSays** [PrismLauncher/PrismLauncher#708]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.1

### Version of Qt

Qt v6.4.0

### Description of bug

I've been testing out some technic packs from Prism Launcher recently, and have noted that while Fabric packs seem to work, Forge ones consistently do not in recent version numbers. This appears true at least for 1.19.2 and 1.18.2 packs. These same packs work totally normally on the Technic launcher.

When right clicking, editing, and selecting "Version" these packs are missing Forge ID's/version number that automatically populate this field in earlier Forge/Technic versions of MC. 

(Note: This can technically be mitigated by editing the pack with a Forge install before launch, but I suspect many new/young players will be surprised and/or confused when launching the pack first, backing out, flailing to discover the Forge fix, and finding that custom settings/configs from mods like Default Options will no longer take effect after the fix is applied, causing further troubleshooting headaches with no obvious source for help/troubleshooting.)

### Steps to reproduce

Click "Add Instance", select Technic, search for a Forge-based pack on 1.19.x (As an example, "Simple Forge 1.19.2"), launch. This should produce a vanilla 1.19.x pack without Forge or any signs of mods running, but with mods/configs in their proper directories.

### Suspected cause

I'm *guessing* that Forge changed their ID name schema sometime in the last few versions and Prism is importing a garbage ID. The fix would likely involve properly detecting Forge versions from the modpack.jar file inside these _newer_ versions of Forge/Technic modpacks and applying it to the Forge version settings section, unless Prism has an alternate load method for Technic specifically.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by byquanton** [comment]
https://github.com/PrismLauncher/PrismLauncher/blob/4b12c85d91be34504384117584fb4f25a754481e/launcher/modplatform/technic/TechnicPackProcessor.cpp#L192
Having a look at the version.json from “Simple Forge” it now looks like “net.minecraftforge:fmlloader:[mc]-[forgebuild]” instead of something like “net.minecraftforge:minecraftforge:[mc-build]-[forgebuild]” what the code is searching for
