### ISSUE TITLE
Allow adding / changing Modrinth's authentication token

### ISSUE THREAD

**Issue by Onako2** [PrismLauncher/PrismLauncher#711]
### Role

I play modded Minecraft and create Modpacks

### Suggestion

I want that a Modrinth API key can be used

### Benefit

so everyone can download and test their private modpacks on the Modrinth site itself without needing to import the modpack as a zip or mrpack

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
The Modrinth API has no API key, so closing this

**Comment by Scrumplex** [comment]
Looking at https://docs.modrinth.com/api-spec/#section/Authentication, there clearly is authorization. The issue suggest adding a field for accessing private resources on MR.
