### ISSUE TITLE
6.1 update cant download mod or modpack

### ISSUE THREAD

**Issue by minhboang11** [PrismLauncher/PrismLauncher#712]
### Version of Prism Launcher

prism luancher 6.1

### Version of Qt

Qt 6.4.0.

### Description of bug

![image](https://user-images.githubusercontent.com/82703775/210895720-460e3d7a-327b-45e6-a5da-e94eb732330b.png)
it cant download mod or modpack or cant see changlog
i try to use 6.0 it dont have error

### Steps to reproduce

![image](https://user-images.githubusercontent.com/82703775/210895991-60d9f894-8e4f-4e5b-9a28-9ce9073cf54d.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
You updated from 5.x to 6.1? Reinstall

**Comment by Onako2** [comment]
Cannot reproduce, on my machine everything is working fine. It may be that when you used 5 then it wasn't using the API too much and now in your network there may be more API requests.

**Comment by Strubbelkopp** [comment]
I have the same problem. Both on my desktop PC & my laptop

**Comment by DioEgizio** [comment]
As my comment says, reinstall
