### ISSUE TITLE
[Suggestion] Move to Codeberg

### ISSUE THREAD

**Issue by RaptaG** [PrismLauncher/PrismLauncher#719]
### Goal

Have the source code moved from GitHub to Codeberg.

### Motivation

GitHub is closed source software owned by Microsoft, opposing to Prism Launcher which is Free and Open Source Software. [Codeberg](https://codeberg.org) is a website created for hosting open source projects and is based on [Gitea](https://gitea.io) (It will move to [Forgejo](https://forgejo.org) soon, since Gitea is now owned by a for-profit organisation). Codeberg has a big userbase and many projects hosted on it, the UI/UX is really close to GitHub's and it allows to migrate projects from many other git services such as GitHub, GitLab, Gitea instances etc. 

### Specification

Create the Prism Launcher organisation in Codeberg and from there migrate all the Prism repositories using their git URLs and an access token. This would also require the maintainers to create Codeberg accounts but this can be easily done, since Codeberg allows signing up and in using GitHub accounts.

### Drawbacks

Fewer people use Codeberg comparing to GitHub, but I believe that willing contrubutors and enjoyers of Prism Launcher would open issues and PRs there as well.

### Unresolved Questions

Is the maintaining team willing to move to Codeberg?

### Alternatives Considered

Moving to GitLab, but GitLab's UX is not ideal.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Using Codeberg is also a good way to support FOSS.

**Comment by DioEgizio** [comment]
> Moving to GitLab, but GitLab's UX is not ideal.

IMO, gitlab'ui/ux is way better than gitea's but moving to gitlab wouldn't fix anything unless we self host ce

**Comment by DioEgizio** [comment]
i can see a few problems for that:
- issues would have to be moved
- less contributors as github has more people than codeberg
- CI would have to be rewritten
- less people would make issues as less people have codeberg accounts then github ones
- this is a launcher for a ms-owned game, so why even bother

**Comment by RaptaG** [comment]
> this is a launcher for a ms-owned game, so why even bother

[...] Using Codeberg is also a good way to support FOSS.

**Comment by RaptaG** [comment]
About your 2nd and 4th point:

> I believe that willing contrubutors and enjoyers of Prism Launcher would open issues and PRs there as well.

and

> [...] Codeberg allows signing up and in using GitHub accounts.

**Comment by RaptaG** [comment]
But for the rest, yes, they can be an issue

**Comment by ghost** [comment]
Supporting FOSS for the sake of it is not worth it where it'd create issues and inconveniences for no actual gain.

**Comment by Scrumplex** [comment]
I use Codeberg exclusively for my personal stuff, but Prism is a project focused on community, and many people might not want to contribute to Prism Launcher, if it's not on GitHub. If this was some niche Linux project, I wouldn't hesitate, but as this targets a more general audience, GitHub is a better choice. Alternatively, we could set up official mirrors on Codeberg.

**Comment by K0-RR** [comment]
Just putting my two cents:

>less contributors as github has more people than codeberg

This is a vicious circle - projects don't want to move because fewer users have accounts on Codeberg. Users don't have accounts on Codeberg as they don't see a reason to create one "just for that one project" they wanted to contribute/report something

Btw Codeberg is not the only Gitea instance available: https://git.disroot.org, https://gitdab.com, https://git.froggi.es.
Other git hostings, even less popular: https://gitbucket.github.io/, https://pagure.io/.

**Comment by Scrumplex** [comment]
Btw., I was just adding to @DioEgizio's comment above. We heavily rely on GitHub Actions, especially for Windows and macOS builds, and from what I can tell no other CI/CD platform can offer Windows and macOS runners for free as GitHub does.

**Comment by TayouVR** [comment]
if anything, i think mirrors make the most sense for this project

or self hosting e.g. gitlab, but thats a whole nother can of worms
EDIT: even if we were to selfhost, we should mirror to gh & accept contributions here

**Comment by Scrumplex** [comment]
I have already claimed `PrismLauncher` on GitLab.com and Codeberg in the early days of the project. See https://codeberg.org/PrismLauncher and https://gitlab.com/PrismLauncher

**Comment by RaptaG** [comment]
> Codeberg is not the only Gitea

They will move to Forgejo though (reasons mentioned on my original comment)

**Comment by RaptaG** [comment]
Official mirrors on Codeberg would be nice, though I have a question: Would PRs and issues on the Codeberg mirrors be accepted/considered?

**Comment by lynrayy** [comment]
Pls no
codeberg is inconvenient and looks ugly

**Comment by Scrumplex** [comment]
> Would PRs and issues on the Codeberg mirrors be accepted/considered?

That would be fairly hard to coordinate. We don't get GitHub Actions on Codeberg, which would be a requirement for PRs and having two issue trackers is also not ideal.

**Comment by Jan200101** [comment]
PrismLauncher is a Launcher for Minecraft, a closed source game.

I don't think moving to codeberg because github is closed source makes a lot of sense considering the subject of the project.

**Comment by flowln** [comment]
I don't think this is really being considered right now, so I'll close it. Feel free to open it again if you want to discuss it further.

**Comment by RaptaG** [comment]
Codeberg now allows projects to use its (experimental for now) CI, if they request it
https://codeberg.org/Codeberg-e.V./requests

**Comment by throwaway-d** [comment]
I just found this in my search results. As a Codeberg user, I have two suggestions:

> PrismLauncher is a Launcher for Minecraft, a closed source game.
1. You should directly ask Codeberg here: https://codeberg.org/Codeberg/Community/issues
Example: https://codeberg.org/Codeberg/Community/issues/370
https://codeberg.org/Codeberg/Community/issues/314

> if anything, i think mirrors make the most sense for this project
2. Correct! I always recommend everyone to mirror instead of switching completely. So, we can attract both users! Here is a mirroring guide I had written: https://codeberg.org/Recommendations/Mirror_to_Codeberg
