### ISSUE TITLE
Custom Mod Providers

### ISSUE THREAD

**Issue by ProjectHSI** [PrismLauncher/PrismLauncher#721]
### Role

Playing modded Minecraft with mods not hosted on either of the major modding providers.

### Suggestion

Custom mod providers to allow for mods not hosted on CurseForge or ModRinth to still be updated automatically by ModRinth

### Benefit

So that mods like Galacticraft can still be updated in the launcher.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Ryex** [comment]
this would be difficult.
at a minimum each potential provider needs to provide a location where the latest mod can be retrieved and preferably it should provide the checksum for that file so we can know if we  need to retrieve it.

possibly related to #694 
This get dicey as building up an interface generic enough to adapt to any new mod provider is by no means simple. we'd effectively need to add providers to the Meta repo...

**Comment by ProjectHSI** [comment]
this issue has been closed until further notice:
#694 already fulfills the use case needed for me -- computronics does not have a viable way of downloading via any sensible API, and Galacticraft already has Github releases setup.

This could be provided via DLL support, where a DLL could be downloaded or made by the user for their use case. (Ignoring dangerous DLLs for this discussion.)
