### ISSUE TITLE
Shader integration with Modrinth

### ISSUE THREAD

**Issue by ZenIsBestWolf** [PrismLauncher/PrismLauncher#725]
### Role

I play Minecraft with shaders.

### Suggestion

I want the Shaders panel to function like the Mods panel, and sync with Modrinth.

### Benefit

It makes Shader updates and acquisitions easier.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

*This may be considered a dupe of #153 but that is regarding resource packs.*

Modrinth now has support for Shaders, so implementation with Modrinth would be convenient, as well as making sure you have the correct shader engine (Iris, OptiFine, Canvas, etc) installed in order to use them.

**Comment by DioEgizio** [comment]
this is already getting worked on btw

**Comment by budderan** [comment]
I second this! I think being able to get shaders from the launcher like we can with mods would be a much appreciated QOL feature and would make prism launcher that much better! Very excited to hear progress on this

**Comment by rapus95** [comment]
For those looking for this feature (like I did just now), it's in the 7.0 milestone, so we have to wait for that :D

**Comment by DioEgizio** [comment]
If you want to try it out you can get a devbuild and try it 
https://prismlauncher.org/wiki/development/development-builds/
