### ISSUE TITLE
Sabotage-resistance

### ISSUE THREAD

**Issue by SoniEx2** [PrismLauncher/PrismLauncher#73]
What are the current plans to make this project sabotage-resistant so that what happened once can't happen again?

(Also the issue templates need updating)

**Comment by IMB11** [comment]
I mean - polymc already had some stuff like this:

- Custom meta server URL support.
- Custom microsoft client id support.

There's no real way to prepare the github org for something happening again, unless you give admin to a random github account and chuck the password away.

**Comment by SoniEx2** [comment]
There is more that can be done. Rust (programming language) moderation has had similar "gone rogue" issues in the past, and they seem to have addressed those - might be something worth looking into?

**Comment by Sakata-MC** [comment]
> 

I agree with this. There has to be some sane alternative to handling this to prevent the issue from occurring again.
I'm not sure if it'd be OK to just roll into other projects' Githubs and ask how they handle this stuff.

**Comment by SoniEx2** [comment]
you don't have to - it's all publicly documented. just gotta find the links...

https://www.theregister.com/2021/11/23/rust_moderation_team_quits/

https://developers.slashdot.org/story/21/11/27/0123211/rusts-moderation-team-resigns-to-protest-unaccountable-core-team

https://blog.rust-lang.org/inside-rust/2021/11/25/in-response-to-the-moderation-team-resignation.html

https://blog.rust-lang.org/inside-rust/2021/12/17/follow-up-on-the-moderation-issue.html

https://blog.rust-lang.org/inside-rust/2022/05/19/governance-update.html

https://blog.rust-lang.org/inside-rust/2022/05/26/Concluding-events-mods.html

probably more that can be found elsewhere and whatnot.

**Comment by Grithz** [comment]
> I mean - polymc already had some stuff like this:
> 
>     * Custom meta server URL support.
> 
>     * Custom microsoft client id support.
> 
> 
> There's no real way to prepare the github org for something happening again, unless you give admin to a random github account and chuck the password away.

Giving admin to a new Github account, telling all the admins the password of said account would be better. You would make an e-mail adress with a random password and log out of it. All the admins would have the password of the account but none could change the password.

**Comment by SoniEx2** [comment]
> > I mean - polymc already had some stuff like this:
> > ```
> > * Custom meta server URL support.
> > 
> > * Custom microsoft client id support.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There's no real way to prepare the github org for something happening again, unless you give admin to a random github account and chuck the password away.
> 
> Giving admin to a new Github account, telling all the admins the password of said account would be better. You would make an e-mail adress with a random password and log out of it. All the admins would have the password of the account but none could change the password.

at that point just use GAnarchy or something. (/self-plug)

**Comment by aprilthepink** [comment]
> > > I mean - polymc already had some stuff like this:
> > > ```
> > > * Custom meta server URL support.
> > > 
> > > * Custom microsoft client id support.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > There's no real way to prepare the github org for something happening again, unless you give admin to a random github account and chuck the password away.
> > 
> > 
> > Giving admin to a new Github account, telling all the admins the password of said account would be better. You would make an e-mail adress with a random password and log out of it. All the admins would have the password of the account but none could change the password.
> 
> at that point just use GAnarchy or something. (/self-plug)

at this point you would also need to use smth independent like Codeberg and not Github cause Github could go rogue too :trollface:
