### ISSUE TITLE
Search function doesn't give exact result first

### ISSUE THREAD

**Issue by Strange05** [PrismLauncher/PrismLauncher#738]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.1

### Version of Qt

Qt 6.4.0

### Description of bug

If you search for the exact name of a modpack, it doesn't immediately show the searched modpack in the first results. 

Example: I searched for Sky Capsule Project which is the exact name of the modpack but the search result didn't show the modpack at first, than you have to scroll a bunch until you find.
![image](https://user-images.githubusercontent.com/85522281/211955189-db138bf8-25cf-4e12-b957-bfecbf6122f1.png)

Look at the scroll bar.
![image](https://user-images.githubusercontent.com/85522281/211955344-953ba2a6-f389-4da7-a615-cd225a066537.png)

 Sorting by Name also doesn't help, it actually makes worst since you have to scroll even more 
![image](https://user-images.githubusercontent.com/85522281/211955514-c076e81f-0aab-4816-b512-f85070eec68a.png)
![image](https://user-images.githubusercontent.com/85522281/211955547-26314617-31ee-4601-a3bc-bdf03ff8eb3b.png)

### Steps to reproduce

- Create a new instance
- select the curseforge option
- Search for a modpack using it's complete name
- (using less know modpacks makes more noticeable)

### Suspected cause

Using the sort by name option and the Sky Capsule Project example, can be noticed that the results are show but every word contrebutes equaly to the results show but the order of words are not considered, so even searching the correct name only show all results that have any of used words.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
This is an issue with cf's search, which is famous for being pretty bad. Not related to prism
