### ISSUE TITLE
GLFW error 65542 on Prism Launcher Flatpak 6.1

### ISSUE THREAD

**Issue by mateowoetam** [PrismLauncher/PrismLauncher#742]
### Version of Prism Launcher

Prism Launcher 6.1 Flatpak

### Version of Qt

Qt 5.15.7

### Description of bug

When trying to run any instance, I get the following error message:
```
GLFW error 65542: GLX: No GLXFBConfigs returned.

Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).
```
Software Details:
Ubuntu 22.04 LTS
Flatpak 1.14.1
Prism Launcher 6.1
Nvidia Drivers 525.60.11
Cuda 12.0
X.org

### Steps to reproduce

Open Prism Launcher, click on any instance and Launch, then the error message appears.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by mateowoetam** [comment]
I enabled GPU acceleration inside Flatseal, and that fixed the error. "device=dri" but the game is way choppy-er now.

**Comment by DioEgizio** [comment]
You don't need to do it, it's just that you don't have the right Nvidia driver installed on the flatpak

Do flatpak install nvidia-525-60-11

**Comment by mateowoetam** [comment]
The thing is, I did have the Nvidia drivers installed on flatpack, the correct ones too. So I thought it was something to do with the app.

**Comment by XHawk87** [comment]
I had this same issue. I had nvidia drivers installed already too, but it turned out it needed more up-to-date ones. This is what worked for me:
- Use this command to find your graphics card details if you don't already know them: `lspci -v | grep NVIDIA`
- Check which is the latest version at: https://www.nvidia.com/Download/index.aspx
- Fill out the details of your graphics card and hit Search
- The version number should be displayed at the top. In my case `Version: 525.105.17`
- Install it using the command above. In my case `flatpak install nvidia-525-105-17`

**Comment by lbrunkho** [comment]
In the event anyone else sees this, I had a similar issue on `Fedora 40`, `Nvidia 555 `drivers, `Flatpak version 8.4`. Drivers were fine and I was running a Gnome Wayland session. I could for the life of me not get this to use the GPU.

If I used flat seal to restrict Prisim to Xorg, then I would get the GLFW error mentioned in this post. 

If I set Prisim to use Walyand, the game would launch but render in CPU. The game would also suffer major artifacting, think frozen [Windows XP with the infinite windows](https://mrdoob.com/lab/javascript/effects/ie6/). 

**Resolved** this issue by uninstalling Prisim completely (removed all user data) and reinstalled. Best guess is something wasn't linking up with the nvidia flatpak driver correctly.

**Comment by jayschuster** [comment]
> I had this same issue. I had nvidia drivers installed already too, but it turned out it needed more up-to-date ones. This is what worked for me:
> 
>     * Use this command to find your graphics card details if you don't already know them: `lspci -v | grep NVIDIA`
> 
>     * Check which is the latest version at: https://www.nvidia.com/Download/index.aspx
> 
>     * Fill out the details of your graphics card and hit Search
> 
>     * The version number should be displayed at the top. In my case `Version: 525.105.17`
> 
>     * Install it using the command above. In my case `flatpak install nvidia-525-105-17`

+1 worked for me! Thank you!
