### ISSUE TITLE
Minecraft and prism crashes after opening a modpack I made

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#750]
### Version of Prism Launcher

6.1

### Version of Qt

6.3.0

### Description of bug

expected the instance to load, instance loaded for a bit and as soon as I attempted to enlarge minecraft it crashed

### Steps to reproduce

launch
attempt to do something
crashes

### Suspected cause

May be caused by hytools, but not entirely sure

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/9vz5eUu

**Comment by Aces-and-Jacks** [comment]
PrismLauncher-0.log

**Comment by Aces-and-Jacks** [comment]
deleted since this probably won't be solved

**Comment by Frontear** [comment]
This issue is being caused by your Java Runtime, not Prism. This issue could either be due to a mod doing something very VERY wrong, or the JVM having a bug.

My tip: Try using Eclipse Adoptium java builds, and see if the issue remains. Alternatively, try disabling mods from the most recent to see which could be responsible for that crash

**Comment by Aces-and-Jacks** [comment]
eclipse is temurin right?

also I identified what may be causing it in the description. Would I open an issue there?

**Comment by Aces-and-Jacks** [comment]
well either way I tried both zulu and temurin, neither worked. 

So it's something that would need to be fixed on the mods end?

**Comment by Frontear** [comment]
Yeah, its very unlikely the JVM is bugged and that confirms it. Its a mod that either uses a library which breaks, or the mod itself breaks. Only way to find out is trial and error

**Comment by Aces-and-Jacks** [comment]
Ok then, thanks
