### ISSUE TITLE
Stuck at working when trying to log in microsoft 

### ISSUE THREAD

**Issue by mirozee** [PrismLauncher/PrismLauncher#754]
### Operating System

Windows 11

### Version of Prism Launcher

Prism Launcher 6.1

### Version of Qt

Qt 6.4.0

### Description of bug

It doesn't get past this stage
![image](https://user-images.githubusercontent.com/109737502/212611487-db93fd12-dad3-4b38-a177-12d527099d18.png)

### Steps to reproduce

by pressing 'add microsoft'

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
This is probably #660.

Try uninstalling and then reinstalling Prism Launcher.

**Comment by mirozee** [comment]
> These steps solved this problem for me:
> 
>     1. Use File Explorer to search for `.dll` in the PrismLauncher folder
> 
>     2. Delete all the files it found
> 
>     3. Unzip the zip file corresponding to the Prism version you chose, (e.g. `MSVC-arm64` for `MSVC-arm64-Setup`) into the PrismLauncher folder, and skip any duplicates.
> 
> 
> I think this issue might be a result of unknowingly switching from MinGW to MSVC during the upgrade.

this solution from #660 seemed to fix it for me.
