### ISSUE TITLE
Resize "download mods" window

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#755]
### Role

Modded Minecraft

### Suggestion

Aďd the ability to resize the download mods window

### Benefit

Better visibility since there is a lot of text to display

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
Resizing works for me

**Comment by ghost** [comment]
> 

not for me? im on windows btw

**Comment by Poopooracoocoo** [comment]
Do you mean this window? 
![image](https://user-images.githubusercontent.com/51363864/214216532-98fc14dd-f9b6-49a4-9b49-b8d2948187b2.png)

Could you please edit your description to follow the bug report template?

**Comment by ghost** [comment]
apparently it's resizeable but when i tested it i couldnt get it to work and i cannot reproduce
