### ISSUE TITLE
Instance duplication doesn't use reflink copying with Btrfs

### ISSUE THREAD

**Issue by cjvth** [PrismLauncher/PrismLauncher#761]
### Operating System

Linux

### Version of Prism Launcher

6.1

### Version of Qt

6.4.2

### Description of bug

I have instances folder on a Btrfs partition. I want to duplicate one of the instances, which has size of 4 GiB. Current output of `compsize` on instances folder:
```
Processed 5837 files, 17292 regular extents (21650 refs), 780 inline.
Type       Perc     Disk Usage   Uncompressed Referenced  
TOTAL       96%      5.4G         5.5G         8.7G       
none       100%      5.1G         5.1G         8.1G       
zstd        61%      281M         455M         605M
```
`Referenced` is the sum of sizes for all files. Disk Usage is how much data needs to be stored on the drive.
If I do `cp -r` or `cp -r --reflink=auto inst inst-copy` in terminal, it copies fastly and `compsize` is:
```
Processed 7921 files, 17292 regular extents (33319 refs), 1042 inline.
Type       Perc     Disk Usage   Uncompressed Referenced  
TOTAL       96%      5.4G         5.5G          12G       
none       100%      5.1G         5.1G          11G       
zstd        61%      281M         455M         970M       
```
Duplicated files point on the same space on my drive, so disk usage doesn't change.
However, if copy my instance in the launcher interface, it takes some time and increases my disk usage
```
Processed 7921 files, 19591 regular extents (23949 refs), 1042 inline.
Type       Perc     Disk Usage   Uncompressed Referenced  
TOTAL       97%      9.4G         9.7G          12G       
none       100%      9.1G         9.1G          12G       
zstd        55%      300M         537M         687M       
```

### Steps to reproduce

- EndeavourOS, installed `btrfs-progs` and `compsize` packages
- Btrfs partition mounted as /home. Mount options in /etc/fstab are `defaults,noatime,compress=zstd 0 0`
- Have a fairly large PrismLauncher instance
- Check consumed space for the whole drive or `sudo compsize instances` output
- Copy the instance with right-click -> Copy..., choose to copy everything
- Check consumed disk space again

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
as nice as this would be I'm fairly sure it's functionally impossible to implement in a clean way.
 
 we would have to delegate directly to [ioctl_ficlone](https://man7.org/linux/man-pages/man2/ioctl_ficlone.2.html/) a Linux specific syscall.

**Comment by Ryex** [comment]
NVM twas easy
