### ISSUE TITLE
ArchLinux Java libnio.so Prism cannot start Minecraft 

### ISSUE THREAD

**Issue by wanesty** [PrismLauncher/PrismLauncher#767]
### Operating System

Linux

### Version of Prism Launcher

prism 6.1

### Version of Qt

qt 6.4.2

### Description of bug

as of 2023/01/19 Prism cannot run minecraft with **mangohud** on **arch** because of _java-runtime-common 3-5_ and _java-environment-common 3-5_ and throw an error : 
```
Error: LinkageError occurred while loading main class org.prismlauncher.EntryPoint
    java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-19-openjdk/lib/libnio.so: /usr/lib/jvm/java-19-openjdk/lib/libnio.so: undefined symbol: reuseport_available
Process exited with code 1.
```

this is from what i've read on the discord server, caused by Mangohud's the java wrapper, **the current fix is to simply disable the use of mangohud in your instance or globally with prism** 

(this is for reference, so i will mark the issue as closed when mangohud updates)

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by edgars-cirulis** [comment]
This is not a bug on our side. Please file an issue with Mangohud.

**Comment by Scrumplex** [comment]
This is not a MangoHud bug either. This is a bug with the AUR package for mangohud.

**Comment by edgars-cirulis** [comment]
> This is not a MangoHud bug either. This is a bug with the AUR package for mangohud.

So you know a fix for that?

**Comment by Scrumplex** [comment]
I commented a patch on the AUR package, but I don't know if the maintainer will accept it: https://aur.archlinux.org/packages/mangohud#comment-898875

**Comment by wanesty** [comment]
> This is not a bug on our side. Please file an issue with Mangohud.

as stated, it's been discuses in the discord server, this is to help peoples having the same issue

**Comment by wanesty** [comment]
Last mangohud update ( aur/mangohud 0.6.8-5 ) fixed the issue.
