### ISSUE TITLE
5.1 to 6.1 made the client unusable

### ISSUE THREAD

**Issue by Yertled** [PrismLauncher/PrismLauncher#773]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.1

### Version of Qt

Qt 6.4.0

### Description of bug

Every single time I launch a "modpack" or client, it asks me what I want my offline username to be (why?), and every single time I open Minecraft, it tells me to restart my game.
How does it break from update 5.1 to 6.1? 
I am going to downgrade and never look back. But please fix it. It's unusable now. Remove the forced choosing of offline names.
Who uses Prism primarily to play offline mode?

### Steps to reproduce

Open Prism Launcher 6.1
Launch ANY modpack/client, it asks for Offline name, I chose my offline name, I launch the pack, cant join any server.

### Suspected cause

God awful update!

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Reinstall
