### ISSUE TITLE
quazip outdated on ArchLinux

### ISSUE THREAD

**Issue by nightlyDuck** [PrismLauncher/PrismLauncher#776]
### Operating System

Linux

### Version of Prism Launcher

PrismLauncher 6.1

### Version of Qt

Qt 6.4.2

### Description of bug

PrismLauncher use quazip 1.3.0, but quazip has been updated to 1.4.0
![image](https://user-images.githubusercontent.com/102286502/213957973-e5df997a-74e6-4a36-9cfd-0d691998f63e.png)

### Steps to reproduce

1. Update quazip from 1.3.0 to 1.4.0
2. See error in your terminal

### Suspected cause

quazip outdated

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Rebuild prism ig

**Comment by DanMeadWasTaken** [comment]
a temporary solution to this would be to just downgrade the package- if you're on linux- as well as tell your package manager to ignore it. then once this has been fixed, remove it from the ignore list and update it.

**Comment by Scrumplex** [comment]
You are supposed to rebuild affected packages when stuff like this happens.

The quazip package was updated and all packages depending on it need to be rebuilt against the new ABI.

So if you use paru or yay, you would run this:
```
yay -S --rebuild prismlauncher
paru -S --rebuild prismlauncher
```

**Comment by DanMeadWasTaken** [comment]
Well, can confirm this works! 
Granted, my previous comment of downgrading quazip works- this solution was one i didn't know about and would (obviously) be better long term
