### ISSUE TITLE
More detailed library and asset download window

### ISSUE THREAD

**Issue by TheMCNerd2017** [PrismLauncher/PrismLauncher#78]
### Role

Downloading libraries and assets

### Suggestion

Make the library and asset download window more detailed

### Benefit

It would give the user a better and more accurate idea of the download progress for libraries and assets

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

_This is a repost of my suggestion from the old repository. I asked in the support channel if I should repost my suggestions currently in the old repository to the new one and was told to move to the new one._

I'm suggesting that the download progress windows for libraries and assets be more detailed. More specifically it should display the current file being downloaded, progress of the current file, and the total overall progress of the library and asset downloading. Some information should also be outputted to the game log area, like the official Minecraft launcher does.

This would be an improvement from the current download progress window which is currently a single progress bar that is not accurate to the actual library and asset download progress. It would also be an improvement for people that are on slow internet like DSL, since they will be able to get a good idea on how long the download will take.

Below is a mockup of what it could look like.

![asset_window_concept](https://user-images.githubusercontent.com/25375242/196518895-3ebcc007-1815-484d-80a1-ea3d3b4164af.png)
I didn't make all the information in that picture accurate, since it's suppose to be a mock-up. Additionally the change would also apply to the library download window as well as any other download progress window (if there are others). Library and asset index updates would also only populate the first download bar (the second bar would either be empty with the text below it hidden or not visible at all).

**Comment by ZombieNub** [comment]
Other, more experienced developers may be able to code this up rather quickly, but I'll give a crack at doing this. Might be a good opportunity to learn Qt.

**Comment by ZombieNub** [comment]
Nevermind, I don't know what I'm doing. Someone more familiar with the codebase and Qt should handle this task

**Comment by TheMCNerd2017** [comment]
Closing this as #961 has been merged recently, which adds functionality similar to what was being requested here.
