### ISSUE TITLE
[6.1] Crash when viewing the mod list, if the mod count is above 511

### ISSUE THREAD

**Issue by SplendidAlakey** [PrismLauncher/PrismLauncher#782]
### Operating System

Windows

### Version of Prism Launcher

6.1

### Version of Qt

Qt 6.4.0

### Description of bug

If the mod count exceeds 511, the launcher hangs on viewing the mod list.

As a temporary workaround, you can take out a single mod, open the mod list, let it load in, then drop the mod back in. But that process has to be repeated on every single launcher start.

### Steps to reproduce

1. Assemble a modpack with 512 mods (you can download literally any mod and make 512 copies of it, too)
2. Right-click the instance - Edit...
3. Navigate to Mods tab
4. The mod list will now start to (I assume) refreshing metadata for the mods
5. Once it reaches the final 10 or so, the launcher hangs and, shortly after, crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Hmm. I wasn't able to reproduce this bug either on 6.1 nor on a recent nightly (the latest nightly is broken in other ways though).

I am on Linux, though, so this could be an issue on Windows only.

I created an instance with exactly 512 copies of Fabric API.

**Comment by DioEgizio** [comment]
Iirc this was fixed very recently in develop

**Comment by flowln** [comment]
Yep was fixed in #758, to reproduce in 6.1 on Linux you have to lower your stack size with something like `ulimit`.

**Comment by SplendidAlakey** [comment]
Got it, thank you. I'll leave this up until the release.

And judging by the wording of that PR, I assume it also fixes the same type of crash, if you try to index the same(-ish) amount of mods at the same time.

**Comment by SplendidAlakey** [comment]
Fixed, thank you!
