### ISSUE TITLE
Disabled Mods are not correctly disabled when downloading a pack from FTB Pack

### ISSUE THREAD

**Issue by Mattabase** [PrismLauncher/PrismLauncher#785]
### Operating System

Windows

### Version of Prism Launcher

Prisim Launcher 6.1

### Version of Qt

Qt 6.4.0

### Description of bug

When downloading the FTB Legend of Eyes 1.0.0 or 1.1.0 version of the pack, it will download the pack but not respect the disabled mods that should be disabled when downlading the pack. 

CTM for Fabric should be disabled by default, and when using Prism it is not

### Steps to reproduce

Install any version of the FTB Legend of Eyes

check enabled mods

CTM for Fabric should be disabled, it is not that is the bug

### Suspected cause

IDK

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Mattabase** [comment]
Does this issue need to be retested on 6.3?

**Comment by DioEgizio** [comment]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/83089242/227866213-96e88fc4-441b-475c-8748-2907f3705220.png">
except there's no indication on the manifest that it should be disabled
