### ISSUE TITLE
Profile creation prompted even when unnecessary

### ISSUE THREAD

**Issue by vgskye** [PrismLauncher/PrismLauncher#786]
### Version of Prism Launcher

built from git rev 2203af7eeb48c45398139b583615134efd8d407f

### Version of Qt

5.15.7

### Description of bug

When there is an account without a Minecraft profile and there are other accounts with a profile, you're prompted to make a profile regardless of what account(if any) is the default.

### Steps to reproduce

* Add a Minecraft account
* Add an account that obtained Minecraft by Game Pass and never played Java
* Try to play Minecraft using the first account

### Suspected cause

Probably hitting some untested corner case

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by XIshArkIX** [comment]
+1
After buying minecraft and installation (with CurseForge modpack) I prompted every time even when click "Play offline". One interesting detail is my nickname correctly shown in official minecraft launcher.
Edited: when using microsoft account - just reconnect

**Comment by Trial97** [comment]
possibly fixed by https://github.com/PrismLauncher/PrismLauncher/pull/1692 (please test this out once the 8.0 is released)

**Comment by Trial97** [comment]
Hey 8.0 was released is this still a issue?

**Comment by vgskye** [comment]
I have no clue, I no longer have the specific circumstance to check

**Comment by Trial97** [comment]
Can you please close this issue then?
