### ISSUE TITLE
Tweaking the java auto-detection for Linux

### ISSUE THREAD

**Issue by Yvaneebe** [PrismLauncher/PrismLauncher#790]
### Role

Playing different versions of Minecraft

### Suggestion

Changing the Java auto-detection function on Linux to be more thorough as it ignores $PATH and symlinks to Java installations

### Benefit

Easy switching between different versions of Java without having to browse to their directories

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The issue first arose when I decided to use SDKMAN on Linux to install different JDKs and realised PrismLauncher doesn't detect them even if their directories were linked in `$PATH` or symlinked in `/usr/lib/jvm`. I browsed the PrismLauncher code ( [launcher/java/JavaUtils::FindJavaPaths](https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/java/JavaUtils.cpp#L413) in particular ) and my doubt was confirmed that it filters out the symlinks to directories. Entries in `$PATH` don't seem to be scanned for java binaries either on Linux as opposed to Windows. 

Including symlink and `$PATH` scanning would be appreciated. It would also be really useful if PrismLauncher also checked `$SDKMAN_DIR/candidates/java` for Java installations since SDKMAN is a versatile and well-established tool for managing and installing different JDKs.
Thanks

**Comment by BalkanMadman** [comment]
Will be present in 7.0 release, I guess

**Comment by Yvaneebe** [comment]
Thanks a lot!

**Comment by BalkanMadman** [comment]
You are welcome :)
