### ISSUE TITLE
[DEVELOP] update and more news repeated 2 times

### ISSUE THREAD

**Issue by DioEgizio** [PrismLauncher/PrismLauncher#792]
### Operating System

Windows, macOS, Linux, Other

### Version of Prism Launcher

develop

### Version of Qt

qt 6.3.0

### Description of bug

update and more news repeated in the more news area even though they're already listed elsewhere

<img width="305" alt="image" src="https://user-images.githubusercontent.com/83089242/215257515-d1c0c29f-b2be-4703-a699-b890bb431951.png">

### Steps to reproduce

- open more news
- see

### Suspected cause

https://github.com/PrismLauncher/PrismLauncher/pull/724

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by leia-uwu** [comment]
oops, i made the help menu bar menu and tool button share the same QMenu and forgor that theres already an update button on the toolbar

i think we can keep the more news action so you can still open the news without opening the menubar when the news toolbar is disabled
