### ISSUE TITLE
Cannot start the portable launcher on a clean Windows 8.1 due to missing CRT

### ISSUE THREAD

**Issue by Anton-V-K** [PrismLauncher/PrismLauncher#794]
### Operating System

Windows

### Version of Prism Launcher

PrismLauncher-Windows-MSVC-Portable-6.1.zip

### Version of Qt

Qt 6.4.0.0 (according to QtCore.dll details)

### Description of bug

When starting the app on a clean Windows 8.1 64-bit PC it shows the error:
```
The program can't start because MSVCP140.dll is missing from your computer.
Try reinstalling the program to fix this problem. 
```

### Steps to reproduce

* Use a freshly installed (clean) Windows (8.1 64-bit in my case)
* Download `PrismLauncher-Windows-MSVC-Portable-6.1.zip`
* Extract to any dir
* Start `prismlauncher.exe`

### Suspected cause

Include required VC DLLs (`MSVCP140.dll`, `VCRUNTIME140.dll`, etc.) in the archive.
It is usually enough to places them in the dir with the executable.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by theofficialgman** [comment]
Please actually read the download page before posting an issue.
https://prismlauncher.org/download/

You have windows 8.1, you need to download the correct version which supports legacy windows.
This issue can be closed.

**Comment by DioEgizio** [comment]
You need the legacy variant and you need to install vcredist, like the website pretty clearly says

**Comment by Anton-V-K** [comment]
Thanks for the link. I've missed the point with the legacy version for Windows 7/8.1 (it's nice these Windows are still supported).
Anyway the issue happens with the legacy version as well.
And my suggestion to place `msvcp140.dll` and `vcruntime140.dll` in the archive will solve the issue partially - an attempt to run the app will end with the complaint about another missing system-specific DLL:
```
The program can't start because api-ms-win-crt-stdio-l1-1-0.dll is missing from your computer. [...]
```
I doubt this DLL can be shipped in the portable archive (it seems to be specific to OS), so installing an update like [KB2999226](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows) will be required.

**Comment by DioEgizio** [comment]
> Thanks for the link. I've missed the point with the legacy version for Windows 7/8.1 (it's nice these Windows are still supported). Anyway the issue happens with the legacy version as well. And my suggestion to place `msvcp140.dll` and `vcruntime140.dll` in the archive will solve the issue partially - an attempt to run the app will end with the complaint about another missing system-specific DLL:
> 
> ```
> The program can't start because api-ms-win-crt-stdio-l1-1-0.dll is missing from your computer. [...]
> ```
> 
> I doubt this DLL can be shipped in the portable archive (it seems to be specific to OS), so installing an update like [KB2999226](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows) will be required.

Have you read my comment? As the website also says, you need vcredist x86 2022

**Comment by Scrumplex** [comment]
> And my suggestion to place `msvcp140.dll` and `vcruntime140.dll` in the archive will solve the issue partially

We can't do this directly for licensing reasons.

See https://opensource.stackexchange.com/questions/7182/redistributing-msvc-runtime-components-with-gpl-application
