### ISSUE TITLE
Can't edit instance when game is open

### ISSUE THREAD

**Issue by TheAirBlow** [PrismLauncher/PrismLauncher#796]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.0

### Version of Qt

5.15.7 (KDE doesn't support QT 6 yet)

### Description of bug

The launcher freezes when I try to edit instance while the game is running (for me it has to at least finish loading and clog up the RAM), if the instance window was open beforehand it is working fine.

### Steps to reproduce

* Start a chonky modpack
* Wait till it finishes loading, play a lil bit maybe
* Now you can't edit instance anymore

### Suspected cause

IDK, in fact, every single button has a little bit of latency to it, which it looks like increases in some weird scenario.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by flowln** [comment]
Part of #485
