### ISSUE TITLE
PolyMC LICENSE VIOLATION

### ISSUE THREAD

**Issue by GenLentils** [PrismLauncher/PrismLauncher#80]
### Role

I do not use license violating software

### Suggestion

resolve license violation

### Benefit

violation of license is not permissible

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

**Per GPLv3**

> 
>   5. Conveying Modified Source Versions.
> 
>   You may convey a work based on the Program, or the modifications to
> produce it from the Program, in the form of source code under the
> terms of section 4, provided that you also meet all of these conditions:
> 
>     a) The work must carry prominent notices stating that you modified
>     it, and giving a relevant date.
> 
>     b) The work must carry prominent notices stating that it is
>     released under this License and any conditions added under section
>     7.  This requirement modifies the requirement in section 4 to
>     "keep intact all notices".
> 
> 

**1. There is no relevant date included neither prominent notice that software is originally fork of PolyMC and not PolyMC affilated**

**2. Secondly from PolyMC repo**

![polymc](https://user-images.githubusercontent.com/116115582/196526456-28bfc67e-227c-4c6f-9939-021b3fd0335d.png)

**There is no clear mention that this project is not endorsed by PolyMC or affiliated with it.**

**By violating above mentioned terms you are opening yourself to the removal of your project from github if owner of original repo wishes to do so.**

**Transgenderism and similar mental illnesses** **are not legal** in my country saudi arabia, therefore I believe it is required for information to be disclosed that this project is not PolyMC or affilated with it **as I do not wish to violate my country law by contributing or using project developed by these individuals**.

I was told that this is safe PolyMC version but it is infact affilated with PolyMC or related to it.

**Please resolve this and tread carefully, cancel culture is not worth lawsuit**
And consider mental treatment
- God bless!

**Comment by initmd** [comment]
🤓

**Comment by RoootTheFox** [comment]
> **Transgenderism and similar mental illnesses** **are not legal** in my country saudi arabia, therefore I believe it is required for information to be disclosed that this project is not PolyMC or affilated with it **as I do not wish to violate my country law by contributing or using project developed by these individuals**.

Transgenderism is not a mental illness, and neither does this project violate any licenses from my understanding.
