### ISSUE TITLE
[Feature request] Install multiple modpacks on a single instance.

### ISSUE THREAD

**Issue by sweenu** [PrismLauncher/PrismLauncher#800]
### Role

I play modded minecraft

### Suggestion

Allow installing multiple modpacks

### Benefit

Allow for modpacks that have different purposes

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I'm making a modpack for all my default client mods (utility + optimization). On top of that, I have different gameplay modpacks that I want to be able to share to friends. I'd like an easy way to not have to include all those client mods in these gameplay modpacks as they might not be what everyone wants for their client and also because it's a bunch of duplication.

In order to do so, I would need to easily install multiple modpacks on an instance.

**Comment by flowln** [comment]
Modpacks aren't designed to be merged together, as they often include repeated files, files from the same mod but in different versions, configurations, etc. You can check out [packwiz](https://github.com/packwiz/packwiz), for instance, to build a modpack with optional dependencies that each user can choose from.
