### ISSUE TITLE
Optifine option

### ISSUE THREAD

**Issue by Alyaqdhans** [PrismLauncher/PrismLauncher#808]
### Role

any minecraft version

### Suggestion

add a toggle option when selecting your version for optifine

### Benefit

it will be easier to play with optifine

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

add a toggle option for Optifine on this page of the launcher:
![image](https://user-images.githubusercontent.com/58079015/216245253-e02b680d-e2ff-4002-88f1-c771cc3e2499.png)

just like Badlion and other clients, they have a simple toggle of whether you want Optifine or not.
Badlion example:
![image](https://user-images.githubusercontent.com/58079015/216245705-cd7e0e63-2a67-4e16-ab69-e3f349912deb.png)

Because it is currently hard to switch between versions and have optifine too, you will need to download the optifine file and to extract it you need to run the official launcher once...etc

**Comment by Ryex** [comment]
I'm... not sure how Badlion can legally do that.
It was my understanding that Optifine is very strict about their redistribution rules hence why you don't find it in modpacks like you do Sodium and Iris.
how are they even getting the direct downloads?

**Comment by Alyaqdhans** [comment]
Could be that they have the optifine files pre-downloaded on their end?

**Comment by Ryex** [comment]
possibly, but that would be against the Optifine license unless they have explicit permission from the dev.

**Comment by TheKodeToad** [comment]
This was previously discussed in https://github.com/PolyMC/PolyMC/issues/141. Parsing the HTML is possible but bypasses advertisements which isn't great.

**Comment by TheKodeToad** [comment]
Considering installing OptiFine is now slightly more involved, perhaps it could have a file picker which extracts and then installs the version with notch mappings?

**Comment by DioEgizio** [comment]
we legally can't do this

**Comment by TheKodeToad** [comment]
> Considering installing OptiFine is now slightly more involved, perhaps it could have a file picker which extracts and then installs the version with notch mappings?

This is legal though? Considering OptiFine is downloaded by the user.

**Comment by Ryex** [comment]
> > Considering installing OptiFine is now slightly more involved, perhaps it could have a file picker which extracts and then installs the version with notch mappings?
> 
> This is legal though? Considering OptiFine is downloaded by the user.

technicaly if the user downloaded the file and we presented a dialog to automate the standalone install it would be legal.
However, this really isn't somthing we should add as a feature imo.
