### ISSUE TITLE
Share settings/resource packs/shaders between profiles

### ISSUE THREAD

**Issue by MrDiamondDog** [PrismLauncher/PrismLauncher#811]
### Role

I play with multiple versions, sometimes modded.

### Suggestion

I want to be able to quickly change the settings of a new profile when I make it without having to go through it in game. It would also be helpful if this could happen with resource packs and shaders as well.

### Benefit

Quickly make new profiles without having to go through setting up everything you need.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flowln** [comment]
Already covered by #38, #175, #380 and  #422
