### ISSUE TITLE
Make prism launcher detect their respective loader if there's multiple loader versions on an update

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#818]
### Role

I play modded Minecraft

### Suggestion

make prism launcher detect their respective loader if there's multiple loader versions on an update

### Benefit

So that if a mod has multiple loader versions for the same Minecraft version it won't crash

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

when installing a mod that has multiple loader versions for one Minecraft version, prism launcher just chooses the latest released version. For example on the wyntils mod they have forge, fabric, and quilt for 1.19.3. Each for their respective loaders. However when I update it on quilt it does the most recent which is fabric. If there was maybe a drop down menu to choose or if the launcher detected the correct version it'd help players with that problem

**Comment by BalkanMadman** [comment]
As far as I am aware Modrinth API does not provide a way to specify modloaders for individual versions. Do not know how it is done on Curseforge's side, though.      
         
What could be done is some kind of version parser, which detects modloader based on version's name, e.g "mymod-fabric-177373737" -> fabric, etc

**Comment by BalkanMadman** [comment]
Just read Modrinth API specification and it is totally possible to do and Prism already does it.

I can't reproduce the issue — having an instance with two modloaders installed (fabric and forge) it downloads the version for enabled modloader (including updating existing mods). So, if Forge is enabled and mods supporting it are downloaded, Prism installs Forge's version, not Fabric's, irrespective of which one is the latest. The same behaviour is observed with Fabric being enabled.

**Comment by Aces-and-Jacks** [comment]
<img width="1512" alt="Screen Shot 2023-02-04 at 3 21 26 PM" src="https://user-images.githubusercontent.com/106651342/216788160-534aa84d-b3d8-46aa-aefd-a6e03ae31e60.png">
<img width="1512" alt="Screen Shot 2023-02-04 at 3 22 29 PM" src="https://user-images.githubusercontent.com/106651342/216788166-c49c85c9-0c5a-4753-83cb-97b77d202348.png">
<img width="1512" alt="Screen Shot 2023-02-04 at 3 22 38 PM" src="https://user-images.githubusercontent.com/106651342/216788168-a6f62a2a-9751-4dec-a62c-93c0bea3b1d9.png">

here's a photo example of what I mean. I download the version for quilt, and when I see if there's an update it updates to the fabric version which wouldn't work for that mod on that modloader

**Comment by Aces-and-Jacks** [comment]
it's fine with forge, but mainly a fabric and quilt issue. Other mods normally work fine with the fabric version of the mod on quilt but in this case a quilt version and a fabric version were both made for 1.19.3. And prism went with the most recent

**Comment by BalkanMadman** [comment]
Checked it out and I can confirm that it is indeed an issue with PrismLauncher. Will look into that!

**Comment by BalkanMadman** [comment]
Hell yeah, I found it!!
https://github.com/PrismLauncher/PrismLauncher/blob/d2fd0fd8e896e3d5dc0449ae719fdaa7d27968a5/launcher/modplatform/modrinth/ModrinthAPI.h#L42-L53
It adds Fabric to the list of modloaders if Quilt is in use

**Comment by flowln** [comment]
Yea, for this do be fixed, we need to at least add options in the mod downloader and updater to change the loader used, so that Quilt instances can download and update Fabric mods compatible with it. I have done the downloader filter [way way _way_ back then](https://github.com/flowln/PolyMC/tree/more_filters), but i kinda forgot about it because i also needed to do the mod updater options thing :p
maybe i can pick it up again when i get some time, or someone else can try their hands at it ^^

**Comment by BalkanMadman** [comment]
Have I understood correctly — you want Prism to prefer Quilt and fallback to Fabric when the former is not available?

**Comment by Aces-and-Jacks** [comment]
Yes

**Comment by BalkanMadman** [comment]
Well, Quilt does support Fabric mods, so, theoretically, it is not much of an issue, but rather a suggestion.
Even if it was somehow implemented there should be some kind of a toggle for users to decide. I will contact maintainers and we will see what we can get out of this...

**Comment by Aces-and-Jacks** [comment]
quilt supports fabric mods unless the mod itself has two separate fabric and quilt versions

**Comment by Aces-and-Jacks** [comment]
So i've come by another mod that also has separate mod loaders but it automatically selects the version. If I'm on fabric it selects fabric, if I'm on quilt it selects quilt. The mod is https://modrinth.com/mod/visual-overhaul

However for https://modrinth.com/mod/wynntils it doesn't select it. Is it something in the information when the mod is uploaded?

**Comment by wanesty** [comment]
this is especially an issue if a **fabric and a quilt** or a **forge and a neoforge** release have the same name on modrinth.

it seems like if the release title is the same it will select the first alphabetical occurrence of it, i detailed it better in an issue on Simple Voice Chat's repo https://github.com/henkelmax/simple-voice-chat/issues/636

**Comment by Trial97** [comment]
@Aces-and-Jacks is this reproduced on the latest nightly? There were a bit of changes regarding filtering.

**Comment by Aces-and-Jacks** [comment]
@Trial97 As of the 9.0 nightly that I tried, still the same issue

Tested with simple voice chat
Downloaded `Simple Voice Chat 1.20.2-2.5.11` for quilt
updated the mod
defaulted to `Simple Voice Chat 1.20.2-2.5.12` for fabric

**Comment by OmegaRogue** [comment]
theres also the problem of mod updates when using sinytra connector.
fabric has to be enabled as a loader (at least as a fake loader with no actual functionality) to download mods for fabric for use with sinytra connector and forge. This results in Prism wanting to update mods to their fabric version when checking for updates, instead of keeping them on forge if they were installed for forge

**Comment by Trial97** [comment]
@OmegaRogue in 9.0 you will be able to filter mods after the loader (allowing you to download fabric mods on forge without the loaders page)
And in implementation for this fix I already took into consideration checks if it has any version compatible with the instance and if not  then it will fail back to the selected modloader
