### ISSUE TITLE
Add /file to the end of the Curseforge download link.

### ISSUE THREAD

**Issue by AnAwesomGuy** [PrismLauncher/PrismLauncher#820]
### Role

Installing modpacks.

### Suggestion

Add /file to the end of the Curseforge download link.

### Benefit

So downloading mods that can't be accessed by 3rd party launchers is quicker.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://user-images.githubusercontent.com/79700396/216749445-a6e806d8-6fef-4de8-9b73-70ce996dea1f.png)
When downloading these mods, you have to wait 5 seconds before the mod downloads. Adding /file to the end of the URL downloads the mod automatically without you needing to wait the extra 5 seconds.

**Comment by DioEgizio** [comment]
CF doesn't want us to do this
