### ISSUE TITLE
Show a welcome background when there are no instances

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#827]
### Role

I- i don't know anymore i just want to help improve it; well i use the launcher

### Suggestion

I want there to be shown a "Right click here to create your first instance and get started" background text whenever there are no instances to show.

### Benefit

so newbies can know how to get started using the launcher faster

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
bad mockup
![image](https://user-images.githubusercontent.com/57493648/216812689-efb9e4c8-f5d6-41e3-bab3-496840a685c8.png)
pls don't comment on the vulnerable version.

**Comment by ghost** [comment]
yup! thanks for this

the color would be a bit darker (or ligher, depending on the theme) than the background, and there'd be a little icon above the text

**Comment by TheKodeToad** [comment]
one of these could be used
ℹ️
U+2139 (github formats it as emoji)
🛈
maybe using emojis and symbols in ui may be weird

**Comment by ghost** [comment]
yeah just use an .svg. Discord does something like that
