### ISSUE TITLE
Shader settings files being interpeted as shaders

### ISSUE THREAD

**Issue by kidofcubes** [PrismLauncher/PrismLauncher#830]
### Role

I use multiple shaders, with multiple setting presets

### Suggestion

I want Prism Launcher to ignore .txt files in the shader packs tab

### Benefit

so that all my settings files wont get mixed up with my shaders

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

my shader settings also appearing in the shader packs menu
![image](https://user-images.githubusercontent.com/40485669/216928620-d933526a-02b4-41e9-bbf9-b5f96e7b59dc.png)

makes it hard to see my real shaders 

integration into the launcher would be cool, but implementing the shader options screen into the launcher seems out of scope

**Comment by RaptaG** [comment]
This reminds me of the hide the .txt files PR

**Comment by Trial97** [comment]
should be fixed by https://github.com/PrismLauncher/PrismLauncher/pull/1657
