### ISSUE TITLE
Broken text at No Chat Reports CF page

### ISSUE THREAD

**Issue by AlexKurisu** [PrismLauncher/PrismLauncher#836]
### Operating System

Linux (Arch Linux)

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.4.2

### Description of bug

No Chat Reports CurseForge page contains broken text when viewed via mod downloader UI
![image](https://user-images.githubusercontent.com/60626727/217421752-04ce2d36-a663-4f71-832e-fb5d922b15ed.png)

### Steps to reproduce

1. Open mod downloader UI
2. Search for No Chat Reports
3. Choose the No Chat Reports mod
4. Enjoy broken text in headers

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by BalkanMadman** [comment]
Font issue?

**Comment by BalkanMadman** [comment]
Cannot reproduce on the latest development branch - https://github.com/PrismLauncher/PrismLauncher/commit/f36c3a3f6c795f1aa6b3dc9ff6f151b077531aaa...
![Screenshot_20230208_095948](https://user-images.githubusercontent.com/103487874/217469364-44eec50c-71e3-47ae-a59e-9f7d2792313a.png)


And on stable - https://github.com/PrismLauncher/PrismLauncher/commit/39bba9cbfadc0aac3ef571a80e78a9fa3f5a0028
![Screenshot_20230208_094512](https://user-images.githubusercontent.com/103487874/217466289-1d7af38d-66f2-4494-a875-a40ae03818b9.png)


Works as expected. ~~Will try to repro on stable.~~ Most likely it is missing font that causes the issue.

**Comment by BalkanMadman** [comment]
Try installing [`noto-fonts`](https://archlinux.org/packages/extra/any/noto-fonts/) and [`noto-fonts-emoji`](https://archlinux.org/packages/extra/any/noto-fonts-emoji/)

**Comment by AlexKurisu** [comment]
> Try installing [`noto-fonts`](https://archlinux.org/packages/extra/any/noto-fonts/) and [`noto-fonts-emoji`](https://archlinux.org/packages/extra/any/noto-fonts-emoji/)

I already have them installed. What fonts do you have?

**Comment by DioEgizio** [comment]
cannot reproduce but i think i know what the issue is: you don't have impact, which is used there; install microsoft fonts, on debian based distros the package is "ttf-mscorefonts-installer"

**Comment by TheKodeToad** [comment]
If the font is not installed, should it be rendering like that though?

**Comment by DioEgizio** [comment]
I don't know, might even be that the font is not correctly installed

**Comment by TheKodeToad** [comment]
Sounds like the most likely explanation. It looks like wingdings...
