### ISSUE TITLE
"Visit on mod's page" button in context menu when right-clicking mods, texture/shader packs

### ISSUE THREAD

**Issue by SplendidAlakey** [PrismLauncher/PrismLauncher#84]
### Role

I play modded MC.

### Suggestion

I want there to be an option to open a mod's webpage.

### Benefit

It would be a lot more convenient to report bugs, check descriptions, look for help with mods etc.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### This is a suggestion transferred from the old repo. 

Was using Mod Organizer 2 the other day and got too used to its "Visit on Nexus" feature. Want to quickly check the description of some mod to make sure you understand how it works? Or you found a bug and want to report it to the devs? Maybe you simply have got a question or want to compliment the mod in the comments? Easy, just right-click on the mod and choose "Visit on Nexus".

In case of Prism it's also extra useful, because currently texture/shader packs can't be automatically updated. Even if for those you would have to initially manually add a homepage link.

For Prism it would be nice for the button to either say "Visit on mod's page" / "Open the mod's page" or, if possible, automatically detect where the mod is hosted and display one of the following options: "Visit on CurseForge" / "Visit on Modrinth" / "Visit on GitHub" or wherever else said mod is hosted. If a mod is hosted on more than 1 platform, make an arbitrary priority of Modrinth > CurseForge > GitHub > whatever else (when MO2 doesn't recognize the source, but it is present it simply prints the link). If a mod has no homepage, don't display the button at all.

Quick mockup of the idea:
![image](https://user-images.githubusercontent.com/86702831/196535738-94da8cb3-9f81-41c5-9cf5-59a68cebd732.png)

**Comment by shadow7483147** [comment]
Bumping; for many mods, they might provide a url in the description seen just above the Filter in the mods list. This url can point to any arbitrary website such as the owner's webpage, or the mod may have no url and only a short description.

I'd rather be able to visit the mod's curseforge or modrinth page, if the mod was downloaded using the Download Mods button on the right.
