### ISSUE TITLE
The procedure entry point SystemParametersInfoForDpi could not be located in the dynamic link library Qt6Gui.dll

### ISSUE THREAD

**Issue by SoniEx2** [PrismLauncher/PrismLauncher#842]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.3 64-bit

### Version of Qt

DNF

### Description of bug

A popup appears with the given error. The launcher doesn't launch.

### Steps to reproduce

Click the exe

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Are you sure you extracted correctly the zip/checked if the zip was corrupted/what version of windows?

**Comment by SoniEx2** [comment]
Yes, double checked even. Windows 10.0.10586

**Comment by DioEgizio** [comment]
I'm pretty sure that windows 10 version is so old it's not supported by Qt. Try using the legacy version

**Comment by SoniEx2** [comment]
thanks

**Comment by FAWAZ-sudo** [comment]
what i want to do i have also same issue i cant open any new application in my pc window 10
