### ISSUE TITLE
Readd (X) button to mods list text filter...

### ISSUE THREAD

**Issue by Xetaxheb** [PrismLauncher/PrismLauncher#849]
### Role

Managing mods in instance properties

### Suggestion

There was an X in the filter bar on mods page to clear the existing search string... it doesn't exist anymore for who knows why

### Benefit

It's so much more convenient than clearing the bar with keyboard and had no reason to be removed

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flowln** [comment]
The reason why it got removed: https://github.com/PrismLauncher/PrismLauncher/pull/445

It's a Qt thingy, so not something we can deal with directly. You can still do Ctrl+A and delete everything, or just select stuff with a mouse. I can see the button being slightly convenient, but I don't think it's a big deal not having it, and its convenience is outcast by the performance gain of not having it imo.

**Comment by Xetaxheb** [comment]
That's tragic, but I agree not worth a bizarre 15% time increase.
