### ISSUE TITLE
FUNDING.yml directs to the PolyMC open collective

### ISSUE THREAD

**Issue by SierraKomodo** [PrismLauncher/PrismLauncher#85]
### Operating System

Other

### Version of PolyMC

N/A

### Version of Qt

N/A

### Description of bug

The `FUNDING.yml` file points to `polymc` on opencollective.com. This should probably be removed or updated.

### Steps to reproduce

N/A

### Suspected cause

N/A

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by CodexNotFound** [comment]
Will be fixed in #47
