### ISSUE TITLE
auto update

### ISSUE THREAD

**Issue by pizzav-xyz** [PrismLauncher/PrismLauncher#855]
### Role

general use

### Suggestion

make it update every time an update gets publiched

### Benefit

i would not have to redownload prism launcher every time it updates

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ghost** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/94
