### ISSUE TITLE
Exporting instances with the .mrpack format (Modrinth)

### ISSUE THREAD

**Issue by MbtMarco** [PrismLauncher/PrismLauncher#861]
### Role

I mainly create modpacks.

### Suggestion

Also add in the Prism Launcher the ability to export instances in the .mrpack (Modrinth) format as is already done on others: MultiMC, ATLauncher, etc..

### Benefit

Make it easier to create modpacks that can be published on Modrinth without having the need to use other tools.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ghost** [comment]
duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/269

**Comment by Scrumplex** [comment]
Yep
