### ISSUE TITLE
Quick scrolling of the modpack list at adding instance screen crashes the app on windows 10

### ISSUE THREAD

**Issue by ksoczowka** [PrismLauncher/PrismLauncher#863]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.4.2

### Description of bug

When in new instance screen and want to get a new modpack. When you scroll quickly the app crashes!

### Steps to reproduce

* Go to Adding new instance menu
* Select Modrinth/CurseForge
* Scroll down with mouse quickly
* Crash

### Suspected cause

It only occurs when the images doesn't load yet so I think it could be that app is trying to access the value of a page that doesn't exist so app is throwing an range error.
On the other hand I don't know, because there is no error message after the crash.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TayouVR** [comment]
can reproduce, issue seems to be caused by our ConcurrentTask
![image](https://user-images.githubusercontent.com/31988415/218801605-2739e554-091f-404f-b86d-35393f6b2d63.png)
https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/tasks/ConcurrentTask.cpp#L118

**Comment by ksoczowka** [comment]
May I try to fix this bug? I want to contribute to this project

**Comment by TayouVR** [comment]
go ahead! 
I am currently occupied with other tasks and my personal life, any contribution is welcome!

**Comment by Trial97** [comment]
Can you try the nightly build(https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/5394098599) and see if this is still reproducing?
