### ISSUE TITLE
Launcher crashes after clicking "mods" on edit page

### ISSUE THREAD

**Issue by TheFieryFalcon** [PrismLauncher/PrismLauncher#870]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.1

### Version of Qt

Qt 6.4.1

### Description of bug

Launcher should not have crashed when clicking on mods button, but it did

### Steps to reproduce

1. Start the launcher
2. Install the instance attatched
3. Click "Edit", then "Mods"
Instance:
https://www.mediafire.com/file/48jmcwt9d421v0m/The+Complete+1.7.10+Pack.zip/file

### Suspected cause

Logs: 
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/10765228/PrismLauncher-0.log)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by flowln** [comment]
Update to 6.3

**Comment by TheFieryFalcon** [comment]
That solves it, thanks!
