### ISSUE TITLE
Game crashes on startup on macOS

### ISSUE THREAD

**Issue by xijdk** [PrismLauncher/PrismLauncher#871]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.3.0

### Description of bug

Every time, I see such error in console and the game doesn't launch:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff800aca41d, pid=22986, tid=259
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (17.0.6+10, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)
# Problematic frame:
# 
C  [libobjc.A.dylib+0x641d]  objc_msgSend+0x1d
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/xijdk/Library/Application Support/PrismLauncher/instances/1.19.3/.minecraft/hs_err_pid22986.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Process crashed with exitcode 6.
```

I'm using 1.19.3 Quilt mod loader and some graphic mods, but I don't think they cause the issue. I tried to disable all mods, it didn't help.

### Steps to reproduce

* Make an instance with 1.19.3 Minecraft and Quilt mod loader
* Use Temurin or Zulu Java
* Start the instance
* See it open for several seconds and crash then

### Suspected cause

No actual suspects, but I think it can't be an issue of Quilt or some mod, rather of launcher itself.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Frontear** [comment]
Why are you so sure its a launcher issue? Please try running vanilla MC, or run those exact mods on a different launcher and see if the issue persists

**Comment by Trial97** [comment]
Closing this as there were no updates on this from February.
Also this is not launcher related
