### ISSUE TITLE
Prism launcher crashed when updating mods

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#875]
### Operating System

MacOS

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.3.0

### Description of bug

not to crash when updating mods

### Steps to reproduce

1. Update mods
2. crash

Not really sure how to reproduce issue. That's just what I did

### Suspected cause

Maybe from me deselecting other mods when updating

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment]
Edit: Removed log since this may contain sensitive info and is no longer needed

**Comment by mattp12** [comment]
I'm guessing this is the same issue I have here: #659 

Luckily it appears to have been fixed a few weeks ago and will make it into a future release. #802

**Comment by Aces-and-Jacks** [comment]
ah ok then. I'll close then since it's a similar issue

**Comment by Poopooracoocoo** [comment]
So it crashes when you click on "check for updates" before the metadata of all the mods has loaded? If so, I think that may be the same issue as 659

**Comment by Aces-and-Jacks** [comment]
Yeah, I figured it might've been the same issue. Tho from what I remember it didn't happen when I clicked on "check for updates" but when I filtered out some mods and pressed "ok"
