### ISSUE TITLE
Provide dark-theme friendly logos

### ISSUE THREAD

**Issue by hwittenborn** [PrismLauncher/PrismLauncher#878]
[makedeb's Homepage](https://makedeb.org) is currently in the process of [getting dark theme support](https://github.com/makedeb/makedeb.org/pull/26), but the Prism Launcher icon doesn't contrast very well on it:

![image](https://user-images.githubusercontent.com/74838472/220015360-cc378c47-81b0-4261-9d9a-b07fab26e06d.png)

Would it be possible to create another logo that uses lighter-colored text, so that it stills looks good on makedeb's Homepage?

**Comment by TayouVR** [comment]
we have a bright text logo on our website. See https://prismlauncher.org/
![image](https://user-images.githubusercontent.com/31988415/220126698-244303ec-4b7e-4672-ad4a-28180ab9d7e0.png)

So I'd imagine the makedeb team can just grab it and use it. They might even already have it somewhere anyways.

The light and dark variants are both located here: https://github.com/PrismLauncher/prismlauncher.org/tree/main/src/img
Logo-text.svg and Logo-text-darkmode.svg

**Comment by Scrumplex** [comment]
We also have these, which are probably identical to the ones on the website:
https://github.com/PrismLauncher/PrismLauncher/blob/develop/program_info/org.prismlauncher.PrismLauncher.logo.svg
https://github.com/PrismLauncher/PrismLauncher/blob/develop/program_info/org.prismlauncher.PrismLauncher.logo-darkmode.svg

**Comment by hwittenborn** [comment]
Didn't notice those were out there, those will work perfectly! Thanks a ton :)
