### ISSUE TITLE
Queue up instance management operations for convenience.

### ISSUE THREAD

**Issue by GBLodb** [PrismLauncher/PrismLauncher#879]
### Role

Modpack developer

### Suggestion

Queue up instance management operations at game runtime and execute them automatically after the game process ends.

### Benefit

This will prevent you from forgetting to do related operations after the game is closed, and provide convenience when dichotomizing mods, replacing mod versions, and other troubleshooting operations.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Trial97** [comment]
This should no longer be needed.
You should be able to edit the setting and manage mods on a running instance,
