### ISSUE TITLE
Failed to get Minecraft access token: Connection closed

### ISSUE THREAD

**Issue by MrDefined** [PrismLauncher/PrismLauncher#883]
### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.4.2

### Description of bug

Cannot add a new account

### Steps to reproduce

Add an account

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by flowln** [comment]
Please provide more information. What OS are you on? Have you updated from 5.x to the current version? Do any other network related functionalities work?

**Comment by Trial97** [comment]
Closing this as no additional information was provided.
