### ISSUE TITLE
Crashes when editing pre-existing Quilt instances

### ISSUE THREAD

**Issue by LackingCats** [PrismLauncher/PrismLauncher#884]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.0-develop (8ce8055aeb3e610088ff5a08f509862c1feafd8f) [Not unique to this commit, just the version I am currently using]

### Version of Qt

5.15.8

### Description of bug

When I go to edit instances with the quilt mod loader, it just crashes. The instance settings window should appear, however the whole program crashes.

### Steps to reproduce

* Click on instance with quilt installed
* Click the "edit" button

### Suspected cause

Whenever it crashes, PrismLauncher-x.log always has some variation of this:
9.600 D | Task "ComponentUpdateTask(0x55774c9507f0)" starting for the first time
     9.600 D | Loading components
     9.600 D | Index is already loaded
     9.600 D | Component list save is scheduled for "Adrenaline 1.10.6-Quilt-1.18.2"
     9.600 D | Task "NetJob(Download of meta file org.quiltmc.quilt-loader/0.17.8.json)" starting for the first time
     9.600 D | Remote loading is being run for "Quilt Loader"
     9.618 D | Instance-type specific settings were loaded!
     9.648 D | Applying "org.lwjgl3" GOOD
     9.648 D | Applying "net.minecraft" GOOD
     9.648 D | Applying "net.fabricmc.intermediary" GOOD
     9.648 D | Applying "org.quiltmc.quilt-loader" ERROR

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by telans** [comment]
Is this still happening? I can't reproduce this

**Comment by LackingCats** [comment]
It's been fixed in previous releases
