### ISSUE TITLE
Cant use optifine pre 5 on 1.19.3 on PrismLauncher.

### ISSUE THREAD

**Issue by St0rmzBr0z** [PrismLauncher/PrismLauncher#885]
### Operating System

Windows

### Version of Prism Launcher

6.3

### Version of Qt

6.3.0

### Description of bug

I cant use optifine pre 5 for 1.19.3 minecraft on prism launcher as a standalone and yes i extracted the mod jar for optifine and i put it in and it says "(Custom)" and i thought it was normal and when i play it doesnt have the optifine settings and all that i followed the instructions here https://prismlauncher.org/wiki/getting-started/installing-optifine and here is a screenshot of it
![2023-02-23 (1)](https://user-images.githubusercontent.com/126161130/220888647-d0ac9d12-cf67-4ef1-b586-3e6b2f0863a1.png)

### Steps to reproduce

* I putted it with the "Add to minecraft.jar" button like the prism launcher for starters tutorial on the website

### Suspected cause

Probably my optifine version.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
1. Run the optifine installer and click on extract
2. Extract the `preview_OptiFine_1.19.3_HD_U_I2_pre3_MOD.jar` file with an archive manager (winrar, file roller...)
3. Move the contents of the `notch` folder in the extracted files to the root
![image](https://user-images.githubusercontent.com/110736028/221368010-4782b990-3b3a-4e3e-b18d-5ac260cccc33.png)
4. Recompress the files in the `zip` format
![image](https://user-images.githubusercontent.com/110736028/221369652-466047cf-177e-4215-bed7-135f8eb169bb.png)
5. Change the file extension to be `.jar` e.g change `optifine_mod.zip` to `optifine_mod.jar`
6. Use that as the jar mod
![image](https://user-images.githubusercontent.com/110736028/221368313-0d434c43-4074-49e0-915d-d7087bd1bfe0.png)

**Comment by St0rmzBr0z** [comment]
Ok i will try that method i will give updates on it.

**Comment by St0rmzBr0z** [comment]
![2023-02-28 (3)](https://user-images.githubusercontent.com/126161130/221615612-b943b36f-d26c-46ba-a44d-29f22621b549.png)
New update, i did the method and it works but i have one problem why is the text look like the screenshot i attached, i tried pre 3 and pre 5 optifine 1.19.3 version but it still look like the attached screenshot, any fix? Thanks.

**Comment by Scrumplex** [comment]
Probably a bug with OF

**Comment by St0rmzBr0z** [comment]
Oh ok, thanks anyway.

**Comment by St0rmzBr0z** [comment]
Im closing the issue then.
