### ISSUE TITLE
Mod updater ignores some updates

### ISSUE THREAD

**Issue by UltraBlackLinux** [PrismLauncher/PrismLauncher#890]
### Operating System

Linux

### Version of Prism Launcher

6.1

### Version of Qt

6.4.2

### Description of bug

The mod updater for some reason ignores a few mod updates. Modmenu's update notification got my attention here.

### Steps to reproduce

Download Spark 1.10.29. It fails to update to https://modrinth.com/mod/spark/version/g60nhl1v

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FractalGeodes** [comment]
The version page you linked is for a version earlier than the one you mentioned

**Comment by UltraBlackLinux** [comment]
oh crap it really is... Then modmenu is just doing some weird stuff xD
