### ISSUE TITLE
Cannot download the blocked mods thru the links or open missing button?

### ISSUE THREAD

**Issue by susan3333333** [PrismLauncher/PrismLauncher#899]
### Version of Prism Launcher

Prism Launche 6.3

### Version of Qt

QT 6.4.2

### Description of bug

When the modpack needs to download a blocked mod, there is a list window with links and the open missing button.
These should allow to download the mods, but I am getting access denied popup from KIOExec?
It's not too bad in a small pack, but copying the link and pasting it in browser for 20-50 mods is not only slow, but difficult for me to work with the list, as I have some visual issues.
How do I fix it? 
I am on Opensuse Tumbleweed, using the stable prism repo provided from here: https://prismlauncher.org/download/linux/

### Steps to reproduce

Install a mod pack
When the window for the blocked mods comes up, click either the individual links or the open missing button.
Wait for error window. 
Cry.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
This sounds like a system configuration issue.
Qt via kde is trying to open a browser but is being denied permission.

Do you have a default browser set up?
If you use `xdg-open` on a url from a terminal does it work? Are you running the launcher from flatpak with hardened security? 

All or any of these could cause issues.

**Comment by susan3333333** [comment]
That was it, the first one. 
I had firefox as default, but I had recently installed a new filemanager, SpaceFM,  and it had without my knowing, set itself as default web browser! This is wrong, goodbye SpaceFM!
Thank you for suggesting to check the default, I knew I had firefox set, but looked anyways and found this.
