### ISSUE TITLE
Failed to download Modpacks

### ISSUE THREAD

**Issue by jitoxx** [PrismLauncher/PrismLauncher#902]
### Operating System

Windows

### Version of Prism Launcher

Newest Prism Launcher Develop Edition

### Version of Qt

Qt 6.4.2

### Description of bug

When i try to download any modpack, it says after downloading the manifest that an error has occured to unzip the modpack

### Steps to reproduce

Open the launcher
Try to download any modpack, for example All The Mods 3

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Frontear** [comment]
I can confirm this issue on the latest version of develop. I have tried deleting cache and LAUNCHER_TEMP files entirely but that did not fix the issue. 0eae935 might have been the commit that broke things but I don't know for sure.

```
   104.748 D | Task "NetJob(Modpack download)" starting for the first time
   104.753 D | Task "Net::Download(0x20eeb5cb100)" starting for the first time
   104.753 D | Downloading  "https://edge.forgecdn.net/files/3983/578/Valhelsia Enhanced Vanilla-1.4.2b.zip"
   108.351 D | Download succeeded: "https://edge.forgecdn.net/files/3983/578/Valhelsia Enhanced Vanilla-1.4.2b.zip"
   108.352 D | Task "NetJob(Modpack download)" succeeded
   108.354 D | Attempting to create instance from "D:/Games/Minecraft/Client/cache/edge.forgecdn.net/files/3983/578/Valhelsia Enhanced Vanilla-1.4.2b.zip"
   108.395 D | Flame: ""
   108.395 D | Extracting subdir "" from "D:/Games/Minecraft/Client/cache/edge.forgecdn.net/files/3983/578/Valhelsia Enhanced Vanilla-1.4.2b.zip" to "D:/Games/Minecraft/Client/instances/.LAUNCHER_TEMP/{878e75fb-ec97-4d97-8cc7-a6ca3e416f1b}"
   108.395 W | Failed to extract file "manifest.json" to "/D:/Games/Minecraft/Client/instances/.LAUNCHER_TEMP/{878e75fb-ec97-4d97-8cc7-a6ca3e416f1b}/manifest.json"
   108.396 C | Task "InstanceImportTask(0x20eecfb30f0)" failed:  "Failed to extract modpack"
   108.396 C | Task "InstanceStaging(0x20eebdb9230)" failed:  "Failed to extract modpack"
```

Above is a snippet of the log, and below is the full log.

[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/10889756/PrismLauncher-0.log)
