### ISSUE TITLE
Setting the java version from a path is broken

### ISSUE THREAD

**Issue by Nukiloco** [PrismLauncher/PrismLauncher#905]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

5.15.8

### Description of bug

I can't set the java path as /usr/lib/jvm/java-19-openjdk/amd64/bin/java

If i choose it from the file picker it chooses /run/user/1000/doc/3eb3036a/java

If I brute force it, the game thinks I have set no java path at all

### Steps to reproduce

This can either be reproduced in the global settings or the instance settings
Note the one I have installed is a flatpak

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by legendaryoaks** [comment]
For anyone else encountering this issue, I got around this by using the terminal to copy and paste the jdk directory into the flatpak directory. Auto-select will be able to find the executable in there.

**Comment by DioEgizio** [comment]
This is because you're using flatpak. You can't use system java on flatpak without granting the prism flatpak access to the entire disk on flatseal/plasma settings

**Comment by KSPAtlas** [comment]
> For anyone else encountering this issue, I got around this by using the terminal to copy and paste the jdk directory into the flatpak directory. Auto-select will be able to find the executable in there.

This does not work, java will then complain about missing java.security

**Comment by Chillsmeit** [comment]
In my case, even after giving Prism permission to the folder /usr/lib/jvm I had the same issue.

What you can do instead is to put java releases in /opt/java for example and if you give Prism permission to access /opt/, it will work.

You can also set them as default and link it them to /usr/bin/java.
I personally use [Temurin](https://adoptium.net/temurin/releases/) and this is what I usually do:
```
wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.9%2B9/OpenJDK17U-jdk_x64_linux_hotspot_17.0.9_9.tar.gz # Download Temurin
tar -xvf OpenJDK17U-jdk_x64_linux_hotspot_17.0.9_9.tar.gz
sudo mkdir /opt/OpenJDKTemurin
sudo mv jdk-17.0.9+9 /opt/OpenJDKTemurin
sudo update-alternatives --install /usr/bin/java java /opt/OpenJDKTemurin/jdk-17.0.9+9/bin/java 500
sudo update-alternatives --set java /opt/OpenJDKTemurin/jdk-17.0.9+9/bin/java # this sets the default java the system uses to jdk-17.0.9+9
java --version # You can use this command to check which java is set as default
sudo flatpak override --filesystem=/opt/OpenJDKTemurin org.prismlauncher.PrismLauncher # giving permission to Prism to access the /opt/OpenJDKTemurin folder
```

**Comment by SeanMcMillan** [comment]
Looks like this is the same problem I am having in 9.1.

Neither sharing /usr/lib/jvm, nor sharing the whole disk allows prism to see my system installed java.

I understand if this is not something you're going to do, but a little documentation would go a long way. Something like "The flatpak version of prism will not use system java" in the documentation somewhere.
