### ISSUE TITLE
PrismLauncher doesn't seen to work well on Linux Mint

### ISSUE THREAD

**Issue by Nukiloco** [PrismLauncher/PrismLauncher#908]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.3 on all the other versions that I installed
Prism Launcher 7.0 on nix packages

### Version of Qt

Qt 5.15.8

### Description of bug

The modpack that I'm testing here is All Of Fabric 6 which seems to be the modpack that causes the most issues with PrismLauncher:

|Package Type |Launcher Works|Modpack Works|Notes |
|-|-|-|-|
|Nix|Yes|No|GLFW either complains about the window not being able to be created or that its library is missing|
|AppImage|Yes|Yes|It is VERY slow. Downloads take forever and loading worlds is very slow|
|Flatpak|Yes|No|Depending on the java version, its either exit code 6 or exit code 255. If you need other java versions you will have to manually copy Java versions into it in order to work. I believe one of the error is due to graphics though I did expose the graphics to by using flatseal but it seems to just yield the same results|
|Prebuilt MPR|No|No|It complains whenever I do ``sudo apt update`` and doesn't list the packages|
|Portable|No|No|Complains that QT is missing even though its installed? Not a very detailed error message|
|Portable with QT|No|No|Still complains that QT is missing even though its bundled with it? Not a very detailed error message|

I seen other people having issues like these too and I haven't seen a fix at all from what I searched up

### Steps to reproduce

^

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Ryex** [comment]
Thank you you for a through report, however we will need specific error messages and logs to begin to figure out what is going wrong. Please upload and link the prismlauncher-0.log file from the data directory.

For flatpak that will be `~/.var/app/org.pridmlaumcher.PrismLauncher/data/Prismlauncher`. 

For everything else it should be `~/.local/share/PrismLauncher`. 

For portable it should be directly next to the binary.

**Comment by Nukiloco** [comment]
Flatpak logs
https://mclo.gs/IOeyS9K

**Comment by Nukiloco** [comment]
Nix logs
https://mclo.gs/gFdiLQ8

**Comment by Nukiloco** [comment]
Prism Launcher Portable
```
/home/nukiloco/Programs/PrismLauncher-Linux-Portable-6.3/prismlauncher: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory
```

**Comment by Nukiloco** [comment]
Prism Launcher QT Portable
```
/home/nukiloco/Programs/PrismLauncher-Linux-Qt6-Portable-6.3/prismlauncher: error while loading shared libraries: libQt6Widgets.so.6: cannot open shared object file: No such file or directory
```

**Comment by DioEgizio** [comment]
Ok so let's start
For nix it's because of something with glibc

For flatpak It might be an issue with the modpack

For prebuilt MPR it doesn't work it's because you didn't read what it says
> NOTE: Prebuilt MPR only officially supports Debian 11, Ubuntu 20.04 and Ubuntu 22.04.

In short, you have to change the codename of your Linux mint version in /etc/apt/sources.list.d/prebuilt-mpr.list to the codename of the Ubuntu version your lm version is based on, then sudo apt update && sudo apt install prismlauncher

For qt5 and qt6 portable the error is very self explanatory, you literally didn't install qt

**Comment by Nukiloco** [comment]
> Ok so let's start For nix it's because of something with glibc
> 
> For flatpak It might be an issue with the modpack
> 
> For prebuilt MPR it doesn't work it's because you didn't read what it says
> 
> > NOTE: Prebuilt MPR only officially supports Debian 11, Ubuntu 20.04 and Ubuntu 22.04.
> 
> In short, you have to change the codename of your Linux mint version in /etc/apt/sources.list.d/prebuilt-mpr.list to the codename of the Ubuntu version your lm version is based on, then sudo apt update && sudo apt install prismlauncher
> 
> For qt5 and qt6 portable the error is very self explanatory, you literally didn't install qt

Ah thanks for the information! Sorry if I came off rude, which I didn't mean to at all! I didn't quite understand the Prebuilt MPR note what it was saying until i looked at it further. Also I assumed QT was already installed to begin with and that the Portable QT version would come with QT. Thanks for the help!
