### ISSUE TITLE
UI: make sidebar width of buttons  consistent

### ISSUE THREAD

**Issue by Maykeye** [PrismLauncher/PrismLauncher#914]
### Role

I play modded minecraft

### Suggestion

I want side bar buttons to have equal width

### Benefit

so that how easy is to click on button doesn't depends on how long the text is

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Right now `edit` button, which is probably one of the most used button on the side bar, can only be clicked if you hover over the text, and the text is very short comparing to other buttons.

![image](https://user-images.githubusercontent.com/13607441/223027169-49fd3064-6357-4b36-8cc4-ef2920d46979.png)

I suggest to make all button width equally large and consistent, i.e. make them go to the right side of the main window:

![image](https://user-images.githubusercontent.com/13607441/223027188-d9e9c846-0acd-488b-aa8b-aaa02f23bf96.png)

That would allow to hover and click empty space, making it much better experience: Right now mouse pointer makes the button unreadable:
![image](https://user-images.githubusercontent.com/13607441/223028036-a3aa65b9-795e-483f-8541-04a829aef91d.png)

Is it "edit"? "exit"? "blit"? It's not possible to read the text of the button if I hover in the center of the button. If the button used all available space

![image](https://user-images.githubusercontent.com/13607441/223029119-ad2fa7a8-e469-4c4f-9eeb-860b751bd5c2.png)

it would be much easier to click.

**Comment by DioEgizio** [comment]
Should be fixed in develop since #724

**Comment by DioEgizio** [comment]
Closing as it's fixed in develop
