### ISSUE TITLE
Make the java compatibility check less strict

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#917]
### Role

I use the launcher

### Suggestion

I want the java compatibility check to not be as strict, notably allowing recent versions to be ran with java 17-19 instead of just 17, and earlier vesions to be ran with java 8 and 11 instead of just 8.

### Benefit

So there is less hassle for new users in case they have a "wrong" Java version installed.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Scrumplex** [comment]
Java 18 is EoL and shouldn't be used anymore. Java 19 breaks some mod loaders because of the new class version. That's why we intentionally removed those two from the compatibility check

**Comment by ghost** [comment]
The force stop on a version mismatch could be a non-default option, with it otherwise just giving a warn (with the good java version recommendation) like it does now when skipping compat checks

**Comment by Scrumplex** [comment]
If you know what you are doing, just go to the global launcher settings and disable the check there. Most users should probably use the right Java versions. Keep in mind that Java 17 is LTS, so it is the preferred version for all applicable MC versions

**Comment by Trial97** [comment]
Going to close this as we prefer to check that by default.
You can disable it globally pretty easily if needed.
