### ISSUE TITLE
Prism "Offline account" bug

### ISSUE THREAD

**Issue by SleepyFemboy** [PrismLauncher/PrismLauncher#920]
### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.4.2.

### Description of bug

The launch button sometimes decides i am not connected into my account, and automatically forces me to choose an offline name.

### Steps to reproduce

I don't know how to reproduce the bug, but it happens randomly.

### Suspected cause

None

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Qwerty-Space** [comment]
I'm also experiencing this issue.  Should you need any logs, I might be able to provide.

When this issue occurs, the news also doesn't load

**Comment by ThaBluNate** [comment]
Sounds like #592 which has been plaguing users since 5.1

**Comment by khankul** [comment]
Can confirm, this forces me to restart the launcher multiple times until I can launch the game in online-mode.
