### ISSUE TITLE
Cant run newer packs as it needs java17.0.6 and the flatpack is only bundled with java17.0.41

### ISSUE THREAD

**Issue by jmars125** [PrismLauncher/PrismLauncher#921]
### Operating System

Steam Deck 3.4

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

5.15.8.

### Description of bug

Upgrade your Java 17 install to Java 17.0.6 for lwjgl3ify to work your java version is 17.0.41+12

### Steps to reproduce

Install a newer modpack that requires lwjgl3ify and you will receive this error

GT New Horizons j9 version is an example

### Suspected cause

If the flatpack could be bundled with Java 17.0.6 instead of Java 17.0.41+12 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk17/commit/1ef80f5a8aa44bbf1aa9363c8ca71c1c616eafe5

org.freedesktop.Sdk.Extension.openjdk17 was recently updated for java 17.0.6, so a rebuild of the flatpak package should be enough

**Comment by Scrumplex** [comment]
I triggered and published a rebuild just now. Not sure if it is available immediately, but let's hope this fixes it.

**Comment by jmars125** [comment]
awesome, it worked for me thank you!!!
