### ISSUE TITLE
Double click a mod in mods list to open its curseforge or modrinth page

### ISSUE THREAD

**Issue by anar4732** [PrismLauncher/PrismLauncher#923]
### Role

Player

### Suggestion

Double click a mod in mods list to open its curseforge or modrinth page

### Benefit

So we can easily get info about the mod its wiki etc.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheKodeToad** [comment]
?
