### ISSUE TITLE
Appimage version can't detect bundled java

### ISSUE THREAD

**Issue by nachoslover813260** [PrismLauncher/PrismLauncher#924]
### Version of Prism Launcher

PrismLauncher-Linux-6.3-x86_64.AppImage

### Version of Qt

Qt version 6.2.4

### Description of bug

java auto-detection in prismlauncher can't detect bundled java in appimage

### Steps to reproduce

1.Launch prismlauncher's appimage
2.Navigate to "Settings" > "Java"
3.Click "auto-detect..."

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Can you send logs?

**Comment by nachoslover813260** [comment]
http://0x0.st/HoF2.txt

This is the output from opening the launcher > click settings > click java > click autodetect > cancel
This host machine is running fedora workstation 37
