### ISSUE TITLE
Mac M1 Crash on CurseForge modpack update

### ISSUE THREAD

**Issue by mnooseman** [PrismLauncher/PrismLauncher#936]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.3.0

### Description of bug

When attempting to update a CurseForge modpack, Prism Launcher crashes to desktop.

### Steps to reproduce

* Edit existing Modpack Instance
* Click CurseForge on left of Edit Screen
* Click Update Button to update the modpack
* Watch Prism Launcher crash
[message (3).txt](https://github.com/PrismLauncher/PrismLauncher/files/10985482/message.3.txt)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Mrquarter** [comment]
Any update on a fix for this bug? Having this exact issue as well :(

**Comment by Ozzymud** [comment]
Just popped in to say same thing but not on macOS, happening to me on Win10

**Comment by OttersMeep** [comment]
I am experiencing this bug as well. For some reason, this isn't happening with some modpacks.

Modpacks I tested that do crash:
Create: Stratus Terra
Modpacks that didn't:
Create Technical
Fabulously Optimized

**Comment by Scrumplex** [comment]
Can some send a new crash report / backtrace? The codebase has changed a bit since then

**Comment by Trial97** [comment]
Closing this as there were no update for more than one year.
We will reopen it if needed
