### ISSUE TITLE
Mod Download Folder not recursively searched.

### ISSUE THREAD

**Issue by AbyssalMonkey** [PrismLauncher/PrismLauncher#938]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

QT 5.15.2

### Description of bug

When adding a modpack, the searched folder for mods does not recursively search through sub folders.
![Prism Search](https://user-images.githubusercontent.com/29171166/226225657-5445e249-84d1-452c-a16b-9eb57506574a.JPG)

### Steps to reproduce

Add mods in subfolder
Add modpack
Watch fail

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Frontear** [comment]
I dont think subdirectory searching was ever implemented. Why not just set the path to the directory itself?

**Comment by DioEgizio** [comment]
not a bug, but definetly a feature request

**Comment by Ryex** [comment]
It's pretty simple to add. The question then is should this be default behavior or an option in settings?

**Comment by Frontear** [comment]
theres no reason for it to not be a default behaviour unless there are concerns with performance in huge directories, which i doubt the average person has.
