### ISSUE TITLE
Windows updater

### ISSUE THREAD

**Issue by elchupe123** [PrismLauncher/PrismLauncher#94]
### Role

I play minecraft in general

### Suggestion

Continue developing the windows updater that was being develop in poymcl

### Benefit

It would be easier to update polymc

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Madis0** [comment]
Cross-post:
> Perhaps a temporary workaround could be to make a changelog popup similar to macOS, but upon clicking install it would simply open the installer exe download in the default browser.
> Would that be easier to implement?

**Comment by Grithz** [comment]
The launcher does not have full releases yet. It has some developer builds you can get from the Github Actions. I am sure that they will implement the updater when there are full releases.

**Comment by Madis0** [comment]
> The launcher does not have full releases yet. It has some developer builds you can get from the Github Actions. I am sure that they will implement the updater when there are full releases.

The issue is here because this has been a long-standing topic for PolyMC as well, aka PolyMC did not have a Windows updater either.

**Comment by forkiesassds** [comment]
macOS version already has an updater, all that could be done for Windows updater is to use a Windows specific version of Sparkle and reuse the same old updating code already used.

**Comment by elchupe123** [comment]
We could use a Python script to downlod the new version from GitHub. Then it should unzip the files (also with Python) and re-start prism but using the new .exe renaming the old .exe as .exe_old

**Comment by TheKodeToad** [comment]
MultiMC has this feature. I wonder why their updater code can't be used for Prism Launcher - it seems like the maintainers plan to remove it.

**Comment by Scrumplex** [comment]
> it seems like the maintainers plan to remove it.

It seems to be fairly undocumented and didn't look like it was easy to implement with our current release workflows.
