### ISSUE TITLE
Selecting a mod for download displays all mods with the same name as selected

### ISSUE THREAD

**Issue by zacharylove** [PrismLauncher/PrismLauncher#943]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.3.0

### Description of bug

Selecting a mod for download also displays all other mods with the same name as selected in the search results. The other mods only look like they are selected, they are not actually selected for download.

In this screenshot, I have selected the first result for download, but the second result is also displayed as selected.
<img width="714" alt="image" src="https://user-images.githubusercontent.com/12072877/226438476-f64a237b-a59b-4717-a7fc-312501205d35.png">
However, the second mod is not actually selected for download- it is just displayed as such:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/12072877/226438756-d8b44edb-3ae0-4394-b4c0-c6290e7a4060.png">

Selecting either one of the identically-named results will cause both entries' titles to be bolded and underlined.

### Steps to reproduce

 - Create a new Minecraft 1.19.2 instance
 - Install Forge 43.2.7
 - In the "Mods" section of the instance, select "Download mods" on the right-hand sidebar
 - In the download menu, search for "double doors" in Modrinth (two results named "Double Doors" should appear at the top of the list)
 - Click on either "Double Doors" mod and hit the "Select mod for download" button
 - Both mods' titles appear as bolded and underlined in the result list.

### Suspected cause

The behavior seems to indicate that Prism Launcher is searching the list of results for all entries whose title matches the title of the selected mod (in this case, "Double Doors"), then changing those entry to display as selected. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FractalGeodes** [comment]
Confirmed on windows

**Comment by annaleighsmith** [comment]
confirmed on Linux as well

**Comment by Trial97** [comment]
Can you reproduce it on the latest release?

**Comment by zacharylove** [comment]
> Can you reproduce it on the latest release?

Can confirm this bug is fixed on Prism Launcher 7.2 on MacOS

![CleanShot 2023-09-26 at 15 41 08@2x](https://github.com/PrismLauncher/PrismLauncher/assets/12072877/6a630224-a3db-4299-941d-610204f1c249)
