### ISSUE TITLE
Can't Download the ModPack

### ISSUE THREAD

**Issue by louanfontenele** [PrismLauncher/PrismLauncher#944]
### Operating System

Windows

### Version of Prism Launcher

6.3

### Version of Qt

6.4.2

### Description of bug

Cant download mobpack, tell it doesnt have a version

![image](https://user-images.githubusercontent.com/2886066/226682800-cf7ddcc7-523b-4efc-a2a1-ab939e4df6dd.png)

### Steps to reproduce

Try to download DawnCraft

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by flowln** [comment]
This modpack is [not available to third-party distribution](https://cflookup.com/829758), meaning the same as the _Nota_ on the top of the page, but applied to modpacks instead of mods.

Download the modpack zip from the CurseForge website directly, and then import it into Prism.
