### ISSUE TITLE
Add PrefersNonDefaultGPU=true to .desktop File on Linux

### ISSUE THREAD

**Issue by ElliotLurie** [PrismLauncher/PrismLauncher#948]
### Role

I play on a dual GPU laptop running Linux

### Suggestion

Add the line `PrefersNonDefaultGPU=true` to the desktop launcher file

### Benefit

This tells Linux desktops to launch the application on the dedicated GPU by default in hybrid scenarios

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
There's a reason why we don't do it. It causes issues for people with just a dedicated gpu and other issues.
You don't even need it, just check "use discrete GPU" in settings-minecraft
