### ISSUE TITLE
Add login to onboarding

### ISSUE THREAD

**Issue by Poopooracoocoo** [PrismLauncher/PrismLauncher#949]
### Role

A new user

### Suggestion

I want Prism to prompt me to login when I open it for the first time

### Benefit

In order to play Minecraft

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

As it currently stands, users must know to create an instance and will then see the login prompt:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/51363864/227555333-5c5df32e-a311-42ca-90d1-38dfba7994a8.png">
This could be much better.

I'd also like to see that message mention that the Mojang or Microsoft account must have a license to Minecraft. 

Prism already has a quick setup on first launch where it asks users to select a language and a Java executable. Logging in should be part of this quick setup as it's not clear where to start.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/51363864/227554511-43b5b0d1-08f3-4386-9ab7-e3ff860925ee.png">
It's also quite empty. This should have some sort of text that informs users that they can add an instance by clicking on "Add Instance". If this is something skippable like the language selection prompt in the quick setup, it should also inform users when they haven't added an account that they will be unable to play, should they skip that in the quick setup. It should also inform users when they haven't added a path Java executable (as that can be skipped for each launch). 

<img width="618" alt="image" src="https://user-images.githubusercontent.com/51363864/227873483-96f37221-d302-42bd-bf32-7391466b3857.png">
This message should state that their account must have a license to Minecraft, and that Mojang accounts are only capable of playing offline and that users must migrate to a Microsoft account for online functionality.

**Comment by TayouVR** [comment]
we could probably put the entire accounts panel into the WelcomeWizard. Doesn't seem like that hard of a task either.
👍
