### ISSUE TITLE
Discord 

### ISSUE THREAD

**Issue by elchupe123** [PrismLauncher/PrismLauncher#95]
### Role

I play minecraft in general

### Suggestion

It would be great to create a discord 

### Benefit

Everyone could help during the devlop

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by GeefireMC** [comment]
there is a discord linked in the README. https://discord.gg/prismlauncher

**Comment by PureTryOut** [comment]
Please also consider setting up a (bridged) Matrix room. PolyMC had this and it allowed me to talk while not having to use Discord. The README indeed mentions a Discord room but not a Matrix one.

**Comment by Seercat3160** [comment]
> Please also consider setting up a (bridged) Matrix room. PolyMC had this and it allowed me to talk while not having to use Discord. The README indeed mentions a Discord room but not a Matrix one.

On the Discord this has been discussed somewhat by the maintainers, with the verdict that at least for now (as the project is new) it's too hard to moderate

**Comment by PureTryOut** [comment]
Well the project isn't that new, it's a continuation of PolyMC no? It seemed to work just fine there. Too bad, I'll have to wait till a Matrix bridge is setup at some point then, I won't create a Discord account.

**Comment by Scrumplex** [comment]
> On the Discord this has been discussed somewhat by the maintainers, with the verdict that at least for now (as the project is new) it's too hard to moderate

this was about Matrix, not Discord.

> Well the project isn't that new, it's a continuation of PolyMC no? It seemed to work just fine there. Too bad, I'll have to wait till a Matrix bridge is setup at some point then, I won't create a Discord account.

will come eventually
