### ISSUE TITLE
Add reminder about screenshot uploading

### ISSUE THREAD

**Issue by F640** [PrismLauncher/PrismLauncher#951]
### Role

I use the launcher

### Suggestion

When upload button pressed, it will show a reminder that the screenshot will be uploaded to internet and anyone can see it

### Benefit

so i will know its function and do not accidentally upload it to internet

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Soo.. When i saw upload button in screenshot section, i thought that it would export the screenshot to other directory, but instead this button uploads the screenshot to internet (imgur) and i don't know that until i clicked hyperlink in the window. Adding reminder about this feature looks nice to me (and others probably).

**Comment by TheKodeToad** [comment]
Since #618, 
![image](https://user-images.githubusercontent.com/57493648/227778581-f68eb790-7339-4afb-abc9-e46fb7f95fcd.png)
this is what you see (I'm pretty sure it's not in the stable version).
Do you think it should have more clarification in that case?

**Comment by F640** [comment]
> Since #618, ![image](https://user-images.githubusercontent.com/57493648/227778581-f68eb790-7339-4afb-abc9-e46fb7f95fcd.png) this is what you see (I'm pretty sure it's not in the stable version). Do you think it should have more clarification in that case?



>You are about to upload the selected screenshot to internet
Uploading to: imgur.com
Anyone that has the the link will able to see uploaded screenshot
Are you sure?

Probably changing to this one looks better as there is more information

Similar to upload log confirmation #618
![image](https://user-images.githubusercontent.com/57493648/207644656-195fdecf-f6b3-4e27-9ac8-34576844f61a.png)
