### ISSUE TITLE
Add more information to Java setup in onboarding

### ISSUE THREAD

**Issue by Poopooracoocoo** [PrismLauncher/PrismLauncher#952]
### Role

A new user

### Suggestion

I want the Java setup in the quick setup to tell me why I need it and where I can get it

### Benefit

In order to play Minecraft

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://user-images.githubusercontent.com/51363864/227897217-4005f5b1-3d4c-4c39-813a-35c6c262e04d.png)

If you select Finish without having selected a Java executable, the following message appears:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/51363864/227897197-fd3bab1d-2f61-4c9a-8f7d-447a20c621b2.png">

The info in this dialogue box could be present in the prior 'Java setup' screen. And a link to the Prism Launcher wiki would be great. https://prismlauncher.org/wiki/getting-started/installing-java/

**Comment by ThaBluNate** [comment]
...Do you want it to list reasons you need _**Java**_ to play Minecraft: _**Java**_ Edition??
I'm sorry? I don't think I got that right.

Anyways, you can get java from sources like adoptium.net

**Comment by Poopooracoocoo** [comment]
Yes. I see tons of users not know that you need to install Java for Prism Launcher. A lot of them are migrating from launchers that handle installing Java for them, so some explanation is needed. Please do not belittle people for not knowing. Thank you. 

I'm very aware that you can install it from Adoptium. Other users are not.
