### ISSUE TITLE
how to update prism launcher

### ISSUE THREAD

**Issue by inikishev** [PrismLauncher/PrismLauncher#955]
how to update prism launcher? Do i replace all existing files or do i delete them?

**Comment by Ryex** [comment]
Yes, unless your useing a portable version your instances and data are stored elsewhere.

If you are using a portable version then it is generally sufficient to extract all the files to the same place and overwrite the existing ones.

When updating from 5.x to 6.x portable release on windows it is nessacery to move your instances and settings file to a back up location, delete the remaining files and install prism again.
 Or if using the Normal not portable installer you must uninstall prism completely and then reinstall it. Your data will be safe

**Comment by alexmdev04** [comment]
would have been nice if the portable update method (v5.x to v6.x) was described in the changelog or download page because ive now just broke my launcher
