### ISSUE TITLE
Website 

### ISSUE THREAD

**Issue by elchupe123** [PrismLauncher/PrismLauncher#96]
### Role

I play minecraft in general

### Suggestion

A website to download this luncher

### Benefit

It would be easier to download Prism.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by GeefireMC** [comment]
the devs are working on getting downloads available to the wider public AFAIK. Builds are currently available through Github Actions.

**Comment by Ingen-ear** [comment]
Is it possible to get an estimate on when a launcher should be available? Within a week? Within a month? Sometime in the next 3 months? etc

**Comment by IThundxr** [comment]
The devs are working on getting a full release done cant give any etas but its known that its being worked on

**Comment by DioEgizio** [comment]
https://prismlauncher.org/
