### ISSUE TITLE
New column in mods list to indicate mod environments

### ISSUE THREAD

**Issue by ChrisLane** [PrismLauncher/PrismLauncher#962]
### Role

I play modded Minecraft using modpacks

### Suggestion

I would like a new column in the mods list that specifies whether each mod is client-only or client/server

### Benefit

This would allow me to more easily discover my client-only mods that can safely be updated without the instance becoming incompatible with servers

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

- I play on a modpack server which means that I must ensure that my mod versions stay compatible with those on the server.
- Client-side only mods will never have a server-side restriction on their version since they are not on the server.
    - As such, client-side mods can be updated freely without worrying about server-side compatibility.
- I would like a new column in the mods list that tells me which mods are client-side only so that I can update them.
- I would also be happy with a much more automated feature that can restrict updates to mods based on a server's mod versions but that sounds like it would be considerably more work.

**Comment by Ryex** [comment]
It's this even detectable from our end? Is there Metadata on a mod to indicate the client or server environment?

**Comment by ChrisLane** [comment]
I hadn't done any investigation into this to be honest but had assumed the mod provider websites or the jars themselves would have some metadata.

I've done a quick search and found that there's the [Get Mod](https://docs.curseforge.com/#get-mod) endpoint for the CurseForge API that returns a `gameVersions` property for each mod file e.g.
```json
        "gameVersions": [
          "Client",
          "1.19.2",
          "Forge",
          "Server"
        ]
```
I suspect this is what the [itzg/docker-minecraft-server](https://github.com/itzg/docker-minecraft-server#auto-curseforge-management) docker container uses to only download server mod files for curseforge modpacks.

I see also that the Modrinth API has `client_side` and `server_side` properties to indicate where a mod file belongs.

Additionally, it looks like Fabric mods have a `fabric.mod.json` in the root of their jar file that contains an `environment` property that indicates what side the mod is for.

**Comment by ChrisLane** [comment]
Thank you @Trial97! Looks great!
