### ISSUE TITLE
Quick Play support

### ISSUE THREAD

**Issue by Madis0** [PrismLauncher/PrismLauncher#975]
### Role

User

### Suggestion

Add an UI to instance settings to launch to a specific world/server

### Benefit

Modpacks, players who play on one server/world a lot

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

See https://www.minecraft.net/en-us/article/minecraft-snapshot-23w14a for details

**Comment by RaptaG** [comment]
It already exists for servers.

**Comment by 456dev** [comment]
the existing feature uses the old `--server localhost --port 25565` format, which was removed in 23w14a, replaced with new args:
`--quickPlaySingleplayer "New World"`
`--quickPlayMultiplayer "localhost:25565"`
`--quickPlayRealms "1234"`

also I would like to see support for a command line argument to launch into a world/server/realm, not just an instance like at the moment

**Comment by byquanton** [comment]
The system aroudn `MinecraftServerTarget` would need a rewrite.

**Comment by TheKodeToad** [comment]
Seems like to keep the server-joining functionality you'd just need to change https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/minecraft/MinecraftInstance.cpp#L567
Currently Minecraft does launch but ignores the old arguments
`Completely ignored arguments: [--server, localhost, --port, 25565]`

**Comment by RuiNtD** [comment]
They also added a `--quickPlayPath` argument to log joined worlds / servers / realm to a specified JSON file. It would be nice to be able to enable a Quick Join option per-instance (or globally?) that would both enable the logging and change the Play button to a Quick Play button (only on 1.20+!), popping up a menu prompting for you to select a world / server / realm or just launch Minecraft normally. BTW, the logging also includes info on the world / server / realm name, game mode, and last played time, so here's what I'm thinking in terms of UI:

![image](https://github.com/PrismLauncher/PrismLauncher/assets/1149870/e377adf4-3f16-481f-b484-ea49d52cb248)

The Set Default option would turn off the Quick Play option and change the instance settings to just that quick play setting (unless Launch Normally is selected).

**Comment by MenacingPerson** [comment]
Also can this be a dropdown or something instead of a simple text box? Thanks

**Comment by TheKodeToad** [comment]
> The system aroudn `MinecraftServerTarget` would need a rewrite.

(removed some things because I was confused)

I suppose it could become a union.

**Comment by whitebear60** [comment]
Any updates on this one? As a workaround for now I modified my Minecraft instance's `minecraftArguments` in json, but that feels kinda janky and not right...

**Comment by TomatechGames** [comment]
this might warrent its own issue request, but it would be good to just have a textbox to append minecraft arguments to the ones generated by prism in case a change like this happens in a future version

**Comment by TomatechGames** [comment]
> Any updates on this one? As a workaround for now I modified my Minecraft instance's `minecraftArguments` in json, but that feels kinda janky and not right...

which file contained the minecraftArguments variable?

**Comment by Fabian42** [comment]
Edit the profile/instance→Version→Minecraft→Edit, near the end. For me, that's `~/.local/share/PrismLauncher/instances/[name]/patches/net.minecraft.json`, line 450 out of 462.
