### ISSUE TITLE
Add datapack download button (from Modrinth)

### ISSUE THREAD

**Issue by Aras14HD** [PrismLauncher/PrismLauncher#976]
### Role

I use datapacks in multiple instances.

### Suggestion

I want a button to be added to the menu, that enables me to download datapacks from Modrinth, similar to the mod download menu.

### Benefit

It would make managing those a lot easier.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Other sources like Vanilla Tweaks would be nice too.

Edit: Removed unnecessary resource pack and shader mentions, as they are already covered.

**Comment by ghost** [comment]
You can download shaders and resourcepacks in Prism Launcher 7.0 dev now
You can download dev build from Actions page

**Comment by Aras14HD** [comment]
My mistake missing #725 and #153 for shaders and resource packs, datapacks still don't have a download button, neither in worlds nor in a non existent instance-global menu.

**Comment by TheKodeToad** [comment]
Superseded by #1863.
