### ISSUE TITLE
error -255 prismlauncher 6.3 flatpak

### ISSUE THREAD

**Issue by powerpuffboysz** [PrismLauncher/PrismLauncher#990]
### Operating System

Manjaro

### Version of Prism Launcher

Prismlauncher 6.3 flatpak

### Version of Qt

5.15.9 according to the flatpak

### Description of bug

playing minecraft 1.7.10 with forge 10.13.4.1614 and java 8 1.8.0_362. no mods installed. game crashes after about a minute of gameplay with error 255

### Steps to reproduce

play for a minute

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by powerpuffboysz** [comment]
[PrismLauncher-4.log](https://github.com/PrismLauncher/PrismLauncher/files/11214409/PrismLauncher-4.log)

**Comment by powerpuffboysz** [comment]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 4/12/23 6:14 AM
Description: Unexpected error

java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalGetSourcei(II)I
	at org.lwjgl.openal.AL10.nalGetSourcei(Native Method)
	at org.lwjgl.openal.AL10.alGetSourcei(AL10.java:853)
	at paulscode.sound.libraries.ChannelLWJGLOpenAL.playing(ChannelLWJGLOpenAL.java:651)
	at paulscode.sound.Source.playing(Source.java:1213)
	at net.minecraft.client.audio.SoundManager$SoundSystemStarterThread.playing(SoundManager.java:500)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:218)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:179)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2013)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.openal.AL10.nalGetSourcei(Native Method)
	at org.lwjgl.openal.AL10.alGetSourcei(AL10.java:853)
	at paulscode.sound.libraries.ChannelLWJGLOpenAL.playing(ChannelLWJGLOpenAL.java:651)
	at paulscode.sound.Source.playing(Source.java:1213)
	at net.minecraft.client.audio.SoundManager$SoundSystemStarterThread.playing(SoundManager.java:500)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:218)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:179)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Powerpuffboysz'/159, l='MpServer', x=5.68, y=64.62, z=92.83]]
	Chunk stats: MultiplayerChunkCache: 522, 522
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,88), Chunk: (at 8,4,8 in 0,5; contains blocks 0,0,80 to 15,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 247 game time, 247 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 92 total; [EntityZombie['Zombie'/2070, l='MpServer', x=82.50, y=14.00, z=33.50], EntityZombie['Zombie'/2071, l='MpServer', x=79.50, y=14.00, z=34.50], EntitySpider['Spider'/2078, l='MpServer', x=57.50, y=37.00, z=149.88], EntitySpider['Spider'/2082, l='MpServer', x=56.50, y=37.00, z=152.06], EntityCreeper['Creeper'/2088, l='MpServer', x=52.50, y=22.00, z=13.50], EntityCreeper['Creeper'/2089, l='MpServer', x=53.50, y=22.00, z=16.50], EntityMinecartChest['entity.MinecartChest.name'/90, l='MpServer', x=-68.50, y=24.50, z=32.50], EntityMinecartChest['entity.MinecartChest.name'/91, l='MpServer', x=-65.50, y=24.50, z=34.50], EntityMinecartChest['entity.MinecartChest.name'/92, l='MpServer', x=-60.50, y=24.50, z=34.50], EntityMinecartChest['entity.MinecartChest.name'/93, l='MpServer', x=-57.50, y=27.50, z=71.50], EntitySheep['Sheep'/94, l='MpServer', x=-29.50, y=64.00, z=68.78], EntitySheep['Sheep'/95, l='MpServer', x=-29.22, y=64.00, z=70.50], EntitySheep['Sheep'/96, l='MpServer', x=-30.81, y=64.00, z=70.50], EntitySheep['Sheep'/97, l='MpServer', x=-29.50, y=64.00, z=67.19], EntityItem['item.item.seeds'/103, l='MpServer', x=-2.19, y=23.13, z=94.88], EntityZombie['Zombie'/160, l='MpServer', x=2.50, y=23.00, z=78.50], EntityCreeper['Creeper'/162, l='MpServer', x=-19.44, y=40.49, z=91.51], EntityClientPlayerMP['Powerpuffboysz'/159, l='MpServer', x=5.68, y=64.62, z=92.83], EntityBat['Bat'/230, l='MpServer', x=8.54, y=12.84, z=122.15], EntitySquid['Squid'/235, l='MpServer', x=-21.28, y=60.38, z=30.03], EntitySquid['Squid'/236, l='MpServer', x=-24.88, y=59.81, z=28.38], EntitySquid['Squid'/237, l='MpServer', x=-17.50, y=60.00, z=29.50], EntitySquid['Squid'/238, l='MpServer', x=-20.81, y=57.84, z=27.44], EntitySquid['Squid'/242, l='MpServer', x=-27.59, y=60.38, z=26.63], EntityBat['Bat'/280, l='MpServer', x=54.75, y=38.54, z=136.05], EntityBat['Bat'/281, l='MpServer', x=60.43, y=39.52, z=131.74], EntityBat['Bat'/282, l='MpServer', x=54.72, y=40.10, z=134.97], EntityBat['Bat'/283, l='MpServer', x=61.77, y=40.00, z=131.50], EntitySpider['Spider'/317, l='MpServer', x=87.66, y=35.00, z=41.44], EntitySkeleton['Skeleton'/358, l='MpServer', x=22.50, y=13.00, z=65.50], EntitySkeleton['Skeleton'/359, l='MpServer', x=19.50, y=13.00, z=64.50], EntityBat['Bat'/392, l='MpServer', x=47.56, y=38.71, z=43.16], EntityBat['Bat'/393, l='MpServer', x=47.52, y=39.63, z=38.65], EntityBat['Bat'/412, l='MpServer', x=74.31, y=22.24, z=44.61], EntityBat['Bat'/425, l='MpServer', x=12.80, y=22.89, z=103.44], EntityBat['Bat'/426, l='MpServer', x=-0.03, y=23.56, z=94.67], EntityCreeper['Creeper'/488, l='MpServer', x=75.50, y=29.00, z=51.50], EntityCreeper['Creeper'/489, l='MpServer', x=51.50, y=24.00, z=54.50], EntitySkeleton['Skeleton'/490, l='MpServer', x=43.50, y=24.00, z=49.50], EntityBat['Bat'/643, l='MpServer', x=-11.17, y=33.10, z=136.23], EntityBat['Bat'/644, l='MpServer', x=-7.97, y=29.04, z=130.77], EntityBat['Bat'/653, l='MpServer', x=30.04, y=24.79, z=50.74], EntityBat['Bat'/656, l='MpServer', x=34.75, y=24.81, z=57.49], EntityBat['Bat'/657, l='MpServer', x=42.53, y=24.62, z=48.67], EntityEnderman['Enderman'/768, l='MpServer', x=-29.00, y=26.00, z=106.88], EntitySpider['Spider'/769, l='MpServer', x=-15.78, y=26.00, z=102.97], EntityCreeper['Creeper'/823, l='MpServer', x=59.50, y=20.00, z=106.50], EntityZombie['Zombie'/846, l='MpServer', x=-9.50, y=18.00, z=115.50], EntityCreeper['Creeper'/847, l='MpServer', x=-9.50, y=18.00, z=114.50], EntitySpider['Spider'/903, l='MpServer', x=4.72, y=24.00, z=99.59], EntityEnderman['Enderman'/923, l='MpServer', x=-61.34, y=44.00, z=170.50], EntityFallingBlock['Falling Block'/5062, l='MpServer', x=64.50, y=30.30, z=200.50], EntitySpider['Spider'/1014, l='MpServer', x=3.53, y=27.00, z=126.28], EntitySkeleton['Skeleton'/1077, l='MpServer', x=73.50, y=50.00, z=79.50], EntityFallingBlock['Falling Block'/3146, l='MpServer', x=66.50, y=30.17, z=200.50], EntityFallingBlock['Falling Block'/3148, l='MpServer', x=63.50, y=30.17, z=200.50], EntityFallingBlock['Falling Block'/3150, l='MpServer', x=64.50, y=30.17, z=200.50], EntityFallingBlock['Falling Block'/3155, l='MpServer', x=63.50, y=30.17, z=199.50], EntityZombie['Zombie'/1125, l='MpServer', x=-24.01, y=18.00, z=132.50], EntityZombie['Zombie'/1126, l='MpServer', x=-28.50, y=13.00, z=125.50], EntityZombie['Zombie'/1173, l='MpServer', x=-29.50, y=39.00, z=63.50], EntityCreeper['Creeper'/1225, l='MpServer', x=-38.44, y=40.00, z=99.91], EntitySkeleton['Skeleton'/1227, l='MpServer', x=-22.50, y=46.00, z=108.50], EntityCreeper['Creeper'/1272, l='MpServer', x=36.50, y=18.00, z=73.50], EntityCreeper['Creeper'/1333, l='MpServer', x=-24.69, y=19.00, z=113.47], EntitySkeleton['Skeleton'/1353, l='MpServer', x=72.50, y=25.00, z=89.88], EntitySpider['Spider'/1358, l='MpServer', x=42.66, y=39.00, z=169.16], EntityZombie['Zombie'/1360, l='MpServer', x=47.84, y=39.00, z=163.69], EntitySkeleton['Skeleton'/1408, l='MpServer', x=68.50, y=17.00, z=53.50], EntitySkeleton['Skeleton'/1409, l='MpServer', x=69.50, y=17.00, z=51.50], EntityCreeper['Creeper'/1410, l='MpServer', x=73.50, y=17.00, z=86.50], EntitySkeleton['Skeleton'/1419, l='MpServer', x=-12.84, y=22.00, z=117.31], EntitySkeleton['Skeleton'/1471, l='MpServer', x=-41.50, y=20.00, z=112.50], EntityZombie['Zombie'/1506, l='MpServer', x=50.06, y=40.00, z=157.59], EntitySkeleton['Skeleton'/1615, l='MpServer', x=77.50, y=31.00, z=168.50], EntityCreeper['Creeper'/1694, l='MpServer', x=51.13, y=40.00, z=154.78], EntitySpider['Spider'/1695, l='MpServer', x=44.13, y=39.00, z=166.00], EntitySpider['Spider'/1696, l='MpServer', x=48.72, y=39.00, z=161.84], EntitySkeleton['Skeleton'/1711, l='MpServer', x=80.50, y=30.00, z=71.50], EntitySkeleton['Skeleton'/1759, l='MpServer', x=70.50, y=30.00, z=153.50], EntityEnderman['Enderman'/1760, l='MpServer', x=70.50, y=30.00, z=150.50], EntityZombie['Zombie'/1846, l='MpServer', x=67.50, y=15.00, z=43.50], EntityZombie['Zombie'/1847, l='MpServer', x=67.50, y=15.00, z=42.50], EntitySkeleton['Skeleton'/1848, l='MpServer', x=68.50, y=15.00, z=42.50], EntitySkeleton['Skeleton'/1855, l='MpServer', x=-45.63, y=20.00, z=92.89], EntitySkeleton['Skeleton'/1856, l='MpServer', x=-50.34, y=20.00, z=86.72], EntitySkeleton['Skeleton'/1885, l='MpServer', x=4.25, y=17.00, z=110.63], EntitySkeleton['Skeleton'/1886, l='MpServer', x=9.09, y=18.00, z=109.50], EntitySkeleton['Skeleton'/1887, l='MpServer', x=3.50, y=17.00, z=108.50], EntitySkeleton['Skeleton'/1888, l='MpServer', x=6.94, y=16.00, z=112.50], EntityEnderman['Enderman'/1889, l='MpServer', x=5.50, y=17.00, z=108.50], EntityZombie['Zombie'/2000, l='MpServer', x=-41.50, y=27.00, z=78.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 6.1.23-1-MANJARO
	Java Version: 1.8.0_362, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 458504904 bytes (437 MB) / 1532493824 bytes (1461 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 530.41.03' Renderer: 'NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2'
	Launched Version: 1.7.10
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 530.41.03, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by WORMSTweaker** [comment]
`java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalGetSourcei(II)I`
Is openAL installed on your system and does the Flatpak package has access to it?

**Comment by powerpuffboysz** [comment]
Openal version 1.23.0-2. i set it to use system level openal in the workarounds tab and that seems to stop the game from crashing but now i have no sound. given it's under "workarounds" i'm assuming i shouldn't use this as a long term fix.

**Comment by WORMSTweaker** [comment]
Looking at the [Flatpak documentation](https://docs.flatpak.org/en/latest/sandbox-permissions.html#standard-permissions), the `--socket=` argument or the `--filesystem=` argument might be your best bet

Using the system OpenAL might be the best though, even if it's a workaround of the launcher. It can also be that the version of OpenAL the launcher downloaded for the Minecraft is not correct for the Java version you're using.

In any case, issue closed?

**Comment by powerpuffboysz** [comment]
so a development has been made. apparently version minecraft 1.7.10 when using forge doesnt like the default bundled version of lwgl 2. i switched to version 2.9.0 and the game seems to be happy with it. i have sound and a crashless game so i guess case closed? maybe put this somewhere for other weird edge case users like me who prefer to play outdated versions who may run into similar issues?
