### ISSUE TITLE
Incompatibility with Arch Linux Qt 6

### ISSUE THREAD

**Issue by skepy1337** [PrismLauncher/PrismLauncher#991]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.3-1

### Version of Qt

Qt 6.5.0-3

### Description of bug

I cannot open Prism Launcher at all.

When started in the terminal, I get the following output:

warning: direct reference to protected function `_ZNK19QStyledItemDelegate15initStyleOptionEP20QStyleOptionViewItemRK11QModelIndex' in `/usr/lib/libQt6Widgets.so.6' may break pointer equality
prismlauncher: _ZNK19QStyledItemDelegate15initStyleOptionEP20QStyleOptionViewItemRK11QModelIndex: /usr/lib/libQt6Widgets.so.6: error due to GNU_PROPERTY_1_NEEDED_INDIRECT_EXTERN_ACCESS

### Steps to reproduce

Try to start the launcher.

### Suspected cause

There was a qt6 update yesterday that might have caused it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Is this also happening with our development builds on your distro?

Grab `PrismLauncher-Linux-Qt6-95842ee-Debug` from here, extract it and try to run the `PrismLauncher` script in there: https://github.com/PrismLauncher/PrismLauncher/actions/runs/4646923411

**Comment by dqnk** [comment]
Yes, this also happens with the development build, but only QT6

**Comment by Scrumplex** [comment]
Well, at the end, this is an ABI incompatibility between Qt that's used in our CI and Qt that's built by Arch Linux

**Comment by WORMSTweaker** [comment]
Can confirm, Qt6 update changed something that broke Prism, switching back to the Qt5 version of the launcher works as a temporary solution

**Comment by Elagoht** [comment]
For now, until the qt6 client updated, you can still use qt5 client.

**Comment by ghost** [comment]
@WORMSTweaker  How do we use the QT5 version?

**Comment by skepy1337** [comment]
> @WORMSTweaker  How do we use the QT5 version?

If you're on archlinux, install prismlauncher-qt5-bin from the AUR

**Comment by Guanran928** [comment]
Can confirm
Using Arch Linux and prismlauncher-bin
Switching to prismlauncher-qt5-bin fixed this problem

**Comment by SangeloDev** [comment]
Happened to me as well, can confirm that the qt5-bin version works fine as a workaround

**Comment by MightyPiggie** [comment]
You can use qt6. I had the same problem. I was on version 6.4.3-1. Updated to 6.5.0-1 and had the same problem. After downgrading I could launch it again. I am not sure but I think it has to do with [this commit](https://github.com/archlinux/svntogit-packages/commit/395c189970fe5b20e7f84ecd60a3bf57c34ac7d9)

Again I could also be completely wrong.

**Comment by Scrumplex** [comment]
> I am not sure but I think it has to do with [this commit](https://github.com/archlinux/svntogit-packages/commit/395c189970fe5b20e7f84ecd60a3bf57c34ac7d9)

Seems like that's the one.

**Comment by DownloadableFox** [comment]
Having this exact issue in ArchLinux.
```sh
warning: direct reference to protected function `_ZNK19QStyledItemDelegate15initStyleOptionEP20QStyleOptionViewItemRK11QModelIndex' in `/usr/lib/libQt6Widgets.so.6' may break pointer equality
prismlauncher: _ZNK19QStyledItemDelegate15initStyleOptionEP20QStyleOptionViewItemRK11QModelIndex: /usr/lib/libQt6Widgets.so.6: error due to GNU_PROPERTY_1_NEEDED_INDIRECT_EXTERN_ACCESS
```

Can also confirm that switching to  `prismlauncher-qt5-bin` fixed my issues.

**Comment by WaviestBalloon** [comment]
I can also also also confirm that switching to `prismlauncher-qt5-bin` has resolved the issue on Arch.

**Comment by Beethoven-n** [comment]
switching to `prismlauncher-qt5-bin` doesn't work on my machine!
i get this error, even after downgrading qt5-base and outright rebuilding qt5-styleplugins:
```Cannot mix incompatible Qt library (5.15.9) with this library (5.15.8)```
sometimes it just core dumps

**Comment by Elagoht** [comment]
> switching to `prismlauncher-qt5-bin` doesn't work on my machine!
> 
> i get this error, even after downgrading qt5-base and outright rebuilding qt5-styleplugins:
> 
> ```Cannot mix incompatible Qt library (5.15.9) with this library (5.15.8)```
> 
> sometimes it just core dumps

Your issue is not related to this package. Remove qt5-styleplugins and be sure you deleted the cache files and re compile qt5-styleplugins.

**Comment by jwaxy** [comment]
Have the exact issue

**Comment by famellad** [comment]
Updated Arch Linux today and I am experiencing this very same issue, switching back to the qt version as per @skep1337 's instructions works flawlessly

**Comment by Scrumplex** [comment]
While the Qt 5 version of Prism Launcher receives the same amount of support as the Qt 6 version, this won't be the case forever.

**Comment by MightyPiggie** [comment]
> While the Qt 5 version of Prism Launcher receives the same amount of support as the Qt 6 version, this won't be the case forever.

Yeah, but I don't think it's prism launchers fault, since something at qt6 broke it. I will take a look today at what exactly made it break and see if there's a fix for it. Otherwise I'll open a issue at qt6.

**Comment by txtsd** [comment]
@Scrumplex Should we build Arch binaries in an Arch container? I can set it up.

**Comment by Scrumplex** [comment]
> @Scrumplex Should we build Arch binaries in an Arch container? I can set it up.

Dunno if we wanna do that. We could also download binary packages from chaotic aur and repackage those as the -bin package

**Comment by txtsd** [comment]
Using a downstream build as an official source seems a little roundabout :sweat_smile: 

What's wrong with building it ourselves? GHA lets us do containers without invoking docker/podman etc.

**Comment by Scrumplex** [comment]
> What's wrong with building it ourselves?

Well, why just Arch? I mean, our binaries only work on other systems because of luck. The proper way to deal with this in the future would be to also ship our own Qt libraries with Prism Launcher.

We might be able to bring back what MultiMC called a full bundle here. Not sure how feasible it is, though. People should just use packages that were built for their distro.

**Comment by txtsd** [comment]
> > What's wrong with building it ourselves?
> 
> Well, why just Arch? I mean, our binaries only work on other systems because of luck. The proper way to deal with this in the future would be to also ship our own Qt libraries with Prism Launcher.
> 
> We might be able to bring back what MultiMC called a full bundle here. Not sure how feasible it is, though. People should just use packages that were built for their distro.

The full bundle thing was packaging Qt and required plugins into the deployed directory structure. We could statically link Qt instead. Less of a hassle if it's just one executable instead of couple of directories for runtime and plugins.

EDIT: Downside is bloated build sizes either way. Arch container seems like the best solution atm.

**Comment by DioEgizio** [comment]
> > What's wrong with building it ourselves?
> 
> Well, why just Arch? I mean, our binaries only work on other systems because of luck. The proper way to deal with this in the future would be to also ship our own Qt libraries with Prism Launcher.
> 
> We might be able to bring back what MultiMC called a full bundle here. Not sure how feasible it is, though. People should just use packages that were built for their distro.

Not really feasible with themes and with openssl versions. I think the problem here is just arch, it works everywhere else fine

**Comment by jwaxy** [comment]
When I used the offical binaries it didnt work but when I compiled it myself it ran.

**Comment by jwaxy** [comment]
qt5 already works btw

**Comment by InsaneJ** [comment]
Manjaro updated and PrismLauncher no longer works with the same GNU_PROPERTY_1_NEEDED_INDIRECT_EXTERN_ACCESS error posted above.

I'm using the prismlauncher-qt5-bin package as a workaround for now.

**Comment by ivanpu** [comment]
I've always used the `prismlauncher` package (not -bin), and it works fine with qt6.
Although I do have to rebuild it after some updates (most likely of qt, as I think about it now).

**Comment by 0x8008** [comment]
Still an issue.

**Comment by Guanran928** [comment]
Only the -bin version is broken, manually built non-bin versions works for me. (both `prismlauncher{,-git}`)
![image](https://github.com/PrismLauncher/PrismLauncher/assets/68757440/ac5d4946-111d-46f3-bd0f-988983525b78)

**Comment by Guanran928** [comment]
Another workaround if you are too lazy to build it yourself: use the Flatpak'ed version

**Comment by 0x8008** [comment]
I know that the -git version works. It's not a workaround though, I have a laptop on which compiling Prism is a solid 10+ minute job and doing it every time an update drops is just ridiculous. Bin build should work, it's pathetic that this has been an issue since April and yet nothing is being done about it. Guess the developers think adding mental issue banners into the launcher is of higher priority...

**Comment by Scrumplex** [comment]
> Bin build should work, it's pathetic that this has been an issue since April and yet nothing is being done about it. 

1. Bin builds are at best a hack. Basically every package in the official repos is built from source. The fact that the Prism Launcher binary builds work is pure luck, as we almost fully rely on system libraries.

2. Arch Linux is the only distribution that has opted to enable `FEATURE_no_direct_extern_access` for their Qt 6 builds. We would have to build a binary package specifically for Arch Linux's Qt 6 build. It is not hard to do, but we don't really want to maintain binary packages for different distributions.

Possible solutions:

1. Use an alternative package. Chaotic-AUR, Flatpak and Nixpkgs are all available on Arch Linux and provide binary builds of Prism Launcher.

2. Use `prismlauncher-qt5-bin`

4. Ask Arch Linux TUs/developers if they can adopt `prismlauncher` into Arch repos. It has been in the top 10 packages of the AUR (by popularity score) for a while. It is simple to package and usually requires minimal changes between versions.

Just look how many binary distributions of Prism Launcher exist out there: https://repology.org/project/prismlauncher/versions
The only real outlier here is Arch Linux (and Gentoo, obviously).

Edit: I am also just going to block you from this organization for your comment about "mental issue banners"

**Comment by Ai-Kiwi** [comment]
same issue here, running arch linux with hyprland (wayland)

**Comment by IGN-Styly** [comment]
Its an issue with the build. Will Fix in AUR

**Comment by Trial97** [comment]
Based on: https://github.com/PrismLauncher/PrismLauncher/issues/2087 the qt5 binary are also broken on arch

**Comment by ewof** [comment]
idk if i should make a new issue or necro but this still happen
using qt5 bin doesnt work either (i dont have styleplugins)
also i cant compile any of the git versions without `sed -i "s/7/8/g" libraries/{launcher,javacheck}/CMakeLists.txt` in prepare()

**Comment by getchoo** [comment]
Last necro: Qt 6 binary builds of Prism are now available in Arch's [official repos](https://archlinux.org/packages/extra-testing/x86_64/prismlauncher/) 🎉

**Comment by HappyGoFishing** [comment]
last necro :)

**Comment by HurricanePootis** [comment]
Ping me with glorpies

**Comment by HurricanePootis** [comment]
> Ping me with glorpies
@getchoo

**Comment by ewe2** [comment]
Could this also be my issue #3422?
