### ISSUE TITLE
Auto-detection of the correct Java version depending on the Minecraft version

### ISSUE THREAD

**Issue by tomodachi94** [PrismLauncher/PrismLauncher#997]
### Role

I play modded Minecraft with multiple modpacks that use very different Minecraft versions (1.6, 1.12, 1.16, etc.)

### Suggestion

The correct Java version should be automatically selected depending on the Minecraft version.

### Benefit

This would be very useful for people who share my role that experiment with lots of modpacks. It's quite annoying to have to manually configure the Java version.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

We already have facilities for finding Java installs through the `Auto-detect` button in settings. If the user has the correct version of Java installed but it is not selected, we should prompt them to use the correct version. This feature should be toggleable per-version or globally.

This might require some extra metadata to be included, something like this:

```json
{
    "1.12.*": "8.*",
    "1.16.*": "14.*"
}
```

The key is a wildcard string that matches the Minecraft version, and the value is a wildcard string that matches the Java version. We could also use regex if necessary, though that would require a bit of string escaping.

**Comment by hadeedsarfaraz** [comment]
Perhaps it would be better to be able create a custom version range for a range of MC versions with a subset for , as i use 2 java 8's, one for a older forge version (jdk8u312)and one for more recent forge packs(jdk8u362). Maybe have a list for each major version of acceptable jdk's with the ability to have multiple jdk's available in a dropdown?

**Comment by Poopooracoocoo** [comment]
Also see #335
